### ISSUE TITLE
WebSocket going on an infinite loop

### ISSUE THREAD

**Issue by jschmid** [couchbase/couchbase-lite-ios#1003]
Hi there,

We just found a very strange behaviour with the Couchbase Lite replication.
You can find a log here: https://gist.github.com/jschmid/521be17b6395de9e8fcf

We currently use CBL 1.1.0. The app has two replications (push/pull) with the `continuous` flag set to `true`. Our Sync gateway is hosted behind a AWS load balancer.

This only happens on the Simulator, and we have never seen this on a device. 

I feel really clueless here. Any chance you've had this before ? Thanks

**Comment by snej** [comment]
Logs are an endless sequence, several times a millisecond, of:
```
11:10:59.112‖ WS: TRACE: -[CBL_WebSocket socket:didReadData:withTag:]
11:10:59.112‖ WS: TRACE: -[CBL_WebSocket socket:didReadData:withTag:]
11:10:59.112‖ WS: TRACE: -[CBL_WebSocket socket:didReadData:withTag:]
11:10:59.112‖ WS: TRACE: -[CBL_WebSocket didReceiveFrame:type:]
11:10:59.112‖ WS: TRACE: -[CBL_WebSocket didReceiveMessage:]
11:10:59.112‖ ChangeTrackerVerbose: CBLWebSocketChangeTracker[0x7fb31b1565e0 myproject]: Got a message: 
```
That's very weird: it's receiving a constant stream of empty WebSocket messages. I assume that these are being sent by the Sync Gateway. Can you verify that, maybe by packet-sniffing or at least looking at the volume of TCP traffic from SG or the CPU usage? If so, that would imply this is an SG bug.

**Comment by snej** [comment]
Is there any chance you've accidentally set the `heartbeat` property of the replication to a tiny value? (Its units are milliseconds.)

**Comment by jschmid** [comment]
We did not change the `heartbeat` property.

After many attempts, we are not able to reproduce this bug. We did capture the traffic in the SG server directly. By looking at the logs from the mobile app and the tcp dumps, we can see that every 300 seconds, the SG sends an empty packet to the client. 

On the mobile side, it translates to this:

> 14:40:16.094‖ WS: TRACE: -[CBL_WebSocket socket:didReadData:withTag:]
> 14:40:16.094‖ WS: TRACE: -[CBL_WebSocket socket:didReadData:withTag:]
> 14:40:16.094‖ WS: TRACE: -[CBL_WebSocket socket:didReadData:withTag:]
> 14:40:16.094‖ WS: TRACE: -[CBL_WebSocket didReceiveFrame:type:]
> 14:40:16.094‖ WS: TRACE: -[CBL_WebSocket didReceiveMessage:]
> 14:40:16.094‖ ChangeTrackerVerbose: CBLWebSocketChangeTracker[0x7ffbb2d6c200 reach]: Got a message: 
> 14:45:16.097‖ WS: TRACE: -[CBL_WebSocket socket:didReadData:withTag:]
> 14:45:16.097‖ WS: TRACE: -[CBL_WebSocket socket:didReadData:withTag:]
> 14:45:16.097‖ WS: TRACE: -[CBL_WebSocket socket:didReadData:withTag:]
> 14:45:16.097‖ WS: TRACE: -[CBL_WebSocket didReceiveFrame:type:]
> 14:45:16.097‖ WS: TRACE: -[CBL_WebSocket didReceiveMessage:]
> 14:45:16.097‖ ChangeTrackerVerbose: CBLWebSocketChangeTracker[0x7ffbb2d6c200 reach]: Got a message: 

Where as usually there is at least a `[]` as content:

> 14:35:15.986‖ WS: TRACE: -[CBL_WebSocket sendFrame:type:tag:]
> 14:35:15.986‖ WS: TRACE: -[CBL_WebSocket isHungry]
> 14:35:15.986‖ WS: TRACE: -[CBL_WebSocket socket:didWriteDataWithTag:]
> 14:35:15.986‖ WS: TRACE: -[CBL_WebSocket isHungry]
> 14:35:16.090‖ WS: TRACE: -[CBL_WebSocket socket:didReadData:withTag:]
> 14:35:16.090‖ WS: TRACE: -[CBL_WebSocket socket:didReadData:withTag:]
> 14:35:16.090‖ WS: TRACE: -[CBL_WebSocket socket:didReadData:withTag:]
> 14:35:16.090‖ WS: TRACE: -[CBL_WebSocket didReceiveFrame:type:]
> 14:35:16.090‖ WS: TRACE: -[CBL_WebSocket didReceiveMessage:]
> 14:35:16.090‖ ChangeTrackerVerbose: CBLWebSocketChangeTracker[0x7ffbb2d6c200 reach]: Got a message: []
> 14:35:16.091‖ ChangeTrackerVerbose: CBLWebSocketChangeTracker[0x7ffbb2d6c200 reach]: read 2 bytes

On the server side, we can clearly see those packets also. I will send you the **.pcap* file by email. As it captured everything on the server, we prefer not to publish it here. 

What's concerning is that the loop I showed above happened to two guys, on two different machine, with two different internet connection. It's not an isolated bug (even though we fail to reproduce it...)

Any idea how to proceed to fix this? Thanks Jens

**Comment by jschmid** [comment]
I don't know if it is worth anything, but we have 3 SG nodes with 3 Couchbase server nodes behind the AWS load balancer.

**Comment by snej** [comment]
The empty message is normal. A `[]` message is sent at the end of the changes so far, as a signal to the client that it's caught up with the current state of the server. After that, empty messages are sent as a heartbeat every few minutes to keep intermediaries like AWS from thinking the socket is idle and closing it.

**Comment by jschmid** [comment]
So I guess we're back to square one. 

I'll get back to this issue if we encounter it again.

**Comment by snej** [comment]
I think it'd be better to file an issue against Sync Gateway, since the problem seems to be occurring over there.
