### ISSUE TITLE
CBListener  setAnonymousSSLIdentityWithLabel  - Assertion failure in findIdentity()

### ISSUE THREAD

**Issue by yonahforst** [couchbase/couchbase-lite-ios#1004]
Using the build from here: http://latestbuilds.hq.couchbase.com/couchbase-lite-ios/0.0.0/ios/0.0.0-525/ CBListener setAnonymousSSLIdentityWithLabel occasionally causes the following crash:

```
2015-12-14 16:59:49.280 proximator[4532:2539021] Logging CBLListener, CBLListenerVerbose, Sync, SyncVerbose to NSLog
2015-12-14 16:59:49.280 proximator[4532:2539021] ### Couchbase Lite 0.0.0 (build 525); git commit ad82b1b94887df639034baf3dfaa1812508fd60a ###
2015-12-14 16:59:49:278 proximator[4532:2539021] Hello World
2015-12-14 16:59:49.801 proximator[4532:2539021] *** ASSERTION FAILED: Unexpected value for err: -34018 (expected -25300)
2015-12-14 16:59:49.801 proximator[4532:2539021] *** Assertion failure in findIdentity(), /Users/jenkins/jenkins/workspace/couchbase-lite-ios-builds/couchbase-lite-ios/vendor/MYUtilities/MYAnonymousIdentity.m:290
```

here is how I'm setting up the listener:

``` objc
if (!self.listener)
   self.listener = [[CBLListener alloc] initWithManager:p2pPort];
self.listener.requiresAuth = YES;
[self.listener setPasswords:@{p2pUsername : p2pPassword}];
[self.listener setAnonymousSSLIdentityWithLabel:@"proximatorv2" error:&error];
```

I'm not able to reliably reproduce the error; it only happens every few builds.

Tried upgrading to build 557 but then it crashed with something like 'invalid compaction option for forestDB'

**Comment by snej** [comment]
That's an unexpected error returned from `SecItemCopyMatching` (at MYAnonymousIdentity.m:290). It also seems to be an undocumented error; http://osstatus.com doesn't know about it.

What's the OS version this is happening on?

**Comment by joshblour** [comment]
9.1

**Comment by brendand** [comment]
I've had this issue also in iOS 9.2. I believe it may happen only when running from Xcode in development though. 

It's a well known error on the Apple dev forums and has existed for a long time. Although the -25300 may be new in recent OS updates.

https://forums.developer.apple.com/thread/4743

**Comment by snej** [comment]
@joshblour: Do you only get this error when running from Xcode?

**Comment by joshblour** [comment]
Yes, only when running from Xcode

**Comment by snej** [comment]
Sounds like an Apple bug, something in the iOS Simulator. Doesn't look like anything we could work around, sorry!

**Comment by brendand** [comment]
I know you closed this, but just wanted to say that It also happens quite frequently when running on device.

**Comment by zgramana** [comment]
Worth a second look.

**Comment by snej** [comment]
I will ask about this on Apple mailing lists/forums and see if I can find more info about it.

**Comment by jayahariv** [comment]
Closing 1.x issue!
