### ISSUE TITLE
Replication fails without starting on wifi if network depends on a proxy

### ISSUE THREAD

**Issue by andyjohns** [couchbase/couchbase-lite-ios#1005]
If on a wifi connection within a network that uses a proxy, replication never really starts because it's using 
SCNetworkReachabilityCreateWithName under the covers to verify the host is reachable before attempting replication. Since SCNetworkReachabilityCreateWithName does not respect http proxy settings (see: http://stackoverflow.com/questions/7286329/does-scnetworkreachability-respect-http-proxy-settings for a discussion of this issue) this means replication within a network that uses a proxy never works.
If however, instead of SCNetworkReachabilityCreateWithName, the code used SCNetworkReachabilityCreateWithAddress with zero address (like Apple's Reachability reachabilityForInternetConnection sample code) the existence of an internet connection could be verified without the specific host check. If then the network connection failed you could examine the failure reason to determine it was because the host could not be reached.

Log snippet:
16:15:26.960‖ Sync: CBL_Puller[https://917xxx.run.aws-usw02-pr.myserver.com/pg/data/pm]: Reachability state = <917530.run.aws-usw02-pr.ice.predix.io>:unreachable (00), suspended=0
16:15:26.960‖ Sync: CBL_Puller[https://917xxx.run.aws-usw02-pr.myserver.com/pg/data/pm]: Going offline
16:15:26.960‖ Sync: Stopping 1 remote requests
16:15:26.961‖ Sync: CBL_Puller[https://917xxx.run.aws-usw02-pr.myserver.com/pg/data/pm]: Error fetching last sequence: The operation couldn’t be completed. (NSURLErrorDomain error -999.)

**Comment by snej** [comment]
@pasin did a bunch of work on this earlier; see #536. It appears the don't-trust-Reachability mode isn't enabled by default (I think there are still some problems with it) but you can opt into it by setting an option. See the instructions in Pasin's comment from 3/25.

**Comment by pasin** [comment]
@andyjohns our current reachability logic is testing the reachability to the host not the internet connection. I will need to check if there is a way to get around the proxy or not. Meanwhile, as commented by @snej, you could ignore the offline status from the reachability by setting the custom properties to your replicator as below (Make sure you don't set the network option):

```
replicator.customProperties = @{ @"trust_reachability" : @(NO) };
```

**Comment by pasin** [comment]
@andyjohns one quick question, is your app a Mac app or an iOS app?

**Comment by pasin** [comment]
@snej we didn't have `don't-trust-Reachability` mode on by default as the current reachability check seems to be working for most cases (by that time, we got only #536, and that is for OSX). Also with #536, we were not certain about the root cause of the issue so we kind of wait and see.

**Comment by andyjohns** [comment]
Hi @pasin. 
This is for an iOS app. The "trust_reachability" workaround did work. The issue, as I understand it looking at the CBL code is the reachability check is very similar to the Apple Reachability sample where SCNetworkReachabilityCreateWithName is used to determine if the host is reachable. This technique uses a low-level TCP/IP validation to access the host, which does not recognize HTTP proxies. Because of this, in my own code, I gone to using SCNetworkReachabilityCreateWithAddress to verify general internet connectivity, then handle any errors to a specific host when I make the network call. Perhaps something similar can be done in a future release of CBL.

For now however, the "trust_reachability" workaround is our solution.

Thanks!

**Comment by pasin** [comment]
@andyjohns, thanks for suggestion. We will look into this.

**Comment by hermanccw** [comment]
@andyjohns @pasin @snej put this workaround in production and it actually caused more problem for us.

Don't have time to write up a test for this, here are the steps to reproduce

1.  open our application which is running with push and pull continuous replication
2.  minimize our app (at the point the app is at background and has *not* been shut down by the OS yet)
3.  update a document on the datastore (for us it is couchdb), this cause our server to send a remote notification to the phone (don't think this affect anything)
4.  switch the phone's connection from wifi to cellular or vice versa
5.  open the app again and do not see the update come in.  update only comes in after the app is restarted manually.

**Comment by pasin** [comment]
Can you enable 'Sync' and 'SyncVerbose' logging and share the log messages?

**Comment by snej** [comment]
I have a pull request that I _think_ will fix this. (See above.) I'm not sure because I don't currently have access to a network that requires a proxy, and I can't mess with the settings of my LAN (because it's not my LAN; I'm away from the office, staying at someone's house for a week.)

It would be great if @andyjohns or anyone who deals with proxies could test this commit.
