### ISSUE TITLE
MYUtilites function beginBackgroundTaskNamed: crash when app goes to background twice while replicating

### ISSUE THREAD

**Issue by Magnat12** [couchbase/couchbase-lite-ios#1006]
Assertion failed in beginBackgroundTaskNamed: when app goes to background twice while replicating. 

You said: 

> *_bgTask should never already be valid when -beginBackgroundTaskNamed: is called.*

But it is crashed. I attached screenshot. Maybe it is because I also use background task in my app. Can beginBackgroundTaskWithExpirationHandler

[Link to pull request](https://github.com/snej/MYUtilities/pull/12)

**Comment by snej** [comment]
@Magnat12, could you try out the patch in PR #1108 and let me know if it fixes your problem?
