### ISSUE TITLE
Support N1QL

### ISSUE THREAD

**Issue by joeljeske** [couchbase/couchbase-lite-ios#1007]
Will N1QL make its way down to CBL? It would be a more complete ecosystem if I could use the same tools / querying on the device as on the server.

**Comment by snej** [comment]
Maybe eventually, but not in the near future. It's written in Go and it's designed to talk to the Couchbase Server secondary-index server, so would have to be re-implemented for mobile use, which would be quite a big job.

**Comment by joeljeske** [comment]
Ok cool, that makes sense. Just getting a feel for project's direction and priorities.

**Comment by paishin** [comment]
Any updates on this?
I think we really need this feature

**Comment by snej** [comment]
This would be a long way off, if it ever happens. See my comment above — both of those are very large tasks. And this goes against the grain of modern app frameworks, which tend to create query APIs that integrate with the language, rather than using a foreign query language like SQL or N1QL. For example, look at Apple's Core Data or .NET's LINQ.

**Comment by paishin** [comment]
That comment was more than half a year ago...that's forever in development years :) 

I agree with what you said but I believe there is also as strong trend towards NoSQL databases that offer live replication between the app and the server, like CouchDb/PouchDb, Meteor and services like firebase. Rest API's are good when the app just consumes data off a server but when you create apps that need to function both online and offline working with APIs and custom sync mechanisms is painful.

SQL is not that foreign to mobile developers, SQLlight is one of the options and a lot of developers come from a web development background with lots of SQL experience. Having something like N1QL combined with live replication would allow us to work on the device the same way we work on the server never having to worry about sync or modeling the data to fit specific questions.

I believe that N1QL does have a place on mobile. I understand the complexities faced with such a task so if it ever arrives it will a warm welcome.

**Comment by MMJM** [comment]
+1

**Comment by djpongh** [comment]
Please check out our 2.0 developer builds: https://www.couchbase.com/downloads.  Feedback welcome.
