### ISSUE TITLE
Eager view indexing (update index when adding revisions)

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1010]
CBL currently updates view indexes on demand, when the view is queried. This behavior is inherited from CouchDB. There have been requests to behave more like a typical relational database and update indexes whenever documents are updated. This probably wouldn't save much time overall, but it moves the time around so that updating the database becomes slightly slower, but there's no extra latency to querying a view. That may be a win from a UX perspective since users really notice and dislike latency when they choose a command.

We probably don't want to do this for _all_ views, though. One of the benefits of the current way is that views only have overhead when they're used. A rarely-used view won't slow anything down until it's queried. We could either create a new property in the API, like `View.indexImmediately`, or just automatically stop eagerly updating views that haven't been queried in a while.

(Note: this is a cross-platform feature that should ideally be implemented on all platforms in the same release.)

**Comment by tleyden** [comment]
Workaround (from @snej via google group) 

> As a workaround, any time you’d like a view to be updated, you can issue an asynchronous query on that view. For best performance try to minimize the result set; for example you can set the limit to 1, or the endKey to a JSON null (i.e. [NSNull null]).

**Comment by tleyden** [comment]
@pasin do you know if this is this still the best recommended workaround?  (or has there been any changes to the API that make this workaround unnecessary?)

> As a workaround, any time you’d like a view to be updated, you can issue an asynchronous query on that view. For best performance try to minimize the result set; for example you can set the limit to 1, or the endKey to a JSON null (i.e. [NSNull null]).

**Comment by snej** [comment]
@tleyden We added -updateIndex and -updateIndexAsync: methods in 1.3.

**Comment by Martin-Hogge** [comment]
Hi, I correctly see the [updateIndex reference](https://developer.couchbase.com/documentation/mobile/current/references/couchbase-lite/couchbase-lite/view/view/index.html) on the official doc but none for the updateIndexAsync. I could run the `updateIndex` method on a background thread myself but if an async method exists it would be easier to directly use it.

Plus, I do not see it in the official documentation but I find out that their is an `updateIndexAlone` method on the CBLite sdk. I'm not sure to understand correctly the difference between `updateIndex` and `updateIndexAlone`. Here is its JavaDoc:

> /**
     * Updates the view's index (incrementally) if necessary.
     * Only the view's index alone will be updated.
     *
     * @return Status OK if updated or NOT_MODIFIED if already up-to-date.
     * @throws CouchbaseLiteException
     */

**Comment by tleyden** [comment]
@Martin-Hogge I filed an issue in our docs repo for that: https://github.com/couchbaselabs/couchbase-mobile-portal/issues/681

**Comment by carrotalan** [comment]
Potentially relates to https://github.com/couchbase/couchbase-lite-ios/issues/123 ?

**Comment by snej** [comment]
CBL 2 updates indexes eagerly. But CBL 1.x is in maintenance mode, with no major changes planned.
