### ISSUE TITLE
receiving error while installing c sdk 

### ISSUE THREAD

**Issue by sirishkalidindi** [couchbase/couchbase-lite-ios#1012]
receiving error : cbc: error while loading shared libraries: libcouchbase.so.2: cannot open shared object file: No such file or directory Couldn't verify installation! at couchbase-csdk-setup line 249, <STDIN> line 2.

need assistance...Thanks.

**Comment by snej** [comment]
That's not Couchbase Lite; looks like the C SDK for Couchbase Server.
