### ISSUE TITLE
Can't compile the Grocery-sync demo for Swift (Xcode 7.2 (7C68))

### ISSUE THREAD

**Issue by sweber6106** [couchbase/couchbase-lite-ios#1013]
I am trying to compare Couchbase, Firebase, and AWS Cognito to decide which to recommend for an upcoming project at work.  The solution needs to work with both Android and iOS, but I am prototyping with iOS using Swift.  I am trying to get the demo Swift app running but seeing errors I don't know how to address (screenshot attached).  Note: I am new to iOS development.  Note2: When I first started Xcode with the demo app, it mentioned that the code was written for a previous version of Swift and offered to convert the project code.  I was worried that that might introduce some confusion so I did not do it.

<img width="626" alt="screen shot 2015-12-27 at 8 49 00 am" src="https://cloud.githubusercontent.com/assets/5557687/12010720/cc8fb16e-ac77-11e5-9483-9fa4f23f7898.png">

**Comment by snej** [comment]
If you don't let Xcode update the source code, it won't build; Swift 2 isn't source-compatible with 1.2.

But if you need a cross-platform single source base, you're best off using the C#/.NET version of Couchbase Lite, since the Xamarin runtime works on many OSs.

**Comment by sweber6106** [comment]
It doesn't build if you let Xcode do its updates either.  Will the Couchbase demo be updated to Swift 2?  

We are not a C#/.NET shop, and I am not looking for a single source base.

**Comment by snej** [comment]
I've just pushed an update. Yeah, the auto-updater left a few minor [if you're familiar with Swift!] glitches in the error handling that I had to clean up by hand.

If you find any further problems with Grocery Sync, please file them in the issue tracker in its own repo. Thanks!

**Comment by sweber6106** [comment]
Super helpful.  Thanks.  I was trying to patch those issues myself
yesterday, but I am also new to Swift.

**Comment by sweber6106** [comment]
I just entered an issue.  Looks like the last one.  Thanks for today's
fixes.
