### ISSUE TITLE
Obsolete statements in ForestDB FTS docs

### ISSUE THREAD

**Issue by jschmid** [couchbase/couchbase-lite-ios#1014]
We are currently using ForestDB in a bet that it will soon become the recommended storage instead of SQLite. However search is quite important in our app and I am not sure ForestDB is still the best choice.

The [wiki page](https://github.com/couchbase/couchbase-lite-ios/wiki/Full-Text-Search) states:

> NOTE: The upcoming ForestDB-based version of Couchbase Lite implements full-text search itself, instead of using SQLite, and doesn't support the fancy search syntax. Instead, the search terms are individual words, with implicit "AND" conjunctions.

and

> NOTE: The ForestDB version doesn't support snippets or relevance.

However commit 9e804978823994f905dfea59fa0abca99d2008f7 says differently. [This line](https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/API/CBLQuery+FullTextSearch.h#L36) also confuses me.

Can we expect to have a clear roadmap for the Full Text Search functionality when v1.2 is released?

Thanks for the good work!

**Comment by snej** [comment]
Thanks for catching the obsolete warnings on the wiki page; I've updated it now. That line you flagged in the doc-comment is also out of date and I'll fix it soon.

There won't be "official" documentation of full-text search until it's available in all 3 implementations and becomes part of the official API. I don't know if we have a timeframe for that yet.

**Comment by snej** [comment]
Fixed on release/1.2 branch.
