### ISSUE TITLE
Possible p2p memory leak

### ISSUE THREAD

**Issue by EthanRTF** [couchbase/couchbase-lite-ios#1017]
We are encountering a very large memory usage from Coushbase Lite iOS. We first noticed it when we had four or more continuous p2p connections (all pull). We have seen this in 1.1.1, 1.2(unofficial), and 1.3(unofficial).

The memory in our app will idle around 150M without the p2p. Once we begin turning the other apps on, p2p automatically begins between all of the iPads, but you will see large memory spikes as they connect (anywhere between 30M-50M per connection). Sometimes, after around three minutes, it will lower down closer to normal memory usage, other times it will not.

The issue really begins to manifest itself when you have more than four iPads. We currently have a use case that is happening in our beta right now where they can have up to 25 iPads all using p2p with each other (we are currently implementing a partially connected mesh design to reduce strain).

Replication class:
```
class Connection : NSObject
{
    var ipadOwner: FoundIpad!
    
    var push: CBLReplication!
    var pull: CBLReplication!
    
    var connectionURL: NSURL!
    
    var peerUUID: String!
    
    init(connectionURL: NSURL, owner: FoundIpad!, database: CBLDatabase! = nil, username: String = "", password: String = "", shouldCreatePush: Bool = true, UUID: String! = nil)
    {
        super.init()
        
        ipadOwner = owner
        
        self.connectionURL = connectionURL
        
        if UUID != nil
        {
            peerUUID = UUID
        }
        
        var db = database
        if db == nil
        {
            db = staticVars.database()
        }
        
        if shouldCreatePush
        {
            push = db.createPushReplication(connectionURL)
            push.continuous  = true
            
            if peerUUID != nil
            {
                push.customProperties = [String: AnyObject]()
                push.customProperties!["remoteUUID"] = peerUUID!
            }
        }
    
        pull = db.createPullReplication(connectionURL)
        pull.continuous  = true
        
        if peerUUID != nil
        {
            pull.customProperties = [String: AnyObject]()
            pull.customProperties!["remoteUUID"] = peerUUID!
        }
        
        if username != "" && password != ""
        {
            if shouldCreatePush
            {
            	push.authenticator = CBLAuthenticator.basicAuthenticatorWithName(username, password: password)
            }
            pull.authenticator = CBLAuthenticator.basicAuthenticatorWithName(username, password: password)
        }
        
        print("Push and pull created for url: \(connectionURL)")
        
        if shouldCreatePush
        {
        	NSNotificationCenter.defaultCenter().addObserver(self,
            	selector: "pushChanged", name: kCBLReplicationChangeNotification, object: push)
        }
        
        NSNotificationCenter.defaultCenter().addObserver(self,
            selector: "pullChanged", name: kCBLReplicationChangeNotification, object: pull)
        
        if shouldCreatePush
        {
        	push.start()
        }
        pull.start()
    }
    
    func stopConnection()
    {
        if push != nil
        {
            push.stop()
        }
        if pull != nil
        {
            pull.stop()
        }
        print("Push and pull closed for url: \(connectionURL)")
    }
    
    func pushChanged()
    {
        let pushStatus = CBLReplicationStatus(rawValue: self.push.status.rawValue)!
        
        if staticVars.appDelegate != nil
        {
            staticVars.appDelegate.notifyReplicationChange()
        }
        print("Replication ➡️ Push Change: replication state: \(pushStatus.description()) | ip: \(self.push.remoteURL) | error: \(self.push.lastError))")
        
    }
    
    func pullChanged()
    {
        let pullStatus = CBLReplicationStatus(rawValue: self.pull.status.rawValue)!
        
        if staticVars.appDelegate != nil
        {
            staticVars.appDelegate.notifyReplicationChange()
        }
        print("Replication ⬅️ Pull Change: replication state: \(pullStatus.description()) | ip: \(self.pull.remoteURL) | error: \(self.pull.lastError))")
        
    }
    
    func restart()
    {
        if push != nil
        {
            push.restart()
        }
        if pull != nil
        {
            pull.restart()
        }
    }
    
    enum CBLReplicationStatus: UInt32
    {
        case kCBLReplicationStopped
        case kCBLReplicationOffline
        case kCBLReplicationIdle
        case kCBLReplicationActive
        
        func description () -> String
        {
            switch self
            {
            case kCBLReplicationStopped:
                return "Stopped"
            case kCBLReplicationOffline:
                return "Offline"
            case kCBLReplicationIdle:
                return "Idle"
            case kCBLReplicationActive:
                return "Active"
            }
        }
    } 
}
```

We create one of these for each iPad that is found and should be replicated to.

![screen shot 2016-01-06 at 10 20 31 am](https://cloud.githubusercontent.com/assets/16580518/12150701/da09afb0-b470-11e5-8157-c4ee349eb329.png)

We have tried a one shot replication model where we would listen for changes based on other iPad's listeners. This fixed the memory issue, but caused a delay in the propagation of documents, which allows for errors in our app (we require changes to be reflected nearly immediately and continuous does that for us).

We have also implemented a UUID model, inspired by the p2p Grocery Sync example, that stores a unique ID of iPads to prevent unnecessary re-cataloging of other iPads when a port or IP address changes.

If any other information is needed, just let me know and I will get it to you posthaste. Any help or advice is greatly appreciated.

**Comment by snej** [comment]
Thanks for the detailed description. Question: I assume the memory growth occurs even with a single connection, just a smaller amount?

Have you used Instruments to look into the memory growth?

**Comment by EthanRTF** [comment]
Yes, it does occur with a single connection. But, as you said, it is a smaller amount.

Here is a screen shot of an Instruments memory trace I ran this morning.

![screen shot 2016-01-07 at 11 09 04 am modified](https://cloud.githubusercontent.com/assets/16580518/12177336/3525f49c-b531-11e5-93cd-6c23c4a72b7d.png)
This instruments was started ~3 minutes in, so there should not be any outside memory interference. All of the databases are fully synced.

It may or may not be important to note that there is also a connection with a SyncGateway going on as well.

I tried to help a bit by drawing hierarchy lines to help show where chunks of memory are being used. Also, I placed blue circles at the lowest level CBL functions that I could, hoping that might point to what may be happening.

**Comment by snej** [comment]
Hi, sorry I lost track of this. I did find a large memory leak last month -- a few source files were accidentally being compiled without ARC, so objects they allocated got leaked. Have you re-tested with the released 1.2?

**Comment by twelvearrays** [comment]
I am on the same development team at @EthanRTF and we have tried 1.2.  It did not resolve the issues we are experiencing.  What other information can we supply to help?

**Comment by snej** [comment]
Use the Leaks instrument, and find the backtraces of leaked objects/blocks.

**Comment by twelvearrays** [comment]
We will do one Monday! Thanks for your quick response!

**Comment by EthanRTF** [comment]
It is important to note that this is not a memory leak in the sense that there are objects that are unallocated that don't have a handle to them, but that Couchbase is taking in an excessive amount of memory and never releasing it, causing the app to crash.

Here is a [link](https://www.dropbox.com/l/sh/Dd9BxpdkuxFXTEttxpQkHu) of a trace file for allocation. The area to watch is after the 1:24 point, where we open the app on four other iPads and allow them to connect to each other.

Other bits of knowledge:
- This database has over 300,000 documents, 31,000 attachments with an average size of 1KB, with the complete database being over 400MB.
- While our system can have many iPads syncing, in accordance with out mesh network, an iPad can only connect to three other iPads at any given time.
- We have no issues syncing to the gateway; The issue only occurs when syncing with p2p devices.
- The issue occurs both on devices it has not synced with before as well as devices it has fully synced with.
- The memory issue not only happens when the iPads connect, but there is a spike when an iPad disconnects as well (when we stop the CBLReplication).

If there is anything further we can do to help please let us know because this is the only thing keeping us from having a releasable product.

**Comment by snej** [comment]
If the problem only occurs in P2P replication, I see two possibilities:

1. The memory usage comes from the CouchbaseLiteListener, not the active side of the replicator;
2. Or, the problem is in the replicator but only in code paths that don't get used when replicating with Sync Gateway, i.e. in the fallback code for when SG protocol optimizations like `_bulk_docs` aren't available.

Ethan, would it be possible to run a unidirectional replication (A pushes/pulls to B, but not vice versa) and identify which device the problem occurs on? That would help identify whether it's the replicator (A) or listener (B).

FYI @ashvindersingh @sethrosetter — this highlights the need for some P2P testing, and also measuring memory usage during tests. (Actually this should reproduce when replicating CBL against LiteServ, because LiteServ also uses the listener.)

**Comment by snej** [comment]
Hm, I just looked closely at that Instruments screenshot from 1/7, and the highlighted code is all in the listener (CBL_Router). That might answer my question above. I'll take a look.

**Comment by snej** [comment]
@EthanRTF, could you try cherry-picking the commit from PR #1123 and see if it fixes your problem? I found a missing `super` call that was preventing HTTPConnection objects from being cleaned up. After this fix I can't find any more growth in the number of CBL-related objects in LiteServ.

**Comment by EthanRTF** [comment]
Thanks for your help! This seems to have cleared up the memory issue.

Since this fix, however, we have run into another issue. I am not sure if it is related, but we only encountered it after fixing the last bug, so I feel I should put it here for the moment.

During p2p replication, I receive the following error on multiple, but not all, iPads.

```
2016-02-17 17:25:41.807 posRetail[3212:1046883] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'
*** First throw call stack:
(0x183711900 0x182d7ff80 0x1835fb134 0x100a7c4bc 0x100a7bd70 0x100a7c578 0x100a5c66c 0x100a5c878 0x100a5a86c 0x100a4d11c 0x100a6dc0c 0x100a705cc 0x183e7a6ec 0x183e7a67c 0x183e7a7f0 0x183ce731c 0x183dd4e7c 0x102ed1bb0 0x102edb354 0x183cd3a88 0x1835f50ac 0x183cd396c 0x183cd382c 0x183cd3658 0x1836c8efc 0x1836c8910 0x1836c6690 0x1835f5680 0x183fed21c 0x100a4562c 0x1840d3c40 0x18337bb28 0x18337ba8c 0x183379028)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

According to the debug navigator, it is occurring in [CBLMultiStreamWriter addInput:length:]:

![screen shot 2016-02-17 at 5 33 37 pm](https://cloud.githubusercontent.com/assets/16580518/13128613/aa7a7b4c-d59c-11e5-9b60-9e13db5b74e4.png)

Also, it may or may not be related but, since the update, I am receiving these warnings as well:

```
2016-02-17 17:18:06.411 posRetail[1049:331534] WARNING: Can't get binary data of attachment 'attachment' of {-Vhn8oqSvY9ouxOw8Eq-9Tw #2-d4d40f2ad57e2da9517a26b5c556b37a}
2016-02-17 17:18:06.412 posRetail[1049:331534] WARNING: CBLRestPusher[http://Pad2.local.:61537/juls2]: Couldn't expand attachments of {-Vhn8oqSvY9ouxOw8Eq-9Tw #2-d4d40f2ad57e2da9517a26b5c556b37a}
2016-02-17 17:18:06.414 posRetail[1049:331534] WARNING: Can't get binary data of attachment 'attachment' of {-ovGGvrPBzXdeZhdbIF_7Rl #2-f2632429d2cc52bffa356b02f982c0eb}
2016-02-17 17:18:06.415 posRetail[1049:331534] WARNING: CBLRestPusher[http://Pad2.local.:61537/juls2]: Couldn't expand attachments of {-ovGGvrPBzXdeZhdbIF_7Rl #2-f2632429d2cc52bffa356b02f982c0eb}
2016-02-17 17:18:06.417 posRetail[1049:331534] WARNING: Can't get binary data of attachment 'attachment' of {-5oC53HvR1bbHmugnLg2eXU #2-636f5dd971d07dad7beaebdf1aa5c866}
2016-02-17 17:18:06.418 posRetail[1049:331534] WARNING: CBLRestPusher[http://Pad2.local.:61537/juls2]: Couldn't expand attachments of {-5oC53HvR1bbHmugnLg2eXU #2-636f5dd971d07dad7beaebdf1aa5c866}
```

We are running ForestDB. Also, we have tried the official 1.2 build with that small change as well as your dev branch with the fix already merged.

Once again, thanks for fixing the other bug. Let me know if I need to open a separate issue.

**Comment by snej** [comment]
Thanks for confirming the leak fix!

And please file the new problems you're seeing as a new issue. It gets too confusing to try to track multiple problems in one bug report.

**Comment by snej** [comment]
Oh, and in the new issue please specify what version or commit of CBL you're using!
