### ISSUE TITLE
Unknown tokenizer error

### ISSUE THREAD

**Issue by brendand** [couchbase/couchbase-lite-ios#1018]
One of my beta testers is in Holland and he has his language set to Dutch. Today he said the full text searching wasn't working. So I had him send me the log output and this is what we saw:

Error calling sqlite3_step (1: unknown tokenizer) SQLITE_ERROR
DB Query:         CREATE VIRTUAL TABLE IF NOT EXISTS fulltext             USING fts4(content, tokenize=unicodesn "stemmer=dutch")

It works for me in Canada in English.

I'm currently using master commit 26c67aff8e2334ab8dd0c3194346422f7ff36d26 on Mac OS X 10.11.3 beta and iOS 9.2.

**Comment by snej** [comment]
#983.
