### ISSUE TITLE
Invalid short version string

### ISSUE THREAD

**Issue by lordkev** [couchbase/couchbase-lite-ios#1019]
I'm not sure if this is a new rule that ITC is enforcing, but when submitting this week we ran into the following validation error when trying to submit our app:

"This bundle is invalid. The value for key CFBundleShortVersionString '1.1+ (1)' in the Info.plist file must be a period-separated list of at most three non-negative integers."

This may be specific to our use of building CBL as a dynamic framework, but I assume others will run into it as well. Happy to put in a PR, but I'm not positive what you'd like to change it to.

**Comment by snej** [comment]
Thanks for reporting this; we'll fix it for 1.2. Until then you can edit the Info.plist to fix it in your copy.

**Comment by lordkev** [comment]
:+1:

**Comment by snej** [comment]
Fixed on 1.2 branch.
