### ISSUE TITLE
Testing: Track memory footprint during replication

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1022]
Version 1.1.1 had an embarrassing memory leak (#1016) that showed up pretty dramatically during replication. We didn't notice it during development. We should have automated testing that runs some scenario involving replication and tracks heap usage, raising an alarm if it exceeds a limit.

**Comment by pasin** [comment]
CC: @sethrosetter

**Comment by snej** [comment]
Other metrics would be useful to track too, like time taken to replicate.

**Comment by djpongh** [comment]
Moved to: https://issues.couchbase.com/browse/CBL-282
