### ISSUE TITLE
Build and Upload PG/Cordova Plugins

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-ios#1026]

**Comment by pasin** [comment]
Done.

**Comment by zgramana** [comment]
Confirmed via https://www.npmjs.com/package/couchbase-lite-phonegap-plugin, though the search results still have not updated to reflect 1.2.0 as the current release.

**Comment by pasin** [comment]
How did you search? When I searched via npmjs.com, it shows 1.2.0.

**Comment by zgramana** [comment]
http://cordova.apache.org/plugins/?q=couchbase
