### ISSUE TITLE
Run unit test against SG

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-ios#1027]
- [x] CBLite iOS 1.1 with sync_gateway 1.2
- [x] CBLite iOS 1.2 with sync_gateway 1.1
- [x] CBLite iOS 1.2 with sync_gateway 1.2

**Comment by pasin** [comment]
Note: CBLite iOS 1.1 with sync_gateway 1.2 was run on Simulator as there was an issue with SSL certificate on .local host that got fixed in 1.2 via https://github.com/couchbase/couchbase-lite-ios/commit/f0eb1cb54d59095f2adc3f3c8b9a7c37991d7272.

**Comment by zgramana** [comment]
Need to re-run against final RC's of both CBL 1.2 final RC and SG 1.2.
