### ISSUE TITLE
bitcode bundle could not be generated because libCBLForestDBStorage.a(CBL_ForestDBStorage.o)' was built without full bitcode

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-ios#1030]
I'm trying to build a couchbase-lite app via Xcode Product / Archive and getting this [error](https://gist.github.com/tleyden/77f276b21bbb0071e9ae#file-gistfile1-txt-L94):

```
ld: bitcode bundle could not be generated because '/Users/tleyden/Development/deepstyle-ios/DeepStyle2/libCBLForestDBStorage.a(CBL_ForestDBStorage.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Filing an issue since it may be a documentation issue.  

How do I get past this error?

The project I'm trying to build is [here](https://github.com/tleyden/deepstyle-ios)  (commit hash https://github.com/tleyden/deepstyle-ios/commit/5e9357515294b3afebaa5293f8e55ae4a35d5a05)

Looks like it might be related to https://github.com/couchbase/couchbase-lite-ios/issues/911

**Comment by tleyden** [comment]
It looks like I'm building couchbase lite locally from https://github.com/couchbase/couchbase-lite-ios/commit/22a6c7f0d52c34ab419c03eeb7ea1c359158b5ec, and copying the resulting framework into my app.

I checked the build settings on couchbase lite, and "Enable Bitcode" is set to "Yes":

<img width="1552" alt="screen shot 2016-01-09 at 9 15 18 pm" src="https://cloud.githubusercontent.com/assets/296876/12220117/218e88c2-b716-11e5-8131-7275f5e01f54.png">

**Comment by pasin** [comment]
From the error, libCBLForestDBStorage build needs bit code enabled, but I checked the CBL ForestDB Storage target in 1.2 branch and it was already enabled. Could you check yours?

To unblock, you could disable the bit code set on your app build settings.

**Comment by tleyden** [comment]
> To unblock, you could disable the bit code set on your app build settings.

This seems to have fixed it!

**Comment by tleyden** [comment]
> I checked the CBL ForestDB Storage target in 1.2 branch and it was already enabled. Could you check yours?

It appears to be enabled:

<img width="1552" alt="screen shot 2016-01-09 at 11 16 29 pm" src="https://cloud.githubusercontent.com/assets/296876/12220458/353a5b92-b727-11e5-83f4-b1660fed0bc6.png">

**Comment by tleyden** [comment]
In order to build todolite-ios and have it install to my iphone 6 device, I had to disable bitcode.

**Comment by snej** [comment]
To be clear: You're building your own CBL binaries, Traun? Using Xcode 7? (The binaries from Jenkins won't have bitcode yet because the server is still using Xcode 6. Michael says he's upgrading it today.)

**Comment by michaelkwok** [comment]
Sounds like the configuration is properly set in branch 1.2.0 and I just need to upgrade Xcode 7 which I am almost done.  I assume the same applies for 'master' branch.

**Comment by tleyden** [comment]
> To be clear: You're building your own CBL binaries, Traun? Using Xcode 7?

Yes on both accounts.

**Comment by pasin** [comment]
I just build the release version (via calling archive) of CBL ForestDB Storage, and I was able to use the generated libCBLForestDBStorage.a with ToDoLite-iOS with bit code enabled without the issue.
