### ISSUE TITLE
FTS: Inconsistent handling of stop words in ForestDB vs SQLite

### ISSUE THREAD

**Issue by brendand** [couchbase/couchbase-lite-ios#1031]
Searching for some words return results in SQLite, but not in ForestDB for the same search term.

I have a document with the words "this and that apple".

With ForestDB, I can search for apple and I get a result. But if I search for "this" or "that" or even "and", I get no results. The same search works perfect with an SQLite version of my database.

I'm not using any fancy syntax such as appending * to my search term or including "AND" or "OR" in my search terms.

This is how I'm emitting my values in my map block. I have an NSArray of values which I join together into one long string divided by a | character. 

    if (emitValues.count > 0) {
        NSString *valueToEmit = [emitValues componentsJoinedByString:@" | "];
	emit(CBLTextKey(valueToEmit), doc[@"form"]);
    }

The value also emitted is the document ID of my form which I use to ensure the result is appropriate for the currently selected form in my database.

I'm using the latest 1.2 release build 98af0ffaadd048de2196e70046a30b8fcd197bbf for Mac. I haven't tested it on iOS yet.

**Comment by snej** [comment]
So the argument to CBLTextKey is `@"this | and | that | apple"? What's the reason for the `|` characters? The tokenizer will ignore them, I think.

**Comment by brendand** [comment]
I probably don't need them. The reason I thought I might need some sort of delimiter is because I have values that come from different fields and I wanted to separate them. For example:

Movie Title: The Terminator
Actor: Arnold Schwarzenegger 
Genre: Action & Adventure

There's 3 different fields there and it would get emitted like this:

The Terminator | Arnold Schwarzenegger | Action & Adventure

I was hoping to restrict searches to specific sets of values instead of bleeding from one field to another. So a search for "Terminator Arnold" would return 0 rows because the | was in between it in the index. But I guess if punctuation gets stripped then it doesn't really matter.

The other reason for it was just for me so that if I were to look at the index itself then I could see the divisions between fields values.

But I don't see a way how to view the search index with ForestDB in a coherent way like I can with SQLite anyway, so I guess I can remove the bars.

**Comment by brendand** [comment]
I'll take out the bars to see if it makes a difference, but somehow I doubt it will.

**Comment by brendand** [comment]
It didn't make a difference. It almost feels like an aggressive tokenizer that's stripping out words from the index. I can't find the word "as", "and", "this", "that", or even "hello". Just some test words. But in the same record it will find "apple", "get", "milk", etc. Also it finds "cookies" when I type in "cooki", but not when I type "cook". I think that's an issue with not being able to do prefixed searches and the stemmer is kicking in to strip the "es" off of "cookies".

I could really use prefixed searches though. I should be able to search for "ap" and have it return "apple".

 I may need to revert back to SQLite for now.

**Comment by zgramana** [comment]
Those are common stop words: https://en.m.wikipedia.org/wiki/Stop_words

In an typical information retrieval system, you ignore them from scoring. However, we aren't a full IR solution like Lucene or SearchKit, so it does make less sense to ignore them completely.

**Comment by snej** [comment]
Yes, the ForestDB FTS indexer strips out stop words, taken from [this list](https://github.com/couchbaselabs/cbforest/blob/master/CBForest/english_stopwords.h). Apparently SQLite doesn't remove stop words, or at least not as many.

**Comment by snej** [comment]
A couple of things:

- [ ] That list of stop words may be too big. I got it off the Internet so it should be infallible and perfect, but on inspection it's got some words I'm not sure should be skipped. Some like "the" and "it" are no-brainers, but "like" and "couldn't"? IIRC, when I looked for stop-word lists I found quite a few and they varied greatly.
- [ ] Internally the text being indexed or searched for is identified by a (human) language. If the language were set to an empty string there would be no stop-word removal (or stemming). However there's no public API for configuring this; the language is looked up from the system's default language. This is something that could be added to the API.
- [ ] Another possibility is to use SearchKit instead on OS X. I haven't used it because it's not available on iOS, sadly. Brendan, you could actually use SearchKit in your app by making a view whose map function added the words to a SearchKit index instead of emitting anything to CBL.

**Comment by brendand** [comment]
Thanks for the SearchKit suggestion Jens. However, I'd prefer to have a native solution since my app is both for iOS and Mac.

**Comment by snej** [comment]
I filed a CBForest issue (https://github.com/couchbaselabs/cbforest/issues/61) suggesting we switch to an existing FTS implementation, instead of putting more work into making my homemade one better. So far I think the leading contender is, ironically, SQLite.

**Comment by snej** [comment]
We'll address this in the 2.0 release since we need to reimplement FTS anyway for both storage engines. Filed https://github.com/couchbase/couchbase-lite-core/issues/4
