### ISSUE TITLE
Carthage badge / readme mention

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-ios#1032]
One thing missing from https://github.com/couchbase/couchbase-lite-ios/pull/994 is a carthage badge or some sort of mention in the README.

@lordkev if you are able to send a PR for this, would be much appreciated!

**Comment by geoffreywiseman** [comment]
It's mentioned in the README now, yes? Is this issue done, then?

**Comment by pasin** [comment]
Closed as done.
