### ISSUE TITLE
Verify couchbase lite release1.2 works with AppleTV

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/couchbase-lite-ios#1034]
The verification consists of two parts:
1. Verify all the Unit tests pass on Apple TV
2. Verify all the headless bee tests pass on Apple TV. 
 https://github.com/couchbaselabs/iOS-WorkerBe

**Comment by ashvindersingh** [comment]
Test with : 
- Couchbase-lite-iOS: release/1.2.0 42f3826b420512eca23c9c40dc8a6d3470efe50e
- tvOS: 9.1
- SG: 1.2.0-77
Unit Test failures:

- ChangeTracker_Tests:
 - test_Simple 
 - test_Auth 
 - test_AuthFailure 
 - test_CBLWebSocketChangeTracker_Auth
 - logs: https://gist.github.com/a9461c37ac5209985f7a

 Listener_Tests
 - test01_SSL_NoClientCert
 - test02_SSL_ClientCert
 - test03_ReadOnly
 - logs: https://gist.github.com/f6e83bd37530ef1c5078

 ListenerHTTP_Tests
 - test01_SSL_NoClientCert
 - test02_SSL_ClientCert
 - test03_ReadOnly
 - test04_GetRange (crashes, got exception)
 - logs: https://gist.github.com/86657062a9287cae9de0

 P2P_HTTP_Tests
 - testPush
 - testPull
 - testPushAttachments
 - testPullAttachments
 - logs: https://gist.github.com/d93f3bf2ea39ae845a12

 ReplicatorInternal_Tests
 - test_06_Puller_SSL
 - test_07_Puller_SSL_Continuous
 - logs: https://gist.github.com/3c1115f3da9199bda52b

 View_Tests
- test07_LiveQuery
- logs: https://gist.github.com/0d90730175bcc34ae254

**Comment by pasin** [comment]
> - ChangeTracker_Tests:
>  - test_Simple 
>  - test_Auth 
>  - test_AuthFailure 
>  - test_CBLWebSocketChangeTracker_Auth
>  - logs: https://gist.github.com/a9461c37ac5209985f7a

All of the failed tests have the same connection error as below. It could be a connection or SSL certificate issue.

```
2016-02-02 18:44:26.105 CBL tvOS Test App[258:14090] CFNetwork SSLHandshake failed (-9847)
2016-02-02 18:44:26.109 CBL tvOS Test App[258:14090] CBLSocketChangeTracker[0x15d56d1f0 cbl_auth_test]: Can't connect, giving up: Error Domain=NSOSStatusErrorDomain Code=-9847 "(null)"
```

**Comment by pasin** [comment]
>  - Listener_Tests
>   - test01_SSL_NoClientCert
>   - test02_SSL_ClientCert
>   - test03_ReadOnly
>   - logs: https://gist.github.com/f6e83bd37530ef1c5078

>  - ListenerHTTP_Tests
>   - test01_SSL_NoClientCert
>   - test02_SSL_ClientCert
>   - test03_ReadOnly
>   - test04_GetRange (crashes, got exception)
>   - logs: https://gist.github.com/86657062a9287cae9de0

> - P2P_HTTP_Tests
>  - testPush
>  - testPull
>  - testPushAttachments
>  - testPullAttachments
>  - logs: https://gist.github.com/d93f3bf2ea39ae845a12

It seems like 'https://Apple-TV.local:<PORT>' is not accessible and causes all of these failures.

**Comment by pasin** [comment]
> - ReplicatorInternal_Tests
>  - test_06_Puller_SSL
>  - test_07_Puller_SSL_Continuous
>  - logs: https://gist.github.com/3c1115f3da9199bda52b

These 2 tests are failed from the same reason:

```
2016-02-02 19:22:14.729 CBL tvOS Test App[423:25197] ---- Using SQLite ----
2016-02-02 19:22:14.833 CBL tvOS Test App[423:25197] Replicating without root cert; should fail...
2016-02-02 19:22:14.836 CBL tvOS Test App[423:25197] Waiting for replicator to finish...
2016-02-02 19:22:14.971 CBL tvOS Test App[423:25197] Replication: CBLRestPuller[https://ashvinders-macbook-pro.local:4994/public] took 0.136 sec; error=(null)
19:22:15.248 Xcode[92988:10999482] _XCT_testCaseDidFailForTestClass:ReplicatorInternal_Tests method:test_06_Puller_SSL withMessage:(($equal(repl.error.domain, expectError.domain) && repl.error.code == expectError.code) is true) failed - 
Unexpected error (null)
  Expected error Error Domain=NSURLErrorDomain Code=-1202 "(null)" file:/Users/ashvinder/mobile_testing/couchbase-lite-ios/Unit-Tests/ReplicatorInternal_Tests.m line:695
19:22:15.421 CBL tvOS Test App[423:25197] -[_XCTestDriverTestObserver testCase:didFailWithDescription:inFile:atLine:]
```

**Comment by pasin** [comment]
> - View_Tests
>  - test07_LiveQuery
>  - logs: https://gist.github.com/0d90730175bcc34ae254

This test is failed due to time out waiting for the live query result. Not sure what is causing this.

```
2016-02-02 19:25:21.180 CBL tvOS Test App[446:26453] ---- Using SQLite ----
2016-02-02 19:25:21.295 CBL tvOS Test App[446:26453] Created CBLLiveQuery[vu, start=23, end=33, mapOnly=YES]
2016-02-02 19:25:21.296 CBL tvOS Test App[446:26453] Waiting for live query to update...
2016-02-02 19:25:21.302 CBL tvOS Test App[446:26453] Live query rows = (null)
2016-02-02 19:25:21.303 CBL tvOS Test App[446:26453] Live query rows = (null)
2016-02-02 19:25:21.304 CBL tvOS Test App[446:26453] Live query rows = (null)
2016-02-02 19:25:21.314 CBL tvOS Test App[446:26453] Live query rows = (null)
/Users/ashvinder/mobile_testing/couchbase-lite-ios/Unit-Tests/View_Tests.m:369: error: -[View_Tests test07_LiveQuery] : ((timeout.timeIntervalSinceNow > 0.0) is true) failed - timed out waiting for live query
2016-02-02 19:30:13.662 CBL tvOS Test App[446:26453] Live query rows = (null)
```

**Comment by ashvindersingh** [comment]
Executed headless-bee tests with CBL-tvOS:
https://gist.github.com/anonymous/6bca0840b66968f7b321

**Comment by pasin** [comment]
It's error because Apple is requires an application to use secure (SSL) communication by default. You may disable the the App Transport Security policy just for verifying. To disable, put the following in the tvOS app info.plist in the XCode:

```
<key>NSAppTransportSecurity</key>  
<dict>  
<key>NSAllowsArbitraryLoads</key><true/>  
</dict> 
```

**Comment by pasin** [comment]
I have run the unit tests on my iPhone device and I could reproduce the failures only from these 2 tests:

ReplicatorInternal_Tests
- test_06_Puller_SSL
- test_07_Puller_SSL_Continuous

I believe the failures are caused by the unit test issue. I have created the ticket (#1092) to fix this in 1.3.

**Comment by snej** [comment]
> You may disable the the App Transport Security policy for verifying.

Please don't do that; we need to ensure that CBL works with ATS.

The unit test code is set up to use _only_ https URLs when running on iOS or tvOS. See the implementation of -[CBLTestCase remoteTestDBURL:]. It sounds like maybe this isn't happening? The test for the iOS version is keyed off of `#if TARGET_OS_IPHONE`, but that conditional is true on tvOS.

The unit tests were passing on Apple TV devices as of October, in the release/1.1.1-appleTV branch... :-(

**Comment by pasin** [comment]
> The unit test code is set up to use _only_ https URLs when running on iOS or tvOS. See the implementation of -[CBLTestCase remoteTestDBURL:]. It sounds like maybe this isn't happening? The test for the iOS version is keyed off of `#if TARGET_OS_IPHONE`, but that conditional is true on tvOS.

@ashvindersingh did run the unit tests on the device with HTTPS enabled. So there is no issue with the -[CBLTestCase remoteTestDBURL:]. The 'App Transport Security policy' error that @ashvindersingh posted above is from the WorkerBee replication test. @ashvindersingh did post the result of running tests on both unit tests and worker bee.

**Comment by ashvindersingh** [comment]
Another ticket is opened to track the failing listener tests #1098

**Comment by ashvindersingh** [comment]
Verified with AppleTV that push and pull replication works. 

tvOS: 9.1
CBL-tvOS: 1.2.0-112
SG: 1.2.0-77 

- push replication headless bee logs: https://gist.github.com/31baca1cfb4b0c5e5fbb
  
- pull replication headless bee logs: https://gist.github.com/fdb3b6d50101395e3695
