### ISSUE TITLE
Request for prefixed search queries in ForestDB's FTS implementation

### ISSUE THREAD

**Issue by brendand** [couchbase/couchbase-lite-ios#1036]
It would be great if we could search for "ap" and have documents that returned "apple", or "ape", or any other word which began with the letters "ap". There are an infinite number of examples of course, but I just wanted to add this as a request.

A more specific example that many of my customers rely upon is to be able to search for order numbers that begin with a certain sequence of digits. For example, searching for "123" would bring back a list of orders like "123ABC", "123L100", and so on. Or even searching for a list of phone numbers in a specific area code would require this sort of thing, especially if the phone numbers were stored as a single string of digits like 4035551212.

**Comment by snej** [comment]
This may not always be wanted, so I'd be inclined to require a `*` at the end of a search term to enable it.

**Comment by brendand** [comment]
Yes, absolutely. That's how SQLite's FTS handles it. Sorry, I should have been more specific about that.

**Comment by brendand** [comment]
Just wondering if there's any possibility that prefixed searches will be implemented in ForestDB at all?

And also if the stemming can be turned off so I can search for "parking" and not receive a result that has "park" in it.

**Comment by jayahariv** [comment]
Closing 1.x issue!
