### ISSUE TITLE
POST _bulk_docs does not support HTTPBodyStream

### ISSUE THREAD

**Issue by lasselaakkonen** [couchbase/couchbase-lite-ios#1045]
Using Couchbase-Lite-PhoneGap-Plugin 1.1.1, which uses Couchbase Lite 1.1.

If data is POSTed as a stream to _bulk_docs, the server returns {"status":500,"error":"Internal error"} and does not add the documents.

Logs show:

	WARNING: Exception caught in CBL_Router:
	data parameter is nil
	0   CoreFoundation                      0x2f809e9b <redacted> + 154
	2   CoreFoundation                      0x2f809dc5 <redacted> + 0
	3   Foundation                          0x30191be7 <redacted> + 66
	4   cbl-ios-xhrupload                   0x0014897f -[CBL_Router bodyAsDictionary] + 114
	6   cbl-ios-xhrupload                   0x0014a045 -[CBL_Router route] + 2740
	7   cbl-ios-xhrupload                   0x0014a503 -[CBL_Router run] + 874
	etc...

bodyAsDictionary:
https://github.com/couchbase/couchbase-lite-ios/blob/e452b5e5d92d7671d551787d5e32663ae29de494/Source/CBL_Router.m#L144-L147

The issue can be reproduced at least on a iOS 7.0 device and iOS 9.0 simulator by referencing request.upload, which apparently triggers use of streams, instead of data in the body. This request fails:

        var request = new XMLHttpRequest();
        request.open('POST', "http://lite.couchbase./testdb/_bulk_docs");
        request.setRequestHeader('Content-Type', 'application/json');
        console.log(request.upload);
        request.send(JSON.stringify({ docs: [ { foo: 123 } ] }));

I ran into this issue while testing PouchDB with Couchbase Lite.

This doesn't seem too hard to fix, but I have no experience with either Object-C or Couchbase Lite.

**Comment by lukemelia** [comment]
Coincidentally running into this same issue today with POST to _revs_diff
