### ISSUE TITLE
CBLLiveQuery notification throttling too aggressive by default

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-ios#1046]
`kDefaultLiveQueryUpdateInterval` defaults to 0.5 seconds, introducing significant delay when processing notifications. This can easily result in a user interface that is inconsistent with the underlying data model for a noticeable period of time. This is easily demonstrated by using the Kitchen Sync app and toggling the checked status at moderately quick rate.

The human threshold for latency that appears "instantaneous" is 200-300ms. Let's set the latency at 200ms by default instead.

**Comment by snej** [comment]
Fixed on branch release/1.2.
