### ISSUE TITLE
Couchbase lite iOS binary has enable_bitcode' flag disabled

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/couchbase-lite-ios#1048]
Found on couchbase lite: 1.2.0-76
Steps:
- Download the latest binary: http://latestbuilds.hq.couchbase.com/couchbase-lite-ios/release/1.2/ios/
- Copy the couchbase lite framework and listener framework to todo lite frameworks directory
- Compile the project. 
ToDo lite ios: https://github.com/couchbaselabs/ToDoLite-iOS

Tried to run with ToDo lite app. When compiling with couchbase lite iOS getting this error

```

ld: '/Users/ashvinder/mobile_testing/ToDoLite-iOS/Frameworks/CouchbaseLite.framework/CouchbaseLite(CBL_Revision.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by tleyden** [comment]
@ashvindersingh sounds like the same issue as https://github.com/couchbase/couchbase-lite-ios/issues/1030

I'm not sure if this is a todolite-ios issue or a couchbase lite issue

**Comment by tleyden** [comment]
@michaelkwok This seems like a possible build issue of couchbase lite 1.2.  /cc @zgramana

**Comment by snej** [comment]
Same as #1030.

**Comment by snej** [comment]
Oops, #1030 was already closed...

**Comment by snej** [comment]
AFAIK, if the framework is built with Xcode 7 or later it will contain bitcode.
If an Xcode 7 based build doesn't have bitcode, then I'm going to need to poke at the binaries to see where it goes missing...

Also, bitcode is (a) only used for App Store submissions, not local builds, and (b) is not yet required by Apple. So it's technically not a showstopper that we're missing it. But we really ought to have it.

**Comment by zgramana** [comment]
WRT to (b), we need to treat it as a showstopper since, for all we know, it may become required before our next release. Not to mention it's a scary warning for dev's, and just generates lots of preventable questions in forums/support channels.

**Comment by michaelkwok** [comment]
I have upgraded to Xcdoe 7 for all the targets in the new builds.

**Comment by zgramana** [comment]
@ashvindersingh just needs verification.

**Comment by ashvindersingh** [comment]
This verified and issue is fixed.

**Comment by zgramana** [comment]
Forum user is reporting the issue present in 1.2: https://forums.couchbase.com/t/couchbaselite-enable-bitcode-error-on-xcode7/5315/5

**Comment by pasin** [comment]
I accidentally closed the issue.

**Comment by srinadhK** [comment]
Still Bit Code enable issue on Couchbase Mobile 1.2

**Comment by pasin** [comment]
@zgramana the forum post doesn't exist anymore.

**Comment by pasin** [comment]
@srinadhK How do you obtain and consume the framework (e.g. download from mobile.couchbase, cocoapod, or phonegap plugin)? Also can you temporarily disable the bitcode, enable 'CBLDatabase' logging, and post CBL version from the log messages?

**Comment by srinadhK** [comment]
@pasin i download framework from couchbase for ios native app. i disabled now, but what is the use of **enable 'CBLDatabase' logging, and post CBL version from the log messages?**

**Comment by snej** [comment]
So we can verify exactly which version it is that you've linked into the app.

**Comment by zgramana** [comment]
```
Ld /Users/zgramana/Library/Developer/Xcode/DerivedData/KitchenSync-hbtjaweroxojftenomzcwhsyixci/Build/Intermediates/ArchiveIntermediates/KitchenSync/IntermediateBuildFilesPath/KitchenSync.build/Release-iphoneos/KitchenSync.build/Objects-normal/armv7/KitchenSync normal armv7
    cd /Users/zgramana/Source/mini-hacks/kitchen-sync/swift/completed
    export IPHONEOS_DEPLOYMENT_TARGET=9.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk -L/Users/zgramana/Library/Developer/Xcode/DerivedData/KitchenSync-hbtjaweroxojftenomzcwhsyixci/Build/Intermediates/ArchiveIntermediates/KitchenSync/BuildProductsPath/Release-iphoneos -F/Users/zgramana/Library/Developer/Xcode/DerivedData/KitchenSync-hbtjaweroxojftenomzcwhsyixci/Build/Intermediates/ArchiveIntermediates/KitchenSync/BuildProductsPath/Release-iphoneos -F/Users/zgramana/Source/mini-hacks/kitchen-sync/swift/completed/Frameworks -filelist /Users/zgramana/Library/Developer/Xcode/DerivedData/KitchenSync-hbtjaweroxojftenomzcwhsyixci/Build/Intermediates/ArchiveIntermediates/KitchenSync/IntermediateBuildFilesPath/KitchenSync.build/Release-iphoneos/KitchenSync.build/Objects-normal/armv7/KitchenSync.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=9.0 -dead_strip -fembed-bitcode -Xlinker -bitcode_verify -Xlinker -bitcode_hide_symbols -Xlinker -bitcode_symbol_map -Xlinker /Users/zgramana/Library/Developer/Xcode/DerivedData/KitchenSync-hbtjaweroxojftenomzcwhsyixci/Build/Intermediates/ArchiveIntermediates/KitchenSync/BuildProductsPath/Release-iphoneos -ObjC -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -Xlinker -add_ast_path -Xlinker /Users/zgramana/Library/Developer/Xcode/DerivedData/KitchenSync-hbtjaweroxojftenomzcwhsyixci/Build/Intermediates/ArchiveIntermediates/KitchenSync/IntermediateBuildFilesPath/KitchenSync.build/Release-iphoneos/KitchenSync.build/Objects-normal/armv7/KitchenSync.swiftmodule -framework CFNetwork -lsqlite3 -lz -framework Security -framework CouchbaseLite -framework SystemConfiguration -Xlinker -dependency_info -Xlinker /Users/zgramana/Library/Developer/Xcode/DerivedData/KitchenSync-hbtjaweroxojftenomzcwhsyixci/Build/Intermediates/ArchiveIntermediates/KitchenSync/IntermediateBuildFilesPath/KitchenSync.build/Release-iphoneos/KitchenSync.build/Objects-normal/armv7/KitchenSync_dependency_info.dat -o /Users/zgramana/Library/Developer/Xcode/DerivedData/KitchenSync-hbtjaweroxojftenomzcwhsyixci/Build/Intermediates/ArchiveIntermediates/KitchenSync/IntermediateBuildFilesPath/KitchenSync.build/Release-iphoneos/KitchenSync.build/Objects-normal/armv7/KitchenSync

ld: bitcode bundle could not be generated because '/Users/zgramana/Source/mini-hacks/kitchen-sync/swift/completed/Frameworks/CouchbaseLite.framework/CouchbaseLite(CBL_Revision.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by snej** [comment]
The older issue about bitcode has some [useful info](https://github.com/couchbase/couchbase-lite-ios/issues/916#issuecomment-147019338).

**Comment by borrrden** [comment]
The useful info includes the flag for full bitcode generation

`-fembed-bitcode` 

as opposed to the bitcode placeholder that Xcode passes during builds

`-fembed-bitcode-marker`

**Comment by snej** [comment]
I wrote a [script that checks the bitcode sizes in a library](https://gist.github.com/snej/b572157521134de83fb4) and warns about files with no bitcode or suspiciously tiny (<1kb) bitcode.

**Comment by snej** [comment]
Fix merged into dev branch. I've verified it by archiving ToDoLite.

**Comment by snej** [comment]
I had to back out this change, because it broke the build for tvOS — the build system for that platform requires `EMBED_BITCODE` to be set and fails if it isn't.

Instead we should change the Jenkins build script to do an `archive` build, which will embed the bitcode (I just verified this by doing a manual Archive build and looking at the resulting framework binaries.) The script will need to change the paths from which it copies the files, since they'll be down inside the xcarchive bundle.

**Comment by pasin** [comment]
We will need to fix libsqlcipher binary bitcode as well. I will take care this part.

**Comment by pasin** [comment]
I have fixed the libsqlcipher and tested on iOS, tvOS, and Mac platform.

**Comment by pasin** [comment]
@michaelkwok , we need to change jenkin script to do `archive` instead of `build` starting from 1.2.1.

Please let me know if you have any question.

**Comment by michaelkwok** [comment]
@pasin can you sit down with me to resolve this one?  Things I need to know
1) The scheme to use for each deliverabe (ios, tvos, macosx).  Currently, xcodebuild listed these schemes (BLIP-iOS-Carthage, Bot CBL iOS Test App, CBForest-iOS-Carthage, CBL iOS Test App, CBL Listener iOS, CBL Mac, CBL Mac Test App, CBL Mac+SQLCipher, CBL tvOS Test App, Continuous iOS, Documentation)
2) What needs to go into each package.  Is our deliverable  an .ipa file?

**Comment by pasin** [comment]
@michaelkwok We can do that this afternoon. I think we can still use target but I haven't tested it. We will not deliver .ipa file. We just need to grab the framework from the archive output directory.

**Comment by michaelkwok** [comment]
The archive action must specify a scheme per xcodebuild manual.  I tried to use -target with 'archive' and got the error "unsupported build action 'archive'"

**Comment by michaelkwok** [comment]
Pasin is going to create the new schemes below:
- CBLJSViewCompiler
- CBL Listener Mac
- LiteServ
- LiteServ App

**Comment by pasin** [comment]
We already have those schemes so we just need to share those schemes.

**Comment by pasin** [comment]
Once the PR gets merged into the dev branch, I will do the same fix to 1.2.1 branch.

**Comment by pasin** [comment]
@michaelkwok We have created 2 schemes for Jenkins to use: `CI iOS` and `CI MacOS`. One thing to note is that `LiteServ` and LiteServ App` target are only included in `CI MacOS` scheme.

**Comment by michaelkwok** [comment]
These 3 files (CBLRegisterJSViewCompiler.h, CBLJSONValidator.h, CBLJSONValidator.m) are not found in the "Extras" folder for the new "CI iOS" scheme.  They were in the Extras when built using -target but not there building with "archive".  If they are required to be in Extras, the build script would need to copy them from ./Source folder.

**Comment by michaelkwok** [comment]
Submitted previous comment prematurely...

Do we need those 3 folders to exist in the "Extras" folder with the new "archive" build?

**Comment by snej** [comment]
CBLRegisterJSViewCompiler.h should be a public header now, i.e. it should be in the framework's Headers dir. But it hasn't been marked as Public in the "CBL iOS" target, so it doesn't show up there. That should be fixed.

CBLJSONValidator files should still be in Extras. The CBL iOS target has a Copy Extras build phase that should be copying them, so I don't know why they wouldn't show up.

**Comment by michaelkwok** [comment]
I will hold off explicitly copying these files in the build script and let you and Pasin take a look.

**Comment by michaelkwok** [comment]
I have finished adding support new build action "archive".  Build #5 in Release 1.2.1has the new changes.  Note documentation is now available in macosx.

@pasin Can you all 3 packages (iOS, tvOS, macosx)?  Let me know if I need to make any other changes afterward.

**Comment by michaelkwok** [comment]
I have kick off build 1.2.1-7 with the workaround to copy the 3 missing files in Extras.  

@pasin can you verify all 3 packages?  Thanks!

**Comment by pasin** [comment]
@michaelkwok Thank you very much. I have announced this in the slack so either @ashvindersingh or @sethrosetter can verify the binary.

**Comment by pasin** [comment]
This was fixed. Verified from the iOS 1.2.1 build 10.
