### ISSUE TITLE
Pushing particular document with attachments -- SG 1.1/1.2 responds with 400 Bad Request

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-ios#1053]
I'm testing the [deepstyle sample app](https://github.com/tleyden/deepstyle-ios) (couchbase lite 1.2 / forestdb storage engine) and seeing Sync Gateway 1.1 and 1.2-rc return this error when the push replicator in the app tries to push a document with several attachments:

```
2016-01-22T18:43:54.738Z HTTP: #110:     --> 400 MIME part #3 doesn't match any attachment  (542.1 ms)
```

[Couchbase lite logs](https://gist.github.com/tleyden/b2325a3fdaa1214047c0#file-gistfile1-txt-L549):

```
11:03:50.204‖ CBLMultipartUploader[PUT http://ec2-54-161-209-25.compute-1.amazonaws.com:4985/deepstyle-cc-sg-11/-0mJlzZ5Fb_MWfHqeMNT1Nx?new_edits=false]: Got error Error Domain=CBLHTTP Code=400 "400 bad_request" UserInfo={NSURL=http://ec2-54-161-209-25.compute-1.amazonaws.com:4985/deepstyle-cc-sg-11/-0mJlzZ5Fb_MWfHqeMNT1Nx?new_edits=false, NSLocalizedFailureReason=bad_request, NSLocalizedDescription=400 bad_request}

```

It seems to cause the push replicator to stop because there are a lot of documents in the app that don't seem to get pushed up to sync gw, which I believe has to do the with error.

The tcpdump raw capture is here:

http://couchbase-mobile.s3.amazonaws.com/misc/debug-push-attachment/capture3.pcap

which can be opened in wireshark.

**Request**

<img width="1552" alt="request" src="https://cloud.githubusercontent.com/assets/296876/12520890/fb93e230-c0fb-11e5-9335-9a38a60bb416.png">

**Response**

<img width="1552" alt="response" src="https://cloud.githubusercontent.com/assets/296876/12520897/03cee9b8-c0fc-11e5-8869-4b7a6dee2825.png">

## Steps to reproduce

* Uninstall app from simulator / device
* Configure to sync with `http://demo.couchbasemobile.com:4984/deepstyle/`
* Run app, FB login with my user, pull down documents
* Stop app
* Delete bucket and restart SG on `http://ec2-54-161-209-25.compute-1.amazonaws.com:4985/deepstyle-cc-sg-11/`
* Configure app to sync with `http://ec2-54-161-209-25.compute-1.amazonaws.com:4985/deepstyle-cc-sg-11/`
* Run app
* Will try to push documents and will hit issue

**Comment by snej** [comment]
In the request you show above, what is the content of the JSON part?

**Comment by tleyden** [comment]
Here's how it's displaying in wireshark:

<img width="1552" alt="json_response" src="https://cloud.githubusercontent.com/assets/296876/12521909/7046fb84-c102-11e5-83d3-720fce325ca5.png">

**Comment by snej** [comment]
I guess that's the raw gzipped form. Any way you can get it to display it unzipped? I need to see it so I can compare the `_attachments` property with the MIME attachments.

**Comment by tleyden** [comment]
Not sure how to do it in wireshark, but I can always use a library to read the raw pcap file and then ungzip it.

What might be easier though is to just reproduce it with gzip disabled.  Do you know how I'd do this on either the couchbase lite ios or SG side?

**Comment by tleyden** [comment]
I tried disabling gzip compression on the SG side via the `compressResponse=false` setting, but the client app still is sending the json part with gzip encoding.  Is that potentially a separate issue?

I tried to verify the server behavior by issuing a curl request to the DB endpoint, here's the [server response headers](https://gist.github.com/tleyden/8d0fb78e3996b49d78a9), and I don't see anything about 'Accept-Encoding: gzip'

Packet capture -- still using gzip:

<img width="1552" alt="still_gzip" src="https://cloud.githubusercontent.com/assets/296876/12524694/b32c75da-c113-11e5-8769-06de23b6b3ee.png">

**Comment by snej** [comment]
`Accept-Encoding` is a _request_ header that applies to the response — it lets the client tell the server whether it can accept a compressed response. There isn't any mechanism that goes the other direction, i.e. for the server to say whether the client is allowed to send compressed requests. I guess it's not a common situation so HTTP/1.1 doesn't consider it. IIRC we just do a version check on SG.

Anyway, the JSON body will mostly just be the contents of the document including attachments. You could just log the doc's properties in the client to find out what they are.

**Comment by tleyden** [comment]
@pasin helped me hack the version checking in couchbase lite to prevent outgoing gzip encoding (it might be useful for debugging if this was a replicator property, would you take a PR?)

Here's a "wireshark export" of the PUT request that's failing:

https://gist.github.com/tleyden/7a222085cc84929c8489

(I can get more details if needed, like expand certain sections, etc)

And here's the JSON part from the first part of the multipart:

https://gist.github.com/tleyden/43dba257902022d7f93f

(I got this by right clicking that part, and choosing Copy / as printable text ..

**Comment by tleyden** [comment]
I should mention that this Sync Gateway document has been updated by both [go-couch](https://github.com/tleyden/go-couch) and couchbase-lite ios.  

Also, it's possible that it was touched by different versions of Sync Gateway, since I pointed both SG 1.1.1 and SG 1.2 at the same Couchbase Server bucket for purposes of upgrade testing.

**Comment by tleyden** [comment]
I just verified that it's something of an edge case, in the sense that these steps work fine:

* Start background push replication 
* Create new couchbase lite document with json + 2 attachments
* Document gets pushed up to SG without any errors 

The fact that one "corrupted" document didn't push isn't a huge deal, but the bigger issue is that it seemed to prevent the other documents in the database from being pushed.

**Comment by snej** [comment]
So, what the SG error is saying is that the SHA-1 digest it computed for the attachment `source_image` doesn't match the digest that's given in the JSON body (`sha1-rwCveXhpBcthvV/IOPSzUjBHj8A=`). Which is weird. The lengths do match (97655 bytes). Some sort of data corruption?

**Comment by tleyden** [comment]
I'm going to repeat the steps to reproduce I just added to the ticket description using the sqlite storage engine to see if I get the same behavior.

**Comment by tleyden** [comment]
Yeah, I'm getting identical behavior when using the sqlite storage engine.

**Comment by tleyden** [comment]
> Some sort of data corruption?

Here's the document as it exists on the Sync Gateway I'm pulling from:

```
curl -X "GET" "http://demo.couchbasemobile.com:4984/deepstyle/-0mJlzZ5Fb_MWfHqeMNT1Nx" \
	-H "Content-Type: application/json" \
	-d "{}"
```

returns:

https://gist.github.com/tleyden/56626454de18779946fa

**Comment by tleyden** [comment]
If I directly get the `source_image` attachment, it doesn't seem to be corrupted:

```
curl -X "GET" "http://demo.couchbasemobile.com:4984/deepstyle/-0mJlzZ5Fb_MWfHqeMNT1Nx/source_image?rev=5-fd1473c6d5a5e5f8b2673ea5af6ed2c5" > img.jpg
```

I'm able to open that in Image Preview with no issues.

**Comment by tleyden** [comment]
I retested with couchbase-lite 1.1.1 and got the same behavior, so it doesn't seem to be a recent regression.  

* [SG log output](https://gist.github.com/tleyden/c104426dd289c3149fff)
* [CBL log output](https://gist.github.com/tleyden/c7fb30400c8e4e575c49)

**Comment by snej** [comment]
By "some sort of data corruption" I mean in the contents of the attachment itself, i.e. the JPEG data.

Can you look at the attachment in the CBL database and compare it to the corresponding MIME part being sent to SG?

**Comment by tleyden** [comment]
Using this [go couchbase code](https://gist.github.com/tleyden/79decc8c130b937a314d) I grabbed the attachment out of couchbase server, and then scp'd it to my local machine as `image_data_couchbase_attachment.jpg`

I downloaded the attachment directly from sync gw via `curl -X "GET" "http://demo.couchbasemobile.com:4984/deepstyle/-0mJlzZ5Fb_MWfHqeMNT1Nx/source_image?rev=5-fd1473c6d5a5e5f8b2673ea5af6ed2c5" > image_data_sync_gateway_attachment.jpg`

Diffing the two files shows no differences:

```
$ diff image_data_sync_gateway_attachment.jpg image_data_couchbase_attachment.jpg
$
```

**Comment by tleyden** [comment]
> Can you look at the attachment in the CBL database and compare it to the corresponding MIME part being sent to SG?

Oops, looks like I read this as "Couchbase Server" database rather than CBL database.

**Comment by tleyden** [comment]
I'll try to take a closer look later, but if you want to look at the raw attachment data .. 

I uploaded the .tar.gz of `/Users/tleyden/Library/Developer/CoreSimulator/Devices/5CBDCDE3-E840-4801-98D0-673455505C79/data/Containers/Data/Application/E153F842-95C3-402E-AF7D-47E9E6E5C7C5/Library/Application Support` here:

http://couchbase-mobile.s3.amazonaws.com/misc/debug-push-attachment/couchbase_lite_deepstyle.tar.gz

I was running couchbase lite 1.1 sqlite using the steps to reproduce from the issue description.

**Comment by pasin** [comment]
Anything to do with MD5 vs SHA1?

From https://gist.github.com/tleyden/43dba257902022d7f93f, I saw SHA-1 digest.

https://github.com/couchbase/sync_gateway/blob/e1faf83a7b6afd42804ae571dfb568567e95a027/src/github.com/couchbase/sync_gateway/db/attachment.go#L346-L353

**Comment by pasin** [comment]
Please ignore my comment, SyncGateway tried to find with sha-1 first.

https://github.com/couchbase/sync_gateway/blob/e1faf83a7b6afd42804ae571dfb568567e95a027/src/github.com/couchbase/sync_gateway/db/attachment.go#L345-L353

**Comment by snej** [comment]
Traun, maybe you could add some parameters to the SG warning, to show the digest it computed and the digest in the JSON.

**Comment by tleyden** [comment]
@snej will do

**Comment by tleyden** [comment]
I added some [HTTP+ debug logging](https://github.com/couchbase/sync_gateway/blob/e2c558bd5178822cf1d2c7b5c1c7f2226f56ac55/src/github.com/couchbase/sync_gateway/db/attachment.go#L316-L396) and I'm seeing something strange in the [logs](
https://gist.github.com/tleyden/f2ff8fdce465420b8c38#file-gistfile1-txt-L20):

```
2016-01-23T23:14:13.712Z HTTP+: getting sha1 digest for 182819 bytes of data
```

That part should have a length of 97655 bytes, not 182819!  

Here's the wireshark packet capture for that request, where it clearly sends 97655 bytes:

```
MIME Multipart Media Encapsulation, Type: multipart/related, Boundary: "-9r_fmvXf-OZ1PbI6P3GLj7"
    [Type: multipart/related]
    Preamble: 0d0a
    First boundary: ---9r_fmvXf-OZ1PbI6P3GLj7\r\n
    Encapsulated multipart part:  (application/json)
        Content-Length: 2452\r\n
        Content-Encoding: gzip\r\n
        Content-Type: application/json\r\n\r\n
        JavaScript Object Notation: application/json
        Line-based text data: application/json
    Boundary: \r\n---9r_fmvXf-OZ1PbI6P3GLj7\r\n
    Encapsulated multipart part: 
        Content-Length: 68881\r\n
        Content-Disposition: attachment; filename="result_image"\r\n\r\n
        Data (68881 bytes)
    Boundary: \r\n---9r_fmvXf-OZ1PbI6P3GLj7\r\n
    Encapsulated multipart part: 
        Content-Length: 97655\r\n
        Content-Disposition: attachment; filename="source_image"\r\n\r\n
        Data (97655 bytes)
    Boundary: \r\n---9r_fmvXf-OZ1PbI6P3GLj7\r\n
    Encapsulated multipart part: 
        Content-Length: 85053\r\n
        Content-Disposition: attachment; filename="style_image"\r\n\r\n
        Data (85053 bytes)
    Last boundary: \r\n---9r_fmvXf-OZ1PbI6P3GLj7--

```

**Comment by tleyden** [comment]
I have a theory: 182819 is pretty close to 97655 + 85053 (182708).  I think if you throw in the bytes for the Boundary `\r\n---9r_fmvXf-OZ1PbI6P3GLj7\r\n` and Last boundary `\r\n---9r_fmvXf-OZ1PbI6P3GLj7--`, that could cover the remaining 111 bytes.

So it looks like somehow the multipart parsing is reading parts 3 and 4 rather than just part 3, and using that to calculate an incorrect sha1 hash.

**Comment by snej** [comment]
I think you're right; this smells like a bug in the Go multipart parser. But I don't understand why it would be happening repeatably with one set of steps but not another.

It just occurred to me that the CBL uses the same UUID generator for multipart separators as it does for docIDs, and in 1.2 I changed the format of the UUIDs and they happen to start with a hyphen now. Since a multipart boundary line starts with two hyphens, maybe having a third hyphen (at the start of the separator) is triggering this bug? (But only in some cases...)

**Comment by tleyden** [comment]
I filed issue https://github.com/golang/go/issues/14085 to see if it looks like a bug in the Go standard library.

**Comment by tleyden** [comment]
So far it's looking like an issue w/ the go multipart library .. closing this until I hear otherwise.

> Since a multipart boundary line starts with two hyphens, maybe having a third hyphen (at the start of the separator) is triggering this bug? (But only in some cases...)

It's definitely [related to the boundary](https://github.com/golang/go/issues/14085#issuecomment-174347244), but from what I can tell the boundary being sent is valid.
