### ISSUE TITLE
Test 1.2 zip file distribution

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#1054]
iOS
- [x] CouchbaseLite.framework
- [x] CouchbaseLiteListener.framework
- [x] libCBLForestDBStorage.a
- [x] libsqlcipher.a

OSX
- [x] CouchbaseLite.framework
- [x] CouchbaseLiteListener.framework
- [x] LiteServ
- [x] LiteServ App

tvOS
- [x] CouchbaseLite.framework
- [x] CouchbaseLiteListener.framework
- [x] libCBLForestDBStorage.a
- [x] libsqlcipher.a

**Comment by pasin** [comment]
From http://latestbuilds.hq.couchbase.com/couchbase-lite-ios/release/1.2.0/ios/1.2.0-80

CouchbaseLite.framework has no issue when building an app from the simulator. However when building an app for a device (iPhone 6), I got the following undefined symbols errors:

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_PSWebSocket", referenced from:
      objc-class-ref in CouchbaseLite(CBLWebSocketChangeTracker.o)
  "_register_unicodesn_tokenizer", referenced from:
      -[CBL_SQLiteStorage openFMDB:] in CouchbaseLite(CBL_SQLiteStorage.o)
  "_OBJC_CLASS_$_BLIPPocketSocketConnection", referenced from:
      objc-class-ref in CouchbaseLite(CBLBlipReplicator.o)
  "_OBJC_METACLASS_$_BLIPPocketSocketListener", referenced from:
      _OBJC_METACLASS_$_CBLSyncListenerImpl in CouchbaseLite(CBLSyncListener.o)
  "_OBJC_CLASS_$_BLIPPocketSocketListener", referenced from:
      _OBJC_CLASS_$_CBLSyncListenerImpl in CouchbaseLite(CBLSyncListener.o)
  "_OBJC_CLASS_$_BLIPHTTPLogic", referenced from:
      objc-class-ref in CouchbaseLite(CBLBlipReplicator.o)
      objc-class-ref in CouchbaseLite(CBLChangeTracker.o)
ld: symbol(s) not found for architecture arm64
```

**Comment by pasin** [comment]
$xcrun lipo -info CouchbaseLite
Architectures in the fat file: CouchbaseLite are: armv7 i386 x86_64 arm64

**Comment by pasin** [comment]
I confirmed that I don't have any issue with the binary I built myself using XCode.

**Comment by snej** [comment]
Looks like the BLIP library is missing from the ARM binaries of CBL.

Pasin, did you build a Release configuration in Xcode? (Cmd-Shift-I)

**Comment by snej** [comment]
Confirmed that I can build the CBL iOS Test App target without link errors, in Release mode.
So this is something to do with the way we're building with xcodebuild...

**Comment by pasin** [comment]
Then I noticed that jenkins build script uses `-target` (e.g. -target "CBL iOS") parameter to specify what to build. When I changed to use `-scheme` (e.g. -scheme "Continuous iOS) instead of the `-target`, the binary was generated with all architectures correctly. I haven't tried the same thing with tvOS and Mac build yet. Anyway here is the command that I use:

```
xcodebuild -scheme "Continuous iOS" -configuration Release -derivedDataPath build -destination "generic/platform=ios" clean build
```

I don't know why using `-target` doesn't work. Maybe XCode7 issue?

**Comment by michaelkwok** [comment]
Can you test with -destination "generic/platform=ios" and -target option?  Don't use -scheme.  Since we're building with no physical device present, I wonder if we need build against a platform generically now.

**Comment by pasin** [comment]
I tested it before changing to use -scheme, and the result binary had the same issue.

**Comment by pasin** [comment]
@michaelkwok I still believe that the missing part is the sdk version number. I have tried it again after you left by cleaning everything including the build folder. I can get the binary that works.

```
$rm -rf build
$xcodebuild -sdk iphoneos9.2 -target 'CBL iOS' clean
$xcodebuild -sdk iphoneos9.2 -target 'CBL iOS' build
```

Is it possible to change to this very quick on the Jenkins build? Make sure that the build folder is cleaned.

**Comment by pasin** [comment]
Actually, it turned out the version number is not required. The following works. No destination is required. Please make sure to delete build folder between running.

```
$rm -rf build
$xcodebuild -sdk iphoneos -target 'CBL iOS' clean build
```

**Comment by pasin** [comment]
@michaelkwok Would it be possible to try above quickly on Jenkins server to see if it works?

**Comment by michaelkwok** [comment]
Quick recap what we found.
- Using the same xcodebuild command (with -destination platform=tvOS/macosx), tvOS and macosx build results show BLIP was build for arm64 and x86_64.
- iOS build have an issue with the option -destination platform. When it builds without the -destination platform and setting -sdk iphoneos, BLIP library got generated and CouchbaseLite binary seems to work fine, except the target Documentation doesn't seem to get generated.  
We will try a few more things and try to close out the issue today.

**Comment by michaelkwok** [comment]
Looks like we're able to confirm -destination platform is the issue and is not needed when building -target.  We are hitting a runtime issue that seems to be a known issue with xcode7.  Working on a solution.

**Comment by pasin** [comment]
Currently we are able to build the binary but there are a lot of warning messages popping up when using the built binary. This link https://forums.developer.apple.com/thread/17921 represents the issue that we are hitting now.

From the link, an Apple staff suggested to turn CLANG_ENABLE_MODULES off. Turning CLANG_ENABLE_MODULES off did help solving the warning issue BUT a new error which is missing JSContext symbol showing up. 

In 1.2.0, we move JSViewCompiler into CouchbaseLite framework (issue #652). From that fix, an application is required to link with JavaScriptCore.framework. However enabling CLANG_ENABLE_MODULES=YES allows XCode to automatically link JavaScriptCore.framework when building an application. So disabling CLANG_ENABLE_MODULES results to that users need to link the JavaScriptCore.framework by themselves.

I discussed about the issue with @snej and it seems like we have 2 options:
1. Document that in 1.2.0, users need to link to JavaScriptCore.framework
2. Move JSViewCompiler back to extra folder

@zgramana Could you please review this?

**Comment by zgramana** [comment]
Please do #2, move JSViewCompiler back to extra folder.

**Comment by pasin** [comment]
Some good info about CLANG_ENABLE_MODULES: http://indiestack.com/2015/02/enable-clang-modules-disable-auto-linking/

**Comment by michaelkwok** [comment]
Do we plan to merge this change to master?  It will break "master" in the meantime.  And I also think we need to do the same for tvOS.

**Comment by pasin** [comment]
A new warning message issue shows up when libCBLForestDBStorage as follows:

```
warning: (x86_64) /Users/jenkins/jenkins/test/couchbase-lite-ios/vendor/CBForest/build/CBForest.build/Release-iphonesimulator/CBForest static.build/Objects-normal/x86_64/GeoIndex.o unable to open object file: No such file or directory
warning: (x86_64) /Users/jenkins/jenkins/test/couchbase-lite-ios/vendor/CBForest/build/CBForest.build/Release-iphonesimulator/CBForest static.build/Objects-normal/x86_64/slice-E2CA260402F0983F.o unable to open object file: No such file or directory
warning: (x86_64) /Users/jenkins/jenkins/test/couchbase-lite-ios/vendor/CBForest/build/CBForest.build/Release-iphonesimulator/CBForest static.build/Objects-normal/x86_64/Database.o unable to open object file: No such file or directory
warning: (x86_64) /Users/jenkins/jenkins/test/couchbase-lite-ios/vendor/CBForest/build/CBForest.build/Release-iphonesimulator/CBForest static.build/Objects-normal/x86_64/KeyStore.o unable to open object file: No such file or directory
warning: (x86_64) /Users/jenkins/jenkins/test/couchbase-lite-ios/vendor/CBForest/build/CBForest.build/Release-iphonesimulator/CBForest static.build/Objects-normal/x86_64/Document.o unable to open object file: No such file or directory
warning: (x86_64) /Users/jenkins/jenkins/test/couchbase-lite-ios/vendor/CBForest/build/CBForest.build/Release-iphonesimulator/CBForest static.build/Objects-normal/x86_64/Geohash.o unable to open object file: No such file or directory
warning: (x86_64) /Users/jenkins/jenkins/test/couchbase-lite-ios/vendor/CBForest/build/CBForest.build/Release-iphonesimulator/CBForest static.build/Objects-normal/x86_64/VersionedDocument-AC75877B749AD443.o unable to open object file: No such file or directory
warning: (x86_64) /Users/jenkins/jenkins/test/couchbase-lite-ios/vendor/CBForest/build/CBForest.build/Release-iphonesimulator/CBForest static.build/Objects-normal/x86_64/DocEnumerator.o unable to open object file: No such file or directory
warning: (x86_64) /Users/jenkins/jenkins/test/couchbase-lite-ios/vendor/CBForest/build/CBForest.build/Release-iphonesimulator/CBForest static.build/Objects-normal/x86_64/MapReduceIndex.o unable to open object file: No such file or directory
warning: (x86_64) /Users/jenkins/jenkins/test/couchbase-lite-ios/vendor/CBForest/build/CBForest.build/Release-iphonesimulator/CBForest static.build/Objects-normal/x86_64/Collatable-7E85D3B7FDB87C65.o unable to open object file: No such file or directory
warning: (x86_64) /Users/jenkins/jenkins/test/couchbase-lite-ios/vendor/CBForest/build/CBForest.build/Release-iphonesimulator/CBForest static.build/Objects-normal/x86_64/Collatable-1DA8E2290FBAEF41.o unable to open object file: No such file or directory
warning: (x86_64) /Users/jenkins/jenkins/test/couchbase-lite-ios/vendor/CBForest/build/CBForest.build/Release-iphonesimulator/CBForest static.build/Objects-normal/x86_64/varint.o unable to open object file: No such file or directory
warning: (x86_64) /Users/jenkins/jenkins/test/couchbase-lite-ios/vendor/CBForest/build/CBForest.build/Release-iphonesimulator/CBForest static.build/Objects-normal/x86_64/Tokenizer.o unable to open object file: No such file or directory
warning: (x86_64) /Users/jenkins/jenkins/test/couchbase-lite-ios/vendor/CBForest/build/CBForest.build/Release-iphonesimulator/CBForest static.build/Objects-normal/x86_64/RevTree.o unable to open object file: No such file or directory
warning: (x86_64) /Users/jenkins/jenkins/test/couchbase-lite-ios/vendor/CBForest/build/CBForest.build/Release-iphonesimulator/CBForest static.build/Objects-normal/x86_64/RevID-D530374491E3B848.o unable to open object file: No such file or directory
warning: (x86_64) /Users/jenkins/jenkins/test/couchbase-lite-ios/vendor/CBForest/build/CBForest.build/Release-iphonesimulator/CBForest static.build/Objects-normal/x86_64/RevID-5FD0FE6120B7058E.o unable to open object file: No such file or directory
warning: (x86_64) /Users/jenkins/jenkins/test/couchbase-lite-ios/vendor/CBForest/build/CBForest.build/Release-iphonesimulator/CBForest static.build/Objects-normal/x86_64/slice-7125AAA8D8C8584E.o unable to open object file: No such file or directory
warning: (x86_64) /Users/jenkins/jenkins/test/couchbase-lite-ios/vendor/CBForest/build/CBForest.build/Release-iphonesimulator/CBForest static.build/Objects-normal/x86_64/VersionedDocument-A32431EE507CF469.o unable to open object file: No such file or directory
warning: (x86_64) /Users/jenkins/jenkins/test/couchbase-lite-ios/vendor/CBForest/build/CBForest.build/Release-iphonesimulator/CBForest static.build/Objects-normal/x86_64/Index.o unable to open object file: No such file or directory
```

I understand that this issue could be fixed by setting debug log format from DWARF with dSYM File to DWARF.

**Comment by pasin** [comment]
All binaries works fine now. Tested with 1.2.0-101. 
Note:
1. I tested tvOS binaries only on the simulator.
2. I haven't tried to use CBLViewCompiler (this could be tested by PhoneGap build).
