### ISSUE TITLE
Push replication stops: only 5/68 docs pushed due to one doc having an error

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-ios#1057]
Scenario:

* Startup empty Sync Gateway (empty meaning the backing couchbase server bucket was flushed prior to starting up Sync Gateway)
* Start couchbase lite app with 68 docs locally, configured for push replication to Sync Gateway (there's also a pull replication running, but there's nothing to pull)
* After it pushes 5 documents, it runs into a problematic document (as described in https://github.com/couchbase/couchbase-lite-ios/issues/1053)

**Expected**: the push replication will skip that document and push the rest
**Actual**: the push replication seems to just stop and doesn't try to push any of the other docs 

If this is considered the intended behavior in this case, then just close this ticket out.  Otherwise, I can provide more details to debug it.

**Comment by tleyden** [comment]
@snej is it the expected behavior that the push replicator would stop if it gets a 4xx error from Sync Gateway and not try to push the rest of the docs?  

If not, it would be a good time to look into it because I can easily reproduce it now.

**Comment by snej** [comment]
Stopping on a 4xx error seemed like the correct behavior at the time — "crap, something is seriously wrong, give up" — but in several actual cases where it's happened due to bugs in CBL or SG, it seems it would have been better to continue and just skip that document. So I should rethink that.

If we did continue, we should really have finer-grained error reporting in the public API that would let the developer know that some docs failed to sync, and which ones and what the errors were. (That's #293.)

**Comment by tleyden** [comment]
What about allowing api users to have a registered callback function whose result would help the replicator decide what to do?  

```
push.addErrorCallback(
  func(docId, error) -> what_to_do {
    if docId == "settings" {
       // nothing will work if the settings doc doesn't sync, so just give up at this point
       return abort_replication
    }
    // as long as it's not the settings doc, we can probably safely ignore it .. write some logs and/or alert the user, but keep going
    return keep_going!
  }
)
```

If a developer didn't register a callback function, then it would just keep the current behavior and stop -- this does have the advantage of having errors of being very easy to notice since they bring the whole replication to a screeching halt.

**Comment by snej** [comment]
That seems like a good comment to add to #293.

**Comment by tleyden** [comment]
Ok I added.  Should I just close this as a dupe of #293?

**Comment by snej** [comment]
I think so. We _could_ downgrade 4xx errors and have the replication continue, but I'm uncomfortable doing that without some means of notification.
