### ISSUE TITLE
liteserv binary doesn't use the ForestDB when specified via 'defaults' mac command

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/couchbase-lite-ios#1062]
Steps to reproduce:

- Download and unzip macos build 1.2.0-85. http://latestbuilds.hq.couchbase.com/couchbase-lite-ios/release/1.2.0/macosx/1.2.0-85/
-  Execute the following command to set ForestDB as default CBLStorageType:
```
defaults write com.couchbase.LiteServ CBLStorageType ForestDB
```
- cd into the unpacked binary location and find liteserv
- Launch liteserv
```
./LiteServ --dir .

```
- Create a db via REST API

```
PUT http://ashvinders-macbook-pro.local:59840/mydb

```

- cd into the current database dir "mydb.cblite2"
- Found the following file:
```
attachments/    db.sqlite3      db.sqlite3-shm  db.sqlite3-wal 
```
##### No ForestDB file found. 
- Rerun the command to verify ForestDB is set
```
defaults find ForestDB
```
Output of defaults command:
```
Snipped...
Found 2 keys in domain 'com.couchbase.LiteServ': {
    CBLStorage = ForestDB;
    CBLStorageType = ForestDB;
}
```

**Comment by snej** [comment]
As I told Pasin, that only works with the bundled app version, not the command-line too. That's because the tool doesn't have a bundle ID so it doesn't have persistent defaults. Sorry!

I just added a `--storage` flag to the tool, but it's on the master branch (commit a804f0168478687073bc7aeec68fc43611d63569). If this is a testing blocker, you could ask Zack about getting it into 1.2.

**Comment by zgramana** [comment]
Go ahead and cherry pick it onto the release branch, since it doesn't require re-testing everything else.

**Comment by snej** [comment]
Done: commit 99e45036f6a664799f0cdd310c71ba7360a914bc on `release/1.2.0` branch

**Comment by snej** [comment]
I found a build setting that gives the tool a bundle ID so it will read user defaults set via the `defaults` tool, same as the app. I've applied it, on the master branch.

**Comment by ashvindersingh** [comment]
Cool this is going to useful. Thanks!
