### ISSUE TITLE
ForestDB issue

### ISSUE THREAD

**Issue by coleifer** [couchbase/couchbase-lite-ios#1067]
Hi, I have two questions.

I've been writing some Python language bindings for ForestDB. You can find them [here](https://github.com/coleifer/forestdb-python).

My first question is, **where can I create forestdb issues?** I noticed that your forestdb repository on GitHub does not seem to have the "issues" tab enabled. Is there a separate issue tracker?

My second question is that in benchmarking I noticed that forestdb performs markedly slow on writes both ordered and random. I benchmarked forestdb against berkeleydb, kyotocabinet, leveldb, sqlite4 LSM and sophia. The benchmark writes 250K key/value pairs where both key and value correspond to 8-bytes zero-padded from `00000001` to `00250000`. Here are the times I'm getting:

```
              berkeleydb
                  Sets:  1.294
                  Gets:  1.4055
           Random Sets:  2.87
           Random Gets:  2.2253
                Ranges:  0.7159
------------------------------------------------------------
                forestdb
                  Sets:  4.0165
                  Gets:  1.2353
           Random Sets:  6.7374
           Random Gets:  1.6482
                Ranges:  0.9619
------------------------------------------------------------
                 kc-tree
                  Sets:  0.3794
                  Gets:  0.5417
           Random Sets:  0.5855
           Random Gets:  0.7545
                Ranges:  0.7772
------------------------------------------------------------
                 leveldb
                  Sets:  0.5006
                  Gets:  0.6738
           Random Sets:  0.664
           Random Gets:  1.0043
                Ranges:  0.1358
------------------------------------------------------------
                  sophia
                  Sets:  0.6147
                  Gets:  4.0233
           Random Sets:  0.8156
           Random Gets:  5.313
                Ranges:  0.4974
------------------------------------------------------------
                     lsm
                  Sets:  0.9623
                  Gets:  0.6001
           Random Sets:  1.0916
           Random Gets:  0.8242
                Ranges:  0.1713
------------------------------------------------------------
```

As you can see, ForestDB's writes are an order of magnitude slower than kyotocabinet, leveldb, and sophia.

Does this result make any sense? I am using the default configuration for both the forestdb environment and key/value store.

**Comment by snej** [comment]
The ForestDB project uses [Couchbase's Jira server](https://issues.couchbase.com/secure/RapidBoard.jspa?rapidView=63&view=planning.nodetail&epics=hidden) to track issues. You're welcome to sign up for an account and post issues there.

There is a ForestDB [mailing list](https://groups.google.com/forum/#!forum/forestdb) on Google Groups. I have no idea what to make of your benchmark results, but I'm sure the ForestDB engineers will be interested in discussing them with you.

**Comment by coleifer** [comment]
Thank you for the prompt reply, I'll follow up on the mailing list, thanks.
