### ISSUE TITLE
Seeing errors in logs of demo app:  WARNING: Unable to open index of CBL_ForestDBViewStorage: 500 Database error

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-ios#1068]
I'm using a recent commit (1-2 weeks ago) of couchbase lite ios -- sorry, I don't know the exact commit because I built it locally and copied the framework over to my app's directory, and then later updated my couchbase lite ios repo.

The app is using forestdb via:

```
CBLManager.sharedInstance().storageType = kCBLForestDBStorage
```

and is running on an iphone 6 with ios 8.3

I believe I'd recently uninstalled the app from the device and was running fresh.

I noticed the following errors in the [app logs](https://gist.github.com/tleyden/7bcc8949b0702980dd1e):

```
2016-01-27 11:05:08.185 DeepStyle[3289:885750] WARNING: ForestDB error: error opening file (-2)
2016-01-27 11:05:08.187 DeepStyle[3289:885750] WARNING: Unable to open index of <CBL_ForestDBViewStorage: 0x1742c1ab0>: Error Domain=CBLHTTP Code=500 "500 Database error!" UserInfo=0x170678300 {NSLocalizedFailureReason=Database error!, NSLocalizedDescription=500 Database error!}
```

I did notice some memory warnings:

```
2016-01-27 11:13:11.504 DeepStyle[3289:885654] Received memory warning.
```

Not sure how reproducible this is.

**Comment by tleyden** [comment]
I tried to use iExplorer to grab the data files:

* attachments
* db.forest.0 (1 MB)
* db.forest.meta (1 kB)
* recentJobs.viewIndex.0 (622 kB)
* recentJobs.viewIndex.meta (1 kB)

however only the attachment folders copied over.

**Comment by tleyden** [comment]
I should mention that there is no noticeable problem in the app -- just seeing those errors in the logs.

**Comment by EthanRTF** [comment]
@tleyden When you get that error, does it continue to use ForestDB, or does it switch back to SQLite? I seem to recall having a similar issue before and it changed to SQLite automatically when it encountered that error.

**Comment by snej** [comment]
No, it won't change to SQLite just because it got an error.

**Comment by snej** [comment]
That's this ForestDB error. I believe it means the filesystem `open()` call failed.
```c
    /**
     * Database open operation fails.
     */
    FDB_RESULT_OPEN_FAIL = -2,
```

**Comment by zgramana** [comment]
Perhaps the FDB view files are marked NSFileProtectionComplete and the database is being accessed via background app refresh callback?

**Comment by tleyden** [comment]
@zgramana I don't have background app refresh enabled (yet)

**Comment by tleyden** [comment]
I tried to leave everything in the same state, so it should be possible to debug this further.  I can rebuild couchbase lite with added debug statements and re-run.

**Comment by tleyden** [comment]
I have tried to reproduce several times, but no luck.

**Comment by snej** [comment]
Filed [a ForestDB issue](https://issues.couchbase.com/browse/MB-17757) regarding the inability to get the real error code.
