### ISSUE TITLE
Couldn't unzip compressed message

### ISSUE THREAD

**Issue by cflorion** [couchbase/couchbase-lite-ios#1074]
As I was testing my app once, at one point it stopped syncing. I looked at the logs and saw the following message:
`
2016-01-28 11:47:07.168 CBLIS iOS Test App[2937:1179248] WARNING: CBLWebSocketChangeTracker: Couldn't unzip compressed message; status=-3
`

 This line kept being logged over and over again as I was using the app. I had to relaunch the app in order for it to work again. I haven't succeeded to reproduce this bug yet.
I am posting this message to know if you ever encountered this and if this is something that can happen and that is not that serious ?

Thanks :)

**Comment by zgramana** [comment]
@cflorion can you provide full logs, including the version of CBL that you're running? And which version of SG are you running against?

**Comment by snej** [comment]
That warning is at CBLWebSocketChangeTracker:187 (in -webSocket:didReceiveMessage:.) It indicates gzip decompression ("inflate") got a zlib error -3, which is Z_DATA_ERROR; interpretation is that "the input data was corrupted (input stream not conforming to the zlib format or incorrect check value)" (see zlib.h.)

**Comment by snej** [comment]
When that error occurs, the change tracker closes the WebSocket, because once you're out of sync reading the gzip stream you can't recover. So if the warning keeps being logged, it means the error keeps happening on successive WebSocket connections.

It'd be helpful to see the SG logs from that time period too.

**Comment by cflorion** [comment]
@zgramana The version of the CBL is the current master branch (#1060). The SG is the current master branch of a week ago.

Unfortunately I have not been able to reproduce this bug yet, once I do I'll post the logs.

Would it be a good idea to have like a method that reset and retry the connection in order to have a clean state ? It's just strange that the error kept happening over and over again...
Anyways, I'll keep you posted :)

Cheers.

**Comment by snej** [comment]
It _does_ close the connection and reconnect, after this error occurs. That's what makes it especially weird that it happened multiple times…

**Comment by snej** [comment]
A forum user ran into this and was able to [capture some logs](https://forums.couchbase.com/t/14-31-48-705-warning-cblwebsocketchangetracker-couldnt-unzip-compressed-message-status-3/7454/5).

**Comment by K-Leon** [comment]
I stumbled over this bug also. The logs are equal to them the noted forum user collected, but i managed to get a little bit background to what happened and i'm convinced that this bug is related to filesize. 

Specifically i had deleted around 20k documents, that got synced down to the device resulting in real large packages. The packages itself seem to be fine - same for sync gateway so far i can tell while looking at the packages with charles.

**Comment by snej** [comment]
By "packages" do you mean WebSocket messages?

**Comment by K-Leon** [comment]
Yes

**Comment by snej** [comment]
Sync Gateway is calling Flush on the GZipWriter at the end of every message; according to the [Go package docs](https://golang.org/pkg/compress/gzip/#Writer.Flush), that's the equivalent of zlib's `Z_SYNC_FLUSH`, which is the appropriate thing to do in this case. So the sending side seems correct.

**Comment by snej** [comment]
I still don't know why the gzip error occurs initially. But I discovered a bug that would cause it to keep happening after that, when the socket reconnects, because it wasn't resetting its gzip decoder.

**Comment by snej** [comment]
I think what might have happened initially is that the websocket got disconnected for some transient reason, and on reconnect the gzip decoder was out of sync and kept logging these errors. So I believe the problem is actually fixed.

**Comment by npomfret** [comment]
I've found it's easy to produce by just turning the sync-gateway off and on again.

**Comment by snej** [comment]
It'll be in 1.3. Unfortunately this was fixed too late to make it into 1.2.1 (which is going to be released any day). I don't know if we're doing to do a 1.2.2, but if we do this fix will be in it. I added the hotfix label to indicate that.

**Comment by npomfret** [comment]
Hi - any news on getting 1.3 out?  As soon as my app loses its connection with the sync_gateway it suffers from the problem and becomes unusable.  I can't figure out a workaround so really need a proper fix.  Mobile devices obviously lose connectivity regularly.

**Comment by snej** [comment]
1.3 is still in development, but I've cherry-picked the fix into the `release/1.2.2` branch. This branch is based on 1.2.1, with just two minor changes for CouchDB compatibility, so it should be stable.

**Comment by npomfret** [comment]
Thanks.

Silly question maybe, but where do I download 1.2.2?

**Comment by snej** [comment]
We don't have a build train set up for it yet, so for now you'll need to check it out from Github and build it yourself (we have directions; see the README.)
