### ISSUE TITLE
-[CBL_SQLiteStorage lowMemoryWarning]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by brendand** [couchbase/couchbase-lite-ios#1079]
When memory is severely constrained, I get this crash right after applicationDidReceiveMemoryWarning: is called.

```
Tap Forms[862:279081] Received memory warning.
Tap Forms[862:279081] applicationDidReceiveMemoryWarning
Tap Forms[862:280953] -[CBL_SQLiteStorage lowMemoryWarning]: unrecognized selector sent to instance 0x13058bdb0
Tap Forms[862:279081] -[CBL_SQLiteStorage lowMemoryWarning]: unrecognized selector sent to instance 0x130748130
```

Using CBL 1.2 with SQCipher on iOS 9.2.1 at the moment.

**Comment by snej** [comment]
Oh crap, that's an `@optional` method in our storage-engine protocol, which only the ForestDB storage implements, but the caller isn't checking if it's implemented :(

**Comment by snej** [comment]
Tentatively assigning to 1.2 milestone so we can triage it. It may be too late though…

**Comment by snej** [comment]
Fixed on release/1.2 branch. Will be merged into master soon.

**Comment by brendand** [comment]
Thanks for the quick fix! I've been testing with a database of over 100,000 documents, so it was easy to trip up.

**Comment by snej** [comment]
You were just in the nick of time — I think if you'd waited till Monday to file the bug, we wouldn't have been able to get it into 1.2. So glad that got fixed.
