### ISSUE TITLE
[tvOS] Getting exception when run on workerbee app

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/couchbase-lite-ios#1080]
Steps to reproduce: 
- Git clone https://github.com/couchbaselabs/iOS-WorkerBee.git
- Copy and link 1.2.0-101 tvOS binaries of Couchbselite.framework and CouchbaseLiteListener.framework
- Select the tvOS scheme and simulator
- Add the following option in scheme in section "Run" with params "-RunTest Test1_CreateDocs"
- Run 
- Get the following exception: https://gist.github.com/ashvindersingh/215fcb8579592fc7fa11

**Comment by pasin** [comment]
Close as duplicate as #1081
