### ISSUE TITLE
CBL tvOS Test App scheme giving errors when trying to run tvOS Unit tests

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/couchbase-lite-ios#1087]
Steps: 
- git clone couchbase-lite-ios
- cd couchbase-lite-ios
- git checkout release/1.2.0
- git submodule update --init --recursive
- Open xcode project and select CBL tvOS Test App. 
- Click run. Got the following errors:

<img width="1440" alt="screen shot 2016-02-01 at 11 21 18 pm" src="https://cloud.githubusercontent.com/assets/2374160/12742437/9855ef78-c93a-11e5-870e-a2ae592a0b9d.png">

<img width="1440" alt="screen shot 2016-02-01 at 11 22 21 pm" src="https://cloud.githubusercontent.com/assets/2374160/12742446/ad21ac4e-c93a-11e5-9c91-03cf3e1afda7.png">

**Comment by pasin** [comment]
@ashvindersingh I just push the fix to the tvOS Unit Test app. Could you please update and try again?

**Comment by ashvindersingh** [comment]
@pasin this fixes the previous issue but now got the following errors. 
<img width="1440" alt="screen shot 2016-02-01 at 11 59 33 pm" src="https://cloud.githubusercontent.com/assets/2374160/12743071/ed4713cc-c93f-11e5-8ea8-7d68f0261cde.png">

**Comment by pasin** [comment]
I couldn't reproduce this when running with the tvOS simulator. Not sure why it happens.

**Comment by ashvindersingh** [comment]
Yup, with simulator there are no errors but with AppleTV device I get the above errors.

**Comment by pasin** [comment]
Let me try it out with your device tomorrow.

**Comment by ashvindersingh** [comment]
sounds good!

**Comment by snej** [comment]
Please copy/paste the text of the errors from the build log, instead of attaching screenshots. The screenshots can be a pain to read, and the text isn't searchable.

**Comment by snej** [comment]
@pasin, you can build for an AppleTV without having a device connected. In the scheme's destination pop-up choose "Generic tvOS device".

**Comment by pasin** [comment]
I tried that already last night on with 'Continuous iOS' and 'CBL tvOS Test App' scheme but I couldn't reproduce the issue. I think the issue happens at runtime while the unit tests are trying to access to those symbol.

**Comment by pasin** [comment]
Hold on, I can now reproduce the issue when I build for testing. The issue didn't happen when I build for running.

**Comment by snej** [comment]
These kind of things should really be build failures. The build-bot should build the test apps to catch them. Just filed https://issues.couchbase.com/browse/CBL-48
