### ISSUE TITLE
test04_ReplicateAttachments should increase timeout for real device testing

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#1094]
The default timeout is 15 seconds but often it's not enough to replicate the large attachment to and from the real device. I observed that the replication time could take up to around 25 - 30 seconds for either push or pull replication.

**Comment by snej** [comment]
IIRC there's a 30MB attachment in that database. Still, 30MB in 15 sec = ~20 megabits/sec, which doesn't seem unreasonable. What was the network connection like? WiFi or cell?

**Comment by pasin** [comment]
I tested that with my home wifi and the connection was good. I also noticed the same behavior yesterday when testing on the office 'Couchbase Mobile' wifi.

**Comment by snej** [comment]
Might be worth profiling sometime. But yeah, increasing the timeout makes sense, esp. if we ever decide to test over real cell connections (or fake cell connections using the Network Link Provisioner tool.)
