### ISSUE TITLE
iOS - invalid revpos warning, CBLRestPuller does not stop but document not in database

### ISSUE THREAD

**Issue by SalmanZafar1105** [couchbase/couchbase-lite-ios#1096]
18:39:47.474‖ WARNING: Attachment 'tomatosoup.png' in -4fdf6fe7284dc76acd2eb2b6551ab408 #1-46fd004b476fba9f72a416876c7f6b6c} has invalid revpos=20
18:39:47.492‖ WARNING: CBLRestPuller[]: Revision {-4fdf6fe7284dc76acd2eb2b6551ab408 #1-46fd004b476fba9f72a416876c7f6b6c} has invalid attachment metadata: {
    "tomatosoup.png" =     {
        "content_type" = "image/jpeg";
        digest = "md5-09GXuqgMa/rj1CVk+H2Cww==";
        follows = 1;
        length = 95418;
        revpos = 20;
    };
}

**Comment by snej** [comment]
What versions of Couchbase Lite and Sync Gateway?

**Comment by SalmanZafar1105** [comment]
Couchbase Lite - 1.2
Sync Gateway - 1.1.0

**Comment by snej** [comment]
From the digest being md5, it looks like this revsion came from CouchDB.

**Comment by SalmanZafar1105** [comment]
Yes, the revision came from CouchDB. The couchbase server copies the attachments from one document to another. In copying the revpos does not change in the attachment metadata.

**Comment by snej** [comment]
How are you copying the attachments from one document to another? Are you using the SG REST API, or directly modifying the Couchbase bucket?

When an attachment is added to a document, the `revpos` needs to be updated to match the revision it's added in.

**Comment by SalmanZafar1105** [comment]
I asked the backend team, they said - 

"For Example I want to copy attachment from document docone to doctwo, I have to find and copy the key "_attachment" and add to the my new document doctwo.."

**Comment by snej** [comment]
Yes, but exactly how are they modifying doctwo? What API are they calling?

If they're modifying the documents in the Sync Gateway bucket using Couchbase Server APIs, tell them they shouldn't do that. That's the source of this bug — it's corrupting the state of the documents by creating illegal revpos values.

**Comment by zgramana** [comment]
@SalmanZafar1105 If your team wasn't using SmartClient to modify the document on Couchbase Server, please re-refile this issue so we can track it down.
