### ISSUE TITLE
CBLListener running on Apple TV cannot be accessed via bonjour (.local) host name

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#1098]
This has been tested by trying to connect to the listener started by Listener_Tests.test03_ReadOnly. The listener URL is `https://Apple-TV.local:60000/db`. However the listener can be accessed via the AppleTV IP Address. All test machines connect to an Apple Airport router.

With the same issue, the following unit tests failed:
- Listener_Tests
- ListenerHTTP_Tests
- P2P_HTTP_Tests

**Comment by snej** [comment]
Should re-test with current OS since this may have been a system Bonjour issue.

**Comment by pasin** [comment]
Closed as not fix.
