### ISSUE TITLE
Compile errors using the latest 1.2.0-112 binaries for Couchbase lite -ios

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/couchbase-lite-ios#1099]
Steps to reproduce: 
- git clone https://github.com/couchbaselabs/ToDoLite-iOS.git
- cd ToDoLite-iOS
- open ToDoLite.xcodeproj/
- Modify the AppDelegate.m file 
```
 #define kSyncGatewayUrl @"http://ec2-54-145-244-2.compute-1.amazonaws.com:4984/todolite12rc2b-cc/"

#define kStorageType kCBLForestDBStorage

#define kSyncGatewayWebSocketSupport YES


// add this option in method (CBLDatabase *)databaseForName:(NSString *)name {
// 
option.encryptionKey = @"seekrit";
```
- Download the latest enterprise binary: http://latestbuilds.hq.couchbase.com/couchbase-lite-ios/release/1.2.0/ios/1.2.0-112/

- Unzip the package
- Copy and paste couchbaselite.framework , libCBLForestDBStorage.a and libsqlcipher.a into the Frameworks folder of Todolite app.
- From a finder window open Frameworks folder and drag and link with xcode: 
- couchbaselite.framework. Complete the linking process. 
- drag and link libCBLForestDBStorage.a from Frameworks folder
- and do the same steps for libsqlcipher.a

- Select your connected iphone and run
- see the following errors;

```
"___asan_stack_malloc_1", referenced from:
      ___54-[CBL_ForestDBViewStorage openIndexWithCreate:status:]_block_invoke in libCBLForestDBStorage.a(CBL_ForestDBViewStorage.o)
      -[CBL_ForestDBViewStorage deleteIndex] in libCBLForestDBStorage.a(CBL_ForestDBViewStorage.o)
      -[CBL_ForestDBViewStorage deleteViewFiles:] in libCBLForestDBStorage.a(CBL_ForestDBViewStorage.o)
      ___59-[CBL_ForestDBViewStorage fullTextQueryWithOptions:status:]_block_invoke_2 in libCBLForestDBStorage.a(CBL_ForestDBViewStorage.o)
      ___59-[CBL_ForestDBViewStorage fullTextQueryWithOptions:status:]_block_invoke259 in libCBLForestDBStorage.a(CBL_ForestDBViewStorage.o)
      CocoaIndexer::addDocType(cbforest::alloc_slice const&) in libCBLForestDBStorage.a(CBL_ForestDBViewStorage.o)
      cbforest::IndexEnumerator::key() const in libCBLForestDBStorage.a(CBL_ForestDBViewStorage.o)
      ...
```
Complete logs: https://gist.github.com/9625f32a93d5cb2a0c91

**Comment by snej** [comment]
`___asan_stack_malloc_1` is a symbol from the Address Sanitizer, which is a debugging tool. It looks like (some of) the code got built with address sanitization turned on, so it emits calls to those functions. Address Sanitization is a scheme option, in the Diagnostics tab.

**Comment by snej** [comment]
I downloaded the iOS build from the above URL, and the `nm` tool doesn't list any `__asan`... symbols in it at all. Pretty sure those symbols are added at compile time not link time.

My guess is that ToDoLite isn't actually linking against that copy of the framework, but some debug copy you've got on your machine that has address sanitization enabled.

**Comment by pasin** [comment]
FYI, both I and @sethrosetter couldn't reproduce the issue.

**Comment by pasin** [comment]
@ashvindersingh Can we close this now?

**Comment by ashvindersingh** [comment]
Yes we can close this issue.

After re-setting the Derived Data location to default the errors disappeared.
