### ISSUE TITLE
Re-write user provided URLs to remove inline auth credentials

### ISSUE THREAD

**Issue by jordanpwood** [couchbase/couchbase-lite-ios#1117]
I really appreciate the way the replication logs replace the password in the URL with "*****", it makes sharing those logs safe.  However, I fount that the following doesn't remove the password field:
```
07:45:14.167‖ CBLRemoteJSONRequest[POST https://couchClient:*****@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb/_bulk_docs]: Got error Error Domain=CBLHTTP Code=500 "500 internal server error" UserInfo={NSURL=https://couchClient:[redacted]@browzine.cloudant.com:443/user-3111fc40-d0d2-11e5-b36b-2776274391bb/_bulk_docs, NSLocalizedFailureReason=internal server error, NSLocalizedDescription=500 internal server error}
```
I put in the "[redacted]" part.  Could you remove the password from this sort of error message as well?

Thanks!

**Comment by snej** [comment]
Everything on that line after `Got error:` is the output of `-[NSError description]`, i.e. it's defined by the Foundation framework, not our code. The only way to do this, I think, would be to copy the userInfo dictionary from the NSError, get the `NSURLErrorKey` property, make a copy of that URL with the password removed, stuff that into a copy of the userInfo dictionary, and make a copy of the NSError with the new dictionary. Whew.

A better solution would be for you to avoid putting passwords into URLs. At one point it was sometimes necessary with CBL to work around auth issues, but it shouldn't be anymore. You should set the authentication properties on the CBLReplication instead.

**Comment by snej** [comment]
After discussion, we may fix this by having CBLReplication detect a password in a URL, and rewrite the URL without the password, then set a CBLAuthenticator for you.

It would be too hard to find every single place where we pass an NSError value as a parameter to our logging functions, and wrap it with something to censor the password as described above.

**Comment by snej** [comment]
Alright, I _did_ find every single place where we pass an NSError value as a parameter to our logging functions, and changed them to call a new category method `my_compactDescription` that logs just the important stuff (_and_ redacts passwords in any associated URLs.)
