### ISSUE TITLE
Is it possible to migrate TouchDB files using CouchbaseLite 1.2?

### ISSUE THREAD

**Issue by aepryus** [couchbase/couchbase-lite-ios#1119]
I'm not sure if I'm perhaps doing something wrong, but the last version of CouchbaseLite that seems to be able to migrate TouchDB files is 1.0.4.

Has the processed changed or was support for migrating TouchDB dropped?

**Comment by snej** [comment]
TouchDB was never an official product, so we've never officially supported migrating from it. I honestly don't know what the status is. We've gone through over time and cleaned up initialization code; it looks as though currently it can't migrate from very old SQLite schema versions (less than 17). Your best bet is to update from TouchDB using the older version of CBL, then update to 1.2.
