### ISSUE TITLE
Warn if map function calls emit(nil, ...)

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1120]
`nil` is not a valid key. If a map function passes a nil key to the emit block, it should log a warning and do nothing.

The code on the master branch will instead emit a JSON `null` key if it's a SQLite database, or crash(!) if it's ForestDB. The crash is a post-1.2 regression.

**Comment by hermanccw** [comment]
@snej just updated to version 1.3.2 and this change broke quite a bit of my app.  I can fix it by emitting some predefined "nil" value has the key that's not nil, but just wondering why nil is not a valid key since in CouchDB, you can definitely emit nil as a key and the view will work fine.
