### ISSUE TITLE
Version number on CBL ios 1.2 is 1.2 (unofficial)

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-ios#1130]
From https://forums.couchbase.com/t/is-couchbase-lite-1-2-really-out/6959

> but after downloading that version the CBLVersion number is "1.2 (unofficial)"

I didn't have a chance to check this myself, just going off that report.

**Comment by zgramana** [comment]
I'm using the 1.2 release binary on my machine and it correctly reads:
```
1.2.0 (build 112)
```
