### ISSUE TITLE
CBLVersion() incorrectly returns "(unofficial)" in official releases

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1131]
As discovered in [this forum thread](https://forums.couchbase.com/t/is-couchbase-lite-1-2-really-out/6959), the result of calling `CBLVersion()` in the official 1.2 release is `@"1.2 (unofficial)"`. But only if you run it in the iOS simulator — on a device, or in a Mac OS app, you correctly get `@"1.2.0 (build 112)"`.

The cause of this is that the constant `CouchbaseLiteVersionNumber` is 0.0 in the simulator builds. And that's because the build setting `CURRENT_PROJECT_VERSION` has its default value of `0`. The [build script](https://github.com/couchbase/build/blob/master/scripts/jenkins/mobile/build_cblite_ios.sh#L208) overrides it to the correct build number when invoking xcodebuild, but that's not taking effect when the simulator binaries are compiled. And _that_ seems to be due to BuildFatLibrary.sh.

**Comment by michaelkwok** [comment]
Latest build #588 is still showing zero.  I looked in the master branch and don't see the changes in BuildFatLibrary.sh.

**Comment by snej** [comment]
I haven't committed the change yet, because I'm still waiting for you to code-review it (#1133). Sorry I forgot about this important detail when you came over earlier.

**Comment by michaelkwok** [comment]
Build 589 looks good now
