### ISSUE TITLE
Define test profiles for Sanity, Nightly, and Release profiles

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-ios#1134]

**Comment by snej** [comment]
All the CBL unit tests should be run for sanity tests.

**Comment by snej** [comment]
It would be good to have a test that involves an Archive build of an app. That would verify that we have proper bitcode in our libraries, for example. Probably doesn't need to be done nightly.

**Comment by snej** [comment]
TBD: Meet with @ashvindersingh and @sethrosetter to verify this makes sense.

**Comment by snej** [comment]
@sethrosetter, @michaelkwok : Can you use this as input for setting up automated testing, or manual test schedules? I think we've done our work here in defining what's to be tested when.
