### ISSUE TITLE
CBLAuthenticator (1.2) basic authenticator fails to send Authorization header

### ISSUE THREAD

**Issue by martinrybak** [couchbase/couchbase-lite-ios#1147]
I have a basic push/pull replication setup to a local CouchDB 1.6.1 server:
```
	NSURL* syncURL = [NSURL URLWithString:@"foo"];
	id<CBLAuthenticator> authenticator = [CBLAuthenticator basicAuthenticatorWithName:@"foo" password:@"bar"];
	self.pull = [self.database createPullReplication:syncURL];
	self.push = [self.database createPushReplication:syncURL];
	self.pull.continuous = YES;
	self.push.continuous = YES;
	self.pull.authenticator = authenticator;
	self.push.authenticator = authenticator;
	[self.pull start];
	[self.push start];
```

This works fine with CBL 1.1.1. Looking at the CouchDB logs, I see the following header info:
```
Headers: [{'Accept',"application/json"},
          {'Accept-Encoding',"gzip, deflate"},
          {'Accept-Language',"en-us"},
          {'Authorization',"Basic xxxxxxxxxxxxxxxxxx"},
          {'Connection',"keep-alive"},
          {'Host',"localhost:5984"},
          {'User-Agent',"CouchbaseLite/1.1 (iOS)"}]
```

However, I get a **401 Unauthorized** error when after upgrading to CBL 1.2, and replication does not work. The logs now show that the **Authorization** header is missing:
```
Headers: [{'Accept',"application/json"},
          {'Accept-Encoding',"gzip, deflate"},
          {'Accept-Language',"en-us"},
          {'Connection',"keep-alive"},
          {'Host',"localhost:5984"},
          {'User-Agent',"CouchbaseLite/1.2 (iOS 1.2)"}]
```

I also tried setting the **credential** property with an **NSURLCredential** object. Same results.

--------
* Version:  1.2
* Client OS: 8.4
* Server:    CouchDB 1.6.1

**Comment by snej** [comment]
There are some changes in basic auth in 1.2 (basically, we switched to the regular challenge/response style of doing basic auth) and it sounds like this is interacting badly with a longstanding glitch/bug in CouchDB (it sends a 401 response without a WWW-Authenticate header, so clients expecting to do challenge/response won't work.)

Our changes also caused some glitches (see #1127) so we're rolling back to proactively sending the Authorization header. This will be in the 1.2.1 release, or you can get it now by checking out the `fix/1.2+basic_auth` branch.
