### ISSUE TITLE
CBLRestReplicator does not properly end bgTask when app is foregrounded

### ISSUE THREAD

**Issue by robertjpayne** [couchbase/couchbase-lite-ios#1152]
When the app comes back to the foreground CBLRestReplicator is not ending the bg task on its `_bgMonitor` ivar. This produces a crash the next time the app is put into the background.

#### Reproduction Steps:

1. Launch app with a continuous replication via REST
2. Put app into background
3. Put app into foreground
4. Put app into background

#### Expected Results:

App is put into background and continues to replicate

#### Actual Results:

The app crashes with logs like:

```
*** Assertion failure in -[MYBackgroundMonitor beginBackgroundTaskNamed:](), couchbase-lite-ios/vendor/MYUtilities/MYBackgroundMonitor.m:65`
```

--------
* Version:   1.2
* Client OS: iOS 9.3
* Server: CouchDB 1.2

**Comment by robertjpayne** [comment]
Ah I just noticed this is fixed via:

```
- (void) appForegrounding {
    // Danger: This is called on the main thread!
    [self.db doAsync: ^{
        if ([_bgMonitor endBackgroundTask])
            LogTo(Sync, @"%@: App foregrounded, ending background task", self);
        [self setSuspended: NO];
    }];
}
```

I think this may still cause a crash in some situations, you end the BG activity on the DB's thread but you start the BG activity on the main thread. Assuming the DB thread is busy and the user puts the app back into the BG it would still fail.

**Comment by snej** [comment]
Yeah, for the record, the crash report is a dup of #1006. (The fix will go out in the 1.2.1 update.)

**Comment by snej** [comment]
Robert, I'm not following your potential failure scenario — could you break it down into steps? And do you have an idea of how to fix it?

**Comment by robertjpayne** [comment]
@snej it's a race condition because you start the background tasks on the main thread but you end them on the async db queue.

If the `self.db doAsync` is held up because it's busy with something else and the app goes back into the background it'll trigger a crash.

Simulate it via a sleep:

```
- (void) appForegrounding {
    // Danger: This is called on the main thread!
    [self.db doAsync: ^{
         [NSThread sleepForTimeInterval:5.0];
        if ([_bgMonitor endBackgroundTask])
            LogTo(Sync, @"%@: App foregrounded, ending background task", self);
        [self setSuspended: NO];
    }];
}
```

The `[_bgMonitor endBackgroundTask]` should also probably be called on the main thread anyways since it's a UIKit method.

**Comment by robertjpayne** [comment]
Sorry the fix would be to simply end the bg task outside of the db queue:

```
- (void) appForegrounding {
    if ([_bgMonitor endBackgroundTask])
            LogTo(Sync, @"%@: App foregrounded, ending background task", self);
    // Danger: This is called on the main thread!
    [self.db doAsync: ^{
        [self setSuspended: NO];
    }];
}
```

**Comment by snej** [comment]
I've pushed a PR with a slight variant of your fix. (The logic is the same but it avoids calling the replicator's `description` method on a different thread.) If you have a chance to test it out, that would be great!

**Comment by snej** [comment]
Merged to dev branch; closing.
