### ISSUE TITLE
CBLDatabase -close: can hit an internal FMDatabase assertion if a transaction is underway when attempting to close

### ISSUE THREAD

**Issue by mz2** [couchbase/couchbase-lite-ios#1154]
My Couchbase Lite based OSX app is experiencing a low frequency crash caused by an internal assertion failure inside FMDatabase, hit on closing a CBLDatabase whilst the transaction level is nonzero:

`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Attempting to close db during a transaction'`

The assertion failure is very rare in my application and I think really my fault as the Couchbase Lite client that it's occurring in the first place (I have lost track of some longer running database operation in a way that I then attempt to close the database when in fact something else is still manipulating it), but I'd appreciate either: 
a) having CBLDatabase -close: return NO and an error in this scenario rather than hitting the FMDatabase assertion + have CBLManager -close similarly have a BOOL return value and an error pointer. The first of these changes depends on the second because CBLManager -close is currently not returning a success / failure and is not checking for the success of the -close: calls it makes to its CBLDatabases but just pushes on even if any of them were to fail. Making these changes would allow a clumsy CBL client programmer such as myself to write retry logic that may be a bit safer at least (though I appreciate it's really still hiding an underlying problem in my application in that I shouldn't be trying to close the database when I may have also scheduled some asynchronous work on the database manager's queue or something).
b) some instructions for a workaround that would allow for safely closing the database (at the cost of potentially some other database manipulating operations failing once the connection is shut down, which would be fine in this instance), if that is safe.

--------
* Version:   1.0.x (I assume this affects also current versions with the SQLite storage engine)
* Client OS: OSX
* Server:    N/A

**Comment by pasin** [comment]
Do you close the database on a different thread/queue from the one that you are setting to CBLManager?

**Comment by mz2** [comment]
The close is happening on the CBLManager's queue and there is nothing offending on other call stacks in none of the crash reports that match this pattern when this happens that would suggest it's a concurrency issue on that level (which is weird).

**Comment by snej** [comment]
Oh, and if you have crash reports, please post the backtrace of the thread on which the assertion fails.

**Comment by mz2** [comment]
Nope, no chance unfortunately that that's happening inside -inTransaction: that I can think of. If that's really feasibly the only reason barring a CBL bug, I should probably first upgrade my app to the current CBL version (have been holding off doing that for a while) and report back?

**Comment by snej** [comment]
Yes, that'd be best. Thanks! (You may want to grab the 1.2.1 build that I posted about on the mailing list, since it fixes a number of annoying bugs in 1.2.)

**Comment by snej** [comment]
Have you been able to update CBL, and has the crash gone away?

**Comment by mz2** [comment]
Not had the chance to do that yet – I do have this logged also in my own issue tracking though (and a workaround kludge I applied also successfully suppresses the crash) so if you prefer closing this and me reporting it again after I've upgraded CBL in my product, I understand.

**Comment by snej** [comment]
I'll leave this open, in case anyone else runs into it. But please report back after you have a chance to upgrade Couchbase Lite.

**Comment by zgramana** [comment]
Closing. Please re-open/re-file if it happens on 1.2+.
