### ISSUE TITLE
Runtime link crash of CBL 1.2 with OS X 10.8

### ISSUE THREAD

**Issue by greengreengreengit** [couchbase/couchbase-lite-ios#1163]
The 1.2 release of CouchbaseLite has a load time link problem with an undefined symbol when running OS X 10.8, see the crash log below.
All is OK using the previous 1.1.1 release.

I've downloaded the code and analysed the CBL Mac Library using the OS X Deploymate app.
It flags 86 instances of API calls being available since 10.9, mainly new NSURLSession calls.

--------
* Version:   1.2
* Client OS: OS X 10.8
* Build: CBL Mac Library

Dyld Error Message:
Symbol not found: OBJCCLASS_$_JSContext
Referenced from: /Users/USER/Desktop/YoYottaID 2.app/Contents/MacOS/../Frameworks//CouchbaseLite.framework/Versions/A/CouchbaseLite
Expected in: /System/Library/Frameworks/JavaScriptCore.framework/Versions/A/JavaScriptCore
in /Users/USER/Desktop/YoYottaID 2.app/Contents/MacOS/../Frameworks//CouchbaseLite.framework/Versions/A/CouchbaseLite

Binary Images:
0x1059b0000 - 0x106a99fef +com.yoyotta.YoYottaID (2.1 - 319) /Users/USER/Desktop/YoYottaID.app/Contents/MacOS/YoYottaID
0x107366000 - 0x10755eff7 +com.couchbase.CouchbaseLite (1.2.0 - 112.0.0) <78544A62-F8FF-373F-8BA3-BAA656DD9509> /Users/USER/Desktop/YoYottaID 2.app/Contents/Frameworks/CouchbaseLite.framework/Versions/A/CouchbaseLite
0x107647000 - 0x107699fff +com.couchbase.CouchbaseLiteListener (1.2.0 - 112.0.0) <7845A8B8-5318-3676-8800-A74968DFF7E5> /Users/USER/Desktop/YoYottaID 2.app/Contents/Frameworks/CouchbaseLiteListener.framework/Versions/A/CouchbaseLiteListener

**Comment by snej** [comment]
Thanks for recommending DeployMate — I've just purchased a copy and I'm looking at the output. I'll see what I can do about removing 10.9 dependencies for 1.2.x updates.

If you're going to analyze the source, you probably want to check out the release/1.2 tag. You were looking at the latest master branch, which is well into 1.3 development. The switch to NSURLSession is definitely post-1.2. But it will definitely happen for 1.3, so it will require OS X 10.9 minimum.

**Comment by greengreengreengit** [comment]
DeployMate always catches little things for us, Xcode wants you to use the latest SDK which is OK, but then it’s all too easy to start using an API without the appropriate checks.

It is good news that I was looking at 1.3 code !!
If CBL 1.2 can support 10.8 it would be fantastic. Lots of little things like the way CBL 1.2 bundles the database files, also the option for ForestDB make it a good starting point for us.
Also we have just dropped new updates for 10.7 so would not want to drop 10.8 quite yet.

Here is a summary of our licenses which may be of interest.
2% on 10.7, some of whom are on computers like MacPro1,1 or 2,1 which cannot run anything newer without some hacking.
7% on 10.8, we are suggesting they update to 10.10 or 10.11.
25% on 10.9
49% on 10.10
17% on 10.11

In theory all 10.8 Macs can run 10.11, however we find some customers are prevented because their SAN software or other drivers are preventing them from moving past 10.8.

**Comment by snej** [comment]
I looked through the incompatibilities in the release/1.2.1 branch; unfortunately I can't get rid of the 10.9 dependency (due to our use of NSProgress), but I can fix the 10.10 and 10.11 dependencies. I don't know if there's still time to get this into our 1.2.1 release.

**Comment by snej** [comment]
I've fixed these, and updated the deployment OS version to 10.9, in commit 520e6ed6 on the dev branch.
