### ISSUE TITLE
Cannot query view with composite key unless descending=true is specified

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-ios#1167]
Using the http rest api I am unable to query a view that has a composite key unless is specify descending=true.  Without this parameter set no rows are returned.

https://forums.couchbase.com/t/view-with-composite-keys-in-cb-lite/7223/2

--------
* Version:   VERSION
* Client OS: iOS 9.2
* Server:    NAME_AND_VERSION

**Comment by snej** [comment]
On Mar 13, 2016, at 10:09 AM, Nick Pomfret <notifications@github.com<mailto:notifications@github.com>> wrote:


Using the http rest api I am unable to query a view that has a composite key unless is specify descending=true. Without this parameter set no rows are returned.

What’s the query, exactly?

—Jens

**Comment by npomfret** [comment]
Any that use start key and endkey.  Looks like you must specify **descending=true**, else you get no rows back.  Even specifying **descending=false** doesn't work.

**Comment by snej** [comment]
I think there's something wrong with your query. Please show us the exact source code.

**Comment by snej** [comment]
This is correct behavior. The startKey is `["some-key",{}]` and the endKey is `["some-key"]`. Since the startKey is greater than the endKey, you have to specify `descending=true` to get any results. If you had switched the startKey and endKey, you wouldn't need to set descending mode.

**Comment by npomfret** [comment]
Of course, many thanks.
