### ISSUE TITLE
Extras folder is not copied to the Archive

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#1172]
From #1048, @michaelkwok reported that `CBLRegisterJSViewCompiler.h`, `CBLJSONValidator.h`, `CBLJSONValidator.m` are missing from the Extras folder, and that is because Jenkins build script currently copies the extra files from `Source/Extras` folder, and those 3 files are not in the `Source/Extras` folder.

The issue is that XCode doesn't copy the Extra folder to the archive. I have confirmed that the Extras folder exists when running `build`.

**Comment by pasin** [comment]
@michaelkwok, for 1.2.1, we could work around this by either copying all the missing files from `Source` folder or running `build` on `CBL iOS` target to get the `Extras` folder.

**Comment by michaelkwok** [comment]
I will put in the workaround for 1.2.1.  Let's keep the ticket opened until we can come up with the permanent solution.

**Comment by michaelkwok** [comment]
The build script also manually copies libCBLForestDBStorage.a and libCBLJSViewCompiler.a into "Extras".  Can you add these 2 files to the build phase to copy them to Extras as part of the permanent solution?  This will remove all the side steps to stage "Extras" folder for packaging.

**Comment by michaelkwok** [comment]
I kick off build 7 to pick up this workaround.

**Comment by snej** [comment]
This got resolved, didn't it? Can we close the issue?

**Comment by pasin** [comment]
Just talked to @michaelkwok to refresh the issue. Jenkins build script is currently doing a workaround by copy files from source folder as the Extra folder doesn't get archived. I'm reopening the issue.
