### ISSUE TITLE
How to resolve Error : CBLUITableSource.m  > Weak property 'delegate' is access multiple times in this method but may be unpredictably set to nil; assign it to a strong variable to keep it alive

### ISSUE THREAD

**Issue by MukeshDubey** [couchbase/couchbase-lite-ios#1173]
Hello All , 
I am upgrading an IOS project from 8.2 to 9.2 using Xcode 7.2.1

I am getting this error when I compile with SDK 9.2 , compiles fine when used SDK 8.3 

_(UITableViewCell *)tableView:(UITableView *)tableView
cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
// Allow the delegate to create its own cell:  

// ERROR IS BEING THROWN HERE 
#UITableViewCell* cell = TELL_DELEGATE(@selector(couchTableSource:cellForRowAtIndexPath:), indexPath);_

if (!cell) {
// ...if it doesn't, create a cell for it:
cell = [tableView dequeueReusableCellWithIdentifier: @"CBLUITableDelegate"];
if (!cell)
cell = [[UITableViewCell alloc] initWithStyle: UITableViewCellStyleDefault
reuseIdentifier: @"CBLUITableDelegate"];

CBLQueryRow* row = [self rowAtIndex: indexPath.row];
cell.textLabel.text = [self labelForRow: row];
    // Allow the delegate to customize the cell:
    id delegate = _tableView.delegate;
    if ([delegate respondsToSelector: @selector(couchTableSource:willUseCell:forRow:)])
        [(id<CBLUITableDelegate>)delegate couchTableSource: self willUseCell: cell forRow: row];
}
return cell;
}
_
 #**CBLUITableSource.m > Weak property 'delegate' is access multiple times in this method but may be unpredictably set to nil; assign it to a strong variable to keep it alive**

Does anyone know the couchbase compatibility with iOS 9.2 or XCode 7.2.1 ?

Cheers

**Comment by snej** [comment]
This is nothing to do with Couchbase Lite; it's a new compiler warning in Xcode 7.
You shouldn't need to compile CBLUITableSource.m since that class is already in the Couchbase Lite framework. Just remove the source file from your project.

**Comment by snej** [comment]
Also, you've got an old copy of that source file (CBLUITableSource.m.) It was updated last June to avoid that compiler warning.

**Comment by MukeshDubey** [comment]
Yep ,removing project from build fixes the issue . Thanks and appreciate your help.
The App is running fine on iOS 9.2 now
