### ISSUE TITLE
No document prefetch on full-text search

### ISSUE THREAD

**Issue by skreutzberger** [couchbase/couchbase-lite-ios#1174]
When I am running a query with `try query.run()` with a CBLTextKey full text search view then the returned rows do not contain the documents but just the id, the key, the value and further full-text search relevant things.

Here is some code for the query:

```swift      

let query = db.viewNamed("by_text_fts").createQuery()     
query.prefetch = true // get whole document, somehow does not work with FTS?!
query.fullTextQuery = "hello"
query.fullTextRanking = true
query.fullTextSnippets = false
let result = try query.run()
```

If I am now looping over each row I then can still fetch the document with `row.document` but as far as I understood it is doing another database call which I want to avoid.

Instead I had expected that a call like `if let dict = row.properties as [String: AnyObject]! {...}` would give me my document object directly from the row due `prefetch = true`?!

Am I doing something wrong or is that expected behavior?

Besides that: I am currently migrating my app’s data storage from SQLite to Couchbase Lite and I am more than happy with my decision :smile: 

--------
* Version:   Latest Master
* Client OS: 10.11.3

**Comment by snej** [comment]
Looks like the FTS query code is missing a check to handle that query flag.

>as far as I understood it is doing another database call which I want to avoid.

It's actually making the same call to load the document, whether you use the preload flag or load the doc yourself. So there's pretty much zero difference in performance. In fact if you don't need to use all of the documents returned by the query, or if the docs it returns are already in the CBLDocument cache, turning off preload would be faster. (And for best performance, have the map function emit only those properties that you need in the query, or values derived from those properties. Then you don't have to load the doc at all.)

The preload flag comes from CouchDB (where it's called `include_doc`.) It makes a lot of sense in a client/server environment where calls to the db server are relatively slow and can have high latency. It makes a lot less sense in an embedded database, and I've often thought about removing it or turning it into a no-op.

**Comment by brendand** [comment]
I thought that prefetch would execute a bulk fetch of the documents. Like with a big SQL IN statement.

**Comment by skreutzberger** [comment]
Thanks for the explanation! So if my query returns, let’s say, 100 results (containing just document ids and a value) then I need to loop over each row to fetch the adequate document? Wouldn’t that turn 1 database roundtrip into 101?

But maybe that does not really matter on a native app due to the extreme performance of CBL?

Do you maybe have benchmark results or at least a feeling about what it would cost performance-wise to fetch 100 (1000?) documents by ID from a Mac app using CBL as db storage? Do we speak here about user-noticable 200+ milliseconds for fetching 100 documents or is it more in the single digit millisecond ballpark?

**Comment by skreutzberger** [comment]
I run my own performance tests to get a feeling for saving & loading speed. I run it on my 2015 iMac always with a newly created database. Each document consists of 10 field with random content of 5-20 character length plus a timestamp double which is used for indexing / view query.

## Performance Test Results

**1 document:**
2 ms	saving
2 ms	querying by timestamp
0.2 ms	loading of document by ID

**10 documents:**
12 ms	looped saving
5 ms	querying by timestamp
1.5 ms	looped loading (row.document) of all documents by ID

**100 documents:**
132 ms	looped saving
26 ms	querying by timestamp
16 ms	looped loading (row.document) of all documents by ID

**1,000 documents:**
1,575 ms	looped saving
250 ms		querying by timestamp
152 ms		looped loading (row.document) of all documents by ID

**10,000 documents:**
15,680 ms	looped saving
2,296 ms	        querying by timestamp
1,252 ms	        looped loading (row.document) of all documents by ID

**100,000 documents:**
156,6944 ms	looped saving
24,0625 ms	querying by timestamp
12,7992 ms	looped loading (row.document) of all documents by ID

It looks like a very **healthy linear growth**. If you multiple the amount of documents 10x then the db takes around 10x longer. 

For my above mentioned scenario of loading 100 documents by ID in a loop I can say that 16ms is absolutely fine for me since it is not noticable by a user. Generally it seems that a query takes twice as long (!) as the serial / looped fetching of the document IDs (due to caching?) so it is ok to fetch documents by ID I guess.

Do you guys share my thoughts? Any comments?

**Comment by snej** [comment]
One factor is that a CBLDatabase keeps a cache of recently used CBLDocument objects (I think the size is 50.) So if your query brings in recently-used documents, the overhead for prefetching the doc body will be wasted because the document is already in memory and parsed anyway.

If you're getting a huge performance difference like 140::1, (i.e. 0.7%), it must be because of the CBLDocuments already being in the cache.

(@brendand: You're right, the SQLite engine gets the JSON body as an extra column in the SQL query result; it doesn't make a separate query for it.)
