### ISSUE TITLE
Couchbase 1.2 crash with iOS 8.2 and Cloudant DB which contains deleted documents

### ISSUE THREAD

**Issue by jordanpwood** [couchbase/couchbase-lite-ios#1177]
For this issue, I have a new device which is replicating a database for the first time from Cloudant.  After I have started continuous replication, the app crashes.  I have output from the [debugger log](https://gist.github.com/jordanpwood/019c7e6c54fe882b652f) and a [backtrace](https://gist.github.com/jordanpwood/915146dada87de68a99c).  In the debugger log, you can see that `CBLMultipartDownloader` gets a 401 error from cloudant on a document `article-47098023`.  This document has been deleted from the database.  This OS version works with databases which don't have deleted docs.

**Steps to Reproduce**
1. start the app with no local database
2. start continuous replication with a Cloudant database containing deleted documents.

**Actual**
App crashes when trying to replicate a deleted document from Cloudant

**Expected**
Finishes the replication, and doesn't crash when there are deleted docs

This problem has been seen with iOS 8.2 only, 8.3 and above work perfectly.  If you need access to a Cloudant database where this problem has been seen, I can arrange that.

--------
* Version:   Couchbase 1.2
* Client OS:  iOS 8.2
* Server:   Cloudant

**Comment by snej** [comment]
This looks a lot like one of the crashes we fixed for 1.2.1. I don't remember which one exactly, but you can look at the issues in the 1.2.1 milestone; there aren't many. I don't know why you'd only be getting it with iOS 8.2; it's sort of intermittent though, so for some reason the timing may be different enough in that OS to hit this situation more often.

Anyway, if you can, please try the latest 1.2.1 and see if the crash goes away.

**Comment by jordanpwood** [comment]
I'll try that!  

Will 1.2.1 be release sometime soon?

**Comment by snej** [comment]
Hopefully within a week; we have one or two more issues to take care of. You can download the latest build [here](http://latestbuilds.hq.couchbase.com/couchbase-lite-ios/release/1.2.1/).

**Comment by jordanpwood** [comment]
That fixed our problem.

**Comment by snej** [comment]
Yay!
