### ISSUE TITLE
Assertion failure in CBL_MutableRevision, pushing document

### ISSUE THREAD

**Issue by hermanccw** [couchbase/couchbase-lite-ios#1179]
Hi all, 

Reposting from forum.

This is probably a long shot, but wanted to see if anyone here experienced the same issue.  Whenever we push out a new update on our app in the app store, some user is reporting a crash on boot and there is no way from them to come back to the app unless they do a full reinstall.

I managed to ask one of them to send us their crash log file in their own device, and [here](https://gist.github.com/hermanccw/d119fc1067a1b4b77cf5) it is.

Which doesn't mean anything since it is not symbolized, however, I am getting the similar crash log from Crashlytics that looks like [this](https://gist.github.com/hermanccw/ca17a10b43e3449f013b)

Which seems to suggest it is failing on the CouchbaseLite thread and it's something regarding an assertFail on "!_changeTracker"

Looking at the log message before the crash in Crashlytics, it seems to indicate that the app is going in and out of network connection before the crash.  Could that be related?

Also want to note that we are using CBL with multiple dispatch queues, I've done a clean up in my code to make sure no cross-thread access to CBL* objects, but not sure if this is the cause of such crash.

It's especially bad since users who's getting these crashes seems to be stuck on a crash on boot cycle and never get into the app.

--------
* Version:   1.1.0 at commit 8880a96
* Client OS: iOS 8/9
* Server:   CouchDB 1.3.1

**Comment by snej** [comment]
Could you post the part of the crash log that says that the exception is an assertion failure for `!_changeTracker`? I can't see that in either link you posted.

If that's the failure, the only assertion with that test (in the 1.2 sourcebase) is at the start of `-[CBLRestPuller startChangeTracker]`. I don't remember any previous bugs involving that failing, though.

**Comment by hermanccw** [comment]
@snej I don't think the crash log have that.   Here is the link to the crash: [http://crashes.to/s/6d89a61312a](http://crashes.to/s/6d89a61312a)

By looking at the log that I have, it also seems to follow the same pattern

1.  User either do open up the app
2.  Initially the network was not reachable (i know this since there are other API call I made to my other server and it came back with error saying the network is not available)
3.  The network came back or change status a couple of time (could be coming in and out of connectivity)
4.  This crash happens

**Comment by snej** [comment]
Your app binary or its dSYM file don't have enough symbols to determine the actual backtrace. Where "MYGetCertificateDigest" shows up, that isn't really the function involved, it's just the nearest known symbol to the PC address. So there's some incorrect build setting in your app target that's causing symbols to be stripped out. Unfortunately I am not too knowledgeable about all the symbol stripping settings in Xcode so I can't tell you exactly what to fix. Are your crash reports otherwise able to identify symbols in your app? I.e. is it just the Couchbase Lite symbols that get lost?

**Comment by hermanccw** [comment]
@snej ah... interesting.... Yes, we do get symbolized crashes from crashlytics for other crash that's not related to CBL.  We actually build our own version of CBL so according to this [this](https://docs.fabric.io/ios/crashlytics/advanced-setup.html#static-or-dynamic-frameworks), I've made the changes, build and link again.  Hopefully this will give me better symbolized crashes.

**Comment by hermanccw** [comment]
@snej I finally were able to get the real stack trace, link [here](https://gist.github.com/hermanccw/95ee65be45cb77c07100653227acecc7)

Seems like users are getting this when they open the app and somehow trying to create CBL_Body with a nil properties dictionary

Any help will be greatly appreciated.

**Comment by snej** [comment]
Here's the interesting bit of the backtrace:
```
0x1009bf400 -[CBL_MutableRevision setProperties:] (CBL_Revision.m:294)
0x1009bf518 -[CBL_MutableRevision setObject:forKeyedSubscript:] (CBL_Revision.m:305)
0x1009cbd14 __27-[CBL_Pusher processInbox:]_block_invoke (CBL_Pusher.m:287)
0x1009c4cec __58-[CBL_Replicator sendAsyncRequest:path:body:onCompletion:]_block_invoke (CBL_Replicator.m:802)
```
Here's [CBL_Pusher.m:287](https://github.com/couchbase/couchbase-lite-ios/blob/8880a96a3eaffaf7ef3b4ab626fed4eedb2415f5/Source/CBL_Pusher.m#L287-L288) from the version you're using. So clearly `-getRevisionHistoryDict:startingFromAnyOf:` returned nil...

**Comment by snej** [comment]
Hm, working backwards I also ended up at `-[CBL_SQLiteStorage loadRevisionBody]`. But in response to your question, it shouldn't be a problem if the revision body's been compacted away — the method will return a 404 status, so then the pusher will [give up on that revision](https://github.com/couchbase/couchbase-lite-ios/blob/8880a96a3eaffaf7ef3b4ab626fed4eedb2415f5/Source/CBL_Pusher.m#L277-L280).

**Comment by snej** [comment]
Any chance you could get console logs from one of the instances of the app that crashes? I'm guessing there'd be a warning like `CBL_Body: couldn't parse JSON:...` right before.

**Comment by snej** [comment]
By the way, I just noticed that the crash we're talking about today is definitely _not_ the same as the one you initially reported in this issue, since it has nothing to do with the changeTracker. (And actually none of the crash logs you've posted in this issue contain the assertion failure message that's in the issue title, so I'm not sure where it came from...)

**Comment by hermanccw** [comment]
@snej I believe it is the same crash, it was just not symbolized correctly so it gives out crappy error message.  If you compare the pattern from the crash before and this real crash, they have very similar pattern.

> Any chance you could get console logs from one of the instances of the app that crashes? I'm guessing there'd be a warning like CBL_Body: couldn't parse JSON:... right before.

I guess I could do that with another push to production, but if there is any chance I don't have to do that, I'd rather not since this bug seems to surface itself whenever I push a update to the app store and render our app useless since it crash on boot continuously until our user reinstall the app.

**Comment by snej** [comment]
`'Fatal Exception: NSInternalInconsistencyException', reason: '!_changeTracker'` is a message from an NSException; it doesn't have anything to do with symbolication. And the assertion failure that would trigger it is entirely different (it's in CBL_Puller, not CBL_Pusher, for instance.)

**Comment by snej** [comment]
I'm working on a commit (on the current dev branch) that should prevent the things that seem to have gone wrong here. I'm not sure if you can directly cherry-pick it into 1.1, but if not it should be easy to hand-merge, as the code around it hasn't changed that much.

**Comment by hermanccw** [comment]
@snej thanks!  Are these two commit the ones that I should try to cherry-pick?  Or is there more you are working on?

**Comment by snej** [comment]
Yes, those two should fix the problem.

**Comment by hermanccw** [comment]
@snej ok, thanks.  For production build, is there anyway for me to turn on all the warning for this bug?  want to try to capture as much as possible in case it crashes again.

**Comment by snej** [comment]
Warnings are always logged, no matter what.

**Comment by snej** [comment]
Merged to dev branch; closing.

**Comment by hermanccw** [comment]
just wanted to confirm that this works in our production environment. thx!
