### ISSUE TITLE
API: Document expiration time (TTL)

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1181]
https://github.com/couchbaselabs/couchbase-lite-api/issues/141: API "to set a limit on how long a given document should exist before it is automatically purged, so that time-sensitive documents that are no longer desired won't continue to take up disk space."

**Comment by zgramana** [comment]
Reference implementation will be tracked on issue couchbase/couchbase-lite-net#617.

**Comment by snej** [comment]
Pushed to dev branch; closing.
