### ISSUE TITLE
Manual compaction returns error if auto-compact is already running

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/couchbase-lite-ios#1192]
Found on build 1.2.1-10
Sync Gateway: 1.2.1.4
Using Mac OS-X (el-capitan) liteserv client

Steps: 
- Setup and install sync-gateway-tests. https://github.com/couchbaselabs/sync-gateway-tests
- git checkout ios_forestdb_support
- add following environment variables in your shell: 
```
export STORAGE=ForestDB
export SYNCGATE_PATH=/your/path/to/bin/sync_gateway
export LITESERV_PATH=/your/path/to/couchbase-lite-macosx-enterprise_1.2.1-10/LiteServ
```
- Run script from sync-gateway-tests as follows:

```
node tests/cbl-database.js
```
Test script line: https://github.com/couchbaselabs/sync-gateway-tests/blob/master/tests/cbl-database.js#L217

Get the following warnings:
https://gist.github.com/ashvindersingh/f884882f8fb7595da79304aae5409541#file-forestdb_cbl_database-js-logs-L42

https://gist.github.com/ashvindersingh/f884882f8fb7595da79304aae5409541#file-forestdb_cbl_database-js-logs-L72

**Comment by snej** [comment]
Manual compaction isn't necessary with ForestDB, but of course it should still work. The error is `WARNING: ForestDB error: file handle is busy (-23)` — it may be that `fdb_compact` doesn't work if there are multiple handles open on the database. I'll ask.

**Comment by snej** [comment]
Aha, here's a note from the doc-comment for `fdb_compact`:
```
 * Also note that if a given ForestDB file is currently being compacted by the
 * compaction daemon, then FDB_RESULT_FILE_IS_BUSY is returned to the caller.
```
So it sounds like ForestDB's auto-compact was already in progress when the manual compact was requested.

To fix this, we can either (a) ignore that error code, or (b) handle it by waiting for the background compaction to complete before returning.

**Comment by snej** [comment]
(To be specific, this should be fixed in CBForest itself.)

**Comment by snej** [comment]
Merged to dev branch; closing.
