### ISSUE TITLE
Recommendation for mocked unit testing

### ISSUE THREAD

**Issue by joeljeske** [couchbase/couchbase-lite-ios#1194]
Do you guys recommended unit test mocks? I would prefer to use an in-memory CBLDatabase when testing but have not found anything like this. 

Any good practices would be appreciated.

**Comment by snej** [comment]
Hi! Please ask your question on the [Couchbase web forum](https://forums.couchbase.com/c/mobile) or the [Couchbase Mobile mailing list](https://groups.google.com/forum/#!forum/mobile-couchbase). We use Github issues only for bug reports and feature suggestions. Thanks.
