### ISSUE TITLE
Assertion failure: !_changeTracker [CBL 1.1]

### ISSUE THREAD

**Issue by hermanccw** [couchbase/couchbase-lite-ios#1196]
Hi there,

Got this other crash in production, crash log [here](https://gist.github.com/hermanccw/ceca9d480897ee36045d7cf6c528d893)

From what I can see from the other logs that I have in crashlytics, this always happen from a warm boot (user minimized the app but the app is still in background memory) and when the network jumping on and off

--------
* Version:   1.1
* Client OS: iOS 9
* Server:    couchdb 1.3.1

**Comment by snej** [comment]
Relevant part of the stack is:
```
0x100a590b0 _AssertFailed (Test_Assertions.m:26)
0x100a16ef4 -[CBL_Puller startChangeTracker] (CBL_Puller.m:94)
0x100a169d8 -[CBL_Puller beginReplicating] (CBL_Puller.m:89)
0x100a15ac4 __42-[CBL_Replicator fetchRemoteCheckpointDoc]_block_invoke (CBL_Replicator.m:995)
0x100a14cec __58-[CBL_Replicator sendAsyncRequest:path:body:onCompletion:]_block_invoke (CBL_Replicator.m:802)
0x100a24778 -[CBLRemoteRequest respondWithResult:error:] (CBLRemoteRequest.m:179)
0x100a25af0 -[CBLRemoteJSONRequest connectionDidFinishLoading:] (CBLRemoteRequest.m:456)
```

**Comment by hermanccw** [comment]
@snej any insight into this?

**Comment by snej** [comment]
Not yet; to be honest, I may have trouble getting to this quickly because the code has changed a lot since 1.1, so it would mean reverting back to old commits.

**Comment by zgramana** [comment]
@hermanccw, are you able to test against 1.2.0?

**Comment by pasin** [comment]
I'm closing the issue now. @hermanccw if you have any additional info when test the app with 1.2 or 1.3 library, please let us know so we can reopen the issue.
