### ISSUE TITLE
Fatal Exception: NSInternalInconsistencyException: Too many calls to releaseReadLock

### ISSUE THREAD

**Issue by hermanccw** [couchbase/couchbase-lite-ios#1197]
Hi there,

[here](https://gist.github.com/hermanccw/8fb2c540b25555ec2c314f087b70bd9a) is another crash we get from production.

--------
* Version:   1.1
* Client OS: iOS 8/9
* Server:    couchdb 1.3.1

**Comment by snej** [comment]
This was fixed in 1.1.1 (see #977).
