### ISSUE TITLE
Memory spikes during replication

### ISSUE THREAD

**Issue by ZancaM** [couchbase/couchbase-lite-ios#1199]
We are trying to prove a concept in which we want to store a lot of information on the device. These are extreme cases in which the user might not have connection for an entire week and he needs full offline capability.

We have seen huge improvements from version 1.1 in memory leaks. However sometimes we get a spike in memory above 700 MB. It really jumps from a stable 150 to 250 MB to a 700-800 MB

Is there something on my side I can do to fix the issue during replication ?

Thank you
--------
* Version:   1.2
* Client OS: iOS 9
* Server:    CouchBase 4.0

**Comment by snej** [comment]
I don't know — we'll first need to isolate when and why this happens. Then we can fix it, and advise you of any workarounds.

Can you identify any triggers for this behavior? For example:
* Pushing or pulling?
* Document JSON size?
* Attachment size?
* Quantity of documents?
* Network errors?

The best would be if you could create a reproducible scenario that we could run. For example, set up a client and a server database that, when synced, will trigger it. Or a small program that will generate a database that will trigger it.

Alternatively you could use Instruments' memory profiling tools to capture a run where this occurs, and send us the Instruments file.

**Comment by pasin** [comment]
I'm closing the issue now. @ZancaM if you can provide any additional info about the issue, please let us know and we can reopen the issue. Thanks.
