### ISSUE TITLE
CBLDynamicObject.h missing from master build

### ISSUE THREAD

**Issue by brendand** [couchbase/couchbase-lite-ios#1203]
I just updated to the master build cd276763bbfac5478ad8584e1cbc55b7005fdd52 and I get an error "CBLDynamicObject.h" file not found.

This happens after I build and incorporate the CouchbaseLite.framework into my project.

--------
* Version:   1.3 master cd276763bbfac5478ad8584e1cbc55b7005fdd52
* Client OS: iOS 9.3.1
* Server:    n/a

**Comment by brendand** [comment]
A bit more info:

When I build I'm archiving the "Continuous iOS" scheme. 

The CBL iOS target appears to be missing the file as the CBL iOS Framework target does have it.

Here's the final archived build's Public header files after I export from Xcode:

CBLAttachment.h
CBLAuthenticator.h
CBLBase.h
CBLDatabase.h
CBLDatabaseChange.h
CBLDocument.h
CBLGeometry.h
CBLJSON.h
CBLManager.h
CBLModel.h
CBLModelFactory.h
CBLQuery.h
CBLQuery+FullTextSearch.h
CBLQuery+Geo.h
CBLQueryBuilder.h
CBLReplication.h
CBLRevision.h
CBLUITableSource.h
CBLView.h
CouchbaseLite.h

and in Private:

CBLRemoteLogging.h
CBLReplication+Transformation.h
CBLStatus.h
CBLTimeSeries.h
CouchbaseLitePrivate.h

**Comment by snej** [comment]
Oops, you're right. It needs to be added to the CBL iOS target as well. Want to fix it and send a PR? Otherwise I can fix it later today...

**Comment by brendand** [comment]
Sure, I can do that.

**Comment by brendand** [comment]
Submitted PR: 17984cb3b3b5812e69589d98bf71ff9e8ac5948c
