### ISSUE TITLE
CBLIncrementalStore Batching Support

### ISSUE THREAD

**Issue by shadzik** [couchbase/couchbase-lite-ios#1209]
Dear CBL Team,

together with a colleague of mine @pawelropa, we've tried to understand `CBLIncrementalStore` and it's capabilities of batching fetch requests in order to lower memory footprint in our target app.

In order to do so, we've created two sample projects that were supposed to show us the difference between batching in the `NSSQLiteStore` and `CBLIncrementalStore`.

The basic concept in both cases, was to seed the database with 10000 contacts on first run and on next runs load the data using an `NSFetchResultsController` with batching.

The two projects were kindly made available by @pawelropa in his repository:

Core Data using `NSSQLiteStore`:
https://github.com/pawelropa/BatchingTest_NSSQLLiteIncrementalStore

Core Data using `CBLIncrementalStore`:
https://github.com/pawelropa/BatchingTest_CBLIncrementalStore

By using XCode Profiling Tools, we've been able to see multiple fetch request in case of `NSSQLiteStore` (low memory footprint), as opposed to just one (all the data) in case of `CBLIncrementalStore` (much higher memory footprint).

The result indicates that the `CBLIncrementalStore` does not support batching using `NSFetchResultsController` and the `fetchBatchSize` property of `NSFetchRequest`. Will that be supported in the future and is this possible to achieve now?

Analysing `CBLInrementalStore` we've spotted the usage of `CBLQuery` `limit` and `skip` functionality, which would indicate some kind of batching support, but we haven't been able to trigger it properly.

We would greatly appreciate your feedback.

---
- Version:   1.2.0
- Client OS: iOS 9.3
- Server:  no server, locally

**Comment by pasin** [comment]
@shadzik thanks a lot for sharing the test projects. CBLIncrementalStore supports `fetchOffset` and `fetchLimit` but not `fetchBatchSize` now. I have never used `fetchBatchSize` before so I would need to look into this.

**Comment by shadzik** [comment]
@pasin thanks for your quick response! The rationale behind batching would be for us to be able to fault data that we don't need, and get data that we will need in smaller batches. I think this is not yet possible with the `CBLIncrementalStore`.

**Comment by pawelropa** [comment]
@pasin With `fetchOffset` and `fetchLimit` we would need to implement functionality which `NSFetchResultsController` and `NSFetchRequest` provide, ourselves. But I am not sure if in the long run it would be a viable solution as many apps relay on `NSFetchResultsController` a lot. Anyway, now we will consider using `fetchOffset` and `fetchLimit` for now.

**Comment by pasin** [comment]
@pawelropa I have just forked your test repos so that I can use them to do some experiments independently. Not sure how we could get `fetchBatchSize` supported at the moment as NSIncrementalStore (CBLIS specifically) doesn't manage the faulting of the returned fetched results.

**Comment by jayahariv** [comment]
Closing 1.x issue!
