### ISSUE TITLE
Documents with incorrect zero length attachments stalls continuous sync on CBL 1.1.1

### ISSUE THREAD

**Issue by lightandshadow68** [couchbase/couchbase-lite-ios#1218]
I've run into a production blocker when performing bulk replication during initial sync via a continuous pull replication. Sync stalls due to a 502 error after encountering a document which is incorrectly reported as having a zero length attachment. The continuous replication correctly resumes, but the sequence repeats itself when CBL encounters the zero length attachment document again, etc. This prevents sync from completing and the app fails to complete initial start. 

From what we can gather, the Android version of Couchbase Lite occasionally sets the length property of individual JSON attachment fragments incorrectly to zero when saving revisions. This causes CBL on iOS to report the incorrect length, throw a 502 and restart continuous replication. If the Android revision wins, the zero length attachment entires are in base of the document. However, 502s are reported even if the revision looses. In this case, the zero length revision entires are in the body map of the underlying Couchbase server document. See issue #849 filed on the Android version of CBL. 

Note: Recreating the attachments on the document resolves this issue and the log messages do not occur. It's not clear if this is specific to bulk replication (see log entires below) 

**Steps to Reproduce**

- Start with a document that has an attachment fragment with an incorrect length of zero in either the current revision or a previous revision. 
- Configure and start continuous replication on iOS. 
- During initial sync, monitor the replication status notifications.

**Expected Results**

Continuous replication reports the incorrect attachment length, but does not stall. (it knows the correct length)

**Actual Results**

Continuous replication enters a loop in which it stalls, restarts, stalls, etc. when encountering an attachment JSON fragment with an incorrect length of zero. 

```
Apr 20 11:55:28 Pixel-iPhone App Name[xxxxx] <Warning>: WARNING: CBLMultipartDocumentReader[_id="8effbdee-bf15-49f6-b924-d8ba44c82ddf"]: Attachment 'objective' has incorrect length field 0 (should be 9767)
Apr 20 11:55:28 Pixel-iPhone App Name[xxxxx] <Warning>: SyncSession: active=0; mode=2; 0/0; 502 Invalid response from remote replication server
```
--------
* Version: CBL 1.1.1
* Client OS: iOS 9.3.1
* Server:  Sync Gateway/1.2.0(79;9df63a5) Couchbase server 4.0.0-4051-community (3 node cluster)

**Comment by snej** [comment]
>Android version of Couchbase Lite occasionally sets the length property of individual JSON attachment fragments incorrectly to zero when saving revisions.

Has this been filed as an issue in couchbase-lite-java-core?

>Continuous replication reports the incorrect attachment length, but does not stall. (it knows the correct length)

Yeah, the replicator is too cautious in some ways when pulling attachments, and will give up when it sees inconsistencies. It should be more forgiving.

**Comment by lightandshadow68** [comment]
> Has this been filed as an issue in couchbase-lite-java-core?

I believe the Android developer on this project only filed an issue on the Android repo.

**Comment by tikimcfee** [comment]
Hey, chiming in here. This was posted today in the couchbase forums, and seems to be a related, if not the same, issue:
https://forums.couchbase.com/t/bulk-download-causes-trouble/7917
https://forums.couchbase.com/t/couchbase-lite-attachments-syncing/7918

**Comment by snej** [comment]
Thanks! I've left comments in the forums pointing here. Seems likely that the C# implementation is following the same logic from the original Obj-C code.

**Comment by pasin** [comment]
As the issue has been fixed on the CBL Android, I understand that this issue can be closed. Let me know if there is still an issue on the CBL iOS side that should be fix, then we can reopen the issue.
