### ISSUE TITLE
Carthage: No shared framework in 1.2

### ISSUE THREAD

**Issue by catalandres** [couchbase/couchbase-lite-ios#1219]
While building the module targeting 1.2 (`github "couchbase/couchbase-lite-ios" "1.2"`), Carthage spits out the following:

`*** Skipped building couchbase-lite-ios due to the error:
Dependency "couchbase-lite-ios" has no shared framework schemes for any of the platforms: iOS`

--------
* Version:   1.2
* Client OS: iOS 9.3
* Server:    NAME_AND_VERSION

**Comment by snej** [comment]
This was supposed to be fixed with #1097, but apparently it wasn't. I'll reopen it.
