### ISSUE TITLE
Investigate cbl-large-revisions-compact.js test hang

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-ios#1223]
As of 1.2.1-13, the test below hangs indefinitely. I verified the behavior against 1.2.0-101. I noticed the test failed in both occasions, however, 1.2.0 completes execution whereas 1.2.1 hangs.
--------
* Version:   1.2.1-13
* Client OS: LiteServ 1.2.1-13
* sync_gateway:    1.2.0-79

The test -https://github.com/couchbaselabs/sync-gateway-tests/blob/master/tests/cbl-large-revisions-compact.js#L270
Output running the test with both versions.

[cbl-large-revisions-compact.zip](https://github.com/couchbase/couchbase-lite-ios/files/235746/cbl-large-revisions-compact.zip)

**Comment by snej** [comment]
Please get a backtrace. You can run `sample PROCESSNAME 2` from another shell.

**Comment by sethrosetter** [comment]
this was due to the local -> local db replication fixed via https://github.com/couchbase/couchbase-lite-ios/pull/1297
