### ISSUE TITLE
Master branch build error

### ISSUE THREAD

**Issue by brendand** [couchbase/couchbase-lite-ios#1225]
When I compile the master branch, I get the following error:

```
Documentation/build_docs.sh:29 Error: doxygen is not installed
Command Documentation/build_docs.sh failed with exit code 1
```

Is it required now to have doxygen installed? I obviously don't have it.

--------
* Version:   1.3 beta e116adf2cfbe3b7f2eeb1fc74f57b45703c15bf9
* Client OS: OS X 10.11.4
* Server:    n/a

**Comment by brendand** [comment]
For now I've just been turning off the Documentation target on the Edit Scheme sheet.

**Comment by snej** [comment]
Which scheme are you building?

**Comment by brendand** [comment]
CI MacOS. Sorry, I should have mentioned that.

**Comment by snej** [comment]
That's the scheme used by our Continuous Integration server, which is why it builds the docs too. So this is intentional.

I usually just build the `CBL Mac` scheme.

**Comment by brendand** [comment]
I picked that one because it also builds the CBL Listener Mac. There's no separate scheme for CBL Listener Mac anymore.

**Comment by snej** [comment]
`CBL Mac` builds the listener too.

And you can just create your own schemes too; you don't have to use shared ones.
