### ISSUE TITLE
Change order of parameters in `View.setMapBlock`

### ISSUE THREAD

**Issue by catalandres** [couchbase/couchbase-lite-ios#1226]
From the API guide's [page on views](http://developer.couchbase.com/documentation/mobile/1.2/develop/guides/couchbase-lite/native-api/view/index.html), here is how you use `View.setMapBlock` in Swift.

```
// Create a view and register its map function:
let phoneView = db.viewNamed("phones")
phoneView.setMapBlock({ (doc, emit) in
    if let phones = doc["phones"] as? [String] {
        for phone in phones {
            emit(phone, doc["name"])
        }
    }
}, version: "2")
```

I would request that the order of the two parameters in `setMapBlock` be switched. The purpose would be to make the code more idiomatic and more readable in Swift: thanks to some syntactic sugar added to the Swift specification, if the last parameter is a closure, one would be able to take the function out of the parentheses. Here is how it would look like after the change:

```
// Create a view and register its map function:
let phoneView = db.viewNamed("phones")
phoneView.setMapBlock(version: "2") { (doc, emit) in
    if let phones = doc["phones"] as? [String] {
        for phone in phones {
            emit(phone, doc["name"])
        }
    }
}
```

---
- Version:   1.2
- Client OS: iOS / Swift
- Server:    N/A

**Comment by snej** [comment]
Unfortunately we won't make incompatible changes to the public API until version 2.0. (We're following Semantic Versioning, or trying to.)

I've run into this too when writing Swift code, and my workaround was to add a tiny `extension` of `CBLView` that defines a wrapper for that method with the parameters reordered.

**Comment by catalandres** [comment]
And one probably needs to name the method differently, because methods in ObjC classes cannot be overloaded (same name, different parameters, etc), right?

**Comment by snej** [comment]
No, the selector would be different because the components are in a different order, i.e. it would be `-setVersion:mapBlock:` instead of `setMapBlock:version:`. So I was actually wrong about this being a breaking change.

It would still be weird to add this superfluous method to the API just to make Swift calls a little cleaner. Until we re-do the API in 2.0, I think the one-line extension is a reasonable workaround :)

**Comment by jayahariv** [comment]
Closing 1.x issue!
