### ISSUE TITLE
Carthage-compiled framework does not include libCBLForestDBStorage.a

### ISSUE THREAD

**Issue by catalandres** [couchbase/couchbase-lite-ios#1227]
I have compiled CouchbaseLite (1.2.2) using Carthage. After setting the `Manager`'s `storageType` property equal to `"ForestDB"`, I get the following warning:
```
WARNING: storageType is 'ForestDB' but no CBL_ForestDBStorage class found; make sure `-ObjC` is in Other Linker Flags in Build Settings
```
I have made sure that the `-ObjC` flag is set under **Build Settings > Other Linker Flags**.

According to the instructions on [how to enable ForestDB in iOS](http://blog.couchbase.com/2016/february/mobile-1.2-enable-forestdb), it entails linking a library called `libCBLForestDBStorage.a`. This library is not part of the output of the compilation of CBL using Carthage.

If this is a dependency that is somehow missing, it should be specified in a `Cartfile`.

--------
* Version:   1.2.2
* Client OS: iOS / Swift
* Server:    N/A

**Comment by snej** [comment]
Carthage doesn't support static libraries. And Carthage has zero configurability, so there's no way for us to tell it that it should build a separate target and link the library it creates.

We don't include the ForestDB storage engine in the base framework because it adds significantly to the code size.

**Comment by snej** [comment]
We're going to close this issue, because we don't have a way to make this work, given Carthage's inflexibility. Workaround is to open the CBL Xcode project and build the ForestDB-storage static library yourself, then add the .a file to your target.
