### ISSUE TITLE
One-shot push from empty db never stops

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1228]
Seth's tests hit an interesting edge case: if you start a non-continuous push replication, and the local database is empty, the replicator does nothing (of course) but never goes into the stopped state.

Embarrassingly, we don't have a unit test for this.

--------
* Version:   1.2
* Client OS: Mac
* Server:    n/a

**Comment by snej** [comment]
The createTarget option has to be off too.

**Comment by dyowee** [comment]
Tested that this also occurs in iOS 1.2.x version

**Comment by snej** [comment]
Yes, I suspect this bug was triggered by some replicator optimizations I added post-1.1.1. (Specifically, by not fetching a remote checkpoint on the first replication of a new database.)
