### ISSUE TITLE
Incremental view indexing

### ISSUE THREAD

**Issue by tgmichel** [couchbase/couchbase-lite-ios#123]
I use _active_tasks to monitor replication progress. Would be useful to be able to do the same or something similar with view indexing.

**Comment by carrotalan** [comment]
+1 We are using couchbase with a rather large database on mobile and currently don't have an effective way to reporting feedback to the user that the database is indexing.

Has this been put into any roadmap?

**Comment by snej** [comment]
This isn't going to happen in 1.x. CBL 2 updates indexes eagerly as documents are updated, which is basically incremental.
