### ISSUE TITLE
Listener POST _replicate using full host name for source failed

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-ios#1230]
Listener POST _replicate using full host name for source failed
--------
* Version:   1.2.1
* Client OS: Mac
* Server:    NA

I am replicating from a listener  (localhost:59840) - `Couchbase Lite 1.2.1 (build 13); git commit 9e635d3a82ff6d398512d0c653a45bab051c9129` to a sync_gateway  (localhost:4985)
 `Couchbase Sync Gateway/1.2.0(79;9df63a5)`.

I issue the following command 
```
curl -X "POST" "http://localhost:59840/_replicate" \
	-H "Content-Type: application/json" \
	-d "{\"source\":\"ls_db1\",\"target\":\"http://localhost:4985/sg_db\",\"continuous\":true}"
```   
    
It succeeds and the response is
```
{"session_id":"repl001"}
```
    
However, when I issue the following command using the full url for the listener db as a source

```
curl -X "POST" "http://localhost:59840/_replicate" \
	-H "Content-Type: application/json" \
	-d "{\"source\":\"http://localhost:59840/ls_db1\",\"target\":\"http://localhost:4985/sg_db\",\"continuous\":true}"
```

If fails with the following reponse
```
{"status":400,"error":"Invalid database\/document\/revision ID"}
```

**Comment by snej** [comment]
You can't give the local database as a URL; it has to be just the database name.
(Sorry I misled you earlier; I misunderstood what you were asking.)
