### ISSUE TITLE
Object cannot be nil error calling [document getRevisionHistory:nil]

### ISSUE THREAD

**Issue by brendand** [couchbase/couchbase-lite-ios#1234]
When getting the revision history from a document, I'm getting the following error:

```
*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil
```

The code stops on the insertObject line below:

```
- (NSArray*) getRevisionHistoryBackToRevisionIDs: (NSArray*)ancestorIDs
                                           error: (NSError**)outError
{
    NSMutableArray* history = $marray();
    for (CBL_RevID* revID in [self.database getRevisionHistory: _rev backToRevIDs: ancestorIDs]) {
        CBLSavedRevision* revision;
        if ($equal(revID, _rev.revID))
            revision = self;
        else
            revision = [self.document revisionWithRevID: revID withBody: NO];
        [history insertObject: revision atIndex: 0];  // reverse into forwards order
    }
    return history;
}
```

revision ends up being nil, so it crashes when attempting to insert into the history array.

When I print out the contents of revID, I get what seems like a proper revision ID: `2-3f3dfe5275ebfc4b6d0730d74e865be3` however it has class `CBL_TreeRevID`. So perhaps the documents' `revisionWithRevID` method doesn't quite work with this class, so it's unable to find the revision in the document, hence the crash.

--------
* Version:   1.3 beta commit 51b723efd3c2cd966006762e46dac2d90652e6ec
* Client OS: OS X 10.11.4
* Server:    n/a

**Comment by snej** [comment]
I just ran into this over the weekend, in the middle of testing something unrelated. But I was on a branch. I'll have to look at the changes on that branch and extract the one that fixes this and bring it over to dev...

**Comment by brendand** [comment]
In the meantime I've switched back to master. It seems syncing doesn't work between a dev build and a master build. For a time I had my OS X version on dev and iOS version on master. They were incompatible for syncing. At least for Nearby syncing.

**Comment by snej** [comment]
BTW, congrats on filing issue #1234!

I found the fix on that branch — it's a one-liner. Testing it now, about to commit.

There shouldn't be any problems replicating. If you could file an issue with whatever details you can gather, like logs/warnings/errors, that would be great.

**Comment by brendand** [comment]
Hehe... stroke of luck on the 1234 :-) 

Thanks for fixing it so quickly!

I'll let you know if I find any issues with peer-to-peer replication between versions.

**Comment by snej** [comment]
The fix for that particular crash was one line, but as I looked into it, there were more things that needed to be fixed, having to do with the way the innards of CBL handle revisions whose bodies are missing (due to compaction or replication.) So the commit ended up larger than I thought. Let me know if there are any problems…
