### ISSUE TITLE
Listener POST _changes does not pass changes mode parameter

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-ios#1235]
When using POST, the feed type is not passed as expected (i.e. Issuing a feed: "longpoll" in the request body does not actually use "longpoll", from what we could tell) I found this while debugging with @pasin. 

Also, should I file an issue to include POST documentation on the website?

---
- Version:   1.2.1
- Client OS: Mac OSX
- Server:    NA

**Comment by borrrden** [comment]
This is a pretty big performance problem and possibly causing other problems with some functional testing because the client will be hammering away at this endpoint expecting it to only return when it has results in P2P scenarios.

**Comment by snej** [comment]
When -[CBLRouter do_POST_changes:] copies the request body properties into URL params, it JSON-encodes them. This means that the `feed` parameter gets double-quotes around it, e.g. `"longpoll"` not `longpoll`, so it isn't recognized.

**Comment by borrrden** [comment]
The problem still exists in `GET`

**Comment by borrrden** [comment]
Sorry, erroneous!

**Comment by swaheed2** [comment]
Is this fix supposed to be included in Couchbase Lite 1.4.1 thats published here: 

https://github.com/couchbaselabs/Couchbase-Lite-PhoneGap-Plugin

First _changes request seems to behave as longpoll then the rest are definitely not.

**Comment by swaheed2** [comment]
Actually it happened a few times when I was testing it, It seems to be working fine.
