### ISSUE TITLE
Listener not respecting timeout on longpoll changes

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-ios#1236]
---
- Version:   1.2.1
- Client OS: Mac OSX
- Server:    NA

I issue the following query and there are no new changes so the request remains open listening for new changes. `http://localhost:59840/ls_db1/_changes?feed=longpoll&since=500`. According to the documentation http://developer.couchbase.com/documentation/mobile/current/develop/references/couchbase-lite/rest-api/database/get-changes/index.html, I would expect the request to timeout after 60 second. 

Also, I talked to @pasin and he was fairly certain that iOS does not support timeout. 

Expected: No new _changes, the longpoll changes request would timeout after 60 seconds
Actual: The request remains open

**Comment by snej** [comment]
@pasin says he's implemented the same thing on Android and will just port it to iOS.

**Comment by sethrosetter** [comment]
Make sure to let me know when this is fix so I can reenable a couple tests - https://github.com/couchbaselabs/mobile-testkit/issues/760
