### ISSUE TITLE
New replicator calls some IPv4-specific code in PSWebSocketServer

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1238]
When the new BLIP replicator opens a listener socket (i.e. when the new replication protocol is enabled in the CBL listener), it calls some code in the PocketSocket submodule that uses IPv4-specific POSIX network APIs. This may fail if run on an IPv6-only network, which will trigger App Store rejections starting in June 2016.

I [filed an issue](https://github.com/zwopple/PocketSocket/issues/50) against PocketSocket. Looks easy to fix, but I don't know enough about POSIX APIs or IPv6 to be able to fix it without doing some research.

**Comment by lightandshadow68** [comment]
Looks like we can work around this by turning off web sockets. Tested this on CBL 1.3 with corresponding 1.3 sync gateway. 

`repl.customProperties = @{@"websocket": @NO};`

**Comment by snej** [comment]
@lightandshadow68: Does the rejected app use P2P sync? That's the only circumstance under which this issue would come up.

**Comment by lightandshadow68** [comment]
Hello Jens, 

We do not use P2P sync. 

The app was rejected because it stalled during initial sync when running on an IPv6 network during Apple review. 

I was able to replicate this by creating a NAT64 infrastructure WiFi network configured as described here: https://developer.apple.com/videos/play/wwdc2015/719/?time=358 When sync stalled, I noticed the following log entry from CBL...

```
CBLWebSocketChangeTracker[0x1626c14f0 a_sync_gateway ]: Connection error #5, retrying in 32.0 sec: Network is unreachable
```

Switching from the NAT64 WiFi to AT&T LTE on my test device caused sync start and complete. Disabling web sockets prevented the problem all together.

**Comment by lightandshadow68** [comment]
On closer inspection, this isn't the only IPv6 reachability issue. #1239 might be a better fit, as we are connecting to sync gateway behind a HTTP proxy.

**Comment by snej** [comment]
Oh — yes, it definitely sounds like you're hitting #1239. I'll try to escalate that one for the 1.3.1 release. Thanks for letting us know.

**Comment by lightandshadow68** [comment]
Thanks, Jens. I'm currently working on a custom build of CBL that uses Cocoa Lumberjack for logging, so if you have a fix in place, I can include it as well.

**Comment by snej** [comment]
On further thought, I don't think #1239 is the issue, because
* It would affect only the determination of whether the replication is online/offline, whereas the error you're getting indicates the replicator is online and is failing to connect.
* The network setup described in the video you linked to doesn't include an HTTP proxy, so #1239 wouldn't be triggered anyway.

**Comment by snej** [comment]
@lightandshadow68 Could you please file a new issue and include the full logs from the failed sync, with `ChangeTracker` logging enabled? Meanwhile I'll set up NAT64 and try to reproduce the issue.

**Comment by snej** [comment]
Merged to dev branch; closing.
