### ISSUE TITLE
Configurable mapping of document type for view indexing

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1240]
A view can be configured to index only documents of a specific type, where the type is defined as the value of the `type` property. (#590) However, the `type` property is just a (pre-existing) convention, and not all databases use it. Some use a different property, and some use a prefix of the `_id`, so they can't use this optimization.

It would be nice to let the developer specify, per database, how to get the document type. Supporting other properties is easy; just give the property name. For the ID prefix they might need to give the delimiter string that ends the type portion, or for the most flexibility a regexp.

**Comment by brendand** [comment]
FYI, I use the `type` property extensively. For a set of `Record` documents in my database, they all share the same `Form` `document id` property. So when I fetch all the records for a specific form, it's fast.

**Comment by skela** [comment]
@brendand do you find querying the database is fast using this approach ? Just wondering if when they implement this for _id prefixes, whether I can expect any speed improvement. (Because at present querying couchbase-lite is EXTREMELY slow) :(

**Comment by snej** [comment]
Can you give more details? Like, number of documents, what you're mapping, and how long it takes vs how long you'd expect? (Please file a new issue for this, as it's separate from this one.)

**Comment by snej** [comment]
Seems likely this or something like it will happen in 2.0, because we're massively overhauling how indexing and querying are done.

**Comment by jayahariv** [comment]
Closing 1.x issue!
