### ISSUE TITLE
Stale parameter in REST api

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-ios#1241]
What are the valid values for the stale parameter used to query views, and what default behaviour if it is omitted? 

The [docs](http://developer.couchbase.com/documentation/mobile/1.2/develop/references/couchbase-lite/rest-api/design-document/get---db--design--design-doc--view--view-name-/index.html) don't seem to reflect reality right now.

--------
* Version:   CBL 1.2
* Client OS: OIS 9.2
* Server:    4

**Comment by snej** [comment]
It supports `ok` and `update_after` (and `false`, for compatibility with Couchbase Server.) See CBL_Router.m:206-216.

Default behavior is to update the view index (if necessary) before running the query. `ok` tells it not to update the index, and `update_after` tells it to update the index asynchronously _after_ the query. This matches what the docs say; what behavior are you getting that you think is different/wrong?

**Comment by npomfret** [comment]
I think I've caused the error by putting unnecessary quotes around the parameter value.
