### ISSUE TITLE
Replication task missing source or target values

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-ios#1243]
Replication tasks coming back from the REST API only show source OR target values, but not both.  The android version has both.

**Comment by snej** [comment]
`-[CBL_Router activeTaskInfo:]` is _almost_ correct, but it's using `_db.name` for the local db name, except `_db` is nil because `_active_tasks` isn't a handler for any specific database. Instead it needs to get the db from the replicator. Looks like a trivial one-line fix...
