### ISSUE TITLE
Geo view not getting updated

### ISSUE THREAD

**Issue by brendand** [couchbase/couchbase-lite-ios#1244]
I have a view that generates Geo coordinates for searching areas. It emits a CBLGeoPointKey.

Here's my method that generates the view and returns a query.

```
- (CBLQuery *)recordsQueryForLocationField:(TFField *)field {
	CBLQuery *query = nil;
	
	NSString *viewName = [NSString stringWithFormat:@"records-by-geo-%@", self.document.documentID];
	
	CBLView *recordsView = [self.database existingViewNamed:viewName];
 
	if (!recordsView) {
		recordsView = [self.database viewNamed:viewName];
	}
	
	recordsView.documentType = self.document.documentID;

	[recordsView setMapBlock: MAPBLOCK({
		NSDictionary *valuesDict = doc[@"values"];
		NSDictionary *locationData = valuesDict[field.document.documentID];
		emit(CBLGeoPointKey([locationData[@"lon"] doubleValue], [locationData[@"lat"] doubleValue]),
			 nil);
	}) reduceBlock: NULL version: @"1.2"];
	
	query = [recordsView createQuery];
	
	return query;
}
```

Whenever I update a document which should trigger the MAPBLOCK to update the index, it doesn't seem to get called. However, if I change the version number, it will then update the view and then I can see the locations on my map. But if I don't change the version number after editing some location data in my documents, the view never gets updated.

Is it something wrong with my code above when creating the view? I know it's not my query that's causing the problem because I do see results if I change the version number and let it rebuild the index. But it never works "live".

--------
* Version:   1.3 dev commit 2d6e6355e46cacab46d404bfb5e7ceaa1a92a7c9
* Client OS: OS X 10.11.4
* Server:    n/a

**Comment by snej** [comment]
> On May 12, 2016, at 2:45 AM, Brendan Duddridge <notifications@github.com> wrote:
> 
>     recordsView.documentType = self.document.documentID;

This seems wrong. You’re potentially changing the view’s documentType every time you query it. The documentType should stay fixed, since it affects how the view is indexed. Changing the documentType should invalidate the view’s index (and trigger a full re-index on the next query. I’m not 100% sure that actually happens, which might explain the problems you’re having, but even if it did, you wouldn’t want that behavior because it’ll make queries really slow.

Also, the way you’re using the documentType implies that there are a bunch of documents whose ‘type’ property is equal to the current document’s _id. Is that true?

—Jens

**Comment by brendand** [comment]
Yes, that's true. But "self" is my TFForm instance. The documentType property is how I separate one set of records from another. The query fetches TFFormEntry model objects from the database that all have a location within the specified area. Many records will have the same form's documentID. And a form's documentID doesn't change once it's created. So I think this is perfectly normal and helps with the performance of fetching records from a specific form.

The problem isn't the query itself, but the fact that the view isn't being updated unless I change the version number of the map block call.

**Comment by brendand** [comment]
For example, in the following screenshot you'll see a bunch of different doc_type entries. But two that have the same value of `frm-93de90a2e7444ab185575c129cf2d92d` which tells me those are two records that belong to the same form.

<img width="1307" alt="screen shot 2016-05-12 at 1 47 11 pm" src="https://cloud.githubusercontent.com/assets/586075/15228207/3f4711de-1848-11e6-83e7-3f3090c71d92.png">

**Comment by brendand** [comment]
Oh, and just to clarify, a TFFormEntry model object is just what I call a `record`. It's an entry for a form. One of an infinite number that can belong to any form (aka TFForm in my model). But instead of using TFFormEntry as the documentType, I use the form's document ID so I can distinguish one set of records for a form from another. Hope that makes sense.

**Comment by snej** [comment]
OK, that makes more sense. I didn't understand the context around that method.

Turn on `View` and `Query` logging to see what's going on. That might provide some clues.

**Comment by brendand** [comment]
Well, after enabling `View` and `Query` logging, it seems to be working now. I don't know what I did, but I'm going to just close this for now. Sorry to bother you.

**Comment by snej** [comment]
It's always nice to find that there isn't some terrible bug lurking :)

BTW, you can simplify your code a bit — this
```objc
    CBLView *recordsView = [self.database existingViewNamed:viewName];

    if (!recordsView) {
        recordsView = [self.database viewNamed:viewName];
    }
```
is equivalent to
```objc
    CBLView *recordsView = [self.database viewNamed:viewName];
```

**Comment by brendand** [comment]
Thanks for the tip! I'll make the adjustment.
