### ISSUE TITLE
Document conflicting with itself??

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-ios#1249]
What does it mean for a document to have a conflicting revision that is the same as it's own revision:

<img width="383" alt="screen shot 2016-05-18 at 10 13 17" src="https://cloud.githubusercontent.com/assets/5489469/15353516/61ca8cb6-1ce1-11e6-8f8e-2f489dd5aed2.png">

--------
* Version:   1.2
* Client OS: IOS 9.3

**Comment by snej** [comment]
It means there's no conflict. (Unintuitive, yeah, but it comes from the CouchDB API.)

**Comment by snej** [comment]
Also, please ask questions on the [Couchbase web forum](https://forums.couchbase.com/c/mobile) or the [Couchbase Mobile mailing list](https://groups.google.com/forum/#!forum/mobile-couchbase). We use Github issues only for bug reports and feature suggestions. Thanks.
