### ISSUE TITLE
App crashing when writing a document on a background thread with ForestDB 

### ISSUE THREAD

**Issue by jschmid** [couchbase/couchbase-lite-ios#1250]
I am not sure if I should put the issue here or in the ForestDB repo. Let me know if I should move it.

I am using Couchbase Lite on a background thread. I have a helper class that is thread safe and makes sure any part of my app uses the same thread to access the database. 

It looks like:

```swift
let queueName = "DatabaseConcurrencyManager-\(databaseName)"
let qosClass = QOS_CLASS_BACKGROUND
let queueAttrs = dispatch_queue_attr_make_with_qos_class(DISPATCH_QUEUE_SERIAL, qosClass, 0)
self.serialQueue = dispatch_queue_create(queueName, queueAttrs)

dispatch_sync(self.serialQueue) { [unowned self] in
    self.mainCBLManager = CBLManager()
    self.mainCBLManager.storageType = kCBLForestDBStorage
    self.mainCBLManager.excludedFromBackup = true
    self.mainCBLManager.dispatchQueue = self.serialQueue

    do {
        let database = try self.mainCBLManager.databaseNamed(databaseName)
    } catch {
        fatalError("Could not create Couchbase database")
    }
}
```

It works fine and this way the UI does not get blocked while CBL performs its operations.

I sometimes get a crash for no apparent reason on my side. By looking at the threads running during the exceptions I see this:

One of my classes uses my database manager to write to CBL on one thread.
<img width="557" alt="screen shot 2016-05-18 at 16 45 02" src="https://cloud.githubusercontent.com/assets/574168/15363695/d4fc2ce8-1d19-11e6-80bf-e9235cc84b9f.png">

Something, which apparently tries to compact the database, runs on another thread.
<img width="561" alt="screen shot 2016-05-18 at 16 44 49" src="https://cloud.githubusercontent.com/assets/574168/15363751/029e62ba-1d1a-11e6-889a-b50531a4dbfb.png">

I am using:

* Couchbase Lite: 1.2.0 with ForestDB
* iOS: 9.3.2

I haven't had the crash with 1.2.1 yet, but the changelog does not seems to say it has been fixed.

**Comment by snej** [comment]
Please post stack traces / crash logs as text, not screenshots — for instance, right now I can't see them because I'm on the train and the cell connection is too sporadic to download the images. (Use the `bt` command in Xcode's debugger console to dump the current thread's stack.)

**Comment by snej** [comment]
OK, I got the images to download. On first glance this looks like a bug in CBL — ForestDB is invoking a callback during compaction, and our code is accessing the database, but unfortunately the callback happens on a background thread so we violate our own threading rules :-(

**Comment by snej** [comment]
I've checked in a fix on the `release/1.2.2` branch. We don't have automated builds of that yet, so unfortunately you'll need to build it yourself.

**Comment by snej** [comment]
Note to self: This fix isn't needed on the dev or master branch, because the bug doesn't exist there anymore, due to switching to the CBForest C API.

**Comment by jschmid** [comment]
Thanks @snej. Sorry about the screenshots. I just took them out of reflex then I realised after the fact that this crashed had already happened a few times. Thanks for the `bt` tip and for fixing it!
