### ISSUE TITLE
Replication double saving checkpoint.

### ISSUE THREAD

**Issue by geoffreyd** [couchbase/couchbase-lite-ios#1251]
In my app, I am manually triggering a once off sync. Since the update to 1.2 I've noticed that it is always failing to save the checkpoint sequence, this means it does a check of all the documents every sync.

Here is the output of `CBLManager.enableLogging("Sync")`: https://gist.github.com/geoffreyd/6bf3e56b0997d89371250dffd2415e19

It looks like it is actually saving the checkpoint, but then attempting to save a second time with a new sequence number. This then fails to save, due to a 409 conflict, meaning it fails with a `lastSequence mismatch`

Since I have so many documents, this is causing a performance issue.

As you can see from the log, I'm calling `start` on both a pull and push replication at the same time, but this shouldn't be causing this issue.

Is there anything else I can provide that might help diagnose this issue?

I looked at other similar issues, but none of them seemed to have a solution, or where not quite the same.

---
- Version:   1.2.1
- Client OS: iOS 9.3
- Server:    CouchDB 1.6.1

**Comment by geoffreyd** [comment]
Rolling back to 1.1.1-leakfix has fixed this issue for us.

I still see the double saving of checkpoints, but they are both successful (201 status)

**Comment by snej** [comment]
What is the remote server? It has a ".local" URL … is it a local Sync Gateway, or is this a P2P replication?

**Comment by geoffreyd** [comment]
It is a CouchDB 1.6.1 server on the local wifi network.

**Comment by jayahariv** [comment]
Closing 1.x issue!
