### ISSUE TITLE
some deletes not appearing in _changes feed

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-ios#1253]
I've got a situation where I'm deleting 4 documents via the sync gateway.  The changes feed in the sync_gateway looks correct with all 4 deletes appearing:

![screen shot 2016-05-20 at 17 55 39](https://cloud.githubusercontent.com/assets/5489469/15435456/20887e6e-1eb4-11e6-85a5-128448b253c7.png)

The changes feed from the iOS app (via the simulator) only has 2, with the other 2 showing as not deleted:

![screen shot 2016-05-20 at 18 02 34](https://cloud.githubusercontent.com/assets/5489469/15435587/13d8529c-1eb5-11e6-950c-88bd4001c0b0.png)

It seems to be easily reproducible, and its always the 1st 2 docs to be deleted that appear in the IOS changes feed correctly.

I'm using CouchbaseLite 1.2.1 (unofficial) in the client, and couchbase-sync-gateway-community_1.2.1-4_x86_64.deb

**Comment by snej** [comment]
Does it stay that way? I.e. if you query the CBL changes feed a few seconds later, does it still not show the other two docs?

**Comment by npomfret** [comment]
Yes, i stays that way.  At least long enough for me to get some screen shots and create this ticket.  I'll monitor it to see if it ever gets into a correct state.

**Comment by snej** [comment]
OK, that's weird! Could you please turn on SyncVerbose and Database logging, then post the logs starting from the time CBL pulls the deletions? (It's best to upload this to a gist or something, then post the link here, because it's likely to be long.)

**Comment by npomfret** [comment]
Ok, I ran another test.  This time 3 of 4 got marked as deleted.  Here are the screen shots again, this time I've included before and after (I've waited a minute or more before taking the after shots).

Here are the logs:

https://gist.github.com/npomfret/5a43ba7092a632feaea3d06d2d012a4b

![screen shot 2016-05-20 at 19 46 00](https://cloud.githubusercontent.com/assets/5489469/15438475/49202330-1ec4-11e6-92d1-a73582f16c1e.png)

![screen shot 2016-05-20 at 19 46 05](https://cloud.githubusercontent.com/assets/5489469/15438480/4f40f712-1ec4-11e6-93ca-97c77e193155.png)

![screen shot 2016-05-20 at 19 50 16](https://cloud.githubusercontent.com/assets/5489469/15438652/15d2fa56-1ec5-11e6-8db2-b968b029be29.png)

![screen shot 2016-05-20 at 19 50 08](https://cloud.githubusercontent.com/assets/5489469/15438655/19e510ac-1ec5-11e6-9384-2c1c2f9fb74d.png)

**Comment by snej** [comment]
The logs only show 3 revisions being received from the changes feed:
```
Received #3405 {-m6k1tC-1t9jjjyhJyo_5Wj #3-6ce9f71094a48e5bc937f7c7c88479e5 DEL}
...
Received #3406 {-yPZshYRgrqWsruYhQsPYXn #2-4ed495eb768723f41b2782bd69db6081 DEL}
...
Received #3407 {-P36uTOV2uxAypRitYuJS7o #3-11aa2fd2967fa65306c9bfd010979443 DEL}
```

**Comment by snej** [comment]
And the sequence it checkpoints is 3407, not 3408 (the last one shown in the SG feed)
```
CBLRestPuller[http://139.59.180.64:4984/sync_gateway] checkpointing sequence=3407
```
Does your pull replication have any filters or channels set, that could limit what revisions it receives?

If you wouldn't mind running this again, could you instead turn on logging for `RemoteRequest`, and includes logs starting from the time the pull replicator starts up?

**Comment by npomfret** [comment]
There's no filters on the sync.  And I think `RemoteRequest` logging is on already:

<img width="931" alt="screen shot 2016-05-20 at 22 57 59" src="https://cloud.githubusercontent.com/assets/5489469/15443206/5b13d8ce-1ede-11e6-8caa-912e2f4f051e.png">


Retest data to follow...

**Comment by npomfret** [comment]
Ok, ran another test.  This time 3 of 4 updates failed to make it into the changes feed on the client, one 1 worked.

**Comment by npomfret** [comment]
I'm going to close this issue for now.  I've found at least one problem in my sync_function. I can't explain why I'm getting different results each time yet, but for now I'm going to assume it's bug on my side.  I'll reopen it it I don't get anywhere.
