### ISSUE TITLE
Basic auth failure when using NSURLCredential but not when using CBLAuthenticator

### ISSUE THREAD

**Issue by brendand** [couchbase/couchbase-lite-ios#1255]
Using peer-to-peer sync, I'm using SSL with basic authentication. There are two different ways you can provide credentials.

This method used to work I'm pretty sure, but no longer does:

```
NSURLCredential *credential =
[NSURLCredential credentialWithUser:username				
                           password:password
                        persistence:NSURLCredentialPersistenceNone];

self.currentPull.credential = credential;
```

However, this method does work fine:

```
id<CBLAuthenticator> authenticator =
[CBLAuthenticator basicAuthenticatorWithName:username
                                    password:password];

self.currentPull.authenticator = authenticator;
```

It was my understanding that using CBLAuthenticator was an older technique and we should be using NSURLCredentials now instead. 

I'm going to try and get some request and response info and post to this issue, but right now Charles proxy is giving me some trouble with my SSL connection.

--------
* Version:   1.3 beta dev # f18ecd3748ae0d731e6b54e48b27e143ffffa2a2
* Client OS: iOS 9.3.2 and OS X 10.11.5
* Server:    peer-to-peer sync

**Comment by brendand** [comment]
Well I'm not quite sure how to get my app to work properly with Charles for peer-to-peer replication. It worked fine communicating with Cloudant, but not with peer-to-peer.

I get the following error trying to connect between my Mac and iPhone.

```
14:28:43.778‖ WARNING: CouchbaseLite: SSL server <iphone-6s.local.> not trusted; cert chain follows: {at CBLWarnUntrustedCert:289}
14:28:43.779‖ WARNING:     Anonymous: error = Host name mismatch {at CBLWarnUntrustedCert:301}
14:28:43.779‖ WARNING:     Charles Proxy Custom Root Certificate (built on Voyager.local, 9 May 2016): error = (null) {at CBLWarnUntrustedCert:301}
```

I have the Charles profile installed on my phone and I've enabled proxy connections to my Mac from my iPhone.

I may need to just disable SSL for this testing.

**Comment by snej** [comment]
Actually CBLAuthenticator is the preferred API. But credentials should still work, so this does look like a bug.

**Comment by snej** [comment]
I think `NSURLCredentialPersistenceNone` may be the problem — the `setCredential:` method stores the credential into an `NSURLProtectionSpace`, and IIRC if the cred has persistence=none the protection space will ignore it. `NSURLCredentialPersistenceSession` (sp?) should work.

**Comment by brendand** [comment]
Ah ok. I'll give that a try. But if CBLAuthenticator is the preferred API then I'll just stick with that.

**Comment by brendand** [comment]
Yes, it seems that NSURLCredentialPersistenceSession solved the problem too.

I'll close this since it's obviously not a bug. 

Thanks for the quick response!
