### ISSUE TITLE
Unexplained behaviour deleting document

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-ios#1256]
I don't think this is a bug, I just don't understand the behaviour I'm seeing.  Hope someone could explain.

I have 4 documents in my db, and I delete one of them.  The screen shots below of the SG `_changes` feed are taken from my browser logged in as the same user as my IOS simulator.  I'm using CBL 1.2.1.

My sync_function just has this for dealing with deletes, right at the start:

    if(doc._deleted) {
        return;
    }

This is the user. The channel _ch\_c570..._ is the one of interest:

![screen shot 2016-05-23 at 10 59 38](https://cloud.githubusercontent.com/assets/5489469/15467579/2ed34de4-20d7-11e6-932c-80748eb47bb3.png)

And this is the document (id _-3J2M..._) that's going to be deleted, which is in channel _ch\_c570..._:

![screen shot 2016-05-23 at 10 59 46](https://cloud.githubusercontent.com/assets/5489469/15467599/4da7e194-20d7-11e6-8279-79e97f2fa37b.png)

This is the SG `_changes` feed seen by the above user (_c4ed..._):

![screen shot 2016-05-23 at 10 59 56](https://cloud.githubusercontent.com/assets/5489469/15467615/629f523a-20d7-11e6-9c0d-706dd47dbe68.png)

This is the `_changes` feed taken from the simulator (change _1095_ has the document _-3J2M..._):

![screen shot 2016-05-23 at 11 00 04](https://cloud.githubusercontent.com/assets/5489469/15467683/b9419ee0-20d7-11e6-9b51-25c97363093e.png)

At this point I delete the document using an _admin_ user (**not** the same user thats logged into the device).  The output from the delete is:

`"{"id":"-3J2MSLICp3mnENpkblYOy3","ok":true,"rev":"2-1c3ac9136429a53ce9df8ec8df228c8a"}"`

[Here are the sg logs](https://gist.github.com/npomfret/4293519f7586e18127d716926e87d1bc).  After the delete, this is what the document looks like on the server. As expected it contains `_deleted: true` and the rev is as above _2-1c3a..._:

![screen shot 2016-05-23 at 11 07 13](https://cloud.githubusercontent.com/assets/5489469/15467797/3fd52170-20d8-11e6-80c9-17efc9a3d663.png)

However, unexpectedly at this point the user appears to have had a channel revoked, channel _ch\_c570..._, and now looks like this:

![screen shot 2016-05-23 at 11 07 05](https://cloud.githubusercontent.com/assets/5489469/15467828/6a99d9e6-20d8-11e6-97e3-279f01441b10.png)

Why??

And so the SG `_changes` feed as seen by that user now has 2 documents missing, not just the deleted one, but also another document that was in that channel.  They aren't in there as _deletes_ or even _removed_, they're just missing:

![screen shot 2016-05-23 at 11 07 20](https://cloud.githubusercontent.com/assets/5489469/15467882/b79f2c1e-20d8-11e6-9897-3445d1a9e81b.png)

And the `_changes` feed from the simulator isn't showing any changes at all, so my app doesn't update:

![screen shot 2016-05-23 at 11 07 28](https://cloud.githubusercontent.com/assets/5489469/15467926/048526fa-20d9-11e6-8ae0-cc6638164757.png)

Finally, if I log into the SG `_changes` feed using the admin user, I can see the deleted document as expected at seq _3534_:

![screen shot 2016-05-23 at 11 09 31](https://cloud.githubusercontent.com/assets/5489469/15468172/90cb901c-20da-11e6-85f3-236542678cc5.png)

The iOS client logs are [also here](https://gist.github.com/npomfret/4293519f7586e18127d716926e87d1bc)

**Comment by snej** [comment]
If you're asking a question, we prefer that to happen on the mailing list or web forum.
Also, this looks like it's all about SG, but you filed it in the iOS issue tracker.

> However, unexpectedly at this point the user appears to have had a channel revoked, channel ch_c570

The sync function must have previously been calling `access()` to grant the user access to that channel, when run on this document. Now that it no longer does so, that access is revoked.

> And so the SG _changes feed as seen by that user now has 2 documents missing, not just the deleted one, but also another document that was in that channel. They aren't in there as deletes or even removed, they're just missing

There are some edge cases in SG's change handling; when a user loses access to a channel, they may not get notifications in the changes feed for the documents in that channel. But you should take this up with the SG people, since I haven't worked on SG in a year and a half and don't know the current state of affairs. Again, posting to the mailing list or forum would be best.
