### ISSUE TITLE
Bundle libCBLJSViewCompiler.a in the listener

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-ios#1257]
On .net and java-core, the filter and view compilers are bundled in the listener dependency.

On iOS, it's a separate libCBLJSViewCompiler.a library. It would be easier to use if it was in the listener framework.

---
- Version:   1.2.1-13

**Comment by brendand** [comment]
Perhaps a silly question, but not for me. What is that library used for on iOS? I don't even include it in my project and all seems to work fine without it.

**Comment by adamski** [comment]
I think this is what I need to remove a manual build step when using [ReactNativeCouchbaseLite](https://github.com/couchbaselabs/react-native-couchbase-lite) on iOS via CocoaPods. I've been trying to find a way to add the `CBLRegisterJSViewCompiler.h` header via the Podspec. Currently it needs to be dragged from the downloaded release's `Extras` folder. This shouldn't be necessary, as the couchbase-lite-ios repo contains everything we need.

**Comment by snej** [comment]
libCBLJSViewCompiler.a implements support for map/reduce functions written in JavaScript. It's used by Cordova/PhoneGap applications.

I'm trying to remember why it's not bundled into the listener. Originally (when we still supported iOS 6) we had to include a copy of JavaScriptCore because it wasn't public API, and that made the library rather large. But that's no longer the case.

**Comment by brendand** [comment]
But for regular iOS apps, if it's not needed, it's good that it's still separate.

**Comment by adamski** [comment]
The JSViewCompiler is not JavaSciptCore! And its only 252Kb...

**Comment by jamiltz** [comment]
@adamski The size of JSViewCompiler in previous versions of CBL was bigger because it had to include JavaScriptCore (not public at the time, see Jens' comment above). Now JavaScriptCore can be added separately in the build phases in Xcode, thus reducing the size of the JSViewCompiler static lib. I think everyone agrees here that it makes sense to make that change.

**Comment by adamski** [comment]
Any progress on this?

**Comment by snej** [comment]
It's not planned for 1.3...

**Comment by snej** [comment]
We can't think of any reason not do do this :) and it's a pretty trivial fix.

**Comment by pasin** [comment]
Note: Phonegap plugin build needs to be updated and tested after doing this.

**Comment by pasin** [comment]
When move the library into the core framework, existing users will need to add JavaScriptCore.framework into their dependencies. I discussed this with @djpongh, we will do this in a major release.

**Comment by jayahariv** [comment]
Closing 1.x issue!
