### ISSUE TITLE
Concurrent replication of multiple databases fail

### ISSUE THREAD

**Issue by jfspencer** [couchbase/couchbase-lite-ios#1258]
I am running into an issue where replication internally fails when I simultaneously start replications against two databases at the same time. I am using non-continuous replication via the REST API. 

When the replication failure occurs I continuously get an Idle response from the _active_tasks end point with the same structure as the continuous replication response, but continuous = false. 
Replication request starts but never provides the response.

Concurrent replication of multiple databases was working with cbl 1.1.1

--------
* Version:   1.2.1
* Client OS: iOS 9
* Server:    CouchDB 1.6.1

**Comment by snej** [comment]
Can you describe the problem in more detail? List the steps to reproduce, and what happens vs. what you expected. Thanks.

**Comment by snej** [comment]
Any update on this? Without more details, we'll have to close it.

**Comment by jfspencer** [comment]
I have two objects in my application that independently interact with the cbl REST API . during my app initialization i am using Promise.all([db1.replicate(), db2.replicate()]) to update both databases. When monitoring the _active_tasks on both databases one of them indefinitely returns the

`{status:"idle", continuous:false}` 

object like continuous replication(except continuous is false in the response and continuous is set as false in the request). 

_active_tasks never gives back and empty array for this database and subsequent one off replication with that database silently fail.

I am in progress putting together a test app to show this behavior. I have had other tasks take higher priority, but will update here when I have the test complete

**Comment by snej** [comment]
The best thing to do would be to turn on `Sync` logging (see the wiki for details) and post a link to the log output.

**Comment by jfspencer** [comment]
Ah cool, I will post that back shortly.

**Comment by pasin** [comment]
I'm closing the issue now. @jfspencer, if you have any additional info, please let us know and we can reopen the issue. Thanks.
