### ISSUE TITLE
OpenID Connect authenticator

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1266]
https://github.com/couchbaselabs/couchbase-lite-api/issues/147

**Comment by snej** [comment]
Current work is on the [feature/openid](https://github.com/couchbase/couchbase-lite-ios/tree/feature/openid) branch. It's pretty much done at this point, including a GUI implementation in the Extras folder.

**Comment by snej** [comment]
Merged to `dev` branch.

**Comment by newlix** [comment]
Will 2.0 support this?

**Comment by snej** [comment]
Hi! Please ask your question on the [Couchbase web forum](https://forums.couchbase.com/c/mobile) or the [Couchbase Mobile mailing list](https://groups.google.com/forum/#!forum/mobile-couchbase). We use Github issues only for bug reports and feature suggestions. Thanks.
