### ISSUE TITLE
Replication requires write permission on Cloudant database even when doing read-only replication

### ISSUE THREAD

**Issue by tangledfruit** [couchbase/couchbase-lite-ios#1267]
### Steps to reproduce:

1. Create an account and database on Cloudant (free tier is fine).
2. Configure an account with read and replicate permissions as shown here.
<img width="860" alt="screen shot 2016-05-27 at 16 18 30 copy" src="https://cloud.githubusercontent.com/assets/16505465/15623361/87fad894-2427-11e6-943d-9f618fe27646.png">
3. Configure CBL to replicate from this database as follows:
```
2016-05-27 16:18:01.320 [info][tid:com.facebook.React.JavaScript] 'http request url = ', 'http://localhostUser:localhostPassword@localhost:3486/_replicate', ' options = ', { method: 'post',
  headers: 
   { Accept: 'application/json',
     'Content-Type': 'application/json' },
  body: '{"source":"https://username:password@dbname.cloudant.com/fs","target":"fs","continuous":true}' }
```

### What happens: 

```
16:18:01.826‖ CBLSocketChangeTracker[0x7fc3005ca110 fs]: Can't connect, giving up: Error Domain=CBLHTTP Code=403 "403 forbidden" UserInfo={NSURL=https://username:password@dbname.cloudant.com/fs/_changes, NSLocalizedFailureReason=forbidden, NSLocalizedDescription=403 forbidden}
```

### Workarounds:

If I revise the account permissions to grant **_writer** permission, the replication succeeds, but for security reasons, I don't want to do that. (I can do it as a temporary workaround, but not in production.)

If I use Apache CouchDB 1.6.1 on the same machine with the same credentials, the replication succeeds.

If I copy and paste the URL from the error message into a browser, I get a valid changes feed response.

So, what's different about Couchbase Lite?

--------
* Version:   1.2
* Client OS: Mac 10.11.5 hosting iOS 9.3 simulator
* Server:    Cloudant

**Comment by snej** [comment]
I was stumped for a minute, then I remembered an earlier case of this happening. Couchbase Lite prefers using POST to `_changes` because it avoids URL-length limitations. Unfortunately Cloudant has a bug where all POST requests fail with a 403 if you don't have write access, even though a POST to `_changes` is read-only.

This was filed as #1020.

**Comment by snej** [comment]
Looks like the existing workaround is triggered by a 405 or 401 status, but not by a 403; we must not have seen that one before. I've added 403.

Would you be able to check out and build the `release/1.2.2` branch, and test the fix?

**Comment by tangledfruit** [comment]
Yes, I'll take a look. I'm currently loading via the react-native-couchbase-lite module. I may have to do a bit of juggling to bypass that mechanism, so it may take me a bit.

**Comment by tangledfruit** [comment]
@snej: Confirmed: The fix is good. Thank you very much for the quick turnaround!

**Comment by snej** [comment]
Merged to dev branch.
