### ISSUE TITLE
Issue with non continuous pull

### ISSUE THREAD

**Issue by ShivangiBhatt** [couchbase/couchbase-lite-ios#1269]
Hi Couchbase,

I have a use case where I want non-continuous pull and continuous push replication. There are several times when while observing replication progress my changesCount for push and pull returns 0, even when pull and push replications are active state. Due to this, my app gets stucked there. What should I do in such a case. Also Let me know if I can integrate couchbase on background thread, as it gets crashed if I try to run(as suggested on [http://developer.couchbase.com/documentation/mobile/current/develop/guides/couchbase-lite/native-api/manager/index.html]) on background thread

--------
* Version:  Couchbase version(1.1.0)
* Client OS: iOS

**Comment by snej** [comment]
Can you explain why your app gets stuck? What is it waiting for?

Please file a separate issue about the problems with a background thread, or ask a question on the web forum.

**Comment by ShivangiBhatt** [comment]
I need to complete pull cycle before proceeding and while observing replication progress my changesCount for pull returns 0, even when pull replications are active state. Infect there are times when pull replication status is stopped or idle, but my changes count is not equal to completed count for pull

**Comment by snej** [comment]
The pull is complete when the status changes to Stopped or Idle.

**Comment by ShivangiBhatt** [comment]
why it enters idle state even if required data is not yet recieved.

**Comment by snej** [comment]
I need more details to understand the problem. How many documents are on the server that should be pulled? How many are actually pulled? Is this a continuous or one-shot replication? Does the replication's lastError property have an error in it?

Turning on `Sync` and `SyncVerbose` logging will help. See the Github wiki for info on how to turn on logging. Don't paste entire logs here; put them in a gist or something.

**Comment by pasin** [comment]
I'm closing the issue now. @ShivangiBhatt if you could provide additional info as @snej's suggested, please let us know and we can reopen the issue. Thanks.
