### ISSUE TITLE
iPhone sleep seems to cause rest client to fail permanently

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-ios#1270]
It seems that as soon as my iPhone sleeps and re-awakes my app stops working.  I'm getting this error from the rest api when requesting changes `http://admin:pass@localhost:5984/pomochat_7846450b-d693-4f80-93fe-8f03f3b7fd3d/_changes?since=6847&feed=longpoll&timeout=5000&include_docs=true`:

From my app:
`... caused by => TypeError: Network request failed]`
Which happens over and over because its in a loop.

From CBlite:
`2016-06-02 13:02:13.586 [error][tid:main][RCTWebSocketManager.m:84] WebSocket connection failed with error Error Domain=NSPOSIXErrorDomain Code=57 "Socket is not connected"
`
..the full log is [here](https://gist.github.com/npomfret/97414cc84347dadcd8425f0beea8bf61), and another example [here](https://gist.github.com/npomfret/1e3c29dcf8b6379d2f750bc056c3ba7e).

I need to restart the app to get it to work.  i can't get it to happen in a simulator, only on a physical device for some reason.

Using `Couchbase Lite 1.2.1 (unofficial)`

**Comment by snej** [comment]
I don't recognize any of those error messages. In particular, CBL does not use a class named `RCTWebSocketManager`.

Is this a PhoneGap app? The URL `http://admin:pass@localhost:5984` looks like it comes from an Android device, not iOS; the iOS listener uses a URL like `http://xxx.couchbase./`.

**Comment by npomfret** [comment]
Its a react-native app.  There's a mix of react-native and coucbase-lite in the logs

**Comment by snej** [comment]
OK, but none of the logs you've shown are from Couchbase Lite, so I don't have anything to go on.

**Comment by snej** [comment]
The problem probably has to do with the listener socket. If the URL you use is `http://admin:pass@localhost:5984`, that implies that the listener has opened a real TCP socket. The OS is going to forcibly close that socket when the app is backgrounded.

Generally we don't do that on iOS, instead we use an NSURLProtocol to create a fake "socket". This avoids problems with backgrounding, as well as with security. Sounds like the react-native plugin isn't doing this; you should file a bug against it. (I don't know who writes it; it isn't Couchbase code.)

**Comment by snej** [comment]
Oops, I forgot the react-native plugin is our (unofficial) project! Thanks James.

**Comment by npomfret** [comment]
@snej The linked logs are all from couchbase lite.

**Comment by snej** [comment]
@npomfret They're from your app, which _uses_ Couchbase Lite, but none of the log messages you showed were generated by Couchbase Lite code. As I said above, `RCTSocketManager` is not our class — judging by the prefix, it seems to be part of React Native.
