### ISSUE TITLE
Disable App Transport Security on Mac OSX LiteServ

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-ios#1271]
```16:07:32.631‖ CBLRemoteJSONRequest[POST http://192.168.0.111:4985/db/_revs_diff]: Got error NSURLError[-1022, "The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.", <http://192.168.0.111:4985/db/_revs_diff>]<--CFCFNetworkError[-1022]```

Currently 1.3.0+ Mac OSX LiteServ cannot replicated with non ssl enabled endpoints. This need to be disabled for LiteServ builds so the tests can function as before.

Here is how to disable App Transport Security - http://stackoverflow.com/questions/32631184/the-resource-could-not-be-loaded-because-the-app-transport-security-policy-requi

**Comment by sethrosetter** [comment]
@snej, assigning to you as @michaelkwok said this requires code changes

**Comment by snej** [comment]
![Plist settings](http://i.stack.imgur.com/SZi2V.png)
