### ISSUE TITLE
pendingDocumentIDs is incorrect

### ISSUE THREAD

**Issue by 666tos** [couchbase/couchbase-lite-ios#1274]
When syncing database for the first time (just pulling), `pendingDocumentIDs` of push replication contains all documents which were pulled.
`changesCount` is actually 0
When stopping/starting replication `pendingDocumentIDs` are cleaned up.

Also, noticed that `pendingDocumentIDs` sometimes don't clean up properly and some documents are never removed

--------
* Version:   1.2.1
* Client OS: iOS 9.3.1
* Server:    4.1

**Comment by snej** [comment]
This must be related to echo suppression, where docs inserted by a pull shouldn't be pushed back. When the pusher skips over the pulled revision, it sounds like it isn't advancing the last-sequence checkpoint past it.

`pendingDocumentIDs` was re-implemented a few months ago in commit f7dc8dc, but this isn't in a release yet (it'll be in 1.3), and I suspect it still has the same problem.
