### ISSUE TITLE
REST API does not allow GET on a db with "/" in its name

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-ios#1285]
--------
* Version:   N/A
* Client OS: 1.3.0.17
* Server:    N/A

`http GET http://localhost:59840/_all_dbs`
```
[
    "foward/slash"
]
```

`http GET http://localhost:59840/forward%2Fslash`
```
{
    "error": "not_found",
    "status": 404
}
```

As a sanity check, I issue the command against Android and it was successful:

`http GET http://192.168.0.14:5984/forward%2Fslash`
```
{
    "db_name": "forward/slash",
    "db_uuid": "c0ea3670-6390-4049-b2fd-73a00d7346f6",
    "disk_size": 64120,
    "doc_count": 0,
    "instance_start_time": 1465520854746000,
    "update_seq": 0
}
```

**Comment by snej** [comment]
Weirdly, there is already a (passing) unit test for this:
```objc
    Send(self, @"PUT", @"/database%2Fwith%2Fslashes", kCBLStatusCreated, nil);
    dbInfo = Send(self, @"GET", @"/database%2Fwith%2Fslashes", kCBLStatusOK, nil);
```

**Comment by snej** [comment]
The exact steps you gave above are working fine for me. I'm building from the `dev` branch.

**Comment by snej** [comment]
Works fine with the latest `master` branch too (commit bc47d0c11b6c5dc4b5528cead2a6c421a5bd064c.)

**Comment by pasin** [comment]
@sethrosetter could you retest with the current master branch?

**Comment by sethrosetter** [comment]
This works for me now.
