### ISSUE TITLE
continuous replication from sync_gateway freezes

### ISSUE THREAD

**Issue by yonahforst** [couchbase/couchbase-lite-ios#1286]
I'm using CBLlite from within a react-native app using https://github.com/couchbaselabs/react-native-couchbase-lite

I notice that sometimes my continuous pull replication with the server just seems to freeze. When I do a GET request to the `_active_tasks` endpoint, I see the push and pull replications with a status of IDLE, but when I make a change to the documents on the sync_gateway, those changes don't get pulled down to my app.

I've opened an issue for this on `react-native-couchbase-lite` (https://github.com/couchbaselabs/react-native-couchbase-lite/issues/61) but I don't think the problem is on the react native side. 

here are my ios logs. https://gist.github.com/yonahforst/3859beefbe1cf404a92b1b6264b186a2
you can see that the last CBLRestPuller entry is around line 3191

Stopping and starting the app gets the pull replication working again.

---
- Version:   1.2.1 community
- Client OS: iOS 9.3 (simulator) & 9.3.1 (iphone)
- Server:    Couchbase Sync Gateway/1.2.1(4;26c202a)

**Comment by snej** [comment]
Hm. Could you enable `ChangeTracker` logging please? That'll monitor what's going on with the `_changes` feed from the server. Thanks.

**Comment by yonahforst** [comment]
I have `ChangeTrackerVerbose` enabled in the logs above. Should I enable them both?

**Comment by yonahforst** [comment]
This might be helpful. Here is a side-by-side look at the `_active_tasks` endpoint on the simulator, the document on the simulator, and the `_changes` feed from the sync_gateway:

**Comment by snej** [comment]
According to the logs, there just isn't any more data received on the changes feed after 17:33:14.998.

It looks as though the app is re-launched at 17:46:40? At least, there's a message "Launching Couchbase Lite". However, the app doesn't start a puller, since the only Sync logs are from a pusher.

**Comment by yonahforst** [comment]
Yeah, the app was "reloaded" (it's a react native app) at 17:46 and ran through the startup sequence. 

So the react-native app interacts with CBL via the REST API; It posts a push and pull (continuous) replication to the `_replicate` end point on startup. These replications should persist between app backgrounding and foregrounding, right? The replications are both there in `_active_tasks` with a status of `idle` but only the pull replication syncs

**Comment by yonahforst** [comment]
sorry, in my previous comment i meant to say that only the *push* replication syncs

**Comment by npomfret** [comment]
I think I am seeing the same issue. To reproduce it I just stop and start the sync gateway while push and pull replication tasks are running.  After I restart the gateway **only the push replication tasks is working as expected**.  From the rest endpoint it appears as that they are both running without problem.

**Comment by pasin** [comment]
Would it be possible that the SGW session is expired and needs to be recreated. If the SGW session is expired, the (continuous/longpoll) pull replicator may not be able to detect the error until _changes feed is timeout.

**Comment by npomfret** [comment]
I can't reproduce with 1.3x.

**Comment by snej** [comment]
Sounds like this may have been fixed … @yonahforst, are you still having this problem in 1.3? If not, we'll close the bug in a week or so.

**Comment by pasin** [comment]
I'm closing this issue as no response.
