### ISSUE TITLE
OpenID Connect test with Google OpenID failed

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#1289]
I have create a new google project according to the instruction from https://github.com/couchbase/sync_gateway/wiki/OIDC-Notes. The SGW config is https://gist.github.com/pasin/917109766b744b33bbd838a7bd645c3a.

Issue: The web view shown with the following content:

<img width="439" alt="screen" src="https://cloud.githubusercontent.com/assets/801454/16023670/ad52f27c-3172-11e6-8630-5452e4a77624.png">

**Comment by adamcfraser** [comment]
@jens I gave you the wrong answer when you asked me earlier about using end.of.auth to identify the redirect in the webview.  I had forgotten that the OP may use the redirect URI as part of its validation, as Google does.

**Comment by pasin** [comment]
Should we use a custom URL scheme for the callback to the client instead? For example, facebook login uses 'fb<someid>'.

**Comment by adamcfraser** [comment]
Google at least is requiring a public domain, so I don't think that a custom URL scheme would help here (unless I'm missing something).

The client knows what the callback URI is going to look like - it's in the query string that's initially passed to the webview - so I'm hoping it's not too much more work to switch the detection to look for that, instead of end.of.auth.

**Comment by adamcfraser** [comment]
Actually Pasin you may be right - looking at the OpenID spec it looks like the redirect URI may use an alternate scheme:
http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest

I'll do a quick test w/ Google to see if it's supported there.

**Comment by adamcfraser** [comment]
@jens I added release-prep and 1.3 to this, based on our discussion this afternoon.  The end.of.auth URL is incompatible with Google as an OP.

**Comment by jens** [comment]
You got the wrong @jens :-)

**Comment by snej** [comment]
OK, I've changed the UI code to stop altering the `redirect_uri`. Haven't verified with Google OP yet.

**Comment by snej** [comment]
Verified with Google OP, using the SG config Pasin gave above.
