### ISSUE TITLE
CouchbaseLiteListener seems to stop when phone sleeps

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-ios#1290]
I have a `CouchbaseLiteListener` started in a react-native app.  It seems that when the iPhone reawakens from sleep the listener is no longer running, at least it's not accepting http requests any more.  My javascript `fetch` code just gets an err, something like:

`Error: http error for GET 'http://admin:pass@localhost:62132/pc_65/_changes', caused by => TypeError: Network request failed `

Any idea what causes this to happen, or what a good solution might be? 

And how can I turn on logging for the listener process?

Ideally, I wouldn't have a listener at all but for some reason react-naive cannot talk to the internal url (`http://lite.couchbase./`).

(ref: https://github.com/couchbaselabs/react-native-couchbase-lite/issues/56#issuecomment-225443499 and https://github.com/couchbase/couchbase-lite-ios/issues/1270)

**Comment by npomfret** [comment]
On top of this, I tried to re-start the listener when my app because active again.  Sometimes it works, but sometimes I get the error:

`Attempting to accept while connected or accepting connections. Disconnect first.`

I also tried calling `stop` on the listener as the app because inactive, but it look like `stop` isn't implemented.

Any ideas how I can keep the `CBLListener` alive?

**Comment by snej** [comment]
It would be better not to use CBLListener for intra-app communications. Instead get the `internalURL` property of the CBLManager and use that as the root URL of the REST API. As long as the JS engine is using NSURLSession to send HTTP requests, this will work. The advantage is that it doesn't open any real TCP sockets; this is more secure and it avoids the problem you're describing where the OS will kill listener/server sockets whenever the app is backgrounded.

**Comment by npomfret** [comment]
@snej - thanks for the reply.

We can't get the internalUrl to work for some reason.  We're trying to write a react-native wrapper for Couchbase lite ([see](https://github.com/couchbaselabs/react-native-couchbase-lite/issues/56)).  For some reason the internalUrl doesn't seem to be available to the react-native process.  Both the `fetch` and `XmlHttpRequest` apis just get connection exceptions if they try to use it.  Hence we're going down the CBLListener path for now until we can understand what's going on.

The problem we are facing is that the device kills the listener when the app changes state and is put in the background or the screen lock comes on.

It think called stop\start on the listener when the app changes state will work for now.  It seems that the Ios simulator behaves differently to a real device and doesn't actually kill the listener when the app because inactive.
