### ISSUE TITLE
Insecure log line regarding login

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-ios#1293]
With the addition of the OpenID authenticator, [this line](https://github.com/couchbase/couchbase-lite-ios/blob/d02ad4486d508f4adc9c907c5095533c795e9b2e/Source/CBLRemoteLogin.m#L134) is now insecure as it displays the code needed to get the OpenID token, which can be replayed to Sync Gateway.  

--------
* Version:   feature/openid build 
* Client OS: All
* Server:    n/a

**Comment by snej** [comment]
Fixed on `feature/openid` branch.

Now redacting any URL query param whose name contains `token` or `code`, so this should also help for OAuth. (Let me know if there are any other param names to add to that list.)
