### ISSUE TITLE
super.init(for: document) in swift 3 error

### ISSUE THREAD

**Issue by orozkoinsider** [couchbase/couchbase-lite-ios#1294]
I am trying to create an initializer that picks the CBLDocument and return the CBLModel, but swift 3 is complaining that I must call a designated initializer of the superclass 'CBLModel'. 

@objc(User)
class User: CBLModel {
    @NSManaged var name: NSString
    
    init(document: CBLDocument) {
        //Seems that I can't call to this initializer
        super.init(for: document)
    }
}

--------
* Version:   1.2.1
* Client OS: iOS

**Comment by orozkoinsider** [comment]
Workaround:

    class func withUser(document: CBLDocument) -> User {
        return User(for: document)
    }

**Comment by snej** [comment]
It's intentional that you can't initialize CBLModel or its subclasses directly. If you could, you could create multiple instances for the same document, which isn't allowed. Instead, you use factory methods to instantiate models, as in your workaround.
