### ISSUE TITLE
No public API for CBLRemoteLogging

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1300]
It turns out I never surfaced a public API for pushing logs to Sync Gateway. I have a test app that does it, but it has to use the private headers `CBLRemoteLogging.h` and `CBLTimeSeries.h`.

**Comment by pasin** [comment]
@snej does this feature need to go into 1.3?

**Comment by snej** [comment]
I've asked Wayne.

**Comment by snej** [comment]
#1339
