### ISSUE TITLE
OIDC needs an API to clear ID Tokens from the keychain

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#1302]
Without this ability, the OIDC authenticator will continue to use the old ID Token and refresh token so the app cannot switch the user.

**Comment by pasin** [comment]
We will need a new API for this so we need to evaluate if we will include this feature in 1.3 or not.

**Comment by snej** [comment]
@sethrosetter: for your tests do you need a REST API for this too?

**Comment by sethrosetter** [comment]
@snej We are only manual testing OpenID connect for 1.3 via a sample app, so the logout would have to be added to grocery sync.

**Comment by snej** [comment]
Cross-platform issue is https://github.com/couchbaselabs/couchbase-lite-api/issues/156.
