### ISSUE TITLE
test04_ReplicateAttachments hang

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#1307]
test04_ReplicateAttachments (and the other tests that push attachments to SGW) hang and then timeout.

CBL iOS hangs inside CBLMultiStreamWriter when it write data into the stream:
https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CBLMultiStreamWriter.m#L254

SGW log:
```
2016-06-20T15:07:34.733-07:00 HTTP:  #012: POST /cbl_replicator_scratch/_revs_diff HTTP/2
2016-06-20T15:07:34.733-07:00 HTTP+: #012:     --> 200   (20.1 ms)
2016-06-20T15:07:34.738-07:00 HTTP:  #013: PUT /cbl_replicator_scratch/oneBigAttachment?new_edits=false HTTP/2
2016-06-20T15:07:34.742-07:00 HTTP:  #014: POST /cbl_replicator_scratch/_bulk_docs HTTP/2
2016-06-20T15:07:34.742-07:00 HTTP+: #014:     --> 201   (0.3 ms)
```

Note:
1. When I ran the same test with SGW 1.2.1 which doesn't have HTTP/2 enabled, the test was passed.
2. I modified SGW code to disable HTTP/2 and reran the same test, the test was passed.

--------
* Version:   Master (f4c6eca0a95ab0e05d7982c36ce801c1cf08c1c6)
* Client OS: iOS 9.3 iPhone 6s Simulator
* Server:    SGW 1.3 (https://github.com/couchbase/sync_gateway/commit/c7729e225eea4a6e2021125b12635c295badd307)

**Comment by pasin** [comment]
@snej and @adamcfraser , please let me know if you have any comments on this issue.

**Comment by pasin** [comment]
I enabled CBLMultipartWriter log.

```
15:07:36.060‖ MultiStreamWriter: <CBLMultipartWriter: 0x60c0000ed280>: Received event 0x4
15:07:36.060‖ MultiStreamWriter: <CBLMultipartWriter: 0x60c0000ed280>:   Wrote 32768 (of 32768) bytes to _output (total 25968640 of 34120666)
15:07:36.061‖ MultiStreamWriter: <CBLMultipartWriter: 0x60c0000ed280>:   Refilling buffer
15:07:36.061‖ MultiStreamWriter: <CBLMultipartWriter: 0x60c0000ed280>:     read 32768 bytes from <__NSCFInputStream: 0x60d000052e40>
15:07:36.061‖ MultiStreamWriter: <CBLMultipartWriter: 0x60c0000ed280>:   refilled buffer to 32768 bytes
15:07:36.061‖ MultiStreamWriter: <CBLMultipartWriter: 0x60c0000ed280>: Received event 0x4
15:07:36.061‖ MultiStreamWriter: <CBLMultipartWriter: 0x60c0000ed280>:   Wrote 32768 (of 32768) bytes to _output (total 26001408 of 34120666)
15:07:36.061‖ MultiStreamWriter: <CBLMultipartWriter: 0x60c0000ed280>:   Refilling buffer
15:07:36.061‖ MultiStreamWriter: <CBLMultipartWriter: 0x60c0000ed280>:     read 32768 bytes from <__NSCFInputStream: 0x60d000052e40>
15:07:36.061‖ MultiStreamWriter: <CBLMultipartWriter: 0x60c0000ed280>:   refilled buffer to 32768 bytes
15:07:36.061‖ MultiStreamWriter: <CBLMultipartWriter: 0x60c0000ed280>: Received event 0x4
```

**Comment by adamcfraser** [comment]
I assume you're also building SG with go 1.6 or later to pick up the HTTP/2 support?

**Comment by pasin** [comment]
Yes, go 1.6.2.

**Comment by adamcfraser** [comment]
That CBLMultipartWriter looks like it's making progress on the large attachment (the total is increasing) - does it eventually complete (or eventually hit an error)?

**Comment by pasin** [comment]
No error, just hang at https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CBLMultiStreamWriter.m#L254.

**Comment by pasin** [comment]
SGW Log after enabling GODEBUG=http2debug=1:
https://gist.github.com/pasin/c4970368e961256c1fd68e09a12e269e

**Comment by pasin** [comment]
From @adamcfraser, SGW 1.3 will be built with Go 1.5 which doesn't support HTTP/2 so we could resolve this issue after 1.3.

**Comment by pasin** [comment]
I have just found a ticket (https://github.com/couchbase/couchbase-lite-ios/issues/1170) created for the same issue. From the ticket, it appears to be a CFNetwork bug. I'm closing this ticket now.
