### ISSUE TITLE
ForestDB TTL Performance issue

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#1309]
I have noticed some performance issue when running Database_Tests.test26_DocumentExpiry with ForestDB storage engine. In general the test is failed due to timeout. I would need to increase the timeout at the line below from 5 seconds to 30 seconds to make the unit test passes.

https://github.com/couchbase/couchbase-lite-ios/blob/master/Unit-Tests/Database_Tests.m#L1642

--------
* Version:   f4c6eca0a95ab0e05d7982c36ce801c1cf08c1c6
* Client OS: iOS 9 Simulator
* Server:    NA

**Comment by snej** [comment]
This happens because unit tests are built with the Debug configuration, so ForestDB is compiled with no optimizations, which makes it very slow compared to SQLite. This is expected.
