### ISSUE TITLE
Two Extras folder in 1.3 iOS binary zip file

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#1312]
There are 2 Extras folder in 1.3 iOS binary file. See the attached photo.

![extras](https://cloud.githubusercontent.com/assets/801454/16244385/8f2c7efa-37b0-11e6-8f83-e76494b21660.png)

In additional to 1.2 binary file, 1.3 iOS and Mac needs to copy OpenIDConnectUI into the Extras folder. Please note that Mac binary zip file doesn't have Extras folder before.

**Comment by pasin** [comment]
@michaelkwok is this done?

**Comment by michaelkwok** [comment]
@pasin It's all done.  Can you verify?

**Comment by pasin** [comment]
@snej Do I understand correctly that OpenIDConnectUI is not applicable for tvOS?

**Comment by snej** [comment]
I'm not sure. tvOS uses UIKit but some things behave differently. We'd have to test out OpenIDConnectUI in a tvOS app to make sure. It's probably best to not promise tvOS compatibility in 1.3.

**Comment by pasin** [comment]
I think the UI between iOS and tvOS are not the same. We don't include the extra folder in 1.2 as well. I'm closing the ticket now.
