### ISSUE TITLE
Add unit test for opening 1.3 databases from Android/.NET

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#1314]
Reference:
https://github.com/couchbase/couchbase-lite-java-core/issues/1283
https://github.com/couchbase/couchbase-lite-net/issues/684

**Comment by snej** [comment]
Hideki just pointed out that we actually do test this, since we have canned database files created on various platforms by 1.2. What we're missing is tests for opening databases from version _1.3_ on other platforms.

**Comment by pasin** [comment]
@hideki and @borrrden 

iOS 1.3.0 database files are here: 
https://github.com/couchbase/couchbase-lite-ios/tree/feature/issue_1314/TestData/replacedb/ios130
https://github.com/couchbase/couchbase-lite-ios/tree/feature/issue_1314/TestData/replacedb/ios130-forestdb

**Comment by pasin** [comment]
@hideki and @borrrden Could you please provide your platform database files?
