### ISSUE TITLE
Podspec doesn't support building for tvOS

### ISSUE THREAD

**Issue by bobbelkl** [couchbase/couchbase-lite-ios#1315]
Hi, 
I'm trying to use couchbase lite in my tvos app.
But there is no tvos target in the podspec-file, nor is there a CLB tvos target in the xcode project.

--------
* Version:   1.2.1
* Client OS: tvos 9.2

**Comment by pasin** [comment]
We do not have podspec updated for tvOS yet. tvOS shares the target scheme with the iOS platform. To build the binary for tvOS, with the couchbase-lite-ios project open in XCode, select `Continuous iOS` scheme with `Generic tvOS Device`, then click Product > Archive.

**Comment by pasin** [comment]
Since 1.3.0, tvOS has its own podspec: https://cocoapods.org/pods/couchbase-lite-tvos.
