### ISSUE TITLE
Missing Headers in iOS 1.3.0 Distribution

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-ios#1317]
http://latestbuilds.hq.couchbase.com/couchbase-lite-ios/1.3.0/macosx/1.3.0-24/couchbase-lite-macosx-enterprise_1.3.0-24.zip

<img width="335" alt="screenshot 2016-06-24 15 00 22" src="https://cloud.githubusercontent.com/assets/1365736/16351746/cf36bb50-3a1c-11e6-9c77-2906f4269083.png">

**Comment by pasin** [comment]
Close as not a bug.
