### ISSUE TITLE
Add instructions on how to build Couchbase Lite iOS with SQLCipher support

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-ios#1318]
To reproduce:

* Build latest couchbase lite from master branch
* Copy framework to ToDoLite
* Enable encryption using:

```
- (CBLDatabase *)databaseForName:(NSString *)name {
    NSString *dbName = [NSString stringWithFormat:@"db%@", [[name MD5] lowercaseString]];

    CBLDatabaseOptions *option = [[CBLDatabaseOptions alloc] init];
    option.create = YES;
    option.storageType = kStorageType;
    option.encryptionKey = @"encryptme";   <---- added this
```

* Getting crash: https://gist.github.com/tleyden/558de0ec7e8579e0a9d49bdcc1ec6417 and warning: `2016-06-24 15:34:13.843 ToDoLite[1066:527769] WARNING: CBL_SQLiteStorage: encryption not available (app not built with SQLCipher) {at -[CBL_SQLiteStorage decryptWithKey:error:]:248}`

Are there any instructions to build couchbase lite or todolite to enable encryption?

**Comment by brendand** [comment]
Right here:

[https://github.com/couchbaselabs/couchbase-lite-libsqlcipher](https://github.com/couchbaselabs/couchbase-lite-libsqlcipher)

I use SQLCipher in my app.

**Comment by manish-mobiuso** [comment]
I am still facing this issue of the `(app not built with SQLCipher) {at -[CBL_SQLiteStorage decryptWithKey:error:]:248}`, Anyone else facing this issue too?

Using the **Carthage** to build Couchbase framework. And still no instruction for the how to build project with Couchbase Lite **iOS** with **SQLCipher** support.

**Comment by manish-mobiuso** [comment]
Filed a new issue #1555
