### ISSUE TITLE
Retry timers should fire immediately when network comes online

### ISSUE THREAD

**Issue by pradipvaghasiya** [couchbase/couchbase-lite-ios#1326]
This issue is already discussed in forums at link https://forums.couchbase.com/t/couchbase-lite-1-2-cblreplication-pull-stuck-at-status-3-in-airport-mode/7818/3

Current OneShot Replication behavior
1. replication started and running when there is no internet 
2. after 8 retries, replication is now will retry after 256 seconds,
3. Internet is back 
4. Still replication is going to wait for 256 full seconds.

Expected: when there is change in reachability replication should immediately retry rather than waiting for long time.

---
- Version:   1.2.1
- Client OS: iOS 9
- Server:    Couchbase Server 4.0.0 + Sync Gateway 1.2.1  = Both Community edition.

**Comment by pasin** [comment]
I have looked into the current behavior of CBL 1.4.1 regarding this. CBL 1.4.1 will go online immediately when the reachability detects that the internet is back. For the case that the internet is ON but the host is down, when the host is back online, the reachability will not get triggered which is expected so the retry will be done after a certain interval.
