### ISSUE TITLE
Scope cookie storage by database, not by replication

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1334]
Currently every replication has its own cookie store. So if you have a push and a pull replication to the same server, each has independent cookie storage. (This came about as a side effect of using the replicator's checkpoint key as the ID of the cookie store.) 

It would make more sense to make the cookie store per-_database_, so all replications involving the same db would share cookies.

This allows us to put the new "clear stored credentials" method on Database, not Replication, which seems clearer. In the future we'll also be able to move the cookie accessor methods there.

**Comment by snej** [comment]
- [ ] Add a private `cookieStorage` property on CBLDatabase that returns a single instance, lazily initialized. The ivar could be weak, as long as the store is saved before the last strong reference goes away.
- [ ] This should only be called on the background CBLDatabase (the one the CBLReplicator uses), to avoid having to keep multiple instances in sync across multiple threads.
- [ ] The state should be saved to a single database info key with a hardcoded name.
- [ ] On first access, it should look for cookie state in the old location and coalesce it.
- [ ] On first save, it should delete the state from the old location.
- [ ] CBLReplication can be simplified because it won't need to wait to access the cookie store till its `_bg_Replicator` is created — instead it can access the cookie store at any time by running a block on the background thread and getting the bg database's cookieStorage property.

**Comment by pasin** [comment]
@snej From the first 2 bullet points, instead of each database object (of the same name) has its own cookie store object, would it be easier to have one single shared cookie storage kept in the CBL_Shared?

Note that current cookie store loads the cookies into the memory during the initialization and keeps maintain the memory data. If each database (of the same name) has its own cookie store object, we need to change the cookie store.

**Comment by snej** [comment]
Yes, I was thinking that it could be a shared per-database-file object kept by CBL_Shared. Its API would need to be thread-safe, but IIRC it already is?

**Comment by pasin** [comment]
Yes, the cookie storage is thread safe.
