### ISSUE TITLE
LinkMap file in Mac OS release should not be there

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1341]
The [Mac OS release archive](http://latestbuilds.hq.couchbase.com/couchbase-lite-ios/1.3.0/macosx/1.3.0-37/) contains a file `couchbaselite-linkmap-normal-x86_64.txt`. This is **not** part of the release and should not be in the archive.

(The file is generated as a way to compute the code sizes of classes and functions. I've used it in the past as part of optimizations. But it's not useful to developers.)

**Comment by michaelkwok** [comment]
Do you need me to remove it from the build?  Or is it something you like to change in the xcode project to not generate it?

**Comment by snej** [comment]
I want to keep the setting that generates it, because it's sometimes useful. But it should not be copied into the build archive.

**Comment by pasin** [comment]
I think we will just not copy the file into the zip file.

**Comment by michaelkwok** [comment]
We actually copied into zip the entire Frameworks directory, which has the LinkMap.  I have to removed the LinkMap in the release package.  It's still gets generated as part of the build.
