### ISSUE TITLE
Carthage builds for macOS fail, because SQLCipher isn't provided

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1344]
Carthage won't build CBL for Mac, because
- Carthage insists on building all shared schemes that build dynamic libs/frameworks (https://github.com/Carthage/Carthage/issues/1209)
- The "CBL Mac+SQLCipher" target won't build without manual assistance — you have to download the libSQLCipher.a binary externally and copy it into the source tree
- We can't get rid of that target from all shared schemes, because the Jenkins CI build relies on the "CI Mac" scheme to build all the Mac binaries.

Workaround for now is to install the SQLCipher library, as described in `Carthage/Checkouts/couchbase-lite-ios/vendor/SQLCipher/README.md`. After that, it should build.

In the long run we need to coordinate with @michaelkwok to update the Jenkins build script to use something other than a shared scheme to build the targets.

**Comment by snej** [comment]
Another option is to add a build phase that runs a script to download libSQLCipher.a, but I'm leery of hiding downloads inside a build script (like -cough- Realm -cough-)

**Comment by snej** [comment]
* We can't do anything about the first item above, because we don't control Carthage.
* We don't know what to do about no. 2 because it involves a big binary blob.
* So no. 3 seems like the one we can change — could we change our Jenkins builds to not be dependent on shared schemes? If so, we could remove the scheme that builds with SQLCipher.

**Comment by snej** [comment]
@michaelkwok: Would it be feasible for us to remove the shared scheme for Mac+SQLCipher builds? Can Jenkins work with the auto-created scheme, or maybe just build the target directly without specifying a scheme?

**Comment by djpongh** [comment]
According to @michaelkwok, the feature was added post 1.2.0.

**Comment by skela** [comment]
This is still not working, over a year later...

	skela@skelmac:~/Desktop/cli$ carthage update --platform macos
	*** Fetching couchbase-lite-ios
	*** Checking out couchbase-lite-ios at "c8d007fd5cea76b881f888e793cd5c2f04355709"
	*** xcodebuild output can be found in /var/folders/l_/x1vl9rsj4nbg_hwb_xgtn0l40000gn/T/carthage-xcodebuild.QEFTUV.log
	*** Building scheme "CBL Mac" in CouchbaseLite.xcodeproj
	*** Building scheme "CI MacOS" in CouchbaseLite.xcodeproj
	Build Failed
		Task failed with exit code 65:
		/usr/bin/xcrun xcodebuild -project /Users/skela/Desktop/cli/Carthage/Checkouts/couchbase-lite-ios/CouchbaseLite.xcodeproj -scheme CI\ MacOS -configuration Release -derivedDataPath /Users/skela/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0_9A235/couchbase-lite-ios/c8d007fd5cea76b881f888e793cd5c2f04355709 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/skela/Desktop/cli/Carthage/Checkouts/couchbase-lite-ios)

	This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/l_/x1vl9rsj4nbg_hwb_xgtn0l40000gn/T/carthage-xcodebuild.QEFTUV.log
	skela@skelmac:~/Desktop/cli$ xcode-select -s /Applications/Xcode.app/
	xcode-select: error: --switch must be run as root (e.g. `sudo xcode-select --switch <xcode_folder_path>`).
	skela@skelmac:~/Desktop/cli$ xcode-select -s /Applications/Xcode.app
	xcode-select: error: --switch must be run as root (e.g. `sudo xcode-select --switch <xcode_folder_path>`).
	skela@skelmac:~/Desktop/cli$ sudo xcode-select -s /Applications/Xcode.app
	Password:
	skela@skelmac:~/Desktop/cli$ carthage update --platform macos
	*** Fetching couchbase-lite-ios
	*** Checking out couchbase-lite-ios at "c8d007fd5cea76b881f888e793cd5c2f04355709"
	*** xcodebuild output can be found in /var/folders/l_/x1vl9rsj4nbg_hwb_xgtn0l40000gn/T/carthage-xcodebuild.Idrn29.log
	*** Building scheme "CI MacOS" in CouchbaseLite.xcodeproj
	Build Failed
		Task failed with exit code 65:
		/usr/bin/xcrun xcodebuild -project /Users/skela/Desktop/cli/Carthage/Checkouts/couchbase-lite-ios/CouchbaseLite.xcodeproj -scheme CI\ MacOS -configuration Release -derivedDataPath /Users/skela/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0_9A235/couchbase-lite-ios/c8d007fd5cea76b881f888e793cd5c2f04355709 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/skela/Desktop/cli/Carthage/Checkouts/couchbase-lite-ios)

	This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/l_/x1vl9rsj4nbg_hwb_xgtn0l40000gn/T/carthage-xcodebuild.Idrn29.log
	skela@skelmac:~/Desktop/cli$ subl /var/folders/l_/x1vl9rsj4nbg_hwb_xgtn0l40000gn/T/carthage-xcodebuild.Idrn29.log
	skela@skelmac:~/Desktop/cli$ tail /var/folders/l_/x1vl9rsj4nbg_hwb_xgtn0l40000gn/T/carthage-xcodebuild.Idrn29.log
	    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -L/Users/skela/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0_9A235/couchbase-lite-ios/c8d007fd5cea76b881f888e793cd5c2f04355709/Build/Products/Release-sqlcipher -L/Users/skela/Desktop/cli/Carthage/Checkouts/couchbase-lite-ios/vendor/SQLCipher/libs/osx -L/Users/skela/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0_9A235/couchbase-lite-ios/c8d007fd5cea76b881f888e793cd5c2f04355709/Build/Products/Release -F/Users/skela/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0_9A235/couchbase-lite-ios/c8d007fd5cea76b881f888e793cd5c2f04355709/Build/Products/Release-sqlcipher -filelist /Users/skela/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0_9A235/couchbase-lite-ios/c8d007fd5cea76b881f888e793cd5c2f04355709/Build/Intermediates.noindex/CouchbaseLite.build/Release/CBL\ Mac+SQLCipher.build/Objects-normal/x86_64/CouchbaseLite.LinkFileList -exported_symbols_list Source/CouchbaseLite.exp -install_name @rpath/CouchbaseLite.framework/Versions/A/CouchbaseLite -mmacosx-version-min=10.9 -Xlinker -object_path_lto -Xlinker /Users/skela/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0_9A235/couchbase-lite-ios/c8d007fd5cea76b881f888e793cd5c2f04355709/Build/Intermediates.noindex/CouchbaseLite.build/Release/CBL\ Mac+SQLCipher.build/Objects-normal/x86_64/CouchbaseLite_lto.o -Xlinker -final_output -Xlinker /Library/Frameworks/CouchbaseLite.framework/Versions/A/CouchbaseLite -fobjc-arc -fobjc-link-runtime -ObjC -lCouchbaseLite -lsqlcipher -lc++ -lz -framework CoreServices -framework Foundation -framework Security -framework SystemConfiguration -single_module -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/skela/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0_9A235/couchbase-lite-ios/c8d007fd5cea76b881f888e793cd5c2f04355709/Build/Intermediates.noindex/CouchbaseLite.build/Release/CBL\ Mac+SQLCipher.build/Objects-normal/x86_64/CouchbaseLite_dependency_info.dat -o /Users/skela/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0_9A235/couchbase-lite-ios/c8d007fd5cea76b881f888e793cd5c2f04355709/Build/Products/Release-sqlcipher/CouchbaseLite.framework/Versions/A/CouchbaseLite
	ld: library not found for -lsqlcipher
	clang: error: linker command failed with exit code 1 (use -v to see invocation)

	** BUILD FAILED **


	The following build commands failed:
		Ld /Users/skela/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0_9A235/couchbase-lite-ios/c8d007fd5cea76b881f888e793cd5c2f04355709/Build/Products/Release-sqlcipher/CouchbaseLite.framework/Versions/A/CouchbaseLite normal x86_64
	(1 failure)

**Comment by pasin** [comment]
Sorry, we haven't fixed the issue. To build macOS, it's required to copy libSQLCipher library to a folder before it can build.

**Comment by pasin** [comment]
@skela do you need SQLCipher?

**Comment by skela** [comment]
I don't need SQLCipher no, how do i disable it?

**Comment by snej** [comment]
Remove the "CI-MacOS" scheme from the CouchbaseLite project. That scheme builds the "CBL Mac+SQLCipher" target, which is the one that requires SQLCipher to be installed. Then Carthage can build the "CBL Mac" scheme instead, which uses the regular SQLIte.

The crux of the problem is (quoting from above)
>Carthage insists on building all shared schemes that build dynamic libs/frameworks (https://github.com/Carthage/Carthage/issues/1209)

We use schemes for our automated builds, and Carthage sees those and builds them. If you look at the linked issue, you'll see that they basically refused to deal with the problem.

**Comment by pasin** [comment]
You could do the following as a workaround:

```
$carthage update --platform macOS --no-build
$rm "Carthage/Checkouts/couchbase-lite-ios/CouchbaseLite.xcodeproj/xcshareddata/xcschemes/CI MacOS.xcscheme"
carthage build --platform macOS
```

**Comment by skela** [comment]
Thanks, that workaround worked ! :)

**Comment by pasin** [comment]
We don't have plan to include SQLCipher in the repo. Please use the workaround above. Thanks and sorry for the inconvenience.
