### ISSUE TITLE
Database Encryption

### ISSUE THREAD

**Issue by marbetschar** [couchbase/couchbase-lite-ios#1346]
I've got an app using the latest stable Couchbase Lite iOS. The database is NOT encrypted right now, but we'd like to do so in the near future as we would allow the user to store a database backup in his iCloud and this backup should be encrypted.

Unfortunately the documentation over here https://github.com/couchbase/couchbase-lite-ios/wiki/Database-Encryption states, that an already existing database can't be encrypted afterwards.

Is this still true? And if so, how could we get an encrpyted database?

**Comment by brendand** [comment]
Check out this project on github: https://github.com/couchbaselabs/couchbase-lite-libsqlcipher

It's what I use to provide encryption support. I think those other docs are a bit outdated. In version 1.3 you can encrypt, decrypt, and change the key of an existing database. Couchbase did a great job with their implementation.

**Comment by marbetschar** [comment]
@brendand this sounds amazing!! Thank you very much!

**Comment by jamiltz** [comment]
Docs for db encryption are at http://developer.couchbase.com/documentation/mobile/1.2/develop/guides/couchbase-lite/native-api/database/index.html#database-encryption. Let us know in https://github.com/couchbaselabs/couchbase-mobile-portal if you face any issue related to docs. Thanks!

**Comment by snej** [comment]
The wiki page is somewhat out of date — I should probably just replace it with a link to the official docs.

As the new docs say, you can use the `changeEncryptionKey:` method to re-key an existing database. We recently found some issues with rekeying if there's more than one SQLite (or ForestDB) connection open on the database, so you should rekey the database _before_ creating any replications.

**Comment by marbetschar** [comment]
👍🏼 - 🎉
