### ISSUE TITLE
Deferred pulling of attachments problem

### ISSUE THREAD

**Issue by combinatorial** [couchbase/couchbase-lite-ios#1354]
---
- Version:   1.2.1
- Client OS: iOS 9.3
- Server:    Couchbase 4.0.0 community + sync gateway 1.2.1

I am seeing a problem with deferring download of attachments.

Here is the usage pattern that is causing problems...
- pull is configured to continuous, with downloadAttachments = YES on the initial device
- push some object with attachments (push is not continuous and only pushes specific document ids)
- on another device with a clean install sync with downloadAttachments = NO - all works as expected
- on the original device, push some changes to the original docs but don't change the attachments
- on another device (clean install) sync with downloadAttachments = NO At the point the documents are syncing every attachment is reported with a warning like this:

```
  WARNING: CBLRestPuller[xxx]: Revision {7FEE076A-A352-405C-92A6-16EB02660BC2 #42-2442fd344ce094b73d1f31e2021972e8} has invalid attachment metadata: {
object =     {
    "content_type" = "application/octet-stream";
    digest = "sha1-kKXJn9tODWUDIk9umfgdMdeZMDg=";
    length = 8075;
    revpos = 30;
    stub = 1;
};
thumnbail =     {
    "content_type" = "image/png";
    digest = "sha1-kCrJcgLO3UyZ79CFW/yinHJ2lcM=";
    length = 1928;
    revpos = 30;
    stub = 1;
};

```

If instead the device is run with a clean install and downloadAttachments = YES then it works.

**Comment by snej** [comment]
Sorry for the delay! This bug got lost in the shuffle and we're going through the backlog.
I am pretty sure this got addressed in the 1.3 release. Have you had a chance to update, and if so, is the problem still present?

**Comment by combinatorial** [comment]
I am sorry I have not had a chance yet. It's going to be October before we move to 1.3. iOS10 has been taking our focus the last month or so.

**Comment by combinatorial** [comment]
I have updated to 1.3.1 client and sync_gateway and we are still see this problem... 

    13:34:18.710‖ WARNING: Don't have original attachment for stub 'object' in {1C21E445-C87B-4869-8B32-15318E527C15 #16-02b6620a9e7236c2b1350166e2939203} (missing rev) {at __74-[CBLDatabase(Attachments) processAttachmentsForRevision:ancestry:status:]_block_invoke:412}
    13:34:18.710‖ WARNING: CBLRestPuller[xxx]: Revision {1C21E445-C87B-4869-8B32-15318E527C15 #16-02b6620a9e7236c2b1350166e2939203} has invalid attachment metadata: {
    object =     {
        "content_type" = "application/octet-stream";
        digest = "sha1-UZgN4++7Njsw9ZQm5APV6auWD3Q=";
        length = 2884;
        revpos = 15;
        stub = 1;
    };
    thumnbail =     {
        "content_type" = "image/png";
        digest = "sha1-sDAWQGG2NeeVEJvxeWzYM0UUsVs=";
        length = 19050;
        revpos = 16;
        stub = 1;
    };
    }

**Comment by combinatorial** [comment]
I think I have a clue as to the cause of this problem... it's at this line...

https://github.com/couchbase/couchbase-lite-ios/blob/66133e2ec76851ed16828f3b05476de0671ced3e/Source/CBLDatabase%2BAttachments.m#L386

`} else if ([attachInfo[@"stub"] isEqual: $true] && attachment->revpos < generation) {`

the comment gives a clue...

```
// "stub" on an incoming revision means the attachment is the same as in the parent.
// (Either that or the replicator just decided to defer downloading the attachment;
// that's why the 'if' above tests the revpos.)
```

The problem occurs when both the replicator is deferring downloading the attachments and `attachment->revpos < generation`

If I comment this whole if block out then my broken cases start working as I am deferring download of all attachments.

So, how to detect that this is the deferred download case, and therefore we won't have the parent revision of the attachment?

**Comment by pasin** [comment]
Do the warnings cause any functional error? I haven't looked into the implementation of this feature in detail, but I saw this [comment](https://github.com/couchbase/couchbase-lite-ios/blob/master/Unit-Tests/Replication_Tests.m#L1227-L1231) in the unit test. If that is the same case, you can ignore those warnings.

**Comment by combinatorial** [comment]
Yes it does cause a functional error... for a document that contains attachments that fail, it does not show up as a document in queries.

I think this is because `processAttachmentsForRevision` fails and this means that `_storage forceInsert` is not called. (CBLDatabase+Insertion.m Line 203)

**Comment by combinatorial** [comment]
I checked the three unit tests that test deferred downloads of attachments: 

* test20_LazyPullAttachments
* test21_LazyPullMissingAttachment
* test22_NonDownloadedAttachments

None of them trigger the warning and so do not test for this error case. And that is because in all 3 tests `attachment->revpos == generation` which is incorrectly being used as the trigger to determine that we are not downloading attachments. It "works" in these case, but doesn't in the case that the attachment is in a parent revision.
