### ISSUE TITLE
Database_Tests.test26_DocumentExpiry is out of memory on device

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#1358]
Sometimes SQLite passes but ForestDB always fails as out of memory.

I think we may need to reduce the number of docs creating in a transaction from 10k to 1k for device friendly testing?

--------
* Version:   VERSION
* Client OS: NAME_AND_VERSION
* Server:    NAME_AND_VERSION

**Comment by snej** [comment]
Should take a look at where the memory's allocated — I think it must be in ForestDB itself.

**Comment by pasin** [comment]
After turning the Address Sanitizer OFF, the test runs a lot faster (~5x) and passes as expected.
