### ISSUE TITLE
Querying and Indexing needs to be faster

### ISSUE THREAD

**Issue by skela** [couchbase/couchbase-lite-ios#1360]
I'm struggling a bit with the performance of this setup. There is around 60,000 documents, and I'm doing most of the
querying in views that operate with a document id prefix. An example of one of these document ids is `projects.1|xyzfg` or `cards.tasks.3._18h37aerk1o_js_sDcQM|c6dc36ceadc34170ce477e0cb77215a114c5634c44e6eef1f1b81affc632bc15` , where anything before the `|` symbol is considered to be the groupId or prefix. So first time I try to query any of my views, it will take around 20 seconds to finish on my iPhone 6+.
Subsequent querying is faster (4-5 seconds), but still not as fast I would expect (less than 1 second).

It's possible that once https://github.com/couchbase/couchbase-lite-ios/issues/1240 is addressed, this will no longer be an issue in my current setup. But making the querying / indexing faster is likely to be a good idea anyway, because at present its not fast enough. We used to use Dropbox datastores for our data, and the underlying tech is the same (sqlite), and we had pretty much instant queries for the same data.

At present this is what we do, we create 1 view per "table", so all the docs with the id prefix of `cards.tasks.3._18h37aerk1o_js_sDcQM` are considered to belong to the same "table".

Mapping function - Used to create 1 view per id prefix:

	func idMapBlock(groupId:String) -> (CBLMapBlock, String)
	{
		let version = "1"
		return ({ (doc, emit) in
				if let id = doc["_id"] as? String
				{
						if id.hasPrefix(groupId)
						{
								emit("_id", doc["_id"])
						}
				}}, version)
	}

After opening the database I create the views:

	func setupMaps(db:CBLDatabase)
	{
			createIdMaps(db,"acc",["projects","settings","companies","categories","disciplines","groups","users"])
			createIdMaps(db,"forms",["layouts","rules","data"])
			createIdMaps(db,"files",["annotations","bubbles","comments","files","mappings","shapes"])
			createIdMaps(db,"cards",["statuses"])
			
			if let pid = projectId
			{
					createIdMaps(db,"acc",["project_features","settings"],pid)
					createIdMaps(db,"log",["activity"],pid)
					createIdMaps(db,"cards",["tasks"],pid)
					createIdMaps(db,"cards",["snags","media","comments"],pid)
					createIdMaps(db,"docs",["docs","comments"],pid)
					createIdMaps(db,"files",["docs"],pid)
			}
	}

	func createIdMaps(db:CBLDatabase,_ storeId:String,_ tableIds:[String],_ pid:String?=nil)
	{
        for tableId in tableIds
        {
            let groupId = CBTable.groupIdForTable(tableId,storeId:storeId,accountId:accountId,projectId:pid)
            let view = db.viewNamed(groupId)
            let block = idMapBlock(groupId)
            view.setMapBlock(block.0, version:block.1)
				}
	}

--------
* Version:   1.2.1
* Client OS: iOS 9 / iOS 10

**Comment by snej** [comment]
There are a couple of problems with what you're doing.

First, it sounds like you want to enumerate documents whose docID has a particular prefix. You don't need a view at all for this. Just use an all-docs query with a key range, something like

```swift
var q = db.createAllDocsQuery()
q.startKey = groupID + "|"
q.endKey = groupID + "}" // '}' is the character after '|' in ASCII order
q.inclusiveEnd = false
```

Second, what you're doing in general in your code above is extracting some value X from each document (the prefix of the `_id`), then querying for docs that have a specific value of X. But you're doing this by _creating a separate view for each value of X_ and emitting the docs that match. That's the wrong approach. Instead you create _a single view_ that handles all documents and emits X as the key. Then you can query that one view with `key = X` to find the results.

**Comment by snej** [comment]
Also, in your `emit` call:
```swift
                            emit("_id", doc["_id"])
```
You never need to emit the docID. It's already implicitly added to the index row. Note that the `CBLQueryRow` class already has a `documentID` property. Just emitting `nil` as the value instead will make your index significantly smaller. (Although of course in this particular case you don't actually need an index, as I said in point 1 above.)

**Comment by skela** [comment]
@snej, thanks so much for this, I'll give it a go tomorrow, but just to clarify:

If I do this, each time I need to return all the docs with a particular groupId (prefix)

	var q = db.createAllDocsQuery()
	q.startKey = groupID + "|"
	q.endKey = groupID + "}" // '}' is the character after '|' in ASCII order
	q.inclusiveEnd = false

Is that going to be faster than having a bunch of views, and doing it via the view route?

**Comment by snej** [comment]
Much faster, because there's no index to generate/update. It's just iterating over the database's main key⟶value map.

**Comment by skela** [comment]
Thanks, that's basically 10 times faster than my view approach. Feel free to close this unless you think there's still room for improvement.

**Comment by snej** [comment]
Cool! I'll close this.
