### ISSUE TITLE
Support request payload compression for Apache CouchDB

### ISSUE THREAD

**Issue by jo** [couchbase/couchbase-lite-ios#1361]
In 7d54535f08d2d9e6f47adae5000873d08d4187a7 CBL GZip-compresses HTTP request bodies, when server supports it.

Now given that Apache CouchDB also [supports compression of request bodies since 1.6.0.](https://github.com/apache/couchdb/commit/4d893387#diff-ae2b6645885f914be9aa0fbae751fa32R558) it would be so good if CBL would also support GZipped payloads with CouchDB.

As I understand this is currently done [only in case CBL talks to Couchbase Sync Gateway](https://github.com/couchbase/couchbase-lite-ios/commit/7d54535f08d2d9e6f47adae5000873d08d4187a7#diff-f1580678a481f417b7268cd7d2b5d403R619).

**Comment by jo** [comment]
Related iOS issue: https://github.com/couchbase/couchbase-lite-android/issues/943

**Comment by jayahariv** [comment]
Closing 1.x issue!
