### ISSUE TITLE
CBL_VERSION_STRING not 1.2.2 in Branch 1.2.2

### ISSUE THREAD

**Issue by Chavenay** [couchbase/couchbase-lite-ios#1364]
I think someone forgot to update CBL_VERSION_STRING in branch version 1.2.2. 
--------
* Version:   1.2.2
* Client OS: MACOS 10.11.5
* Server:    couchDB 1.7

**Comment by snej** [comment]
1.2.2 isn't an official release, just some patches added to 1.2.1 … you're best off moving to 1.3 now.

**Comment by Chavenay** [comment]
Where is 1.3 ?

**Comment by snej** [comment]
https://github.com/couchbase/couchbase-lite-ios/releases/tag/1.3 (developer preview)
