### ISSUE TITLE
Non-continuous push replication gets stuck in kCBLReplicationIdle status

### ISSUE THREAD

**Issue by davidquon** [couchbase/couchbase-lite-ios#1365]
Using the CBL branch `release/1.2.2` on iOS 9.3.  For replication there is a `replicate` method that gets called during initial login as well as periodically from a timer and when the app is foregrounded.  The replications are one shot replications and not continuous.

```
(void)replicate
{
    [self.pullReplication start];
    [self.pushReplication start];
}
```

Upon initial login the databases for the push and pull replication don't exist yet and are created as part of the `self.pullReplication` and `self.pushReplication` method calls similar to below.

```
- (CBLReplication *)pullReplication
{
    if (!_pullReplication)
    {

        _pullReplication = [self.database createPullReplication:self.pullReplicationURL];

    }
    return _pullReplication;
}

- (CBLReplication *)pushReplication
{
    if (!_pushReplication)
    {
        _pushReplication = [self.database createPushReplication:self.pushReplicationURL];
    }
    return _pushReplication;
}
```

During the initial login the databases are created properly and the push and pull replication occur successfully verified by watching the logging with `-Log YES`, `-LogSync YES`, and `-LogSyncVerbose YES`.  The next time `replicate` is called after the initial login the logging only shows the pull replication and not the push replication.

After the initial login and during the periodic replication the pull replication `status` is `kCBLReplicationStopped` and the push replication `status` is `kCBLReplicationIdle`.  If the app is stopped and re-started both pull and push replication statuses are `kCBLReplicationStopped` and both push and pull replications again replicate correctly.

It seems that there is some sort of race condition during the initial login which causes the push replication to get stuck in the `kCBLReplicationIdle` status causing the `[self.pushReplication start]` not to work.

Couchbase Mobile Google Group Discussion Reference:
https://groups.google.com/d/msg/mobile-couchbase/Mx81Hiv-Wis/SVDhCFk6BgAJ

---
- Version:   `release/1.2.2`
- Client OS: `iOS 9.3`
- Server:    `CouchDB/1.6.1 (Erlang OTP/17)`

**Comment by davidquon** [comment]
I'll create private gists with the logging described above enabled for the different use cases and email the links to @snej for reference.

**Comment by davidquon** [comment]
Email sent to @snej with links to logging gists.  Let me know if there is anything else I can do to help.  Thanks.

**Comment by pasin** [comment]
@snej have you looked into the gist?

**Comment by pasin** [comment]
@davidquon Can you resend the gist to me (pasin@couchbase.com)?

**Comment by davidquon** [comment]
Email sent @pasin.  Thanks!

**Comment by pasin** [comment]
@davidquon I just recalled one fix (https://github.com/couchbase/couchbase-lite-ios/commit/f653593bd06a03dd08a094d89a5742127cae4465) that we made in 1.3.1. There is an issue that sometime the replication change notification from the background replicator doesn't post correctly to the foreground. We observed a behavior that a push replicator keeps being in IDLE state which looks very much like what you are seeing in this issue. Please try to use 1.3.1 and see if you are still encountering the issue. Thanks!
