### ISSUE TITLE
Pull Replication Not Updating

### ISSUE THREAD

**Issue by grawson** [couchbase/couchbase-lite-ios#1373]
Gist References:
MainViewController: https://gist.github.com/grawson/55d2014289485f0e55414f8fa4f5fca7
AppDelegate: https://gist.github.com/grawson/0eb0be613aca3e7ea5b8a961672fec71

We are trying to setup replication between a CouchDB server and an iOS app. We begin in the appDelegate file by initializing the database and the replication. We do not set up a continuous pull. Instead, in the next file, we set a timer to check for pull updates to the replication every 10 seconds. We also register an observer to NSNotificationCenter to print out data every time there is a data change on the remote database. 

When starting the app, the remote database is initially replicated to the store on the phone. However, when we change data in the database, the local replication does not notice any data changes. Further, if we change the pull to continuous, the database registers a change multiple times per second, even when the data on the database is not being changed.

Based on the code in the screenshots, is there a bug present in the pull replication process? 

--------
* Version:   VERSION
* Client OS: NAME_AND_VERSION
* Server:    NAME_AND_VERSION

**Comment by snej** [comment]
You're calling `restart` on the replication. This doesn't do what you're expecting it to do. From the header comment:
```objc
/** Restarts a running replication.
    Has no effect if the replication is not running. */
```
If you want to start the replication again, call `start` instead.

However, running replications over and over on a timer is almost always a bad idea. It generates extra network traffic and server activity, and increases the latency of receiving changes.

> if we change the pull to continuous, the database registers a change multiple times per second, even when the data on the database is not being changed.

I think you mean the _replication_ registers a change, since that's what your code is observing. You will see a number of changes as the replication status changes, but once the replicator catches up its status will change to Idle and it won't notify you any more until the source database changes. If that's not what you're seeing, can you show the notifications you're receiving?

**Comment by grawson** [comment]
I see, thanks for the help!

I have removed the timer and set the pull to continuous. Changes to the the database are now being noticed by the replication. I just have two quick questions:

1. Since a timer is not the way to go, what is the best practice to make a custom (and not very often) schedule for the replication to check for changes to the database?

2. I have registered a kCBLReplicationChangeNotification in NSNotificationCenter, and there are multiple calls to its target method per second. It seems like the pull is continuously active even when the database is not changed. Is there a way to call the target method only when data has been changed on the database? I have included a log below which shows the pull status, timestamp, and data changes. There also seem to be a few warnings in there:


REPLICATION CHANGE NOTIFICATION RECIEVED:
July 21, 2016 at 12:27:41 PM EDT
Pull Status: Active
Data: Adherence, Age, Antiplatelet, Apnea, Arteries

REPLICATION CHANGE NOTIFICATION RECIEVED:
July 21, 2016 at 12:27:41 PM EDT
Pull Status: Active
Data: Adherence, Age, Antiplatelet, Apnea, Arteries

REPLICATION CHANGE NOTIFICATION RECIEVED:
July 21, 2016 at 12:27:41 PM EDT
Pull Status: Active
Data: Adherence, Age, Antiplatelet, Apnea, Arteries

REPLICATION CHANGE NOTIFICATION RECIEVED:
July 21, 2016 at 12:27:41 PM EDT
Pull Status: Active
Data: Age, Antiplatelet, Apnea, Arteries

REPLICATION CHANGE NOTIFICATION RECIEVED:
July 21, 2016 at 12:27:41 PM EDT
Pull Status: Active
Data: Age, Antiplatelet, Apnea, Arteries

REPLICATION CHANGE NOTIFICATION RECIEVED:
July 21, 2016 at 12:27:41 PM EDT
Pull Status: Active
Data: Age, Antiplatelet, Apnea, Arteries

2016-07-21 12:27:41.690 Corrie[1577:401566] WARNING: Truncated changes feed
2016-07-21 12:27:41.692 Corrie[1577:401566] WARNING: CBLSocketChangeTracker[0x12ed93a10 dev_data]: Longpoll connection closed (by proxy?) after 0.1 sec
REPLICATION CHANGE NOTIFICATION RECIEVED:
July 21, 2016 at 12:27:42 PM EDT
Pull Status: Idle
Data: Age, Antiplatelet, Apnea, Arteries


Thanks for the help!

**Comment by snej** [comment]
> what is the best practice to make a custom (and not very often) schedule for the replication to check for changes to the database?

You can use a timer. Just call `start` on the replication, not `restart`. Polling is reasonable as long as it's not too often — 10 seconds as in your example will probably cause a lot more server load than a continuous replication would. But if you only poll every few minutes, that's fine.

>It seems like the pull is continuously active even when the database is not changed. 

The notification is posted whenever the properties of the replication change, including the total number of docs to be pulled. It's intended to be used for communicating progress to the user, or for detecting when the replication is done.

>Is there a way to call the target method only when data has been changed on the database?

Observe database-changed notifications instead. You can tell whether a particular change comes from a pull replication by looking at the DatabaseChange object's `source` property, which will be the URL that the revision was received from.

**Comment by grawson** [comment]
Everything is working now! Thanks for all the help!
