### ISSUE TITLE
Invalid libsqlcipher.a in couchbase-lite-tvos-community_1.3.0-57.zip

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#1386]
couchbase-lite-tvos has the wrong libsqlcipher.a. From the file size, I believe the file is copied from couchbase-lite-libsqlcipher/iOS instead of tvOS.
--------
* Version:   1.3.0-57
* Client OS: tvOS
* Server:    NA

**Comment by pasin** [comment]
CC @sethrosetter

**Comment by hkodungallur** [comment]
This is fixed in build #61

**Comment by pasin** [comment]
Verified. The issue is fixed in build 61. @hkodungallur, thank you very much for your help.
