### ISSUE TITLE
Allow SQLite reads concurrently with writer

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1389]
The locking code I added to FMDatabase explicitly blocks readers while there is a writer. This matches the default behavior of SQLite, but I just noticed that when the WAL is enabled, SQLite does allow reads concurrently with writes. The readers will see a snapshot of the database from before the in-progress write transaction:

>Writers merely append new content to the end of the WAL file. Because writers do nothing that would interfere with the actions of readers, writers and readers can run at the same time. However, since there is only one WAL file, there can only be one writer at a time. [*](https://www.sqlite.org/wal.html)

Changing the FMDatabase locking accordingly would be a big performance/availability win. For example, currently the database is entirely unavailable while a view index is being updated (any reads will block.) With this change, reads will work normally during indexing. The same goes for large inserts that might happen during a pull replication.

**Comment by snej** [comment]
FYI, the C# implementation of CBL already supports this. Not sure about Java.

**Comment by pasin** [comment]
Java has implemented one write and mutiple read connection pool.

**Comment by snej** [comment]
@hideki said on Slack:

>Android API > 20, We use connection pool approach which feature is provided by SQLiteDatabase.java written by originally Google. It creates maximum 4 connection, 1 writer and 3 or 4 reader. With this, CBL Android/Java can read data during other connection is writting. Before 20, CBL Java/Android SQLite is alway one connection.

**Comment by pasin** [comment]
@hideki I think we always use multiple connections now regardless of API level.

**Comment by snej** [comment]
Enabling concurrent connections made the ConcurrentWrites unit test (which uses 2 writer and 2 reader threads) run 2.25x faster on my Mac!
