### ISSUE TITLE
iOS update 9.3.3 breaks continuous pull

### ISSUE THREAD

**Issue by zebra1024** [couchbase/couchbase-lite-ios#1391]
I recently upgraded an existing ionic/cordova app to 1.2.1. During testing my devices upgraded to iOS 9.3.3. After the update the continuous pull stopped working. The continuous push and one-time pull both work. The continuous pull works for Android devices. I tested on an iPhone with iOS 9.2.1 and it worked fine. I then upgraded to iOS 9.3.3 and it stopped working. If I downgrade to couchbase-lite-ios 1.1 it works again. I did not try 1.3 as I do not have a version of the Couchbase-Lite-PhoneGap-Plugin which supports 1.3.
--------
* Version:   1.2.1
* Client OS: iOS 9.3.3 (Cordova 6.2 using Couchbase-Lite-PhoneGap-Plugin 1.2.1)
* Server:    Sync Gateway  1.0.4

**Comment by pasin** [comment]
phonegap plugin 1.3.0 has been released last week. You could try that. Also if you still encountered the issue, could you please try to enable some logging as below:

```
[CBLManager enableLogging: @"Sync"];
[CBLManager enableLogging: @"SyncVerbose"];
```

**Comment by pasin** [comment]
I'm closing this issue now. @zebra1024, if you have any additional info, please let us know and we can reopen the issue. Thanks.
