### ISSUE TITLE
Getting a 404 when trying to cancel replication in 1.3.0-62

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-ios#1394]
Using version http://latestbuilds.hq.couchbase.com/couchbase-lite-ios/1.3.0/ios/1.3.0-62/

I'm trying to cancel a replication task via the REST api.  

As far as I can figure out from the [docs](http://docs.couchdb.org/en/stable/api/server/common.html#post--_replicate) the way to cancel a replication task is to POST to the `_replicate` endpoint with exactly the same parameters as were used to start the task, but adding a `cancel: true` parameter.  It works on android 1.3.0-45, and I'm sure it used to work on iOS (in 1.2.x).  But now I just get a `{status: 404, error: "not_found"}` returned.

**Comment by pasin** [comment]
cbl-ios returns 404 if the replicator is already stopped. It would be better to have cbl-android and ios implementation synced for this case. Meanwhile, if you have already stopped the replication, you can ignore this 404.

https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CBL_Router%2BHandlers.m#L414-L417

**Comment by pasin** [comment]
I think now it's an API question that we should return 404 or 200 for the case that the replication is already stopped. 

@snej what is your opinion on this?

**Comment by npomfret** [comment]
What I'm actually trying to do is test what happens when a session expires.  I do this by starting a replication process, then use the admin api to delete it's session.

From this point the client replication task goes into the stopped/404 state.  But from here I don't seem to be able to start a new one.  All new replication tasks I create immediately go into the same stopped/404 state.  Its as if I'm not allow 2 identical replication tasks that differ only in the session that was used to create them.

**Comment by pasin** [comment]
CBL iOS shares the same internal replicator object if 2 replicators have the same settings (e.g. URL, type (push/pull), docIds, and etc). Have you tried GET /_active_tasks? I think it may help getting the info about the state of the replicators that you need.

**Comment by npomfret** [comment]
GET /_active_tasks just shows each replicator in the stopped/401 state.

I guess my question really is: what happens to replication why a session expires or is deleted?  And how do I get replication started again?

**Comment by pasin** [comment]
The (continuous) replication can be stopped when there is a permanent error (such as authentication error due to SGW session cookie expires). What is the error you are seeing from the `_active_tasks` result?

> I guess my question really is: what happens to replication why a session expires or is deleted? And how do I get replication started again?
From the REST API, you can keep listening to the _active_tasks (maybe with feed=longpoll) and check if your replicator is stopped and then you can restart.

**Comment by jamiltz** [comment]
I've found that if invalid credentials are provided to `/_replicate` then the replication reports a 401 unauthorized in `/_active_tasks`, then stops and is removed from the list of replications.

If the credentials are valid then it starts and if the session expires later on (which can be done using the DELETE /db/_user/name/_session endpoint) then the replication also reports the 401 unauthorized, stops and is removed from `/_active_tasks`. There is no issue in my testing (see below). So we have to provide guidance on how to detect 401 unauthorized for applications using the REST API. I'll monitor this thread so we can add it to the docs as well.

> Note: Step 8 below is important. Without it, the pusher won't try to send any request to Sync Gateway because there is nothing to push. At this stage the replication is still reported as Idle until a change happens in the database, then it sends the requests, gets back 401 unauthorized etc. 

```
1. Start Sync Gateway with user in config file
{
  "databases": {
    "mydatabase": {
      "users": {
        "GUEST": {"disabled": true},
        "john": {"password": "pass", "admin_channels": ["a", "b"]}
      }
    }
  }
}
2. Start LiteServ
3. Create user session
curl -H 'Content-Type: application/json' -vX POST 'http://localhost:4985/mydatabase/_session' -d '{"name":"john", "password":"pass"}'
4. Create database on LiteServ
curl -H 'Content-Type: application/json' -vX PUT 'http://localhost:5984/mydatabase'
5. Create session
curl -H 'Content-Type: application/json' -vX POST 'http://localhost:4985/mydatabase/_session' -d '{"name":"john", "password":"pass"}'
6. Start replication
curl -H 'Content-Type: application/json' -vX POST 'http://localhost:5984/_replicate' \
                                            -d '{"source":"mydatabase","target":{"headers":{"Cookie":"SyncGatewaySession=bf460c58654e6bb32dcf0da6766b8d26b63db3ad; Path=/sync_gateway; Expires=2016-08-11T15:21:53.548902811+01:00"},"url":"http://localhost:4984/mydatabase"},"continuous":true}'
7. Delete user session on Sync Gateway
curl -H 'Content-Type: application/json' -vX DELETE 'http://localhost:4985/mydatabase/_user/john/_session'
8. Add docs to wake up the replication
curl -H 'Content-Type: application/json' -vX POST 'http://localhost:5984/mydatabase' -d '{}'
```

**Comment by npomfret** [comment]
Hi,  I've just upgraded to 1.3.0-68 any re-ran my experiment and things worked exactly as you described.  I'm pretty sure I've not done anything different, but now I can kill sessions and my app is able to start new replication tasks along side the broken/401 tasks... amazing - thank you.  So working on iOS at least.  Now for android...
