### ISSUE TITLE
Occasional 404 when trying to display new image attachment in 1.3.0-62

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-ios#1396]
Images fail to display from time to time in my app.  I've added an error handler to the image load and its reporting a 404.  It doesn't always happen, and happens on very new attachments only.  The code  tests the document first to make sure the attachment is present before attempting to load it.  And if I re-query for the attachment manually after I experience a 404 its always there. 

Is there a situation where a version of document which has a new attachment doesn't have that attachment synced yet?  Is there a way in the rest API to test if an attachment is available?

**Comment by npomfret** [comment]
In fact I have a situation where my documents image just won't load.  This is the doc:

![screen shot 2016-08-05 at 14 03 39](https://cloud.githubusercontent.com/assets/5489469/17437414/74a0d062-5b15-11e6-8152-bbc46022f454.png)

And my image loader fails with this error:

` failed to load slice image for doc 54c2ecff-3daa-423e-982b-819dc66a4b40 http://lite.couchbase./pc_dev_0_7f3b03b8-340d-4d41-80f9-d4ebec187216/08ce3201-1497-4a38-9e22-04d8026a1a76/slice Object {error: "The operation couldn’t be completed. (NSURLErrorDomain error 404.)"}`

If I load the image directly from the sync gateway, using the same users credentials, it works perfectly.

So it seems that the device has a document that has attachments.  But those attachments haven't syncd to the device.

I guess my questions are,

a) should this happen?  it is expected behaviour or a bug?
b) if it's expected behaviour, what's a good way to test for the presents of an attachment using the REST API?

**Comment by pasin** [comment]
I don't think this is an expected behavior.

> And if I re-query for the attachment manually after I experience a 404 its always there.
Do you mean after that the slice image can be loaded?

Do you happen to have or be able to recapture the log with Sync / SyncVerbose enabled when syncing the attachment that has the issue?

**Comment by npomfret** [comment]
Its difficult because its not easy to reproduce.  It only happens from time to time.

**Comment by npomfret** [comment]
I'm going to close this, think I may have found a potential cause in my code.  Will re-open if I can prove otherwise.
