### ISSUE TITLE
Ability to mark a document as not having history

### ISSUE THREAD

**Issue by skela** [couchbase/couchbase-lite-ios#1397]
Is there any way to mark a particular document as not having history ? I.e. that you are not interested in keeping revisions around for it, and that the latest revision of the document becomes the only revision ?

**Comment by pasin** [comment]
I don't think CBL has that feature. You may use local doc which is like key-value store but it will not get synced. Another option would be setting CBLDatabase.maxRevTreeDepth to 1. Anyway can you provide your use case?

**Comment by snej** [comment]
No, there isn't. History is necessary for replication, and to prevent different threads from overwriting each others' changes (MVCC).

**Comment by skela** [comment]
The use case is for a very select few of documents, that update very frequently, the latest is always the right one, and we don't ever need to look at the previous revisions. And we are finding that the massive amount of revisions for these documents that we don't need take a lot of time on the initial sync. 

I understand some history is necessary for replication, but I still think it would be useful for some usecases to limit the maxRevTreeDepth for a particular document (not for the whole database). You already have CBLDatabase.maxRevTreeDepth, so just extending this functionality to documents too.

**Comment by snej** [comment]
This should be a lot more efficient in 1.3 — both CBL and SG have been optimized to send the minimum necessary history during replication.

In the long run, in CBL 2.0 we're going to be tracking document history differently and the amount of metadata will be much less.
