### ISSUE TITLE
- 1009 Error in _active_tasks endpoint

### ISSUE THREAD

**Issue by jfspencer** [couchbase/couchbase-lite-ios#1398]
**Description**
I am running into an issue where the _active_tasks endpoint gets stuck after the device goes offline and back online.

I am using the active_tasks endpoint to keep track of what replications are active. when returning online I get the following response from _active_tasks. I query it multiple times after coming back online and the following is the consistent response. The actual sync progress in my tests is around 10% to 15% complete.

``` javascript
[{
"source": "https:\/\/****:*@.***.com:443\/******",
"status": "Processed 9432 \/ 9433 changes",
"task": "repl001",
"type": "Replication",
"progress": 100,
"error": [ - 1009, "The Internet connection appears to be offline."],
"x_active_requests": []
}]
```

**Include Steps To Reproduce** 
- start a non-continuous pull replication from CouchDB 1.6.1 to cbl 1.2.1
- after some progress enable airplane mode 
- disable airplane mode and monitor multiple requests to _active_tasks
- observe the above response from each request

**Include Actual vs. Expected**
Actual: _active_tasks is continually returning a stale state relating to an offline line event after the device has returned online.

Expected: The active tasks should return an idle response if the replication is canceled internally or a response that indicates replication has continued.

**Attempted Solutions**
Attempt: Create a native api that is called on the offline event to manually cancel any replications active on the syncing database. 
Result: found that no replications were listed in the db's replications array, no effect on _active_tasks

Attempt: create a native api that closes the manager and creates a new manager when the device comes back online
Result: did not have an effect on the _active_tasks response

---
- Version:   1.2.1
- Client OS: iOS 9.3 via Cordova 6.2.0(iOS 4.2.0)
- Server:    CouchDB 1.6.1

**Comment by pasin** [comment]
> start a non-continuous pull replication from CouchDB 1.6.1 to cbl 1.2.1

If using a non-continuous pull replication, I understand that the replication will be stopped (not continue) after the device is offline. I'm not sure why the status is not changed from offline to stopped.

**Comment by pasin** [comment]
I have tested this with the code from the current master (https://github.com/couchbase/couchbase-lite-ios/commit/d373b4e9f69df5db592e1d8c2808afbada52c386), but I couldn't reproduce this issue. After bringing the device online again, the replicator is stopped and the `_active_tasks` doesn't have stale offline/stopped replicator included. I'm closing this issue as cannot reproduce. Anyway sorry that I took so long to get into this issue.
