### ISSUE TITLE
CBL fails to create FTS view due to unknown tokenizer stemmer=ja

### ISSUE THREAD

**Issue by brendand** [couchbase/couchbase-lite-ios#1399]
When an FTS search index is created in an SQLite database, if there's no stemmer associated with the user's language, Couchbase fails to create the FTS index:

```
2016-08-11 00:43:09.135 Tap Forms 5[57747:3078615] Error calling sqlite3_step (1: unknown tokenizer) SQLITE_ERROR
2016-08-11 00:43:09.135 Tap Forms 5[57747:3078615] DB Query:         CREATE VIRTUAL TABLE IF NOT EXISTS fulltext             USING fts4(content, tokenize=unicodesn "stemmer=ja")
00:43:09.136| WARNING: Error initializing fts4 schema: SQLite[1, "unknown tokenizer"] {at -[CBL_SQLiteViewStorage createFullTextSchema]:175}
00:43:09.136| WARNING: CouchbaseLite: Failed to rebuild views (fullTextView): 501 {at -[CBL_SQLiteViewStorage updateIndexes:]:531}
00:43:09.136| WARNING: Failed to update view index: 501 {at -[CBLDatabase(Views) queryViewNamed:options:ifChangedSince:status:]:490}
2016-08-11 00:43:09.136 Tap Forms 5[57747:3078615] Error running its query: Error Domain=CBLHTTP Code=501 "unimplemented" UserInfo={NSLocalizedFailureReason=unimplemented, NSLocalizedDescription=unimplemented}
-
```

This is a problem because my customers are not able to search in their database due to this issue.

Is there a way to have a fallback stemmer if the language is not supported for stemming? At least they can still query the database then.

---
- Version:   1.3 GM
- Client OS: OSX 10.11
- Server:    n/a

**Comment by brendand** [comment]
I've worked around this problem by simply removing the stemmer command altogether from the code that creates the full text index. Although it would be better if there was official support for this. My customers don't like how the searching works now because it's not accurate. For example, If I search for "Officer", I don't want it to return "Office" like it's doing now.

**Comment by jayahariv** [comment]
Closing 1.x issue!
