### ISSUE TITLE
Request: CBLDatabase deleteView method should also deletes associated FTS index.

### ISSUE THREAD

**Issue by brendand** [couchbase/couchbase-lite-ios#1401]
When an FTS index is created, a stemmer is set on it. In order to clear or change the stemmer used in the FTS index, the FTS index needs to be dropped and re-created. It would be good to delete the FTS index whenever its corresponding CBLView is deleted. It can easily be re-created.

---
- Version:   1.3
- Client OS: OSX and iOS
- Server:    n/a

**Comment by brendand** [comment]
If this isn't possible, is there a way that I can re-create the FTS index? I need to rebuild the indexes on my customer's databases because they're getting wrong results from the search. I have a process that compacts the database already but if I could include recreating of the FTS index, then I could help them to correct this problem for existing databases.

**Comment by snej** [comment]
This is SQLite, right? Should be easy to fix.

**Comment by brendand** [comment]
Yes, this is SQLite. I've modified the CouchbaseLite code for now to leave out the stemmer when creating the FTS virtual table. That solved my problem for now.

This is all I did for now:

```
   NSString* sql = $sprintf(@"\
        CREATE VIRTUAL TABLE IF NOT EXISTS fulltext \
            USING fts4(content, tokenize=unicodesn %@);\
        CREATE INDEX IF NOT EXISTS  'maps_#_by_fulltext' ON 'maps_#'(fulltext_id); \
        CREATE TRIGGER IF NOT EXISTS 'del_maps_#_fulltext' \
            DELETE ON 'maps_#' WHEN old.fulltext_id not null BEGIN \
                DELETE FROM fulltext WHERE rowid=old.fulltext_id| END", stemmer);
```

I changed the very last line to this:

```
                DELETE FROM fulltext WHERE rowid=old.fulltext_id| END", @"");
```

So the stemmer value just is the empty string and leaves it out of the create statement.

**Comment by jayahariv** [comment]
Closing 1.x issue!
