### ISSUE TITLE
Query: skip and limit should be applied AFTER reducing/grouping.

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1402]
@borrrden noticed today that when CBL runs a reduced query it applies the `skip` and `limit` parameters to the initial view traversal before doing the grouping/reducing. This is wrong, or at least contrary to CouchDB.

**Comment by snej** [comment]
The ForestDB storage does this correctly (CBL_ForestDBQueryEnumerator.mm.) Haven't checked SQLite yet.

**Comment by snej** [comment]
SQLite storage is **incorrect** (-[CBLSQLiteViewStorage reducedQueryWithOptions:status:]).

**Comment by jayahariv** [comment]
Closing 1.x issue!
