### ISSUE TITLE
CBLSocketChangeTracker endless loop of JSON Parsing Errors

### ISSUE THREAD

**Issue by eliog** [couchbase/couchbase-lite-ios#1403]
On occasion I've noticed that a pull replication I start on a new database ends up failing and I get an endless loop of JSON parsing errors.

It doesn't happen all the time.  I try the replication on the same database/server and it works 90% of the time.  I've noticed that there's a higher probability of it happening if I suspend/resume the app while the replication is going.  It also seems like there's a less probability of it happing if I have all the logging turned on (but that's probably just Murphy's law).

The exact error i'm getting is:
```
2016-08-12 21:53:17.625 charm[644:249029] WARNING: JSON error parsing _changes feed: lexical error: invalid char in json text.
 {at -[CBLChangeTracker parseBytes:length:]:355}
2016-08-12 21:53:17.627 charm[644:249029] CBLSocketChangeTracker[0x14d714e60 charm]: Connection error #1, retrying in 2.0 sec: CBLHTTP[587, "JSON error parsing _changes feed: lexical error: invalid char in json text.
```

On the off chance that I am receiving invalid JSON (randomly) I added code to print out what's been read in CBLChangeTracker->parseBytes:

```
    NSMutableString *hex = [NSMutableString stringWithCapacity:(long)length];
    for(size_t i=0;i<length;i++) {
        [hex appendFormat:@"%02x", ((char*)bytes)[i]];
    }
    NSLog(@"read = %@", hex);
```

As far as I can tell, I see nothing wrong with the JSON.

Looking at the code it *seems* that after this failure, the _parser is never set to nil.  So, the next time the request is made the new data is sent to the old _parser which is still in the old state.

My log output is here: https://gist.github.com/eliog/98ff2f97e124a79baf1fe37c9619a795

You can see the replication start and when it gets to around line 300 the first error happens, from then on the error continues indefinitely.

--------
* Version:   1.3 and latest from master
* Client OS: IOS 9.3
* Server:    CouchDB 1.6.1

**Comment by eliog** [comment]
Looked at it some more today, and noticed that if I get a NSStreamEventError it also triggers the problem.

In CBLSocketChangeTracker it lands here:

```
        case NSStreamEventErrorOccurred:
            [self failedWithError: stream.streamError];
            break;
```

This seems to fix it, but you may prefer to set _parser to nil when the error is caught:
https://github.com/eliog/couchbase-lite-ios/commit/689ecba9eccbf49cf7daadd4a2bdde6c59bdf7b8

**Comment by snej** [comment]
You're right — the parser doesn't get cleared in some error conditions, so it'll fail during the next connection too. Thanks for the fix!
