### ISSUE TITLE
500 database error (error opening!: 23) when saving a new document in app pause state

### ISSUE THREAD

**Issue by HanzhiDou** [couchbase/couchbase-lite-ios#1405]
Hi,
- Version:   1.2.1 by Couchbase Lite Phonegap plugin
- Client OS: ios 9.3 (it happens also in earlier versions)

My ios cordova app uses the couchbase lite phonegap plugin, sometimes it can not save documents in app pause state(app is running in background),  the restful save request get error response as below:

`{ ... "status":500,"statusText":"Internal Server Error","responseText":"{\"status\":500,\"error\":\"Database error!\"}","responseXML":null,"responseBytes":null}`

There is also one log: 

`error opening!: 23`

However the save operation can succeed once app resumes from background mode,  so just some documents are lost from user point of view.  After further investigation and many tests,  I observed the error occurred only when:
- app in background mode
- the database has never been read before the save document operation

Workaround: I add one query view operation just after the database ready in app startup phase, the error disappeared. 

Though the workaround works, it's better to find the root cause and fix it.

Thanks!

**Comment by HanzhiDou** [comment]
The error in console log:
`error opening!: 23
`
The app uses background location updates, once new location available, it save the info to cbl.

background task is used to make the app running in background (beginBackgroundTaskWithExpirationHandler).

There is no attachment in this database, and the save operation is happened only after cbl ready and location updates are manual started.

**Comment by snej** [comment]
We don't have a REST API for changing the file protection settings of the database files. I think we'd need to add one, for this case. Then you can use a more lenient setting that allows you to access files while in the background.

**Comment by snej** [comment]
Note: We'd implement this along with the other proposed REST API extension to specify the db storage type, encryption key, etc.

**Comment by npomfret** [comment]
I'm also seeing thousands of these messages in the log

`<Notice>: error opening!: 23
`
Is there a workaround?

**Comment by snej** [comment]
> On Sep 27, 2016, at 1:47 AM, Nick Pomfret <notifications@github.com> wrote:
> 
> I'm also seeing thousands of these messages in the log
> 
> <Notice>: error opening!: 23
> 
> Is there a workaround?
> 

Yes, but it’s not available to PhoneGap apps unless you modify the native plugin code. You need to change the file protection mode of the CBLManager to one of the modes that allows file access after the app has been backgrounded. (Sorry, I don’t have the long names of those enums memorized!) We’re aware that this should be accessible from the REST API and have an issue open on that.

(It appears that iOS 10 is quicker to make files inaccessible after an app backgrounds; this problem has been coming up a lot more often.)

—Jens

**Comment by npomfret** [comment]
I'm using react-native so have access to the native code.  I'll see what I can get working.  Thanks for the advice.

**Comment by npomfret** [comment]
Does [NSDataWritingFileProtectionCompleteUntilFirstUserAuthentication](https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/StrategiesforImplementingYourApp/StrategiesforImplementingYourApp.html) sound familiar?

I'm scratching around a bit here.  My [code](https://github.com/couchbaselabs/react-native-couchbase-lite/blob/master/ios/ReactCBLite.m#L34) was doing this:

`CBLManager* dbmgr = [CBLManager sharedInstance]`

And I've tried changing to this:

```
        NSString* dir = [CBLManager defaultDirectory];
        CBLManagerOptions options = {};
        options.fileProtection = NSDataWritingFileProtectionCompleteUntilFirstUserAuthentication;
        NSError* error;
        CBLManager* dbmgr =   [[CBLManager alloc] initWithDirectory: dir options: &options error: &error];
```

But its not worked.  My databases aren't accessible over the rest api.

**Comment by snej** [comment]
`dbmgr` has to remain valid for the lifetime of the app, so you should make it a global variable, or an instance variable of the app delegate. Otherwise the reference will be released as soon as that method exits, which I believe will cause the manager to be dealloced. (Ah, the joys of using a language without full garbage collection!)

**Comment by npomfret** [comment]
Thank you! It's not live yet, but I hope this will improve the application responsiveness when backgrounded for long periods of time.  At the moment my push notifications and background fetch operations only work for a while and eventually stop.

In case anyone out there is as incompetent as me, here's the change I made:

Instead of `[CBLManager sharedInstance]`...

```
        CBLManagerOptions options = {NO, NSDataWritingFileProtectionCompleteUntilFirstUserAuthentication};
        NSError* error;
        manager = [[CBLManager alloc] initWithDirectory: [CBLManager defaultDirectory]
                                                        options: &options error: &error];
```


And add this to my header file:

```
#import <CouchbaseLite/CouchbaseLite.h>

@interface ...
{
...
CBLManager *manager;
}
@end
```

**Comment by pasin** [comment]
I added https://github.com/couchbaselabs/Couchbase-Lite-PhoneGap-Plugin/issues/89 for adding a configuration to set PhoneGap iOS file protection level. I will close this issue here.
