### ISSUE TITLE
OSStatus Error -9806 with peer-to-peer syncing

### ISSUE THREAD

**Issue by brendand** [couchbase/couchbase-lite-ios#1408]
When I configuring my CBLListener, I make this call:

```
BOOL success = [self.syncListener setAnonymousSSLIdentityWithLabel:@"tf-peer-sync" error:&error];
```

This should setup the anonymous SSL certificate, public, and private keys. 

But when sync occurs, some of my customers are getting an error that's thrown by the replicator (or somewhere down there) that simply states: `OSStatus Error -9806` which is an SSL security error of some sort.

https://www.osstatus.com/search/results?platform=all&framework=all&search=-9806

Apparently it's `errSSLClosedAbort the connection closed due to an error`

Have I done something wrong in setting up the SSL identity for peer-to-peer syncing?

---
- Version:   1.3
- Client OS: OS X 10.11 and iOS 9.x
- Server:    NAME_AND_VERSION

**Comment by brendand** [comment]
Oh, and if it's relevant, here's how I create my CBLListener:

```
self.syncListener = [[CBLListener alloc] initWithManager:_couchManager port:0];
self.syncListener.delegate = self;
self.syncListener.readOnly = YES;
```

**Comment by snej** [comment]
-9806 is [`errSSLClosedAbort`](https://www.osstatus.com/search/results?platform=all&framework=all&search=-9806) — means the SSL connection was aborted during the handshake, usually because the cert was rejected or App Transport Security decided the security level wasn't good enough.

I'd need to know exactly what versions of iOS both peers are running. It's been a while, but IIRC some older versions of iOS don't support the right SSL ciphers to be acceptable to iOS 9.

**Comment by brendand** [comment]
The minimum requirements for my app to launch are iOS 9.3.0 and OS X 10.11.0

**Comment by brendand** [comment]
So the customer said they were using iOS 9.3.4 and OS X 10.11.6. So pretty much current up-to-date.

It works for me without these errors. I'm really not sure what to have them try.

Did my code look correct?

**Comment by snej** [comment]
Device logs would be useful. It's also possible to make CFNetwork more verbose about SSL errors but it needs to be done by setting an environment variable, so it's not convenient for users to do.

**Comment by brendand** [comment]
Especially on iOS. It's happening on both Mac and iOS. If you can tell me what command I can get them to issue I'm pretty sure I can have them do it. Perhaps a defaults database setting?

**Comment by brendand** [comment]
I got some log information from the customer, but it just repeats this a bunch of times:

```
20/08/2016 11:24:18.124 am Tap Forms 5[4773]: CFNetwork SSLHandshake failed (-9806)
20/08/2016 11:28:36.730 am Tap Forms 5[4773]: CFNetwork SSLHandshake failed (-9806)
20/08/2016 11:31:27.649 am Tap Forms 5[4773]: CFNetwork SSLHandshake failed (-9806)
20/08/2016 11:34:03.639 am Tap Forms 5[4773]: CFNetwork SSLHandshake failed (-9806)
```

**Comment by brendand** [comment]
I found the Apple tech note on that and I've asked the customer if he'd be willing to run a special version of my app which has the CFNetwork logging enabled.

https://developer.apple.com/library/ios/qa/qa1887/_index.html

**Comment by jayahariv** [comment]
Closing 1.x issue!
