### ISSUE TITLE
Add resume/suspend replications to REST API

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-ios#1410]
I can't get any replications using `CBLDatabase allReplications` when called inside `didReceiveRemoteNotification` while the app is backgrounded. I assume this is because they are in a SUSPENDED state?

I'd like a method that does indeed return all replications, regardless of their state.

And / OR - add functionality to the REST API that allows the user to unsuspend the replication tasks.

**Comment by npomfret** [comment]
Its probably worth mentioning why I'm asking for this:  Without it I can't replicate data when receiving a push notification whilst the app is backgrounded.  I've added code to AppDelegate.m that wakes the app up for a few seconds, but without being able to resume the suspended tasks nothing happens.  

Also with mentioning is that the iOS behaviour and Android behaviour would ideally be the same.  Currently android appears to sync while in the background (there doesn't seem to be a concept of _suspended_).  In my opinion this is preferred.  I don't see why replications **need** to be suspended when the app is backgrounded, that decision should be for the developer to make.  I think adding an API call that allows the app developer to suspend is needed, but suspending when backgrounded by default is not ideal.

**Comment by npomfret** [comment]
Any chance of getting this into 1.3 ?

**Comment by snej** [comment]
The next upcoming release is 1.4, unless we find a real show-stopper bug that requires creating a 1.3.2.

**Comment by snej** [comment]
-allReplications does return all replications that haven't been stopped, so it should include suspended ones. These are continuous replications, right?

**Comment by snej** [comment]
How is your JS code being called when the app gets a notification while in the background? Ideally we'd automatically resume replications when this happens, but I don't think CBL code actually gets invoked. Does PhoneGap/Cordova have a special handler that dispatches to your JS code?

**Comment by npomfret** [comment]
I have 2 continuous replications running.  When a push notification comes in, my JS code gets notified so at this point I'm free to resume replications, or start some more (non-continuous / one-shot) replications.  The app has a certain amount of time before its suspended again.   My AppDelegate has this:

```
// Required for silent notification event (with "content-available" = 1) which *should* wake up the app in the background for a few seconds
-(void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)notification fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler {
  NSLog(@"notification-body => %@", notification);
  
  [RCTPushNotificationManager didReceiveRemoteNotification:notification];
  
  dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(10 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
    NSLog(@"notification-complete => %@", notification);

    completionHandler(UIBackgroundFetchResultNewData);
  });
}
```

Does that answer your question?

**Comment by npomfret** [comment]
If I could get a handle on the replications I could turn them on & off in objective-c code, but they don't seem to be available.

**Comment by snej** [comment]
So, revisiting this, I'm still unsure why -allReplications wouldn't return suspended replications. According to the code it should. How are you getting the CBLDatabase object? It may not be the same instance as the one your JS code talks to. Also:

>I don't see why replications need to be suspended when the app is backgrounded, that decision should be for the developer to make

Because Apple doesn't allow apps to have unlimited background time. When the app is backgrounded it can request a background task and will get a limited amount of time to finish up; after that, it's frozen. This is to improve battery life and performance.

**Comment by npomfret** [comment]
I see, thanks.


I start my db like this:

`        manager = [CBLManager sharedInstance];
`
And when a push notification arrives I get my db like this:

```
...
  CBLManager *manager = [CBLManager sharedInstance];
  for (NSString* name in [manager allDatabaseNames]) {
    CBLDatabase* db = [manager databaseNamed:name error:nil];
    NSArray* replications = [db allReplications];
   ...
```

The `replications` array is always empty even though I have started both push and pull replications using the REST api.

**Comment by jayahariv** [comment]
Closing 1.x issue!
