### ISSUE TITLE
bulk_get support for CouchDB 2.0

### ISSUE THREAD

**Issue by dyowee** [couchbase/couchbase-lite-ios#1411]
Will detection code be added to CouchbaseLite 1.4 to enable bulk_get with CouchDB 2.0?

**Comment by snej** [comment]
- [ ] Extend `Server` header detection to recognize CouchDB version number (as well as SG version number)
- [ ] Have the `_bulk_get` check look for CouchDB ≥ 2.0
- [ ] Test, then find and fix any compatibility problems

**Comment by jayahariv** [comment]
Closing 1.x issue!
