### ISSUE TITLE
ForestDB file `db.forest.1` size is very large and app sometimes crashes on launch

### ISSUE THREAD

**Issue by pahmed** [couchbase/couchbase-lite-ios#1413]
Hi,

I have a problem where sometimes the application crashes everytime i launch it, BUT when i try to launch the app while connecting it to the debugger it works normally (this happened with me many times on iOS 8.4 and on iOS 9 also), and when i checked the content of the `.cblite2` i found a file named `db.forest.1` with size `664 MB`, but not sure if the large database size is related to the crash.

---
- Version:   CBL 1.3
- Client OS: iOS 8.4

**Comment by pasin** [comment]
Can you provide a crash log?

**Comment by snej** [comment]
Large db files should not cause a problem. We need to see the crash log, please.

**Comment by pahmed** [comment]
I couldn't get a crash log because the app works normally whenever i connect it to the debugger.

**Comment by orenyodfat** [comment]
I see this issue also on my couchbase lite java server.
db.forest.1 is getting larger and larger..though ...there is no replication..

**Comment by pahmed** [comment]
I've tried after upgrading to CBL 1.3.1, and the problem still happens, i noticed the app size started getting bigger (while the replicators was working) until it reached `2.3 GB` now, when i disconnected the debugger and tried to launch the app, it crashed on launch and couldn't open it again until i connected it to the debugger. After launching the app from the debugger i saw those lines in the logs multiple times

```
[FDB ERR] Error in opening a partially compacted file '/var/mobile/Containers/Data/Application/71A04A45-CD93-4D3C-A2F0-3A10E132C58A/Library/Application Support/CouchbaseLite/xxxx.cblite2/db.forest.1' for recovery.

[FDB ERR] Error in OPEN on a database file '/var/mobile/Containers/Data/Application/71A04A45-CD93-4D3C-A2F0-3A10E132C58A/Library/Application Support/CouchbaseLite/xxxx.cblite2/db.forest.1', errno = 2: 'No such file or directory'
```

**Comment by snej** [comment]
ForestDB should be compacting the database (on a background thread) when the amount of wasted space reaches a threshold. It sounds like it's getting errors that prevent this from happening.

Please attach a complete log of application startup, and we can let the ForestDB engineers look at it.
Also, please get a crash log from when the app crashes on launch. Thanks!

**Comment by snej** [comment]
Could we get the info mentioned above ^ ? We need that to make progress figuring this out. Thanks.

**Comment by pahmed** [comment]
I'll try to reproduce the issue again and see if i can access the device crash log.

**Comment by lucatorella** [comment]
I'm experiencing something similar (and I'm using 1.3.1). 
I don't see any crash, but the size of the forest db database increase to over 1 GB while the size on the server is just 400MB.
What's strange is that inside the couchbase.cblite2 folder I see:
- db.forest.1 (about 1MB)
- db.forest.2 (> 1GB)
Another strange thing is that when I force quite the app the size of the second file is reduced to less than 400MB.

**Comment by dbauduin** [comment]
I'm also facing such a size issue (1.3.1, on Android): one of my forest db cblite2 file contains a file "db.forest.4" whose size is about 2 GB, and another one "db.forest.19" with a size of about 200 KB.
This database contains only 345 small documents and I don't synchronize it with a server.
I have just tried to set max revision tree depth to 2 and to compact it but the size is still the same.

**Comment by pasin** [comment]
Recently ForestDB has improved the space usage as well as fixed a compaction issue. See #1497 for more detail. The fix has been merged into the master branch. Please check it out.
