### ISSUE TITLE
Review database migration atomicity

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#1419]
CBL Android has an issue that if during the migration, something (e.g. crash) happens, the database migration ends up with incomplete data from the previous database. We should review if CBL iOS has the same or similar issue or not.

Reference: https://github.com/couchbase/couchbase-lite-android/issues/888

**Comment by snej** [comment]
We've decided iOS does have the same issue, and identified a strategy to update safely.

**Comment by pasin** [comment]
Close as not fix.
