### ISSUE TITLE
Dates BC stored as AD

### ISSUE THREAD

**Issue by 5b5** [couchbase/couchbase-lite-ios#1423]
Dates before Christ get stored as AD.
Change date pattern in CBLJSON.getISO8601Formatter() to
@"YYYY-MM-dd'T'HH:mm:ss.SSSXXX"
(uppercase 'Y's) ? 
CBLParseISO8601Date() seems to be already aware of leading minus sign.

- Version:   1.2.2
- Client OS: iOS 9
- Server:    CouchDB 1.6.1

**Comment by 5b5** [comment]
Using uppercase Y's solves the "negative years" problem but produces another one: YYYY is the year that is used together with "ww" (Week of year) so for 2015-12-30 "YYYY" prints "2016" because the day belongs to week 1/2016
It seems like there is currently no generic solution (working for each calendar seamlessly) which i suppose is one of the reasons for Apple adding the class NSISO8601DateFormatter in iOS/MacOS 10. (which does currently not to work with fractions of seconds)

**Comment by snej** [comment]
According to the [date patterns spec](http://unicode.org/reports/tr35/tr35-4.html#Date_Format_Patterns), `uuuu` should work:

>Extended year. This is a single number designating the year of this calendar system … An extended year value for the Julian calendar system assigns positive values to CE years and negative values to BCE years, with 1 BCE being year 0.
