### ISSUE TITLE
1.3.1-6: Unable to increment sequence: MCResponse status=TMPFAIL, opcode=INCREMENT, opaque=0, msg: Temporary failure

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-ios#1427]
Saw this in  my client logs today.  Any idea what it means?

Sorry for the formatting: 

`{\"error\":\"Internal Server Error\",\"reason\":\"Internal error: Unable to increment sequence: MCResponse status=TMPFAIL, opcode=INCREMENT, opaque=0, msg: Temporary failure\"},{\"_id\":\"5f4b60ba-cc24-4e68-b79f-5cba5c775a14\",\"type\":\"live-chat\",\"owner\":\"7f3b03b8-340d-4d41-80f9-d4ebec187216\",\"chat_group_id\":\"e26ae078-a325-4131-9b84-e73f046aef3e\",\"client_timestamp_utc\":\"2016-09-03T08:28:25Z\",\"recipients\":[\"7f3b03b8-340d-4d41-80f9-d4ebec187216\",\"e35960ec-8b72-4048-9454-c4d891f05c21\"],\"typing\":\"Not specta\",\"audit\":{\"user_id\":\"7f3b03b8-340d-4d41-80f9-d4ebec187216\",\"client_timestamp_utc\":\"2016-09-03T08:28:25Z\",\"build_number\":\"227\"}},\"failed to save\",\"live-chat\",\"5f4b60ba-cc24-4e68-b79f-5cba5c775a14\",null,{\"error\":\"Internal Server Error\",\"reason\":\"Internal error: Unable to increment sequence: MCResponse status=TMPFAIL, opcode=INCREMENT, opaque=0, msg: Temporary failure\"},{\"_id\":\"5f4b60ba-cc24-4e68-b79f-5cba5c775a14\",\"type\":\"live-chat\",\"owner\":\"7f3b03b8-340d-4d41-80f9-d4ebec187216\",\"chat_group_id\":\"e26ae078-a325-4131-9b84-e73f046aef3e\",\"client_timestamp_utc\":\"2016-09-03T08:28:25Z\",\"recipients\":[\"7f3b03b8-340d-4d41-80f9-d4ebec187216\",\"e35960ec-8b72-4048-9454-c4d891f05c21\"],\"typing\":\"Not specta\",\"audit\":{\"user_id\":\"7f3b03b8-340d-4d41-80f9-d4ebec187216\",\"client_timestamp_utc\":\"2016-09-03T08:28:25Z\",\"build_number\":\"227\"}},6]"
`

**Comment by pasin** [comment]
I guessed the error is from SGW as? I understand that MCResponse is from gomemcached. @adamcfraser do you have any ideas about this error?

**Comment by adamcfraser** [comment]
Looks like a temporary failure coming back from Couchbase Server in response to an incr request (used when Sync Gateway is assigning a sequence to the write).  

This should be less frequent when using Sync Gateway 1.3 or later - there's internal retry processing for the incr operation.

**Comment by pasin** [comment]
Thanks @adamcfraser for the info. I'm closing the issue now. @npomfret if you found that the error links or causes any side effects, please let us know and we can reopen the issue.

**Comment by npomfret** [comment]
Ok. It happened with sg 1.3 but I couldn't see any negative side effects.  Just thought I should post it in case it was of interest.

**Comment by npomfret** [comment]
Hi, its still happening on the latest CBL 1.3.1-9.  Document fails to save for no apparent reason from time to time.

`Internal error: Unable to increment sequence: MCResponse status=TMPFAIL, opcode=INCREMENT, opaque=0, msg: Temporary failure`

**Comment by snej** [comment]
IIRC we decided the current behavior is the right thing to do. Couchbase Server via SG is kind of pushing back to the client saying that it's too busy right now. The client responds by giving up for the moment and then retrying a few seconds later.

This should NOT be preventing replication from succeeding. At worst it means it'll take a little while longer to finish, because it has to back off and retry some writes.

**Comment by npomfret** [comment]
Ok, so the write to my local CBL succeeded, its just the replication got delayed?

**Comment by snej** [comment]
Yes. That error message is from Sync Gateway, which is relaying the error message it got from Couchbase Server (the `MCResponse....` stuff.) If you look at the logs around that stuff, it should indicate that it's displaying a replication error status.
