### ISSUE TITLE
Attachments failed to replicate when deleted and recreated

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-ios#1440]
This also fails with Android (1.3.1-30) and .NET (1.3.1-13)

Failing test - https://github.com/couchbaselabs/mobile-testkit/blob/feature/add-multiple-sg-replication-test/testsuites/listener/shared/client_sg/attachments.py#L14-L86

Steps to reproduce:
1. Start continuous replication between LiteServ and Sync Gateway
2. Add a few docs with large attachements to LiteServ
3. Immediately after delete the docs on LiteServ
4. Recreate the docs on LiteServ with the same id and attachment (rev = 3-xxxxx)
5. The recreated attachement docs do not sync to sync gateway

Expected: Recreated attachment docs would sync
Actual: They do not

I am seeing these errors in the logs

```
14:21:50.655‖ WARNING: CBLRestPusher[http://192.168.0.49:4985/db]: _bulk_docs got an error: {
    error = "bad_request";
    id = "large_attach_0";
    reason = "Missing digest in stub attachment \"golden_gate_large.jpg\"";
    status = 400;
} {at __40-[CBLRestPusher uploadBulkDocs:changes:]_block_invoke:402}
14:21:50.655‖ WARNING: CBLRestPusher[http://192.168.0.49:4985/db]: _bulk_docs got an error: {
    error = "bad_request";
    id = "large_attach_1";
    reason = "Missing digest in stub attachment \"golden_gate_large.jpg\"";
    status = 400;
```

---
- Version:   1.3.1-6
- Client OS: Mac OSX
- Server:    Sync Gateway 1.3.1-16

**Comment by borrrden** [comment]
https://github.com/couchbaselabs/mobile-testkit/blob/feature/add-multiple-sg-replication-test/testsuites/listener/shared/client_sg/attachments.py#L82 I don't think this is valid.  Purged docs do *not* replicate

**Comment by borrrden** [comment]
Analysis:  https://github.com/couchbase/couchbase-lite-ios/blob/2d6e6355e46cacab46d404bfb5e7ceaa1a92a7c9/Source/CBLDatabase%2BAttachments.m#L303 this is the offending area.  Include the digest here (it is already on attachment in this case, but need to confirm that this is a valid thing to do.  It seems that there is already a stub in this case so really the attachment doesn't need mutating I think?) and the test can proceed.  .NET will pass the test with this change and a small .NET specific one.

**Comment by snej** [comment]
I'm not clear how that line relates to this bug. If the doc was deleted and then recreated, doesn't the new revision's attachment have a `revpos=3`? If so, it wouldn't hit the offending line.

**Comment by borrrden** [comment]
It doesn't.  It still has `revpos=1`

**Comment by borrrden** [comment]
Analysis:  The following sequence triggers this behavior:

1) PUT document with attachment
2) DELETE document
3) PUT document with attachment *and no rev-id*

In particular the third call without the revid causes the process attachments method to get a `nil` previous revision and default to generation 1

**Comment by pasin** [comment]
Once https://github.com/couchbase/couchbase-lite-net/pulls?q=is%3Apr+is%3Aopen+label%3Across-platform is merged, I can port the fix to the iOS platform.
