### ISSUE TITLE
Collection class properties not propagating from CBLDocument to CBLModel after sync

### ISSUE THREAD

**Issue by brendand** [couchbase/couchbase-lite-ios#1442]
I'm debugging a sync issue and I'm seeing a situation where the CBLDocument has been correctly updated after a sync on my iPhone from a change I made on my Mac, but the associated property on the CBLModel subclass has not updated from the sync.

This appears to be related to the values within a collection class (in this case an NSDictionary) not updating in the CBLModel after a sync.

Here's what a fragment of my CBLDocument looks like on my iPhone after my iPhone pulls the changes from the Mac:

```
(lldb) po [self.formEntry.document properties]
{
    values =     {
        "fld-0323bba4bfa54faa924da9128e298264" = "There we are again stuff";
        "fld-0c1953513df54c07ae9b30ba3c44f93e" = 1;
```

And here's what my CBLModel looks like for the same values property on the iPhone:

```
(lldb) po [self.formEntry values]
{
    "fld-0323bba4bfa54faa924da9128e298264" = "There we are";
    "fld-0c1953513df54c07ae9b30ba3c44f93e" = 1;
```

I've defined my "values" property as such:

`@property (nullable, nonatomic, strong) NSDictionary *values;`

And in my implementation I have values defined as @dynamic:

`@dynamic values;`

Notice the content in the first "fld" dictionary key's value is different. The CBLDocument's values property contains a key with the value "There we are again stuff" whereas the CBLModel has "There we are".

I would have expected that the values property in the CBLModel would contain the same data as the values property in the CBLDocument's properties dictionary.

For reference, here's the Google Groups discussion on this topic:

https://groups.google.com/forum/?pli=1#!topic/mobile-couchbase/yNp-hi29s0M

--------
* Version:   1.3 commit # 372b6bfdffc2ea70cf1fe040b52dd05937bdec9c
* Client OS: iOS 10.0.1
* Server:    n/a

**Comment by snej** [comment]
This is pretty surprising, but it also sounds easy to write a unit test for :) so I'll try that today.

**Comment by brendand** [comment]
I've discovered that it seems to be limited to iOS also. On macOS Sierra, the values appear to propagate to the model after a sync.

**Comment by snej** [comment]
I wrote a simple test case for this and can't reproduce it. Also, I can't imagine how the behavior of CBLModel would be different on iOS.

The only way that a model's properties wouldn't be in sync with the doc's after the doc updates, is if the model had unsaved changes. Those changes shadow the document's properties. Is it possible you'd assigned a new value to the model's `values` property? (On the other hand, the setter does a deep equality test, so if you set `values` to an identical dictionary, that would be a no-op and no shadowing would happen.)

**Comment by snej** [comment]
I think the best way for you to debug this is to temporarily override this CBLModel method:
```objc
- (void) document: (CBLDocument*)doc didChange:(CBLDatabaseChange*)change {
    NSLog( ... Log stuff before the change);
    [super document: doc didChange: change];
    NSLog( ... Log stuff after the change);
}
```
If you have access to CBLModel's implementation while debugging, it would be very interesting to know what the values of `_properties` and `_changedNames` are.

**Comment by brendand** [comment]
I think we may be on to something here. I just noticed that I have a formula that uses the current date to calculate a result. The current date is always changing of course so I think this might be the source of the problem. If so I really apologize for sending you on this goose chase. I'm just digging into it now.

**Comment by brendand** [comment]
Ok. I think this is definitely the problem. I'm going to close this issue because it turns out it is in fact my problem because of me updating the record due to my calculation field's value being updated after a sync. It just seemed odd that the CBLDocument's property had a different value than the model's property.

**Comment by snej** [comment]
Whew, OK. I do admit that CBLModel is lacking support for handling these sorts of conflicts between an in-memory change and a document update. I've been meaning to add that forever but haven't.
