### ISSUE TITLE
Handle iOS file protection gracefully when in background

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1443]
Detect when the database files are not accessible (i.e. app is in background / device is locked) and don't perform operations that would open db files.

To some degree it may be cleaner to just try and fail; we'll have to evaluate that. (There can certainly be race conditions involved with preflighting.)

**Comment by snej** [comment]
See #1433, #1422 for side effect bugs caused by accessing files when they're un-openable.

**Comment by brendand** [comment]
Not sure if this is relevant to this issue, but my Apple Watch app requires access to the database when the app is running in the background. In fact, the Apple Watch app will launch the iOS app in the background if it's not already running and will establish a background database connection on its own dispatch_queue. So if whatever change you're making won't allow background access to the database then that could be an issue. Sorry if I've misunderstood or don't know all the details about iOS file protection.

**Comment by basememara** [comment]
If your app requires background access before and you have your database protection level set to 'NSFileProtectionCompleteUnlessOpen' (the Couchbase default), then it almost never worked for you and you should see existing crash reports. This change should not make it crash but silently ignore if the database cannot be opened. This is important because if your app crashes in the background, it will not be woken up by iOS anymore until he user explicitly opens the app again.

**Comment by brendand** [comment]
I haven't noticed any crashing when my device is locked and I access my app from my Apple Watch. It just works (so far).

**Comment by snej** [comment]
I don't know the details, but I _think_ that if the OS explicitly wakes up your app to do work, it first gives it access to its files. The problems I know of stem from the app already running in the background when the user locks the device, which causes file access to be lost.

**Comment by jamiltz** [comment]
@brendand I'm definitely

**Comment by jamiltz** [comment]
Oops sorry, I pressed the wrong button.

@brendand The remote access to documents from the apple watch sounds great!

**Comment by npomfret** [comment]
I get a 500 error on mine sometimes during start up.  I think it might be when the app is being started in the background (though I don't know what causes it to start in the background). Is this likely to cause it?

I'm starting the CBLManager with `CBLManagerOptions options = {NO, NSDataWritingFileProtectionCompleteUntilFirstUserAuthentication}`.

**Comment by npomfret** [comment]
Has there been any progress on this?

It seems to me that it happens only (but not always) when the app is started in the background after the OS has suspended it, for example when a push notification arrives.  Sometimes the app starts ok, and sometimes not.  If it doesn't I see lots of these 500 errors when querying CBL.  I haven't found a work around yet.  Does anyone know of one?

There's no error messages unfortunately.  Could we at least add one?
