### ISSUE TITLE
/_all_docs failed on 1.3.1-9

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-ios#1449]
Calling the `_all_docs` endpoint with just `include_docs=true` parameter sometimes results in this error:

`{"error":"Database error!","status":500}}` 

Request adding some more information to the http response.

**Comment by snej** [comment]
Hm, in 1.3 I added better error handling that should have resulted in a more descriptive error. Was anything written to the console/log?

**Comment by npomfret** [comment]
That's all I got I'm afraid.

**Comment by snej** [comment]
@sethrosetter: This sounds like a good functional test to add.
@npomfret: How often does the error occur? Is it purely random, or does it depend on the state of the database?

**Comment by npomfret** [comment]
I haven't seen any pattern to it yet, but I'll let you know if that changes.

**Comment by npomfret** [comment]
It might be happening when the app is running in the background.  Either awoken by a push notification or a periodic background fetch.  Does that sound like a likely cause?

**Comment by snej** [comment]
Probably. We're tracking that problem as #1443.

**Comment by npomfret** [comment]
This seems to happen at start up, when the very first call to the database happens.  Is it possible that my app is starting up in the background somehow?  And because it's in the background then it doesn't have the necessary permissions to assess the db?
