### ISSUE TITLE
Unable to compile CBL latest Github code - linker errors

### ISSUE THREAD

**Issue by msanilkumar2020** [couchbase/couchbase-lite-ios#1452]
--------
* Version:   Latest branch
* Client OS: Xcode 7.3.1

Hi ,

I am not able to compile latest checkout code from git, please let me know how to resolve this issue.

Below is the linker issue details.

Thanks,
Anil Kumar

Undefined symbols for architecture arm64:
  "___asan_alloca_poison", referenced from:
      -[CBL_GCDAsyncReadPacket readLengthForTermWithPreBuffer:found:] in CouchbaseLiteListener(GCDAsyncSocket.o)
      -[CBL_GCDAsyncSocket ssl_startTLS] in CouchbaseLiteListener(GCDAsyncSocket.o)
  "___asan_allocas_unpoison", referenced from:
      -[CBL_GCDAsyncReadPacket readLengthForTermWithPreBuffer:found:] in CouchbaseLiteListener(GCDAsyncSocket.o)
      -[CBL_GCDAsyncSocket ssl_startTLS] in CouchbaseLiteListener(GCDAsyncSocket.o)
  "_$regex", referenced from:
      -[CBL_Router processRequestRanges] in CouchbaseLiteListener(CBL_Router.o)
  "___asan_stack_malloc_3", referenced from:
      -[CBL_HTTPServer start:] in CouchbaseLiteListener(HTTPServer.o)
      +[CBL_DDLog lt_removeLogger:] in CouchbaseLiteListener(DDLog.o)
      +[CBL_DDLog lt_removeAllLoggers] in CouchbaseLiteListener(DDLog.o)
      +[CBL_DDLog lt_flush] in CouchbaseLiteListener(DDLog.o)
      _CBL_DDIntersectionRange in CouchbaseLiteListener(DDRange.o)
      -[CBL_GCDAsyncSocket getDelegate:delegateQueue:] in CouchbaseLiteListener(GCDAsyncSocket.o)
      -[CBL_GCDAsyncSocket acceptOnInterface:port:error:] in CouchbaseLiteListener(GCDAsyncSocket.o)
      ...
  "___asan_report_load2", referenced from:
      -[CBL_HTTPServer port] in CouchbaseLiteListener(HTTPServer.o)
      ___22-[CBL_HTTPServer port]_block_invoke in CouchbaseLiteListener(HTTPServer.o)
      ___26-[CBL_HTTPServer setPort:]_block_invoke in CouchbaseLiteListener(HTTPServer.o)
      ___24-[CBL_HTTPServer start:]_block_invoke in CouchbaseLiteListener(HTTPServer.o)
      -[CBL_HTTPServer listeningPort] in CouchbaseLiteListener(HTTPServer.o)
      -[CBL_GCDAsyncSocket isIPv4Enabled] in CouchbaseLiteListener(GCDAsyncSocket.o)
      ___35-[CBL_GCDAsyncSocket isIPv4Enabled]_block_invoke in CouchbaseLiteListener(GCDAsyncSocket.o)
      ...
  "__mdictof", referenced from:
      -[CBLDatabase(REST) updateAttachment:body:type:encoding:ofDocID:revID:source:status:error:] in CouchbaseLiteListener(CBLDatabase+REST.o)
      -[CBL_Router queries] in CouchbaseLiteListener(CBL_Router.o)
      -[CBL_Router(Handlers) do_POST_revs_diff:] in CouchbaseLiteListener(CBL_Router+Handlers.o)
  "__AssertFailed", referenced from:
      -[CBLDatabase(REST) attachmentForRevision:named:status:] in CouchbaseLiteListener(CBLDatabase+REST.o)
      -[CBL_Router route] in CouchbaseLiteListener(CBL_Router.o)
      -[CBL_Router run] in CouchbaseLiteListener(CBL_Router.o)
      ___42-[CBL_Router(Handlers) do_POST_bulk_docs:]_block_invoke in CouchbaseLiteListener(CBL_Router+Handlers.o)
  "___asan_memcpy", referenced from:
      -[CBL_HTTPAuthenticationRequest quotedSubHeaderFieldValue:fromHeaderFieldValue:] in CouchbaseLiteListener(HTTPAuthenticationRequest.o)
      -[CBL_HTTPAuthenticationRequest nonquotedSubHeaderFieldValue:fromHeaderFieldValue:] in CouchbaseLiteListener(HTTPAuthenticationRequest.o)
      -[CBL_HTTPConnection parseRangeRequest:withContentLength:satisfiableRange:] in CouchbaseLiteListener(HTTPConnection.o)
      -[CBL_HTTPConnection continueSendingMultiRangeResponseBody] in CouchbaseLiteListener(HTTPConnection.o)
      -[CBLDatabase(REST) updateAttachment:body:type:encoding:ofDocID:revID:source:status:error:] in CouchbaseLiteListener(CBLDatabase+REST.o)
      _CBL_DDIntersectionRange in CouchbaseLiteListener(DDRange.o)
      -[NSValue(NSValueDDRangeExtensions) ddrangeValue] in CouchbaseLiteListener(DDRange.o)
      ...
  "___asan_memset", referenced from:
      -[CBL_HTTPConnection filePathForURI:allowDirectory:] in CouchbaseLiteListener(HTTPConnection.o)
      -[CBLDatabase(REST) updateAttachment:body:type:encoding:ofDocID:revID:source:status:error:] in CouchbaseLiteListener(CBLDatabase+REST.o)
      ___23-[CBL_HTTPServer stop:]_block_invoke in CouchbaseLiteListener(HTTPServer.o)
      +[CBL_DDLog registeredClassNames] in CouchbaseLiteListener(DDLog.o)
      +[CBL_DDLog lt_removeLogger:] in CouchbaseLiteListener(DDLog.o)
      +[CBL_DDLog lt_removeAllLoggers] in CouchbaseLiteListener(DDLog.o)
      +[CBL_DDLog lt_log:] in CouchbaseLiteListener(DDLog.o)
      ...
  "___asan_handle_no_return", referenced from:
      -[CBLDatabase(REST) attachmentForRevision:named:status:] in CouchbaseLiteListener(CBLDatabase+REST.o)
      -[CBL_Router route] in CouchbaseLiteListener(CBL_Router.o)
      -[CBL_Router run] in CouchbaseLiteListener(CBL_Router.o)
      ___42-[CBL_Router(Handlers) do_POST_bulk_docs:]_block_invoke in CouchbaseLiteListener(CBL_Router+Handlers.o)
      -[CBL_Router(Handlers) do_POST_temp_view:] in CouchbaseLiteListener(CBL_Router+Handlers.o)
  "___asan_report_store16", referenced from:
      -[CBL_HTTPAuthenticationRequest quotedSubHeaderFieldValue:fromHeaderFieldValue:] in CouchbaseLiteListener(HTTPAuthenticationRequest.o)
      -[CBL_HTTPAuthenticationRequest nonquotedSubHeaderFieldValue:fromHeaderFieldValue:] in CouchbaseLiteListener(HTTPAuthenticationRequest.o)
      -[CBL_HTTPConnection isAuthenticated] in CouchbaseLiteListener(HTTPConnection.o)
      -[CBL_HTTPConnection parseParams:] in CouchbaseLiteListener(HTTPConnection.o)
      -[CBL_HTTPConnection parseRangeRequest:withContentLength:satisfiableRange:] in CouchbaseLiteListener(HTTPConnection.o)
      -[CBL_HTTPConnection newUniRangeResponse:] in CouchbaseLiteListener(HTTPConnection.o)
      -[CBL_HTTPConnection newMultiRangeResponse:] in CouchbaseLiteListener(HTTPConnection.o)
      ...
  "___asan_stack_malloc_0", referenced from:
      ___25-[CBLJSViewCompiler init]_block_invoke.10 in libCBLJSViewCompiler.a(CBLJSViewCompiler.o)
      -[CBL_HTTPDataResponse dealloc] in CouchbaseLiteListener(HTTPDataResponse.o)
      -[CBL_HTTPFileResponse dealloc] in CouchbaseLiteListener(HTTPFileResponse.o)
      -[CBLHTTPListener setTXTRecordDictionary:] in CouchbaseLiteListener(CBLHTTPListener.o)
      -[CBL_MYDDLogger logMessage:] in CouchbaseLiteListener(CBLHTTPListener.o)
      +[CBL_HTTPConnection initialize] in CouchbaseLiteListener(HTTPConnection.o)
      -[CBL_HTTPConnection dealloc] in CouchbaseLiteListener(HTTPConnection.o)
      ...
  "___asan_report_load16", referenced from:
      -[CBL_HTTPAuthenticationRequest quotedSubHeaderFieldValue:fromHeaderFieldValue:] in CouchbaseLiteListener(HTTPAuthenticationRequest.o)
      -[CBL_HTTPAuthenticationRequest nonquotedSubHeaderFieldValue:fromHeaderFieldValue:] in CouchbaseLiteListener(HTTPAuthenticationRequest.o)
      -[CBL_HTTPConnection parseRangeRequest:withContentLength:satisfiableRange:] in CouchbaseLiteListener(HTTPConnection.o)
      -[CBL_HTTPConnection newUniRangeResponse:] in CouchbaseLiteListener(HTTPConnection.o)
      -[CBL_HTTPConnection newMultiRangeResponse:] in CouchbaseLiteListener(HTTPConnection.o)
      _CBL_DDIntersectionRange in CouchbaseLiteListener(DDRange.o)
      -[NSValue(NSValueDDRangeExtensions) ddrangeValue] in CouchbaseLiteListener(DDRange.o)
      ...
  "__castIf", referenced from:
      -[CBLView(REST) compileFromDesignDoc] in CouchbaseLiteListener(CBLView+REST.o)
      -[CBLView(REST) compileFromProperties:language:] in CouchbaseLiteListener(CBLView+REST.o)
      -[CBLDatabase(REST) getDesignDocFunction:key:language:] in CouchbaseLiteListener(CBLDatabase+REST.o)
      -[CBLDatabase(REST) compileFilterNamed:status:] in CouchbaseLiteListener(CBLDatabase+REST.o)
      -[CBL_Router bodyAsDictionary] in CouchbaseLiteListener(CBL_Router.o)
      -[CBL_Router(Handlers) do_POST_facebook_token] in CouchbaseLiteListener(CBL_Router+Handlers.o)
      -[CBL_Router(Handlers) do_POST_bulk_docs:] in CouchbaseLiteListener(CBL_Router+Handlers.o)
      ...
  "___asan_stack_malloc_1", referenced from:
      -[CBLJSCompiler init] in libCBLJSViewCompiler.a(CBLJSFunction.o)
      _WarnJSException in libCBLJSViewCompiler.a(CBLJSFunction.o)
      ___25-[CBLJSViewCompiler init]_block_invoke in libCBLJSViewCompiler.a(CBLJSViewCompiler.o)
      -[CBLJSViewCompiler emitWithKey:value:] in libCBLJSViewCompiler.a(CBLJSViewCompiler.o)
      -[CBL_HTTPDataResponse initWithData:] in CouchbaseLiteListener(HTTPDataResponse.o)
      -[CBLHTTPListener setBonjourName:type:] in CouchbaseLiteListener(CBLHTTPListener.o)
      -[CBL_HTTPConnection supportsMethod:atPath:] in CouchbaseLiteListener(HTTPConnection.o)
      ...
  "___asan_report_store1", referenced from:
      -[CBL_HTTPFileResponse initWithFilePath:forConnection:] in CouchbaseLiteListener(HTTPFileResponse.o)
      -[CBL_HTTPFileResponse abort] in CouchbaseLiteListener(HTTPFileResponse.o)
      -[CBL_HTTPAuthenticationRequest initWithRequest:] in CouchbaseLiteListener(HTTPAuthenticationRequest.o)
      +[CBL_HTTPConnection hasRecentNonce:] in CouchbaseLiteListener(HTTPConnection.o)
      ___37+[CBL_HTTPConnection hasRecentNonce:]_block_invoke in CouchbaseLiteListener(HTTPConnection.o)
      ___27-[CBL_HTTPConnection start]_block_invoke in CouchbaseLiteListener(HTTPConnection.o)
      -[CBL_HTTPConnection parseRangeRequest:withContentLength:satisfiableRange:] in CouchbaseLiteListener(HTTPConnection.o)
      ...
  "___asan_report_load1", referenced from:
      -[CBLView(REST) compileFromDesignDoc] in CouchbaseLiteListener(CBLView+REST.o)
      -[CBL_HTTPFileResponse openFileIfNeeded] in CouchbaseLiteListener(HTTPFileResponse.o)
      -[CBL_HTTPAuthenticationRequest initWithRequest:] in CouchbaseLiteListener(HTTPAuthenticationRequest.o)
      -[CBL_HTTPAuthenticationRequest isBasic] in CouchbaseLiteListener(HTTPAuthenticationRequest.o)
      -[CBL_HTTPAuthenticationRequest isDigest] in CouchbaseLiteListener(HTTPAuthenticationRequest.o)
      +[CBLHTTPListener initialize] in CouchbaseLiteListener(CBLHTTPListener.o)
      -[CBL_MYDDLogger logMessage:] in CouchbaseLiteListener(CBLHTTPListener.o)
      ...
  "___asan_register_globals", referenced from:
      _asan.module_ctor in libCBLJSViewCompiler.a(CBLJSViewCompiler.o)
      _asan.module_ctor in libCBLJSViewCompiler.a(CBLJSViewCompiler_vers.o)
      _asan.module_ctor in CouchbaseLiteListener(CBLView+REST.o)
      _asan.module_ctor in CouchbaseLiteListener(HTTPFileResponse.o)
      _asan.module_ctor in CouchbaseLiteListener(HTTPConnection.o)
      _asan.module_ctor in CouchbaseLiteListener(CBLDatabase+REST.o)
      _asan.module_ctor in CouchbaseLiteListener(HTTPServer.o)
      ...
  "___asan_report_store2", referenced from:
      -[CBL_HTTPServer init] in CouchbaseLiteListener(HTTPServer.o)
      ___22-[CBL_HTTPServer port]_block_invoke in CouchbaseLiteListener(HTTPServer.o)
      -[CBL_HTTPServer setPort:] in CouchbaseLiteListener(HTTPServer.o)
      ___26-[CBL_HTTPServer setPort:]_block_invoke in CouchbaseLiteListener(HTTPServer.o)
      -[CBL_HTTPServer setListeningPort:] in CouchbaseLiteListener(HTTPServer.o)
      -[CBL_GCDAsyncSocket acceptOnInterface:port:error:] in CouchbaseLiteListener(GCDAsyncSocket.o)
      ___51-[CBL_GCDAsyncSocket acceptOnInterface:port:error:]_block_invoke.207 in CouchbaseLiteListener(GCDAsyncSocket.o)
      ...
  "___asan_stack_malloc_2", referenced from:
      -[CBLJSViewCompiler compileMapFunction:language:] in libCBLJSViewCompiler.a(CBLJSViewCompiler.o)
      -[CBLJSFilterCompiler compileFilterFunction:language:] in libCBLJSViewCompiler.a(CBLJSViewCompiler.o)
      +[CBL_HTTPConnection generateNonce] in CouchbaseLiteListener(HTTPConnection.o)
      +[CBL_HTTPConnection hasRecentNonce:] in CouchbaseLiteListener(HTTPConnection.o)
      -[CBL_HTTPConnection responseHasAvailableData:] in CouchbaseLiteListener(HTTPConnection.o)
      -[CBL_HTTPConnection responseDidAbort:] in CouchbaseLiteListener(HTTPConnection.o)
      -[CBL_HTTPConfig initWithServer:documentRoot:] in CouchbaseLiteListener(HTTPConnection.o)
      ...
  "___asan_report_load4", referenced from:
      -[CBL_HTTPFileResponse openFile] in CouchbaseLiteListener(HTTPFileResponse.o)
      -[CBL_HTTPFileResponse openFileIfNeeded] in CouchbaseLiteListener(HTTPFileResponse.o)
      -[CBL_HTTPFileResponse setOffset:] in CouchbaseLiteListener(HTTPFileResponse.o)
      -[CBL_HTTPFileResponse readDataOfLength:] in CouchbaseLiteListener(HTTPFileResponse.o)
      -[CBL_HTTPFileResponse dealloc] in CouchbaseLiteListener(HTTPFileResponse.o)
      -[CBL_MYDDLogger logMessage:] in CouchbaseLiteListener(CBLHTTPListener.o)
      -[CBL_HTTPConnection continueSendingMultiRangeResponseBody] in CouchbaseLiteListener(HTTPConnection.o)
      ...
  "___asan_stack_malloc_4", referenced from:
      ___23-[CBL_HTTPServer stop:]_block_invoke in CouchbaseLiteListener(HTTPServer.o)
      +[CBL_DDLog lt_log:] in CouchbaseLiteListener(DDLog.o)
  "___asan_report_store4", referenced from:
      -[CBLJSViewCompiler init] in libCBLJSViewCompiler.a(CBLJSViewCompiler.o)
      -[CBLJSViewCompiler compileMapFunction:language:] in libCBLJSViewCompiler.a(CBLJSViewCompiler.o)
      -[CBLJSViewCompiler compileReduceFunction:language:] in libCBLJSViewCompiler.a(CBLJSViewCompiler.o)
      -[CBLJSFilterCompiler compileFilterFunction:language:] in libCBLJSViewCompiler.a(CBLJSViewCompiler.o)
      -[CBL_HTTPFileResponse initWithFilePath:forConnection:] in CouchbaseLiteListener(HTTPFileResponse.o)
      -[CBL_HTTPFileResponse openFile] in CouchbaseLiteListener(HTTPFileResponse.o)
      +[CBL_HTTPConnection generateNonce] in CouchbaseLiteListener(HTTPConnection.o)
      ...
  "___asan_unregister_globals", referenced from:
      _asan.module_dtor in libCBLJSViewCompiler.a(CBLJSViewCompiler.o)
      _asan.module_dtor in libCBLJSViewCompiler.a(CBLJSViewCompiler_vers.o)
      _asan.module_dtor in CouchbaseLiteListener(CBLView+REST.o)
      _asan.module_dtor in CouchbaseLiteListener(HTTPFileResponse.o)
      _asan.module_dtor in CouchbaseLiteListener(HTTPConnection.o)
      _asan.module_dtor in CouchbaseLiteListener(CBLDatabase+REST.o)
      _asan.module_dtor in CouchbaseLiteListener(HTTPServer.o)
      ...
  "___asan_version_mismatch_check_apple_703", referenced from:
      _asan.module_ctor in libCBLJSViewCompiler.a(CBLJSFunction.o)
      _asan.module_ctor in libCBLJSViewCompiler.a(CBLRegisterJSViewCompiler.o)
      _asan.module_ctor in libCBLJSViewCompiler.a(CBLJSViewCompiler.o)
      _asan.module_ctor in libCBLJSViewCompiler.a(CBLJSViewCompiler_vers.o)
      _asan.module_ctor in CouchbaseLiteListener(CBLView+REST.o)
      _asan.module_ctor in CouchbaseLiteListener(HTTPDataResponse.o)
      _asan.module_ctor in CouchbaseLiteListener(HTTPFileResponse.o)
      ...
  "___asan_init", referenced from:
      _asan.module_ctor in libCBLJSViewCompiler.a(CBLJSFunction.o)
      _asan.module_ctor in libCBLJSViewCompiler.a(CBLRegisterJSViewCompiler.o)
      _asan.module_ctor in libCBLJSViewCompiler.a(CBLJSViewCompiler.o)
      _asan.module_ctor in libCBLJSViewCompiler.a(CBLJSViewCompiler_vers.o)
      _asan.module_ctor in CouchbaseLiteListener(CBLView+REST.o)
      _asan.module_ctor in CouchbaseLiteListener(HTTPDataResponse.o)
      _asan.module_ctor in CouchbaseLiteListener(HTTPFileResponse.o)
      ...
  "__dictof", referenced from:
      -[CBLDatabase(REST) updateAttachment:body:type:encoding:ofDocID:revID:source:status:error:] in CouchbaseLiteListener(CBLDatabase+REST.o)
      -[CBLResponse setInternalStatus:] in CouchbaseLiteListener(CBL_Router.o)
      -[CBLResponse setMultipartBody:type:] in CouchbaseLiteListener(CBL_Router.o)
      -[CBL_Router(Handlers) do_POST_persona_assertion] in CouchbaseLiteListener(CBL_Router+Handlers.o)
      -[CBL_Router(Handlers) do_POST_facebook_token] in CouchbaseLiteListener(CBL_Router+Handlers.o)
      -[CBL_Router(Handlers) do_GET_uuids] in CouchbaseLiteListener(CBL_Router+Handlers.o)
      -[CBL_Router(Handlers) do_GET_session] in CouchbaseLiteListener(CBL_Router+Handlers.o)
      ...
  "_$equal", referenced from:
      -[CBLView(REST) compileFromProperties:language:] in CouchbaseLiteListener(CBLView+REST.o)
      -[CBLHTTPConnection supportsMethod:atPath:] in CouchbaseLiteListener(CBLHTTPConnection.o)
      -[CBLHTTPConnection expectsRequestBodyFromMethod:atPath:] in CouchbaseLiteListener(CBLHTTPConnection.o)
      -[CBL_Router boolQuery:] in CouchbaseLiteListener(CBL_Router.o)
      -[CBL_Router cacheWithEtag:] in CouchbaseLiteListener(CBL_Router.o)
      -[CBL_Router route] in CouchbaseLiteListener(CBL_Router.o)
      -[CBL_Router processRequestRanges] in CouchbaseLiteListener(CBL_Router.o)
      ...

**Comment by pasin** [comment]
I haven't seen any issues building the library. Please make sure that the submodule has been initialized and updated recursively with the following command, and follow the instruction [here](https://github.com/couchbase/couchbase-lite-ios/wiki/Building-Couchbase-Lite).

```
git submodule update --init --recursive
```

**Comment by msanilkumar2020** [comment]
Hi Pasin,

I did new pull request by following below step, still I'm having same issue.
https://github.com/couchbase/couchbase-lite-ios/wiki/Building-Couchbase-Lite

Even download 1.3.1 libraries are not working because of duplicate symbol issue(MYLogging).
/Couch_lib/CouchbaseLite.framework/CouchbaseLite(MYLogging.o)
ld: 13 duplicate symbols for architecture arm64

MYLogging - having reference twice in Myutilities and Blips-Myutilities.

We are blocked to migrate to latest version of CBL.

Thanks,
Anil Kumar

**Comment by msanilkumar2020** [comment]
Still 12th Sep it used to work, we had sync issue and planned to migrate to latest CBL.

**Comment by snej** [comment]
The missing `__asan_...` symbols implies that part of the code is being compiled with the Address Sanitizer enabled, but the target that builds the app doesn't have it enabled so the runtime library support doesn't get linked in. From the list of methods that use those symbols, it looks like the Couchbase Lite Listener static library was built with address sanitizer enabled.

I don't know why `__dictof` and `$equal` would be missing — those are functions defined in Couchbase Lite that are called from the listener.

What schemes/targets are you building?

**Comment by pasin** [comment]
@msanilkumar2020 please make sure that you select 'Continuous iOS' OR 'CI iOS' scheme with 'Generic iOS Device' and then run Product > Archive. I have just tested it with XCode 7.3 (7D175) and I was able to build the binary without any issue.

I haven't heard about the issue with 1.3.1 binary before. Please make sure that you removed the old version of the binary and copied the new over to your project ; Remove the previous link to the frame, re-add the framework to your project, clean and build.
