### ISSUE TITLE
LiveQuery is blocking the main thread on launch until the app crashes (terminated by the OS)

### ISSUE THREAD

**Issue by pahmed** [couchbase/couchbase-lite-ios#1453]
Hi,

I have a problem where the live query blocks the main thread for long time until the watch dog terminates the app, from the back trace is see that the main thread is blocked on `MYReadWriteLock lockForWriting`, i've attached the stack trace for all threads.

NOTES:
- The issue happened many times on iPhone 5, and 5c and on both iOS 8 and iOS 9.
- I use multiple live queries in the app.
- All the created live queries are created on the main thread.
- I noticed this problem starting from CBL 1.3.
- I thought at first that the problem may be because it took some time in indexing, but i noticed the the mapBlock for the query is not invoked at all.

[logs.txt](https://github.com/couchbase/couchbase-lite-ios/files/482761/logs.txt)

--------
* Version:   1.3 and 13.1
* Client OS: iOS 8 and iOS 9

**Comment by snej** [comment]
It's not the query blocking the main thread, it's a call to `-[CBLView setMapBlock:version:]`. This method accesses the database to compare the version with the one saved in the index, but at the time the database is busy running a query on a background thread.

You may be able to work around this by setting up all the map blocks when your app starts up, so you won't need to call that method later while a query is running.

**Comment by pahmed** [comment]
Yeah, this workaround solved the app launch problem, but whenever i access the database after the app launch it locks the database (e.g. if i tried to get document attachment), which causes the app to hang a lot, especially if the CBL is indexing. BTW there is a closed issue #1389 `Allow SQLite reads concurrently with writer`, i guess this should solve my problem. Is this ready for use?, can i cherry-pick this commit to CBL 1.3.1?

**Comment by snej** [comment]
That commit should be safe, although it hasn't been through serious testing yet (just the large but not comprehensive unit test suite) so you'll be a bit of a guinea-pig. Yes, you can easily cherry-pick it to 1.3.1. I would love to hear about how large the benefit is, or of course whether it causes any problems.

**Comment by pahmed** [comment]
I've tried this commit, but the read operations still ask for database lock, e.g. when i try to get `existingDocumentWithID`, a call to `[_fmdb acquireReadLock]` happens which blocks the running thread.

**Comment by snej** [comment]
Did you run `git submodule update`? The real change is in the `fmdb` submodule (the SQLite interface.)

**Comment by pahmed** [comment]
I have did that and tried again, but still it was locking the db, i guess the problem is that the commit `94321 Enable readers concurrently with a writer (assumes WAL mode)` in `fmdb` sets `CONCURRENT_READS 0`. I set it to `1` and now it does not lock the db on read.

**Comment by snej** [comment]
Oh! That was a mistake. I should change `CONCURRENT_READS` to 1 in the repo; thanks for noticing that.

**Comment by snej** [comment]
Fixed on the master branch now.

**Comment by pahmed** [comment]
Good, i'll close the PR i opened then :)
