### ISSUE TITLE
Crash in `-[CBLModel propertiesToSave]` for model objects with a deleted (or otherwise nil) document

### ISSUE THREAD

**Issue by mz2** [couchbase/couchbase-lite-ios#1454]
I noticed a subtle issue with `-propertiesToSave` in CBLModel based on some low level crash reports in my app:

```
- (NSDictionary*) propertiesToSave {
    if (!_document) {
        return [self propertiesToSaveForDeletion];
    }

    NSMutableDictionary* properties = [_document.properties mutableCopy];
    if (!properties)
        properties = [NSMutableDictionary dictionaryWithObject: _document.documentID
                                                        forKey: @"_id"];
    for (NSString* key in _changedNames) {
        id value = _properties[key];
        [properties setValue: [self externalizePropertyValue: value] forKey: key];
    }
    [properties setValue: self.attachmentDataToSave forKey: @"_attachments"];
    return properties;
}
```

… will crash if `-propertiesToSave` is sent to an object that's been deleted but is still referenced as a model object. I will work around this in my client app as well, but it does appear like this scenario could be more specifically handled in CBL rather than crashing due to [NSMutableDictionary dictionaryWithObject:…] being passed a nil. I can think of a few alternatives:

a. Assertion failure with a meaningful error message if calling `-propertiesToSave` on a CBLModel instance with a nil `_document` is illegal.
b. `if (!_document) { return [self propertiesToSaveForDeletion]; }`
c. `if (!_document) { return @{}; }`
d. `if (!_document) { return nil; }`

I don't really know which one of these alternatives would be the most appropriate? Happy to put a PR together if you advise.

---
- Version:   All versions up until current HEAD of master (presently at 66133e2ec76851ed16828f3b05476de0671ced3e)

---
- Version:   All current versions
- Client OS: All supported OS versions

**Comment by snej** [comment]
…Oh, I see. I was confused at first because the source code above includes your workaround (option a) so I couldn't see how the method would crash in this case. But of course the current method doesn't have that test at the top.

Good catch! I agree, it seems like (a) is the best workaround. In your app, in what context does -propertiesToSave` get called for a deleted model?

**Comment by mz2** [comment]
Oops, I indeed forgot the drafted solution there, not the code as it stands.

Re: my app, the reason was related to its undo system, which calls -propertiesToSave to get snapshots of the (potentially unsaved) versions of data to undo / redo, and in certain rare conditions a race condition in code that is supposed to prepare for an undoable deletion was being called for data already deleted. So, my case is not suggesting any particular use for this API call for deleted objects, only really reported it as you probably don't want to crash.

I shall send a PR your way in a moment -->

**Comment by mz2** [comment]
Ah, some confusion on the preferred solution actually: I unhelpfully labelled my solutions a, b, c, c (corrected), and the one I included in code above was labelled b (responding with the deletion). I now realised this won't actually work because _document can of course be nil for a deleted model (`-propertiesToSaveForDeletion` depends on a non-nil _document). Oopsies. I personally would be happy with just reporting a meaningful assertion failure and documenting that one shouldn't call it for a deleted object, as it isn't a terribly meaningful state to be in to have deleted an object, then call this method (as an empty dictionary as a response for instance would communicate a fundamentally different thing than the dictionary that includes _id, _rev, and nil returning would require making a change to the nullability of that API call, causing some pretty pointless hassle and confusion for us who use CBL from Swift).

**Comment by snej** [comment]
Adding an assertion would be fine. Do you want to submit a PR?

**Comment by mz2** [comment]
Sorry, took me ages. PR up now.

**Comment by pasin** [comment]
Close as the PR has been merged.
