### ISSUE TITLE
Feature request: add _bulk_get endpoint to CBL REST API

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-ios#1455]
Please implement: http://developer.couchbase.com/documentation/mobile/1.3/develop/references/couchbase-lite/rest-api/index.html#operation---db--_bulk_get-post

**Comment by snej** [comment]
Definitely a mistake that we didn't implement this for CBL itself when we added it to SG.
Also note that the pull replicator should use bulk_get when the server is CBL.

**Comment by jayahariv** [comment]
Closing 1.x issue!
