### ISSUE TITLE
1.3.1 (Commit 7ec0ec2) does not sync with Server (4.1.0)

### ISSUE THREAD

**Issue by jscubida** [couchbase/couchbase-lite-ios#1458]
We're currently using the framework generated from commit 7ec0ec2 due to compilation issues with 1.3.1. Android counterpart syncs with the server just fine. Downgrading to 1.2 enables syncing for iOS 9 but breaks syncing for iOS 10. 

--------
* Version:    7ec0ec2 (1.3.1)
* Client OS: iOS 9, iOS 10
* Server:      4.1.0-5005, SG: 1.3

**Comment by pasin** [comment]
What is the sync issue? Can you provide more information along with the logs with Sync and SyncVerbose logging enabled?

**Comment by snej** [comment]
You might want to cherry-pick the specific commit(s) you need onto the 1.3.1 tag, instead of building from master.

**Comment by jscubida** [comment]
It looks like an issue with connecting to the server. I'm still working on fixing the configuration file. This thread might have more information if anyone stumbles on this in the future:

https://forums.couchbase.com/t/upgrading-sync-gateway-from-1-2-to-1-3-results-in-fatal-error/10096/10

**Comment by jscubida** [comment]
I'm kicking myself. The issue was with App Transport Security Settings. With Couchbase Lite 1.2, the value of NSExceptionMinimumTLSVersion was TLSv1.2. After upgrading to Couchbase Lite 1.3.1 syncing just stopped working. Changing the value of NSExceptionMinimumTLSVersion to TLSv1.0 fixed everything.

I stumbled upon this [SO Post](http://stackoverflow.com/a/32046052/123890), which suggested the use of 

`nscurl --ats-diagnostics https://example.com`

The output basically clued me into the TLS minimum version:

````
Configuring TLS exceptions with PFS disabled and insecure HTTP allowed for vtfsmpmcouch01.fsm.northwestern.edu

---
TLSv1.2 with PFS disabled and insecure HTTP allowed
2016-09-26 11:36:05.769 nscurl[72079:4238506] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9824)
Result : FAIL
---

---
TLSv1.1 with PFS disabled and insecure HTTP allowed
2016-09-26 11:36:05.828 nscurl[72079:4238506] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9824)
Result : FAIL
---

---
TLSv1.0 with PFS disabled and insecure HTTP allowed
Result : PASS
---
````

**Comment by snej** [comment]
Aha! Makes sense. Yes, `nscurl` is your friend. But you should go nag the server admins to update their SSL … it's pretty clear that over time Apple is ratcheting up the minimum settings they'll accept.
