### ISSUE TITLE
Couldn't build custom private pod "Swift Framework" with Couchbase

### ISSUE THREAD

**Issue by engmsaleh** [couchbase/couchbase-lite-ios#1459]
--------
* Version:   1.3.0
* Client OS: iOS_9.0
* Server:    None

What I'm trying to accomplish is to build a custom swift framework as a private pod which have `CouchbaseLite`.

I have build the `Swift framework` successfully and it build nicely with the following:
I have integrated `CouchbaseLite` as a pod here is my pod file

```
platform :ios, '8.0'

target 'MSTabbarTemplate' do
  use_frameworks!
pod 'PureLayout'
pod 'Eureka'
pod 'StretchHeader'
pod 'ChameleonFramework/Swift'
pod 'Validator'
pod 'SCLAlertView'
pod 'BonMot'
pod 'couchbase-lite-ios'
end
```
 in order to make the `CouchbaseLite` header seen inside my swift framework I have created a folder called `CouchbaseLite` inside my framework folder and added `module.map` file inside as suggested in couchbase forums. the file is as follows:

```
module CouchbaseLite 
{ 
     header "../Pods/couchbase-lite-ios/CouchbaseLite.framework/Headers/CouchbaseLite.h" 
     export * 
}
```  
Import Paths under Swift Compiler – Search Paths in your project settings. Use ${SRCROOT} in the module path (e.g. ${SRCROOT}/CouchbaseLite) 

Currently, If I build the swift framework from Xcode it will build nicely without any problems.
But when I try to make `pod lint` to publish the custom pod for that framework I need up with 

`ERROR | xcodebuild:  MSTabbarTemplate/MSTabbarTemplate/Extensions/CBLDocument.swift:10:8: error: no such module 'CouchbaseLite' `

**Comment by pasin** [comment]
Swift Framework requires dynamic framework to work with. CBL is still built as a static library framework in order to support iOS < 8. Meanwhile, the only choice now is to use Carthage to build the binary or build the framework yourself with XCode.

**Comment by pasin** [comment]
Closed as the issue will be fixed after https://github.com/couchbase/couchbase-lite-ios/issues/1474 is done.
