### ISSUE TITLE
Carthage build failed

### ISSUE THREAD

**Issue by bernhardwaidacher** [couchbase/couchbase-lite-ios#1460]
--------
* Version:   1.3.2
* Client OS: macOS Sierra, 10.12.1 Beta (16B2327e)

I tried to build couchbase lite for macOS with Carthage with this line:
`github "couchbase/couchbase-lite-ios" "release/1.3.2"`

I get this error:
```
*** Building scheme "CBL Mac" in CouchbaseLite.xcodeproj
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/Bernhard1/Library/Developer/Xcode/DerivedData/CouchbaseLite-cwaroowasviusxftmmlieupherjf/Build/Intermediates/CouchbaseLite.build/Release/CBL\ Mac\ library.build/Objects-normal-asan/x86_64/MYAnonymousIdentity.o vendor/MYUtilities/MYAnonymousIdentity.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
/Users/Bernhard1/Library/Mobile Documents/com~apple~CloudDocs/Ausgaben4/Ausgaben4/Carthage/Checkouts/couchbase-lite-ios/vendor/MYUtilities/MYAnonymousIdentity.m:146:5: error: ignoring return value of function declared with warn_unused_result attribute [-Werror,-Wunused-result]
A shell task (/usr/bin/xcrun xcodebuild -project /Users/Bernhard1/Library/Mobile Documents/com~apple~CloudDocs/Ausgaben4/Ausgaben4/Carthage/Checkouts/couchbase-lite-ios/CouchbaseLite.xcodeproj -scheme CBL Mac -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/Bernhard1/Library/Developer/Xcode/DerivedData/CouchbaseLite-cwaroowasviusxftmmlieupherjf/Build/Intermediates/CouchbaseLite.build/Release/CBL\ Mac\ library.build/Objects-normal-asan/x86_64/MYAnonymousIdentity.o vendor/MYUtilities/MYAnonymousIdentity.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

I've included the xcodebuild log

[carthage-xcodebuild.PaFj9N.log.zip](https://github.com/couchbase/couchbase-lite-ios/files/492425/carthage-xcodebuild.PaFj9N.log.zip)

**Comment by snej** [comment]
Only the master branch has been updated for Xcode 8 compatibility. If you want to build 1.3.2 you'll need to use Xcode 7, or else fix the couple of very minor errors like the one above — all you have to do is insert `(void)` in front of calls to `SecRandomCopyBytes`.

**Comment by pasin** [comment]
I have just cherry-picked XCode8 compatibility fixed from master to 1.3.2. Those fixes shouldn't add any risks to the current 1.3.2 code base.

**Comment by bernhardwaidacher** [comment]
Thank you!
Using master branch, I'm still not able to build it with carthage. Neither am I when using 1.3.2

Getting this error.
```

** BUILD FAILED **


The following build commands failed:
	Ld /Users/Bernhard1/Library/Developer/Xcode/DerivedData/CouchbaseLite-cwaroowasviusxftmmlieupherjf/Build/Products/Release-sqlcipher/CouchbaseLite.framework/Versions/A/CouchbaseLite normal x86_64
(1 failure)
ld: warning: ignoring undefined symbol .objc_class_name_CBLUITableSource from -exported_symbols_list
ld: warning: ignoring undefined symbol .objc_class_name_CBLUITableSource from -exported_symbols_list
ld: warning: ignoring undefined symbol .objc_class_name_CBLUITableSource from -exported_symbols_list
ld: warning: ignoring undefined symbol .objc_class_name_CBLUITableSource from -exported_symbols_list
clang: error: linker command failed with exit code 1 (use -v to see invocation)
A shell task (/usr/bin/xcrun xcodebuild -project /Users/Bernhard1/Library/Mobile Documents/com~apple~CloudDocs/Ausgaben4/Ausgaben4/Carthage/Checkouts/couchbase-lite-ios/CouchbaseLite.xcodeproj -scheme CI MacOS -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	Ld /Users/Bernhard1/Library/Developer/Xcode/DerivedData/CouchbaseLite-cwaroowasviusxftmmlieupherjf/Build/Products/Release-sqlcipher/CouchbaseLite.framework/Versions/A/CouchbaseLite normal x86_64
(1 failure)
```

**Comment by snej** [comment]
The only issues listed there are warnings, which shouldn't be fatal. You may have to scroll back to find the actual error from that `ld` command.

**Comment by bernhardwaidacher** [comment]
ok, this is the whole terminal output + log 

Bernhards-MacBook-Pro:Ausgaben4 Bernhard1$ carthage update --platform mac
*** Fetching couchbase-lite-ios
*** Checking out couchbase-lite-ios at "0c72291eb1e6b533e577189d0f12977b9ba500b9"
*** xcodebuild output can be found in /var/folders/fr/n4k31bpd599gmx6vxrfvtr8r0000gp/T/carthage-xcodebuild.Uud8uy.log
*** Building scheme "CI MacOS" in CouchbaseLite.xcodeproj
** BUILD FAILED **


The following build commands failed:
	Ld /Users/Bernhard1/Library/Developer/Xcode/DerivedData/CouchbaseLite-cwaroowasviusxftmmlieupherjf/Build/Products/Release-sqlcipher/CouchbaseLite.framework/Versions/A/CouchbaseLite normal x86_64
(1 failure)
ld: warning: ignoring undefined symbol .objc_class_name_CBLUITableSource from -exported_symbols_list
ld: warning: ignoring undefined symbol .objc_class_name_CBLUITableSource from -exported_symbols_list
clang: error: linker command failed with exit code 1 (use -v to see invocation)
A shell task (/usr/bin/xcrun xcodebuild -project /Users/Bernhard1/Library/Mobile Documents/com~apple~CloudDocs/Ausgaben4/Ausgaben4/Carthage/Checkouts/couchbase-lite-ios/CouchbaseLite.xcodeproj -scheme CI MacOS -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	Ld /Users/Bernhard1/Library/Developer/Xcode/DerivedData/CouchbaseLite-cwaroowasviusxftmmlieupherjf/Build/Products/Release-sqlcipher/CouchbaseLite.framework/Versions/A/CouchbaseLite normal x86_64
(1 failure)

[carthage-xcodebuild.Uud8uy.log.zip](https://github.com/couchbase/couchbase-lite-ios/files/504824/carthage-xcodebuild.Uud8uy.log.zip)

**Comment by snej** [comment]
Carthage doesn't show the entire build log by default. There's a command-line option to enable that.

**Comment by zygoat** [comment]
Carthage still fails to build Couchbase Lite 1.4.0.
