### ISSUE TITLE
Memory leak caused by ref cycle between replicator and CBLRemoteSession

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1467]
Geoffrey Wiseman [pointed out](https://forums.couchbase.com/t/couchbase-lite-ios-2-node-cycle-in-memory-debugger/10141) a reference cycle between CBLRESTReplicator and CBLRemoteSession. I confirmed that this will cause a memory leak: the replicator calls `close` on the session when it stops, but neither object clears the reference to the other.

The fix is either to have the objects clear their references on close, and/or to make the session's reference (`_requestDelegate`) weak.

(Fortunately this leak isn't very significant since apps don't create large numbers of replications.)

**Comment by vmilea** [comment]
Perhaps related, some of the blocks in `CBLRestPuller.m` are unwillingly capturing strong references.

- in `downloadAttachment` with `[self addToWaitingAttachments: task]`
- in `pullBulkRevisions` with `LogTo` / `Warn`

**Comment by snej** [comment]
Fixed by 930aa634648aa00d69bbd71f60e5a359bf3fe358
