### ISSUE TITLE
linker issue in compiling CBL version 1.3.1

### ISSUE THREAD

**Issue by msanilkumar2020** [couchbase/couchbase-lite-ios#1468]
--------
* Version:   1.3.1
* Client OS: Xcode 8 , iOS 10

Hi,

We are getting below linker errors tried using both pod and also directly adding framework.

duplicate symbol _AllLogDomains in:
    /Volumes/Data/crashes/Kodiak_iOS_PoC_Client_7_10_CouchBase/Product/HTMLPoCClient/iOS_POC_Client/InstaPoC/Pods/couchbase-lite-ios/CouchbaseLite.framework/CouchbaseLite(MYLogging.o)
duplicate symbol _AlwaysLog in:
    /Volumes/Data/crashes/Kodiak_iOS_PoC_Client_7_10_CouchBase/Product/HTMLPoCClient/iOS_POC_Client/InstaPoC/Pods/couchbase-lite-ios/CouchbaseLite.framework/CouchbaseLite(MYLogging.o)
duplicate symbol _EnableLog in:
    /Volumes/Data/crashes/Kodiak_iOS_PoC_Client_7_10_CouchBase/Product/HTMLPoCClient/iOS_POC_Client/InstaPoC/Pods/couchbase-lite-ios/CouchbaseLite.framework/CouchbaseLite(MYLogging.o)
duplicate symbol _EnableLogTo in:
    /Volumes/Data/crashes/Kodiak_iOS_PoC_Client_7_10_CouchBase/Product/HTMLPoCClient/iOS_POC_Client/InstaPoC/Pods/couchbase-lite-ios/CouchbaseLite.framework/CouchbaseLite(MYLogging.o)
duplicate symbol _MYDefault_LogDomain in:
    /Volumes/Data/crashes/Kodiak_iOS_PoC_Client_7_10_CouchBase/Product/HTMLPoCClient/iOS_POC_Client/InstaPoC/Pods/couchbase-lite-ios/CouchbaseLite.framework/CouchbaseLite(MYLogging.o)
duplicate symbol _MYLogTo in:
    /Volumes/Data/crashes/Kodiak_iOS_PoC_Client_7_10_CouchBase/Product/HTMLPoCClient/iOS_POC_Client/InstaPoC/Pods/couchbase-lite-ios/CouchbaseLite.framework/CouchbaseLite(MYLogging.o)
duplicate symbol _MYLoggingCallback in:
    /Volumes/Data/crashes/Kodiak_iOS_PoC_Client_7_10_CouchBase/Product/HTMLPoCClient/iOS_POC_Client/InstaPoC/Pods/couchbase-lite-ios/CouchbaseLite.framework/CouchbaseLite(MYLogging.o)
duplicate symbol _MYWarn in:
    /Volumes/Data/crashes/Kodiak_iOS_PoC_Client_7_10_CouchBase/Product/HTMLPoCClient/iOS_POC_Client/InstaPoC/Pods/couchbase-lite-ios/CouchbaseLite.framework/CouchbaseLite(MYLogging.o)
duplicate symbol __WillLogTo in:
    /Volumes/Data/crashes/Kodiak_iOS_PoC_Client_7_10_CouchBase/Product/HTMLPoCClient/iOS_POC_Client/InstaPoC/Pods/couchbase-lite-ios/CouchbaseLite.framework/CouchbaseLite(MYLogging.o)
duplicate symbol _gMYLogDomainList in:
    /Volumes/Data/crashes/Kodiak_iOS_PoC_Client_7_10_CouchBase/Product/HTMLPoCClient/iOS_POC_Client/InstaPoC/Pods/couchbase-lite-ios/CouchbaseLite.framework/CouchbaseLite(MYLogging.o)
duplicate symbol _gMYWarnRaisesException in:
    /Volumes/Data/crashes/Kodiak_iOS_PoC_Client_7_10_CouchBase/Product/HTMLPoCClient/iOS_POC_Client/InstaPoC/Pods/couchbase-lite-ios/CouchbaseLite.framework/CouchbaseLite(MYLogging.o)
ld: 11 duplicate symbols for architecture arm64

looks like MYLogging is available twice in project, if we uncheck one place i mean Blip it is working. But i don't want branch code, can we have same in released framework.

This issue is similar to https://forums.couchbase.com/t/problem-compiling-with-new-ios-couchbaselite-v1-3/9423

Thanks,
Anil Kumar

**Comment by trramsiq** [comment]
Same here!

Xcode 8 iOS 10
pod 1.3.1

BridgingHeader.h:

`#import <CouchbaseLite/CouchbaseLite.h>`

```
duplicate symbol _AllLogDomains in:
    /myPath/Pods/couchbase-lite-ios/CouchbaseLite.framework/CouchbaseLite(MYLogging.o)
duplicate symbol _AlwaysLog in:
    /myPath/Pods/couchbase-lite-ios/CouchbaseLite.framework/CouchbaseLite(MYLogging.o)
duplicate symbol _EnableLog in:
    /myPath/Pods/couchbase-lite-ios/CouchbaseLite.framework/CouchbaseLite(MYLogging.o)
duplicate symbol _EnableLogTo in:
    /myPath/Pods/couchbase-lite-ios/CouchbaseLite.framework/CouchbaseLite(MYLogging.o)
duplicate symbol _MYDefault_LogDomain in:
    /myPath/Pods/couchbase-lite-ios/CouchbaseLite.framework/CouchbaseLite(MYLogging.o)
duplicate symbol _MYLogTo in:
    /myPath/Pods/couchbase-lite-ios/CouchbaseLite.framework/CouchbaseLite(MYLogging.o)
duplicate symbol _MYLoggingCallback in:
    /myPath/Pods/couchbase-lite-ios/CouchbaseLite.framework/CouchbaseLite(MYLogging.o)
duplicate symbol _MYWarn in:
    /myPath/Pods/couchbase-lite-ios/CouchbaseLite.framework/CouchbaseLite(MYLogging.o)
duplicate symbol __WillLogTo in:
    /myPath/Pods/couchbase-lite-ios/CouchbaseLite.framework/CouchbaseLite(MYLogging.o)
duplicate symbol _gMYLogDomainList in:
    /myPath/Pods/couchbase-lite-ios/CouchbaseLite.framework/CouchbaseLite(MYLogging.o)
duplicate symbol _gMYWarnRaisesException in:
    /myPath/Pods/couchbase-lite-ios/CouchbaseLite.framework/CouchbaseLite(MYLogging.o)
ld: 11 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jordanpwood** [comment]
I'll put a "me too!" in, I just tried to update my project from Couchbase 1.2.1 to 1.3.1, and the new version gave me the same errors.  FYI, I'm using cocoapods and Xcode 8.

**Comment by snej** [comment]
Well, this is weird. I wonder why we haven't seen this? It doesn't happen when building our iOS tests or sample apps.

There was a similar issue that was a result of using the `-all_load` linker flag — apparently if this flag isn't used, the linker will realize that one of the copies of MYLogging.o is redundant and dead-strip it. IIRC that flag was not explicitly set by the developer but was added by CocoaPods somehow.

Are all 3 of you sure you're not somehow building with `-all_load`?

**Comment by jordanpwood** [comment]
I was building with `-all_load`!  I'm not sure why it was set, I can build my app without it.  I have a bunch of tests which use Couchbase which are failing, but I'm pretty sure its unrelated to the build problems.  I'll open a separate issue if I can't figure it out.

**Comment by msanilkumar2020** [comment]
@snej, i am sure -all_load is removed from other linker flags, any how we already have two references of MYLogging classes, can you remove one reference in next release?

Thanks,
Anil Kumar

**Comment by snej** [comment]
The fix has been checked in. I don't know how you can be getting the error without`-all_load`, since otherwise the linker will detect that one of the two identical `.o` files isn't necessary and will dead-strip it. So I can't think of a good workaround.

**Comment by pasin** [comment]
This is fixed in https://github.com/couchbase/couchbase-lite-ios/commit/7ec0ec2342964d03a00dbc6deaa4bfb206e4b50c.
