### ISSUE TITLE
Give up iOS 7 compatibility, eliminate static framework

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1474]
If we eliminate support for iOS 7 we can switch to building a true dynamically-linked framework. (Support for dynamic linking was added in iOS 8.0.) This will save us and our developers from the many problems involved in distributing a static library, which have caused probably dozens of issues in the past and taken up man-weeks of development time.

Also, a dynamic framework is already needed by developers whose apps include extensions like Today widgets or Apple Watch apps, because the extensions are separate binaries that would also need to link with CBL.

We already have a target that builds the dynamic framework; it's just not part of our Jenkins builds. So the switch-over would be easy from a development and build standpoint, though it would take more effort for QA, docs and sample code.

The [current estimates of iOS usage by version](https://mixpanel.com/trends/#report/ios_frag) indicate only 1.4% of devices still on iOS 7 (as of Oct 1 2016).

**Comment by marcblanchet** [comment]
+1

**Comment by brendand** [comment]
+1

**Comment by jordanpwood** [comment]
+1

**Comment by toddfreese** [comment]
+1

**Comment by Cyclic** [comment]
It will help if it has a module.map file too, so that we can include it in Swift projects that are Frameworks #1459 ...

**Comment by snej** [comment]
In the absence of hard data about all of our users/customers, we'll move forward and switch to iOS 8.0 as our minimum. We don't think we have to change our project settings much, since we already build both static and dynamic frameworks. We will transition to have our CI system build the dynamic framework instead of the static, and testing that framework.

We'll also update the minimum-OS-required build constant to iOS 8.

We also need to update documentation (ReadMe, tutorials, sample app readmes, etc.) to reflect any differences in setup.

**Comment by pasin** [comment]
Plus another task that we also need to make changes to https://github.com/couchbaselabs/Couchbase-Lite-PhoneGap-Plugin.

**Comment by jordanpwood** [comment]
I'm wondering, what's the status on this issue?  I'd love to try out a dynamically linked version of Couchbase Lite!

**Comment by snej** [comment]
You already can, if you want to build it yourself… Just check out the code, open the Xcode project and build the "CBL iOS Framework" scheme.

**Comment by jordanpwood** [comment]
I can build the "Continuous iOS" scheme, but when I try to build "CBL iOS Framework" I get:

>None of your accounts are a member of 'N2Q372V7W2':  An unexpected error occurred. Xcode cannot find a team matching 'N2Q372V7W2'.
No signing certificate "iOS Development" found:  No "iOS Development" signing certificate matching team ID "N2Q372V7W2" with a private key was found.

**Comment by djpongh** [comment]
done
