### ISSUE TITLE
CBLRestPuller Assert crash on iOS 10

### ISSUE THREAD

**Issue by pradipvaghasiya** [couchbase/couchbase-lite-ios#1476]
Hello,
I am attaching crash image here. Not sure when this really happens but happens on iOS 10. Any idea about this? If you can suggest how can I reproduce or what may be causing this I will investigate further and provide details.

<img width="626" alt="screen shot 2016-10-03 at 7 41 38 pm" src="https://cloud.githubusercontent.com/assets/1885940/19040471/cff98a02-89a1-11e6-919d-9d5713d5b60c.png">

--------
* Version:   1.3.1
* Client OS: iOS 10
* Server: Sync Gateway   1.3.1

**Comment by snej** [comment]
Dup of [#794](https://github.com/couchbase/couchbase-lite-ios/issues/794#issuecomment-241831450), looks like.
