### ISSUE TITLE
_changes on local DB stops working on IOS10

### ISSUE THREAD

**Issue by Crapulax** [couchbase/couchbase-lite-ios#1477]
When deplyoing our couchbase phonegap lite 1.3.1 app on **IOS 10**, the _changes listener on the App **local** DB stops working once new changes are loaded. On all other platforms IOS/Android it works just fine.

The replication with the sync gateway <-> local DB is working fine, documents are flowing in both directions. When a doc is received by the App, it is stored locally as we can get it from a query for instance. But the poller of the local DB is not triggered.... It is triggered at startup but stops working shortly after. There are no error message in java script on the the $http request.

We are going to investigate further the issue. But is someone facing a similar issue?

--------
* Version:   1.3.1
* Client OS: IOS 10
* Server:    1.3.1

**Comment by Crapulax** [comment]
This isssue is Critical!
I have workarounded it by setting an http timeout of 58s and reinstalling the listener on each timeout.
When app starts the listener works for exactly 60s (I guess there is an internal timeout or heartbeat). Afterward, nothing is returned from the http request (probaly it crashed behind the scene).

What I did is:

       var poller = function (databaseUrl, databaseName, cseq) {
                    if (!cancelFlag) {
                        var params = {
                            ...
                        };
                        **params.timeout = 58000;**

                        $http(params).then(
                            function (result) {
                                if (!cancelFlag) { // cancel was requested, discard current msg
                                    $rootScope.$broadcast('couchbase:change', result.data);
                                    cseq = result.data.last_seq;
                                    setTimeout(function () {
                                        poller(databaseUrl, databaseName, cseq);
                                    }, 10);
                                } else {
                                    console.log('listen effectively cancelled');
                                }
                            }, function (error) {
                                if (!cancelFlag) {
                                    **setTimeout(function () {
                                        poller(databaseUrl, databaseName, cseq);
                                    }, 10);**

**Comment by Crapulax** [comment]
No feedback am I the only one to face this issue?
Either I have an issue in my code and then yes this is my issue or it does not work on IOS10 and this should trigger some interest...

**Comment by snej** [comment]
What exactly is the HTTP request you're sending? (I mean the URL and headers, not the JS code.)

**Comment by snej** [comment]
CBL for iOS doesn't even support a `timeout` parameter for `_changes` requests — I think there's an open issue to add support, but the current code does not check that URL parameter at all, and there's nothing that cancels the request after some time has elapsed. The string `timeout` literally does not appear at all in the source code for the HTTP router and changes-feed implementation.

I have no idea where the timeout is coming from (WebKit?) or why the behavior changes when you add `?timeout=58` to your URL parameters.

**Comment by Crapulax** [comment]
Hello Jens,

Thanks for your feedback. The timeout (params.timeout) is passed to the http handler not to the replication itself. This is a workaround we are using to reinstantiate the _changes before it ends. The issue we have with IOS10 is that the http requests stops silently working after exactly 60s. BUT we have no return in error or whatsoever. This is why we cancel it before failure and restart it. Doing so the app works fine.

Although I have no evidence of it we have plenty of $http requests in our code and this the only one (identified at least) with such behavior. I will provide you with params passed and inspector of the http request tomorrow. I will also makes some research in Angular's forums to see if people raised some issues with $http/IOS10. 
Note that the exact same code works on all platforms IOS / Android but IOS10.

Brgds,
Steve.

**Comment by snej** [comment]
It really does sound like a change in WebKit, then. It's been years since I used XHR, but is there a way to explicitly set a timeout on it? (Or is that what you're using already?)

One thing to try is to add `?heartbeat=50000` to the URL — this will cause CBL to write some no-op data like a newline to the response every 50 seconds. If WebKit is closing the request because it thinks the connection is idle, this might fix it.

**Comment by msanilkumar2020** [comment]
Snej, we are also same issue.

Puller replication works fine but it is unable to provide the data to UI through rest APi's.

For us heartbeat is set to 300000.

Data is available but unable to get it through REST apis

Thanks,
Anil Kumar

**Comment by msanilkumar2020** [comment]
Even i changed timeout to less value 30000, still we have same issue.

**Comment by Crapulax** [comment]
The timeout you are talking is at the http level? Or you are in fact referring to the heartbeat? If you refer to heartbeat may be test with 20000. Often heartbeat algorithm wait for 2 x heartbeat before breaking which with 30s would mean 60s.

We were able to workaround it by setting http header params timeout to 40s(40000ms). This is not related to a param passed to the replication itself. 

extract from https://docs.angularjs.org/api/ng/service/$http#usage
timeout – {number|Promise} – timeout in milliseconds, or promise that should abort the request when resolved.

When the timeout is reached on http request, we catch the error and reinstall the listen on _changes.

Jens,

The params to the _changes http request:
var params = {
                            method: 'GET',
                            url: databaseUrl + databaseName + '/_changes',
                            params: {feed: 'longpoll', since: cseq, include_docs: true},
                            withCredentials: false
                        };

                        params.timeout = 40000;

                        $http(params).then(

**Comment by pasin** [comment]
@sethrosetter do we have a functional test that covers this case? The test might require to be in the IDLE state (no changes) for at least 60 seconds and see if the longpoll _changes  still works.

**Comment by sethrosetter** [comment]
@pasin. I don't believe we have one but it should be pretty trivial to write. Can you file an issue with the scenario steps to https://github.com/couchbaselabs/mobile-testkit

**Comment by pasin** [comment]
@Crapulax setting heartbeat to _changes feed request to anything less than 60 seconds doesn't work?

**Comment by Crapulax** [comment]
@pasin,

I have not checked yet, will try to find time tomorrow to verify. I keep you updated.

**Comment by snej** [comment]
@Crapulax: Is there a way you can show the settings of the actual XMLHTTPRequest object that gets run? I've never used Angular and I have no idea what sort of things it does with its input to generate the request.

**Comment by snej** [comment]
I just tried running LiteServ and querying with `curl ':59840/db/_changes?feed=longpoll'` ... it never times out. The `curl` command just keeps waiting and waiting for minutes. (This is on macOS 10.12, not iOS 10, but the OS's are pretty similar at this level.)

**Comment by msanilkumar2020** [comment]
@snej, this issue is occurring only in iOS 10 not in other devices/os version.

**Comment by npomfret** [comment]
I don't know if it's helpful, but I have a react-native app thats uses the `_changes` feed and t's working fine on iOS 10.  It uses the 'fetch' api.

**Comment by snej** [comment]
I think we should move this issue to the CBL PhoneGap plugin repo, since it sounds like it's at that level, not CBL itself. We may need a workaround for changed(?) WebKit XHR behavior in iOS 10.

**Comment by pasin** [comment]
Moved the issue to https://github.com/couchbaselabs/Couchbase-Lite-PhoneGap-Plugin/issues/86.
