### ISSUE TITLE
Deleted docs are not replicated on other clients

### ISSUE THREAD

**Issue by pradipvaghasiya** [couchbase/couchbase-lite-ios#1483]
When I delete a document using Couchbase Lite iOS 1.3.1 app. Other iOS and Android clients still see that document even though document is deleted from database. This is only happening only for one kind of document and others work.

Scenario:
Event doc is put into channels  "channel", "channel-data", "channel-owners" (here channel is unique id for that event)  (channel and channel-data is open to all users. GUEST accessible)
Photos related to that event also put on above channel, When particular photo gets deleted it syncs with other clients well. All fine 
When User deletes the event entirely all documents from all channels are deleted however in this case Neither Event nor photos inside it are replicated into other clients (including Android and iOS) All clients still have event and images in it. They are not being deleted.

All clients are pulling event docs using  "channel-data" channel which are accessible for all.

Sample event doc is attached after deletion.
[-UWk-Xq6kcilt1YDtDm5XYt.txt](https://github.com/couchbase/couchbase-lite-ios/files/519268/-UWk-Xq6kcilt1YDtDm5XYt.txt)

--------
* Version:   1.3.1
* Client OS: iOS 10, Android Kitkat
* Server:    Sync Gateway 1.3.1

**Comment by pasin** [comment]
I understand that the issue you are encountering is related to the following issues that have been fixed on the SGW side. Could you please check if it's related to your issue or not? If not, we can reopen the issue. Thanks.

https://github.com/couchbaselabs/ToDoLite-iOS/issues/54
https://github.com/couchbase/sync_gateway/issues/1484
https://github.com/couchbase/sync_gateway/issues/2005
