### ISSUE TITLE
Pull Replication filterParams not working

### ISSUE THREAD

**Issue by ch0eb1t** [couchbase/couchbase-lite-ios#1484]
Is filterParams broken?
Used to be able to do:
pull.filterParams = @{@"username":@"myusername", @"style":@"main_only"};

But now CBL doesn't send the filter param to server.

--------
* Version:   1.3.1
* Client OS: iOS 9 - 10
* Server:    CouchDB 1.6.1

**Comment by snej** [comment]
https://github.com/couchbase/couchbase-lite-ios/issues/1139#issuecomment-240423530

**Comment by ch0eb1t** [comment]
The fixed code have a condition of _usePOST = false for filterParams to be parse into URL.
Is there any way I can set _usePOST to false without changing the source code?

protogrid mentioned changing the _usePOST variable https://github.com/couchbase/couchbase-lite-ios/issues/1139#issuecomment-228069144
But not sure he/she changed it via source code or from public api.

**Comment by snej** [comment]
There's no API for that; you'd have to change the source code.
