### ISSUE TITLE
Push replication retry interval

### ISSUE THREAD

**Issue by lucatorella** [couchbase/couchbase-lite-ios#1485]
I was trying to find out what's triggering the push replication to start syncing. I searched in the documentation but I found out nothing specific, and then I checked the code briefly.

Is it correct to say that a push replication starts when one of these events happen:
- any db change (update/deletion/insertion)
- retries after 2 secs from previous failure, then it doubles the interval every failure till it reaches 10 mins, then it will retry every 10 mins
- when the internet connection state changes
- app goes to the foreground 

I think this information it's rather important and should be added to the documentation.

Also are iOS and Android consistent?

--------
* Version: 1.3.1
* Client OS: iOS Any

**Comment by djpongh** [comment]
Closing as this is really a dup of issue #1326

**Comment by snej** [comment]
This shouldn't need documentation, since it should behave as you'd expect :) Unfortunately it doesn't today.

Currently the unintuitive part is the bug that a pending retry timeout can delay the reconnect attempt — that's 1326. Once we fix that, it should behave intuitively.

**Comment by lucatorella** [comment]
I am asking because I'm receiving some complaints by some customers who were using the app and creating/changing some documents when the connection was low/no existent for a few hours. 
Then they moved for a couple of hours in another zone with decent internet coverage and, while other http requests not related to the database went through, the documents changes weren't pushed. This is a serious issue, so I'm trying to figure out how often couchbase lite retries to push the changes, and in case is not good for my use case, I have to force push according to my needs.
