### ISSUE TITLE
Sometimes No database query works for iOS

### ISSUE THREAD

**Issue by pradipvaghasiya** [couchbase/couchbase-lite-ios#1491]
I am using Couchbase lite iOS app with SQLite database. Everything works fine normally. But sometimes when app comes from suspended background session or background (not sure) No query works. Can not debug this as this never happened during development.

All pages on all type of queries returns no result. In my app this can happen when
1. CBLQuery object not generated
2. Query object returns empty results

When I kill the app and run again everything works fine.

I also use continuous replication in background mode (by marking suspended no) when silent notification arrives. May be this is not relevant but just putting as FYI.

I know this is very limited information so can you please help me when this can happen and how should I go to debug it? This happens once in a while (Lets say once in 25-30 app sessions)

---
- Version:   Couchbase lite 1.3.1
- Client OS: iOS 10
- Server:    Sync Gateway 1.3.1

**Comment by pasin** [comment]
Can you enabling some logging as below? We may be able to see what's going on from the log?

```Swift
CBLManager.enableLogging("Database")
CBLManager.enableLogging("View")
CBLManager.enableLogging("ViewVerbose")
CBLManager.enableLogging("Query")
```

**Comment by pradipvaghasiya** [comment]
Thanks for you reply. This does not happen in my testing when phone is connected to Xcode. It happens when I keep app for 1 - 2 days in phone and when iOS decides to suspend the app in background (again not sure). So logging wont help. 

All screens display nothing even when database has the data. It may be possible that this issue is not related to Query itself. The common observation is it does not work in one particular app session meaning all views and queries do not work for that app session. so I am suspecting it is database level issue rather than one particular query or view related. 

Is it possible in any rare scenario that database itself does not open? I have NOT handled error in below statement? I should keep fatalerror if below fails. 
`try manager.databaseNamed(kDatabaseName)`

I use singleton for database object and all next steps (i.e. Query, view creation etc) I use swift optional object so everywhere else it does not crash.

Please note when I kill the app all views and queries work just fine so there is not for sure an issue in business logic of reading data from database.

**Comment by pasin** [comment]
> Is it possible in any rare scenario that database itself does not open? I have NOT handled error in below statement? I should keep fatalerror if below fails. 
try manager.databaseNamed(kDatabaseName)

Do you have a feature to launch or wake the app in the background / lock screen from a Notification or Location change? If that's the case, the database may not have a permission to read/write data due to the set file protection level, and creating a CBLManager with the right file protection level set in CBLManagerOptions should solve the issue.

**Comment by pradipvaghasiya** [comment]
Yes I do have a feature of silent notification which wakes up app and fetches new data from server. but that too works normally. 

If it is related to file protection then no background fetch should work right?

OR Does this file protection level comes into picture only when app is suspended in background or device is locked or something? 

If thats the case then I will still try to set the file protection option and try to reproduce the issue in next few days.

Can you confirm if flag NSDataWritingFileProtectionCompleteUntilFirstUserAuthentication is set to false works? Got info from this link 
https://groups.google.com/forum/#!topic/mobile-couchbase/X9TIHtNTf1Y

Currently In background notification, I am doing below
`        ContinuousReplication.sharedInstance.replication?.suspended = false
        ContinuousReplication.sharedInstance.addPullChannel(eventDataChannel)

//When idle set suspended back to true.
`

**Comment by pasin** [comment]
> Can you confirm if flag NSDataWritingFileProtectionCompleteUntilFirstUserAuthentication is set to false works? Got info from this link 
https://groups.google.com/forum/#!topic/mobile-couchbase/X9TIHtNTf1Y

Let me correct your quote a bit. From the link above, it doesn't set NSDataWritingFileProtectionCompleteUntilFirstUserAuthentication to false, but It set file protection level to `NSDataWritingFileProtectionCompleteUntilFirstUserAuthentication' and set readOnly to false. The settings should make the database accessible in the background including the lock screen.

For Swift syntax, you may try something like this
```
var options = CBLManagerOptions(readOnly: false, fileProtection: NSData.WritingOptions.completeFileProtectionUntilFirstUserAuthentication)
let manager = try? CBLManager(directory: CBLManager.defaultDirectory(), options: UnsafeMutablePointer(&options))
```

Please try and see if that works. Thanks.

**Comment by pasin** [comment]
@pradipvaghasiya does setting the file protection level solve your issue?

**Comment by pradipvaghasiya** [comment]
I have temporarily disabled silent push notification from server and not found the issue again. So I think it was causing the issue. In the next release I will try with file protection. So you can close this issue for now. I will also comment if file protection will work.

**Comment by npomfret** [comment]
I have the same issue. And I agree that its unfortunately impossible to reproduce reliably.  What I've learned so far is that the OS will arbitrarily 'suspend' an application that's running in the background.  And after a while it will _purge_ suspended apps to free up memory (this means your app gets killed completely).  If the OS chooses to kill your app in this way it will also restart it for you should something like a push notification arrive with the `content-available=1` flag set.  But now your app is starting in the background, which seems to be very different to it being started by the user clicking on the app icon.  

In this situation i've found that CBL refuses to start correctly, at least sometimes - but possibly not always (it's so difficult to tell what's going on).  I use the REST API only, and the only response if get back from it is a "database error" with status code 500. I'm currently starting my database like so:

```
        CBLManagerOptions options = {NO, NSDataWritingFileProtectionCompleteUntilFirstUserAuthentication};
        NSError* error;
        manager = [[CBLManager alloc] initWithDirectory: [CBLManager defaultDirectory]
                                                        options: &options error: &error];
```

...which I think is effectively the same as @pasin suggested above(?).  If so, I can confirm that this isn't the solution.  What would really help is a better error message.  If someone could do a nightly build that added some more detail other than 'database error' I'd be happy to try it.

**Comment by pasin** [comment]
`NSDataWritingFileProtectionCompleteUntilFirstUserAuthentication` means that the file is encrypted and inaccessible until after the device has booted and the user has unlocked it once. Is it possible that the issue happens after the device got restarted and has never been unlocked once?

Also can you enable some logging in Couchbase Lite especially with `Database` and `Router` to see what operation causes the issue?

> There are other options, like NSDataWritingFileProtectionNone - should I try this?

It depends, but you could try.

> Also, if a CBL database already existed on a phone before I changed my app to use NSDataWritingFileProtectionCompleteUntilFirstUserAuthentication, would changing this have any effect? Or would they need to delete and start again?

NO, there is no need to delete the database.

**Comment by npomfret** [comment]
It happens too regularly to be related to the device being re-booted.  People just don't reboot their phones that often.  That said, it never seems to happen on my personal device.  I can't re-create the situation at all.  I just get some crash reports sent to my server sometimes when the app is having trouble starting.  

I don't currently have the ability to capture the couchbase logs on a central server, so upping the log levels won't help until I solve that problem.

Can you add some code to give a better error message?  Currently I just get "database error", nothing else.

**Comment by pasin** [comment]
@npomfret I could spin up a quick branch to differentiate different types of the database errors for you to try out. What couchbase-lite-ios version are you using?

**Comment by npomfret** [comment]
thanks - http://latestbuilds.hq.couchbase.com/couchbase-lite-ios/1.3.2/ios/1.3.2-6/

**Comment by pasin** [comment]
Copied from @snej's comment on the [forum](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/mobile-couchbase/gyuXLuUGLlM/ET_lv4HWBgAJ),

>Looking at the code, this setting only takes effect when the CBLManager’s root directory is created. (See CBLManager.m:220.) That would explain what you’re seeing.

> You can change the mode of an existing installed app by using NSFileManager to set the NSFileProtectionKey attribute of the CBLManager's directory. I think setting it on the top-level directory is enough, because that attribute is inherited by subdirectories and files.

**Comment by snej** [comment]
I'm posting a question to the cocoa-dev mailing list.

**Comment by snej** [comment]
BTW, isn't this a dup of one or more of the open issues regarding file protection?
