### ISSUE TITLE
CBLArrayDiff has NSLog and std:cerr logging in 1.3.1 release build

### ISSUE THREAD

**Issue by combinatorial** [couchbase/couchbase-lite-ios#1492]
The release build (from cocoapods) includes CBLArrayDiff.m with logging. See this line...

https://github.com/couchbase/couchbase-lite-ios/blob/66133e2ec76851ed16828f3b05476de0671ced3e/Source/CBLArrayDiff.mm#L114

```
NSLog(@"CBLArrayDiff: %lu deleted, %lu replaced, %lu inserted, %lu moved, %lu modified",
              (unsigned long)deletions.count, (unsigned long)changesBefore.count,
              (unsigned long)insertions.count, _moves.size(), _modifiedIndexes.size());
std::cerr << changeVector << "\n";
```

---
- Version:   1.3.1
- Client OS: 10.0
- Server:    sync_gateway 1.3.1

**Comment by snej** [comment]
Is it causing problems? What's the volume of stuff it logs?

**Comment by combinatorial** [comment]
Log spam make it harder to spot real warnings or error. This is pure debug... perhaps add a DEBUG guard macro?

e.g. when the data updates...

2016-10-21 18:18:27.851 Concepts[96178:22405976] CBLArrayDiff: 0 deleted, 45 replaced, 9 inserted, 0 moved, 0 modified
{ {sub, 0, 0}, {sub, 1, 1}, {sub, 2, 2}, {sub, 3, 3}, {sub, 4, 4}, {sub, 5, 5}, {sub, 6, 6}, {sub, 7, 7}, {sub, 8, 8}, {sub, 9, 9}, {sub, 10, 10}, {sub, 11, 11}, {sub, 12, 12}, {sub, 13, 13}, {sub, 14, 14}, {sub, 15, 15}, {sub, 16, 16}, {sub, 17, 17}, {sub, 18, 18}, {sub, 19, 19}, {sub, 20, 20}, {sub, 21, 21}, {sub, 22, 22}, {sub, 23, 23}, {sub, 24, 24}, {sub, 25, 25}, {sub, 26, 26}, {sub, 27, 27}, {sub, 28, 28}, {sub, 29, 29}, {sub, 30, 30}, {sub, 31, 31}, {sub, 32, 32}, {sub, 33, 33}, {sub, 34, 34}, {sub, 35, 35}, {sub, 36, 36}, {sub, 37, 37}, {sub, 38, 38}, {sub, 39, 39}, {sub, 40, 40}, {sub, 41, 41}, {sub, 42, 42}, {sub, 43, 43}, {sub, 44, 44}, {ins, 45, 45}, {ins, 45, 46}, {ins, 45, 47}, {ins, 45, 48}, {ins, 45, 49}, {ins, 45, 50}, {ins, 45, 51}, {ins, 45, 52}, {ins, 45, 53} }

**Comment by combinatorial** [comment]
In a related question, why did CBLArrayDiff get added to the build and it's header not get exported as public in the framework? We have a copy in our project which now means we get the warning `Class CBLArrayDiff is implemented in both a and b. One of the two will be used. Which one is undefined.`
But we can't use the one in the couchbase-lite framework as the header is not exposed.

**Comment by nikolaykasyanov** [comment]
>Is it causing problems? What's the volume of stuff it logs?

Yes it is. There's no way to disable this log for App Store builds, for example. And it can be pretty big if diffed arrays are big.

**Comment by snej** [comment]
@combinatorial: CBLArrayDiff is not a public class. It's only used internally by CBLUITableSource. If you want to use it yourself, the best approach is to rename the class. It's pretty easy to do this by adding something like `#define CBLArrayDiff XXXArrayDiff` to your target's prefix header.
