### ISSUE TITLE
POST longpoll changes does not behave as longpoll

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-ios#1494]
Using @sethrosetter's peer_2_peer_sanity_pull test, I have determined that the listener is treating POST longpoll _changes requests the same as one shots (i.e returning with empty results). 

The test creates 5000 documents in the database, and then I issue the following request:

`GET http://localhost:60000/ls_db2/_changes?feed=longpoll&heartbeat=300000&style=all_docs&since=5000`

This hangs as expected waiting for new data

I then try the following request
`POST http://localhost:60000/ls_db2/_changes?feed=longpoll&heartbeat=300000&style=all_docs&since=5000`

with body

```
{
	"feed":"longpoll",
	"heartbeat":30000,
	"style":"all_docs",
	"since": 5000,
	"accept_encoding":"gzip"
}
```

I immediately get the following response:
```
{
  "results": [],
  "last_seq": 5000
}
```

This will cause big performance problems as the client on the other side of P2P fires off dozens of requests per second thinking that it got some data and needs to circle back.

--------
* Version:   1.3.1-6
* Client OS: macOS 10.12

**Comment by pasin** [comment]
Duplicate as https://github.com/couchbase/couchbase-lite-ios/issues/1235.
