### ISSUE TITLE
Manually deleting old revisions

### ISSUE THREAD

**Issue by skela** [couchbase/couchbase-lite-ios#1495]
In my system, the default database wide maxRevTreeDepth and the compact operation work well for most documents. But there's some documents where I need a lot less revisions. How do I go about manually deleting old revisions for a document? Alternatively if this isn't possible, is there any chance this could be made possible some time? 

Another option is of course to allow us to set a different maxRevTreeDepth for particular documents.

**Comment by snej** [comment]
maxRevTreeDepth only affects how much _metadata_ is stored for revisions. The metadata is only about 100 bytes per revision. Is this an issue for you?

**Comment by djpongh** [comment]
Sounds like this turned out not to be an issue?
