### ISSUE TITLE
Cannot connect to DB (lite.couchbase.) on iOS 10

### ISSUE THREAD

**Issue by JPDas** [couchbase/couchbase-lite-ios#1496]
CBL access via  https://github.com/couchbaselabs/Couchbase-Lite-PhoneGap-Plugin, we cannot make a connection to the internal URL http://lite.couchbase./ on iOS 10.
It detects CORS rejected error. In iOS 9 it works fine. We updated the couchbase lite to the latest 1.3.1, but still issues.

Any update on this?

Thanks,
## JP
- Version:   VERSION
- Client OS: NAME_AND_VERSION
- Server:    NAME_AND_VERSION

**Comment by pasin** [comment]
I have never heard about the issue before. Will need to run some tests.

**Comment by pasin** [comment]
I have run [ToDoLite-Phonegap](https://github.com/couchbaselabs/TodoLite-PhoneGap) on an iOS 10.0.2 device with Phonegap 6.3.1 , and I haven't gotten any CORS errors. The application works as just normal.

@JPDas Could you do more investigation (e.g. using different Phonegap version, JS HTTP Client, and etc.)? It could be helpful if you can create a very simple phonegap app that reproduces the issue.

**Comment by JPDas** [comment]
@passin , thanks for your answer.

This issue is already discussed in another forum. Please find the below link.

https://forums.couchbase.com/t/cannot-connect-to-db-lite-couchbase-on-ios-10/10318
https://forums.couchbase.com/t/couchbase-lite-rest-api-preflight-requests/10019


ToDoLite-Phonegap seems to work because  the files are loaded from a local source. 

Looks like preflight OPTIONS requests does not work in ios 10.

Thanks,
JP

**Comment by snej** [comment]
So you are loading remote web pages that are trying to make a connection to the local Couchbase Lite database? Are the pages being loaded over SSL from a domain under your control? (Otherwise there could be security issues.)

I don't know if anyone has ever done something like this before. It seems odd to me to load remote pages/scripts to use a local database; for offline support wouldn't you want to host the pages on the filesystem?

**Comment by pasin** [comment]
@JPDas loading the HTML page from outside the application is a new feature that we do not currently supported.

You may check this issue https://github.com/couchbaselabs/Couchbase-Lite-PhoneGap-Plugin/issues/38 to see if anything is helpful for your application architecture or not.

**Comment by JPDas** [comment]
@snej and @pasin 
Thanks for your response.

We are not loading any web page/script from outside.
Our app is similar to Todolite phonegap. I tried with cors by adding Access-Control-Allow-Origin header as * in ios 10. still no luck.

Remote PULL sync is fine, but the local db changes callback one which is registered in login time is not getting called after remote pull sync success. 


 Initially ,I am registering the below callback in login time.

function registerdbChanges() {
  config.db.changes({since : config.info.update_seq}, function(err, change){
      if(err)
            log("config.db.changes()", err, change)
      else 
           // api() , which will display the upadtes.
  })
}

After some time say 1 min, I am seeing the below logs.

[10/24 13:48:01:652] ["config.db.changes() ",{"line":1434,"column":31,"sourceURL":"file:///var/containers/Bundle/Application/DF3F4F80-46A8-4757-BFDF-1CCA2C37DB2F/kptt%20EPTT.app/www/app/lib/CouchHelper/coax.js","cors":"rejected"},null]

After that no callback i.e function(err, change) called by coax /ReST.

Thanks,
JP

**Comment by pasin** [comment]
> ToDoLite-Phonegap seems to work because the files are loaded from a local source.

> We are not loading any web page/script from outside. Our app is similar to Todolite phonegap.

@JPDas Could you please clarify what is the difference between your application and ToDoLite-Phonegap, which make the changes feed having the CORS issue? 

I'm trying to understand what is actually causing the CORS issue, but I think I'm missing some information as I tried to understand two of your comments above:

**Comment by pasin** [comment]
I'm closing as no response. If there is a new info regarding the issue, we can reopen.
