### ISSUE TITLE
Automated CI unit tests for iOS & Mac

### ISSUE THREAD

**Issue by djpongh** [couchbase/couchbase-lite-ios#1501]
--------
* Version:   VERSION
* Client OS: NAME_AND_VERSION
* Server:    NAME_AND_VERSION

**Comment by snej** [comment]
I think you mean automated unit test runs? We already have the tests :)

We support macOS too so we should run tests there as well (it's easier than on iOS.)

**Comment by ceejatec** [comment]
@pasin I saw you had mentioned you might be adding this to the 2.0 build script - if so, let me know and I'll ensure that's what's run in the 2.0 build jobs.

**Comment by djpongh** [comment]
done
