### ISSUE TITLE
Using CBL as a dependency in a pod used in Swift projects fails

### ISSUE THREAD

**Issue by stefanwascoding** [couchbase/couchbase-lite-ios#1505]
When you create a pod that uses couchbase-lite-ios, and that pod is used in a project that has frameworks enabled (which is necessary if you use Swift anywhere in your project), then the installation fails:

> ```
> Analyzing dependencies
> Downloading dependencies
> Using MySparklyPod (0.0.3)
> Using couchbase-lite-ios (1.3.1)
> [!] The 'Pods-Sparkly-Playground' target has transitive dependencies that include static binaries: ([...]/sparkly-playground/Pods/couchbase-lite-ios/CouchbaseLite.framework and [...]/sparkly-playground/Pods/couchbase-lite-ios/CouchbaseLiteListener.framework)
> ```

- using frameworks & requiring CBL in a Podfile works
- not using frameworks & requiring a pod that has a dependency on CBL works
- using frameworks & requiring a pod that has a dependency on CBL works *fails*

Do you have any suggestion on how to fix or at least around that?

--------
* Version:   1.3.1
* Client OS: iOS

**Comment by stefanwascoding** [comment]
Potentially relevant:

https://github.com/CocoaPods/CocoaPods/issues/2926
https://github.com/CocoaPods/CocoaPods/issues/3267
https://github.com/CocoaPods/CocoaPods/issues/5624

**Comment by pasin** [comment]
The release version of couchbase-lite-ios currently supports only static library so basically using use_frameworks! will not be working. I don't have a workaround for cocoapods. Does the library that you want to use support Carthage? You could use Carthage to build couchbase-lite-ios dynamic library to use with Swift.

**Comment by pasin** [comment]
Close as we have made 2.x framework dynamic library.
