### ISSUE TITLE
CBLManager.storageType is 'SQLite' but no CBL_SQLiteStorage class found. The SQLite storage class is being dead-stripped by the linker. 

### ISSUE THREAD

**Issue by Cyclic** [couchbase/couchbase-lite-ios#1506]
--------
* Version:   1.3.2
* Client OS: iOS
* Server:    Latest

I'm able to build the latest 1.3.2 branch and 1.3.1, but when I run the project, I get the known error:

> CBLManager.storageType is 'SQLite' but no CBL_SQLiteStorage class found.
> The SQLite storage class is being dead-stripped by the linker. Add -ObjC to "Other Linker Flags" in your app target settings.

I've triple checked that the -ObjC flag is in Other Linker Flags of the CouchbaseLite library, and my swift project. Is there something I'm missing? I do not recall having this problem before upgrading to Xcode 8.1 

Thanks!

**Comment by brendand** [comment]
Most likely CBL_SQLiteStorage.h isn't in the Public section of the Headers section on the Build Phases area of the target.

**Comment by pasin** [comment]
What is the selected build scheme? Please make sure that you have selected either `Continuous iOS` or `CI iOS` scheme. I would recommend to do archive instead of build to properly include the bitcode in the binary.

**Comment by pasin** [comment]
@Cyclic I'm closing the issue now. If you have already used the right scheme to build the binary, please report back and I can reopen the issue. Thanks.
