### ISSUE TITLE
ForestDB error: invalid compaction mode (-22), Assertion failed: _refCount == 0

### ISSUE THREAD

**Issue by jscubida** [couchbase/couchbase-lite-ios#1509]
Hi. A call to `viewNamed()` results in the following error:

`10:39:53.739| WARNING: ForestDB error: invalid compaction mode (-22)
 {at FDBLogCallback:68}
10:39:53.740| WARNING: ForestDB error: Assertion failed: _refCount == 0 (/Users/jenkins/jenkins/workspace/couchbase-lite-ios-builds/couchbase-lite-ios-community/vendor/CBForest/C/c4Impl.hh:115, in ~RefCounted) {at FDBLogCallback:68}
libc++abi.dylib: terminating with uncaught exception of type cbforest::error: unknown error`

--------
* Version:   1.3.1
* Client OS: iOS 10.1.1
* Server:    4.1.0-5005 Community Edition

**Comment by snej** [comment]
What are the steps to reproduce this?

**Comment by jscubida** [comment]
Starting with the default SQLite backing, I installed the app, started replications, and created views. Then, I followed the iOS instructions [here](http://blog.couchbase.com/2016/february/mobile-1.2-enable-forestdb) to enable ForestDB. Build, run, and everything is fine. 

Next, I uninstall the app and reinstall it. When it reaches a call to `viewNamed()`, I get the error generated above.

**Comment by jayahariv** [comment]
Closing 1.x issue!
