### ISSUE TITLE
Locking issue when mixing transaction, semaphores & runAsync

### ISSUE THREAD

**Issue by Orangenhain** [couchbase/couchbase-lite-ios#1511]
I'm having an issue with a -runAsync: call that doesn't call its completion handler. After a bit of experimenting, here is the minimal example I came up with that demonstrates the issue (example project will be posted below):

```objc
    // self.manager.dispatchQueue = dispatch_queue_create("Playground CouchDB", DISPATCH_QUEUE_SERIAL);
    // ... initDB ...

    [self.database inTransaction:^BOOL{
        dispatch_semaphore_t callbackSemaphore = dispatch_semaphore_create(0);
        
        CBLQuery *query = [self.database createAllDocumentsQuery];
        [query runAsync:^(CBLQueryEnumerator * _Nonnull result, NSError * _Nonnull error) {
            dispatch_semaphore_signal(callbackSemaphore);
        }];
        
        long status = dispatch_semaphore_wait(callbackSemaphore, dispatch_time(DISPATCH_TIME_NOW, 30 * NSEC_PER_SEC));
        if (status != 0) {
            NSLog(@"timed out");
        }
        return YES;
    }];
    NSLog(@"DONE  <<<<<<<<<<<<<<<<<<<<<<<<<<");
```

The debug output is:
```
10:57:07.833| Logging Database, Query, Server, View to TTY
10:57:07.835| ### Couchbase Lite 1.3.1 (build 6) (master branch, Aug 26 2016) ###
10:57:07.835| Database: Created CBLManager[0x6080000e4680 [path]/Documents]
10:57:07.836| Database: Opening CBLDatabase[<0x608000121040>playground_3]
10:57:07.836| Database: Using CBL_SQLiteStorage for db at [path]/Documents/playground_3.cblite2; upgrade=0
10:57:07.836| Couchbase Lite using SQLite version 3.14.0 (2016-07-26 15:17:14 91e811f51e611a37372875e96a4c51bbed2dfdea)
10:57:07.837| Database: Opening <CBL_SQLiteStorage: 0x608000260d80>
10:57:07.837| Database: Open [path]/Documents/playground_3.cblite2/db.sqlite3 with SQLite (flags=6(null))
10:57:07.845| Database: No pending doc expirations
10:57:09.915‖ Database: {{ Begin transaction (level 1)...
10:57:09.916‖ Query: CBLQuery[AllDocs]: Async query playground_3/_all_docs...
10:57:09.916‖ Database: Created CBLManager[0x6000000e3d80 [path]/Documents]
10:57:09.916‖ Server: CBL_RunLoopServer[0x60000003a640] Starting server thread ...
10:57:09.916‖ Database: CBLManager[0x6080000e4680 [path]/Documents] created CBL_RunLoopServer[0x60000003a640] (with CBLManager[0x6000000e3d80 [path]/Documents])
10:57:09.917‖ Server: CBL_RunLoopServer[0x60000003a640]: Server thread starting...
10:57:09.917‖ Database: Opening CBLDatabase[<0x600000121180>playground_3]
10:57:09.918‖ Database: Using CBL_SQLiteStorage for db at [path]/Documents/playground_3.cblite2; upgrade=0
10:57:09.918‖ Database: Opening <CBL_SQLiteStorage: 0x608000262180>
10:57:09.918‖ Database: Open [path]/Documents/playground_3.cblite2/db.sqlite3 with SQLite (flags=6(null))
```
... as you can see there, the async query starts, but never finishes.

Now, while experimenting (see example project) it turns out that:
- it works when dropping the transaction
- it works when dropping the semaphores
- it works when replacing the `-runAsync:` with a synchronous `-run:`

But why doesn't it work in combination?

The stack trace:
<img width="420" alt="stacktrace during lock" src="https://cloud.githubusercontent.com/assets/168694/20343537/123093ba-abef-11e6-8996-617c3c6c1696.png">

Example project:
[minimal_example.zip](https://github.com/couchbase/couchbase-lite-ios/files/594305/minimal_example.zip)

--------
* Version:   1.3.1
* Client OS: iOS 10.1 Simulator

**Comment by pasin** [comment]
It doesn't work in `inTransaction:` because the run loop is blocked on waiting for the transaction block to finish so the query result block cannot be executed when it's posted back to the same runloop.

**Comment by pasin** [comment]
I'm not sure what you are trying to do but if you would like to process the query result in a transaction, you could call database's -inTransaction: in the query result block instead.

**Comment by Orangenhain** [comment]
@pasin Is there a way to enable lock logging? Because the logging wiki page doesn't mention anything.

**Comment by pasin** [comment]
No. The lock is down to the FMDatabase level but you can modify the code to enable it:

https://github.com/couchbaselabs/fmdb/blob/a025c161a5f26d04bd1f330d1208dfbf96737671/src/FMDatabase.m#L26

**Comment by Orangenhain** [comment]
Just a small update, because I ran into this again. This time I didn't use CBL via Cocoapods, instead I've compiled directly against the source so I can properly debug. And I think your explanation for this issue wasn't quite complete.

Here's what it looks like to me:
1. `-inTransaction:` acquires a write lock (on the manager's dispatch queue)
2. the transaction executes its given block, and encounters the `-runAsync:`
3. this causes a call to `tellDatabaseNamed:to:` on the CouchbaseLite server thread (via `MYOnThread(_serverThread, block)`)
4. this opens the DB file and tries to initialise it (trying to run the statement `PRAGMA foreign_keys = ON;`) ... which is what you can see in thread 9 on the previous screenshot
5. but executing this statement needs a write lock ... which is already held by the transaction from step 1 -> *deadlock*

So the problem isn't that the query's result block can't be executed on the same runloop, the query _itself_ will never be executed, as FMDB can't open the DB file while the transaction is ongoing.

Just for background: The reason this code construct came up is that I have an SDK that provides async methods that access the DB, but there are also "higher level" methods that are compositions of those that should either all succeed, or all fail (hence the transaction) ... but "un-async-ing" those methods & using that in a transaction at the same time doesn't work.
Most likely I'll have to make sure the internal DB methods actually use `-doSync:` and make the public API methods async without using the CBL async methods ... that way even the composite methods can be made up of synchronous operations. Should even simplify the code ... quite a few semaphores will be out of a job.
