### ISSUE TITLE
Query: Accessing CBL server from 3rd party application

### ISSUE THREAD

**Issue by msanilkumar2020** [couchbase/couchbase-lite-ios#1520]
In iOS is it possible for  3rd party app to access CBL server using REST requests.(Knowing the db name and credentials)?

In Android, this security issue is reported in below link
https://github.com/couchbase/couchbase-lite-java-listener/issues/48#issuecomment-260525485

Does this issue is applicable for iOS also ?

Thanks,
Anil Kumar

--------
* Version:   1.3.1
* Client OS: iOS 10,Xcode 8

**Comment by msanilkumar2020** [comment]
Do you have any update on these query, i want to know the behaviour of iOS.

Thanks,
Anil Kumar

**Comment by pasin** [comment]
You can use CouchbaseLite Listener to enable REST access. You can also setup users' credentials as well.

See https://github.com/couchbase/couchbase-lite-ios/blob/master/Listener/CBLListener.h#L85.

**Comment by NitzDKoder** [comment]
@pasin we are running the cordoava based app with CouchbaseLite Listener runiing.. how secure is the iOS module? Pls confirm..

Android has below issue open:

https://github.com/couchbase/couchbase-lite-java-listener/issues/48
https://github.com/couchbase/couchbase-lite-java-listener/issues/78

Thanks
Nithin

**Comment by pasin** [comment]
@NitzDKoder 
1. iOS PhoneGap plugin uses internal custom URL protocol which is bound to the process.
2. I believe iOS already supports OPTIONS request. Do you have CORS issue with iOS?

**Comment by NitzDKoder** [comment]
1)"bound to the process" meaning other Apps cant access it? 

Is there a server concept in iOS too?  PCAP will have traces of http/custom url used? SSL is not needed?


https://github.com/couchbase/couchbase-lite-ios/wiki/LiteServ-With-SSL


2)We do have cors issue in iOS 10, will share more info soon.
https://github.com/couchbase/couchbase-lite-ios/issues/1496


Thanks
Nithin

**Comment by NitzDKoder** [comment]
@pasin your thoughts on above?

**Comment by pasin** [comment]
@NitzDKoder Sorry, I missed your questions.

> Is there a server concept in iOS too? PCAP will have traces of http/custom url used? SSL is not needed?

CBL iOS PhoneGap plugin doesn't start the listener (see the code [here](https://github.com/couchbaselabs/Couchbase-Lite-PhoneGap-Plugin/blob/master/src/ios/CBLite.m#L25-L36)).  It uses an internal custom URL (a subclass of NSURLProtocol) that allows the requests with the internal URL scheme to get handled directly. I don't think PCAP will have the traces. There are some good articles about NSURLProtocol such as [here](http://nshipster.com/nsurlprotocol/) and [here](https://www.raywenderlich.com/59982/nsurlprotocol-tutorial). So no SSL is needed. On the other hand, this means that with iOS PhoneGap plugin, you are not able to access to the local database via HTTP requests outside the app.

> 2)We do have cors issue in iOS 10, will share more info soon.

To use the local database from outside the app, you will need to spin a the listener object. I'm not sure how this will work in the real app as when the app goes into the background mode, there is a time limit by the OS for the tasks to be run. I'm not sure what is the CORS issue that you have. Can you describe about that more or open a new ticket. I saw @jamiltz submitted a [PR](https://github.com/couchbase/couchbase-lite-ios/pull/1708) related to CORS to add CORS enabled flag to the LiteServ which utilizes the listener object. You can check that as well if it could solve the issue that you have.
