### ISSUE TITLE
Assertion failed: Background task already running

### ISSUE THREAD

**Issue by tommyle** [couchbase/couchbase-lite-ios#1521]
We are having an issue with the background task failing to start with the following stack trace

> #0. Crashed: com.twitter.crashlytics.ios.exception
> 0  APPNAME                           0x1005a11f0 CLSProcessRecordAllThreads + 1530768
> 1  APPNAME                           0x1005a11f0 CLSProcessRecordAllThreads + 1530768
> 2  APPNAME                           0x1005a10ac CLSProcessRecordAllThreads + 1530444
> 3  APPNAME                           0x10059186c CLSHandler + 1466892
> 4  APPNAME                           0x10059f2c4 __CLSExceptionRecord_block_invoke + 1522788
> 5  libdispatch.dylib              0x1834ce1bc _dispatch_client_callout + 16
> 6  libdispatch.dylib              0x1834db7f0 _dispatch_barrier_sync_f_invoke + 84
> 7  APPNAME                           0x10059ed68 CLSExceptionRecord + 1521416
> 8  APPNAME                           0x10059eb9c CLSExceptionRecordNSException + 1520956
> 9  APPNAME                           0x10059e7bc CLSTerminateHandler() + 1519964
> 10 libc++abi.dylib                0x18306b66c std::__terminate(void (*)()) + 16
> 11 libc++abi.dylib                0x18306b234 __cxa_rethrow + 144
> 12 libobjc.A.dylib                0x18307c71c objc_exception_rethrow + 44
> 13 CoreFoundation                 0x18452032c CFRunLoopRunSpecific + 560
> 14 GraphicsServices               0x185fd4198 GSEventRunModal + 180
> 15 UIKit                          0x18a60f7c8 <redacted> + 684
> 16 UIKit                          0x18a60a500 UIApplicationMain + 208
> 17 APPNAME                           0x1000dc110 main (main.m:18)
> 18 libdispatch.dylib              0x1835015b8 (Missing)
> 
> --
> 
> Fatal Exception: NSInternalInconsistencyException
> 0  CoreFoundation                 0x1846471b8 (Missing)
> 1  libobjc.A.dylib                0x18307c55c (Missing)
> 2  CoreFoundation                 0x18464708c (Missing)
> 3  Foundation                     0x1850ff098 (Missing)
> 4  APPNAME                           0x1004ed920 _AssertFailed (Test_Assertions.m:31)
> 5  APPNAME                           0x1004a95e0 -[MYBackgroundMonitor beginBackgroundTaskNamed:] (MYBackgroundMonitor.m:66)
> 6  APPNAME                           0x1004f180c -[CBLRestReplicator(Backgrounding) appBackgrounding] (CBLRestReplicator+Backgrounding.m:59)
> 7  APPNAME                           0x1004f161c __54-[CBLRestReplicator(Backgrounding) setupBackgrounding]_block_invoke (CBLRestReplicator+Backgrounding.m:32)
> 8  CoreFoundation                 0x1845e0b10 (Missing)
> 9  CoreFoundation                 0x1845e0214 (Missing)
> 10 CoreFoundation                 0x1845dff90 (Missing)
> 11 CoreFoundation                 0x18464fb8c (Missing)
> 12 CoreFoundation                 0x184521e64 (Missing)
> 13 Foundation                     0x185056e0c (Missing)
> 14 UIKit                          0x18a83170c (Missing)
> 15 UIKit                          0x18a90d210 (Missing)
> 16 UIKit                          0x18a8315ac (Missing)
> 17 UIKit                          0x18a83bdbc (Missing)
> 18 UIKit                          0x18a8400d8 (Missing)
> 19 UIKit                          0x18a83ffb4 (Missing)
> 20 UIKit                          0x18a82b554 (Missing)
> 21 UIKit                          0x18a82b1d8 (Missing)
> 22 UIKit                          0x18ab56490 (Missing)
> 23 FrontBoardServices             0x1861eef98 __80-[FBSSceneImpl updater:didUpdateSettings:withDiff:transitionContext:completion:]_block_invoke.376
> 24 FrontBoardServices             0x18621c97c __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__
> 25 FrontBoardServices             0x18621c7e8 -[FBSSerialQueue _performNext]
> 26 FrontBoardServices             0x18621cb90 -[FBSSerialQueue _performNextFromRunLoopSource]
> 27 CoreFoundation                 0x1845f4b5c (Missing)
> 28 CoreFoundation                 0x1845f44a4 (Missing)
> 29 CoreFoundation                 0x1845f20a4 (Missing)
> 30 CoreFoundation                 0x1845202b8 (Missing)
> 31 GraphicsServices               0x185fd4198 GSEventRunModal
> 32 UIKit                          0x18a60f7c8 (Missing)
> 33 UIKit                          0x18a60a500 (Missing)
> 34 APPNAME                           0x1000dc110 main (main.m:18)
> 35 libdispatch.dylib              0x1835015b8 (Missing)
> 
> #0. Crashed: com.twitter.crashlytics.ios.exception
> 0  APPNAME                           0x1005a11f0 CLSProcessRecordAllThreads + 1530768
> 1  APPNAME                           0x1005a11f0 CLSProcessRecordAllThreads + 1530768
> 2  APPNAME                           0x1005a10ac CLSProcessRecordAllThreads + 1530444
> 3  APPNAME                           0x10059186c CLSHandler + 1466892
> 4  APPNAME                           0x10059f2c4 __CLSExceptionRecord_block_invoke + 1522788
> 5  libdispatch.dylib              0x1834ce1bc _dispatch_client_callout + 16
> 6  libdispatch.dylib              0x1834db7f0 _dispatch_barrier_sync_f_invoke + 84
> 7  APPNAME                           0x10059ed68 CLSExceptionRecord + 1521416
> 8  APPNAME                           0x10059eb9c CLSExceptionRecordNSException + 1520956
> 9  APPNAME                           0x10059e7bc CLSTerminateHandler() + 1519964
> 10 libc++abi.dylib                0x18306b66c std::__terminate(void (*)()) + 16
> 11 libc++abi.dylib                0x18306b234 __cxa_rethrow + 144
> 12 libobjc.A.dylib                0x18307c71c objc_exception_rethrow + 44
> 13 CoreFoundation                 0x18452032c CFRunLoopRunSpecific + 560
> 14 GraphicsServices               0x185fd4198 GSEventRunModal + 180
> 15 UIKit                          0x18a60f7c8 <redacted> + 684
> 16 UIKit                          0x18a60a500 UIApplicationMain + 208
> 17 APPNAME                           0x1000dc110 main (main.m:18)
> 18 libdispatch.dylib              0x1835015b8 (Missing)
> 
> #1. com.apple.uikit.eventfetch-thread
> 0  libsystem_kernel.dylib         0x1835f5188 mach_msg_trap + 8
> 1  libsystem_kernel.dylib         0x1835f4ff8 mach_msg + 72
> 2  CoreFoundation                 0x1845f45d0 <redacted> + 192
> 3  CoreFoundation                 0x1845f21ec <redacted> + 1132
> 4  CoreFoundation                 0x1845202b8 CFRunLoopRunSpecific + 444
> 5  Foundation                     0x18505d26c <redacted> + 304
> 6  Foundation                     0x18507ddd0 <redacted> + 96
> 7  UIKit                          0x18af82af8 <redacted> + 136
> 8  Foundation                     0x18515ae68 <redacted> + 1024
> 9  libsystem_pthread.dylib        0x1836d9850 <redacted> + 240
> 10 libsystem_pthread.dylib        0x1836d9760 _pthread_start + 282
> 11 libsystem_pthread.dylib        0x1836d6d94 thread_start + 4
> 
> #2. Thread
> 0  libsystem_kernel.dylib         0x183613a88 __workq_kernreturn + 8
> 1  libsystem_pthread.dylib        0x1836d7344 _pthread_wqthread + 1452
> 2  libsystem_pthread.dylib        0x1836d6d8c start_wqthread + 4
> 
> #3. com.twitter.crashlytics.ios.MachExceptionServer
> 0  libsystem_kernel.dylib         0x1835f5188 mach_msg_trap + 8
> 1  libsystem_kernel.dylib         0x1835f4ff8 mach_msg + 72
> 2  APPNAME                           0x10058c6cc CLSMachExceptionServer + 1445996
> 3  libsystem_pthread.dylib        0x1836d9850 <redacted> + 240
> 4  libsystem_pthread.dylib        0x1836d9760 _pthread_start + 282
> 5  libsystem_pthread.dylib        0x1836d6d94 thread_start + 4
> 
> #4. Thread
> 0  libsystem_kernel.dylib         0x183613a88 __workq_kernreturn + 8
> 1  libsystem_pthread.dylib        0x1836d7344 _pthread_wqthread + 1452
> 2  libsystem_pthread.dylib        0x1836d6d8c start_wqthread + 4
> 
> #5. com.apple.NSURLConnectionLoader
> 0  libsystem_kernel.dylib         0x1835f5188 mach_msg_trap + 8
> 1  libsystem_kernel.dylib         0x1835f4ff8 mach_msg + 72
> 2  CoreFoundation                 0x1845f45d0 <redacted> + 192
> 3  CoreFoundation                 0x1845f21ec <redacted> + 1132
> 4  CoreFoundation                 0x1845202b8 CFRunLoopRunSpecific + 444
> 5  CFNetwork                      0x184d259ec <redacted> + 336
> 6  Foundation                     0x18515ae68 <redacted> + 1024
> 7  libsystem_pthread.dylib        0x1836d9850 <redacted> + 240
> 8  libsystem_pthread.dylib        0x1836d9760 _pthread_start + 282
> 9  libsystem_pthread.dylib        0x1836d6d94 thread_start + 4
> 
> #6. Thread
> 0  libsystem_kernel.dylib         0x183612e1c __psynch_cvwait + 8
> 1  libsystem_pthread.dylib        0x1836d89c0 <redacted> + 640
> 2  libc++.1.dylib                 0x1830013ec std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 56
> 3  JavaScriptCore                 0x188ecb60c <redacted> + 112
> 4  JavaScriptCore                 0x188ecb580 <redacted> + 168
> 5  JavaScriptCore                 0x188ecb460 <redacted> + 10
> 6  JavaScriptCore                 0x188ecb710 <redacted> + 92
> 7  libsystem_pthread.dylib        0x1836d9850 <redacted> + 240
> 8  libsystem_pthread.dylib        0x1836d9760 _pthread_start + 282
> 9  libsystem_pthread.dylib        0x1836d6d94 thread_start + 4
> 
> #7. WebThread
> 0  libsystem_kernel.dylib         0x1835f5188 mach_msg_trap + 8
> 1  libsystem_kernel.dylib         0x1835f4ff8 mach_msg + 72
> 2  CoreFoundation                 0x1845f45d0 <redacted> + 192
> 3  CoreFoundation                 0x1845f21ec <redacted> + 1132
> 4  CoreFoundation                 0x1845202b8 CFRunLoopRunSpecific + 444
> 5  WebCore                        0x1891ccd98 <redacted> + 456
> 6  libsystem_pthread.dylib        0x1836d9850 <redacted> + 240
> 7  libsystem_pthread.dylib        0x1836d9760 _pthread_start + 282
> 8  libsystem_pthread.dylib        0x1836d6d94 thread_start + 4
> 
> #8. com.apple.CoreMotion.MotionThread
> 0  libsystem_kernel.dylib         0x1835f5188 mach_msg_trap + 8
> 1  libsystem_kernel.dylib         0x1835f4ff8 mach_msg + 72
> 2  CoreFoundation                 0x1845f45d0 <redacted> + 192
> 3  CoreFoundation                 0x1845f21ec <redacted> + 1132
> 4  CoreFoundation                 0x1845202b8 CFRunLoopRunSpecific + 444
> 5  CoreFoundation                 0x18456db44 CFRunLoopRun + 112
> 6  CoreMotion                     0x18b489120 CLStartStopAdvertisingBeacon + 203196
> 7  libsystem_pthread.dylib        0x1836d9850 <redacted> + 240
> 8  libsystem_pthread.dylib        0x1836d9760 _pthread_start + 282
> 9  libsystem_pthread.dylib        0x1836d6d94 thread_start + 4
> 
> #9. CouchbaseLite
> 0  libsystem_kernel.dylib         0x1835f5188 mach_msg_trap + 8
> 1  libsystem_kernel.dylib         0x1835f4ff8 mach_msg + 72
> 2  CoreFoundation                 0x1845f45d0 <redacted> + 192
> 3  CoreFoundation                 0x1845f21ec <redacted> + 1132
> 4  CoreFoundation                 0x1845202b8 CFRunLoopRunSpecific + 444
> 5  Foundation                     0x18505d26c <redacted> + 304
> 6  APPNAME                           0x100485b20 -[CBL_RunLoopServer runServerThread] (CBL_Server.m:193)
> 7  Foundation                     0x18515ae68 <redacted> + 1024
> 8  libsystem_pthread.dylib        0x1836d9850 <redacted> + 240
> 9  libsystem_pthread.dylib        0x1836d9760 _pthread_start + 282
> 10 libsystem_pthread.dylib        0x1836d6d94 thread_start + 4
> 
> #10. JIT Worklist Worker Thread
> 0  libsystem_kernel.dylib         0x183612e1c __psynch_cvwait + 8
> 1  libsystem_pthread.dylib        0x1836d89c0 <redacted> + 640
> 2  libc++.1.dylib                 0x1830013ec std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 56
> 3  JavaScriptCore                 0x188eb3da0 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 2132
> 4  JavaScriptCore                 0x188c8bad4 <redacted> + 192
> 5  JavaScriptCore                 0x188c8bf24 <redacted> + 14
> 6  JavaScriptCore                 0x1885fc15c <redacted> + 212
> 7  JavaScriptCore                 0x1885fc06c <redacted> + 24
> 8  libsystem_pthread.dylib        0x1836d9850 <redacted> + 240
> 9  libsystem_pthread.dylib        0x1836d9760 _pthread_start + 282
> 10 libsystem_pthread.dylib        0x1836d6d94 thread_start + 4
> 
> #11. WTF Parallel Helper Thread
> 0  libsystem_kernel.dylib         0x183612e1c __psynch_cvwait + 8
> 1  libsystem_pthread.dylib        0x1836d89c0 <redacted> + 640
> 2  libc++.1.dylib                 0x1830013ec std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 56
> 3  JavaScriptCore                 0x188eb3da0 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 2132
> 4  JavaScriptCore                 0x188eb3324 <redacted> + 288
> 5  JavaScriptCore                 0x188eb30c4 <redacted> + 76
> 6  JavaScriptCore                 0x1885fc15c <redacted> + 212
> 7  JavaScriptCore                 0x1885fc06c <redacted> + 24
> 8  libsystem_pthread.dylib        0x1836d9850 <redacted> + 240
> 9  libsystem_pthread.dylib        0x1836d9760 _pthread_start + 282
> 10 libsystem_pthread.dylib        0x1836d6d94 thread_start + 4
> 
> #12. Thread
> 0  libsystem_kernel.dylib         0x183613a88 __workq_kernreturn + 8
> 1  libsystem_pthread.dylib        0x1836d7344 _pthread_wqthread + 1452
> 2  libsystem_pthread.dylib        0x1836d6d8c start_wqthread + 4
> 
> #13. Thread
> 0  libsystem_kernel.dylib         0x183613a88 __workq_kernreturn + 8
> 1  libsystem_pthread.dylib        0x1836d7160 _pthread_wqthread + 968
> 2  libsystem_pthread.dylib        0x1836d6d8c start_wqthread + 4
> 
> #14. Thread
> 0  libsystem_kernel.dylib         0x183613a88 __workq_kernreturn + 8
> 1  libsystem_pthread.dylib        0x1836d7344 _pthread_wqthread + 1452
> 2  libsystem_pthread.dylib        0x1836d6d8c start_wqthread + 4
> 
> #15. Thread
> 0  libsystem_kernel.dylib         0x183613a88 __workq_kernreturn + 8
> 1  libsystem_pthread.dylib        0x1836d7344 _pthread_wqthread + 1452
> 2  libsystem_pthread.dylib        0x1836d6d8c start_wqthread + 4
> 
> #16. Thread
> 0  libsystem_kernel.dylib         0x183613a88 __workq_kernreturn + 8
> 1  libsystem_pthread.dylib        0x1836d7160 _pthread_wqthread + 968
> 2  libsystem_pthread.dylib        0x1836d6d8c start_wqthread + 4
> 
> #17. Thread
> 0  libsystem_kernel.dylib         0x183613a88 __workq_kernreturn + 8
> 1  libsystem_pthread.dylib        0x1836d7160 _pthread_wqthread + 968
> 2  libsystem_pthread.dylib        0x1836d6d8c start_wqthread + 4
> 
> #18. Thread
> 0  libsystem_kernel.dylib         0x183613a88 __workq_kernreturn + 8
> 1  libsystem_pthread.dylib        0x1836d7344 _pthread_wqthread + 1452
> 2  libsystem_pthread.dylib        0x1836d6d8c start_wqthread + 4
> 
> #19. Thread
> 0  libsystem_kernel.dylib         0x183613a88 __workq_kernreturn + 8
> 1  libsystem_pthread.dylib        0x1836d7344 _pthread_wqthread + 1452
> 2  libsystem_pthread.dylib        0x1836d6d8c start_wqthread + 4
> 
> #20. Thread
> 0  libsystem_kernel.dylib         0x183613a88 __workq_kernreturn + 8
> 1  libsystem_pthread.dylib        0x1836d7344 _pthread_wqthread + 1452
> 2  libsystem_pthread.dylib        0x1836d6d8c start_wqthread + 4
> 
> #21. Thread
> 0  libsystem_kernel.dylib         0x183613a88 __workq_kernreturn + 8
> 1  libsystem_pthread.dylib        0x1836d7344 _pthread_wqthread + 1452
> 2  libsystem_pthread.dylib        0x1836d6d8c start_wqthread + 4
> 
> #22. Thread
> 0  libsystem_kernel.dylib         0x183613a88 __workq_kernreturn + 8
> 1  libsystem_pthread.dylib        0x1836d7160 _pthread_wqthread + 968
> 2  libsystem_pthread.dylib        0x1836d6d8c start_wqthread + 4
> 
> #23. Thread
> 0  libsystem_kernel.dylib         0x183613a88 __workq_kernreturn + 8
> 1  libsystem_pthread.dylib        0x1836d7344 _pthread_wqthread + 1452
> 2  libsystem_pthread.dylib        0x1836d6d8c start_wqthread + 4
> 
> #24. Thread
> 0  libsystem_kernel.dylib         0x183613a88 __workq_kernreturn + 8
> 1  libsystem_pthread.dylib        0x1836d7344 _pthread_wqthread + 1452
> 2  libsystem_pthread.dylib        0x1836d6d8c start_wqthread + 4
> 
> #25. AFNetworking
> 0  libsystem_kernel.dylib         0x1835f5188 mach_msg_trap + 8
> 1  libsystem_kernel.dylib         0x1835f4ff8 mach_msg + 72
> 2  CoreFoundation                 0x1845f45d0 <redacted> + 192
> 3  CoreFoundation                 0x1845f21ec <redacted> + 1132
> 4  CoreFoundation                 0x1845202b8 CFRunLoopRunSpecific + 444
> 5  Foundation                     0x18505d26c <redacted> + 304
> 6  Foundation                     0x1850b1aa0 <redacted> + 88
> 7  APPNAME                           0x10031bda8 +[AFURLConnectionOperation networkRequestThreadEntryPoint:] (AFURLConnectionOperation.m:170)
> 8  Foundation                     0x18515ae68 <redacted> + 1024
> 9  libsystem_pthread.dylib        0x1836d9850 <redacted> + 240
> 10 libsystem_pthread.dylib        0x1836d9760 _pthread_start + 282
> 11 libsystem_pthread.dylib        0x1836d6d94 thread_start + 4

--------
* Version:   1.3.0
* Client OS: iOS 10.2.0

**Comment by snej** [comment]
This appears to be a dup.
