### ISSUE TITLE
When app goes background state CBL automatically going Offline mode ( status 1 )

### ISSUE THREAD

**Issue by Tamil-Arya** [couchbase/couchbase-lite-ios#1524]
Hi, i set replication as  Continuous even though when app goes background it automatically going offline mode if i try to restart (pull & push ) even though it goes offline mode. 
--------
* Version:   CBL 1.3
* Client OS: iOS 10
* Server:   CouchDB

**Comment by pasin** [comment]
Not sure if I understand your questions correctly or not. When the app goes into the bg mode, the replicator will automatically suspend itself. However you could set the suspended property of the replicator to `false` to reactivate the replicator. Please see the `suspended` property info here:

https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/API/CBLReplication.h#L172-L177

I will close the issue now. If you encounter the issue after setting the `suspended` property to `false`, please let us know.
