### ISSUE TITLE
Sync via document IDs

### ISSUE THREAD

**Issue by SalmanZafar1105** [couchbase/couchbase-lite-ios#1526]
Sync documents by specifying document IDs. 

As of now, filter pull is done by specifying channels. We have to run a separate pull replication for one single document.

How to pull one document from sync gateway?

--------
* Version:   1.3.1
* Client OS: iOS 10.0.1, iOS 10.1.1
* Server:    1.3.0

**Comment by pasin** [comment]
You can set `documentIDs` to the replicator. Thanks.

**Comment by SalmanZafar1105** [comment]
I am using couchbase lite and not couchdb, mongodb, etc.
Couchbase lite supports only channel based filter.

http://developer.couchbase.com/documentation/mobile/current/guides/couchbase-lite/native-api/replication/index.html#filtered-pull-from-sync-gateway

**Comment by jamiltz** [comment]
Have you tried using the [`documentIDs`](https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/API/CBLReplication.h#L75) method on the replication object as Pasin pointed out? If that doesn't solve your query can you explain why?

**Comment by SalmanZafar1105** [comment]
CBLHTTP[400, "bad_request", <http://:*****@my:4990/db/_changes?feed=longpoll&heartbeat=300000&style=all_docs&since=1088&filter=_doc_ids>]

I get this error.

**Comment by jamiltz** [comment]
Can you try with a one-shot replication instead of continuous?

**Comment by SalmanZafar1105** [comment]
No error, but document is not synced.

In couchbase lite documentation, it is written that to filter documents from sync gateway we need to specify channels, but if we are using couchdb, pouchdb or cloudant then there are other methods.

The word "documentID" is not written in the replication part of couchbase lite documentation.

**Comment by jamiltz** [comment]
The last sentence in [this paragraph](http://developer.couchbase.com/documentation/mobile/1.3/guides/couchbase-lite/native-api/replication/index.html#types-of-replications) mentions filtering by doc ID and I agree we need a bit more content on that (specifically that it's not supported for continuous replications). Per https://github.com/couchbase/sync_gateway/issues/1703 and https://github.com/couchbase/sync_gateway/issues/1712 it should work though. Are you sure that user has access to the document?

**Comment by SalmanZafar1105** [comment]
I coordinated with the back-end team to check if I have access to the document. They said the document's channel should be in the user's admin channel. 

The userId is 919711. The user document has the following channel -

"channels": {
      "ch-919711": null
    }

Also, user's admin channels also contain this channel - 
"admin_channels":["ch-919711",...]

**Comment by jamiltz** [comment]
I just tried with the following and the replication pulled the doc successfully from SG:

```swift
let replication = database.createPullReplication(kSyncGatewayUrl)
replication.authenticator = CBLAuthenticator.basicAuthenticator(withName: "user1", password: "pass")
replication.documentIDs = ["456"]
replication.start()
```

after adding the doc:

```bash
curl -vX PUT 'http://user1:pass@localhost:4984/todo/456' -H 'Content-Type: application/json' -d '{}'
```

We'll update the documentation to make that clearer so thanks for the feedback!

**Comment by pasin** [comment]
@SalmanZafar1105, sorry about this. I don't know that SGW doesn't currently support docIDs in continuous replication. Meanwhile, you might need to setup the timer to periodically start a single shot pull replicator.

**Comment by SalmanZafar1105** [comment]
It's OK. I have it working now.
