### ISSUE TITLE
How to get the not pushed pending document from local database while device in offline mode ?

### ISSUE THREAD

**Issue by Tamil-Arya** [couchbase/couchbase-lite-ios#1530]
Hi i m trying to get the pending document from CBL while device in offline but i could not get (if device in offline the replication part is not running so i tried this "push.pendingDocumentID " ) any idea ?

My code :  
CBLReplication *pushReplication =  [[self _database] createPushReplication:url]; 
NSLog(@" push pendingDocumentIDs :%d", pushReplication.pendingDocumentIDs.count);
--------
* Version:   1.3
* Client OS: iOS 10
* Server:    CouchDB

**Comment by pasin** [comment]
I believe this feature has been already implemented in https://github.com/couchbase/couchbase-lite-ios/commit/f7dc8dc3e3d231cea9de2d6010d970aa939fdf50. I also tested it and I was able to get the pendingDocumentID without a need to start the replicator. Could you please explain more about the issue?

**Comment by Tamil-Arya** [comment]
Yeah. you are right but some time it's showing wrong count of local pending document.( ex : if i have set of doc well if i didn't change anything in the doc then also it showed complete doc hasn't pushed to server )

**Comment by mglasgow** [comment]
@Tamil-Arya, you are correct. If the push replication to the server has never run, then pendingDocumentIDs will return all documents in the local database.

However, once the push replication has successfully synchronised at least once, then this method will behave as expected.
