### ISSUE TITLE
Broken links in README.md

### ISSUE THREAD

**Issue by richardgroves** [couchbase/couchbase-lite-ios#1531]
The first three links in the 'More Information' section of README.md are broken:

Why Couchbase Lite? - https://github.com/couchbase/couchbase-lite-ios/wiki/Why-Couchbase-Lite%3F - tries to make a new page in the wiki

API Overview & API Reference lead to 404s.
--------
* Version:   master
* Client OS: N/A
* Server:    N/A

**Comment by jamiltz** [comment]
Thanks for the feedback! Links are updated.
