### ISSUE TITLE
Concurrency issue with stacked transactions, DB change notifications & `-existingDocumentWithID:`

### ISSUE THREAD

**Issue by Orangenhain** [couchbase/couchbase-lite-ios#1535]
I have some code that imports a lot of entities (multiple documents) in batches. Each batch is wrapped in a transaction, and the creation of all documents for each entity is a transaction as well ... so boiled down the code looks like this:

```objc
for (int a = 0; a < kBatchCount; a++) {
    [self.database inTransaction:^BOOL {
        for (int i = 0; i < kBatchSize; i++) {
            [self.database inTransaction:^BOOL {
                for (int j = 0; j < kDocCount; j++) {
                    [self create_doc];
                }
                NSLog(@"inner transaction done");
                return YES;
            }];
        }
        NSLog(@"outer transaction done");
        return YES;
    }];
}
```

I also have some "changes stream" code that listens to `kCBLDatabaseChangeNotification` and handles it like this:

```objc
- (void)databaseDidChange_fails:(NSNotification *)notification
{
    for (CBLDatabaseChange *change in changes) {
        CBLDocument *document = [self.database existingDocumentWithID:change.documentID];
        if (document) {
            // event = update or create
        } else {
            // event = delete
        }
        // emit change event
    }
}
```

Depending on batch size I regularly get a crash with:
> Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Already holding read lock'

<img width="1344" alt="screen shot 2016-12-22 at 17 49 13" src="https://cloud.githubusercontent.com/assets/168694/21433264/783a5ffa-c86f-11e6-9b38-7e4789d7c9d5.png">

As this seems to be caused by accessing the database from two different threads, I thought that wrapping the changes handler in a `-doAsync:` would help, but while this doesn't crash (most of the time), there are still warnings and failed transactions:

<img width="1423" alt="screen shot 2016-12-22 at 17 51 48" src="https://cloud.githubusercontent.com/assets/168694/21433340/cb75cc18-c86f-11e6-8996-2201d6bc1a9d.png">

While reading the CBL code, it dawned on me that I don't even have to use `-existingDocumentWithID:` ... I only use the return value of the call to decide whether the change was a deletion event, but the *CBLDatabaseChange* object actually has that information, although it's not made public ... using

```objc
BOOL isDeletion = [[change valueForKey:@"isDeletion"] boolValue];
```

instead of fetching the document from the DB, seems to fix all the issues for my use case. No warnings and no failed transactions.

Why is the `isDeletion` not public?
Is there another "official" way to determine if a change was a deletion event?
Shouldn't the `-doAsync:` variant work?

In case you are interested in this issue, here's a sample app to play around with it (contains all three iterations of the changes handler): 
[minimal_example.zip](https://github.com/couchbase/couchbase-lite-ios/files/669318/minimal_example.zip)

--------
* Version:   1.3.1
* Client OS: iOS 10.2

**Comment by pasin** [comment]
Thanks for providing the sample code. I will look at it.

**Comment by pasin** [comment]
I ran the app and I couldn't reproduce the crash. I also tried to adjust the kBatchCount, kBatchSize, and kDocCount to higher numbers but I still couldn't make the app crash. I believe I don't have the right setup to reproduce the issue.

However I noticed that the code set a DISPATCH_QUEUE_SERIAL dispatch queue to the manager but the database operation is executed inside a NSOperationQueue which will use its own queue. These would violate the threading model of the CBL iOS that requires the database operations to operate on the same dispatch queue set to the manager. Please fix the dispatch queue issue and rerun the app. If the issue still exists, we can reopen the issue and do more investigation. Thanks!

**Comment by Orangenhain** [comment]
I noticed that I left the addObserver call with a wrong selector, if you change line 86 (in `-registerForDBChanges` to use the `-databaseDidChange_fails` selector, you would hopefully be able to see my issue.

However, after your comment about the operation queue, I changed line 29 in the operation into
```
[self.database doSync:^{ [self create_doc]; }];
```
This also fixes the issues, for all the different `-databaseDidChange_*` selectors.

When **does** CBL use the `dispatchQueue` that's specified on the manager? From the documentation I thought it would just *always* use it for database operations, but that doesn't seem to be the case. Do I have to explicitly call `-doSync:` or `-doAsync:` for CBL to use the dispatch queue?

**Comment by Orangenhain** [comment]
Could you also please look into my questions about "isDeletion" (and how to best recognise a deletion event in the change notification)?
Or, should I split that into a separate issue  ... since it's got nothing to do with my (mis-)understanding of the CBL threading model.

**Comment by pasin** [comment]
> When does CBL use the dispatchQueue that's specified on the manager? From the documentation I thought it would just always use it for database operations, but that doesn't seem to be the case. Do I have to explicitly call -doSync: or -doAsync: for CBL to use the dispatch queue?

When a dispatchQueue specified, it means that the manager and its database are bound to the dispatch queue. Any database operations need to be performed on that dispatch queue either by using the the dispatch queue directly or use `-doSync:` or `-doAsync:`.

**Comment by pasin** [comment]
> Could you also please look into my questions about "isDeletion" (and how to best recognise a deletion event in the change notification)?

Currently isDeletion is not public and used internally by the replicator. I created #1538 for your question about opening isDeletion for public use. Meanwhile, you can get a document with ID and check isDeleted property of the document. Thanks.

**Comment by Orangenhain** [comment]
👍  Thank you.
