### ISSUE TITLE
didEnterBackground pull replications

### ISSUE THREAD

**Issue by Tamil-Arya** [couchbase/couchbase-lite-ios#1540]
Hi everyone, I m trying to download some document from **CouchDB** server after enter didEnterBackground state but i couldn't download complete documents after certain time the pull replication automatically stoped  ( **active=0; status=1; 0/0; (null)** ). it was approximately 3 min to do pull replication afterward it stoped.
Even i tried to set **[pull setSuspend:NO];** even though didn't work.

Please comment here the reason of stop. thanks :|

* Version:   1.3
* Client OS: iOS 10
* Server:    CouchDB

**Comment by snej** [comment]
This is expected. iOS won't let apps keep running forever in the background; it only gives them a limited amount of time. The replicator stops when the OS tells it it's run out of background time.

**Comment by Tamil-Arya** [comment]
Ok thanks. my requirement is  "While download some file that time if goes background that sync automatically stoped after certain time so that file could n't download " is there any other way to do achieve this functionalities ?

**Comment by snej** [comment]
Sorry, I didn't understand the requirement. Can you explain?

**Comment by Tamil-Arya** [comment]
Hi thanks for reply, My requirement is " i start downloading some documents from CouchDB (ex: around 100 MB ) while downloading time if user gonna background state at the time, it has to be continue downloading as by the pull replication. Indeed, it works fine but after some more time approximately 3min stop pull replication as well my download also has stoped. is there any other way to do complete requirement ? (note : if downloading doc more than 10 m also should download in the background state )
