### ISSUE TITLE
how to use the setHeaders() in CBLReplication (ios)

### ISSUE THREAD

**Issue by RoronoaZoroLYS** [couchbase/couchbase-lite-ios#1543]
I want to make custom HTTP headers of replication process. On android, I get the replication firstly then set the headers. eg: `manager.getReplicator(properties).setHeaders(header);` How can I use the setHeaders() on ios. There is no getReplicator() available.

Thanks so much
--------
* Version:  1.3.1
* Client OS: ios

**Comment by pasin** [comment]
I don't think Manager.getReplicator(properties) is a public API for CBL Android. Please use `CBLDatabase`'s `-createPushReplication:`  or `-createPullReplication` to create a push or pull replication. From there you will get a `CBLReplication` object that you can set the header.
