### ISSUE TITLE
Crash when deleting the database

### ISSUE THREAD

**Issue by lucatorella** [couchbase/couchbase-lite-ios#1550]
While debugging my code, I experienced a crash when deleting the database. I should also add that I wasn't able to reproduce it.

The incriminated code is the following:
```
couchbaseQueue.async {
    do {
        _ = try self.database.delete()
    } catch ...
```
This code should not crash and instead it should raise an exception (or in the Obj-C world, it should "return" an NSError).

This is the stack trace:
```
#7	0x0000000105f11953 in cbforest::error::_throw(fdb_status) at CBForest/Error.cc:24
#8	0x0000000105f138f8 in cbforest::check(fdb_status) [inlined] at CBForest/Error.hh:59
#9	0x0000000105f138f1 in cbforest::Database::getKeyStore(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) const at CBForest/Database.cc:161
#10	0x0000000105f13c23 in cbforest::Database::updatePurgeCount() at CBForest/Database.cc:227
#11	0x0000000105f1355c in cbforest::Database::onCompact(unsigned int, char const*, fdb_doc_struct*, unsigned long long, unsigned long long) [inlined] at CBForest/Database.cc:405
#12	0x0000000105f1352a in cbforest::Database::compactionCallback(_fdb_file_handle*, unsigned int, char const*, fdb_doc_struct*, unsigned long long, unsigned long long, void*) at CBForest/Database.cc:385
```

And this is what I see in the console:
```
[FDB ERR] Error in UNLINK on a database file '.../couchbase.cblite2/db.forest.0', errno = 2: 'No such file or directory'
13:47:09.094‖ WARNING: ForestDB error: ForestDB handle is invalid (-30)
 {at FDBLogCallback:68}
libc++abi.dylib: terminating with uncaught exception of type cbforest::error
```

--------
* Version:   1.3.1
* Client OS: iOS 10.2

**Comment by snej** [comment]
Could I see more of the stack trace? There's a missing C++ try/catch block somewhere, but I think it goes below frame 12...

**Comment by snej** [comment]
It looks like this is a race condition, deleting the database right as it begins compaction. The crash is happening in a callback invoked by the compactor on a background thread.

**Comment by lucatorella** [comment]
Unfortunately I wasn't;t able to reproduce it, and I tried several times! :)

**Comment by snej** [comment]
Looks like the try/catch block belongs in cbforest::Database::compactionCallback.

**Comment by djpongh** [comment]
Refiled under cbforest:
 https://issues.couchbase.com/browse/MB-22537
