### ISSUE TITLE
Forest DB crash : when we are updating data

### ISSUE THREAD

**Issue by msanilkumar2020** [couchbase/couchbase-lite-ios#1553]
Hi,

We are getting this Forest DB crash when we are updating data.

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x00000000
Termination Signal: Segmentation fault: 11
Termination Reason: Namespace SIGNAL, Code 0xb
Terminating Process: exc handler [0]
Triggered by Thread:  15

Thread 15 name: CouchbaseLite
Thread 15 Crashed:
0 xxxxxxx 0x003d080a cbforest::MapReduceIndexer::startingSequence() (MapReduceIndex.cc:394)
1 xxxxxxx 0x003fbbbc c4indexer_enumerateDocuments (c4View.cc:285)
2 xxxxxxx 0x003acc3c -[CBL_ForestDBViewStorage updateIndexes:] (CBL_ForestDBViewStorage.mm:347)
3 xxxxxxx 0x00562096 -[CBLView updateIndexes:] (CBLView.m:287)
4 xxxxxxx 0x00561d5e -[CBLView _updateIndex] (CBLView.m:258)
5 xxxxxxx 0x0060f95c -[CBL_Router(Handlers) queryDesignDoc:view:keys:] (CBL_Router+Handlers.m:1182)
6 xxxxxxx 0x0060fc8c -[CBL_Router(Handlers) do_GET:designDocID:view:] (CBL_Router+Handlers.m:1218)
7 xxxxxxx 0x00606446 -[CBL_Router route] (CBL_Router.m:491)
8 xxxxxxx  0x00606c8c -[CBL_Router run] (CBL_Router.m:520)
9 xxxxxxx 0x00607fba __19-[CBL_Router start]_block_invoke (CBL_Router.m:742)
10 Foundation 0x1f27f30a __NSThreadPerformPerform + 386
11 CoreFoundation 0x1e916c8a _CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION_ + 12
12 CoreFoundation 0x1e916794 __CFRunLoopDoSources0 + 438
13 CoreFoundation 0x1e914a6a __CFRunLoopRun + 762
14 CoreFoundation 0x1e864072 CFRunLoopRunSpecific + 486
15 CoreFoundation 0x1e863e80 CFRunLoopRunInMode + 104
16 Foundation 0x1f1960da -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 260
17 xxxxxxx  0x00549d96 -[CBL_RunLoopServer runServerThread] (CBL_Server.m:193)
18 Foundation 0x1f27f0d0 _NSThreadstart_ + 1160
19 libsystem_pthread.dylib 0x1e1b8a16 _pthread_body + 216
20 libsystem_pthread.dylib 0x1e1b893c _pthread_start + 234
21 libsystem_pthread.dylib 0x1e1b6498 thread_start + 8

--------
* Version:   1.3.1
* Client OS: iOS 10

**Comment by pasin** [comment]
Close as duplicate with #1432.
