### ISSUE TITLE
Carthage based build for couchbase-lite-ios framework in project causes the Encryption not available issue.

### ISSUE THREAD

**Issue by manish-mobiuso** [couchbase/couchbase-lite-ios#1555]
I am facing this issue with encryption. I am using Carthage.

I have following line in my project Cartfile.

`github "couchbase/couchbase-lite-ios" "release/1.3.2"`

I have downloaded the libsqlcipher.a in my project but there are no symbols in my project app file. I have used libsqlcipher.a in my project

`WARNING: CBL_SQLiteStorage: encryption not available (app not built with SQLCipher) {at -[CBL_SQLiteStorage decryptWithKey:error:]:267}`

Anyone else facing this issue too?

This happens with **Carthage** to build Couchbase framework for the project I am using. Right now there is no instruction for the how to build project with Couchbase Lite iOS with SQLCipher support.

`$ nm CouchbaseLite | grep sql`
00000000000c91ab t +[CBL_FMDatabase sqliteLibVersion]
000000000006da45 t -[CBLDatabaseUpgrade initWithDatabase:sqliteFile:]
00000000000c91f0 t -[CBL_FMDatabase sqliteHandle]
00000000000b54d3 t -[CBL_SQLiteStorage sqliteHasRealEncryption]
000000000015f038 s _OBJC_IVAR_$_CBLDatabaseUpgrade._sqlite
00000000000cd600 t _sqlite3Fts3UnicodeSnTokenizer
000000000011a3f0 s _sqlite3Fts3UnicodeSnTokenizer.module
00000000000d4200 t _sqlite3FtsUnicodeFold
000000000010ea40 s _sqlite3FtsUnicodeFold.aEntry
000000000010ecd0 s _sqlite3FtsUnicodeFold.aiOff
00000000000d4120 t _sqlite3FtsUnicodeIsalnum
000000000010ea30 s _sqlite3FtsUnicodeIsalnum.aAscii
000000000010e3d0 s _sqlite3FtsUnicodeIsalnum.aEntry
00000000000d41c0 t _sqlite3FtsUnicodeIsdiacritic
000000000010d500 s _sqlite3Utf8Trans1
                 U _sqlite3_bind_blob
                 U _sqlite3_bind_double
                 U _sqlite3_bind_int
                 U _sqlite3_bind_int64
                 U _sqlite3_bind_null
                 U _sqlite3_bind_parameter_count
                 U _sqlite3_bind_text
                 U _sqlite3_busy_handler
                 U _sqlite3_changes
                 U _sqlite3_close
                 U _sqlite3_column_blob
                 U _sqlite3_column_bytes
                 U _sqlite3_column_count
                 U _sqlite3_column_double
                 U _sqlite3_column_int
                 U _sqlite3_column_int64
                 U _sqlite3_column_name
                 U _sqlite3_column_text
                 U _sqlite3_column_type
                 U _sqlite3_compileoption_used
                 U _sqlite3_config
                 U _sqlite3_create_collation
                 U _sqlite3_create_function
                 U _sqlite3_db_handle
                 U _sqlite3_errcode
                 U _sqlite3_errmsg
                 U _sqlite3_finalize
                 U _sqlite3_free
                 U _sqlite3_last_insert_rowid
                 U _sqlite3_libversion
                 U _sqlite3_libversion_number
                 U _sqlite3_malloc
                 U _sqlite3_mprintf
                 U _sqlite3_next_stmt
                 U _sqlite3_open_v2
                 U _sqlite3_prepare_v2
                 U _sqlite3_realloc
                 U _sqlite3_reset
                 U _sqlite3_result_double
                 U _sqlite3_sourceid
                 U _sqlite3_sql
                 U _sqlite3_step
                 U _sqlite3_stmt_readonly
                 U _sqlite3_threadsafe
                 U _sqlite3_value_blob
000000000006dda7 t _sqliteErrToStatus
0000000000163730 d _sqliteHasRealEncryption.hasRealEncryption

--------
* Version:  release/1.3.2
* Client OS: iOS 10, Xcode 8
* Server: NA

**Comment by snej** [comment]
This is mostly a limitation of Carthage.
* Carthage can only build dynamic libraries, not static ones. So the linking of SQLite happens during building the Couchbase Lite dylib, not while linking your app.
* There's no way to provide options to Carthage, i.e. to tell it to build with SQLCipher instead of SQLite.

To build with SQLCipher:

1. Build the iOS _static_ framework of Couchbase Lite according to the build instructions in the wiki.
2. Download a build of SQLCipher for iOS.
3. Link your app with Couchbase Lite and SQLCipher.

**Comment by snej** [comment]
…or you could just [download Couchbase Lite](https://www.couchbase.com/nosql-databases/downloads) instead of building it yourself.
