### ISSUE TITLE
Not all updates propagating while under load

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-ios#1558]
I'm not sure if this issue lives here but just a guess at the moment. 

During testfest today, using @jamiltz's new doc load tool, we found a scenario where doc updates fail to sync intermittently

Using:
- iOS 1.4-29
- Android 1.4-25

Sync Gateway
- 1.4-35 (DI)

Steps to repro:
- Add 5000 docs using the doc loader tool
- Check 5 docs in the list on the iOS device
- Stop doc load and wait for all docs to sync
- The other clients (Android) see 3-4 of the 5 updates.
- Reseting the app allows all the updates to sync. 

Todo:
- [ ] Find where in the system this inconsistency is happening

**Comment by pasin** [comment]
The issue could be either on iOS, Android, or SGW.

@sethrosetter have you also tested iOS to iOS?

**Comment by pasin** [comment]
From my conversation with @sethrosetter, iOS client can receive all of the updates from SGW and Android. Android Client missed some lists / tasks but after restarting the Android client, Android client can get all of the lists and tasks. Most likely the issue happens on the Android client side not iOS side. It could be at Replication, Live Query, or Android Todo app.

cc: @hideki

**Comment by hideki** [comment]
The ticket was transferred to couchbase-lite-java-core https://github.com/couchbase/couchbase-lite-java-core/issues/1572
