### ISSUE TITLE
Stop continuous CBLRestPusher requesting remote checkpoint every time the app comes into foreground

### ISSUE THREAD

**Issue by mglasgow** [couchbase/couchbase-lite-ios#1561]
Currently, a continuous push replication will suspend itself when the app goes into the background. When returning to the foreground, the CBLRestPusher will query the remote server to fetch the remote checkpoint. However, this generates unnecessary network traffic and uses more energy than required, waking up the device radios.

I think the push replication should be able to short-circuit fetching the remote checkpoint, if all the following conditions are true:
-the replication has already retrieved the remote checkpoint and _lastCheckpoint is populated
-the replication's unpushedDocumentIDs array is empty

Currently, [CBLRestReplicator goOnline] will clear the lastSequence then fetch it again from the remote server. However, perhaps it should be persisting the lastSequence value if the replication has already succeeded?

Am I right in thinking that if the replicator has nothing to push and the remote checkpoint is different, then fetching the remote checkpoint will not actually achieve anything?

I'm happy to tackle the changes after my logic above has been reviewed.

**Comment by mglasgow** [comment]
@snej If you're not taking any public api changes for v1.x branch anymore, I can implement this external to couchbase. That was my first thought - handle the app foreground/background and CBL database changed events myself and only start a continuous push when there is actually something to push. However, I think this improving this behaviour is something that would benefit the wider couchbase lite community.

**Comment by snej** [comment]
This doesn't sound like an API change, just an optimization of the behavior, right? At this point it isn't clear whether or not the existing replicator implementation will be used in 2.0 (the alternative is a hypothetical cross-platform C++ implementation), but even if we rewrite it we'll be using logic from the current implementation, so fixes would be useful.

Your logic seems sound. If you could implement this in a fork and post a pull request, I'd be glad to look at it.

**Comment by mglasgow** [comment]
Sure, I'll work on a fork and submit a PR when ready for review.

**Comment by jayahariv** [comment]
Closing 1.x issue!
