### ISSUE TITLE
iOS database failing to open with “Domain: SQLite Code: 11 NSLocalizedDescription: database disk image is malformed”

### ISSUE THREAD

**Issue by combinatorial** [couchbase/couchbase-lite-ios#1569]
Transferred from the[ forum thread](https://forums.couchbase.com/t/ios-database-failing-to-open-with-domain-sqlite-code-11-nslocalizeddescription-database-disk-image-is-malformed/11477)
 
We are seeing a rare issue reported (~0.15% of users) where a user starts our app and the app fails as the database can't open. For these devices we see the following on our error logging platform...

Domain: SQLite Code: 11 NSLocalizedDescription: database disk image is malformed

Restarting the app does not solve it. If they restart their device and wait for a period of time (1 minute is the shortest amount we have asked someone to wait so far), then it will then successfully open the database. If they open the app immediately on restarting they get the same error.

> What is the file protection entitlement of your app set to?
It is off

> Do you use database encryption (i.e. SQLCipher)?
No, we do not.

We do this when initializing Couchbase

    CBLManagerOptions options;
    options.fileProtection = NSDataWritingFileProtectionCompleteUntilFirstUserAuthentication;

--------
* Version:   1.3.2 https://github.com/tophatch/couchbase-lite-ios/tree/concepts/1.3.2_patched
* Client OS:  iOS 10.2 and 10.1.1
* Server:    sync-gateway:1.3.1-community, server:community-4.1.0

**Comment by combinatorial** [comment]
iOS 10.3 seems to have solved a lot of issues related to this, in the week since it has been out we are seeing many less SQLite and CBL file access errors.

**Comment by pasin** [comment]
Thanks a lot for sharing the information.

**Comment by pasin** [comment]
I'm closing this issue. Please reopen if the issue still exists.
