### ISSUE TITLE
CB 2.0 - exposing _rev(read only) and _deleted(soft delete)

### ISSUE THREAD

**Issue by househippo** [couchbase/couchbase-lite-ios#1570]
There are case in which know what version a document is can be helpful so it would be great to still have access to _rev as a "read-only" item in CB Mobile 2.0.

Many time people want to do a "soft delete". So mark a document as _deleted:true but still retain the JSON body content instead of creating a Tombstone only.

**Comment by snej** [comment]
Could you file these against the [couchbase-lite-api](https://github.com/couchbaselabs/couchbase-lite-api/issues) repo? That's where cross-platform API related stuff goes. Be sure to put something like "2.0" in the title. Thanks!

**Comment by snej** [comment]
Oh, and file them as two separate issues please.
