### ISSUE TITLE
DELETE database from REST api hangs [1.4-29]

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-ios#1573]
Delete database called from the REST api appears to hang.

--------
* Version:   http://latestbuilds.hq.couchbase.com/couchbase-lite-ios/1.4/ios/1.4-29/
* Client OS: iOS 10

**Comment by snej** [comment]
Can you include a backtrace or thread dump?
It sounds like you're saying this is 100% reproducible? Do you have a simple test case?

**Comment by npomfret** [comment]
I don't have a test case, not sure how to write them to be honest.  But I see lots of this in the logs:

`15:53:17.155‖ WARNING: <CBL_Shared: 0x60000002c8a0>: Still waiting to -forgetDatabaseNamed: "pc_0_93ce61b9-2a8e-460e-a758-2326abc3f399" {at -[CBL_Shared forgetDatabaseNamed:]:139}
`

**Comment by npomfret** [comment]
The problem might be that replication tasks are still running - could that cause it?  I have called `stop` on all the replication tasks but they still appear when calling `[database allReplications]`.

**Comment by jayahariv** [comment]
Closing 1.x issue!
