### ISSUE TITLE
[NSLock lock]: deadlock when deleting database (ForestDB)

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-ios#1579]
--------
* Version:   1.4-30 ForestDB
* Client OS: Mac OSX
* Server: N/A

Failing test - http://uberjenkins.sc.couchbase.com/job/macosx-listener-client-sync-gateway/93/testReport/junit/testsuites.listener.shared.client_sg/test_replication/test_multiple_replications_not_created_with_same_properties/

Seems to be a failure with deleting a database with multiple replications

Interesting output
```
2017-01-25 20:33:14.703 LiteServ[36219:102699806] *** -[NSLock lock]: deadlock (<NSLock: 0x7fd4bb623d30> '(null)')
2017-01-25 20:33:14.703 LiteServ[36219:102699806] *** Break on _NSLockError() to debug.
```

Mac OSX LiteServ logs - http://uberjenkins.sc.couchbase.com/job/macosx-listener-client-sync-gateway/93/artifact/results/logs/LiteServMacOSX-test_multiple_replications_not_created_with_same_properties-2017-01-25%2020%3A32%3A54.216661.txt

**Comment by djpongh** [comment]
@sethrosetter have you seen this again? We need a backtrace to figure this out.

**Comment by sethrosetter** [comment]
I have not seen this again.

**Comment by pasin** [comment]
Let's close the issue then.
