### ISSUE TITLE
2.0: Load blob contents lazily

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1581]
The initial implementation of CBLBlob reads the blob data into memory as soon as the CBLBlob property is accessed. Instead, we should delay reading the data until the caller asks for it by calling `CBLBlob.content` or `CBLBlob.contentStream`. This becomes important if the data is very large.

**Comment by borrrden** [comment]
Where is this happening?  I tried to be dutiful about this.  Actually I think the blob method is not named properly:  `dataForBlobWithDigest:error:` doesn't actually return the data, it returns a stream to the file.

**Comment by snej** [comment]
You're right; looking more closely I see that `-initWithProperties:...` takes a stream, and the CBLBlobStream passed in doesn't call `c4blob_openReadStream` until its `-open` method is called.
