### ISSUE TITLE
How to do pagination in Map by using GeoQuery ?

### ISSUE THREAD

**Issue by Tamil-Arya** [couchbase/couchbase-lite-ios#1582]
I need to do pagination in the **CATileLayer** ( Blue print Map ) by using GeoQuery. But there is no more info about GeoQuery.
**Scenario** : I implemented **blue print** using CATileLayer as Map for pointing particular location as well saving those data into the CouchDB. Now i have pointed more number of locations ( ex : 1000 location ) so now for this blue print i need to do pagination. 

Saved in CouchDB :
 "CBLQueryRow[key={\"x\":30.87646403819598,\"rev\":\"74-6f383edea147189085edfeb95be\",\"type\":\"Location\",\"y\":138.300981086858,\"zoom\":1,\"latitude\":37.785834,\"longitude\":-122.406417}; value=(null); id=F8CC0F5EDAC0495BA406ADD404523B0B]"
)
  "CBLQueryRow[key={\"x\":10.87646403819598,\"rev\":\"24-757af6f383edea147189085edfeb95be\",\"type\":\"Location\",\"y\":68.981086858,\"zoom\":3,\"latitude\":54.85675834,\"longitude\":-152.406417}; value=(null); id=CC0F5EDAC0495BA406ADD404523B0B]"
)

> look at the blueprint map & i referred below link but i couldn't get the prepare answer.

![screen shot 2017-01-27 at 10 52 49 am](https://cloud.githubusercontent.com/assets/13419184/22361365/d665db38-e47e-11e6-9b9f-58a8c230c7ff.png)

[https://github.com/couchbase/couchbase-lite-ios/wiki/Geo-Querying](url)
--------
* Version:   1.3
* Client OS: iOS 10
* Server:    CouchDB

**Comment by snej** [comment]
Hi! Please ask your question on the [Couchbase web forum](https://forums.couchbase.com/c/mobile) or the [Couchbase Mobile mailing list](https://groups.google.com/forum/#!forum/mobile-couchbase). We use Github issues only for bug reports and feature suggestions. Thanks.

**Comment by snej** [comment]
Generally you do pagination of a query by setting the `skip` and `limit` properties.
