### ISSUE TITLE
2.0: Link warnings about inconsistent Mac deployment targets

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1585]
Yesterday's LiteCore commit 3b0b5c22 to enable CI unit testing changes LiteCore's `MACOSX_DEPLOYMENT_TARGET` from 10.8 to 10.10 … this conflicts with the 10.8 setting in the CBL project, causing dozens of link warnings about inconsistent deployment targets.

@borrrden: was this change in LiteCore intentional? Changing the OS version requirement is something that we should coordinate with other teams like marketing, probably via Sachin.

I'll back out this specific change for now, since even if it's the right thing to do it shouldn't be made in the .pbxproj file, rather in Project.xcconfig.

**Comment by borrrden** [comment]
Oops. When I looked at it it was showing 8.0 so I thought "huh that's weird" and set it to 10.10 (two minor version back). It wasn't based on anything technical.
