### ISSUE TITLE
2.0 - Port Todo samples to use 2.0 API

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#1588]
This is in progress. I plan to port to both objective-c and swift (bridging). The Swift one should take a lot less time because we can reuse like 80% of the old code.

https://github.com/couchbaselabs/mobile-training-todo/tree/feature/2.0

**Comment by pasin** [comment]
- [x] Objective-c
- [ ] Swift
- [ ] Readme

**Comment by brendand** [comment]
Is this the recommended way of building apps now? Directly using CBLDocument instead of CBLModel? Or have you just not managed to re-create CBLModel in CBL 2.0 yet?

**Comment by pasin** [comment]
CBLModel is not scheduled in the DP1. We need to work on it, and it will definitely come. Thanks for checking.

**Comment by brendand** [comment]
Ok thanks. I'll have to wait until CBLModel is added. Will it be in DP2 then?

**Comment by snej** [comment]
We're not sure yet.
It's best to ask questions on the mailing list or forums, not here.
