### ISSUE TITLE
Assertion crash ForestDB

### ISSUE THREAD

**Issue by msanilkumar2020** [couchbase/couchbase-lite-ios#1594]
Hi, below crash is observed when we did network up and down.

Last Exception Backtrace:
0 CoreFoundation 0x18c2391b8 __exceptionPreprocess + 124
1 libobjc.A.dylib 0x18ac7055c objc_exception_throw + 56
2 CoreFoundation 0x18c23908c +[NSException raise:format:arguments:] + 104
3 Foundation 0x18ccf1098 -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 88
4 APP_NAME          0x1007366d4 _AssertFailed (Test_Assertions.m:31)
5 APP_NAME          0x10049aa0c CBL::err2status(C4Error) (CBLForestBridge.mm:211)
6 APP_NAME          0x10048b2c0 -[CBL_ForestDBStorage inTransaction:] (CBL_ForestDBStorage.mm:257)
7 APP_NAME          0x100491ae0 -[CBL_ForestDBStorage setInfo:forKey:] (CBL_ForestDBStorage.mm:897)
8 APP_NAME          0x100733250 -[CBLDatabase(Replication) setLastSequence:withCheckpointID:] (CBLDatabase+Replication.m:86)
9 APP_NAME          0x1006cf6c0 -[CBLRestReplicator clearDbRef] (CBLRestReplicator.m:137)
10 APP_NAME          0x1006d35ec -[CBLRestPuller stopped] (CBLRestPuller.m:186)
11 APP_NAME          0x1006d6838 -[CBLRestPuller insertDownloads:] (CBLRestPuller.m:771)
12 APP_NAME          0x1006ebe48 -[CBLBatcher processNow] (CBLBatcher.m:81)
13 Foundation 0x18cd3646c __NSFireDelayedPerform + 428
14 CoreFoundation 0x18c1e71d8 _CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION_ + 28
15 CoreFoundation 0x18c1e6eec __CFRunLoopDoTimer + 872
16 CoreFoundation 0x18c1e67a8 __CFRunLoopDoTimers + 244
17 CoreFoundation 0x18c1e43a4 __CFRunLoopRun + 1572
18 CoreFoundation 0x18c1122b8 CFRunLoopRunSpecific + 444
19 Foundation 0x18cc4f26c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
20 APP_NAME          0x1006cdb04 -[CBL_RunLoopServer runServerThread] (CBL_Server.m:193)
21 Foundation 0x18cd4ce68 _NSThreadstart_ + 1024
22 libsystem_pthread.dylib 0x18b2cd850 _pthread_body + 240
23 libsystem_pthread.dylib 0x18b2cd760 _pthread_start + 284
24 libsystem_pthread.dylib 0x18b2cad94 thread_start + 4

--------
* Version:   VERSION
* Client OS: NAME_AND_VERSION
* Server:    NAME_AND_VERSION

**Comment by pasin** [comment]
> case kC4ErrorAssertionFailed:
>                    Assert(NO, @"Assertion failure in CBForest (check log)");

Above where it causes the assertion failure crash. Could you please also provide the log? You may need to enable Database, Sync, and SyncVerbose logging?

**Comment by djpongh** [comment]
Were ever able to get logs?

Thanks

**Comment by msanilkumar2020** [comment]
@djpongh , Logs were disable at the time of crash. Now i am not able to reproduce this crash.

**Comment by djpongh** [comment]
Unfortunately without more info there's no place for us to go here. Please reopen if you can get logs when this happens again.
