### ISSUE TITLE
1.4 iOS reporting as 1.3 in user agent

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-ios#1601]
User-Agent: CouchbaseLite/1.3 (iOS 1.4/41eb2b9fadb337043f396ae085134c344444bee9)
--------
* Version:   1.4-35
* Client OS: iOS
* Server:   N/A

**Comment by pasin** [comment]
1.3 is the replicator protocol. We don't have anything changes since 1.3 so I think it's still correct to use 1.3.

**Comment by sethrosetter** [comment]
Great. Thanks!
