### ISSUE TITLE
2.0 - Set or change file protection level not affected

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#1606]
Setting or changing file protection level when opening a database doesn't work.

--------
* Version:   2.0-DP1
* Client OS: iOS 10.2, iPhone 6 Device

**Comment by jordanpwood** [comment]
I'm using couchbase 1.4.0 and I want to change the file protection of an existing database to `NSDataWritingFileProtectionCompleteUntilFirstUserAuthentication` so I can access it from the background.  Does this issue mean that that doesn't work for 1.4?  Is there a work-around I can use?  Will it work for 2.0?

**Comment by pasin** [comment]
There is a [PR](https://github.com/couchbase/couchbase-lite-ios/pull/1656) submitted for 1.4.

**Comment by djpongh** [comment]
removed API from 2.0
