### ISSUE TITLE
2.0 - CI, Build fat binaries for iOS, tvOS, and MacOS

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#1607]
Based on my conversation with @borrrden, current CI is building only simulator binaries. We need to make it fat and make sure that bitcode is in there. The easiest way to get the bitcode in the binary is to do archive instead of build.

For the DP1, we could use Carthage to manually build and release Or we can use Carthage to build the binary in CI as well.

**Comment by borrrden** [comment]
Actually we had been talking about two different things.  The CBL build can do whatever we want it to because it's (wastefully) rebuilding LiteCore from scratch at the moment.  Making things fat is still something that needs to be done though.

**Comment by borrrden** [comment]
Apparently Objective-C won't use the LiteCore builds I am making, so all I need is for someone to set up a fat target.  I will then switch the CI to use that instead.

**Comment by pasin** [comment]
OK, I will look into that fat target, but it will be in DP2.

**Comment by pasin** [comment]
I wrote two scripts that could be chose to use in the CI.

// Build FAT framework based on Scheme and Platform:
https://github.com/couchbase/couchbase-lite-ios/blob/feature/2.0/Scripts/build_framework.sh

// Build release zip file:
https://github.com/couchbase/couchbase-lite-ios/blob/feature/2.0/Scripts/generate_release_zip.sh
