### ISSUE TITLE
Crash in askDelegateToValidateServerTrust

### ISSUE THREAD

**Issue by combinatorial** [couchbase/couchbase-lite-ios#1613]
When running our own unit tests we sometimes get a crash in asynchronous tests inside askDelegateToValidateServerTrust.

The actual crash is in 

    - (BOOL) checkSSLServerTrust: (SecTrustRef)trust
                         forHost: (NSString*)host port: (UInt16)port
    {
        if (![_settings checkSSLServerTrust: trust forHost: host port: port])
            return NO;
        // Server is trusted. Record its cert in case the client wants to pin it:
        cfSetObj(&_serverCert, SecTrustGetCertificateAtIndex(trust, 0));
        return YES;
    }

By the time of the call to `SecTrustGetCertificateAtIndex` I think `trust` has been released.

Changing `askDelegateToValidateServerTrust` to retain/release trust fixes the crash.

    - (void) askDelegateToValidateServerTrust: (NSStream*)stream {
        if (!_serverUnvalidated)
            return;
        SecTrustRef trust = (__bridge SecTrustRef)[stream propertyForKey: (__bridge id)kCFStreamPropertySSLPeerTrust];
        NSAssert(trust != nil, @"Couldn't get SSL trust");
        CFRetain(trust);
        [self executeDelegate:^{
            BOOL ok = [_delegate webSocket: self validateServerTrust: trust];
            [self executeWork:^{
                CFRelease(trust);

--------
* Version:   1.3.2
* Client OS: iOS 10.2.1
* Server:    Couchbase 4.5.0

**Comment by pasin** [comment]
Thanks for investigating issue and providing the fix. The fix looks good to me.

**Comment by combinatorial** [comment]
For reference I found the stack for this crash from our main app, not the unit tests...

```
#8. Crashed: CouchbaseLite
0  libobjc.A.dylib                0x1800bef70 objc_msgSend + 16
1  Security                       0x181ac5ac8 SecTrustGetCertificateAtIndex + 80
2  ConceptsCore                   0x101100b08 -[CBLRestReplicator checkSSLServerTrust:forHost:port:] (CBLRestReplicator.m:660)
3  ConceptsCore                   0x101110230 -[CBLChangeTracker checkServerTrust:forURL:] (CBLChangeTracker.m:200)
4  ConceptsCore                   0x101189898 __59-[CBLWebSocketChangeTracker webSocket:validateServerTrust:]_block_invoke (CBLWebSocketChangeTracker.m:122)
5  Foundation                     0x182189048 __NSThreadPerformPerform + 340
6  CoreFoundation                 0x181622b5c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
7  CoreFoundation                 0x1816224a4 __CFRunLoopDoSources0 + 524
8  CoreFoundation                 0x1816200a4 __CFRunLoopRun + 804
9  CoreFoundation                 0x18154e2b8 CFRunLoopRunSpecific + 444
10 Foundation                     0x18208b26c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
11 ConceptsCore                   0x1010fca44 -[CBL_RunLoopServer runServerThread] (CBL_Server.m:193)
12 Foundation                     0x182188e68 __NSThread__start__ + 1024
13 libsystem_pthread.dylib        0x180709850 _pthread_body + 240
14 libsystem_pthread.dylib        0x180709760 _pthread_body + 282
15 libsystem_pthread.dylib        0x180706d94 thread_start + 4
```

**Comment by pasin** [comment]
Changes in PocketSocket has been merged to the master branch. Closed the issue now. Thanks!
