### ISSUE TITLE
2.0: Overhead of posting kCBLDocumentChangeNotification

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1614]
In early performance testing using Instruments, I noticed that a nontrivial fraction of the time to create or update a document is spent in NSNotificationCenter posting a `kCBLDocumentChangeNotification`. (It's been a week or so and I don't have the numbers anymore; it was something like 5-10%. I can re-run the test, but I wanted to record this before I forget to again.)

We should consider using a different notification mechanism, or maybe having documents only post these notifications on request (maybe via a boolean `postsChangeNotifications` property.)

I know that one of the reasons Apple created a new notification API for KVO in 10.3 was to make it lower-overhead than NSNotificationCenter. KVO allows an object to detect when observers are added, so it can skip posting notifications if there aren't any.

**Comment by djpongh** [comment]
Moved to: https://issues.couchbase.com/browse/CBL-280
