### ISSUE TITLE
2.0: Add threading support

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#1616]
1. Add dispatchQueue option to CBLDatabaseOptions.
2. Ensure to post notification on the database thread or on the dispatchQueue if specified.
3. Add doAsync: and doSync: method to the public API.

**Comment by borrrden** [comment]
I still oppose a user settable dispatch queue for access to the database because there is no way of ensuring that it is serial...

**Comment by borrrden** [comment]
Also there is no way to do thread safe async on .NET without a queue, so this won't be portable if we need two modes (or doAsync will need to throw an exception without a queue)

**Comment by pasin** [comment]
This issue is not applicable anymore.
