### ISSUE TITLE
error opening!: 23 - when trying to load data from iOS to Apple Watch

### ISSUE THREAD

**Issue by marbetschar** [couchbase/couchbase-lite-ios#1622]
I'm experiencing database connection errors while trying to read data from my Apple Watch from the CouchbaseLite database stored on the iOS device. The only thing I see is `error opening!: 23` in the Xcode log.

I'm guessing I got a similar error as the one described here: https://github.com/couchbase/couchbase-lite-ios/issues/1405

I've already tried to set the `CBLManager` options as follows - without any luck. Any other ideas?

```
let managerOptions = CBLManagerOptions.init(readOnly: false, fileProtection: .noFileProtection)
let managerOptionsPointer: UnsafeMutablePointer<CBLManagerOptions> = {
		let pointer = UnsafeMutablePointer<CBLManagerOptions>.allocate(capacity: 1)
		pointer.initialize(to: managerOptions)
		
		return pointer
	}()
try CBLManager(directory: CLSConfiguration.standard.directory, options:managerOptionsPointer)
```

--------
* Version:   1.3.2
* Client OS: iOS 10.2.1
* Server:    None

**Comment by marbetschar** [comment]
Ok; I was able to fix the issue. Here my solution for future reference:

1. Create a [Singleton](https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/AdoptingCocoaDesignPatterns.html) `CBLManager` with the FileProtection set to `.completeFileProtectionUntilFirstUserAuthentication`:

```
class Manager{
	static let standard: CBLManager? = {
		let options = CBLManagerOptions.init(readOnly: false, fileProtection: .completeFileProtectionUntilFirstUserAuthentication)
		let optionsPointer = UnsafeMutablePointer<CBLManagerOptions>.allocate(capacity: 1)
		pointer.initialize(to: options)
		
		do{
			return try CBLManager(directory: CBLManager.defaultDirectory(), options:optionsPointer)
		} catch let _{}
		return nil
	}()
}
```

2. In the `WCSessionDelegate` use the `backgroundTellDatabaseNamed` function in order to read from the database
```
func session(_ session: WCSession, didReceiveMessage message: [String : Any], replyHandler: @escaping ([String : Any]) -> Void){
	guard let manager = Manager.standard else{
		return replyHandler([:])
	}
	
	manager.backgroundTellDatabaseNamed("my-database-name"){ database in
		//do your stuff here...

		return replyHandler(...)
	}
}
```

**Comment by marbetschar** [comment]
Have to reopen this issue. The solution posted above is not guaranteed to work after the device was locked for quite some time.

To reproduce: If the device was locked for 15mins, the Apple Watch whether shows any data loaded from CBL nor does it display an error. It behaves like it's freezed.

That's why I assume in the above code, the `backgroundTellDatabaseNamed` throws an error and therefore the `replyHandler` in the `backgroundTellDatabaseNamed` completion block wont get executed.

So the question is: If the `.completeFileProtectionUntilFirstUserAuthentication`, why does the `backgroundTellDatabaseNamed` throws an error in the above scenario?

**Comment by pasin** [comment]
In 1.3, we have a bug that changing file protection level doesn't affect to all files. Do you happen to change the file protection level?

**Comment by marbetschar** [comment]
@pasin indeed, I've changed the file protection level. I've read about this bug earlier if I thought it it only affects attachments?

How may I fix the issue?

**Comment by pasin** [comment]
You can build the binary from the master branch or release/1.4.0 branch or grab a pre-release 1.4.0 binary from [here](http://latestbuilds.hq.couchbase.com/couchbase-lite-ios/1.4.0/ios/1.4.0-3). Let me know if that fixes the issue.

**Comment by pasin** [comment]
Actually, if the top level folder file protection level has already been changed, using 1.4.0 will not help. So along with using 1.4.0, you will need to change the file protection to something else and then changing it again to `completeFileProtectionUntilFirstUserAuthentication`.

**Comment by marbetschar** [comment]
@pasin is the branch release/1.4.0 production ready?

**Comment by pasin** [comment]
Yes, it's production ready.

**Comment by marbetschar** [comment]
@pasin did what you suggested:

1. Updated to Couchbase Lite iOS `release/1.4.0`
2. Changed the file protection level to `.noFileProtection`
3. Changed the file protection level back to `.completeFileProtectionUntilFirstUserAuthentication`

Unfortunately the app does not start anymore now - it crashes right in the beginning. The only output i see is:

```
2017-03-03 13:38:56.811214 Valletti[563:225889] [DYMTLInitPlatform] platform initialization successful
2017-03-03 13:38:57.170452 Valletti[563:225760] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2017-03-03 13:38:57.179072 Valletti[563:225760] [MC] Reading from public effective user settings.
(lldb) 
```

How to solve/debug this?

**Comment by marbetschar** [comment]
Finally I was able to track down the error - this is what I get:

```
Error Domain=NSCocoaErrorDomain Code=257 "Die Datei „.com.apple.mobile_container_manager.metadata.plist“ konnte nicht geöffnet werden, da du nicht die Zugriffsrechte hast, um sie anzuzeigen." UserInfo={NSFilePath=/private/var/mobile/Containers/Shared/AppGroup/581E3E30-4ABE-479F-B3E8-DD24BFE1FE2D/.com.apple.mobile_container_manager.metadata.plist, NSUnderlyingError=0x17424bd90 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
```

Basically it's saying I'm not permitted to open the file `.com.apple.mobile_container_manager.metadata.plist`

**Comment by marbetschar** [comment]
As a temporary workaround, I switched back to `. noFileProtection ` - everything works fine in this mode. What's wrong?

**Comment by pasin** [comment]
Are you setting a dir to the manager or using the default one? Can you check what is your db location? IIRC, if enabling Database logging, it will print out the db location.

**Comment by marbetschar** [comment]
The directory is set to a app group directory by using:

```
let appGroupDirectoryPath = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: "group.valletti")
```

Which is then used to initialize a `CBLManager` (options are set as described in the first post of this issue):

```
CBLManager(directory: appGroupDirectoryPath, options:options)
```

**Comment by pasin** [comment]
Thanks for the information. The current logic is trying to change the file permission of all the files under the directory set to the Manager. We need to fix this by only changing the database files.

**Comment by marbetschar** [comment]
Your welcome!

So, till a new version is done the only thing which works is setting the persmissions to .noFileProtection ?

Any ETA of a fixed version?

**Comment by npomfret** [comment]
@marbetschar have you found that using `noFileProtection` is the most reliable solution?

**Comment by marbetschar** [comment]
@npomfret I'm using `.noFileProtection` in production. Not tested the new fix yet.
