### ISSUE TITLE
2.0: Swift, ambiguous use of 'subscript' when accessing optional property

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#1634]
Accessing optional property with subscription as follows cause `ambiguous use of 'subscript'` compilation error:

var i1 = doc["abc"] as? Int
var i2: Int? = doc["abc"] as? Int

var a1 = doc["abc"] as? Any
var a2: Any? = doc["abc"] as? Any
var a3: Any? = doc["abc"]

Currently the way to do this is to use the property method instead of subscription.

**Comment by pasin** [comment]
`var i1: Int? = doc["abc"]` doesn't cause error but the result of i1 is 0.

**Comment by pasin** [comment]
Adding the following, fix `var i1: Int? = doc["abc"]` but still not the case with `as?`. 

```
public subscript(key: String) -> Int? {
        get {return _impl.object(forKey: key) as? Int}
        set {_impl.setObject(newValue, forKey: key)}
    }
```

**Comment by pasin** [comment]
One solution would be implementing a similar API to https://github.com/SwiftyJSON/SwiftyJSON.

I did a pass on this. I got the getter path working nicely but I'm not sure about the setting part that requires users to create a Value or PropertyValue object and pass the actual value. I will try to do a bit more research one this.

**Comment by pasin** [comment]
Look like in Swift 4.0, the subscription can have generic parameters that could be useful here.

**Comment by snej** [comment]
I agree that following SwiftyJSON might be a better approach. (There are a couple of other Swift JSON APIs too, that we could look at.)

**Comment by pasin** [comment]
As we moved on to the Fragment API, the issue is not valid anymore.
