### ISSUE TITLE
[CBLMultipartDownloader description] crash while printing logs

### ISSUE THREAD

**Issue by msanilkumar2020** [couchbase/couchbase-lite-ios#1637]
Hi,
We are getting this crash when multiple media messages received at a time.

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x000000000000004a
Termination Signal: Segmentation fault: 11
Termination Reason: Namespace SIGNAL, Code 0xb
Terminating Process: exc handler [0]
Triggered by Thread:  20

Thread 20 name:  Dispatch queue: NSOperationQueue 0x170429fc0 :: NSOperation 0x17024b220 (QOS: DEFAULT)
Thread 20 Crashed:
0   CFNetwork                     	0x00000001877e4840 CFURLRequestGetURL + 32
1   CFNetwork                     	0x00000001877e4834 CFURLRequestGetURL + 20
2   AT&T EPTT                     	0x000000010068cadc -[CBLMultipartDownloader description] (CBLMultipartDownloader.m:49)
3   Foundation                    	0x0000000187b5cb14 _NSDescriptionWithLocaleFunc + 108
4   CoreFoundation                	0x000000018711223c __CFStringAppendFormatCore + 7996
5   CoreFoundation                	0x00000001871102c8 _CFStringCreateWithFormatAndArgumentsAux2 + 244
6   AT&T EPTT                     	0x000000010067ca60 _Logv (MYLogging.m:225)
7   AT&T EPTT                     	0x000000010067cbc0 MYLogTo (MYLogging.m:290)
8   AT&T EPTT                     	0x00000001006b4540 -[CBLRemoteSession URLSession:task:didCompleteWithError:] (CBLRemoteSession.m:331)
9   CFNetwork                     	0x000000018791dbd0 __51-[NSURLSession delegate_task:didCompleteWithError:]_block_invoke.185 + 72
10  Foundation                    	0x0000000187c3ffb0 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
11  Foundation                    	0x0000000187b84aa8 -[NSBlockOperation main] + 96
12  Foundation                    	0x0000000187b750a4 -[__NSOperationInternal _start:] + 620
13  Foundation                    	0x0000000187c4235c __NSOQSchedule_f + 228
14  libdispatch.dylib             	0x0000000185fda1bc _dispatch_client_callout + 16
15  libdispatch.dylib             	0x0000000185fe83dc _dispatch_queue_serial_drain + 928
16  libdispatch.dylib             	0x0000000185fdd9a4 _dispatch_queue_invoke + 652
17  libdispatch.dylib             	0x0000000185fea34c _dispatch_root_queue_drain + 572
18  libdispatch.dylib             	0x0000000185fea0ac _dispatch_worker_thread3 + 124
19  libsystem_pthread.dylib       	0x00000001861e32a0 _pthread_wqthread + 1288
20  libsystem_pthread.dylib       	0x00000001861e2d8c start_wqthread + 4

--------
* Version:  CBL 1.3.1
* Client OS: iOS 10.2

**Comment by pasin** [comment]
As this is crash when logging, a quick workaround is to disable logging in production.

**Comment by pasin** [comment]
This have the same root cause as https://github.com/couchbase/couchbase-lite-ios/issues/1572. Let's track this issue on #1572
