### ISSUE TITLE
Initial Sync Is Slow, Any way to download the whole thing in 1 hit somehow?

### ISSUE THREAD

**Issue by skela** [couchbase/couchbase-lite-ios#1641]
I'm finding the initial sync when you try to open a database that has a lot of records can be a bit slow, as it seems to be doing it record by record. My guess is that even with some kind of intelligent batching here, there will always be situations where there is simply too many records. 

So what I want to do is to somehow download the whole database in 1 request.
How would I go about doing that? Is it even possible?

**Comment by pasin** [comment]
How many docs that the app needs to sync first time? Are those docs static so that they can be packed inside the app?

**Comment by pasin** [comment]
I think this is more like a question. Can you post the question in forums.couchbase.com? Thanks.

**Comment by skela** [comment]
The docs are not static no, and we are talking about 20,000+ docs. I don't think this is a question no, because at present the initial sync is very slow, and its not because of the total amount of MB, but rather the vast amount of docs and in many cases number of revisions per doc. It is not a question, this is a limitation of the SDK that should really be addressed.

**Comment by pasin** [comment]
Could you please give more info?
- What is the average doc size (and min/max)?  
- What is the average attachment size (and min/max)?
- How many revisions does each doc normally have?
- What is the network type and condition?
- How long does it take to do the initial sync?
- What is the CBL version and SGW version?
