### ISSUE TITLE
2.0: XCode cannot generate Swift codes when using CouchbaseLiteSwift via cocoapods

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#1647]
When doing Command-Click on the CBL Class name, XCode cannot generate Swift Representation with Error as 

```
Error (from SourceKit): "Could not load module: CouchbaseLiteSwift"
```

I believe this is due to how Cocoapods links with the Swift vendor framework. If I use the framework directly (not via Cocoapods), there is no issues.

**Comment by pasin** [comment]
Maybe something to do with https://guides.cocoapods.org/syntax/podspec.html#module_map.

**Comment by djpongh** [comment]
@pasin is this still the case?

**Comment by djpongh** [comment]
bug in cocopods
