### ISSUE TITLE
Purge does not remove row from 'docs' table

### ISSUE THREAD

**Issue by djpongh** [couchbase/couchbase-lite-ios#1648]
When a document is purged, its entry is not removed from the SQLite docs table. In fact nothing removes rows from this table, so over time, if lots of docs with UUIDs are created and purged, the table will grow monotonically. (See internal bug report). My commentary from there:

I think I remember what led to this. For speed, every CBLDatabase instance keeps an in-memory cache of some of the mappings from the docs table. That means that removing a row from the table would require some nasty multithreaded cache-invalidation. Instead I punted on that, figuring that the table is small (each row is just the docID string and an integer primary key) so it would take a long time to affect performance, and this was the kind of performance problem that we could hold off on fixing until/unless someone actually hit it in real life. Sounds like that's happened :-/ ...
This affects all three of our platforms. But it will not affect LiteCore or CBL 2.0 as the schema is entirely different.

**Comment by JFlath** [comment]
https://github.com/couchbase/couchbase-lite-net#827
https://github.com/couchbase/couchbase-lite-java-core/issues/1608

**Comment by pasin** [comment]
iOS doesn't have the issue as removing the doc from the docs table is the only thing that it is current doing (see [here](https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CBL_SQLiteStorage.m#L2360-L2368)). The `couchbase-lite-java-core` does have the issue.
