### ISSUE TITLE
missing role appears to cause continuous push replication to stop [v1.4]

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-ios#1649]
If I client attempts to edit a document for which they are not permission using roles i see the "missing role" error message in the sync gateway and iOS logs as you would expect.  What appears to be happening after is that no more changes that the client makes are pushed to the sync gateway.  It's as if the pull replication process stops completely.  Is this intended behaviour?

Here are the logs: https://gist.github.com/npomfret/359800d530ef07b539fdbf52c9acdbbb

**Comment by pasin** [comment]
From the log, it seems like there is a bug when uploading the multipart document that doesn't ignore the status forbidden. Sending _bulk_docs seems to be able to handle that.

**Comment by npomfret** [comment]
What do you mean? Is this a bug?  Or am i doing something wrong.  FYI - i'm only using the REST api.

**Comment by pasin** [comment]
I believe it's a bug in CBL.

**Comment by npomfret** [comment]
Thanks @pasin 

It occurs to me that it's becoming quite a serious problem.  You see, if a client is offline they may not have the right information, and so may attempt to make changes to documents which they 'think' are allowed.  But when that change hit's the sync gateway it gets rejected, because the SG is using more up to date information.

So my clients die - through no fault of there own, and through no programming error on my part.

**Comment by pasin** [comment]
Marked as a potential cross-platform error.

**Comment by npomfret** [comment]
Hi - has there been any progress on this issue?

**Comment by pasin** [comment]
It's still waiting for code review. https://github.com/couchbase/couchbase-lite-ios/pull/1657
