### ISSUE TITLE
Error Domain=CBLHTTP Code=400 "Invalid database/document/revision ID"

### ISSUE THREAD

**Issue by leonardo-hammer** [couchbase/couchbase-lite-ios#1652]
I getting started with couchbase lite  iOS, and follow the document that ['Couchbase Mobile - Training - Create a Database'](https://developer.couchbase.com/documentation/mobile/1.3/training/develop/create-database/index.html)

This is my all code about open database, it with a option call create that true.

```swift
func openDatabase(userName: String) throws {
    let options = CBLDatabaseOptions()
    options.create = true
        
    try database = CBLManager.sharedInstance().openDatabaseNamed(userName, with: options)
}
```

But, just this simple code occur a Error. 

**Error Domain=CBLHTTP Code=400 "Invalid database/document/revision ID"**

What is I missing? 
What's wrong with my code?

Thanks every help!

--------
* Version:   'couchbase-lite-ios', '~> 1.3.1'
* Client OS: iOS 10.2.1, macOS 10.12
* Server:    None

**Comment by leonardo-hammer** [comment]
Added these Linked Frameworks and Libraries, but error still occur.

- CFNetwork.framework
- Security.framework
- SystemConfiguration.framework
- libsqlite3.tbd
- libz.tbd
- libc++.tbd

**Comment by pasin** [comment]
Could you please check your database name? 

From the [documentation](https://developer.couchbase.com/documentation/mobile/1.3/guides/couchbase-lite/native-api/database/index.html):
```
Database names cannot contain uppercase letters! The only legal characters are lowercase ASCII letters, digits, and the special characters _$()+-/
```

**Comment by leonardo-hammer** [comment]
@pasin Thanks so much! It's worked!
