### ISSUE TITLE
2.0 - error on creating DB

### ISSUE THREAD

**Issue by Fujio-Turner** [couchbase/couchbase-lite-ios#1654]
https://forums.couchbase.com/t/couchbase-lite-2-0-db-creation-error/11988

I'm getting error when creating a DB in CBL 2.0. In the if statement it always returns false.

```

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    
    NSError *error;
    NSString *dbName = @"db";
    
    _database = [[CBLDatabase alloc] initWithName:dbName error:&error];
    if (! _database) {
        NSLog(@"Cannot open the database: %@", error);
        return NO;
    }

}
```

OUTPUT: 
`2017-03-06 18:06:54.513 cb-2.0-dp1[74243:5428445] Cannot open the database: (null)
`

I'm using this https://github.com/couchbaselabs/mobile-training-todo/tree/feature/2.0/objc/Todo as an example.

**Comment by pasin** [comment]
I created a new fresh iOS project with 2.0DB002, copied the code above, run on both simulator and 
device but I couldn't reproduce the issue.

Would it be possible to attach the sample project that reproduces the issue?

**Comment by Fujio-Turner** [comment]
@pasin 

Looks like it was a library dependency issue as I was trying to run and install 2.x like 1.x.

Closing
