### ISSUE TITLE
2.0: Query with Distinct=YES doesn't have distinct effect

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#1669]
Test with NSPredicate Query:

```
- (void) test_SelectDistinct {
    for (int i = 0; i < 10; i++) {
        NSError* error;
        CBLDocument* doc = [self.db document];
        doc[@"number"] = @(1);
        Assert([doc save: &error], @"Error when creating a document: %@", error);
    }
    
    CBLQuery *q = [self.db createQueryWhere: nil];
    q.returning = @[@"number"];
    q.distinct = YES;
    Assert(q);
    NSLog(@"%@", [q explain: nil]);
    uint64_t numRows = [self verifyQuery: q test: ^(uint64_t n, CBLQueryRow *row) { }];
    AssertEqual(numRows, 1u);
}
```

Results: All 10 docs are returned.

Explain Plan:

```
2017-03-15 17:27:14.039 xctest[12618:34769790] SELECT DISTINCT sequence, key, meta, fl_value(body, 'number') FROM kv_default ORDER BY key LIMIT $limit OFFSET $offset
0|0|0| SCAN TABLE kv_default USING INDEX sqlite_autoindex_kv_default_1
0|0|0| USE TEMP B-TREE FOR DISTINCT
```
--------
* Version:   VERSION
* Client OS: NAME_AND_VERSION
* Server:    NAME_AND_VERSION

**Comment by pasin** [comment]
@borrrden do you get this test pass? What am I missing?

**Comment by borrrden** [comment]
I didn't get this test working.  I don't think the correct results are being returned from LiteCore.

**Comment by borrrden** [comment]
An analysis of this is that the underlying SQLite query is incorrect.  In this case it is getting translated to:

> SELECT DISTINCT sequence, key, meta FROM kv_default LIMIT $limit OFFSET $offset

That means that unless all three columns are unique (which is impossible since duplicate keys / sequences are not allowed) it won't be considered unique.

**Comment by borrrden** [comment]
I guess the bigger question here is "does SELECT DISTINCT make sense in our current model?"  It would only make sense if we are only optionally returning the document that the properties came from and have the result set also have key accessors since SELECT DISTINCT, by definition, needs to only select bits that are exactly the same as the others.  At that point there is no way to tell which document the properties came from.

**Comment by snej** [comment]
So because the query translator implicitly adds `sequence, key, meta` to the returned columns, that breaks `DISTINCT`? I guess that makes sense. I thought it would be a good idea to always return these so the query row object can point to the document, but I'll have to rethink that.

**Comment by snej** [comment]
This issue was moved to couchbase/couchbase-lite-core#81
