### ISSUE TITLE
Accelerator working in 1.4?

### ISSUE THREAD

**Issue by basememara** [couchbase/couchbase-lite-ios#1678]
We just deployed accelerator to our test server. However, it's acting strange such as querying records are `nil` when they are actually there. Turning off accelerator makes things work again.

Is the Accelerator integration ready in the iOS 1.4 version, or was this put off?
--------
* Version:   1.4.0
* Client OS: iOS 10.2.1
* Server:    Sync Gateway 1.4

**Comment by pasin** [comment]
Can you post this question on the SGW repo?
