### ISSUE TITLE
2.0: Missing Query API Pieces

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#1685]
The following are the missing pieces from the Cross Platform Query API that needs to suppport.

* Class Expression.Property extends Expression (We could support this when we implement JOINS)
* Expression.concat()        (Need to check if LiteCore already supports this or not)
* Expression.inQuery()       (Need LiteCore support for SubQuery)
* Expression.notInQuery() (Need LiteCore support for SubQuery)
* Expression.exist()            (Need LiteCore support for SubQuery)
* Expression.notExist()      (Need LiteCore support for SubQuery)
* Expression.group()          (Not clear if we still need it)
* Select also implements WhereRouter and OrderByRouter (Select without FROM feature)
* DataSource.Database.as() (We could support this when we implement JOINS)

**Comment by borrrden** [comment]
FYI:  I don't see a CONCAT operator in LiteCore (from QueryParserTables.hh).  I only see array_concat().

Group I imagine is still needed because we need a way to change order of operations.

**Comment by pasin** [comment]
I think we can close this.
