### ISSUE TITLE
2.0: database change notification not firing in objective-c

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-ios#1691]
With the code below, the database change notification doesn't fire. It might be something wrong with the example code maybe?

```objective-c
// create database
NSError *error;
CBLDatabase* database = [[CBLDatabase alloc] initWithName:@"my-database" error:&error];
if (!database) {
    NSLog(@"Cannot open the database: %@", error);
}
// database change listener
[[NSNotificationCenter defaultCenter] addObserverForName:kCBLDatabaseChangeNotification object:database queue:nil usingBlock:^(NSNotification * _Nonnull note) {
    NSArray* changes = note.userInfo[@"changes"];
    NSLog(@"array %@", changes);
}];
// create document
CBLDocument* document = [database document];
[document save:&error];
if (error) {
    NSLog(@"Cannot save document %@", error);
}
```

--------
* Version:   2.0 DB3
* Client OS: iOS 10
* Server:    N/A

**Comment by pasin** [comment]
I don't see anything wrong with code above. Will need to investigate.

**Comment by snej** [comment]
The notification won't be posted until the next runloop iteration; does your code run long enough for that to occur? (I.e. is this in a real app, or just a test that exits as soon as the above code completes?)

**Comment by jamiltz** [comment]
I must have overlooked something. Ran it again and works fine.
