### ISSUE TITLE
2.0: how to use the database change notification API in swift

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-ios#1692]
I was not able to find the NSNotification name to use to register for database changes in Swift (marked as X in the code sample below):

```swift
NotificationCenter.default.addObserver(forName: X, object: database, queue: nil) { (notification) in
    let changes = notification.userInfo!["changes"] as? [AnyObject]?
    print("array \(changes)")
}
```

--------
* Version:   2.0 DB4
* Client OS: iOS 10
* Server:    N/A

**Comment by pasin** [comment]
Can you see NSNotification.Name.cblDatabaseChange (from Objective-C)?

However I think that we may have a bug that the notification will not be notified as the database object that notifies the change is database.impl object. We could need to catch the changes and re-notified.

**Comment by jamiltz** [comment]
> Can you see NSNotification.Name.cblDatabaseChange (from Objective-C)?

Yes this compiles but I can't run the project at the moment because I upgraded to Xcode 8.3 (Swift 3.1) and DB3 was built for 3.0.x and I can't figure out how to create a project with DB4 :). So I can't say if it would fire the event or not.

**Comment by pasin** [comment]
It should work now.
https://github.com/couchbase/couchbase-lite-ios/blob/feature/2.0/Swift/Tests/NotificationTest.swift#L25-L52
