### ISSUE TITLE
2.0: empty userInfo in document change listener in objective-c

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-ios#1693]
When receiving a document change with 2.0 DB3, is the change posted as part of the userInfo? I was not able to retrieve it from it with the following example:

```objective-c
// create document
CBLDocument* document = [database document];
[document save:&error];
if (error) {
    NSLog(@"Cannot save document %@", error);
}
// document change listener
[[NSNotificationCenter defaultCenter] addObserverForName:kCBLDocumentChangeNotification object:document queue:nil usingBlock:^(NSNotification * _Nonnull note) {
    NSLog(@"change event for docID :: %@", [[note object] documentID]);
}];
// mutability
document.properties = @{
                        @"type": @"user",
                        @"admin": @FALSE,
                        @"address": @{
                                @"street": @"1 park street",
                                @"zip": @123456
                                }
                        };
[document save:&error];
NSLog(@"document type :: %@", document[@"type"]);
if (error) {
    NSLog(@"Cannot save document %@", error);
}
```

screenshot of the userInfo dictionary:

![image](https://cloud.githubusercontent.com/assets/2589337/24610787/d1caab62-1877-11e7-83bf-08cf4ed65657.png)

--------
* Version:   2.0 DB3
* Client OS: iOS 10
* Server:    N/A

**Comment by pasin** [comment]
From the code, we currently don't send any UserInfo. Will need to revise this as the API spec. Thanks!

**Comment by pasin** [comment]
The API is changed. Use the following function instead:
https://github.com/couchbase/couchbase-lite-ios/blob/feature/2.0/Swift/Tests/NotificationTest.swift#L25-L52

**Comment by mohsinsurani1** [comment]
> The API is changed. Use the following function instead:
> https://github.com/couchbase/couchbase-lite-ios/blob/feature/2.0/Swift/Tests/NotificationTest.swift#L25-L52

Link is not working

**Comment by jayahariv** [comment]
if you are looking for an example on change listener you can find that on [2.5 change listener](https://docs.couchbase.com/couchbase-lite/2.5/swift.html#document-change-events).
