### ISSUE TITLE
2.0: Swift replication delegate not functional

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-ios#1699]
Link to a class implementing the replication delegate - https://gist.github.com/sethrosetter/e83d4d227cb5c883a7d74231959208d8

Expected: Changes / error in the replicator trigger the delegate functions
Actual: The delegate functions never fire

After a quick review of this with @pasin, he believes since the internal ObjC delegates are weak, they are being removed from behind the Swift reference (not sure if I'm 100% accurately reporting this)  

--------
* Version:   2.0-DB004
* Client OS: iOS Swift
* Server:    Sync Gateway 1.4.1(292;d91d78f)

**Comment by snej** [comment]
Doing the bridging from the Obj-C to the Swift delegate was kind of tricky, but I _thought_ I got it right...

**Comment by pasin** [comment]
I looked at code with @sethrosetter briefly, and I think the issue is that the bridge is not set to `_bridge` after it gets created.

https://github.com/couchbase/couchbase-lite-ios/blob/feature/2.0/Swift/Replication.swift#L99-L101

**Comment by snej** [comment]
Think I fixed this in 37b961cff4d140b8d25633c8f5044c4c30151db5.
