### ISSUE TITLE
2:0 swift expression based query returning empty results

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-ios#1701]
The following creates a document and query.

```swift
// create database
let database: Database;
do {
    database = try Database(name: "my-database")
} catch let error as NSError {
    return NSLog("Cannot open the database: %@", error);
}
// create document
let document = database.document()
do {
    try document.save()
} catch let error {
    print(error.localizedDescription)
}
// mutability
document.properties = [
    "type": "user",
    "admin": false,
    "address": [
        "street": "1 park street",
        "zip": 123456
    ]
]
do {
    try document.save()
    print("document type :: \(document["type"] as String?)")
} catch let error {
    print(error.localizedDescription)
}

// standalone query
let query = Query
    .select()
    .from(DataSource.database(database))
    .where(
        Expression.property("type").match("user")
            .and(Expression.property("admin").match(false))
    )
do {
    let rows = try query.run()
    for row in rows {
        print("doc ID :: \(row.documentID)")
    }
} catch let error {
    print(error.localizedDescription)
}
```

On the last method call when the `query.run()` is called it throws the error message `no such table: kv_default::.type` to the console. Not sure if the code syntax above is incorrect or if it is a bug. No query index were created in this example.

--------
* Version:   2.0 DB4
* Client OS: iOS 10
* Server:    N/A

**Comment by pasin** [comment]
match is for full-text search so I'm not sure if that is the case of not. Can you change from match to equal?

**Comment by jamiltz** [comment]
Good catch, that's why it was throwing the error. Updated the example to use `equalTo`. However the expected results are not returned (i.e `rows` is empty). Keeping this open and will try again tomorrow.

**Comment by jamiltz** [comment]
@pasin the above example is working fine and the expected results are returned. However, in another query the result is empty again. Here it is:

```swift
let query = Query
    .select()
    .from(DataSource.database(database))
    .where(Expression.property("type").equalTo("airline"))

do {
    let rows = try query.run()
    print(rows.underestimatedCount)
    for row in rows {
        print("doc ID :: \(row.documentID)")
    }
} catch let error {
    print(error.localizedDescription)
}
```

Is the `type` property treated differently to other properties? The logs don't return anything (0 rows) but I'm sure some document with `type: "airline"` are present in the database.

**Comment by pasin** [comment]
@jamiltz is this still an issue?

**Comment by jamiltz** [comment]
That database with `airline`, `route`, `airport` and `landmark` documents contained 35 000 docs. Running a replication with 2.0 and then querying the database content resulted in those unexpected empty results. This issue was resolved by replicating the documents to a `.cblite2` file with CBL 1.4 and then opening the local database with 2.0 (which automatically upgrades the database to 2.0). There's strong indication that replicating the documents with 2.0 resulted in those empty results. But I don't know how to provide details on that. I'll use the `query.explain()` which I didn't try previously. What is the level of logging by default?

**Comment by pasin** [comment]
I understand that this is for travel sample app. @jamiltz  / @rajagp is this still an issue?

**Comment by jamiltz** [comment]
Haven't seen this issue happen again so I'll close the ticket.
