### ISSUE TITLE
1.x: Can speed up transactions with `PRAGMA synchronous=normal`

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1704]
If we're going to release any more versions of CBL 1.x, we could easily make transactions faster by issuing a SQLite call `PRAGMA synchronous=normal` when opening the DB. (We already do this in LiteCore for CBL 2.0.)

The SQLite docs say:
>When synchronous is NORMAL (1), the SQLite database engine will still sync at the most critical moments, but less often than in FULL mode. There is a very small (though non-zero) chance that a power failure at just the wrong time could corrupt the database in NORMAL mode. But in practice, you are more likely to suffer a catastrophic disk failure or some other unrecoverable hardware fault. Many applications choose NORMAL when in WAL mode.

>In WAL mode when synchronous is NORMAL (1), the WAL file is synchronized before each checkpoint and the database file is synchronized after each completed checkpoint and the WAL file header is synchronized when a WAL file begins to be reused after a checkpoint, but no sync operations occur during most transactions. With synchronous=FULL in WAL mode, an additional sync operation of the WAL file happens after each transaction commit. The extra WAL sync following each transaction help ensure that transactions are durable across a power loss. Transactions are consistent with or without the extra syncs provided by synchronous=FULL. If durability is not a concern, then synchronous=NORMAL is normally all one needs in WAL mode.

My interpretation of "If durability is not a concern" is that they're not talking about file corruption; they mean that the latest few transactions could be lost after a power failure (because the recently-written part at the end of the WAL file might not be intact.)

**Comment by jayahariv** [comment]
Closing 1.x issue!
