### ISSUE TITLE
add handling of OPTIONS request to the Listener

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-ios#1709]
Following a discussion with @snej, it appears that after enabling CORS on the listener (https://github.com/couchbase/couchbase-lite-ios/pull/1708), requests from a web app running in the browser (`localhost:3000`) to the listener (`localhost:59840`) are failing because the listener doesn't handle OPTIONS request. In cross origin requests, the browser tries to send an OPTIONS request first to see if the server supports CORS.

[Google Chrome logs](https://gist.github.com/jamiltz/940a60ca25b971dcd2bdfae756edd3d0#file-logs-L15-L30) (same in Safari)

**Comment by jamiltz** [comment]
@snej can you point me to the place in the repo to make that change? I will try and test it again. All it needs to do in the case of an OPTIONS request is to return a 200 I think, like the Java example in this comment https://github.com/couchbaselabs/Couchbase-Lite-PhoneGap-Plugin/issues/38#issuecomment-64202027

**Comment by snej** [comment]
It would go in CBLRouter+Handlers.m. If you just want to handle it for the root, you can add a method
`- (CBLStatus) do_OPTIONSRoot { ... }`. It can go right below the existing `-do_GETRoot`.

**Comment by sobuga** [comment]
Hello,

Did anyone tried to implement snej proposed solution ?

Best regards,
Cyril.

**Comment by climam** [comment]
I have implemented that function in CBL_Router+Handlers.m:

(CBLStatus) do_OPTIONS {
return kCBLStatusOK;
}

It does not solve the issue.

**Comment by djpongh** [comment]
Moved to Jira DOC-3013
