### ISSUE TITLE
Unable to add observer for userInfo property of Progress object while downloading an attachmnt

### ISSUE THREAD

**Issue by parvezq** [couchbase/couchbase-lite-ios#1712]
While implementing the observer for error from attachment downloading Progress, I am getting below compilation error:

**Value of type '[ProgressUserInfoKey : Any]' has no member 'addObserver'**

The above error comes in the last line of downloadAttachment function as shown below:

```
var downloadProgress: Progress?
var anAttachment: CBLAttachment?
var pullReplication: CBLReplication?

func downloadAttachment() {
   self.downloadProgress = self.pullReplication?.downloadAttachment(self.anAttachment!)
   self.downloadProgress?.addObserver(self, forKeyPath: "fractionCompleted", options: [.new,.old], context: nil)
   self.downloadProgress?.userInfo.addObserver(self, forKeyPath: "fractionCompleted", options: [.new,.old], context: nil)
}
```
If I omit the last line in above method (that is giving compilation error) then I will be unable to identify error (if any occurred) during attachment download.
I am using CocoaPods for Couchbase lite ios with below pod entry:

```
use_frameworks!
pod 'couchbase-lite-ios'
```
--------
* Version:   Couchbase lite version: 1.3.1 (build 6)
* Client OS: iOS 10.2 / Swift 3.0 / XCode 8.2

**Comment by snej** [comment]
`self.downloadProgress?` is a Cocoa NSProgress object, and its `userInfo` property is an NSDictionary. In Swift that's being represented as `[ProgressUserInfoKey : Any]`, and I guess native Swift dictionaries don't support KVO.

This doesn't have anything to do with Couchbase Lite ... it's a question about using KVO on NSProgress in Swift. I suggest asking on Apple's developer forum or the cocoa-dev mailing list.
