### ISSUE TITLE
Uploading attachment with size greater than 20MB seems not working

### ISSUE THREAD

**Issue by parvezq** [couchbase/couchbase-lite-ios#1713]
I have tried to upload zip files as attachment to the document. When document sizes are less than 20MB, then the attachments gets uploaded successfully. When size of attachment becomes greater than 20MB then I did not get any error in document save operation. I also wait for some time so that attachment can upload properly.

When I run the iOS application afresh then it shows the error
**Got error CBLHTTP[404, "missing", <http://172.26.248.125:4984/modules/-lYouZJj26r5vuBplPrx9fO/MyModule---lYouZJj26r5vuBplPrx9fO?rev=1-733dd60131e6c66250c473c74536b9dd>]**

I am able to verify that the respective document is visible in admin panel on the couchbase sever.
Below is the code snippet that is performing upload of attachment. It seems to me that attachment is getting failed to upload.

```
//Enabled ChangeTracker logging
CBLManager.enableLogging("ChangeTracker")
public class PackageModule: CBLModel{
    @NSManaged var moduleName: String!
    @NSManaged var created_at: String!
}

public func uploadZipFileAtPath(zipFilePath: String){
   let packageURL = URL(fileURLWithPath: zipFilePath) //zipFilePath is a path to a zip file inside the application bundle.
   let packageModule = PackageModule(forNewDocumentIn: self.database!)
   packageModule.type = "packageModule"
   packageModule.moduleName = "MyModule--" + (packageModule.document?.documentID)!
   packageModule.created_at = CBLJSON.jsonObject(with: Date())
   packageModule.setAttachmentNamed(packageModule.moduleName, withContentType: "application/zip", contentURL: packageURL)
       
   do{
       try packageModule.save()
        print("Module saved successfully.")
   }catch{
       print("Encountered error: \(error) while saving a package module information")
   }        
}
```
There is no error encountered while performing save operation. On couchbase server, is there a physical location / path where I can cross check that an attachment is uploaded or not?

--------
* Version:   Couchbase lite version: 1.3.1 (build 6)
* Client OS: iOS 10.2 / Swift 3.0 / XCode 8.2

**Comment by djpongh** [comment]
From: https://blog.couchbase.com/couchbase-lite-future-mobile-faq/

Q: Are there any known size limitations with Couchbase Lite or Sync Gateway?
A: We currently have a size limit of 20MB per JSON document, and 20MB per attachment. Beyond this, we do not have set limitations for how many documents can be sent over the wire, or how many channels you can create and use. However, we do have a couple of recommendations. For example, when routing data, developers should use roughly as many channels as they have users, and that each document should belong to no more than a handful of channels. Additionally, we also support deletion and purging of documents that can be used locally on Couchbase Lite for clean up.

**Comment by snej** [comment]
Couchbase Lite has no attachment size limitations. However, Sync Gateway does; that's what the limit in that blog post refers to.

The attachment has been saved to the local database. However it will fail to replicate to Sync Gateway.

>When I run the iOS application afresh then it shows the error

What API call does this error come from? The URL in the error message is from the Sync Gateway REST API, so this is an error from the replicator trying to pull the attachment. It's not a local error accessing the attachment in Couchbase Lite.
