### ISSUE TITLE
replication fails with 401 but session is valid

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-ios#1716]
https://forums.couchbase.com/t/sync-issue-please-help/12315/20
https://github.com/couchbase/sync_gateway/issues/1665
https://github.com/couchbase/couchbase-lite-android/issues/1077

I think there's an open issue on Android for this (or a very similar issue), but I couldn't see one in iOS (apologies of there is).  I've tried using wireshark to debug it...

So I'm using the REST API in CBL on iOS to issue a one shot pull replication.  My app creates a session with the sync gateway first:

`SyncGatewaySession=28e741c16f3c4a87be805d3426f4024b5748fbd3; path=/sync_gateway; domain=192.168.1.75; Max-Age=431999; Expires=Sun, 23-Apr-2017 09:55:55 GMT`

And then posts to `http://lite.couchbase./_replicate`.  The response is a 500 and the body contains: 

`{"status":401,"reason":"Login required","url":"http://192.168.1.75:4986/sync_gateway/_local/6feec6b9f104056bf867aa714ec239ba94080e4a","error":"unauthorized"}`

I don't understand how CBL works internally, and so I've no idea what this _local_ document is or what it's used for.  But, the header used to request it contains the wrong cookie:

![screen shot 2017-04-18 at 11 06 14](https://cloud.githubusercontent.com/assets/5489469/25125556/28cfa1be-2427-11e7-9265-07e9afe78c95.png)

Where does this cookie come from?  I can't see any other relevant traffic before this, I guess it's stored on my device somewhere?  ...If I delete the entire DB it starts working again.

I *think* I managed to create this situation by changing a users password and deleting all of their existing sessions.

Using sync-gateway-community_1.4-273 and couchbase-lite-ios-community_1.4-44.

**Comment by pasin** [comment]
@hideki have found the root cause which I believe iOS has the same issue.

Close as dup with https://github.com/couchbase/couchbase-lite-ios/issues/1715.

**Comment by npomfret** [comment]
Great.  Can you post here where there is a fix to test?
