### ISSUE TITLE
Where is version 1.4.0 release/tag? 

### ISSUE THREAD

**Issue by sundeepgupta** [couchbase/couchbase-lite-ios#1719]
The latest release on Couchbase's [download page](https://www.couchbase.com/downloads) is 1.4. However, there is no release or tag for 1.4. I see 1.3.1 and the 2.x pre-releases. Can someone point me to the commit or help me check out 1.4 code?

**Comment by pak-amsiq** [comment]
Please add 
pod 'couchbase-lite-ios', '~> 1.4' 
to your Podfile

**Comment by pasin** [comment]
Here is the release branch https://github.com/couchbase/couchbase-lite-ios/tree/release/1.4.0.

I need to check about the tag.

**Comment by pasin** [comment]
OK, the release tag has been regenerated.

https://github.com/couchbase/couchbase-lite-ios/releases/tag/1.4.0
