### ISSUE TITLE
Query : Difference between enterprise and community edition in CBLClient

### ISSUE THREAD

**Issue by msanilkumar2020** [couchbase/couchbase-lite-ios#1723]
Hi,

Is there any difference between Enterprise edition community edition in CBLClient(CBLiOS/CBL android client).

I can make out difference in CBLServer but not the CBLClient from below link.
https://forums.couchbase.com/t/couchbase-community-vs-enterprise-features-comparison/2447

**Comment by NitzDKoder** [comment]
@hideki 

See that no change in android code perspective..see the image attached..

![code_diff_android](https://cloud.githubusercontent.com/assets/1461456/25473743/3d06393a-2b4e-11e7-8634-d0c328b033c4.PNG)

pls confirm how is the support system work for any issues?


Thanks
Nithin

**Comment by pasin** [comment]
No differences in terms of feature at this point.
