### ISSUE TITLE
'sqlite3_unicodesn_tokenizer.h' file not found 

### ISSUE THREAD

**Issue by ufosky** [couchbase/couchbase-lite-ios#1743]
I use carthage to build the version 'release/1.4.0', but got a exception.

```
/Users/.../ios/Carthage/Checkouts/couchbase-lite-ios/Source/CBL_SQLiteStorage.m:33:9: fatal error: 'sqlite3_unicodesn_tokenizer.h' file not found
#import "sqlite3_unicodesn_tokenizer.h"
        ^
1 error generated.
```
--------
* Version:   release/1.4.0
* Client OS: N/A
* Server:    N/A

**Comment by pasin** [comment]
Please make sure to run 'carthage update --platform iOS' to just carthage update.
