### ISSUE TITLE
Backgrounding Task Fails in iOS App when App Pushed to Background

### ISSUE THREAD

**Issue by rajagp** [couchbase/couchbase-lite-ios#1744]
--------
* Version:   CBL 1.4
* Client OS: iOS 9/10 , Xcode 8.3
* Server:    N/A

Steps to reproduce
- Use GrocerySync App. https://github.com/couchbaselabs/Grocery-Sync-iOS  (Issue happens with any iOS app)
- Enabled detailed logging
- Launch the App 
 - Push it to background. 

Observed the following  :

SIDE NOTE (FYI): This poses to be a bigger issue with iOS App Extensions because the replicator is suspended because of this particular issue even if the extension is running. However, if we can debug this background task failure in the general app case, that would solve the issue with app extensions as well. 
It is a separate question as to why backgrounding is attempted even when the App Extension is running but we can treat that as a separate topic. 

```

22:22:20.559| Sync: CBLRestPusherhttp://localhost:4984/grocery-sync/: App backgrounding, but can't run background task; suspending
22:22:20.559‖ Sync: CBLRestPusherhttp://localhost:4984/grocery-sync/: SUSPENDING
22:22:20.559‖ Sync: CBLRestPusherhttp://localhost:4984/grocery-sync/: Reachability state = <localhost>:reachable (02), suspended=1
22:22:20.559‖ Sync: CBLRestPusherhttp://localhost:4984/grocery-sync/: Going offline
22:22:20.559‖ RemoteRequest: Stopping 0 remote requests
22:22:20.560‖ Sync: CBLRestPusherhttp://localhost:4984/grocery-sync/: postProgressChanged (1/1, active=0 (batch=0, net=0), lastSeq=18, online=0, error=(null))
22:22:20.560| Sync: CBLRestPullerhttp://localhost:4984/grocery-sync/: App backgrounding, but can't run background task; suspending
22:22:20.560‖ Sync: CBLRestPullerhttp://localhost:4984/grocery-sync/: SUSPENDING
22:22:20.560‖ Sync: CBLRestPullerhttp://localhost:4984/grocery-sync/: Reachability state = <localhost>:reachable (02), suspended=1
22:22:20.560‖ Sync: CBLRestPullerhttp://localhost:4984/grocery-sync/: Going offline


```

[log.txt](https://github.com/couchbase/couchbase-lite-ios/files/976957/log.txt)

**Comment by snej** [comment]
This is a regression … has something changed in iOS, like some new way to mark an app as eligible to run in the background? Or did we break something in CBL?

**Comment by rajagp** [comment]
I checked the docs and I don’t believe anything has changed in iOS w.r.t Background Tasks (In fact, like Background fetches, no special capabilities declaration is needed for BG tasks).

So I wrote a test app without Couchbase and I was able to run a task in background successfully using the code snippet below - 
 
   func runBackgroundTask() {
	// Start bg task
        self.backgroundUpdateTask = UIApplication.shared.beginBackgroundTask(expirationHandler: {
            if self.backgroundUpdateTask != UIBackgroundTaskInvalid
            {
                print("BG Task Ended")
                UIApplication.shared.endBackgroundTask(self.backgroundUpdateTask)
                 self.backgroundUpdateTask = UIBackgroundTaskInvalid;
            }
            else {
                print("Backgrounding invalid")
            }
        })
            

        let _ = Timer.scheduledTimer(timeInterval: 10, target: self, selector: #selector(AppDelegate.runningInBG), userInfo: nil, repeats: true)
         // End the background task.
        UIApplication.shared.endBackgroundTask(self.backgroundUpdateTask)
        self.backgroundUpdateTask = UIBackgroundTaskInvalid
       
    }
    
    func runningInBG() {
        print(#function)
        
    }

**Comment by pasin** [comment]
From the [source code](https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CBLRestReplicator%2BBackgrounding.m#L83-L91), I think the reason that the background task cannot be started because _active = NO (meaning that the replicator is idle).

**Comment by rajagp** [comment]
OK. So what I gather is that if I were having active data transfers when I pushed the app to BG, the  BG task would have started. Makes sense. 
I have raised a somewhat related issue w.r.t iOS App Extensions https://github.com/couchbase/couchbase-lite-ios/issues/1779 .

**Comment by pasin** [comment]
I don't think this is an issue. When background task is used for extending the unfinished replication activities when pushing the app into the background. By default the replication will be suspended when the application is in background. To make the replicator working in the background, the app needs to manually switch the replicator.suspended flag to NO when the app entered into the background.
