### ISSUE TITLE
Query : Background support - uploading/downloading  attachment while application is in background

### ISSUE THREAD

**Issue by msanilkumar2020** [couchbase/couchbase-lite-ios#1747]
Hi,

Do we support uploading/downloading attachment while application is in background.

NSURLSession support background upload/download, from logs i can see application sync is stopped immediately entering background. Not utilizing background extended time(180sec).

Please let us know the existing CBL application attachment uploading/downloading desing when user enters background.

**Comment by pasin** [comment]
You will need to turn off suspended property on the replicator when the app entered the background mode. If you also want the database and replicator to work under the locked screen, you will need to make sure that you set the CBLManager's file protection level appropriately (e.g. noFileProtection or completeFileProtectionUntilFirstUserAuthentication).

**Comment by snej** [comment]
@pasin, turning off `suspended` is for when the application makes changes to the database while in the background. It sounds like in this case the changes were made while in the foreground, but the replicator isn't continuing to run.

This sounds similar to #1744 ... there seems to be a regression with CBL not being able to start a background task.

**Comment by msanilkumar2020** [comment]
@pasin / @snej 
In this case, before moving to background we have downloaded/uploaded attachment partially and application enter background. Replication will stop, upload/download will fail.

Once application becomes active whether download/upload will start from the place where it stopped or it will start from beginning(RFC 7233).

**Comment by msanilkumar2020** [comment]
@pasin  / @snej 
Do you have any update on this issue?

Thanks,
Anil Kumar

**Comment by pasin** [comment]
Sorry, there is no progress on this yet.

**Comment by pasin** [comment]
It seems like starting the replicator in background doesn't work at all as the app got suspended before CBL starts the background task. The problem is that CBL starts background task when the bg-replicator starts which seems to be too late for at least the case of using silent push notification.

**Comment by pasin** [comment]
The workaround would be having the application starts the background task immediately by itself after receiving the push notification and end the background task after the replicator is stopped.
