### ISSUE TITLE
Push replication becomes slower as local DB grows

### ISSUE THREAD

**Issue by djpongh** [couchbase/couchbase-lite-ios#1751]
From: https://github.com/couchbase/couchbase-lite-java-core/issues/1623

**Comment by pasin** [comment]
iOS code has already done what .NET has fixed the performance of the push replicator (see [here](https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CBLRestPusher.m#L292-L296)). The iOS code is slightly different from .NET as there calling a method on a nil object will be evaluated as a false in if cause.

**Comment by pasin** [comment]
Close there is nothing to fix.
