### ISSUE TITLE
2.0: Suspicious overload

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-ios#1752]
Noticed in CBLDictionary and CBLReadOnlyDictionary, but it might be applicable in other places as well.  The call to arrayForKey: etc will end up calling objectForKey: which is overridden and might cause unintended effects, especially in a case like this:

CBLDictionary arrayForKey: doesn't have the entry in its dictionary so it calls
CBLReadOnlyDictionary arrayForKey: which calls
CBLDictionary objectForKey: which obviously still doesn't have the entry so it calls
CBLReadOnlyDictionary objectForKey: which then adds a change listener

But then, it adds a change listener (via CBLDictionary's objectForKey:) to the array again so it looks like two end up being added.  Maybe this is not the case, but it is suspicious.

**Comment by pasin** [comment]
I think your suspicious is correct. There will be 2 CBLArray created. One will not get used.

Probably the CBLReadOnlyDictionary arrayForKey shouldn't call objectForKey.
