### ISSUE TITLE
2.0 warning message when opening a database in a swift playground

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-ios#1753]
The following warning message is logged when opening a database in a Swift playground:

https://gist.github.com/jamiltz/0ae9d08dd6a5cd3b8b250c81a527e76a

This message is not logged when running the same code in an iOS app. Any idea what is going on? Is there a way to suppress this message temporarily?

--------
* Version:   2.0
* Client OS: Swift playground
* Server:   n/a

**Comment by jamiltz** [comment]
One more clue, this only happens when a database file is manually moved to a folder in Finder and then opened with `Database(name: "todo", options: options)`. It doesn't happen for new databases.

In this case, it was previously a 1.3 database that was upgraded to 2.0. So it could be related to that. Need to narrow down when this happens. All the functionalities are working regardless so it's not critical.

**Comment by jamiltz** [comment]
After doing more testing, this message is actually logged both in a swift playground and an iOS app scheme. On first launch, the message is not logged. It is only logged on subsequent launches (when the database file already exists at this file path location).

**Comment by pasin** [comment]
I believe this's from enabling write ahead logging in SQLite from the LiteCore. I understand that it doesn't indicate the real error. @snej is there a way to suppress this warning?

**Comment by snej** [comment]
This is a message logged by SQLite (via a callback that we route through our logging.) It occurs if the database was not explicitly closed the last time it was open.

The message is harmless, but you can keep it from happening by calling `close` on your CBLDatabases when the app quits.
