### ISSUE TITLE
2.0: CBLQuery doesn't support offset, limit, or parameters

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1755]
CBLQuery doesn't appear to support run-time parameterization yet. From its -run: method:

```objc
    C4QueryOptions options = kC4DefaultQueryOptions;
    NSData* paramJSON = nil;
    
    C4Error c4Err;
    auto e = c4query_run(_c4Query, &options, {paramJSON.bytes, paramJSON.length}, &c4Err);
```

Note neither `options` nor `paramJSON` are configured. Compare with CBLPredicateQuery.

**Comment by pasin** [comment]
Fixed in 322e175ed75e364f35ceaa8e564a7e77769cd442 and 7b94e56d85e0733362443ac9cf6957e75cdab816
