### ISSUE TITLE
2.0: CBLLiveQuery (final API)

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1759]
This is probably blocking some developers from being able to try 2.0, since it's a very widely used feature.

Note that we don't have a solid API spec for it yet.

**Comment by snej** [comment]
I'm working on this, with a placeholder API based on 1.x's, in a `feature/2.0-livequery` branch. It's working, although it runs the query on the main thread, which is of course bad. I can't move this to a background thread until we implement thread-safety in the bindings.

**Comment by snej** [comment]
LiteCore infrastructure supporting this is being tracked as https://github.com/couchbase/couchbase-lite-core/issues/111

**Comment by snej** [comment]
This is merged (and in DB8) with the placeholder API. @pasin is working on designing/implementing the real API.

**Comment by rajagp** [comment]
@pasin , @hideki : Can you confirm if this is or will be available for DB12 ?

**Comment by jamiltz** [comment]
I think those APIs are already available in DB11 (unless the API has changed). The example snippets for objc/swift are missing though. I'll make sure they are in DB12.

**Comment by jamiltz** [comment]
https://developer.couchbase.com/documentation/mobile/2.0/guides/couchbase-lite/native-api/query/index.html?language=java#live-query

**Comment by pasin** [comment]
It is already in DB11. FYI, There will be a minor change in DB13: change method name from run() to start() and will add parameters support to LiveQuery.
