### ISSUE TITLE
body digest doesn't match

### ISSUE THREAD

**Issue by brendand** [couchbase/couchbase-lite-ios#1760]
I've received the following error trying to import an attachment along with a record when calling the `putExistingRevisionWithProperties` method:

> WARNING: Attachment 'D1840D31-9128-4B5C-A04F-4C2A4D8B40E0.jpg' body digest (sha1-2jmj7l5rSw0yVb/vlWAYkK/YBwk=) doesn't match 'digest' property sha1-/6/T8q3rG5GWLZaPijH64hg4fXA= {at -[CBLDatabase(Attachments) registerAttachmentBodies:forRevision:error:]_block_invoke:265}

I don't know why the .blob attachment doesn't match the digest recorded in the JSON object. 

Here's what the `_attachments` property looks like.

```
    "_attachments" =     {
        "D1840D31-9128-4B5C-A04F-4C2A4D8B40E0.jpg" =         {
            "content_type" = "image/jpeg";
            digest = "sha1-/6/T8q3rG5GWLZaPijH64hg4fXA=";
            length = 6989075;
            revpos = 7;
            stub = 1;
        };
    };
```

and here's my code where the crash happens (specifically crashes on the `putExistingRevisionWithProperties` method call:

```
	NSDictionary *attachments = jsonObject[@"_attachments"];
				
	NSMutableDictionary *attachmentProps = nil;
				
	if (attachments) {
		attachmentProps = [[NSMutableDictionary alloc] init];
		[attachments enumerateKeysAndObjectsUsingBlock:^(id  _Nonnull filename, id  _Nonnull fileData, BOOL * _Nonnull stop) {
			NSString *digest = fileData[@"digest"];
			NSString *blobKey = [self blobKeyForDigest:digest];
			NSURL *attachmentURL = [attachmentsURL URLByAppendingPathComponent:blobKey];
			if ([fileManager fileExistsAtPath:attachmentURL.path]) {
				attachmentProps[filename] = attachmentURL;
			}
		}];
	}
				
	@try {
					
		BOOL success = [newDoc putExistingRevisionWithProperties:jsonObject
							attachments:attachmentProps
							revisionHistory:revIds
							fromURL:nil
							error:&error];
					
		if (!success) {
			TFFLog(@"Error importing document: %@", error);
		}
					
	} @catch (NSException *exception) {
					
	}

```

When this situation occurs, my app crashes. I wish it was just a warning and not a crash.

I'm thinking that the only way to resolve this problem is to generate a new sha1 digest for the file and then update the _attachments property to replace the incorrect digest.

Does that seem like a reasonable way to resolve this situation?

--------
* Version:   1.4
* Client OS: macOS Sierra 10.2.5.
* Server:    n/a

**Comment by brendand** [comment]
So I found that if I set the digest value to nil, CBL automatically recomputed one and I was able to proceed with the import without a crash.

**Comment by snej** [comment]
If the digest is wrong, something is changing in the attachment data when you transfer it — you really should look into that, because it implies some kind of data corruption.

Also, please post a crash log or backtrace. It shouldn't be crashing.

**Comment by djpongh** [comment]
Have you had a chance to get the crash log  backtrace?

**Comment by brendand** [comment]
Sorry, since I changed my code to set digest value to nil everything seemed to work fine after that, so I didn't investigate this any further.
