### ISSUE TITLE
Invalid Attachment Metadata issue for deferred attachment download scenario

### ISSUE THREAD

**Issue by parvezq** [couchbase/couchbase-lite-ios#1761]
We are getting invalid attachment metadata issue while using deferred attachment download for a document: 
`public class Module: CBLModel{
    @NSManaged var moduleName: String!
    @NSManaged var isActive: NSNumber!
}`

For above model, initially we are simply adding a document with "isActive" as false (No attachment added). Then we change the "isActive" to true and also adds a zip file as attachment using the setAttachmentNamed on the instance of above model class. The attachment gets added but on receiving end sometimes we encounter invalid attachment metadata.

What can be the probable reason for this issue?

--------
* Version:   1.3.1
* Client OS: iOS 8.0 onwards
* Server: Couchbase Server

**Comment by jayahariv** [comment]
Closing 1.x issue!
