### ISSUE TITLE
Support for watchOS 3.0

### ISSUE THREAD

**Issue by callo90** [couchbase/couchbase-lite-ios#1763]
I've been trying to use it on apple watch, I checked some threads but nothing clear, #1622 seems to be talking about that but no explanation at all .

Carthage is only compiling an iOS version, so it looks like you have to do something else with watchkit. is there actually support?

Cheers.
--------
* Version:   1.4.0
* Client OS: iOS 10.2.1
* Server:   none

**Comment by pasin** [comment]
We currently do not have support watchOS. You may check at the forum to see if anyone have tried to use the library with the watchOS.

**Comment by pasin** [comment]
@rajagp Have you tried to build the library for watchOS?
