### ISSUE TITLE
2.0: Dictionary's integerForKey: for floating number gets round up

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#1764]
Unit Test:
https://github.com/couchbase/couchbase-lite-ios/blob/feature/2.0/Objective-C/Tests/DocumentTest.m#L471-L511

**Comment by borrrden** [comment]
This already has an issue open in lite core FYI.

**Comment by borrrden** [comment]
Oops wrong issue sorry ignore my comment.
