### ISSUE TITLE
Is CBL support for Ionic windows hybrid app ?

### ISSUE THREAD

**Issue by Tamil-Arya** [couchbase/couchbase-lite-ios#1769]
Hi guys,

We have implemented CBL local storage for iOS and android hybrid  app by using Ionic 2, Its working charm. But while testing with windows mobile, Its not working. So, is it supporting or not i don't know there is no prepare document for that. If anyone has implemented or tested please let me know.

Thanks & Regards 
Tamil

* Version:   Current Version of CBL
* Client OS: Ionic 2 windows platform
* Server:    CouchDB

**Comment by snej** [comment]
Hi! Please ask your question on the [Couchbase web forum](https://forums.couchbase.com/c/mobile) or the [Couchbase Mobile mailing list](https://groups.google.com/forum/#!forum/mobile-couchbase). We use Github issues only for bug reports and feature suggestions. Thanks.
