### ISSUE TITLE
Missing iOS LiteServ package

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-ios#1771]
--------
* Version:   1.4.0.1-2
* Client OS: iOS
* Server:    N/A

This is the expected behavior - http://latestbuilds.hq.couchbase.com/couchbase-lite-ios/1.4/ios/1.4-44/

This is no LiteServ present here - http://latestbuilds.hq.couchbase.com/couchbase-lite-ios/1.4.0.1/ios/1.4.0.1-2/

**Comment by ceejatec** [comment]
Fixed by working around automount failure on slave.
