### ISSUE TITLE
CBLModel willSave does not include changed attachment property names

### ISSUE THREAD

**Issue by combinatorial** [couchbase/couchbase-lite-ios#1774]
When an attachment is changed, and save, `- (void)willSave:(NSSet*)changedPropertyNames` with a nil set. It should include the name of attachment properties that have changed. The caller has these in the `_changedAttachments` variable.

--------
* Version:   1.3.1
* Client OS: iOS 10.3.1
* Server: N/A

**Comment by jayahariv** [comment]
Closing 1.x issue!
