### ISSUE TITLE
Filtered replication not working via REST API

### ISSUE THREAD

**Issue by adamski** [couchbase/couchbase-lite-ios#1776]
I seem to be having an issue doing a filtered replication from Cloudant to CBL (iOS Simulator). I've tested via `curl` that the filter works as expected, replicating to another Cloudant DB. 

Replicating on CBL via the REST API without the `filter` param it works and I get the full dataset. 

I've also tried adding the `filter` and `query_params` to the request url, (with other parameters in the body) e.g.:
```
http://u21417279:p7710746@localhost:5985/_replicate?filter=words/by_category&query_params={"category":"free"}
```

but it seems to be ignored there. 

With the `filter` and `query_params` in the request body I get the following response:

```
{ session_id: 'repl001' }
```

But no documents appear in the client database. 

--------
* Version:   1.4
* Client OS: iOS 10.1 (Simulator)
* Server:   Cloudant

**Comment by pasin** [comment]
This is a known issue that CBL's filterParams setting is not compatible with CouchDB. See https://github.com/couchbase/couchbase-lite-ios/issues/1484 for more detail.

**Comment by adamski** [comment]
Ok, I had seen that issue too. Is there any way I can do filtered replication from CouchDB to CBL? 
If this is not actually supported anymore, then the [documentation](http://labs.couchbase.com/couchbase-mobile-portal/develop/guides/couchbase-lite/native-api/replication/index.html) is misleading. It clearly states that CBL supports standard CouchDB replication.

**Comment by jamiltz** [comment]
@adamski that documentation link you used is outdated so I removed them from that resource. Regarding the support for filter functions, the [upstream docs](https://developer.couchbase.com/documentation/mobile/current/guides/couchbase-lite/native-api/replication/index.html#filtered-pull-from-couchdb-pouchdb-or-cloudant) are now updated. Have you considered migrating from CouchDB to Sync Gateway?

**Comment by adamski** [comment]
Yes, I have considered using Sync Gateway + Couchbase Server but was hoping to avoid needing to manage a server, hence the choice to use Cloudant. If thats the only way to get filtered replication then I might have to reconsider.

**Comment by pasin** [comment]
Closed as not the issue.

**Comment by Fenil15** [comment]
Usign filter params in query string is not a correct way to implement at query string has its own limitation. Instead one should use selector instead of filter if you are using CouchDB Server 2.0 and above. Only thing you need to make sure at your client side is, set the filter name = _selector and in filter params, pass params in following format -

    {
      "selector": {
        "key_name_to_filter": "key_value_to_filter",
        "$or": [
          {
            "$and": [
              {
                "key_1": "value_1"
              },
              {
                "key_2": "value2"
              }
            ]
          },
          {
            "$and": [
              {
                "key_3": "value_3"
              },
              {
                "key_4": "value_4"
              }
            ]
          }
        ]
      }
    }
Above format is just an example illustrating you can create complex queries in selector filter.

**Comment by adamski** [comment]
@Fenil15 Thanks for the example. I assume you mean Couchbase Server 2.0? If so, I am planning to move away from Couchbase Server for this particular project. (Happy to elaborate on reasons why if you're interested).

**Comment by Fenil15** [comment]
@adamski No I mean CouchDB server

**Comment by adamski** [comment]
@Fenil15 ah ok thank you I will looking it.
