### ISSUE TITLE
Deferred attachment retrieval fails when document is updated locally

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/couchbase-lite-ios#1780]
If a document is updated locally before deferred attachment retrieval is triggered, the new local revision is being sent.  Sync Gateway doesn't recognize the revision, and so is failing to return the attachment.

It's not clear to me whether the client should be sending the revision it originally received from Sync Gateway (which won't necessarily still exist in Sync Gateway if the document has been updated since), or just omit the revision altogether (which will only retrieve the attachment if it's still associated with the active revision).

Additional details on https://github.com/couchbase/sync_gateway/issues/2621.

**Comment by combinatorial** [comment]
From our perspective the "or just omit the revision altogether" would work. We are continuously pulling (just not attachments) so if the attachment changed it's owning doc would change and we would have that new document.

**Comment by jayahariv** [comment]
Closing 1.x issue!
