### ISSUE TITLE
Retrying of failed attachment is going infinite instead of 2 times retrying

### ISSUE THREAD

**Issue by msanilkumar2020** [couchbase/couchbase-lite-ios#1781]
Hi ,

We try to upload document (s915500000002_ptx1496212396636_a1496212396637_attachment.doc) to server. It is always failing with timeout error. Library started retrying, it should retry only for 2 times(4sec and 8Sec). Instead of retrying for 2 times, it is going for infinite loop and always failing because of timeout.

Attached log file to get more details in this issue. 
[RetryCBL.rtf.zip](https://github.com/couchbase/couchbase-lite-ios/files/1063567/RetryCBL.rtf.zip)

**Comment by pasin** [comment]
There are two types of retrying. First, when a remote request fails, the request will be retried 2 times. Second, when a revision fails to transfer due to a recoverable (e.g. timeout or network) error, the replicator will keep retrying to send the revision after a certain period of time. Otherwise the revision will be skipped. From the log, the behavior is expected.

Regarding the attachment transfer timeout, what is the network condition and what is the size of the attachment?

**Comment by pasin** [comment]
When the attachment upload is timeout, do you see anything on the SGW log?

**Comment by djpongh** [comment]
@msanilkumar2020 any chance to look over the Sync Gateway logs?

**Comment by msanilkumar2020** [comment]
@djpongh ,
[SYNCGateway_Logs.zip](https://github.com/couchbase/couchbase-lite-ios/files/1102101/SYNCGateway_Logs.zip)

Please find the attached syncgateway logs.

**Comment by msanilkumar2020** [comment]
We are always getting internal server error and attachment uploading is failing.
14:15:19.534197 2017-05-31T14:15:19.534+05:30 HTTP: #272476:     --> 500 Internal error: multipart: Part Read: read tcp 10.3.1.233:4984->10.3.1.96:31354: read: connection reset by peer  (40668.1 ms)

**Comment by snej** [comment]
From the log initially posted, CBL is throwing an exception:
```
[05/31 17:07:55:691] [T 0x14f4a3280] Type-WARNING , Message-ForestDB error: Forestdb Handle is being used by another thread (-39)
 {at FDBLogCallback:68}
[05/31 17:07:55:691] [T 0x14f4a3280] Type-WARNING , Message-Unexpected CBForest error -39 {at err2status:214}
[05/31 17:07:55:696] [T 0x14570b540] Type-WARNING , Message-Exception caught in -[CBLDatabase doAsync:]:
	*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil
	0   CoreFoundation                      0x00000001831a51d0 <redacted> + 148
	2   CoreFoundation                      0x0000000183083d44 CFStringConvertNSStringEncodingToEncoding + 0
	3   AT&T EPTT                           0x00000001003626c0 -[PTXCBliteManager dbChangedNotification:] + 2332
	4   CoreFoundation                      0x000000018313eb10 <redacted> + 20
	5   CoreFoundation                      0x000000018313e214 <redacted> + 400
	6   CoreFoundation                      0x000000018313df90 <redacted> + 60
	7   CoreFoundation                      0x00000001831adb8c <redacted> + 1504
	8   CoreFoundation                      0x000000018307fe64 _CFXNotificationPost + 376
	9   AT&T EPTT                           0x0000000100972e00 __42-[CBLDatabase(Internal) postNotification:]_block_invoke + 64
	10  AT&T EPTT                           0x000000010093ab20 catchInBlock + 28
	11  Foundation                          0x0000000183cb9048 <redacted> + 340
	12  CoreFoundation                      0x0000000183152b5c <redacted> + 24
	13  CoreFoundation                      0x00000001831524a4 <redacted> + 524
	14  CoreFoundation                      0x00000001831500a4 <redacted> + 804
	15  CoreFoundation                      0x000000018307e2b8 CFRunLoopRunSpecific + 444
	... {at MYReportException:43}
```

**Comment by snej** [comment]
There are two things going on:

1. An error from ForestDB, "Handle is being used by another thread". This indicates a threading problem in Couchbase Lite. Another issue reported by your team indicates you're using a modified version of Couchbase Lite and the code you added has threading bugs (running things on the main thread instead of the replicator thread.) This could be another side effect of that.
2. An exception being thrown by `PTXCBliteManager`, which must be an application class. This is clearly a bug in your code.

**Comment by msanilkumar2020** [comment]
@snej ,
In this attachments uploading is getting timeout because of internal server error (500 Internal error: multipart: Part Read: read tcp 10.3.1.233:4984->10.3.1.96:31354: read: connection reset by peer).
- Threading issue in our code is fixed from our side.

**Comment by snej** [comment]
The server error is simply reporting that Couchbase Lite abruptly closed the TCP socket.
Bugs in your code (threading or exceptions) can really mess up the state of the app and might cause trouble for Couchbase Lite. Please re-run this scenario with a fixed version of your app and send us the Couchbase Lite log output from a run that encounters the error. Thanks.

**Comment by pasin** [comment]
Close this issue as no activities. We can reopen this issue when there is more info.
