### ISSUE TITLE
invalid JSON in query param

### ISSUE THREAD

**Issue by adamski** [couchbase/couchbase-lite-ios#1782]
I'm getting the following error trying to call the REST API with the following URL (GET):

```
'http://u67888914:p2440393@localhost:5985/mydb/_design/words/_view/byName?endkey=aunt&include_docs=true&startkey=aunt'
```

CBL_Router: invalid JSON in query param ?startkey=aunt {at -[CBL_Router jsonQuery:error:]:138}

--------
* Version:   1.4
* Client OS: iOS 10.1
* Server:    n/a

**Comment by adamski** [comment]
So I did some searching and found that the start key and end key need to be in JSON format, so I'm now trying e.g.

```
'http://u79290936:p17802765@localhost:5992/mydb/_design/words/_view/byName?endkey=%5B%22aunt%EF%BF%BE%22%5D&include_docs=true&startkey=%5B%22aunt%22%5D'
```

However this is not bringing back any data rows.

**Comment by pasin** [comment]
Can you just try with just quote, e.g. startkey="aunt"? The key with array, e.g. ["aunt"], is for composite keys.

**Comment by adamski** [comment]
Thank you, that's sorted it! 👍
