### ISSUE TITLE
CBL Syncing issue in the new version of v1.4

### ISSUE THREAD

**Issue by Tamil-Arya** [couchbase/couchbase-lite-ios#1786]
**# CBL syncing issus from v1.4** 

2017-06-14 09:40:38.772154+0530 [1732:666812] Sync: CBLRestPusher[https://comm.server.url]: Replicating from lastSequence=230
2017-06-14 09:40:38.775357+0530 [1732:666812] Sync: CBLRestPusher[https://comm.server.url]: Received 0 revs
2017-06-14 09:40:38.775803+0530 [1732:666812] Sync: CBLRestPusher[https://comm.server.url] Progress: set active = 0
2017-06-14 09:40:38.776315+0530 [1732:666812] Sync: CBLRestPusher[https://comm.server.url]: postProgressChanged (0/0, active=0 (batch=0, net=0), lastSeq=230, online=1, error=(null))

Note :  I do see it is not considering the changes, postProgressChanged is 0. Even though there are 2 changes locally

--------
* Version:   CBL 1.4v
* Client OS: iOS 10.3.2
* Server:    CouchDB

**Comment by pasin** [comment]
Is the issue reproducible reliably? Do you have sample code or any info that we can use to reproduce the issue?

**Comment by Tamil-Arya** [comment]
The problem is i have installed v1.1 into my iPhone even i have downloaded few documents afterward on top of i have installed v1.3 CBL here is the issue such way when i trying to edit or create a document in offline after coming up online its not syncing while checking the _push.pendingDocumnetID thats throughs empty document id event lastSeq number is not changed.

**Comment by pasin** [comment]
If using CBL 1.4 alone (not upgraded), does the issue happen? Also what is CouchDB version?

**Comment by Tamil-Arya** [comment]
Nope. If i have install a app along v1.4 freshly i m not getting such a issue. When if i already installed v1.1 on top up if i install v1.3 or v1.4 at the time i m getting such issue. When app goes offline that time is any change into the doc or create new doc while coming to online its not even sync to server at the time pending doc printing as 0. We are using CouchDB v1.6.

**Comment by pasin** [comment]
I just updated the version number configuration in the master branch to match with the CI build version number to avoid further confusion.

**Comment by pasin** [comment]
Here is the CI build from the current master branch: http://latestbuilds.hq.couchbase.com/couchbase-lite-ios/1.4.1/ios/1.4.1-50/couchbase-lite-ios-community_1.4.1-50.zip. You can try that. Please make sure that it replaces the old 1.4 one.

**Comment by pasin** [comment]
Closed as no activities. We can reopen this issue when there is more info.
