### ISSUE TITLE
2.0: Pagination support in Query API

### ISSUE THREAD

**Issue by rajagp** [couchbase/couchbase-lite-ios#1795]
--------
* Version:   CBM DB10

PredicateQuery API supports pagination. Need support in Query interface as well

**Comment by rajagp** [comment]
@pasin , @hideki  : To confirm (per assigned milestone labels) that this will be available in DB12 on both iOS and Android

**Comment by pasin** [comment]
This doesn't get implemented yet. Need https://github.com/couchbase/couchbase-lite-core/issues/172 to be resolved first.

**Comment by pasin** [comment]
Fixed in 322e175ed75e364f35ceaa8e564a7e77769cd442.

**Comment by rajagp** [comment]
@pasin , @hideki  : Is this available in both iOS and Android DB13?

**Comment by pasin** [comment]
Yes.

**Comment by thomai-d** [comment]
Will there be a .NET implementation in the future?
I see Limit() is already available, but I can't find Offset()

**Comment by rajagp** [comment]
@thomai-d - it’s Supported in .net as well - http://docs.couchbase.com/mobile/2.0/couchbase-lite-net/html/M_Couchbase_Lite_Query_ILimitRouter_Limit_1.htm
