### ISSUE TITLE
2.0: testDeleteDBOpendByOtherInstance fails on iOS device

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1797]
I'm running Obj-C unit tests on my iPhone 6s+, and -[DatabaseTest testDeleteDBOpendByOtherInstance] fails, i.e. deleting the second database instance did not return an error.

The cause appears to be that the two databases don't have identical paths, despite referring to the same location in the filesystem:
```
(lldb) po self.db.path
/private/var/mobile/Containers/Data/Application/76BA27A5-5034-417D-8DD4-562E0E287ECD/tmp/CouchbaseLite/testdb.cblite2/
(lldb) po otherDB.path
/var/mobile/Containers/Data/Application/76BA27A5-5034-417D-8DD4-562E0E287ECD/tmp/CouchbaseLite/testdb.cblite2/
```
I suspect `/private/var` is a symlink to `/var` in the iOS filesystem.

I'm not sure where the two databases' paths are coming from, but one of them is probably getting canonicalized or having its symlinks resolved. Unfortunately LiteCore relies on direct string comparison to detect when two databases refer to the same on-disk file.

**Comment by Codeido** [comment]
I think that I have this issue. 
When I try to recreate the db
```
try database?.delete()
database = try Database(name: "my-db")
```
and add a live query to the new database, I get this crash:
`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Database is not open.'`
