### ISSUE TITLE
2.0: MATCH Query with two FTS indexes causes problems

### ISSUE THREAD

**Issue by rajagp** [couchbase/couchbase-lite-ios#1798]
--------
* Version:   CBL 2.0

**The Request:**
Look for a string  in either "description" or "name" property.

**My two FTS indexes are:**

```
     try _db?.createIndex(["airportname"], options: IndexOptions.fullTextIndex(language: nil, ignoreDiacritics: false))
        
     try _db?.createIndex(["description"], options: IndexOptions.fullTextIndex(language: nil, ignoreDiacritics: false))
        
      try _db?.createIndex(["name"], options: IndexOptions.fullTextIndex(language: nil, ignoreDiacritics: false))
```

**Query Expression:**
```
descExp = Expression.property("description").match("'\(descriptionStr)'")
            .or(Expression.property("name").match("'\(descriptionStr)'" ))
```

**This Fails with following error in console**

`SELECT sequence, key, version, flags, offsets("kv_default::.description"), offsets("kv_default::.name") FROM kv_default, "kv_default::.description" AS FTS1, "kv_default::.name" AS FTS2 WHERE fl_value(body, 'type') = 'hotel' AND ((((fl_value(body, 'country') = 'London' OR fl_value(body, 'city') = 'London') OR fl_value(body, 'state') = 'London') OR fl_value(body, 'address') = 'London') AND ((FTS1.text MATCH '''Spa''' AND FTS1.rowid = kv_default.sequence) OR (FTS2.text MATCH '''Spa''' AND FTS2.rowid = kv_default.sequence))) LIMIT $limit OFFSET $offset`
```
0|0|1| SCAN TABLE kv_default::.description AS FTS1 VIRTUAL TABLE INDEX 0:
0|1|2| SCAN TABLE kv_default::.name AS FTS2 VIRTUAL TABLE INDEX 0:
0|2|0| SEARCH TABLE kv_default USING INDEX kv_default_seqs (sequence=?)
0|2|0| SEARCH TABLE kv_default USING INDEX kv_default_seqs (sequence=?)`
```

`2017-06-21 10:10:35.275 TravelSample[75237:35646168] CouchbaseLite  WARNING: SQLite error (code 1): statement aborts at 24: [SELECT sequence, key, version, flags, offsets("kv_default::.description"), offsets("kv_default::.name") FROM kv_default, "kv_default::.description" AS FTS1, "kv_default::.name" AS FTS2 WHERE fl_value(body, 'type') = 'hotel' AND ((((fl_value(body, 'country') = 'London' OR fl_value(body, 'city') = 'London') OR fl_value(body, 'state') = 'London') OR fl_value(body, 'address') = 'London') AND ((FTS1.text MATCH '''Spa''' AND FTS1.rowid = kv_default.sequence) OR (FTS2.text MATCH '''Spa''' AND FTS2.rowid = kv_default.sequence))) LIMIT $limit OFFSET $offset] unable to use function MATCH in the requested context`
```
2017-06-21 10:10:35.275 TravelSample[75237:35646168] CouchbaseLite Query ERROR: CBLQuery failed: 4/1
Error when fetching hotels Optional("unable to use function MATCH in the requested context")`
```

(**Note**: If I just did a match query on description, it works)

**Comment by snej** [comment]
Looks like a LiteCore issue. (Rule of thumb: If you see anything warning about SQLite errors, it's probably LiteCore.) It appears that the query generator is producing invalid syntax for some reason.

**Comment by djpongh** [comment]
Created LiteCore issue: https://github.com/couchbase/couchbase-lite-core/issues/166
