### ISSUE TITLE
2.0 LiveQuery listens for changes on all databases

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-ios#1801]
[[NSNotificationCenter defaultCenter] addObserver: self 
                                                 selector: @selector(databaseChanged:)
                                                     name: kCBLDatabaseChangeNotification 
                                                   object: _query.database];

This line is meant to add for just the database in question, but it is never copied from the original query when a copy is made for the live query and so `_query.database` is simply `nil`

--------
* Version:   2.0-db011
* Client OS: All
* Server:    n/a

**Comment by pasin** [comment]
Thanks!
