### ISSUE TITLE
Add Support for Mango Selector Replication

### ISSUE THREAD

**Issue by stefanwascoding** [couchbase/couchbase-lite-ios#1809]
It would be great if I could specify a Mango selector for replications.
If this is already possible in CBL 1.4, how? I didn't see any promising property on the replication object.

Or is this planned for CBL 2?

https://issues.apache.org/jira/browse/COUCHDB-2988 — Allow query selector as changes and replication filter

--------
* Version:   1.4.0
* Client OS: iOS 10.3.2
* Server:    CouchDB 2.0.0

**Comment by pasin** [comment]
We don't have the query selector supported.

**Comment by jo** [comment]
+1 for Mango filter support.

This even might be an easy change:
* `filter=_selector`
* method POST
* mango selector as body

Mango filters has several advantages over classic filters. They are way more performant on the server side and the user does not need to author a ddoc but can specify the filter client side.

**Comment by snej** [comment]
I'm not aware of Mango filters so I don't know what the details are. But we're not going to be adding any features that are specific to replication with CouchDB.
