### ISSUE TITLE
CBLRegisterJSViewCompiler is not included into couchbaselite.framework

### ISSUE THREAD

**Issue by CharlesGrimont** [couchbase/couchbase-lite-ios#1810]
I'am not able to use CBLRegisterJSViewCompiler when using carthage to build couchbaselite.framework

and there is not any explanation concernig the way to import this lib throw carthage 

have any ideas ? 
--------
* Version:   release/1.4.0
* Client OS: ios swift

**Comment by pasin** [comment]
There is a history why we still don't have CBLRegisterJSViewCompiler in the framework. We definitely should do this.

**Comment by CharlesGrimont** [comment]
this would be amazing thanks a lot !

**Comment by jayahariv** [comment]
Closing 1.x issue!
