### ISSUE TITLE
Updating Views via REST API

### ISSUE THREAD

**Issue by EthanRTF** [couchbase/couchbase-lite-ios#1812]
Once a view is created through the REST API I can't seem to edit it. The only I have found is to delete the design document and recreate it.

I am able to update the design document, and if I examine the design document after it shows that the updated code, but the results never change.

I know iOS and Java both have a 'version' they can set when creating views. I tried doing the same by passing a 'version' field in with the view's body but it didn't change anything.

As per [suggestion](https://forums.couchbase.com/t/updating-views-via-rest-api/13346/4), I have filed this issue to help find a solution.

--------
* Version:   1.4 
* Client OS: iOS 10.2
* Server:  4.6.1

**Comment by pasin** [comment]
Duplicate with https://github.com/couchbase/couchbase-lite-ios/issues/1758. Let's track this issue on #1785.
