### ISSUE TITLE
Multi threading issue 

### ISSUE THREAD

**Issue by SalmanZafar1105** [couchbase/couchbase-lite-ios#1813]
I have created a single CBLDatabase instance, which is used throughout my project. Any background tasks are done using doAsync on the database instance. Also, I have provided my own serial queue to the cblmanager to execute the background tasks.

The problem occurs when I start a live query, while writing a large number of documents (more than 10,000...) into the database using doAsync. The live query waits for the write operation to complete, before returning results. It took almost 10 seconds to complete the write operation. Both the live query and the write operation are using the same CBLDatabase instance.

We are using doAsync for write, so the live query should run in parallel with it, but it does not. How to run both in parallel?

We tried going around it by creating a new instance of manager and database for the live query and it worked. But still we are creating a new instance of manager and database, which leaks memory, and our live query needs to be stopped and started again frequently. If our app is used extensively for longer periods it will be terminated due to memory issues.

Also, is it safe to use the method 'backgroundTellDatabaseNamed:to:' as it runs on the replicator's thread and we have an active replication running alongside all these operations. Can we shift all our CRUD operations on this method, without facing any delays or read-write locks? Because then only it will help us. Our app displays content based on what data is coming through the replication.

We are using CBLUITableSource and CBLUITableDelegate to populate the data in table view.

--------
* Version:   1.4.1
* Client OS: iOS 10.2.1 and above.
* Server:    Couchbase Server 4.6 and Sync Gateway version 1.4

**Comment by pasin** [comment]
I would recommend to create a new Manager with a serial dispatch queue to use with a large database operations so that it will not block anything. 

> But still we are creating a new instance of manager and database, which leaks memory, and our live query needs to be stopped and started again frequently. If our app is used extensively for longer periods it will be terminated due to memory issues.

In general, creating an new manager to use shouldn't be any differences from using the shared manager one. Have you run any memory or leak profiling to check where the issue is?

**Comment by snej** [comment]
>We are using doAsync for write, so the live query should run in parallel with it

No, it doesn't. Asynchronous operations are run on a single queue. (Each CBLDatabase instance has its own queue, though.) 

>But still we are creating a new instance of manager and database, which leaks memory

If it does, that's a bug and needs to be reported separately.
