### ISSUE TITLE
2.0: Replicator Activity Level stays in Busy state

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#1816]
Reported by Priya,

```
Hey Pasin
I am integrated my travel sample app with DB 12 and replication doesn’t seem to work properly. When I added a document via the SDK, I noticed that it does get synced over (see SG logs at bottom) but it’s stuck in “busy” state forever.
After a while, , an attempt is made to reestablish connect and changes is pushed down
 
(I haven’t tried live queries yet to see if the DB gets updated)
```

I have also confirmed this by testing with Todo app.

```
2017-07-11 16:46:07.721949-0700 Todo[487:77497] CBLReplicator[<*> blip://10.17.1.23:4984/todo] is busy, progress 110/110, error: (null)
2017-07-11 16:46:07.722288-0700 Todo[487:77497] [Todo] Replicator: BUSY 110/110, error: (null)
```

**Comment by pasin** [comment]
I have seen the behavior for both push and pull replication. Here are the unit tests:

https://github.com/couchbase/couchbase-lite-ios/blob/feature/2.0/Objective-C/Tests/ReplicatorTest.m#L148-L165

https://github.com/couchbase/couchbase-lite-ios/blob/feature/2.0/Objective-C/Tests/ReplicatorTest.m#L189-L207

**Comment by rajagp** [comment]
May be related to this :- May want to test out live queries in the context of continuous replication.  When replication is in the busy state, the live query callback isn't getting invoked.

**Comment by snej** [comment]
Weird; there's no direct connection between live queries and the replicator. They're not even operating on the same CBLDatabase instance. Can you provide a small test case and file a new issue?

**Comment by snej** [comment]
There was no bug in the actual replicator code in CBL or in LiteCore, just some problems with the unit test class. It wasn't waiting long enough for the replicator to go idle — the replicator saves its checkpoint first, and there's by default a 5sec delay for that. I altered the tests to lower that to 1sec.

Priya's original issue is still open, it's just that the unit tests don't appear to reproduce it.

**Comment by pasin** [comment]
@snej IIRC hat when I tested with Todo, the status stayed in busy (more than 5 seconds IIRC). I will retest this and report back.

**Comment by rajagp** [comment]
OK. So following on my earlier comment on LiveQueries. So it seems like when the replicator is in busy state when updating a document, all operations on DB related to that document are stalled (which results in callbacks to live queries not being received). This is what I tried : 
1. Get the replicator in busy state (original problem) when trying to sync document  Doc1
2. I tried to update the same document Doc1 (that was being replicated) locally. The call never returns ...
```
   try db.save(flightDocument)
````

**Comment by pasin** [comment]
@rajagp Thanks. I will try to create a unit test to test the behavior.

**Comment by snej** [comment]
@rajagp Are you saying that the call to `db.save` hangs? Could you please pause the debugger and get a backtrace?

**Comment by rajagp** [comment]
@snej Created a separate ticket to track this . Hopefully this helps - https://github.com/couchbase/couchbase-lite-ios/issues/1825

**Comment by pasin** [comment]
From the previous test fest, we are still seeing this behavior when SGW returned an error (e.g. from Sync Function).

**Comment by pasin** [comment]
I understand that this is already fixed in the LiteCore. We can reopen the issue if it's still not fixed.
