### ISSUE TITLE
2.0: CBLQuery OrderBy Always Needs a Where

### ISSUE THREAD

**Issue by eljefe6a** [couchbase/couchbase-lite-ios#1820]
`CBLQuery` doesn't have a `select:from:orderBy` method. There is only a `select:from:where:orderBy`. Not every `orderBy` will have a `where`.

These methods should get added:
`select:from:orderBy`
`select:from:orderBy:limit`
`selectDistinct:from:orderBy`
`selectDistinct:from:orderBy:limit`

**Comment by snej** [comment]
That's a lot of methods to add just for this edge case. We can just allow the `where:` parameter to be `nil`.

**Comment by pasin** [comment]
We already allow nil in the where parameter.

**Comment by eljefe6a** [comment]
Thanks!
