### ISSUE TITLE
2.0: Suggest You Prepend Replication Again

### ISSUE THREAD

**Issue by eljefe6a** [couchbase/couchbase-lite-ios#1821]
In 2.0 the `Replicator` the `ActiveLevels` are `kCBLBusy`, `kCBLIdle`, and `kCBLStopped`. I suggest naming them like 1.0 with `Replication` being prepended like `kCBLReplicationBusy`.

**Comment by snej** [comment]
I agree; Obj-C/Cocoa naming conventions tend to have a prefix like this on enumeration constants. For example `kCALayerLeftEdge`, `AVPlayerStatusReadyToPlay`, `NSViewLayerContentsPlacementTop`...

**Comment by pasin** [comment]
Thanks @eljefe6a and @snej. I will fix this.
