### ISSUE TITLE
2.0: iOS release build is too large (has full symbols)

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1824]
As @borrrden points out, the CBL binary in Release/iphoneos is currently 15.7MB, which is way too large. By comparison, the current Mac binary is ~1.6MB. The iOS binary contains 32bit as well as 64bit, and it contains the LLVM bitcode, but it shouldn't be nearly that large.

I took a quick look, and one factor is that the binary contains symbols for everything, not just for exported functions. (To check, just run `nm CouchbaseLite.framework/CouchbaseLite` — currently it lists 14887 lines of symbols.)

**Comment by pasin** [comment]
@snej below is what I found (binary built from d70b7c17d6882207fc30e076a581696b4b9c76e7):

```
$ du -h CouchbaseLite.framework/CouchbaseLite
 18M	CouchbaseLite.framework/CouchbaseLite

$ lipo -info CouchbaseLite.framework/CouchbaseLite
Architectures in the fat file: CouchbaseLite.framework/CouchbaseLite are: i386 x86_64 armv7 arm64

$ nm -g CouchbaseLite.framework/CouchbaseLite | wc -l
     593

$ nm CouchbaseLite.framework/CouchbaseLite | wc -l
    7353
```

Use `xcrun bitcode_strip` to remove bitcode (found a command from [here](https://pspdfkit.com/guides/ios/current/faq/bitcode/)):
```
$ xcrun bitcode_strip -r CouchbaseLite.framework/CouchbaseLite -o CouchbaseLite.framework/CouchbaseLite-no-bitcode

$ du -h CouchbaseLite.framework/CouchbaseLite-no-bitcode 
6.3M	CouchbaseLite.framework/CouchbaseLite-no-bitcode
```

From the above result, the bitcode takes 2/3 of the size. 6.3MB seems to be reasonable to me.

**Comment by pasin** [comment]
I just noticed that the release `STRIP_STYLE` is set to `debugging` instead of `non-global`. 
I just quickly tested building the binary with the `STRIP_STYLE` = `non-global` and the binary size is reduced 2MB to 16MB. If stripping bitcode, the binary size is 4.9M. The result of  `nm CouchbaseLite | wc -l` is also 593. I will run binary test to make sure that the binary works fine on Monday, and we can close this issue.

**Comment by snej** [comment]
Interesting. You're looking at a fully-fat library with all 4 architectures, but I'm looking at just the ARM binaries in iphoneos. I'm not familiar with the process we use to merge the binaries in 2.0; does it also strip anything? Because your 4x-fat binary is much less than twice the size of my 2x-fat one and contains half the number of total symbols, so it's clearly not just a merge of the device and simulator binaries.

**Comment by pasin** [comment]
The [build_framework.sh](https://github.com/couchbase/couchbase-lite-ios/blob/feature/2.0/Scripts/build_framework.sh) doesn't do anything special.

Build Frameworks

https://github.com/couchbase/couchbase-lite-ios/blob/feature/2.0/Scripts/build_framework.sh#L94

Merge Frameworks

https://github.com/couchbase/couchbase-lite-ios/blob/feature/2.0/Scripts/build_framework.sh#L133

I could try to see what the different between running the xcodebuild command and using the xcode. Is it possible that it could be about XCode 8.3 vs 9?

**Comment by snej** [comment]
Wow, great discovery! I just tried defining STRIP_STYLE in the CBL xcconfig, and the MacOS binary size went from 1.74MB down to 1.36MB! That's ~380kbytes saved. (I don't know if it's worth doing this in the Mac version, but on iOS we should save a similar amount and it's totally worth it.)

**Comment by pasin** [comment]
Close and open a specific one for Swift.
