### ISSUE TITLE
2.0: Missing longForKey

### ISSUE THREAD

**Issue by eljefe6a** [couchbase/couchbase-lite-ios#1830]
The 2.0 iOS API is missing a `CBLDocument` getter for `long`. There are getters for `integerForKey` and `numberForKey`, but no equivalent of a `longForKey`.

**Comment by pasin** [comment]
I have an issue filed at https://github.com/couchbase/couchbase-lite-ios/issues/1768. This is only iOS issue so let track it there. Thank you very much anyway.
