### ISSUE TITLE
2.0: Encoding CBLDocuments to Fleece is too slow

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1831]
I've done some initial profiling of the TuneMark benchmark, and one thing that immediately jumps out is that, in the initial data import (12000+ JSON docs into a db), 30% of the time is spent in -[CBLDocument encode:], versus only 12% in c4doc_create and 12% in c4db_endTransaction.
![screen shot 2017-07-21 at 1 37 50 pm](https://user-images.githubusercontent.com/43241/28481462-e2783c34-6e19-11e7-9f6c-aa7e76f8ba06.png)
Another heavy function is -[CBLDocument setDictionary:], with 17% of the total time.

I think there's a lot of low-hanging fruit here, since this code has never been profiled. For instance, -[CBLDocument encode:] spends _35% of its time_ in calls to -conformsToProtocol:!

**Comment by djpongh** [comment]
When we do an overall performance analysis when will open up issues as appropriate.
