### ISSUE TITLE
1.4 - CBL Listener causes degradation of WiFi download speed

### ISSUE THREAD

**Issue by brendand** [couchbase/couchbase-lite-ios#1859]
When you start a CBLListener, the download speed on your WiFi connection degrades dramatically.

I've created a sample app which demonstrates this issue. 

If you go to speedtest.net and do a performance test on WiFi (I haven't tested on Ethernet), note your download speeds after a few test cycles.

Then, run the attached application (in Xcode) and click the button to start the CBL Listener.

Now go back to speedtest.net and run a few more tests.

In my experience (and my customers), starting the listener causes that Mac's WiFi download speed to decrease dramatically. For example, my tests dropped from approx. 150 mbps down to 35 - 50 mbps.

[CBLListenerTest.zip](https://github.com/couchbase/couchbase-lite-ios/files/1226195/CBLListenerTest.zip)

--------
* Version:   1.4.1
* Client OS: macOS 10.12.16 (and also tested on High Serra beta 5)
* Server:    N/A

**Comment by pasin** [comment]
I downloaded the app and ran the test. I could see my internet speed (through my home wifi) drops about 10% - 20%. I don't see the same kind drop (150 mbps down to 35 - 50 mbps) as you have experienced.

 I captured the traffic with the Wireshark tool and I did see a number of MDNS packages when starting the listener from the app. I then commented out the code that set the bonjour name and type to disable the MDNS stuff. After I did that, I don't see the drop of my internet speed. I guessed Bonjour is required for your app? Possible to turn if off (e.g. if users don't use it)?

**Comment by brendand** [comment]
Bonjour is how the devices discover each other for setting up peer-to-peer syncing. It seems like it would be a required thing otherwise I'd have to have the user configure a "server" and port number to connect to the peers.

I'm using an Apple Airport Extreme (tower) WiFi router. So maybe it's an issue with that. I'm not sure. But it does seem fishy.

I'll try it again without setting the Bonjour name and type.

**Comment by pasin** [comment]
@brendand any updates/discovery on this.

**Comment by brendand** [comment]
I wrote a sample app that uses just MCNearbyServiceAdvertiser on Mac and it causes the same problem as Couchbase Lite. I submitted a bug report to Apple about it, but haven't heard back from them on it at all.

**Comment by snej** [comment]
I was told long ago that multicast packets slow down a WiFi network, because the base station has to drop down to a slow transmission mode while sending such a packet. But there was optimization work early on to limit the rate at which Bonjour (mDNSResponder) sends them.
You could use some sort of packet-sniffer program like WireShark to see how many multicast packets are being sent over the network -- they'd be DNS packets sent on port 5353.

**Comment by brendand** [comment]
Ok, I'll see if I can figure Wireshark out. I installed it the other day.

But is there a best practice with respect to Couchbase Lite for peer-to-peer networking to allow discovery but to avoid this issue?

**Comment by snej** [comment]
All the listener does is publish an NSNetService, which is the absolutely bog-standard way of enabling Bonjour discovery. If that's causing network issues, something is really wrong with the Bonjour implementation in the OS. :( Either that, or maybe there's some other device on the network that's somehow reacting badly to the service advertisement and flooding the net with packets.

**Comment by djpongh** [comment]
Closing as a Bonjour issue. Re-open if you find that's not the case.
