### ISSUE TITLE
Query : Threading model in CBL 

### ISSUE THREAD

**Issue by msanilkumar2020** [couchbase/couchbase-lite-ios#1864]
Hi Pasin/Snej,

Could you please clarify below queries,
1) Total number of threads CBL library is using/creating.
2) What thread it uses serve for restbased Queries/requests(Phonegap)
3) Do we use same thread to access Change tracker/Remote request/Restbased queries?

--------
* Version:   1.4
* Client OS: iOS 10.3.3

**Comment by pasin** [comment]
> Total number of threads CBL library is using/creating.

CBL normally works under the application runloop unless a dispatch queue or a thread is specify to the CBLManager object. The replicators has its own thread operating on a runloop. All of the replicator created under the same manager will share the same thread / runloop; basically one single thread per all replicators. 

Each replicator owns a remote session which utilizes the NSURLSession to send remote requests. Each remote session runs under its own NSOperationQueue with the maximum queue size of one. However when each remote session completes sending a remote request, the response will be reported back to the replicator thread (schedule on the replicator runloop).

> What thread it uses serve for restbased Queries/requests(Phonegap)

CBLListener and PhoneGap's NSURLProtocol will serve each request by using a single shared background thread; internally it is a shared background server thread of the CBLManager object set to the CBLListener object. 

> Do we use same thread to access Change tracker/Remote request/Restbased queries?

Rest based queries will be served by using a background thread. Change Tracker and Remote Requests work on separate threads but Remote Requests will report response back to the replicator thread which is the same thread that the Change Tracker is operating on.

Please note that the answers are only for CBL iOS. I suggested to ask questions on the forum not the github issue. Thanks.
