### ISSUE TITLE
is it possible to share cbl local db to another device local db by Airdrop ?

### ISSUE THREAD

**Issue by Tamil-Arya** [couchbase/couchbase-lite-ios#1868]
Hi CBL Team,

**We want to share the local database , one device to another device using Airdrop. Is it possible to do?**

(**Note** : the idea is, we don't want to download same data from server again and again for that, get the local db(all doc) zip and share to the nearest mobile device by airdrop) 

* Version:   iOS 10
* Client OS: CBL 1.3
* Server:    CouchDB

**Comment by pasin** [comment]
I'm not familiar with the AirDrop API. However you can do the following:
1. Zip the database directory located at CBLManager's .directory properties. The directory name will be <database name>.cblite2
2. Send the zip file to another application on another device.
3. Unzip the zip file to a temp folder or any folder allowed.
4. Use CBLManager's `- (BOOL) replaceDatabaseNamed: (NSString*)databaseName withDatabaseDir: (NSString*)databaseDir error: (NSError**)outError` method to install the database.

If you encountered an issue, you could open a new issue.

**Comment by snej** [comment]
@Tamil-Arya: Please ask questions on the [Couchbase web forum](https://forums.couchbase.com/c/mobile) or the [Couchbase Mobile mailing list](https://groups.google.com/forum/#!forum/mobile-couchbase). We use Github issues only for bug reports and feature suggestions. Thanks.

**Comment by Tamil-Arya** [comment]
Thanks a lot,... @pasin.  Ok @snej.
