### ISSUE TITLE
2.0: Create 2 different type indexes with the same name is allowed.

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#1874]
Failing unit test: https://github.com/couchbase/couchbase-lite-ios/blob/feature/2.0/Objective-C/Tests/DatabaseTest.m#L1354-L1388

**Comment by borrrden** [comment]
Just fixed this with https://github.com/couchbase/couchbase-lite-core/commit/f3c8d9a390428240c5ee57acea764a5d18df026c

**Comment by pasin** [comment]
Thanks!
