### ISSUE TITLE
2.0: -createIndex:forName: should be named "*with*Name"

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1876]
"create ... for name ..." doesn't make sense grammatically. It should be "create ... with name ...".

Basically you can set a value _for_ some key, but you create something _with_ attributes.

It also seems weird that the CBLIndex object isn't actually an index, so creating the object isn't the same thing as creating the index.

**Comment by pasin** [comment]
Thanks. I will fix this.

**Comment by pasin** [comment]
> It also seems weird that the CBLIndex object isn't actually an index ...

I'm not sure what you mean by this. Can you elaborate this more?

**Comment by snej** [comment]
The CBLIndex is more of a _request_; it doesn't represent an actual index. It's only created before the index exists, and is never used to represent an existing index; existing indexes only get referred to by name. Contrast with CBLView in 1.x, which did represent an actual existing view.

**Comment by djpongh** [comment]
already fixed
