### ISSUE TITLE
2.0: CBLFTSIndexOptions is unnecessary

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1877]
CBLFTSIndexOptions is used to specify the collation and whether to ignore accents. But there's already a class for that, CBLQueryCollation, which can be added to the CBLQueryExpression given to the index:

```objc
CBLQueryCollation* collation = [CBLQueryCollation unicodeWithLocale: @"en-US"
                                                         ignoreCase: YES
                                                      ignoreAccents: YES];
CBLQueryExpression* artist = [[CBLQueryExpression property: @"Artist"] collate: collation];
CBLIndex *index = [CBLIndex ftsIndexOn: [CBLFTSIndexItem expression: artist] options: nil];
```
Here the collation is specified exactly without having to use `CBLFTSIndexOptions` or the `options:` parameter.

**Comment by pasin** [comment]
Does this mean C4IndexOptions.language and C4IndexOptions.ignoreDiacritics are not necessary?

Currently there is one thing different between specifying FTS index option and collation, which is `the default locale`. If the default value of `CBLFTSIndexOptions.locale` is the current device locale but the `CBLQueryCollation.locale` is nil (I understand that it is interpreted as 'en' by LiteCore). What do you think about this? Does it make sense to make the default locale to nil or 'en' for both cases?

**Comment by snej** [comment]
They should both default to the current device locale. Whether that's represented as a 'nil' value or by pre-populating the property with a string value is up to you. I'd say the latter is better since it lets the developer see what locale is going to be used.

**Comment by snej** [comment]
Changing this will require some LiteCore fixing — I just found that if you set FTS collation by using a CBLQueryCollation, LiteCore ends up using inconsistent index names so the query fails. Filed https://github.com/couchbase/couchbase-lite-core/issues/239.

**Comment by pasin** [comment]
CBLFTSIndexOptions no longer exists. The properties are moved to the FullTextIndex class itself.
