### ISSUE TITLE
2.0 : The default Collation.locale should be the current device locale

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#1880]
Based on the discussion in https://github.com/couchbase/couchbase-lite-ios/issues/1877.

**Comment by pasin** [comment]
CC: @hideki @borrrden

**Comment by borrrden** [comment]
Is this actionable now?

**Comment by pasin** [comment]
Yes

**Comment by borrrden** [comment]
This won't work for .NET because sometimes the default culture is not valid for collation.  It is something called "Invariant culture."  What should it be in that case?

**Comment by borrrden** [comment]
The [Microsoft Docs](https://msdn.microsoft.com/en-us/library/4c5zdc6a(v=vs.71).aspx) indicate that it is associated with a cultureless English language, so in that case I will use "en" instead I think.
