### ISSUE TITLE
sample code CollectionUtils.h not found ??

### ISSUE THREAD

**Issue by michaelmou** [couchbase/couchbase-lite-ios#1881]
Hello, thank you for your contribution on this project..It's great, but there's some bug on your sample code that I can run.. please tell me the method to fix that , thank you 
--------
* Version:   VERSION
* Client OS: NAME_AND_VERSION
* Server:    NAME_AND_VERSION

**Comment by pasin** [comment]
@michaelmou What is CBL version are you using? Which example code are you trying to run?

**Comment by djpongh** [comment]
Without more info we're unsure how to help.

**Comment by snej** [comment]
For the record, it sounds like @michaelmou didn't update/init the submodules when cloning the repo. (If you're still reading, read the build instructions and follow them exactly!)
