### ISSUE TITLE
2.0: Change the default data protection to CompleteUntilFirstUserAuthentication

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#1883]
From the comment in https://forums.developer.apple.com/message/140215#140215, the default file protection is `NSFileProtectionCompleteUntilFirstUserAuthentication`. Currently we are setting it to `NSFileProtectionCompleteUnlessOpen` - which allows the database being able to used when the screen is locked (once the database is opened once in foreground - if the app is awaken from the background, the database cannot be used.) but not the attachments.

After discussing with @snej , we probably should change the default value to `NSFileProtectionCompleteUntilFirstUserAuthentication`.

Related Issue: #1606

**Comment by djpongh** [comment]
not going to do this
