### ISSUE TITLE
Order by date

### ISSUE THREAD

**Issue by Codeido** [couchbase/couchbase-lite-ios#1893]
Hi, there is a way to order the result of a query by a date field? Or I can do that only with the result array?

--------
* Version:   2.0 Build 16
* Client OS: iOS 10.3
* Server:    -

**Comment by snej** [comment]
Hi! Please ask your question on the [Couchbase web forum](https://forums.couchbase.com/c/mobile) or the [Couchbase Mobile mailing list](https://groups.google.com/forum/#!forum/mobile-couchbase). We use Github issues only for bug reports and feature suggestions. Thanks.
