### ISSUE TITLE
Can't run KIF and CouchbaseLite together

### ISSUE THREAD

**Issue by sellingsolutions** [couchbase/couchbase-lite-ios#1894]
--------
* Version:   CouchbaseLite 1.4.0
* Client OS: iOS 10.3
* Server:    -

**Xcode Crash**
https://gist.github.com/sellingsolutions/109134c1f8489bcec186de93b59854af

**lldb bt all**
https://gist.github.com/sellingsolutions/3cfa2b1e66ffd33b9bcaaa4e439fe23e

This crash has surfaced before in earlier tickets, what you guys found then was that CouchbaseLite had been tied to 2 targets and subsequently CBL was loaded twice and run at the same time.

That's probably true in this case as well since I'm running the KIF tests in one target which then loads the app target.

Do you guys have any advice as to how I could run KIF together with CouchbaseLite?
(Besides following the guide here https://github.com/kif-framework/KIF/blob/master/README.md)

**Comment by snej** [comment]
```
*** Assertion failure in -[CBL_Revision initWithDocID:revID:deleted:](), /Users/jenkins/jenkins/workspace/couchbase-lite-ios-builds/couchbase-lite-ios-community/Source/CBL_Revision.m:45
 *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '!revID || [revID isKindOfClass: [CBL_RevID class]]'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010cc29b0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010c695141 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010cc2dcf2 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x0000000106d9d69b -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 165
	4   App                        0x00000001033dcfe5 _AssertFailed + 485
	5   App                        0x000000010336d691 -[CBL_Revision initWithDocID:revID:deleted:body:] + 0
	6   App                        0x00000001033764d9 -[CBLRestPuller changeTrackerReceivedSequence:docID:revIDs:deleted:] + 537
	7   App                        0x0000000103385ffb __38-[CBLChangeTracker parseBytes:length:]_block_invoke + 173
...
```

>This crash has surfaced before in earlier tickets

Could you post links to them? Because I'm not sure what you mean by "CBL was loaded twice and run at the same time."

>I'm running the KIF tests in one target which then loads the app target.

If these targets are separate processes, there's no problem with CBL loading in each one.

**Comment by sellingsolutions** [comment]
I'm not sure if this actually solved it but I went through all my targets and made sure nothing was loaded/linked twice, it's common that the pods get added twice

![screen shot 2017-09-14 at 14 09 04](https://user-images.githubusercontent.com/1778201/30429044-4b3a82c4-9956-11e7-8ebf-d96bfbc632a0.png)

**Comment by sellingsolutions** [comment]
I'm now able to run my KIF tests again
