### ISSUE TITLE
2.0 : and Query expression in where clause not working properly with meta().id

### ISSUE THREAD

**Issue by rajagp** [couchbase/couchbase-lite-ios#1896]
--------
* Version:   2.0 DB16
* Client OS: Tested on iOS. Likely to be an issue on all platforms. 

This issue may be a lite_core issue but since I encountered this with CBL iOS , Im filing it here. May have to be cloned to other platform or lite_core repos appropriately.

**Case1** 
The following query returns an empty array even though there are documents that match the where clause (see Case2)
```
 let searchQuery = Query
        .select(SelectResult.all())
        .from(DataSource.database(db))
        .where(Expression.property("type").equalTo("hotel").and(Expression.meta().id.equalTo("hotel_15912")))
        .limit(limit)

```

**Case2** 
The following query returns the matching hotel document of type = "hotel"
```
    let searchQuery = Query
        .select(SelectResult.all())
        .from(DataSource.database(db))
        .where(Expression.meta().id.equalTo("hotel_15912"))
        .limit(limit)
```

( You may use this playground for testing purposes : -
https://github.com/couchbaselabs/couchbase_lite_query_playground/tree/master )

(CC @hideki , @pasin , @snej , @borrrden )

**Comment by pasin** [comment]
@rajagp Is this still an issue?

**Comment by rajagp** [comment]
Lets close it . I think there was possibly a corruption of the local database which may have caused the issue - It had to do with adding a document of  type of "hotel" locally to travel sample bucket which messed things up. ( If it resurfaces, I will reopen)
