### ISSUE TITLE
2.0: Query does not return certain properties although it exists in the document

### ISSUE THREAD

**Issue by rajagp** [couchbase/couchbase-lite-ios#1897]
--------
* Version:   2.0 DB 16
* Client OS: Observed on CBL 2.0  but likely to be an issue on other platforms as well.
Filing issue against iOS since it is observed here. Please clone the issue appropriately as needed

The document `hotel_15912` : https://gist.github.com/rajagp/eb75f4d04f9a52865883d1dd797538d7

**case 1:**
Consider this query
```
let searchQuery = Query
        .select(
            SelectResult.expression(Expression.meta().id),
                SelectResult.expression(Expression.property("title")),
                SelectResult.expression(Expression.property("city")))
        .from(DataSource.database(db))
        .where(Expression.property("type").equalTo("hotel"))
        .orderBy(Ordering.property("title").ascending())
        .limit(limit)
```
Returned results:
```[["id": Optional(hotel_15912), "city": Optional(Liverpool), "title": Optional(<null>)]]```

Expected results:
```[["id": Optional(hotel_15912), "city": Optional(Liverpool), "title": Optional(Liverpool)]]```

**case 2: Requesting url field**
Consider this query
```
let searchQuery = Query
        .select(
            SelectResult.expression(Expression.meta().id),
                SelectResult.expression(Expression.property("url")),
                SelectResult.expression(Expression.property("city")))
        .from(DataSource.database(db))
        .where(Expression.property("type").equalTo("hotel"))
        .orderBy(Ordering.property("title").ascending())
        .limit(limit)
```
Returned results (as expected)
```[["id": Optional(hotel_15912), "city": Optional(Liverpool), "url": Optional(http://www.theliner.co.uk/)]]```

I tried to fetch property "name", it fails. So the query seems to work for certain properties

( You may use this playground for testing purposes : -
https://github.com/couchbaselabs/couchbase_lite_query_playground/tree/master )

(CC @hideki  , @pasin  , @snej , @borrrden

**Comment by pasin** [comment]
@rajagp Is this still the issue?

**Comment by rajagp** [comment]
Lets close it. Seems to work with DB19
