### ISSUE TITLE
2.0: version '2.0DB016' in the Info.plist not allowed in App store

### ISSUE THREAD

**Issue by Codeido** [couchbase/couchbase-lite-ios#1906]
I have tried to upload a build on the app store (testflight), but I get this error:
**ERROR ITMS-90060: "This bundle is invalid. The value for key CFBundleShortVersionString '2.0DB016' in the Info.plist file must be a period-separated list of at most three non-negative integers."**

Can you fix it?
Thanks
--------
* Version:   2.0DB016
* Client OS: iOS 11
* Server:    -

**Comment by pasin** [comment]
Thanks for reporting this. I will fix this today. How do you install the CBL library (Cocoapods, Carthage, or downloaded binary)?

**Comment by Codeido** [comment]
Cocoapods

**Comment by pasin** [comment]
I have fixed this and committed to `feature/2.0` branch. The fix will be included in the next DB17.

**Comment by Codeido** [comment]
Only another thing. The installation using Cocoapods is really really slow, more than 30 minutes. Why?
Is not only a problem of this new commit, but in general of the release 2.0.

```
pod 'CouchbaseLiteSwift', :git => 'https://github.com/couchbase/couchbase-lite-ios', :commit => '0acb6df71e624a94560d4e8f0b29180b208bac76', :submodules => true
```

**Comment by pasin** [comment]
> The installation using Cocoapods is really really slow, more than 30 minutes. Why?

It's the reason that I have described in #1891. More than 30 mins seems to be too long though. I'm creating #1908 to double check the time and see if we can optimize anything or not. Thanks!
