### ISSUE TITLE
2.0: Need a Swift 3.2/Swift 4 compatible version of CouchbaseLiteSwift framework

### ISSUE THREAD

**Issue by rajagp** [couchbase/couchbase-lite-ios#1907]
--------
* Version:   2.0 DB
* Client OS: iOS 11

Now that Xcode9 is GM, we would need to provide a swift 3.2/ Swift4 ABI compatible version of CouchbaseLiteSwift available for download from https://developer.couchbase.com/documentation/mobile/2.0/whatsnew.html

<img width="568" alt="screen shot 2017-09-21 at 10 48 32 pm" src="https://user-images.githubusercontent.com/645251/30727404-0650d40a-9f1f-11e7-9c5d-24a57d710b65.png">

(CC @pasin )

**Comment by pasin** [comment]
I think we need to upgrade XCode on the build machine (Dan's macbook?). This should be done before releasing DB17.

**Comment by pasin** [comment]
I have created https://issues.couchbase.com/browse/MB-26143.

**Comment by pasin** [comment]
From DB18, we build the binary with XCode 8, and we set Swift version to 3.2.
