### ISSUE TITLE
2.0 : Cocoapods takes long time to finish installing

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#1908]
From #1891 and #1906, the cocopods could take a long time to finish install. The main reason is that it is because we need to build all (FAT) frameworks for all platforms in the pods preparation steps. At that step, we don't know have an ability to know what platform the app is.

I'm creating this ticket to see what else we can do to optimize the installation time.

**Comment by pasin** [comment]
Today I discovered that when running `pod install`, cocoapods processed both podspec (CouchbaseLite.podspec and CouchbaseLiteSwift.podspec) after downloading the repository. This means that both CouchbaseLite and CouchbaseLiteSwift frameworks will be built at that time regardless of what the dependency will be used.

I couldn't find a way for users to specify the podspec file to use when specifying git repository to download the project. This seems to be a limitation now.

**Comment by gcox** [comment]
How long does it actually take to complete? I'm using a brand new MBP and had to gave up after 30 minutes.

**Comment by pasin** [comment]
I have just timed the `time pod install --verbose` command using my Late 2013 Macbook pro. Basically the time taken was about 22 mins.

```
real	21m31.403s
user	64m3.839s
sys	5m22.622s
```
I knew that this is still slow. With that we need to pre-build framework and the current Cocoapods limitation, we are not able to optimize the `pod install` time at this moment.
