### ISSUE TITLE
2.0: CBLDatabase.allDocuments is too limited to be useful

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1911]
In 2.0, CBLDatabase.allDocuments has lost the ability to set query options. This means that you can't

* Restrict the range of keys (for example to ones with a prefix)
* Iterate in descending order
* Paginate using an offset or limit
* Include deleted documents

If it's this limited, it doesn't seem useful to have it. (It's also not in the API spec, I see.)

**Comment by gtur-disney** [comment]
Sorry, haven't played with 2.0 much, but we could use range and need deleted documents (to enable "server-always-wins" scenario). Other options seem very useful too. Are there other alternatives to get these features just as easily?

**Comment by pasin** [comment]
Currently allDocuments is not a part of 2.0 release (we will need to clean up the API a bit). Currently we could use the Query API to query all docs by projecting the meta.id to get the document IDs. The only thing that I cannot do is to included deleted docs.

**Comment by snej** [comment]
Right. I propose we remove the `allDocuments` method.
