### ISSUE TITLE
Peer sync between High Sierra and iOS 11 CBLWarnUntrustedCert error

### ISSUE THREAD

**Issue by brendand** [couchbase/couchbase-lite-ios#1912]
Using peer-to-peer sync, in High Sierra I'm getting the following errors:

```
10:02:32.818‖ DEALLOC CBLRemoteLogin[https://iPhone-8.local.:49219/db-edca70d0d6524c0fbc527270114445a6]
10:02:32.923‖ WARNING: CouchbaseLite: SSL server <iphone-8.local.> not trusted; cert chain follows: {at CBLWarnUntrustedCert:294}
10:02:32.923‖ WARNING:     Anonymous: error = CSSMERR_TP_NOT_TRUSTED {at CBLWarnUntrustedCert:306}
2017-09-27 10:02:32.925849-0600 Tap Forms 5[36217:2160053] Task <104BF60E-1A26-4EF2-BCCE-BB3910270EDA>.<1> HTTP load failed (error code: -999 [1:89])
2017-09-27 10:02:32.925875-0600 Tap Forms 5[36217:2160054] Task <104BF60E-1A26-4EF2-BCCE-BB3910270EDA>.<1> finished with error - code: -999
10:02:32.926‖ CBLRemoteJSONRequest[GET https://iPhone-8.local.:49219/db-edca70d0d6524c0fbc527270114445a6/_local/037a993f64ee86ee9146564094af06f08fd83d21]: Got error NSURLError[-999, "cancelled", <https://iphone-8.local.:49219/db-edca70d0d6524c0fbc527270114445a6/_local/037a993f64ee86ee9146564094af06f08fd83d21>]
10:02:32.926‖ Replication: CBLRestPuller[https://iPhone-8.local.:49219/db-edca70d0d6524c0fbc527270114445a6] took 0.108 sec; error=(null)
```

I do setup an anonymous SSL certificate when I create my `CBLListener` object:

```
BOOL success = [self.syncListener setAnonymousSSLIdentityWithLabel:@"peer-sync" error:&error];
```

Is there anything more I have to do than this to get encrypted syncing between peers?

It worked fine in macOS Sierra and iOS 10.

But what's interesting is it works fine if I make a change on the Mac. That is, the iOS 11 device is able to successfully pull from the Mac. But if I make a change on the iOS 11 device, the Mac running High Sierra complains about the untrusted certificate.

Is there a way I can get the Mac to trust the certificate from the iOS device?

--------
* Version:   1.4.1
* Client OS: macOS High Sierra and iOS 11
* Server:    n/a

**Comment by snej** [comment]
By default, the SSL handshake will always fail if the server has a self-signed cert. How are you configuring the replicator to allow the cert?

**Comment by brendand** [comment]
Well that may be the issue. I'm not doing anything in particular. It just worked before.

I create my puller this way:

```
self.currentPull = [self.databaseDocument.couchDatabase createPullReplication:peerURL];

NSDictionary *pullProperties = @{@"remoteUUID" : self.currentPullPeer.service.name};
self.currentPull.customProperties = pullProperties;
[self.currentPull start];

```

I based my code off your sync grocery example. Although your's was in Swift. Mine is in Objective-C.

What can I do to the CBLReplicator to tell it to accept the anonymous certificate? Not sure why it worked before now though.

**Comment by brendand** [comment]
According to the Wiki:

> Note: In versions after 1.1, this problem won't occur as long as the hostname of the replication URL ends with .local (which is used by Bonjour for devices on the local network.) So if you're using Bonjour to discover peers, you won't have SSL trust issues.

I am using Bonjour and the address being connected to does end with .local:

>CouchbaseLite: SSL server <iphone-8.local.> not trusted

But I'll try out this and see if that helps:

>To get around this, the client can get a copy of the server cert from the CBLReplication, then tell the replicator to trust the cert by calling the setAnchorCerts method, and then start the replication again.

Hopefully that'll solve the problem.

**Comment by brendand** [comment]
So where would I put the code to get the client certificate and allow it to be used?

I put it in my pullStatusChanged handler, but it doesn't ever get a cert:

```
SecCertificateRef certRef =  self.currentPull.serverCertificate;
if (certRef) {
	[CBLReplication setAnchorCerts:@[CFBridgingRelease(certRef)] onlyThese:NO];
}
```

It seems that maybe CBL is handling the certificate error but not telling the calling application. Because I don't even see any error in the pull replicator's lastError object.

**Comment by snej** [comment]
Oops, I forgot about the special-casing of `.local` hostnames. You're right, the connection should work...

**Comment by brendand** [comment]
It did seem like it should with that special case. 

Do you have any recommendations on what I could try to get this to work on High Sierra?

**Comment by brendand** [comment]
So I'm not having much luck getting this to work now.

I'm still getting the error:

```
CouchbaseLite: SSL server <iphone-8.local.> not trusted; cert chain follows: {at CBLWarnUntrustedCert:294}
```

I tried the setAnchorCerts function, but that didn't work either.

Do you have any other suggestions on what I could try? I was trying to debug Couchbase Lite when referenced as a development build (not archiving) and putting a breakpoint in Couchbase Lite. I'm sure I was able to do that before many Xcodes before. But it's not stopping at my breakpoints now. 

I also tried changing the name of the anonymous SSL identity label to see if generating a new self signed certificate would work, but it didn't unfortunately.

So I'm a bit stuck at the moment.

**Comment by snej** [comment]
For breakpoints to work, the source file you're setting the breakpoint in has to be at the same path as the file that was compiled when building the framework. So if you build the framework on the same machine as your app, it should generally work...

**Comment by brendand** [comment]
Have you seen this problem at all with High Sierra? I mean the untrustworthy SSL certificate? I'm starting to get more and more customers asking me about why nearby sync has stopped working.

I am building the framework on the same Mac as I'm running the app on.

**Comment by brendand** [comment]
Well I got peer sync to work again, but only by disabling SSL completely. Not an ideal situation, but perhaps maybe better than nothing. I'm not sure what's worse, non-encrypted syncing, or no syncing at all.

I know this is CBL 1.4 code and you're focusing on 2.0 code now, but is this one perhaps serious enough to try and fix in 1.4? Does peer sync with an SSL connection currently work on High Sierra in CBL 2.0?

I'm guessing either it may be a bug in High Sierra that needs a workaround now or Apple's doubling down on security and has closed some sort of hole that is now causing this problem for CBL.

**Comment by pasin** [comment]
@brendand I will look into this next week as part of 1.4.1.

**Comment by brendand** [comment]
@pasin Awesome! Thanks! I really appreciate it. Perhaps also test if `[CBLAuthenticator basicAuthenticatorWithName:password]` is still working too. I don't think it requires an SSL connection, but I had to turn off authentication and SSL to get it to sync.

**Comment by pasin** [comment]
The reason that it failed is because the check on this [line](https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CBLAuthorizer.m#L169) is failed. On High Sierra, there are two error codes returned instead of one as below:

```
StatusCodes =     (
        "-2147408896", // CSSMERR_APPLETP_HOSTNAME_MISMATCH
        "-2147409622"  // CSSMERR_TP_NOT_TRUSTED
);
```

For Basic Auth, I don't see any issue.

**Comment by brendand** [comment]
Awesome! It works! Case closed! Thanks for fixing it so quickly @pasin

**Comment by brendand** [comment]
So this error appears to have reared its ugly head on iOS 11.3 beta 2 now using peer-to-peer syncing.

Here's the errors I see now:

```
WARNING: CouchbaseLite: SSL server <voyager.local.> not trusted; cert chain follows: {at CBLWarnUntrustedCert:293}
2018-02-06 18:21:40.145287-0700 Tap Forms[346:37039] WARNING:     Anonymous {at CBLWarnUntrustedCert:298}
2018-02-06 18:21:40.151141-0700 Tap Forms[346:37241] Task <13E30C99-FA24-4E12-A63A-52B45DF03B3C>.<1> HTTP load failed (error code: -999 [1:89])
2018-02-06 18:21:40.151294-0700 Tap Forms[346:36920] Task <13E30C99-FA24-4E12-A63A-52B45DF03B3C>.<1> finished with error - code: -999
2018-02-06 18:21:40.152352-0700 Tap Forms[346:37039] CBLRemoteJSONRequest[GET https://Voyager.local.:54243/db-edca70d0d6524c0fbc527270114445a6/_local/11e43740fc02d3ea1e9fe3c05af9b7ff07c99b21]: Got error NSURLError[-999, "cancelled", <https://voyager.local.:54243/db-edca70d0d6524c0fbc527270114445a6/_local/11e43740fc02d3ea1e9fe3c05af9b7ff07c99b21>]
```

This was the High Sierra fix:

```
#if !TARGET_OS_IPHONE
            else if ([problem isEqualToString: @"StatusCodes"]) {
                // Same thing, but on Mac they express the problem differently :-p
                // From #1912:
                // 10.13 (High Sierra) : @[CSSMERR_APPLETP_HOSTNAME_MISMATCH and CSSMERR_TP_NOT_TRUSTED]
                // Less than 10.13     : @[CSSMERR_APPLETP_HOSTNAME_MISMATCH]
                if ([details[problem] containsObject: @(CSSMERR_APPLETP_HOSTNAME_MISMATCH)])
                    accept = (i == 0 && SecTrustGetCertificateCount(trust) == 1 && localDomain);
            }
#endif
```

Is there an equivalent fix for iOS 11.3 perhaps?

**Comment by brendand** [comment]
So I did a bit of debugging and I dumped out the list of problems that came in during handshake and this is what I got:

```
host: voyager.local.
2018-02-06 19:02:21.566389-0700 Tap Forms[373:51251] problem: SSLHostname
2018-02-06 19:02:21.566417-0700 Tap Forms[373:51251] problem: **MissingIntermediate**
2018-02-06 19:02:21.566488-0700 Tap Forms[373:51251] WARNING: CouchbaseLite: SSL server <voyager.local.> not trusted; cert chain follows: {at CBLWarnUntrustedCert:293}
2018-02-06 19:02:21.566550-0700 Tap Forms[373:51251] WARNING:     Anonymous {at CBLWarnUntrustedCert:298}
```

So I think maybe the real problem is "MissingIntermediate"?

I didn't think you needed an intermediate SSL certificate for self-signed certificates?

**Comment by brendand** [comment]
So looking at the code in acceptProblems (in CBLAuthorizer.m), I see this line:

`accept = (i == 0 && SecTrustGetCertificateCount(trust) == 1 && localDomain);`

That seems fine and in this case the call to `SecTrustGetCertificateCount(trust)` does return 1 and the domain is `.local.` and `i == 0`, so that returns `YES`.

But I think the second time it goes through the loop and resets `accept = NO`, then because the `MissingIntermediate` doesn't get handled, the value of `accept` is NO at that time. So that's why it's failing.

What is the correct way to handle this problem?

As a test I just forced `accept = YES` and that worked. But it was just a test to see if I was on the right track.

**Comment by Visput** [comment]
We have the same issue on peer-to-peer replication since iOS 11.3.
@pasin Do you have any suggestion on how to solve this?

We have exactly the same setup as @brendand: we use https connection with basic auth and self-signed certificated set by calling `CBLListener.setAnonymousSSLIdentityWithLabel(self.database.name)`.
It was working fine on iOS < 11.3.

**Comment by pasin** [comment]
I think "MissingIntermediate" is find for self-signed certificate. 

@snej what is your take on this?

**Comment by snej** [comment]
In a typical self-signed situation there's only one cert (as shown in the log from Feb 6) so there is no intermediate.

It's been quite a long time since I looked at the logic in that method, so I don't have any direct advice on how to change it.

**Comment by rahimrahman** [comment]
@Visput have you been able to resolve the issue of peer to peer replication with devices using iOS > 11.3?

We have similar issue and research got me here, saw your comment and got me to experiment.

iPod 6th Gen running iOS 11.4 were able to sync with iPhone 5S Simulator 11.0.1 but iPhone 5S Simulator 11.0.1 could not sync with iPod 6th Gen (11.4).

**Comment by pasin** [comment]
I have added MissingIntermediate to the list of accepted problems for local domain.
