### ISSUE TITLE
2.0: Replicator pendingDocumentIDs feature

### ISSUE THREAD

**Issue by BrandonNott** [couchbase/couchbase-lite-ios#1929]
The replicator `pendingDocumentIDs` feature is useful to us for 2 use cases:

1.  Similar to the email download status shown in the iOS Mail app, we want to convey the replicator status to our users.  i.e. "3 Uploads Pending" or "Updated Just Now". 

<img width="665" alt="screen shot 2017-10-11 at 4 36 32 pm" src="https://user-images.githubusercontent.com/12227784/31472245-6b8b939a-aea2-11e7-99c7-1dd6ef321c2c.png">
<img width="636" alt="screen shot 2017-10-11 at 4 36 44 pm" src="https://user-images.githubusercontent.com/12227784/31472248-6e335704-aea2-11e7-89d0-05fe7bd8baff.png">

2. When displaying user generated documents in a list, it is helpful to distinguish documents pending upload from the rest.

**Comment by pasin** [comment]
Thanks for the suggestion. I have created an issue in our internal 2.0 API repo for considering this.

**Comment by pasin** [comment]
We will track this feature in API repo.
