### ISSUE TITLE
2.0: Crashed unit tests after merging Mutable Fleece

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#1934]
The following unit tests are crashed after merging mutable fleece. The root cause of the crashes appears to be the same which is caused by enumerating the dictionary keys.

DocumentTest
* [testEnumeratingKeys](https://github.com/couchbase/couchbase-lite-ios/blob/feature/2.0/Objective-C/Tests/DocumentTest.m#L1484)

DictionaryTest
* [testEnumeratingKeys](https://github.com/couchbase/couchbase-lite-ios/blob/feature/2.0/Objective-C/Tests/DictionaryTest.m#L238)

ConflictTest
* [testConflict](https://github.com/couchbase/couchbase-lite-ios/blob/feature/2.0/Objective-C/Tests/ConflictTest.m#L162)

ReplicatorTest
* [testPullConflict](https://github.com/couchbase/couchbase-lite-ios/blob/feature/2.0/Objective-C/Tests/ReplicatorTest.m#L218)
* [testPullConflictNoBaseRevision](https://github.com/couchbase/couchbase-lite-ios/blob/feature/2.0/Objective-C/Tests/ReplicatorTest.m#L254)

**Comment by pasin** [comment]
The issue is that the NSArray of the keys needs to be retained/cached when this [method](https://github.com/couchbase/couchbase-lite-ios/blob/feature/2.0/Objective-C/CBLReadOnlyDictionary.mm#L205) is called.

**Comment by snej** [comment]
Weird, I can't reproduce the problems. I've tried macOS and iOS.
