### ISSUE TITLE
High Sierra Peer-to-Peer sync and App Transport Security

### ISSUE THREAD

**Issue by brendand** [couchbase/couchbase-lite-ios#1936]
For customers who have upgraded to High Sierra, I was getting reports of SSL connection errors when they were attempting to use peer-to-peer syncing. With the most recent High Sierra fix for the untrustworthy SSL certificate, it was also necessary to enable the `Allow Arbitrary Loads YES` option in the `Info.plist` file for the `App Transport Security` section on macOS to avoid this error. I thought I'd file this issue so you can update the Wiki to note this change in requirement with High Sierra. 

This was the output in the log without `Allow Arbitrary Loads YES` enabled:

```
default	08:36:41.442048 +0100	Tap Forms Mac 5	System Trust Evaluation yielded status(-9802)
error	08:36:41.442077 +0100	Tap Forms Mac 5	ATS failed system trust
error	08:36:41.442132 +0100	Tap Forms Mac 5	System Trust failed for [9:0x604000572b40]
default	08:36:41.442165 +0100	Tap Forms Mac 5	TIC TLS Trust Result [9:0x604000572b40]: 4
error	08:36:41.442206 +0100	Tap Forms Mac 5	TIC SSL Trust Error [9:0x604000572b40]: 3:0
default	08:36:41.442243 +0100	Tap Forms Mac 5	TIC TCP Conn Cancel [9:0x604000572b40]
default	08:36:41.442390 +0100	Tap Forms Mac 5	NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)
error	08:36:41.442474 +0100	Tap Forms Mac 5	Task <E5BF0E23-E22A-4046-A0DC-87E3EEC36C5E>.<1> HTTP load failed (error code: -1200 [3:-9802])
error	08:36:41.442599 +0100	Tap Forms Mac 5	Task <E5BF0E23-E22A-4046-A0DC-87E3EEC36C5E>.<1> finished with error - code: -1200
default	08:36:41.443258 +0100	Tap Forms Mac 5	TIC TCP Conn Destroyed [9:0x604000572b40]
```

Afterwards there were no errors and an SSL connection was established.

--------
* Version:   1.4.1
* Client OS: macOS High Sierra
* Server:    peer-to-peer

**Comment by pasin** [comment]
Thanks for the info.

**Comment by djpongh** [comment]
Refiled for doc bug under mobile-portal #826

**Comment by brendand** [comment]
@djpongh I don't believe this has anything to do with #826, which was about ForestDB encryption.
