### ISSUE TITLE
2.0 : WS Warning - Unexpected or unclean socket disconnect

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#1937]
When running the replicator, the WS Warning as below keeps showing up:

```
CouchbaseLite WS WARNING: {1} Unexpected or unclean socket disconnect! (reason=WebSocket status, code=1000)
```

**Comment by snej** [comment]
The warning comes from `WebSocketImpl::onClose` in LiteCore, which is called by `c4socket_closed`. It looks as though this method wants the CloseStatus to have code 0, while the call to `c4socket_closed` (by CBLWebSocket?) has code 1000 and reason kWebSocketClose. But that is a normal WebSocket close code, so it seems like it shouldn't produce a warning. So this might be something to fix in LiteCore.

**Comment by snej** [comment]
Aha, the problem is in `c4socket_closed`, when it translates the C4Error to a CloseStatus:
```c++
    if (error.code == 0) {
        status.reason = kWebSocketClose;
        status.code = kCodeNormal;
```
