### ISSUE TITLE
2.0: Warning when trying to call db.close()

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-ios#1938]
With @pasin in workshop, filing a stub ticket to be filled out with more details later.

- On userInitiated dispatchQueue
- Open database
- Run a query 
- Close database

Observed:

- Warning about sqlite query being open

--------
* Version:   2.0 db 18
* Client OS: iOS

**Comment by pasin** [comment]
This should be fixed by https://github.com/couchbase/couchbase-lite-ios/commit/4ab2589320cb110ccecd2c387f5993a127070070.
