### ISSUE TITLE
2.0: Missing reserved fields in CBLDocument toDictionary method

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-ios#1939]
toDictionary not including doc id.

(stubbed out bug, with @pasin in workshop -- will fill out later)

--------
* Version:   cbl 2.0 db 18
* Client OS: NAME_AND_VERSION
* Server:    NAME_AND_VERSION

**Comment by pasin** [comment]
Here is the use case: Document.toDictionary() > Dictionary > Data > Codable Model. The Dictionary doesn't contain the document ID information by default so that the Codable Molde losses the document ID information.

**Comment by snej** [comment]
We're intentionally not including metadata in dictionaries.
What's a Codable Model?

**Comment by pasin** [comment]
@snej is right. The toDictionary() method was meant to return only content, not metadata.
