### ISSUE TITLE
objc_storeWeak Crash in reachabilityChanged 

### ISSUE THREAD

**Issue by msanilkumar2020** [couchbase/couchbase-lite-ios#1944]
Hi,

We are simulating network up/down scenario, we found below crash in reachability.

Attached screen shot.
<img width="1056" alt="screen shot 2017-11-02 at 3 36 19 pm" src="https://user-images.githubusercontent.com/751736/32324521-b3aae602-bff1-11e7-899f-f3815dc807df.png">

--------
* Version:   1.4.1
* Client OS: iOS 11.3

**Comment by pasin** [comment]
From the crash point, I couldn't think why that would crash as the self object should be retained.

Do you start a continuous replicator and keep simulating network up/down several times? Please let me know your test scenario so I can try to reproduce the issue?

**Comment by msanilkumar2020** [comment]
@pasin , Yes we started continuous replication and simulating network up/down scenario. After doing it  several times it crashed in reachability.

**Comment by snej** [comment]
Please post stack traces, logs or source code as text, not screenshots. Screenshots can't be searched, indexed or copied from. They are difficult to read on a phone and can be slow to download on a flaky cell connection. Thanks.
When pasting logs, put a line of three back-quotes (\`\`\`) before and after, to mark them as raw text.
To get a textual thread backtrace, use the `bt` command in Xcode's debugger console.
