### ISSUE TITLE
2.0: REST API support

### ISSUE THREAD

**Issue by msanilkumar2020** [couchbase/couchbase-lite-ios#1945]
Hi CBL development,

Do you support restbased apis in CBL 2.0?

We are planning to migrate to CBL 2.0, our application is using Restbased Apis.

Looking at the code i am not able to locate code related to Restbased Api's/Listener, NSURLProtocol.

Please let us know your plan on this inclusion in CBL 2.0.

**Comment by pasin** [comment]
@msanilkumar2020 Thanks for inquiry about the 2.0 REST API. Unfortunately, CBL 2.0 will not support REST API, but we have a plan to support the REST API in 2.x.

**Comment by djpongh** [comment]
We'll tag this in our 2.1 release but we are basing additions to the 2.0 API  based on demand so it might not make it in.

**Comment by rajagp** [comment]
More on related note : https://forums.couchbase.com/t/why-couchbase-team-still-doesnt-support-react-native/15003/4 . 
`"Probably for RN world it will be quite enough to expose REST end-point to RN and use fetch requests (as REST is quite well-documented officially by couchbase) instead of bothering with this swagger stuff ending with copypasted crap as “documentation”, but couchbase to decide."  `

**Comment by msanilkumar2020** [comment]
@pasin ,
Do you have any update on this issue?

**Comment by msanilkumar2020** [comment]
Hi @pasin , @djpongh 

Please let me know your plan to implement Restbased support to CBL 2.0.

Because of this issue, we are blocked to migrate to this Version of CBL.

Thanks,
Anil Kumar

**Comment by rajagp** [comment]
@msanilkumar2020  Can you clarify why you are "blocked" ? What type of app are you developing ? We do not have plans of supporting the REST API in CBL 2.1 .

**Comment by msanilkumar2020** [comment]
@rajagp ,
Our's is phonegap based application, we are using restbased Apis to communicate between UI and CBL library.

Without Restbased Api, we wont be able to use CBL 2.0 library.

**Comment by rajagp** [comment]
@msanilkumar2020 - curious - What are your thoughts about developing your own [Cordova](https://cordova.apache.org/plugins/) plugin?

**Comment by msanilkumar2020** [comment]
@rajagp ,
We have multiple platform, in each platform we can't have duplicate implementation. Currently we have common implementation in UI for all platforms.

**Comment by pasin** [comment]
Closed as this is a product management plan / issue.
