### ISSUE TITLE
2.0: "CBL" prefix for Swift

### ISSUE THREAD

**Issue by rajagp** [couchbase/couchbase-lite-ios#1946]
--------
* Version:   DP 18
* Client OS: iOS Swift

Some of our customers have been asking us to bring in "CBL" prefix to Swift . . This is to facilitate searches, auto completion , debugging and to avoid the need to include modules to disambiguate types named identically across frameworks. Although our Swift data types are named accurately per guidelines, it does not lend itself very well in a framework where developers may be linking with several frameworks.(CC @pasin , @waynecarter )

**Comment by snej** [comment]
@djpongh (via email) found the following style references and quotes:

https://www.mobomo.com/2017/03/naming-conventions-for-swift/
https://www.gitbook.com/book/opchen/swift-style-guide2/details
> “Swift types are automatically name spaced by the module that contains them and you should not add a class prefix…”
>“If two names from different modules collide you can disambiguate by prefixing the type name with the module name.”
 
https://github.com/raywenderlich/swift-style-guide/issues/13
>“Definitely do away with prefixes. Apple seems to be encouraging this as well.”
 
https://stackoverflow.com/questions/24214863/swift-class-prefix-needed
Consensus is name spaces are not needed

**Comment by pasin** [comment]
Thanks @snej for the info. I have also talked to @waynecarter about this before the break, and we will not have prefix for CBL Swift per common swift naming convention. Let's close the issue.
