### ISSUE TITLE
Feature Request: Swift Codables support

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1949]
_From @rajagp on November 2, 2017 14:29_

A lot of interest in Swift 4 Codables support in CBL. Although this would be Swift only- it could be the first instantiation of native object support . Some customers have been enquiring about it

_Copied from original issue: couchbase/couchbase-lite-core#283_

**Comment by pasin** [comment]
This provides a very good example about implementing a custom encoder and decoder.

https://www.mikeash.com/pyblog/friday-qa-2017-07-28-a-binary-coder-for-swift.html

**Comment by lightandshadow68** [comment]
Here's one for Swift Dictionaries...

https://github.com/elegantchaos/DictionaryCoding

**Comment by djpongh** [comment]
Moved to: https://github.com/couchbase/couchbase-lite-ios/issues/1949
