### ISSUE TITLE
shorthand API for sync

### ISSUE THREAD

**Issue by jchris** [couchbase/couchbase-lite-ios#195]
So after beating myself up all day over how hard it is to configure synchronization, I came to the conclusion that the only thing for it, is to wrap it up in a tight API, something like this on iOS:

``` Objective-C
[CBLSocialSync syncDatabase: database withURL: remoteURL usingFacebookAppID: kFBAppID];

[CBLSocialSync syncDatabase: database withURL: remoteURL usingTwitterAPIKey: kTwitterAPIKey andSecret: kTwitterAPISecret];

[CBLSocialSync syncDatabase: database withURL: remoteURL usingPersona: YES];
```

![sync setup 3](https://f.cloud.github.com/assets/253/1555762/8cfb036e-4e82-11e3-8a7c-854f770a45eb.png)

This CBLSocialSync module I'm considering would be a wrapper around ALL the complexity in the picture above.

The only clean way to do that, is to give it responsibility both for getting the user logged into the service indicated (it might have to draw some UI...), and for getting the right access tokens / assertions / etc we need from the authentication services. It will also cover the details of installing the authentication into the sync session (pull and push) as well as detecting and handling the sort of errors that might be remedied by getting a new assertion and using it to start a new session with the remoteURL. So that aside from that one line of code, the developer is basically done thinking about sync for their app.

The goal would be to deliver this as a source add-on module (in the Extras folder with CBLUICollectionSource etc) so instead of trying to build a comprehensive library of social sync helpers, we can illustrate the common patterns, and let the community fill them out over time.

**Comment by jayahariv** [comment]
Closing 1.x issue!
