### ISSUE TITLE
1.4 Continuous replication stops working once the app is backgrounded.

### ISSUE THREAD

**Issue by BrandonNott** [couchbase/couchbase-lite-ios#1951]
The push and pull replicators stop detecting changes once our app goes into the background.  Both replicators are set to continuous.

After returning from the background, both replicators have an idle status, however changes in sync-gateway never make their way to the device (or simulator).

We've been able to reproduce this issue consistently by simply backgrounding the app.

Troubleshooting steps include:
 - stopping and starting replication (during the application life cycle and elsewhere)
 - deinitializing and reinitializing the stack (database, replicator and all related pieces).
 - switching over to manual replication.

From our troubleshooting steps, our only working solution was to switch over to manual replication.

To replicate the issue described above:
 1. initialize a stack with continuous push / pull replication.
 2. background the app momentarily and bring it back into the foreground.
 3. create a unique document and save it.

The document will not make it to sync gateway until the application is force quit and relaunched.  

Couchbase Lite 1.4.0 / Sync Gateway 1.4

**Comment by pasin** [comment]
We have fixed replicator backgrounding issues that will be released in 1.4.1, but none of the issues has been seen as described here.

Could you enable Sync, SyncVerbose, ChangeTracker, and ChangeTrackerVerbose logging when reproducing the issue and share the log? Please capture the SGW log and share as well.

**Comment by geraldapeoples** [comment]
When will version 1.4.1 be released?

**Comment by BrandonNott** [comment]
Hi @pasin. I am working to get you those logs ASAP, but no luck recreating the issue this morning.   It seems to be off and on, across environments, in simulator and on device.

**Comment by BrandonNott** [comment]
@pasin, I've enabled the logs you've requested, but at this point we have not been able to replicate the issue so I'm closing it for now.

As development continues if it comes up again we should have the logs and I'll re-open.
