### ISSUE TITLE
2.0: feature request - Replace database

### ISSUE THREAD

**Issue by CezaryBielecki** [couchbase/couchbase-lite-ios#1952]
Can you add replace database from file like it was possible in 1.4?

https://developer.couchbase.com/documentation/mobile/1.4/training/develop/create-database/index.html#using-the-pre-built-database

--------
* Version:   2.0DB018
* Client OS: iOS 11
* Server:    -

**Comment by pasin** [comment]
You could use CBLDatabase's [+copyFromPath:toDatabase:config:error:](https://github.com/couchbase/couchbase-lite-ios/blob/feature/2.0/Objective-C/CBLDatabase.h#L300-L315)to do that.
