### ISSUE TITLE
2.0: Delete Database Failed: there are still open connections 

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#1954]
[From the forum](https://forums.couchbase.com/t/couchbaseliteswift-2-0-0-delete-database-failed-there-are-still-open-connections/14635):

>I tried to delete my couch database on the device with try Database.delete(dbName), but pretty often it failed with "Couchbase: failed to delete database [dbname] Error Domain=LiteCore Code=24 “Still 2 open connection(s) to path[/dbName]/db.sqlite3”

>I stopped the replicator, removed change listener on both replicator and database before the delete, so I don’t know why there are still open connections.

**Comment by jayzhanghs** [comment]
Also as @snej suggested, I waited for a couple of seconds (2~3) before trying to delete the DB. It may still fail with the same error.

**Comment by jayzhanghs** [comment]
Is there any update on this?

**Comment by snej** [comment]
Can you still reproduce it in DB21? I think it's likely this issue is a dup of #1958.

**Comment by pasin** [comment]
I believe this issue was fixed in the feature/2.0 branch. Please reopen the issue if the issue still exists.

**Comment by jayzhanghs** [comment]
I'm using DB21 and it's much less frequent than before, but I still get the problem once in a while, and when it happens it takes a long time before a retry would successfully close the DB, and I often ended up killing the app.

**Comment by rajagp** [comment]
I believe that the fix fix will be going into DB22...You can pull the feature/2.0 branch and build from source and try with that. Let us know if issue exists.

**Comment by CezaryBielecki** [comment]
In general it shouldn't happen? On 2.0 it still happens for me

**Comment by snej** [comment]
Do you have a reproducible case? Or can you provide details like the log output and a thread dump at the time of the error?

**Comment by nightstranger007** [comment]
Facing this issue (Can't delete db file while other connections are open)
Any update?
