### ISSUE TITLE
Implement new Logging API

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#1955]
New Logging API support:
* Console Log
* File Log
* Custom Log

PRD: https://docs.google.com/document/d/1NmD2kD8_cO3XG0LTT5GdnMBzmbtT94QlNZClw_iynY4/edit

Design Doc:
https://docs.google.com/document/d/1V_kVZuvckAPX41obYsu9SAqRuLxwe0TLbZDrMA_InEE/edit

**Comment by rajagp** [comment]
@hideki  : We would need this on Android as well.

**Comment by pasin** [comment]
Finished in 53ef58530e27e4ba11e64928b9e5e4ba902c440a.
