### ISSUE TITLE
2.0: Swift binary not working with XCode 9.1.

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#1956]
Error: `Module compiled with Swift 4.0 cannot be imported in Swift 3.2.2`.

This means that we need to update the XCode on the build machine again. Hope Swift ABI is stable soon.

**Comment by jayzhanghs** [comment]
@pasin thanks. looking forward to the push.

**Comment by jayzhanghs** [comment]
Also the CBLSwift 2.0 framework distributed by Couch is a Fat library containing both simulator and device slices. Could you add a strip-framework shell script which we can add to our build phase to remove the simulator slices when we submit our code to App Store?

**Comment by jayzhanghs** [comment]
@pasin  I'm trying to compile couchbase-lite-ios myself, followed the instruction on readme, particularly ran the `git submodule update --init --recursive` command, then switched to feature/2.0 branch, but still get a bunch of build errors, starting with "Fleece.h" not found.

**Comment by pasin** [comment]
You probably need to the following order:
```
$git checkout feature/2.0
$git submodule update --init --recursive.
```

**Comment by jayzhanghs** [comment]
Thanks @pasin! You're right, I have to do the recursive update after. I guess it's because when checking out the branch the subdirectories have contents purged.

**Comment by jayzhanghs** [comment]
The CouchbaseLiteSwift framework compiled by myself does work, but one thing I noticed is that the headers contained in it only has CBL classes, not those "bare" classes like `Database`, `Document`, etc.

**Comment by pasin** [comment]
Those CBL classes are from Objective-C because the Swift framework is calling into the Objective-C. As of now, to make the Objective-C codes visible to Swift, I need to make those public too. There might be a better way of doing it, but I couldn't find that now.

**Comment by jayzhanghs** [comment]
Showing those CBL classes is fine with me but I don't know why Database etc are not shown in the headers folder. 

The more serious thing is I cannot create new Document object with this Feature/2.0 branch compiled framework. All initializers of it result in compilation errors.

**Comment by pasin** [comment]
Can you post the command line that you ran?

**Comment by jayzhanghs** [comment]
This seems to be an issue with Feature/2.0. 

I recompiled from the 2.0DB019 branch and that one works.

**Comment by pasin** [comment]
I was able to build and use `CouchbaseLIteSwift` from `feature/2.0` branch without issues. 

Either one of the followings works as expected:
```
./Scripts/build_framework.sh -s "CBL Swift" -p iOS -o out
./Scripts/generate_release_zip.sh -o out 
```
@jayzhanghs You shouldn't see any non CBLxxx.h in the headers.

**Comment by pasin** [comment]
DB20 will be closed this Friday and could be released early next week.

**Comment by jayzhanghs** [comment]
Thanks, I'll try your scripts next time. DB20 will be compiled in Xcode 9.1, right?

**Comment by pasin** [comment]
Yes, it will be compiled in XCode 9.1.

**Comment by pasin** [comment]
> Also the CBLSwift 2.0 framework distributed by Couch is a Fat library containing both simulator and device slices. Could you add a strip-framework shell script which we can add to our build phase to remove the simulator slices when we submit our code to App Store?

I have a ticket created for this: https://github.com/couchbase/couchbase-lite-ios/issues/1610.
