### ISSUE TITLE
2.0: When database is closed, the replicator and live query should be stopped.

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#1958]
When a database is closed, the replicator and live query should be stopped.

**Comment by borrrden** [comment]
Just for clarification:  If a DB is closed, its change event will no longer be fired and nothing will happen for that live query after that point.  Does there still need to be something explicit happening here?  Could I also free the native objects at this point for .NET?

**Comment by pasin** [comment]
I think you can free the object because to reopen the database, a new database object should be created.

**Comment by jayzhanghs** [comment]
Is this the cause of failure to delete database which I see pretty often in my case?  We sometimes need to delete the database for a fresh re-sync.

**Comment by snej** [comment]
Probably.

**Comment by pasin** [comment]
This feature has been implemented and merged into the feature/2.0 branch. We could close the issue now.
