### ISSUE TITLE
1.4.1 - Simple view on nested documents returning nothing

### ISSUE THREAD

**Issue by carrotalan** [couchbase/couchbase-lite-ios#1959]
Hi There,

I am attempting to use a simple view on data which includes nested JSON objects, for example:
```json
{
   "_id": "01C1A5C0-9DE1-11E7-9097-DBBEEF5F2781",
   "_rev": "3-6c7b876387f33ce1bd7fbf2b46f24661",
   "data": {
       "type": "collection",
       "name": "TEST",
       "collectionType": "customer",
       "meta": {
           "creator": "customer",
           "widdopId": "",
           "username": "test",
           "tagline": "",
           "banner": false,
           "bannerImage": null
       },
       "credentials": [
       ],
       "customer": "I0028",
       "dateCreated": 1505897538,
       "lastUpdated": 1506011941,
       "products": [
           "1234",
           "5678"
       ],
       "productsLength": 2,
       "promotionProductsLength": 0,
       "notes": null
   }
}
```

However after running this view, it seems to return nothing.

I have tried to find examples of accessing nested data in a view but cannot find any mention of it whatsoever in the guides, other issues or anywhere on the web!

Can Couchbase Lite work with nested documents? Or am I being an idiot...

Here is the view:
``` objc
CBLView* collectionsByType = [database viewNamed: @"collections/collectionsByType"];

    [collectionsByType setMapBlock: MAPBLOCK({
        if ([doc[@"type"] isEqual: @"collection"]) {
            emit(doc[@"data"][@"collectionType"], doc[@"id"]);
        }
    }) version: @"2"];
```

Thanks in advance,
--------
* Version:   1.4.1
* Client OS: iOS 10.3.1

**Comment by pasin** [comment]
From the map function, the `type` of the document is checked in if clause, but in the sample JSON object, there is no `type`. Can you confirm if the sample JSON is correct?

**Comment by pasin** [comment]
Second, to emit document id, the should be `doc[@"_id"]`.

**Comment by carrotalan** [comment]
Thanks for the reply @pasin I have updated the example with the real document contents.

I can change the ID emitting, but would that stop the nested path from showing?

**Comment by carrotalan** [comment]
I have updated the view function to:

```objc
    [collectionsByType setMapBlock: MAPBLOCK({
        if ([doc[@"data"][@"type"] isEqual: @"collection"]) {
            emit(doc[@"data"][@"collectionType"], doc[@"_id"]);
        }
    }) version: @"3"];
```

Reindexing data now, will let you know how it goes!

**Comment by carrotalan** [comment]
This worked perfectly!

Apologies, its getting late here in the UK 😮 

At least this can be used as a reference for anybody else in the future needing to use nested data in views.

**Comment by pasin** [comment]
Glad to hear that. Close the issue now.
