### ISSUE TITLE
iOS Swift: Crash issue

### ISSUE THREAD

**Issue by parvezq** [couchbase/couchbase-lite-ios#1961]
For a swift based ios application, I am getting a crash (attached screenshot). Their is no change in Couchbase lite ios source code as I am using the framework itself. The scenario to reproduce this crash is a single pull replication (continuous) that is being used on main thread and pointing to the same database. No other queue is being used for this database. The replication is being stopped and re-started again with a different sync gateway url. Their are basically two sync gateway urls to which pull replication is associated. This is basically a toggling behaviour of sync switch as initiated from UI. In short based on one condition, the pull replication uses one url and use another based on another url. The code to setup pull replication is as below:

`if pullReplication == nil {
                pullReplication = database?.createPullReplication(serverURL)
                pullReplication?.continuous = true
            }
            pullReplication?.customProperties = ["websocket":true]
            let basicAuthenticator = CBLAuthenticator.basicAuthenticator(withName: "username", password: "password")
            self.pullReplication?.authenticator = basicAuthenticator
            self.pullReplication?.start()`

The code to re-start the pull replication is as below:

`     pullReplication?.stop()
        pullReplication = nil        
        //start database replication with new sync url
        //the above code snippet is used to setup pull replication`

I have enabled "Sync Verbose" logging and below is outputted in xcode console.

`CBLWebSocketChangeTracker[0x1c41dac70 <bucket name>]: Connection error #1, retrying in 2.0 sec: PSWebSocketError[3, "Output stream end encountered"]
*** ASSERTION FAILED: !_docReader
*** Assertion failure in -[CBLBulkDownloader startedPart:](), /Users/jenkins/jenkins/workspace/couchbase-lite-ios-builds@2/couchbase-lite-ios-enterprise/Source/CBLBulkDownloader.m:153`

What is causing this crash? What the *** ASSERTION FAILED: !_docReader means?

![crash](https://user-images.githubusercontent.com/1989434/33078763-b2f975fe-cef9-11e7-9635-3f6107dacd2f.png)

--------
* Version:   Couchbase version: 1.3.1 (build 6)
* Client OS: iOS 11
* Server:    Couchbase Sync Gateway/1.4.1

**Comment by pasin** [comment]
This issue is fixed in CBL 1.4.1. Please update CBL to 1.4.1.

**Comment by parvezq** [comment]
Thanks for the updates. What are the differences in features between version 1.3.1 and 1.4.1 besides the above mentioned issue fix?

**Comment by pasin** [comment]
It contains several bug fixes and performance improvement. Please see the change log [here](https://github.com/couchbase/couchbase-lite-ios/releases/tag/1.4.1).
