### ISSUE TITLE
我擦嘞，怎么查看同步进度啊 大哥？

### ISSUE THREAD

**Issue by wokenshin** [couchbase/couchbase-lite-ios#1964]
你好，大哥。
我想知道 如何查看 数据库同步的进度。
--------
* Version:   VERSION
* Client OS: NAME_AND_VERSION
* Server:    NAME_AND_VERSION

**Comment by wokenshin** [comment]
iOS  CouchBaseLite2.0

**Comment by pasin** [comment]
What is the issue? Please create the issue in english.

**Comment by wokenshin** [comment]
Hi， I wana know， How to view the progress of database synchronization
