### ISSUE TITLE
How to view the progress of synchronizing data

### ISSUE THREAD

**Issue by wokenshin** [couchbase/couchbase-lite-ios#1965]
Hello, I used couchbase-lite when I was developing the iOS program. I want to be able to see the progress of data synchronization when synchronizing data. At the same time, I want to know if the data is successfully synchronized to the server. The client does not output prompt information. I didn't see the response interface, either.
--------

**Comment by pasin** [comment]
@wokenshin are you using CBL 2.0, right? You can add a change listener to the replicator to receive the replicator status changes. See the code [here](https://github.com/couchbaselabs/mobile-training-todo/blob/feature/2.0/swift/Todo/AppDelegate.swift#L132-L175) as an example.

**Comment by wokenshin** [comment]
Yes！thank you very much！
