### ISSUE TITLE
Framework TOO large to use

### ISSUE THREAD

**Issue by zyy71104233** [couchbase/couchbase-lite-ios#1968]
thanks for publishing this excellent nosql project firstly.
but I have some suggestions，first is that，the framework is too large to integrate into our app（binary size of couchbase-lite is about 38M），whether can trim the binary  size？or provide a simple bin？ e.g. remove no essential module，like data sync module and so on，just leave a nosql feature on iOS device. 
 still thank for your hard-working

--------
* Version:   VERSION
* Client OS: NAME_AND_VERSION
* Server:    NAME_AND_VERSION

**Comment by pasin** [comment]
The framework file is a FAT framework which contains the binaries for both Simulator and Device architecture. Also the binary file contains a lot of meta data information which shouldn't be included into the application file (should be less than 1M impact to the application file).

**Comment by snej** [comment]
Static libraries are not binaries; they're the output of the compiler and contain tons of metadata for the linker to use. The size of a static library is nothing like the size of the final code once it's linked into the app.
