### ISSUE TITLE
2.0: Possible lacking coverage of Fleece serialization

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-ios#1969]
See https://github.com/couchbase/couchbase-lite-net/issues/932 for .NET version of this issue, but the issue lies with the platform object serialization.  There likely is not an issue present, but since this is a pretty low level part please ensure a test is present for round tripping to Fleece if it is not already.  The .NET test is [here](https://github.com/couchbase/couchbase-lite-net/blob/feature/api-v2/src/Couchbase.Lite.Tests.Shared/CSharpTest.cs#L355)

**Comment by pasin** [comment]
The value encoding for ObjC is done at the Fleece level. There are already some intensive objective-C value encoding tests in [here](https://github.com/couchbaselabs/fleece/blob/693fa709fb18f60caebf6d910515ef387f63b431/Tests/ObjCTests.mm). I'm closing this issue.
