### ISSUE TITLE
Couchbase Lite 2.0 Swift LiteCore saveDocument() EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by jayzhanghs** [couchbase/couchbase-lite-ios#1974]
I have a loop to save several hundred documents in a way like 

            do {
                try myDB.save(syncDoc)
            } catch {
                ERROR_MSG("record db changes \(error)")
            }
Most of the time it's working fine. But sometimes it throws errors like 

Error Domain=LiteCore Code=25 "must be called during a transaction" UserInfo={NSLocalizedDescription=must be called during a transaction}

Then subsequently crash due to EXC_BAD_ACCESS.

I saw an Android developer posted a similar problem on stackoverflow too but no answers there:

https://stackoverflow.com/questions/47266192/exception-when-saving-document-to-db

Please let me know what does the error mean and how should I avoid the crash here.

--------
* Version:  2.0DB019
* Client OS: iOS 11.1
* Server:   Sync Server 1.5

**Comment by jayzhanghs** [comment]
Besides this error "must be called during a transaction" , which may be "fixed" by deleting the database and start the whole thing anew, the EXC_BAD_ACCESS error happens very often, even if `myDB` is initialized in the same method (and on the same thread) when I'm running in loops to save hundreds of documents a time, and in many batches. I tried using `inBatch` like this but it's not helpful:

            do {
                try myDB.inBatch {
                    try myDB.save(syncDoc)
                }
            } catch {
                ERROR_MSG("record db changes \(error)")
            }

**Comment by jayzhanghs** [comment]
Also saw a lot of warnings and errors like:

    CouchbaseLite  WARNING: SQLite error (code 21): bind on a busy prepared statement: [SELECT sequence, flags, 0, version, body FROM kv_default WHERE key=?]
    CouchbaseLite  WARNING: SQLite error (code 21): misuse at line 81269 of [1a584e4999]

**Comment by jayzhanghs** [comment]
Upgraded to CBL 2.0DB020, saw an new error when saveDocument():

    CouchbaseLiteSwift was compiled with optimization - stepping may behave oddly; variables may not be available.

**Comment by jayzhanghs** [comment]
With DB20 I was able to see the crash trace beyond my code and it looks like the EXC_BAD_ACCESS happens pretty often in Encoder::addItem(Value v) function call in Encoder.cc. 

<img width="944" alt="screen shot 2017-12-08 at 8 56 33 pm" src="https://user-images.githubusercontent.com/18294900/33791497-692360de-dc5a-11e7-9b25-5d220a747bd6.png">

<img width="441" alt="screen shot 2017-12-08 at 8 56 46 pm" src="https://user-images.githubusercontent.com/18294900/33791498-6db3b932-dc5a-11e7-9b59-6385e264b0e7.png">

**Comment by pasin** [comment]
@jayzhanghs do you share database object across threads? As of DB 20, the database object is not thread safe.

**Comment by jayzhanghs** [comment]
I saw you have an open issue about making it thread safe. Will that be in DB21? 

In the meantime, should I always create a new Database object in each thread with `Database(name: "...")` call?

**Comment by pasin** [comment]
The database thread safe is scheduled for DB21.

In the meantime, should I always create a new Database object in each thread with Database(name: "...") call?

> Yes so each thread has its own database object.

Also please see my second comment, I also experienced this crash even if I created a new database object in the same thread.

> I will need to try to reproduce the issue and see what is going on.

**Comment by rajagp** [comment]
@jayzhanghs With DB21 out which includes DB thread safety support, can you check if this issue is fixed for you.

**Comment by pasin** [comment]
CC: @raghusarangapani and @sridevi-15 I would be great if we could add a function test for this.

**Comment by pasin** [comment]
@jayzhanghs I have added a unit test to save 1000 docs with and without inBatch: method. I ran it multiple time and I was not able to reproduce the issue. Could you please try with the latest DB or the latest build from the feature/2.0 branch? Thanks.
