### ISSUE TITLE
CBL 1.4.x Support for error code 429 - too many requests

### ISSUE THREAD

**Issue by brendand** [couchbase/couchbase-lite-ios#1975]
The IBM Cloud / Cloudant platform has instigated a restriction on the number of requests that can be sent to their servers within each second. Currently their Lite plan supports up to 10 requests per second.  Couchbase Lite appears to be be going over that or not handling the error response code.

IBM Cloud will return a `429 - too many requests` error when this happens.

It's preventing my app from syncing to IBM Cloud now.

It would be great if Couchbase Lite 1.4.x could back-off for a moment in response to the 429 error.

--------
* Version:   1.4.1
* Client OS: macOS 10.13.1 and iOS 11.2
* Server:    IBM Cloud / Cloudant.

**Comment by pasin** [comment]
Does the replicator retry after getting 429?

**Comment by brendand** [comment]
There's code in CBLMisc.m in the method CBLMayBeTransientError which could be modified to support 429. Right now it checks 500, 502, 503, and 504. It retries if CBLMayBeTransientError returns YES. 

I modified it to add 429:

```
BOOL CBLMayBeTransientError( NSError* error ) {
    NSString* domain = error.domain;
    NSInteger code = error.code;
    if ($equal(domain, NSURLErrorDomain)) {
        return code == NSURLErrorTimedOut || code == NSURLErrorCannotConnectToHost
                                          || code == NSURLErrorNetworkConnectionLost;
    } else if ($equal(domain, NSPOSIXErrorDomain)) {
        return code == ENETDOWN || code == ENETUNREACH || code == ENETRESET || code == ECONNABORTED
            || code == ECONNRESET || code == ETIMEDOUT || code == ECONNREFUSED;
    } else if ($equal(domain, CBLHTTPErrorDomain)) {
        // Internal Server Error, Bad Gateway, Service Unavailable or Gateway Timeout, or Too Many Requests:
        return code == 500 || code == 502 || code == 503 || code == 504 || code == 429;
    } else {
        return NO;
    }
}
```

So far so good.

**Comment by pasin** [comment]
I added 429 to CBLMayBeTransientError  as suggestion.
