### ISSUE TITLE
Downloaded CouchbaseLiteSwift Framework 2.0DB020  not exposing the lite classes

### ISSUE THREAD

**Issue by jayzhanghs** [couchbase/couchbase-lite-ios#1977]
So in the header file CouchbaseLiteSwift.h I only see 

{code}
//
//  CouchbaseLiteSwift.h
//  CouchbaseLiteSwift
//
//  Created by Jens Alfke on 2/9/17.
//  Copyright © 2017 Couchbase. All rights reserved.
//

#import <Foundation/Foundation.h>

//! Project version number for CouchbaseLiteSwift.
FOUNDATION_EXPORT double CouchbaseLiteSwiftVersionNumber;

//! Project version string for CouchbaseLiteSwift.
FOUNDATION_EXPORT const unsigned char CouchbaseLiteSwiftVersionString[];

#import "CouchbaseLite.h"
#import "CBLArray+Swift.h"
#import "CBLDictionary+Swift.h"
{code}

and the compiler has a lot of errors like
- "Missing argument label 'withName:' in call" for `Database.delete(dbName)`
- "Argument labels '(database:, targetURL:)' do not match any available overloads" for `ReplicatorConfiguration(database:, targetURL:)`

and so on.

--------
* Version:   2.0DB020
* Client OS: ios 11

**Comment by jayzhanghs** [comment]
Or is the DB20's APIs have changed dramatically?

**Comment by borrrden** [comment]
The APIs are currently undergoing a lot of flux.  DB021 was delayed for the goal of having it be the last major API change.  It's plausible that the API has just changed from under you, since nothing else in our build process has changed that I am aware of.

**Comment by jayzhanghs** [comment]
I recompiled from source my self and the result is the same as the downloaded version. So yeah it's not because of the build process, but the API does have quite several big changes.

**Comment by jayzhanghs** [comment]
I'm closing this issue as this is more like the API signatures change from DB19 to DB20
