### ISSUE TITLE
iOS CredStore error - not persisting session cookie

### ISSUE THREAD

**Issue by djpongh** [couchbase/couchbase-lite-ios#1985]
from: https://github.com/couchbase/couchbase-lite-core/issues/326

Filing a separate ticket for 1.4.1.

We're seeing a CredStore error in the Xcode console after I set the session cookie on the replicator object

2017-12-15 13:07:19.560786-0800 CouchbaseDemo[28283:1017224] CredStore - performQuery - Error copying matching creds.  Error=-25300, query={
    class = inet;
    "m_Limit" = "m_LimitAll";
    ptcl = htps;
    "r_Attributes" = 1;
    sdmn = "Couchbase Sync Gateway";
    srvr = "subdomain.example.com";
    sync = syna;
}
followed by

2017-12-15 14:53:31.075120-0800 CouchbaseDemo[33113:1161139] <CBLHTTPLogic: 0x6000000976b0>: Auth challenge; credential = (null)
2017-12-15 14:53:31.075277-0800 CouchbaseDemo[33113:1161139] <CBLHTTPLogic: 0x6000000976b0>: HTTP auth failed; sent Authorization: (null)  ;  got WWW-Authenticate: Basic realm="Couchbase Sync Gateway"
2017-12-15 14:53:31.075728-0800 CouchbaseDemo[33113:1161139] CouchbaseLite WS WARNING: {2}--> blips:subdomain.example.com/public/_blipsync
2017-12-15 14:53:31.075954-0800 CouchbaseDemo[33113:1161139] CouchbaseLite WS WARNING: {2} Unexpected or unclean socket disconnect! (reason=WebSocket status, code=401)
This is occurring in both CBL 2.0 dev build 20 and CBL 1.4.1 using iOS 11 / Xcode 9.
The 401 - unauthorized error only occurs when guest access is disabled.
Looks like sync gateway (version 1.5) is seeing a blank user from the logs:

2017-12-15T22:53:24.905Z HTTP:  #003: GET /public/_blipsync
2017-12-15T22:53:24.905Z HTTP: #003:     --> 401 Login required  (0.8 ms)

**Comment by snej** [comment]
The initial logging starting with `CredStore - performQuery` doesn't look like anything of ours; I've never seen it before, but I suspect it's part of iOS's credential storage code, probably happening during a call to NSURLCredentialStorage or as part of NSURLSession's auth-challenge handling.

**Comment by pasin** [comment]
From a stackoverflow [post](https://stackoverflow.com/questions/46099940/credstore-perform-query-error), the CredStore error message is shown when trying to request a credential from the credential storage from an unknown URL protection space or realm. This is pretty much a false alarm error message when trying it get the a credential which is not there from the storage. 

I matched the log message above and the CredStore is shown when trying to get the current credential after getting a challenge response from the SGW (see this [line](https://github.com/couchbase/couchbase-lite-ios/blob/feature/2.0/Objective-C/Internal/Replicator/CBLHTTPLogic.m#L247)).

The question now is whether the session cookie is sent to the SGW or not. If the session cookie is sent probably assuming that the session is still valid, there shouldn't be a challenge response from SGW.

@BrandonNott Could you provide some more info?

1. Can you capture the raw HTTP requests sent from the replicator to SGW by using Wireshark, HTTPScoop, or any HTTP Sniffers? We would like to see if the session cookie is sent to SGW properly or not.

2. How do you set the session cookie to the replicator?

**Comment by BrandonNott** [comment]
@pasin - I've emailed you directly with the Xcode logs.

Unfortunately the root certificate for SSL does not play nicely with Charles Proxy, and because CBL 2.0 rolls it's own networking library I'm unable to see the traffic using 3rd party dependencies.  Because of SSL Wireshark is not helpful.  

Here are the Sync gateway logs: 

```
2017-12-15T22:53:24.905Z HTTP:  #003: GET /public/_blipsync
2017-12-15T22:53:24.905Z HTTP: #003:     --> 401 Login required  (0.8 ms)
2017-12-15T22:53:31.028Z Bucket: Update("_sync:user:", 0, ...) --> CAS quit [692.767µs]
```

**Comment by snej** [comment]
What's special about the SSL cert? If it's not generally trusted by the OS, you can remedy that by adding it in the Keychain Access utility and marking it as trusted. Or can you temporarily configure the server to accept non-SSL connections, so you can debug more easily?

FYI, CBL 2 doesn't roll its own networking library; it uses NSURLSession. It just uses WebSockets instead of HTTP.

**Comment by BrandonNott** [comment]
Pasin responded to me in an email earlier, and it was an error on my part.

In my code I was setting the session cookie like so:
```
    func setSessionCookie(sessionCookie: HTTPCookie) {
        replicator.config.authenticator = CBLSessionAuthenticator(
            sessionID: sessionCookie.value,
            expires: sessionCookie.expiresDate,
            cookieName: sessionCookie.name
        )
    }
```
Not realizing that the `config` object was actually immutable and accessing it was returning a copy.  From the CBL 2.0 source code:
```
@property (readonly, copy, nonatomic) CBLReplicatorConfiguration* config;
```

**Comment by pasin** [comment]
@BrandonNott Thanks for the update. I have also flagged the configuration API for review to further prevent this issue. I'm closing the issue now.
