### ISSUE TITLE
2.0: Couchbase Lite Swift 2.0 SQLite Error

### ISSUE THREAD

**Issue by jayzhanghs** [couchbase/couchbase-lite-ios#1986]
I saw many errors like 

    017-12-18 18:10:33.970800-0500 HandshakeHD[40292:1397316] CouchbaseLite  WARNING: SQLite error (code 21): misuse at line 81269 of [1a584e4999]
    017-12-18 18:10:33.971402-0500 HandshakeHD[40292:1397316] CouchbaseLite  WARNING: SQLite error (code 21): bind on a busy prepared statement: [SELECT sequence, flags, 0, version, body FROM kv_default WHERE key=?]

Should I be concerned about this?
--------
* Version:   DB20
* Client OS: iOS 11
* Server:    Sync Server 1.5

**Comment by snej** [comment]
What exactly is your code doing?
In particular, are you calling CBL objects from multiple threads or dispatch queues? (The API is not thread-safe yet as of DB20.)

**Comment by pasin** [comment]
I'm closing the issue now. Feel free to provide more information and reopen the issue. Thanks.

**Comment by jayzhanghs** [comment]
ok @pasin
