### ISSUE TITLE
2.0: PropertyExpression property should not be public

### ISSUE THREAD

**Issue by rajagp** [couchbase/couchbase-lite-ios#1987]
--------
* Version:   2.0
* Client OS: iOS

PropertyExpression property is expected to be internal but it is available publicly. 
From discussions w/ @Pasin : "We will need to set final to all static functions in Expression."

**Comment by rajagp** [comment]
This is tricky because all static functions are final automatically. That said, I am wondering what it really means to have a function accessible publicly via base class and not via inherited class. Is that

**Comment by borrrden** [comment]
Is this going to affect the API of other platforms?

**Comment by pasin** [comment]
I just looked into this today during Java API review. It is correct that PropertyExpression is public. It is Swift or Xcode issue that allows all static methods from Expression classes accessible from PropertyExpression.

**Comment by snej** [comment]
If Expression has a public function `property()`, it's inherited by subclasses and callable through them. That would apply whether or not it's static.

**Comment by pasin** [comment]
@snej is right. 

Note:
* Java doesn't have the same issue as java subclasses cannot see the static methods of its super classes.
* Probably need to change the implementation to return a different object / interface. I have seen @borrrden is doing this in .NET when reviewing .NET API.
