### ISSUE TITLE
set methods are not public in MutableDictionaryObject

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-ios#1993]
DB21

The following methods are not public. Confirmed with @pasin that this is an issue. Logging a ticket for tracking.
```
setString
setNumber
setInt
setInt64
setDouble
setFloat
setBoolean
setDate
setBlob
setArray
setDictionary
setData
```

**Comment by pasin** [comment]
Fixed in https://github.com/couchbase/couchbase-lite-ios/commit/c2e20e65b2018d60e551d2ca80b687292665ab74.
