### ISSUE TITLE
How to retrive data through observer in Swift4

### ISSUE THREAD

**Issue by AchillesSium** [couchbase/couchbase-lite-ios#1996]
Hello, I am new to Couchbase as well as Nosql. I can upload data on CouchBase DB and retrive them through enumerator and show them in a table view. But i want to retrive data by observer which can observe a change on DB and i can save those data immediately in my local DB from Couchbase DB. I am on Swift4 Xcode9.1. Can anyone help me please???

--------
* Version:   1.4.0
* Client OS: iOS 11
* Server:    n/a

**Comment by djpongh** [comment]
Welcome! GitHub issues are for bugs/enhancements requests to Couchbase products. For help with programming such as this, please use our forums: 
  https://forums.couchbase.com/c/mobile
you be able to get help from many members of our community.
