### ISSUE TITLE
couchbase lite 2.0 still is nosql database ?

### ISSUE THREAD

**Issue by nguoithichkhampha** [couchbase/couchbase-lite-ios#1999]
--------
* Version:   2.0
Does couchbase lite 2.0 still is nosql database ?
I see couchbase lite 2.0 only support sql lite database storage and remove forest db

**Comment by djpongh** [comment]
Couchbase Lite 2.0 is still an embedded database just like Couchbase Lite 1.0. In 2.0 we are implementing a brand new API and also adding queries and full-text search.

As of this time, we are not supporting the use of ForestDB as a data store for Couchbase Lite 2.0.

**Comment by snej** [comment]
"NoSQL" is a really vague term. Really it means "nonrelational". Couchbase Lite is a nonrelational document-oriented database that, as an implementation detail, happens to use SQLite as its underlying storage engine.
