### ISSUE TITLE
Query .toDictionary() seems to be returning CBLDictionary instead of Dictionary

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-ios#2000]
CBL 2.0 top of tree feature/2.0 branch

Query code
```
            for row in try searchQuery.execute() {
                print("row.toDictionary() is \(row.toDictionary())")
                resultArray.append(row.toDictionary())
            }
```
The above code prints
```
row.toDictionary() is ["test_db": <CBLDictionary: 0x604000104890>]
```

This used to print the actual document with DB20.

**Comment by rajagp** [comment]
@pasin  Any chance we can issue a patch for this only for iOS ? Given the nature of the issue, I don't think we should wait for a couple weeks   (CC @djpongh )

**Comment by snej** [comment]
`row` is a CBLQueryResult, not a CBLQuery. I checked the implementation of `toDictionary` and it definitely returns an NSDictionary. In your sample above it's being logged as `["test_db": <CBLDictionary: 0x604000104890>]`, i.e. it has a single key `"test_db"` whose value is a CBLDictionary.

**Comment by pasin** [comment]
There is a regression with one my commit so I fixed this issue.

**Comment by Codeido** [comment]
Same problem here.
