### ISSUE TITLE
Declare our error domain & codes in a header

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#2006]
The function `convertError` in CBLStatus.mm wraps some LiteCore errors in custom NSError domains. Those domains and their codes need to be declared in a header just like other NSError domains, otherwise developers won't know how to programmatically interpret errors returned from the CBL API.

The Obj-C code also has its own error domain `CouchbaseLite` and three codes declared in the internal header CBLStatus.h. These should be documented there too.

**Comment by rajagp** [comment]
Also it's good practice to use reverse DNS prefix for CBL errors.  From [Apple Docs](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/ErrorHandlingCocoa/ErrorObjectsDomains/ErrorObjectsDomains.html)

> You can create your own error domains and error codes for use in your own frameworks, or even in your own applications. It is recommended that the string constant for the domain be of the form com.company.framework_or_app.ErrorDomain.
