### ISSUE TITLE
Blip replication throws an error for doc with attachment while replicating to Sync-gateway

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-ios#2009]
**Environment:**
* Sg Version:   2.0.0-722
* Client OS: platform - iOS, version = latest bits of DB of Jan 4th
* Server:    5.0.0-3519

**Steps to reproduce :** 
1. Create docs in sync-gateway with attachments. 
2. Do pull or (push pull) replication to CBL.
3. Update docs in Sync-gateway -> This is option , I tried with and without
4. Update docs in CBL.
5. Do push replication (or push pull) replication to sync-gateway with continous True

**Result :** Docs that got updated in CBL did not get pushed to sync-gateway.
Throws an error in CBL with this message : 
CouchbaseLite Sync Info: CBLReplicator[<*> blip://192.168.33.11:4984/db]: error pushing 'sg_docs_3': Error Domain=LiteCore Code=35 "Incorrect proof for attachment sha1-mvCtygxdDxFXFtu01/hQttQcXSA=" UserInfo={NSLocalizedDescription=Incorrect proof for attachment sha1-mvCtygxdDxFXFtu01/hQttQcXSA=}

**Expected :** Conflict resolver should resolve the conflict and replicate to sync-gateway .

**Note :** When I tried without attachments , it works fine.
Also, when I try same scenario with no-conflicts mode , I get this error
CouchbaseLite Sync Info: CBLReplicator[*> blip://192.168.33.11:4984/db] is stopped, progress 11114/11114, error: Error Domain=LiteCore Code=35 "Document update conflict" UserInfo={NSLocalizedDescription=Document update conflict}
2018-01-09 12:09:08.858113-0800 CBLTestServer-iOS[20431:1460118] CouchbaseLite DB Info: Closing DataFile

I guess this is expected with no-conflicts mode(above error)

Here is the sample doc with attachment :  Get doc from CBL with attachment
CBL updated docs  {'sg_docs_8': {'channels': [u'no-conflicts-channel'], 'random': u'18395498-2b43-44f9-9ba5-869f105e13e8', '_attachments': {'1a637e6d-a404-4644-a0af-bea50de59397.png': {'stub': 1, 'length': 478, 'revpos': 1, 'digest': u'sha1-366X/6LayyVUbgGLHmtBI/WWxKI='}, 'c8f92e38-b0a1-47e0-bd34-e739218f9928.png': {'stub': 1, 'length': 478, 'revpos': 1, 'digest': u'sha1-q4Sl6okYV+57jmvVOSmVg8PACpY='}}, 'updates-cbl': 4, 'updates': 2}

this is the code used to generate attachments : https://github.com/couchbaselabs/mobile-testkit/blob/feature/cbl20-replication/keywords/attachment.py#L22

**Comment by pasin** [comment]
I have tested this manually with the above 5 steps and I couldn't reproduce the issue with the latest build. During the past week, @snej have fixed some issues related to attachments. I could be possible that this issue was fixed as well. 

@sridevi-15 could you please rerun the test with the latest CI build or the latest code from the feature/2.0 branch? If the issue still exists, we can reopen the issue.

**Comment by sridevi-15** [comment]
works fine on DB22
