### ISSUE TITLE
2.0: Not throwing an error for attachment when replication fails

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-ios#2010]
**Environment**
Sg Version: 2.0.0-722
Client OS: platform - iOS, version = latest bits of DB of Jan 4th
Server: 5.0.0-3519

**Steps to reproduce :**

1. Create docs in sync-gateway with attachments.
2. Do pull or (push pull) replication to CBL.
3. Update docs in Sync-gateway -> This is option , I tried with and without
4. Update docs in CBL.
5. Do push replication (or push pull) replication to sync-gateway.
6. Get changes while doing replication and also get error using the replicator library

**Result :** Error shows nil in changes and Replicator.status.error shows nil 
Error is thrown in CBL logs with error : 
CouchbaseLite Sync Info: CBLReplicator[<*> blip://192.168.33.11:4984/db]: error pushing 'sg_docs_3': Error Domain=LiteCore Code=35 "Incorrect proof for attachment sha1-mvCtygxdDxFXFtu01/hQttQcXSA=" UserInfo={NSLocalizedDescription=Incorrect proof for attachment sha1-mvCtygxdDxFXFtu01/hQttQcXSA=}

**Expected :** While getting changes during replication, it should catch errors in changes and show up in changes and Replicator.status.error with Code
 
this is the code used to generate attachments : https://github.com/couchbaselabs/mobile-testkit/blob/feature/cbl20-replication/keywords/attachment.py#L22

**Comment by sridevi-15** [comment]
I do not see error for below use case too in no-conflicts mode

 1. Create docs in SG.
        2. Pull replication to CBL
        3. update docs in SG and  CBL.
        4. Pull replication to CBLs
        5. Verify docs can resolve conflicts and
        should able to replicate docs to CBL
        6. Update docs in CBL
        7. Do "push_pull " replication with continous True 

Result : It throws an error in CBL with 409  which is expected, but I do not see error in changes. It show the error in changes. 

_CouchbaseLite Sync Info: CBLReplicator[<*> blip://192.168.33.11:4984/db]: error pushing 'sg_docs_0': Error Domain=WebSocket Code=409 "rejected by proposeChanges" UserInfo={NSLocalizedDescription=rejected by proposeChanges}
2018-01-10 00:01:34.011254-0800 CBLTestServer-iOS[43291:2191328]_ 

Note : I am getting changes during whole replication time. I got all changes before connection started and till replication is idle for sometime, but the error shows 'nil'
CBL logs shows 409

**Comment by snej** [comment]
Two bugs here:

1. Error `"Incorrect proof for attachment sha1-mvCtygxdDxFXFtu01/hQttQcXSA="`
2. Error isn't reported to the app by LiteCore

**Comment by pasin** [comment]
Per my comment in https://github.com/couchbase/couchbase-lite-ios/issues/2009, please re-run the test with the latest code from the feature/2.0 branch. If the issue still exists, we can reopen the issue. Thanks!
