### ISSUE TITLE
Database encryption crashes on doSync method in iOS

### ISSUE THREAD

**Issue by Yuvraj-Sorav** [couchbase/couchbase-lite-ios#2012]
I am using couchbase lite 1.4.1. I am trying to implement database encryption in iOS and successfully done with the integration part as described in the documentation.

But when i am using database doSync method, it crash. It shows the error on line number:162 in CBLDatabase.m file.If i comment this database doSync method in my code, it works fine.

Also,I have cross check by removing database encryption, everything works well like before.

Ex: - Suppose I have a function A():

1. function A() {
2.   //get your database reference/Instance here
3.  [database doSync: ^ {
4.    //your code stuff
5.   }];
6.  }
when i run the function A, it will give a crash on line number:3.
Thanks in Advance

**Comment by pasin** [comment]
Could you provide the crash log that include the exception message?

**Comment by Yuvraj-Sorav** [comment]
It gives no logs but shows a bad excess error.The only thing i get is class name and method in it.
The caller and callee of the function gives me a stack of called classes.
Ex:- function A() {
       methodABC()
}
function ABC() {
    [database doSync: { 
             //your code stuff
      }]
}

What i am getting is functionA-> methodABC()->function ABC()->bad excess on database doSync.

**Comment by snej** [comment]
We need at least a backtrace. If you're hitting the crash in Xcode, enter "bt" at the "(lldb)" prompt in the debugger console, and it will print a backtrace of the current thread.

**Comment by djpongh** [comment]
@Yuvraj-Sorav, any chance on that backtrace?

**Comment by djpongh** [comment]
If you can get a backtrace, feel free to re-open.
