### ISSUE TITLE
Enhancement: 2.x. Separate isNull and isMissing Query options

### ISSUE THREAD

**Issue by rajagp** [couchbase/couchbase-lite-ios#2018]
This applies to all platforms. 
--------
* Version:   1.0

From https://github.com/couchbase/couchbase-lite-ios/issues/1982

Split isNullorMissing to isNull and isExisting to be consistent with how server behaves

**Comment by pasin** [comment]
Track this in https://github.com/couchbaselabs/couchbase-lite-apiv2/issues/193.
