### ISSUE TITLE
“isOldAttachment” check is incorrect

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#2022]
I just saw this change in commit 6cc6e94:
```obj-c
    // Check whether the dictionary is the old attachment or not:
    static bool isOldAttachment(Dict properties, DocContext *context) {
        auto sk = context->sharedKeys();
        if (properties.get(C4STR("digest"), sk) != nullptr &&
            properties.get(C4STR("length"), sk) != nullptr &&
            properties.get(C4STR("stub"), sk) != nullptr &&
            properties.get(C4STR("revpos"), sk) != nullptr &&
            properties.get(C4STR("content_type"), sk) != nullptr)
            return true;
        return false;
    }
```
This isn't going to work correctly.

1. An attachment isn't required to have a `content_type` property; the developer may not have set one.
2. Attachments only appear inside the top-level `_attachments` property. An object elsewhere in the document, with the above properties, isn't an attachment. It seems unlikely that this would happen, but maybe if someone were archiving old or conflicting versions of a doc inside a nested property?

The second point might be nit-picky, and it looks like it would complicate the calling code to have to know where in the document the `properties` Dict is, so maybe we can ignore it. But I wanted to point it out.

**Comment by pasin** [comment]
Thanks @snej for pointing this out. CC: @hideki and @borrrden.

**Comment by pasin** [comment]
I did the fix for the first point. I will leave the issue open to think about the second point.
