### ISSUE TITLE
2.0: Exposure of metadata - including _rev

### ISSUE THREAD

**Issue by BrandonNott** [couchbase/couchbase-lite-ios#2023]
We want to expose metadata - `_rev` in particular - for documents using couchbase lite 2.0.

This will enable us to assemble a changes block for particular documents describing the changes necessary (according to RFC 6902 JSON Patch notation) to get back to the previous revisions.  Each array of JSON Patch operations is key'd under the previous document revision id and serves as a proof that the changes block overall hasn't been tampered with.

--------
* Version:   CBL 2.0 DB 21
* Client OS: iOS 11 / macOS Sierra
* Server:    Couchbase Server 5.0.1 / Sync Gateway 1.5.1

**Comment by snej** [comment]
The revID isn't necessary for this: a document history is linear, and you can refer to any ancestor revision by how many generations back it is. So you can keep the history as an array where the first element has the patch for the parent, the second has the patch for the grandparent, etc.

BTW, JSON Patch is _extremely_ verbose, and for small documents or extensive changes the patch can be bigger than the target doc itself. [JSON-Delta](https://json-delta.readthedocs.io/en/latest/) is a better format IMO.

**Comment by djpongh** [comment]
@BrandonNott, can you provide us more info on why this is needed?

**Comment by djpongh** [comment]
If Jens' solution doesn't work for you, feel free to reopen and provide more detail of what you are trying to do.
