### ISSUE TITLE
2.0 Replicator stops when CBL goes offline

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-ios#2028]
Tested in TODO app.
1. login as user.
2. Create tasks and sub tasks
3. Change the settings to have network in airplane mode.

Result : Replicator stops in iOS
--------
* Version:   VERSION
* Client OS: NAME_AND_VERSION
* Server:    NAME_AND_VERSION

**Comment by snej** [comment]
Please file more detailed bug reports.

Continuous or one-shot replication?
Push, pull or both?
Whey you say "stops", what exactly do you mean?
