### ISSUE TITLE
2.0 How to get all documents with a document id prefix efficiently / fast

### ISSUE THREAD

**Issue by skela** [couchbase/couchbase-lite-ios#2031]
All our documents have ids along the lines of `acc.projects.3|xyzasdsadasdasd`, I use the following to get all documents with a document prefix of `acc.projects.3|` in Couchbase Lite 1.4.1:

	let groupID = "acc.projects.3"
	guard let q = database?.createAllDocumentsQuery() else { return nil }
	q.startKey = groupID + "|"
	q.endKey = groupID + "}" // '}' is the character after '|' in ASCII order
	q.inclusiveEnd = false
	q.prefetch = true

	do
	{
		let rows = try q.run()
	}
	catch let error
	{
	    log.error("Failed to query table \(table.groupId) - \(error)")
	}

So with the approach of Couchbase Lite version 2.0, I was wondering what is the fastest, most efficient solution to achieve the same thing?

Note: We don't have a "type" field in our documents, so were never able to use that to help us.

**Comment by snej** [comment]
in pseudo-code, "meta.id >= groupID+'|' and meta.id < groupID+'}'"

(Please ask questions on the forum or mailing list, not in the form of issues.)
