### ISSUE TITLE
2.0: iOS App crashes with Release build of couchbase-lite-ios

### ISSUE THREAD

**Issue by rajagp** [couchbase/couchbase-lite-ios#2032]
--------
* Version:   DB022
* Client OS: iOS

**Steps** 
- Link the latest release build of the couchbase-lite-ios framework to any iOS app . the Todo mobile training sample app is an example
- Open DB using `openDatabase`
- Build and run the app. Crash observed through`CouchbaseLiteSwift.Database.setLogLevel()`

**Output**
- [Traces](https://gist.github.com/rajagp/1c93874a80e7d6cf089d27adcd9e5c82)

**Comment by snej** [comment]
CBL is trying to set the level of an internal LiteCore log domain that happens not to exist in a release build (it gets dead-stripped by the linker.) I'm cleaning up logging right now...
