### ISSUE TITLE
Cross Join Not Returning expected results

### ISSUE THREAD

**Issue by rajagp** [couchbase/couchbase-lite-ios#2035]
--------
* Version:   Latest feature/2.0 build of iOS
* Client OS: iOS

**Version**: Latest feature/2.0 branch of Couchbase Lite iOS. Haven't tried on other platforms. 

**Test Data:** [Here](https://gist.github.com/rajagp/7e1ef3b69063fb62fc80e7e66071c85f)

**JOIN Query :** 
Trying to do a cross join between documents of type "employee" and type "department" 

Please insert the test query into `QuertTest.m` of Couchbase_Lite_ios
```
- (void) testCrossJoin {
    [self loadJSONResource:@"join"];
    CBLQueryExpression* FIRSTNAME  = [CBLQueryExpression property: @"firstname" from:@"employeeDS"];
    CBLQueryExpression* LASTNAME  = [CBLQueryExpression property: @"lastname" from:@"employeeDS"];
    CBLQueryExpression* DEPTNAME  = [CBLQueryExpression property: @"name" from:@"departmentDS"];
    
    NSArray* results = @[[CBLQuerySelectResult expression: FIRSTNAME],
                         [CBLQuerySelectResult expression: LASTNAME],
                         [CBLQuerySelectResult expression: DEPTNAME]];
    
    
    [CBLQuerySelectResult expression: [CBLQueryMeta idFrom: @"employeeDS"]];
    
  
    CBLQueryJoin* join = [CBLQueryJoin crossJoin:[CBLQueryDataSource database: self.db as: @"departmentDS"]];
    CBLQuery* q = [CBLQuery select: results
                              from: [CBLQueryDataSource database: self.db as: @"employeeDS"]
                              join: @[join]];
    Assert(q);
    NSError* error;
   
    
    CBLQueryResultSet* rs = [q execute: &error];
 
    NSUInteger i = 0;
    NSArray* res = [rs allResults];
    for (CBLQueryResult* r in res) {
        NSLog(@" %@",[r toDictionary]);
       
        i++;
    }
    
}
```

**Compiled Query:**
```
 SELECT fl_result(fl_value("employeeDS".body, 'firstname')), fl_result(fl_value("employeeDS".body, 'lastname')), fl_result(fl_value("departmentDS".body, 'name')) FROM kv_default AS "employeeDS" CROSS JOIN kv_default AS "departmentDS" ON ("departmentDS".flags & 1) = 0 WHERE ("employeeDS".flags & 1) = 0
```
**Observed Results:**
Quite random. Does not produce a cross join results. Getting empty rows etc

Examples
```
\\This is not matched with any entry in the "department" document
2018-01-20 18:58:06.094554-0500 xctest[7564:2477971]  {
    firstname = Chas;
    lastname = Cefalu;
}
```

```` 
\\Empty :
2018-01-20 18:58:06.138359-0500 xctest[7564:2477971]  {
}
```

**Comment by rajagp** [comment]
Some more details and I think that this may not be an issue after all
- The JSON data also included documents with "type" of "location" that also include the property "code" which was messing up the results

So I updated the select query above to include `where` to specify exactly the documents to join
```
- (void) testCrossJoin {
    [self loadJSONResource:@"join"];
    CBLQueryExpression* FIRSTNAME  = [CBLQueryExpression property: @"firstname" from:@"employeeDS"];
    CBLQueryExpression* LASTNAME  = [CBLQueryExpression property: @"lastname" from:@"employeeDS"];
    CBLQueryExpression* DEPTNAME  = [CBLQueryExpression property: @"name" from:@"departmentDS"];
    
    NSArray* results = @[[CBLQuerySelectResult expression: FIRSTNAME],
                         [CBLQuerySelectResult expression: LASTNAME],
                         [CBLQuerySelectResult expression: DEPTNAME]];
    
    
    [CBLQuerySelectResult expression: [CBLQueryMeta idFrom: @"employeeDS"]];
    
  
    CBLQueryExpression* expr1 = [[CBLQueryExpression property:@"type" from:@"employeeDS"]  equalTo: [CBLQueryExpression string:@"employee"]];
    CBLQueryExpression* expr2 = [[CBLQueryExpression property:@"type" from:@"departmentDS"] equalTo :[CBLQueryExpression string:@"department"]];
    
    CBLQueryJoin* join = [CBLQueryJoin crossJoin:[CBLQueryDataSource database: self.db as: @"departmentDS"]];
    CBLQuery* q = [CBLQuery select: results
                               from: [CBLQueryDataSource database: self.db as: @"employeeDS"]
                              join: @[join]
                             where:[expr1 andExpression:expr2]];
                   
    
    Assert(q);
    NSError* error;
   
    NSLog(@"%@",[q explain:nil]);
    
    CBLQueryResultSet* rs = [q execute: &error];
 
    NSUInteger i = 0;
    NSArray* res = [rs allResults];
    for (CBLQueryResult* r in res) {
        NSLog(@" %@",[r toDictionary]);
       
        i++;
    }
    
}
```

I think this is the way it should be. But any one else have any comments / thoughts? If you agree, I will close the issue.

**Comment by rajagp** [comment]
> Getting empty rows doesn't seem to be correct. With the cross-joins, should it be like N x N results?

I don't get empty if I filter using the `where` clause but I _do_ get empty rows if I don't. It is odd because it should just be a NxM set, You should be able to repro this with the test data and unit test specified above just in case I am overlooking something...latest branch.

**Comment by rajagp** [comment]
Not a JOIN expert but Rethinking this issue, doing a cross join across more than 2 documents without a where clause is probably a misuse of the JOIN feature and we should expect to see weird results. So I am inclined to say that this is a non-issue. If we used a where clause to scope the join to <=2 document types, we are good.

**Comment by snej** [comment]
Priya: I tried the (updated) test method in the latest CBL and LiteCore, and it passes. Does that mean the bug doesn't exist anymore? Or am I misunderstanding? (I'm even less of a Join expert than you are!)

**Comment by rajagp** [comment]
Yes-I would say that we can close this. I was attempting to cross join across more than 2 documents and I  haven't come across instances where that's deemed fine.

**Comment by snej** [comment]
OK, I will close this then.
