### ISSUE TITLE
Release date of 2.0.0 final?

### ISSUE THREAD

**Issue by carrotalan** [couchbase/couchbase-lite-ios#2036]
Apologies if this is already here and I have missed it. If not, this will be a easy way for users to find this information...

I can see some great working going on in the 2.0.0 branch.

We would like to start planning to use version 2 in our production systems and was wondering when the projected release date is of the final version of 2.0.0, where there will be no breaking changes to the API and any absent features/regressions are known.

At the time of writing, the latest release is 2.0 Developer Build 21.

**Comment by djpongh** [comment]
2.0 GA is currently scheduled for February 28.

**Comment by snej** [comment]
Sorry you're frustrated. The release is very close. Please ask questions on the Couchbase forums; we use Github for bug reports & feature requests only.
