### ISSUE TITLE
Peer to Peer sync on iOS 11 returns changes count always 0

### ISSUE THREAD

**Issue by ajaykoppisetty** [couchbase/couchbase-lite-ios#2037]
We are trying to sync between device to device(using bonour) using CouchbaseLiteListener. On iOS 10 everything works perfectly fine but on iOS 11 the sync is not happening. 

In one of the articles, we found out that from iOS 11 apple is not supporting bluetooth peer to peer connections. Does this effect the sync in couchbase lite?

Also with added logging we are seeing an error as below

```
CredStore - performQuery - Error copying matching creds.  Error=-25300, query={
    class = inet;
    "m_Limit" = "m_LimitAll";
    ptcl = htps;
    "r_Attributes" = 1;
    srvr = "DMQKFDXGF185.local";
    sync = syna;
}
```
We also tried `listener.setAnonymousSSLIdentityWithLabel` but no luck :(

--------
* Version:   iOS
* Client OS: 1.4.1

**Comment by snej** [comment]
If Bonjour doesn't work over Bluetooth, then you'd need to find some other way to handle discovery. :( Does IP-over-Bluetooth still work? If so, then once you discover a device, you can get an IP address for it and construct a replication URL from that.

**Comment by rajagp** [comment]
FYI . Some relevant reads : 
"Peer-to-peer Bluetooth is not supported on iOS 11 and friends."
1. https://lists.apple.com/archives/bonjour-dev/2017/Sep/msg00005.html
2. https://forums.developer.apple.com/thread/88104

**Comment by djpongh** [comment]
Change in iOS functionality
