### ISSUE TITLE
DB22 : Delete database is failing

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-ios#2038]
Environment : 
1. couchbase-lite-iOS : build 560 -> DB 22 
2. sync-gateway version : 2.0.0-759

Steps to reproduce : 
1. Configure database 
2. Create database in CBL with name.
3. Create docs in CBL
4. Delete database with api database.delete()

Result : 
1. database is not getting deleted.
2. Reason  "database is busy/locked"

Expected : 
1. It should delete the database 

Note : Tried closing the database and delete. CBL is throwing an error that database should have it opened

**Comment by pasin** [comment]
@sridevi-15 The following code works to me:

```
    CBLMutableDocument* doc = [[CBLMutableDocument alloc] init];
    [doc setValue: @"foo" forKey: @"bar"];
    Assert([self.db saveDocument: doc error:nil]);
    Assert([self.db delete: nil]);
    AssertNil(self.db.path);
```

**Comment by pasin** [comment]
> Note : Tried closing the database and delete. CBL is throwing an error that database should have it opened

I checked the implementation and currently it behaves correctly that an error is thrown.

**Comment by sridevi-15** [comment]
I clean up the the database at teardown , so need to delete database for every tests, otherwise following tests fails, that is why it is functional test blocker

**Comment by snej** [comment]
@sridevi-15, we can't reproduce this; all of our unit tests successfully close and delete the database when they finish. You'll have to show us the exact code you're using. Also, this may be a bug in your test framework (the RPC stuff.)

**Comment by sridevi-15** [comment]
After updating database API with builder, it worked fine now. closing the ticket
