### ISSUE TITLE
Replicator error for invalid json did not give doc information

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-ios#2044]
### steps to reproduce : 
1. Create docs in SG.
        2. Start replication with  Pull replication to CBL with continous True
        3. update docs in SG and CBL concurrently.
        4. Do Push_pull replication .
        5. Verify docs got replicated.
        6. Update docs  in CBL.
         7. Wait until replicator is idle.
      
###Result : 
1. Got an error while replication is going through with invalid json. Looks like one of the doc is invalid json, but the error which CBL give did not give enough  information which doc has that error 

###Expected  : 
1. The error should provide the json to look into the doc and correct , otherwise it is hard to find out which doc has that error and which doc to correct if there are bunch of docs

###  CBL Logs : 
https://gist.github.com/sridevi-15/0f9cbcc4ea9875c0b4de6864404625b2

### Test code : 
https://github.com/couchbaselabs/mobile-testkit/blob/feature/cbl20-ver1/testsuites/CBLTester/CBL_Functional_tests/test_no_conflicts_cbl.py#L953

**Comment by pasin** [comment]
Can you check SGW log to check the error as well? It's a response from the SGW about that error.

**Comment by pasin** [comment]
@sridevi-15 I suspected that the error is from saving remote checkpoint as the document shouldn't have invalid JSON. Can you check from the SGW log to see if you can determine that?

**Comment by snej** [comment]
This error should never occur; we should never generate invalid JSON regardless of what's stored in a document. This is probably the same issue as couchbase/couchbase-lite-core#373.

**Comment by sridevi-15** [comment]
Latest build of DB22 has this issue : https://github.com/couchbase/sync_gateway/issues/3249. I will  rerun the test once 3249 is fixed

**Comment by sridevi-15** [comment]
I tested today with latest build of iOS i.e 576 and i do not see this error anymore. so, closing this ticket now.
