### ISSUE TITLE
'Connection reset by peer' error in CBL logs

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-ios#2045]
### Steps to reproduce : 
1. Create docs in SG.
2. Pull replication to CBL with continous 'True'

### Result : 
1 . I see 'connection reset by Peer' error atleast 3 times and it stops showing this error, but eventually replication happens

### Expected : 
It should not display this error as sync gateway is up and running

### CBL logs : 
https://gist.github.com/sridevi-15/a3402ff18c4837ff5e365471d5bdf463

### Test code 
https://github.com/couchbaselabs/mobile-testkit/blob/feature/cbl20-ver1/testsuites/CBLTester/CBL_Functional_tests/test_no_conflicts_cbl.py#L953

**Comment by pasin** [comment]
@sridevi-15 Any errors on SGW log when that happens?

**Comment by snej** [comment]
@sridevi-15 "Connection reset by peer" means that SG abruptly closed the socket without sending a WebSocket close message. That probably means a panic or crash on SG. So it would be best to file issues like this against SG.

**Comment by sridevi-15** [comment]
Confirmed that it is issue with SGW.
