### ISSUE TITLE
2.0 : ObjC version of OrderBy Query resulting in compile errors while swift version compiles

### ISSUE THREAD

**Issue by rajagp** [couchbase/couchbase-lite-ios#2050]
--------
* Version:   2.0 (feature /2.0-dev)
* Client OS: iOS

This version of OrderBy query fails to compile in ObjC but seems to be working in swift
**ObjC:**
States that there is no matching select:from:join:orderBy query
<img width="1081" alt="screen shot 2018-01-26 at 9 36 10 pm" src="https://user-images.githubusercontent.com/645251/35468260-7148d014-02e8-11e8-8201-9002947ff19a.png">

**Swift: ** 
Equivalent query compiles just fine

<img width="693" alt="screen shot 2018-01-26 at 10 30 44 pm" src="https://user-images.githubusercontent.com/645251/35468272-9ef9c7ac-02e8-11e8-92f9-ec8c3c301509.png">

What am I missing?

**Comment by pasin** [comment]
OrderBy parameter type is an array. Put the ordering object in @[] would solve the compilation issue.
