### ISSUE TITLE
Replication of design documents fails from CouchDB to Couchbase Lite

### ISSUE THREAD

**Issue by alexmcarthur** [couchbase/couchbase-lite-ios#206]
Hi

We have encountered an issue where design documents fail to replicate from CouchDB (1.4.0 tested) to Couchbase Lite.

The cause for the failure is that the design document id is escaped in CBLEscapeID.

The proposed workaround is to replace "_design%2F" with "_design/" post escaping.

See pull request: #205

Cheers
Alex M

**Comment by opicciotto** [comment]
I would like to add a comment here, using %2F in urls could lead to a security issue  see : http://security.stackexchange.com/questions/40185/what-are-the-consequences-of-turning-on-apache-allowencodedslashes

This means that if we want to setup a replication through a reverse proxy we will have to  turn on Apache AllowEncodedSlashes, that is strongly discouraged ...

Could the replicator not escape the / to %2F in design documents ?

For example, I see in the PullerInternal.java for Android the fowllowing line 

StringBuilder path = new StringBuilder("/" + URLEncoder.encode(rev.getDocId()) + "?rev=" + URLEncoder.encode(rev.getRevId()) + "&revs=true&attachments=true");

The DocId is always urlencoded including the '/'...

I think this will solve some security concerns in Enterprises.

**Comment by snej** [comment]
It's not just about design documents. `/` is a legal character in document IDs, and has to be encoded as `%2F` in a URL to avoid being interpreted as a path separator. (Being able to use the literal unencoded `/` when accessing a design document is a special-case hack to simplify using the REST API.)

My reading of that StackExchange article is that it's a security issue for an app-server to mishandle slashes in path components, i.e. assuming a path component in a URL can be used directly as a filename that won't have a path in it. It's not a security issue for Apache.

**Comment by opicciotto** [comment]
Yes you are right, I Agree,  but some enterprises are blocking this at the reverse proxy level. And we you discuss with the security guys they just tell you "this is how it is and there is no way we will change that in our security policy". You guys,  find an other solution if you want to run your apps in my enterprise...

**Comment by snej** [comment]
Actually I should jump up a level and ask why you're replicating design documents into Couchbase Lite/iOS? Apple's going to reject your iOS app for doing that, since it constitutes downloading and running executable code (i.e. JavaScript map/reduce functions.)

**Comment by opicciotto** [comment]
Yes, good  question : ) .  Enterprise mobile apps are usually not deployed to public stores so this apple validation process is not required , Also, the target is more android in our case .. 

Syncing views is a very interesting feature about CouchBase lite and CouchBase server  it enables to maintain in one place valuable business logic and this is a killer functionality compared to SQL databases... Our customers like it  a lot ...
