### ISSUE TITLE
Swift 2.0: LiteCore error trying to copy prebuilt DB

### ISSUE THREAD

**Issue by jayzhanghs** [couchbase/couchbase-lite-ios#2061]
I'm using this code snippet from Couchbase Document at https://developer.couchbase.com/documentation/mobile/2.0/couchbase-lite/swift.html#database

{code}
let assetPath = Bundle.main.path(forResource: "travel-sample", ofType: "cblite2")!
if !Database.exists(withName: "travel-sample") {
do {
try Database.copy(fromPath: assetPath, toDatabase: "travel-sample", withConfig: nil)
} catch {
fatalError("Could not load pre-built database")
}
}
{code}

It jumped to Fatal error with LiteCore error code 12 "no such file or directory"

--------
* Version:   Swift 2.0 DB21
* Client OS: iOS 11
* Server:    NAME_AND_VERSION

**Comment by snej** [comment]
Have you verified that a database exists at `assetPath`? Because if not, the error is correct.

**Comment by jayzhanghs** [comment]
It's in the Resources folder, as shown here, otherwise it would crash at the first line in trying to unwrap the assetPath (the ! sign)

![img_0236](https://user-images.githubusercontent.com/18294900/35936368-0f78b7c8-0c11-11e8-8c80-c068a6a0499d.PNG)

**Comment by jayzhanghs** [comment]
It's in the Resources folder, as shown here, otherwise it would crash at the first line in trying to unwrap the assetPath (the ! sign)

![img_0237](https://user-images.githubusercontent.com/18294900/35936430-3ffcd816-0c11-11e8-9bd3-0532ffdea5d7.PNG)

**Comment by snej** [comment]
@pasin: `+[CBLDatabase copyFromPath:...]` calls `c4db_copy` without first ensuring that the parent directory of `toPath` exists. If it doesn't, LiteCore will return a file-not-found error instead of creating the database directory.

The method does call `setupDatabaseDirectory`, but only after the copy request; at that point it's a no-op. It needs to call it beforehand, and it should pass the parent of `toPath`.

**Comment by snej** [comment]
@jayzhanghs, you should be able to work around this by creating another database first; that will cause the parent directory to be created. You can then delete it. Or alternatively, look up the `directory` property of the `DatabaseConfiguration` and create that directory yourself.

**Comment by pasin** [comment]
I fixed the bug in `feature/2.0-dev branch`.

**Comment by jayzhanghs** [comment]
Thanks @pasin and @snej for the quick turn around in investigation and the fix!
