### ISSUE TITLE
Validate Sec-WebSocket-Protocol header in server response

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#2063]
If CBL 2 tries to sync with SG 1.5, it will fail because the versions of BLIP are incompatible. But the resulting errors are pretty arcane, like "invalid checksum" or "invalid BLIP message number". Since this is a fairly easy mistake to make, we should do better version-checking.

The problem is that our version-checking happens on the server side: SG 2 checks that the client sent a Sec-WebSocket-Protocol header containing the value "BLIP_3a2". But SG 1.5 doesn't include that check, nor do SG 2 builds earlier than about DB 20. So we should also add a check to CBL (because that's where our WebSocket implementations live; there's one in LiteCore too but it's only used for the `cblite` tool.)

The specific check for CBL is: If a `Sec-WebSocket-Protocol` request header was sent (because the the replicator `kC4SocketOptionWSProtocols` option is set), then the HTTP response must also contain a `Sec-WebSocket-Protocol` header. Otherwise the socket should be closed immediately and the client should return a C4Error {WebSocket, 1002} to LiteCore.

**Comment by snej** [comment]
It turns out that LiteCore can detect this on its own, since the client WS implementation sends it the HTTP headers. So I've added a small check for this; the CBL implementations won't have to do anything.

**Comment by djpongh** [comment]
@snej ,so we can close this or is this still open to improve the per platform error messages?
