### ISSUE TITLE
Unable to get any results from a multi-key query

### ISSUE THREAD

**Issue by skela** [couchbase/couchbase-lite-ios#2064]
Struggling to get any kind of results from views with multiple keys.
I've got 2 different view's here, 1 multi key view, and 1 composite key view. 
I also have an all docs query with an id prefix filter just as a baseline.
Not getting anywhere with the multi key query.

View named "list.items_in_folder_multi_key"
```
let map : CBLMapBlock = {doc,emit in
            
            guard let docId = doc["_id"] as? String else { return }
            guard docId.hasPrefix("files.system.") else { return }
            
            let gid = CBUtils.groupIdFromDocumentId(docId)
            let aid = CBUtils.accountIdFromGroupdId(gid)
            
            guard let folder = doc["folder"] as? String else { return }
            
            emit([aid,folder], nil) // aid : Int, folder : String
        }
```

In interest of completeness, here's my other view where I've got a single combined key:

View named "list.items_in_folder"
```
let map : CBLMapBlock = {doc,emit in
            
            guard let docId = doc["_id"] as? String else { return }
            guard docId.hasPrefix("files.system.") else { return }
            
            let gid = CBUtils.groupIdFromDocumentId(docId)
            let aid = CBUtils.accountIdFromGroupdId(gid)
            
            guard let folder = doc["folder"] as? String else { return }
            
            let key = "\(aid):\(folder)"
            emit(key, nil)
        }
```

I get results only for my single key view "list.items_in_folder", getting nothing for the "list.items_in_folder_multi_key" view.

Here's me doing the queries using a single key view, a multi key view and the all docs query with an id prefix query:

```
queryView(named:"list.items_in_folder",configure:{query in
    query.mapOnly = true
    query.keys = ["117:/data/2046 ebrd level 2/content"]
})

queryView(named:"list.items_in_folder_multi_key",configure:{query in
    query.mapOnly = true
    query.keys = [[117],["/data/2046 ebrd level 2/content"]]
})

queryTable(named:"files.system.117.1eHjrdArxIkaD6tzW45E",key:"/data/2046 ebrd level 2/content")
```

I get the following results:
```
Queried view 'list.items_in_folder', got 16 rows, took: 7.450544 ms
Queried view 'list.items_in_folder_multi_key', got 0 rows, took: 0.939741 ms
Queried table 'files.system.117.1eHjrdArxIkaD6tzW45E', got 16 rows, took: 22.891379 ms
```

The multi key query simply isn't working. Can I get some guidance as to what I'm not doing? I've been told I'm supposed to use an array of arrays when querying the multi key view, i've tried without any luck. 

--------
* Version:   d373b4e9f69df5db592e1d8c2808afbada52c386

**Comment by snej** [comment]
The query should look like
```
queryView(named:"list.items_in_folder_multi_key",configure:{query in
    query.mapOnly = true
    query.keys = [[117, "/data/2046 ebrd level 2/content"]]
})
```

**Comment by skela** [comment]
Thanks so much! I could have sworn I tried that before and it didnt work. I've got a somewhat related question regarding this. When you use views with multiple keys, do you have to query using all the keys then? Or can you do a query with a subset of the keys. In my example, that would mean getting all items in all folders for account 117. Or do you recommend having multiple views. One that only has the account id, and another that has both account id and folder keys.

**Comment by skela** [comment]
So in situations where I want to query the view, but I am only interested in matching on one of the keys.
I've tried everything I can think of, but getting no results.


```
queryView(named:"list.items_in_folder_multi_key",configure:{query in
    query.mapOnly = true
    query.keys = [[117, ""]]
})
```

```
queryView(named:"list.items_in_folder_multi_key",configure:{query in
    query.mapOnly = true
    query.keys = [[117, NSNull()]]
})
```

```
queryView(named:"list.items_in_folder_multi_key",configure:{query in
    query.mapOnly = true
    query.keys = [[117]]
})
```

Even tried this, which is according to your documentation what I should be using here:

```
queryView(named:"list.items_in_folder_multi_key",configure:{query in
    query.mapOnly = true
    query.keys = [[117,[:]]]
})
```

**Comment by snej** [comment]
I think you've got an incorrect mental model of what array keys do. Have you read the view documentation? (If you're familiar with SQL or relational databases, it's very much like creating an index with a primary and secondary key.)

**Comment by skela** [comment]
@snej I'm only asking because in the documentation you specify that u can use the "special JSON null object", but you don't really ever say what that is or how to use it?

**Comment by skela** [comment]
@snej sorry, I'm not that familiar with SQL, I'm just trying to do a query on a view that has keys of the form [accountId , folder], and I was trying to avoid having 3 different views, for the situation where I only want to do a lookup based on using just the accountId key, the folder key or both keys.

**Comment by snej** [comment]
Yeah, you can't do that. Array keys are like using primary/secondary keys in an index. So in your case, you can get all the rows with a specific (or range of) accountID, or a specific accountID plus a range of folder IDs, but you cannot query just for folder IDs. It's kind of the same reason that in a dictionary you can easily find all the words that start with A, but not all the words that have A as the second letter -- they're just not sorted in a way that makes that work.

**Comment by snej** [comment]
Anyway, the answer is that you do need three views. (Just like in a SQL database you would need three indexes.)
