### ISSUE TITLE
2.0: Obj-C -> Swift Exceptions

### ISSUE THREAD

**Issue by mtrossbach** [couchbase/couchbase-lite-ios#2066]
Hi,

the Swift version of Couchbase Mobile Library is essentially a Swift wrapper for the Obj-C version. But there is no functionality to catch Obj-C exceptions.

Example: When you try to save an invalid document to the database an exception is caused by the Obj-C implementation of the Database class. But on the Swift side we cannot catch this exception although the Swift API of Database is marked with a "throws". As a result the app crashes.

So I think there should be some kind of wrapper for these exception to the "Swift world", too.

> Although Swift error handling resembles exception handling in Objective-C, it is entirely separate functionality. If an Objective-C method throws an exception during runtime, Swift triggers a runtime error. There is no way to recover from Objective-C exceptions directly in Swift. Any exception handling behavior must be implemented in Objective-C code used by Swift.

https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/AdoptingCocoaDesignPatterns.html#//apple_ref/doc/uid/TP40014216-CH7-ID10

--------
* Version:   2.0 Beta 1
* Client OS: iOS 11
* Server:    Couchbase Server 5.0.1

**Comment by snej** [comment]
>When you try to save an invalid document to the database an exception is caused by the Obj-C implementation of the Database class

That's an assertion failure, which is considered a fatal error. It should not be caught & handled; instead you should fix your code. (Or if you don't believe it's your mistake, please post details of what you did, and what the backtrace of the crash is, so we can reopen & investigate.)

Exceptions in Objective-C are not for 'normal' behavior like error handling. They are nearly always treated as fatal conditions. (And as you've seen, they are not related to Swift errors even though similar words like 'try' and 'throw' are used.)
