### ISSUE TITLE
What error should be returned when delete or purge a newly created document

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#2075]
Based on the comment in https://github.com/couchbase/couchbase-lite-ios/pull/2068, the error might be changed from `CBLErrorInvalidParameter` to `CBLErrorNotFound`.

**Comment by pasin** [comment]
@borrrden What is your thought on this?

**Comment by borrrden** [comment]
All else being equal, not found seems more appropriate

**Comment by pasin** [comment]
OK, I will change the error to not found.
