### ISSUE TITLE
Error on remote server error on 625 build

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-ios#2076]
### Steps to reproduce : 
 1. Create docs in CBL DB1, DB2 , DB3 associated with each channel.
        2. Replicate docs from CBL DB1 to DB2 with push pull and continous.
        3. Wait until replicatio is done.
        4. Repliate docs from CBL DB1 to DB3.
        5. Wait until replication is done with push pull and continous.
        6. update docs on CBL DB1, DB2, DB3.
        7. Now update docs concurrently on all 3 CBL DBs.
        8. Wait until replication is done.'''

### Expected : 
1. REplication should complete

### Result : 
Fails at step 8
Error while replicating', 'Optional(Error Domain=CouchbaseLite Code=35 "error on remote server"

I see this error too in CBL logs . : 2018-02-26 12:01:29.225961-0800 CBLTestServer-iOS[9414:432703] CouchbaseLite Sync Info: CBLReplicator[<*> DB[cbl_db31519675224.94]]: error pushing 'no-conflicts2_76': Error Domain=CouchbaseLite Code=10409 "(unknown WebSocket status)" UserInfo={NSLocalizedDescription=(unknown WebSocket status)}.
 

https://github.com/couchbaselabs/mobile-testkit/blob/feature/cbl20-ver1/testsuites/CBLTester/CBL_Functional_tests/test_no_conflicts_cbl.py#L556

test_sg_CBL_updates_concurrently

**Comment by snej** [comment]
"Error Domain=CouchbaseLite Code=10409" is an NSError translation of LiteCore error C4Error{WebSocketDomain, 409} -- WebSocket/HTTP error codes get offset by 10000 when mapping them to NSErrors so they don't overlap with the LiteCore error codes.

But CBLReplicator is expecting a conflict to be {LiteCoreDomain, kC4ErrorConflict} ... what changed?

**Comment by snej** [comment]
Please post a link to the CBL logs.

**Comment by snej** [comment]
I think the source of this is SG rejecting the pushed document since it would cause a conflict. Pusher.cc:276:
```c++
auto err = c4error_make(WebSocketDomain, status, "rejected by proposeChanges"_sl);
```
CBLReplicator doesn't have any code to handle this so it treats it as a generic doc error.

**Comment by snej** [comment]
SG might also return code 403 (forbidden).

**Comment by snej** [comment]
I can remap this in LiteCore, but we probably need a new error code for this -- kC4ErrorConflict is already used for _incoming_ conflicts, which have a different meaning. Maybe kC4ErrorRemoteConflict?

**Comment by pasin** [comment]
I think `kC4ErrorRemoteConflict` makes sense.

**Comment by pasin** [comment]
@sridevi-15 Can you retest with the new build (647) with the latest SGW build to confirm the behavior?

**Comment by sridevi-15** [comment]
I tested on 647 and I do not see this issue anymore, so closing this ticket
