### ISSUE TITLE
BasicAuthenticator is not accessible on latest ios build 

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-ios#2081]
--------
* Version:   662
* Client OS: iOS 

Steps to reproduce : 
1. Got the latest iOS build 662 and complaining that Basic Authenticator is not accessible 

Error message : 'BasicAuthenticator' initializer is inaccessible due to 'internal' protection level

**Comment by pasin** [comment]
This issue will be fixed in the next build. @sridevi-15, please verify and close the issue.

**Comment by pasin** [comment]
Please test with http://latestbuilds.service.couchbase.com/builds/latestbuilds/couchbase-lite-ios/2.0.0/664.

**Comment by sridevi-15** [comment]
Verified on build 664 and works fine now.
