### ISSUE TITLE
isEqual and hashValue methods of blob is not available on latest iOS builds

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-ios#2082]
--------
* Version:   662
* Client OS: iOS 

1. Got latest build of iOS 662 on xcode
Complaining that hashValue  and isEqual not available

**Comment by pasin** [comment]
This issue will be fixed in the next build. @sridevi-15, please verify and close the issue.

When comparing Blob in Swift, please use '==' instead of isEquals: as isEquals: is the Objective-C API and we don't expose that in Swift anymore.

**Comment by pasin** [comment]
Please test with http://latestbuilds.service.couchbase.com/builds/latestbuilds/couchbase-lite-ios/2.0.0/664.

**Comment by sridevi-15** [comment]
verified on latest build, 664 . it works fine
