### ISSUE TITLE
EXC_BAD_ACCESS (code=1, address=0x1010087) on build 664

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-ios#2083]
--------
* Version:   664
* Client OS: iOS 

### Steps to reproduce 
1. Configure the replication 
2 target = URLEndpoint(url: URL(string: target_url!)!) 
3. if (target == nil)   
is throwing 
EXC_BAD_ACCESS.

It works fine with build 647

**Comment by snej** [comment]
With any crash, please attach a crash log or backtrace. If you're running the iOS app in Xcode, enter `bt` at the debugger console to log a backtrace.

**Comment by snej** [comment]
`EXC_BAD_ACCESS` is a crash -- commonly called a seg-fault or bus-error. Xcode is now paused in the debugger at the point of the crash -- that's what the "`(lldb)`" prompt is.

Type `bt` and press Return. LLDB will log a backtrace. Copy that and paste it here.

**Comment by sridevi-15** [comment]
* thread #13, queue = 'com.apple.root.default-qos', stop reason = EXC_BAD_ACCESS (code=1, address=0x1010087)
    frame #0: 0x000000010e15bc57 libobjc.A.dylib`objc_retain + 7
    frame #1: 0x000000010d7747b5 CouchbaseLiteSwift`initializeBufferWithCopyOfBuffer value witness for CouchbaseLiteSwift.URLEndpoint at Endpoint.swift:0
  * frame #2: 0x000000010d3e9d55 CBLTestServer-iOS`ReplicatorConfigurationRequestHandler.handleRequest(method="replicatorConfiguration_configure", args=0x000060400003b400, self=0x0000600000221020) at ReplicatorConfigurationRequestHandler.swift:86
    frame #3: 0x000000010d3f7f0f CBLTestServer-iOS`closure #1 in Server.init(request=0x000060400015a8e0, self=0x00006080001723c0) at Server.swift:134
    frame #4: 0x000000010d3fbcbc CBLTestServer-iOS`partial apply for closure #1 in Server.init() at Server.swift:0
    frame #5: 0x000000010d3fbd5e CBLTestServer-iOS`thunk for @callee_owned (@owned GCDWebServerRequest) -> (@owned GCDWebServerResponse?) at Server.swift:0
    frame #6: 0x000000010d336fcf CBLTestServer-iOS`__79-[GCDWebServer((null)=0x0000000112a5d170, request=0x000060400015a8e0, completionBlock=0x000000010d322110) addDefaultHandlerForMethod:requestClass:processBlock:]_block_invoke at GCDWebServer.m:874
    frame #7: 0x000000010d3291ac CBLTestServer-iOS`-[GCDWebServerConnection(self=0x00006040000c42f0, _cmd="processRequest:completion:", request=0x000060400015a8e0, completion=0x000000010d322110) processRequest:completion:] at GCDWebServerConnection.m:786
    frame #8: 0x000000010d3220e6 CBLTestServer-iOS`-[GCDWebServerConnection _startProcessingRequest](self=0x00006040000c42f0, _cmd="_startProcessingRequest") at GCDWebServerConnection.m:143
    frame #9: 0x000000010d3231a0 CBLTestServer-iOS`-[GCDWebServerConnection _readBodyWithLength:initialData:](self=0x00006040000c42f0, _cmd="_readBodyWithLength:initialData:", length=0, initialData=198 bytes) at GCDWebServerConnection.m:253
    frame #10: 0x000000010d324668 CBLTestServer-iOS`__45-[GCDWebServerConnection _readRequestHeaders]_block_invoke((null)=<unavailable>, extraData=198 bytes) at GCDWebServerConnection.m:345
    frame #11: 0x000000010d325c85 CBLTestServer-iOS`__64-[GCDWebServerConnection((null)=<unavailable>, success=YES) readHeaders:withCompletionBlock:]_block_invoke at GCDWebServerConnection.m:472
    frame #12: 0x000000010d3254a1 CBLTestServer-iOS`__68-[GCDWebServerConnection((null)=<unavailable>, buffer=0x0000604000260a40, error=0) readData:withLength:completionBlock:]_block_invoke at GCDWebServerConnection.m:440
    frame #13: 0x0000000112992995 libdispatch.dylib`__dispatch_read_block_invoke_2.53 + 39
    frame #14: 0x000000011296e2f7 libdispatch.dylib`_dispatch_call_block_and_release + 12
    frame #15: 0x000000011296f33d libdispatch.dylib`_dispatch_client_callout + 8
    frame #16: 0x000000011297b3a2 libdispatch.dylib`_dispatch_root_queue_drain + 1444
    frame #17: 0x000000011297ada0 libdispatch.dylib`_dispatch_worker_thread3 + 132
    frame #18: 0x0000000112e3a1ca libsystem_pthread.dylib`_pthread_wqthread + 1387
    frame #19: 0x0000000112e39c4d libsystem_pthread.dylib`start_wqthread + 13

**Comment by pasin** [comment]
I was able to reproduce the issue and fixed. Not sure why the issue just showed up as the implementation has been there for quite sometime.

**Comment by pasin** [comment]
Please use build 655 to test. Thanks!

**Comment by sridevi-15** [comment]
Tested on 665 build , this bug is fixed on 665
