### ISSUE TITLE
Possible API enhancement for Document and Result

### ISSUE THREAD

**Issue by WarWithinMe** [couchbase/couchbase-lite-ios#2088]
`Document` class and `Result` class should adopt a common protocol just like [couchbase-lite-net](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/API/Document/Document.cs#L40))

So that we don't need to write two methods (with identical implementation) to process these two types.

--------
* Version:   2.0DB22
* Client OS: Mac
* Server:   -

**Comment by pasin** [comment]
Thanks for the feedback. Initially the Dictionary (and Array) interface are used privately to ensure that Document, Dictionary, and Result are consistent, but on some platforms including .NET and Objective-C cannot make the interfaces private. We could consider make them public for all platforms.

**Comment by djpongh** [comment]
Moved to: https://issues.couchbase.com/browse/CBL-277
