### ISSUE TITLE
Testserver crashes for sytem testing during replication of 1m docs to SG 

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-ios#2091]
I'm running system test on iOS emulator using Xcode. I'm adding 1M docs in batch (10000 docs in 100 iterations). Testserver app crashes after a while during replication (after replicating around 410953 docs).

Test invocation command:
pytest -rsx -s --mode=cc --server-version=5.5.0-1992 --sync-gateway-version=2.0.0-814 --liteserv-platform=ios --liteserv-version=2.0.0-670 --liteserv-host=localhost --liteserv-port=8080 --xattrs --create-db-per-suite="suite_db" --create-db-per-test="test_db" --timeout=21600 --skip-provisioning -k test_system testsuites/CBLTester/System_Test/test_system_testing.py

--------
* Version:   2.0.0-670
* Client OS: RHEL 7
* Server:    CBS 5.5-1992

- CBL Logs from Xcode -  
[CBL_system_testing_ios.zip](https://github.com/couchbase/couchbase-lite-ios/files/1784088/CBL_system_testing_ios.zip)

Also, I'm attaching the screenshot of error - 
<img width="1440" alt="screenshot 2018-03-06 13 05 39" src="https://user-images.githubusercontent.com/18100038/37021562-0338f4f6-2146-11e8-9b8e-9626f85d272e.png">

- Python test client logs - 
[python_system_testing_ios.log](https://github.com/couchbase/couchbase-lite-ios/files/1784187/python_system_testing_ios.log)

**Comment by pasin** [comment]
@hrajput89 Can you provide the following information?

1. Backtrace of all threads (type 'bt -all' from the console)
2. The link to the Swift source code. It will be easier for me to copy the code and run locally instead of setting up the test environment.

**Comment by borrrden** [comment]
FYI The test environment is set up on mobile mac mini if you want to make use of it.

**Comment by pasin** [comment]
I have been running 1M replication in the following scenarios with my own test app, but I couldn't reproduce the crash:

Push 1M Docs
1. Using push replicator.
2. Using push-and-pull replicator.
3. Using push-and-pull replicator + creating 1M docs at the same time.

Pull 1M Docs
1. Using pull replicator.
2. Using push-and-pull replicator.

From the screenshot above, I saw `Thread 250`.  I'm wondering what caused that many threads. Anyway, please provide information as I requested in my comment 2 days ago. When re-testing the issue, please use build 678 (beta 2) or latest to test.

**Comment by ritamcouchbase** [comment]
Hemant running with latest build.

**Comment by hrajput89** [comment]
System test for iOS with 1M doc ran successfully. Hence closing the ticket

**Comment by pasin** [comment]
Thanks for the update.
