### ISSUE TITLE
Log level incorrectly indicated in the log

### ISSUE THREAD

**Issue by zygoat** [couchbase/couchbase-lite-ios#2096]
It appears that prior to emitting its first log message, CBL makes the following announcement to console, regardless of the configured logging level: 

```
2018-03-08 11:28:25.899577-0800 Shoebox[93187:20540237] CouchbaseLite default log level is Verbose and above 
```
It asserts a "Verbose" log level, even if configured for something else. For example, if I call `CouchbaseLiteSwift.Database.setLogLevel(.warning, domain: .all)` first thing in my `application(didFinishLaunchingWithOptions:)` delegate method, it promptly logs the same message. 

Despite this, the actual logging output suggests the level was correctly set.

--------
* Version:  2.0DB021 and 2.0DB022
* Client OS: iOS 11.2
* Server: n/a (currently SG 1.5)

**Comment by pasin** [comment]
The log message actually means the default log level before a developer customizes the log level via the Database.setLogLevel(level, domain:) function. But the default log level to 'verbose' is not correct.

**Comment by zygoat** [comment]
It seems irrelevant and nonsensical to log what the default level is when the current level is (and hasn't been) the default, especially when the message is a direct result of setting the level to something else.

**Comment by pasin** [comment]
I changed the log message. Hope it help.
