### ISSUE TITLE
CBL 2.0 for Swift: get attachments as blob

### ISSUE THREAD

**Issue by jayzhanghs** [couchbase/couchbase-lite-ios#2099]
In CBL android version, there is a method `getBlob()` on Database that fetches attachments like `getBlob("_attachements.something")`. On Swift side however I don't find this method on `Database`. There is a `blob(forKey:)` method on Document class, but when I tried it on "_attachments" or "_attachments.something", both returned nil. `value(forKey:)` on the same document returns both as DictionaryObject.

So my question is, how to get attachments sync'ed down from server side other than getting it from sync gateway as it suggested in this doc: https://developer.couchbase.com/documentation/mobile/2.0/couchbase-lite/swift.html

Thanks

--------
* Version:   DB21
* Client OS: iOS 11
* Server:    SG 1.5

**Comment by rajagp** [comment]
How did you create the attachment on the server side ?
Also, please post questions on our Developer Forums .  Github is for bugs and feature requests. If we identify an issue, we will open a ticket here.

**Comment by jayzhanghs** [comment]
We created the attachments via Sync Gateway Admin API

I opened a topic in the developer forum if you want to close this issue here: https://forums.couchbase.com/t/cbl-2-0-for-swift-get-attachments-as-blob/16157

**Comment by snej** [comment]
Please don't file issues to ask questions; use the forum instead.
