### ISSUE TITLE
How can I embed documents in documents? 

### ISSUE THREAD

**Issue by krema** [couchbase/couchbase-lite-ios#2101]
Hi, 
I have question about data modeling and the API of Couchbase Mobile 2.0.

I am not sure how I can achieve embedding documents as described [here](https://developer.couchbase.com/documentation/server/current/data-modeling/modeling-relationships.html ) (Embedding "1" in "many" side) with the current available API.

I expected some API like this:

    let studentDocument = ...
    let students = classDocument.array(forKey: "students")
    students.appendDocument(studentDocument)

The only way I could find was referencing documents but not embed them.
Is there a way to embed documents with the current API otherwise it would be nice to have an API method for that?

Thanks

--------
* Version:   2.0
* Client OS: iOS 11.2
* Server:    n/a

**Comment by djpongh** [comment]
@krema, thanks for your interest in Couchabse Lite!  Please use Github issues for bugs/feature requests only. Questions such as above are better suited for the forums: https://forums.couchbase.com/c/mobile/couchbase-lite

**Comment by snej** [comment]
You can embed dictionaries in documents to do what you want.

Documents are the top-level entities in a database, so they are by definition not nested.
