### ISSUE TITLE
Sync for specified period of time

### ISSUE THREAD

**Issue by sivamani1818** [couchbase/couchbase-lite-ios#2107]
I will be having Last document Sequence number(Using Rest Api).
After that PULL Replication(sync) should happen only for mentioned period  of time(Example: 1 week of data should be synced).How this should done in Router ? Can You please guide .

--------
* Version:  1.4.1
* Client OS: iOS

**Comment by pasin** [comment]
@sivamani1818 You will need to use sync function via some channel structure for this, which also depend on the period of time requirement. Could you please ask this question in the [forum](https://forums.couchbase.com/c/mobile/sync-gateway)?
