### ISSUE TITLE
GCDWebServerConnection crashes in simulator when build the app with configuration 'Release'

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-ios#2108]
### Environment
* Version:   tested on iOS 2.0.0-724
* Client OS: iOS
* sg-version : 2.0.0-823

### Steps to reproduce : 
1. Move couchbaselite.swift.framework of version which you want to test to  framework folder.

2.  Go to edit scheme, and change Run configuration to 'Release' 
3. Build the app 
4. Run the test which can do calls to CBL library like create database, create docs, start replication to sync-gateway and replicate all docs with continuous true, update docs and get activity level status 

### Result : 
App gets crashed.
It get crashed randomly to one of the steps above, it is not consistent at one step. Sometime test goes through successfully without failure, but most of the time app getting crashed.

### Note : Tried on ios device (iphone 5c ios 10.3.3) and did not see this issue.
Tried on simulator with iphone 5s with 10.3.1 and able to reproduce the issue.
Looks like the issue is on simulator.
Also when I change the configuration to 'Debug' on xcode and build the app, it looks fine and do not see this issue.

Pasin was able to reproduce once with cblite code without using TestServer app and able to see this issue with configuration 'Release'

### bracktrace : 
https://gist.github.com/sridevi-15/5885c6bf06ec9d5765003c3019e9906b

**Comment by snej** [comment]
The crash is in the QE test server code, not in CBL or LiteCore. GCDWebServerConnection's dealloc method is releasing a bogus Obj-C reference, probably an already-dealloced object. Using Xcode's 'Zombies' diagnostic mode will help track this down: in the scheme editor's Diagnostics tab, check "Zombie Objects".

```
* thread #12, queue = 'com.apple.root.default-qos', stop reason = EXC_BAD_ACCESS (code=1, address=0x20)
    frame #0: 0x00000001016d9ccb libobjc.A.dylib`objc_release + 11
  * frame #1: 0x000000010091dd3b CBLTestServer-iOS`-[GCDWebServerConnection .cxx_destruct](self=0x00006000000c85e0, _cmd=<unavailable>) at GCDWebServerConnection.m:77 [opt]
    frame #2: 0x00000001016c4912 libobjc.A.dylib`object_cxxDestructFromClass(objc_object*, objc_class*) + 127
    frame #3: 0x00000001016d01a4 libobjc.A.dylib`objc_destructInstance + 124
    frame #4: 0x00000001016d01db libobjc.A.dylib`object_dispose + 22
    frame #5: 0x000000010091dcb0 CBLTestServer-iOS`-[GCDWebServerConnection dealloc](self=0x00006000000c85e0, _cmd=<unavailable>) at GCDWebServerConnection.m:421 [opt]
```

**Comment by sridevi-15** [comment]
@snej,  just wondering why this is not happening on Debug mode or on device with Release mode. Anyways, i ran with 'zombie objects' enabled and see this back trace
 
https://gist.github.com/sridevi-15/1482d42d2b7f524995e84df86e2c6e1d

**Comment by sridevi-15** [comment]
now it says it failed at Databa.inbatch in this backtrace
https://gist.github.com/sridevi-15/077671410c1c1af7a5bd21f8e4d85871

**Comment by pasin** [comment]
This could be related to https://github.com/couchbase/couchbase-lite-ios/issues/2109.

**Comment by sridevi-15** [comment]
https://gist.github.com/sridevi-15/4aca580f2efd3da8a87b462304500485

**Comment by djpongh** [comment]
I'm thinking this is the same root cause as: https://github.com/couchbase/couchbase-lite-ios/issues/2109

If I'm wrong, please re-open.
