### ISSUE TITLE
CBL is not giving proper status of Reachability.

### ISSUE THREAD

**Issue by Tamil-Arya** [couchbase/couchbase-lite-ios#2120]
My scenario is, If any changes in server end we will pull as download component those status not giving proper way some times if internet available also reachability status is offline. In that scenario i quit the app and reopen its working. How to handle it, any suggestions ?  

* Version:   CBL 1.4
* Client OS: iOS 9
* Server:    CouchDB

**Comment by pasin** [comment]
Could you please describe more in detail when that situation happens or how to reproduce the issue? If you could reproduce the issue, could you enable Sync and SyncVerbose logging and share the log?

**Comment by djpongh** [comment]
Haven't heard back. If you get more info, feel free to re-open.
