### ISSUE TITLE
CBL Swift 2.0 Beta 2 is not compatible with XCode 9.3

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#2126]
Error:
```
Module compiled with Swift 4.0.3 cannot be imported in Swift 4.1
```
As expected, the current CBL Swift Beta 2 binary cannot be use with XCode 9.3. We need to upgrade the build machine to use XCode 9.3 and update the Swift version to 3.3.

**Comment by pasin** [comment]
Jira ticket created: https://issues.couchbase.com/browse/MB-28990

**Comment by rajagp** [comment]
The lack of ABI compatibility support in swift is a nightmare for anyone trying to directly use the binaries  . Hope a resolution is announced at WWDC this year .

**Comment by winklerp** [comment]
CBL 1.4.1 is also not compatible with Xcode 9.3. At least it cannot be compiled and some errors in source code are showing up.

**Comment by djpongh** [comment]
Fixed in RC3
