### ISSUE TITLE
couchdb1 cannot replicate to couchdb2 & couchdb3

### ISSUE THREAD

**Issue by azcrusher** [couchbase/couchbase-lite-ios#2129]
--------
* Version:   couchdb-1.6.1 
* Client OS: CentOS release 6.9 (Final) : couchdb-1.6.1 
* Server:    CentOS release 6.9 (Final) :  couchdb-1.6.1 

Hi all,

i have a some problem, please help for fix the problem.

i cannot replication from couchdb1 cannot replicate to couchdb2 & couchdb3,

i use script for replication, by python:
https://pastebin.com/4NpAeVRR

my error is, when running script is:
https://pastebin.com/skUeBF9p

database, from couchdb1 (master):

[root@couchdb1 couchdb]# curl  http://admin:*****@localhost:5984/_all_dbs
["_replicator","_users","testing1","testing7"]

and this is error log couchdb:
https://pastebin.com/7eH4XwWA

Kindly need your assist for fix ASAP my problem.

Thank you,

**Comment by djpongh** [comment]
Couchbase != couchdb

You might try our forums for help but we do not support couchdb.
