### ISSUE TITLE
CBL 1.4.1 unable to delete document due to not found error.

### ISSUE THREAD

**Issue by brendand** [couchbase/couchbase-lite-ios#2134]
I have a situation in a customer's database where he has a basically empty record that can't be deleted.

I traced through the code and found that CBL (1.4.1) is returning kCBLStatusNotFound when trying to delete (or even modify) the document.

Here's the relevant code being executed in CBL_SQLiteStorage.m (1728) in 

```
- (CBL_Revision*) addDocID: (NSString*)inDocID

                 prevRevID: (CBL_RevID*)inPrevRevID

                properties: (NSMutableDictionary*)properties

                  deleting: (BOOL)deleting

             allowConflict: (BOOL)allowConflict

           validationBlock: (CBL_StorageValidationBlock)validationBlock

                    status: (CBLStatus*)outStatus

                     error: (NSError**)outError

...

        SequenceNumber parentSequence = 0;

        if (prevRevID) {

            // Replacing: make sure given prevRevID is current & find its sequence number:

            if (isNewDoc)

                return kCBLStatusNotFound;

            parentSequence = [self getSequenceOfDocument: docNumericID revision: prevRevID

                                             onlyCurrent: !allowConflict];

            if (parentSequence == 0) {

                // Not found: kCBLStatusNotFound or a kCBLStatusConflict, depending on whether there is any current revision

                if (!allowConflict && [self existsDocumentWithID: docID revisionID: nil])

                    return kCBLStatusConflict;

                else

                    return kCBLStatusNotFound;

            }
```

The last `return kCBLStatusNotFound` bit is what's being executed when this code runs. 

Is there any way that I can get rid of this document even though the parentSequence is 0 and it falls through to the else statement? I just want to be able to delete it and move on. But it's preventing any documents in a batch transactions from being saved if this document appears in the transaction block being saved.

--------
* Version:   1.4.1
* Client OS: macOS 10.13.4
* Server:    n/a

**Comment by brendand** [comment]
One more clarification. The document cannot be updated nor deleted. So it's not just a deletion issue.

**Comment by snej** [comment]
Is it possible to get a copy of the database?

**Comment by brendand** [comment]
I'll ask my customer if it's ok then I'll email you.

**Comment by brendand** [comment]
For reference to this issue, once I get you the database, the error that's displayed when the document can't be deleted is:

```
11:47:42.258| Database: DELETE _id=rec-d4556f07fcc741b7845be076632714e2, _rev=1-f3f223af31358e5eee8338c5f9d14ee7 (allowConflict=0)
2018-04-05 11:47:42.258682-0600 Tap Forms 5[57551:5686275] error deleting document: Error Domain=CBLHTTP Code=404 "not_found" UserInfo={NSLocalizedFailureReason=not_found, NSLocalizedDescription=not_found}
```

or updated:

```
11:56:02.270| Database: PUT _id=rec-d4556f07fcc741b7845be076632714e2, _rev=1-f3f223af31358e5eee8338c5f9d14ee7 (allowConflict=0)
11:56:02.270| Database: }} Abort transaction (level 1)
2018-04-05 11:56:02.269938-0600 Tap Forms 5[57551:5686275] Error saving value: Error Domain=CBLHTTP Code=404 "not_found" UserInfo={NSLocalizedFailureReason=not_found, NSLocalizedDescription=not_found}
```

There may be other documents with this same situation in the database.

**Comment by brendand** [comment]
Email sent with copy of database.

**Comment by jayahariv** [comment]
Closing 1.x issue!
