### ISSUE TITLE
CBL 2.0 cannot be imported in Swift 4.1

### ISSUE THREAD

**Issue by Codeido** [couchbase/couchbase-lite-ios#2135]
![couchbase](https://user-images.githubusercontent.com/495617/38370810-493d2988-38eb-11e8-9813-4f8c94c325d9.png)

Couchbase lite 2.0 currently not run on Swift 4.1 (Xcode 9.3).

--------
* Version:  2.0 DB 21
* Client OS: iOS 11
* Server:    -

**Comment by pasin** [comment]
Same as https://github.com/couchbase/couchbase-lite-ios/issues/2126, and the issue will be fixed in the next release.
