### ISSUE TITLE
Instructions for CocoaPods or Carthage are missing (404) under releases

### ISSUE THREAD

**Issue by roikatz** [couchbase/couchbase-lite-ios#2136]
When you go to the releases page, under the "Where to get it" section,
The link for instructions is dead: "https://github.com/couchbase/couchbase-lite-ios/tree/feature/2.0"
you get the generic gitHub 404 page instead of instructions.

**Comment by jamiltz** [comment]
Looks like that link was added by hand for each DB. The link broke when 2.0 was merged to master. Engineering typically maintains this content so re-assigning to Pasin.

**Comment by pasin** [comment]
Fixed. Thanks.
