### ISSUE TITLE
Carthage JSON invalid for CBL Community Edition

### ISSUE THREAD

**Issue by btyler** [couchbase/couchbase-lite-ios#2142]
If I try to install the community edition as in the readme, carthage gives me this error:

Unable to parse binary-only framework JSON at https://raw.githubusercontent.com/couchbase/couchbase-lite-ios/master/Release/Carthage/CouchbaseLite-Community.json due to error: invalid JSON: dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "No value." UserInfo={NSDebugDescription=No value.})))

--------
* Version:   2.0
* Client OS: OSX 10.13.4
* Server:    -

**Comment by pasin** [comment]
Thanks for letting us know.  Please try again. Fixed in https://github.com/couchbase/couchbase-lite-ios/commit/e39fda5ae6812c36d0bb7b15a163549a64170232.
