### ISSUE TITLE
latest iOS cbl 2.1.0 builds are crashing 

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-ios#2150]
### Version
CBL - 2.1.0-150
sg version -> 2.1.0-55

### Issue caused 
1. Running ios functional tests on jenkins having crash on the app and bunch of tests failing

I ran tests with 2.1.0-126 and that looks good

If I run tests individually, it works fine.
### Logs:

[CBLTestServer-iOS_2018-04-30-154305-1_Dans-Test-MacBook-Pro.crash.zip](https://github.com/couchbase/couchbase-lite-ios/files/1968363/CBLTestServer-iOS_2018-04-30-154305-1_Dans-Test-MacBook-Pro.crash.zip)

**Comment by pasin** [comment]
Please try with build [156](http://latestbuilds.service.couchbase.com/builds/latestbuilds/couchbase-lite-ios/2.1.0/156). Thanks.

**Comment by sridevi-15** [comment]
testing on build 159 and it looks good. Do not see any crash
