### ISSUE TITLE
Pod install fails with CBL 2.0.0

### ISSUE THREAD

**Issue by vaskooooo** [couchbase/couchbase-lite-ios#2151]
Environment
macOS Sierra 10.12.6
Cocoapods 1.5.0
Xcode 9.2 (9C40b)

Log
 > Running prepare command
   $ /bin/bash -c  set -e sh Scripts/prepare_cocoapods.sh "CBL Swift"
   Preparing CouchbaseLite framework ...
 > Running prepare command
   $ /bin/bash -c  set -e sh Scripts/prepare_cocoapods.sh "CBL ObjC"
   Preparing CouchbaseLite framework ...
[!] Unable to find a specification for 'CouchbaseLiteSwift'.

Note:
tag => '2.0DB022' works correctly!

**Comment by pasin** [comment]
When we published the pod spec to Cocoapod, we realized that CouchbaseLiteSwift has been taken. We changed the name to `CouchbaseLite-Swift`. Please change the name in the pod file to `CouchbaseLite-Swift`. Sorry for confusion.

**Comment by rajagp** [comment]
FYI : The 2.0.0 documentation specifies "CouchbaseLite-Swift" ( https://developer.couchbase.com/documentation/mobile/2.0/couchbase-lite/swift.html)
