### ISSUE TITLE
Connection error #1, retrying in 2.0 sec: NSURLError[-1001, "Timeout"

### ISSUE THREAD

**Issue by suzhaev** [couchbase/couchbase-lite-ios#2159]
We are create replication like this:

```
        CBLReplication *pull = [database createPullReplication:url];
        CBLReplication *push = [database createPushReplication:url];
        
        NSDictionary *auth = @{ @"Authorization" : ***};
        [pull setHeaders:auth];
        [push setHeaders:auth];
        
        pull.continuous = YES;
        push.continuous = YES;
        [pull start];
        [push start];
```

In logs:

```
15:33:58.000‖ ChangeTracker: CBLSocketChangeTracker[0x60c0003d8150 pl_restik_sjapxviwg]: Start timeout, will timeout in 330 sec.
15:33:58.000‖ ChangeTracker: CBLSocketChangeTracker[0x60c0003d8150 pl_restik_sjapxviwg]: Started... <https://***/_changes?feed=longpoll&heartbeat=300000&style=all_docs&since=***>
15:39:28.000‖ ChangeTracker: CBLSocketChangeTracker[0x60c0003d8150 pl_restik_sjapxviwg]: Timeout ...
15:39:28.002‖ CBLSocketChangeTracker[0x60c0003d8150 pl_restik_sjapxviwg]: Connection error #1, retrying in 2.0 sec: NSURLError[-1001, "Timeout", <https://***/_changes?feed=longpoll&heartbeat=300000&style=all_docs&since=***>]
```

Then interval between request increases.

```
retrying in 2.0
retrying in 4.0
retrying in 8.0
...
```

 What we are doing wrong? Thank you

--------
* Version:   1.4.1
* Client OS: iOS
* Server: Apache CouchDB 2.1.1

**Comment by suzhaev** [comment]
Сan anyone help? Why client close connection by timeout? Seems it isn't get heartbeat?
We debug it several days, but can not find the cause of the error

**Comment by pasin** [comment]
ChangeTracker has an internal timer for detecting half-close connection so the timer will timeout if change tracker hasn't received any data from the remote host for sometime including heartbeat. Would it be possible to check if the remote host send the heartbeat?

**Comment by suzhaev** [comment]
@pasin thank you for your reply!
what is the best way to check heartbeat is being sent?

**Comment by suzhaev** [comment]
We tried check it via Charles.

Request closed on client, but still "waiting for response" in Charles, I don't see any data from the remote host or heartbeat.

Here screenshots: 
<img width="968" alt="2018-06-04 18 58 17" src="https://user-images.githubusercontent.com/19522238/40928303-a49d9f98-6829-11e8-88c7-36353dca4e23.png">
<img width="1100" alt="2018-06-04 18 58 36" src="https://user-images.githubusercontent.com/19522238/40928304-a4bbcfcc-6829-11e8-917b-666ec65754b5.png">
<img width="1099" alt="2018-06-04 18 58 46" src="https://user-images.githubusercontent.com/19522238/40928305-a4d838a6-6829-11e8-964d-8565a13fb7d5.png">
<img width="453" alt="2018-06-04 18 59 27" src="https://user-images.githubusercontent.com/19522238/40928306-a4fd8408-6829-11e8-97a1-74bb277bb7c7.png">

**Comment by jayahariv** [comment]
Closing 1.x issue!
