### ISSUE TITLE
Incompatible swift version

### ISSUE THREAD

**Issue by Thiryn** [couchbase/couchbase-lite-ios#2161]
Hi, I am using carthage as package manager, and the lastest XCode version (iOS 11.4 with XCode 9.3). Unfortunately, couchbase-lite-ios is a binary-only release with Carthage (recomended way to get it in the readme) and is incompatible with the latest swift version:
```bash
$ carthage update --platform iOS              
*** Downloading binary-only framework CouchbaseLite-Community at "https://raw.githubusercontent.com/couchbase/couchbase-lite-ios/master/Release/Carthage/CouchbaseLite-Community.json"
*** xcodebuild output can be found in /var/folders/f9/33ntg5xj38n_5xrdj7rc7bqh0000gq/T/carthage-xcodebuild.9T8SGO.log
Incompatible Swift version - framework was built with 4.1 (swiftlang-902.0.48 clang-902.0.37.1) and the local version is 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2).
```
--------
* Version:   2.0.0
* Client OS: macOS High Sierra 10.13.4
* Server:    n/a

**Comment by pasin** [comment]
I was able to reproduce this when using XCode 9.4. We need to re-release the pre-built binaries built with the new XCode.

**Comment by pasin** [comment]
It turns out Carthage does check the swift version even though the binary compiled with Swift 4.1 seems to be working fine with Swift 4.1.2.

**Comment by Thiryn** [comment]
My guess is the version check is done because carthage usually pulls git repository and build the library locally. AFAIK Apple do not pre-release for developers (at least minor versions) it would be easier if couchbase-lite-ios gives the possibility to build with carthage, not only have a binary release.
With binary releases, the release is tied with the swift version, which means that it need to be re-released with every new swift version and the new library is not usable (with carthage) for the one who did not do the update (yet).

**Comment by pasin** [comment]
Currently we have some shared schemes that cannot be built directly from couchbase-lite-ios repo. Carthage doesn't support a feature to select schemes to build. I agree that it's better to provide an option to build from source. We will need to work on that.

**Comment by pasin** [comment]
We plan to release 2.0.3 which will fix the issue. Meanwhile you can try to use Carthage to build the source code from master or release/2.0.x branch.

**Comment by skela** [comment]
I get the usual failures when trying to have carthage build from source:

*** Building scheme "SQLCipher iOS" in sqlcipher.xcodeproj
Build Failed

Any idea how long it will take to get 2.0.3 ? Or a new binary ready?

**Comment by Thiryn** [comment]
I successfully built from source the version I am using (2.0.0), I kept the .framework locally and force carthage not to update this package (remove the cbl line from `Cartfile` when updating, removing the line from `Cartfile.resolved` when bootstraping) while this bugfix is not released (meaning  my CI is broken btw...)

**Comment by snej** [comment]
@skela, what's the actual build error? If it's not shown in the navigator UI, you can look in the build log.

**Comment by pasin** [comment]
@skela `*** Building scheme "SQLCipher iOS" in sqlcipher.xcodeproj` shouldn't happen with 2.0. Please make sure the right branch was selected.

**Comment by skela** [comment]
@snej @pasin I got the error with both
`github "couchbase/couchbase-lite-ios" ~> 2.0.3`
and master

`github "couchbase/couchbase-lite-ios" "release/2.0.x"`

Works though without errors, thanks, sorry about that.

**Comment by pasin** [comment]
Sometime you may need to delete carthage cache. I ran into this myself when trying to use cathage pointing to the master branch. See https://github.com/Carthage/Carthage/issues/1191 for some detail.

```
rm -rf ~/Library/Caches/org.carthage.CarthageKit
```
