### ISSUE TITLE
iOS Swift: Best practice to include CouchbaseLite framework in a custom frafmework

### ISSUE THREAD

**Issue by parvezq** [couchbase/couchbase-lite-ios#2166]
It may be possible that one may have multiple reusable components in iOS swift that needs to be converted into custom frameworks such that all these requires use of CouchbaseLite framework. Looking to this requirement, it seems that various custom frameworks should not embed CouchbaseLite and instead have it available as a separate framework.

How this can be achieved?

What I have tried to achieve above thing is summarized below:
1. Created a CocoaTouch framework for iOS Swift.
2. In Xcode (9.3.1)'s General > Linked Frameworks & Libraries section, I added CouchbaseLite and all 
    dependencis like libsqlite3.tbd, libc++.tbd, libz.tbd etc.
3.  Also added a run script build phase so as to create a universal framework.
4. In the Framework header, I added `#import <CouchbaseLite/CouchbaseLite.h>`
5. After creating a universal framework, I am able to add it to another iOS Swift project and get it compiled successfully. On iOS simulator it runs fine but on device it is giving error at runtime that **Library not loaded** followed by the framework name that I created.
6. Using LIPO command on the created framework, I ensured that the framework is properly created for device & simulator.

What's wrong with above procedure?

--------
* Version:   1.4.1
* Client OS: iOS 11

**Comment by parvezq** [comment]
The framework header is under Public section of Build Phase > Headers

**Comment by snej** [comment]
I don't think you should embed CBL.framework inside your framework; instead, the frameworks should be peers of each other.

This sounds like a general issue with Swift framework dependencies, and I don't know what the answer is. Try asking on the Swift.org forums.

**Comment by parvezq** [comment]
@snej can you please suggest how we can use CBL framework without embedding it inside the custom framework?

**Comment by snej** [comment]
I don't know what the answer is. Try asking on the Swift.org forums.

**Comment by djpongh** [comment]
Unfortunately, nothing we can do on our end.
