### ISSUE TITLE
CBL Library 1.4 compilation is failing with Xcode 10 (SDK 12)

### ISSUE THREAD

**Issue by SaurabhDwivediMsi** [couchbase/couchbase-lite-ios#2167]
--------
* Version:   1.4.1
* Client OS: iOS 12

Hi,
 
CBL Library compilation is failing with Xcode 10 (SDK 12).
Type casting issue was also present for log line. This error is fixed locally.
But we are unable to resolve below mentioned error msg.
How we can resolve this error?
For error details Please refer screen shots.

Error: **"Parameter of overriding method should be annotated with __attribute__((noescape))"** 
CBL Version Used: 1.4.1 
Platform : iOS
IDE: Xcode 10 beta

![screen shot 2018-06-11 at 12 18 06 pm](https://user-images.githubusercontent.com/40160092/41216684-f20d1954-6d72-11e8-846e-39ddb99721e6.png)
![screen shot 2018-06-11 at 12 18 08 pm](https://user-images.githubusercontent.com/40160092/41216686-f240ce34-6d72-11e8-9013-efc956b9e5c4.png)
![screen shot 2018-06-11 at 12 18 24 pm](https://user-images.githubusercontent.com/40160092/41216687-f2707bc0-6d72-11e8-8bd9-3484c6d46d8e.png)
![screen shot 2018-06-11 at 12 18 43 pm](https://user-images.githubusercontent.com/40160092/41216688-f2a02960-6d72-11e8-9e66-6355e88cc18e.png)
![Uploading Screen Shot 2018-06-11 at 12.18.55 PM.png…]()

**Comment by snej** [comment]
Do you need to compile CBL itself? We prefer that people use the pre-built frameworks downloaded from Couchbase.

Have you tried doing exactly what the error message says — adding `__attribute((noescape))` to the parameter declaration?

**Comment by SaurabhDwivediMsi** [comment]
Hi Jens,

I am able to compile successfully by adding *MYNoEscape* in definition of
below mentioned function.
Please review attached files for SDK12 compilation.


Function:

- (NSArray*) my_map: (MYNoEscape *id* (^)(*id* obj))block;

- (NSArray*) my_filter: (MYNoEscape *int* (^)(*id* obj))block;

- (*void*) my_removeMatching: (MYNoEscape *int* (^)(*id* obj))block;

- (NSDictionary*) my_dictionaryByUpdatingValues: (MYNoEscape *id* (^)(*id*
key, *id* value))block;


Saurabh Kumar Dwivedi
Senior Software Engineer
+91-7406969389
saurabh.dwivedi@motorolasolutions.com

*Kodiak*, a Motorola Solutions Company
+1 972-665-0200  |  kodiakptt.com  |  motorolasolutions.com
[image: Kodiak, a Motorola Solutions Company] <https://kodiakptt.com/>



On Mon, Jun 11, 2018 at 9:45 PM, Jens Alfke <notifications@github.com>
wrote:

> Do you need to compile CBL itself? We prefer that people use the pre-built
> frameworks downloaded from Couchbase.
>
> Have you tried doing exactly what the error message says — adding
> __attribute((noescape)) to the parameter declaration?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_couchbase_couchbase-2Dlite-2Dios_issues_2167-23issuecomment-2D396299831&d=DwMFaQ&c=q3cDpHe1hF8lXU5EFjNM_A&r=s7TOJ1AvZEaXVaKQR_pxnLJOX9UWUaO6Yw3-6hstPNz2JHW4gLllW63GAXPR7I-k&m=pP4WwtbpTKo8GQJ6VpmW_63On3i6SQJV4NLPgE80Tvc&s=X1kbp4yR43fjWNg8YnmIZiZxbS4aE9V0DsK5UuHynlI&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AmTLXPK302PfkNVnyezqpP-5FXVDWdmMRaks5t7peugaJpZM4UiJ9L&d=DwMFaQ&c=q3cDpHe1hF8lXU5EFjNM_A&r=s7TOJ1AvZEaXVaKQR_pxnLJOX9UWUaO6Yw3-6hstPNz2JHW4gLllW63GAXPR7I-k&m=pP4WwtbpTKo8GQJ6VpmW_63On3i6SQJV4NLPgE80Tvc&s=Dw0VQ3dvTEJ2WheOYvpznRROC7wsH81jOXb12C0ahmY&e=>
> .
>



--

**Comment by zippo227** [comment]
> Github Issues doesn't support file attachments. If you want to send a proposed fix, please open a pull request.
> 
> Also, note that Couchbase does not support building Couchbase Lite with unreleased versions of Xcode.

Xcode 10 has moved from Beta to Gold Master (GM). Are GM builds supported?

**Comment by pasin** [comment]
I have fixed some XCode 10 build issue in 1.x branch. Could you please try to build the framework and let me know if you are still seeing the issue? We will release the binary build with XCode 10 in 1.4.4.

**Comment by zippo227** [comment]
I'll try to look into that on Monday.
