### ISSUE TITLE
Swift error in module CouchbaseLiteSwift Warning in lldb

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#2172]
```
*(lldb) po options*

warning: Swift error in module CouchbaseLiteSwift.

Debug info from this module will be unavailable in the debugger.
```

--------
* Version:   2.0 / 2.1
* Client OS: Any
* XCode: 9.4

**Comment by pasin** [comment]
There is an apple radar opened: http://www.openradar.me/30646008

**Comment by pasin** [comment]
To complement about what Apple said above, I noticed that the binary built from my Mac doesn't have the issue when I use it on the same Mac. I have tested to use it on a different Mac that has the same XCode version yet.

**Comment by djpongh** [comment]
Unfortunately, we need Apple to take care of this.
