### ISSUE TITLE
Replication stops when sg restarts

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-ios#2173]
### Environment
* Version:   2.0.4-5
* Client OS: iOS

### Steps to reproduce : 
1. Create docs in cbl (around 1000 is better to test )
2. Start push_pull replication with continous True 
3. While replication happening, restart sync-gateway
4. Verify all docs got replication to sync-gateway

### Result : 
1. Only few docs , out of 1000 docs, around 200 docs gets replicated and then stops

### Expected : 
All docs should get replicated.

### Test : 
https://github.com/couchbaselabs/mobile-testkit/blob/master/testsuites/CBLTester/CBL_Functional_tests/TestSetup_FunctionalTests/test_replication.py#L2105
Test name is : test_CBL_push_pull_with_sg_down

### Logs : 
cbl logs : 
https://gist.github.com/sridevi-15/26057b981d4f2fc77891bda877c552eb

**Comment by pasin** [comment]
Could you test with http://latestbuilds.service.couchbase.com/builds/latestbuilds/couchbase-lite-ios/2.0.4/8/?

**Comment by pasin** [comment]
@sridevi-15 reported another error which also caused the replicator to stop. Here is the log:
https://gist.githubusercontent.com/sridevi-15/ed542ed79380e1289bb736b2a012e679/raw/e8a92315c2ae43fc31e4be4a4d67772194fa3fcd/cbl%2520logs2

It seems like this scenario of this case is:
1. <CBLWebSocket: 0x604000157970>: EndEncountered on read stream
2. <CBLWebSocket: 0x604000157970>: Disconnect
3. CBLWebSocket CLOSED
4. WS WARNING: {C4SocketImpl#1} Unexpected or unclean socket disconnect! (reason=WebSocket status, code=1000)
5. BLIP Info: {Connection#1} Closed with WebSocket status 1006: (null)
6. Sync Info: {Repl#1} Connection closed with WebSocket status 1006: "(null)" (state=2)
7. Sync ERROR: {Repl#1} Got LiteCore error: connection closed abnormally (6/1006)
8. CBLReplicator[<*> URL[ws://192.168.33.11:4984/db]] is busy, progress 70968/1613076, error: Error Domain=CouchbaseLite Code=11006 "connection closed abnormally" UserInfo={NSLocalizedDescription=connection closed abnormally} --> This is strange that the status is busy.
9. CBLReplicator[<*> URL[ws://192.168.33.11:4984/db]] is stopped, progress 325802/1613076, error: Error Domain=CouchbaseLite Code=11006 "connection closed abnormally" UserInfo={NSLocalizedDescription=connection closed abnormally} --> Eventually the replicator stopped as connection closed abnormally.

Currently we don't recognize the `1006` error as a recoverable error so the replicator stopped. A quick workaround is to do the retry when the CBLReplicator gets `1006` error.

**Comment by pasin** [comment]
The problem is that the NSStreamEventEndEncountered event could be a result from either socket close requested by C4Socket or connection reset by peer.  For the latter case, we should call `c4socket_closed(socket, error)` with `ECONNRESET` instead of null.

**Comment by snej** [comment]
I don't think this was actually an ECONNRESET, or NSStream would have reported it. I think SG just closed its socket while it was shutting down. (I assume that SG was stopped cleanly, not just killed?)

The error in steps 5-7 is correct — WebSocket status 1006, "the connection was closed abnormally, e.g., without sending or receiving a Close control frame."

So I think the problem is that WebSocket/1006 isn't recognized as a transient error that should cause CBL to retry.

**Comment by sridevi-15** [comment]
I tested it out with 2.0.4-9, It passed with sg version 2.1.0-107, but it failed with sg version 2.1.0-55. 
When I tested yesterday with 2.0.4-5 , it failed on both sg versions. 

cbl logs with sg version 2.1.0-95 : https://gist.github.com/sridevi-15/c836a851900d675250e252b43c89250b

cbl logs with sg version 2.1.0-107 : https://gist.github.com/sridevi-15/341b705f5da157da4d7e21e86849e332

**Comment by pasin** [comment]
@sridevi-15 Please test with http://latestbuilds.service.couchbase.com/builds/latestbuilds/couchbase-lite-ios/2.0.4/10.

**Comment by sridevi-15** [comment]
test has passed with both builds of sg version i.e 2.1.0-95 and 2.1.0-107
