### ISSUE TITLE
Replication is not finishing in multiple apps (iOS devices) cluster for high doc count

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-ios#2175]
--------
* Version:   2.0.4-9
* Client OS: iOS simulator
* Server:    CBS-5.5.0-2884
* SG: 2.1-95

I'm running system test for 1M docs with 4 iOS devices (250k docs/ per device). After creating docs on all devices, I start replication on each device sequentially. Replication from device 1 got completed, however replication on device 2 never finishes up and is still in busy state. I can see the doc count on CBS is 501,031 as below.

<img width="1440" alt="screen shot 2018-06-21 at 11 46 23 am" src="https://user-images.githubusercontent.com/18100038/41701109-c6059a1a-7548-11e8-9d5a-c99837df1e9c.png">

Attaching logs from Xcode for second device - 
[cbl logs.zip](https://github.com/couchbase/couchbase-lite-ios/files/2122361/cbl.logs.zip)

SG logs are quite huge so adding last 20k lines from sync_gateway_error.log. Will send the location to access sgcollect zip file over mail - 
[sync_gateway_error_last20k.log.zip](https://github.com/couchbase/couchbase-lite-ios/files/2122368/sync_gateway_error_last20k.log.zip)

**Comment by hrajput89** [comment]
sgcollect logs are available at - https://s3.amazonaws.com/bugdb/jira/github-2175/sgcollect_info.zip

**Comment by borrrden** [comment]
Note: Looking at the logs it seems like all the documents *are* replicated, but the replicator stays in busy for some unknown reason.

**Comment by djpongh** [comment]
@snej , can you take a look? This is for our MP.

**Comment by snej** [comment]
90% of the CBL log file is actually logs from the QE API, like
```
[DEBUG] Did open connection on socket 16
[DEBUG] Did connect
[DEBUG] Did start background task
[DEBUG] Connection received 176 bytes on socket 16
[DEBUG] Connection on socket 16 preflighting request "POST /replicator_getError" with 176 bytes body
...
```
In the future could this be turned off, or maybe written to a different file?

**Comment by snej** [comment]
The last log message from the replicator is at 16:52:20:
```
2018-06-20 16:52:20.568373+0530 CBLTestServer-iOS[2642:65509] CouchbaseLite Sync Info: CBLReplicator[<*> URL[ws://172.16.12.250:4984/db]] is busy, progress 56793934/56793934, error: (null)
```
So, as Jim said, the replicator seems to have completed but it's stuck in the Busy state. There's no good way to debug this without turning on some more logging that's only enabled in debug builds, unfortunately.

**Comment by hrajput89** [comment]
I ran the system test again today with 2.0.4-10 build and it also got stuck at the same point.

SG logs - https://s3.amazonaws.com/bugdb/github-2175/sgcollect_info-2.0.4-10.zip
CBS Logs - https://s3.amazonaws.com/bugdb/github-2175/cbs-172.16.12.226_node.zip
CBL Logs - 
[cbl logs.zip](https://github.com/couchbase/couchbase-lite-ios/files/2127201/cbl.logs.zip)

If you can provide the debug build, I'll be able to run with it.

**Comment by snej** [comment]
@hrajput89, I'm emailing you a debug build right now. Please set Sync logging to the Debug level.

**Comment by hrajput89** [comment]
I setup the cluster today properly and the replication was able to complete on second device. There was some issue in network due mixed network settings between devices. I've kept the test running and will update about progress. 

Closing this issue for now.

**Comment by ritamcouchbase** [comment]
Test has started to run for build 10
