### ISSUE TITLE
iOS Swift: Unable to view a cblite2 database created from CouchbaseLite 2.0 framework

### ISSUE THREAD

**Issue by parvezq** [couchbase/couchbase-lite-ios#2176]
For cblite2 generated via iOS CouchbaseLite.framework version 1.4.1, we are able to view the database file using CouchbaseLiteViewer with no issues.
After updating the iOS CouchbaseLite.framework to 2.0, when we try to open the database file in viewer then it fails to open and instead shows the message "The document somedb.cblite2" could not be opened.
For the generated cblite2 database we are using "wss" url scheme. 
What is causing this issue?

I have ensured that the CouchbaseLite Viewer has latest CBL framework available  in it which is "CouchbaseLite Version: 1.4.0 (build 3)"

Below is the error that I see in XCode console (in CouchbaseLite viewer project) when opening a cblite2 file:

`WARNING: SQLite error (code 1): near "(": syntax error {at errorLogCallback:125}
19:22:27.095| WARNING: SQLite error (code 11): database corruption at line 108616 of [2ef4f3a5b1] {at errorLogCallback:125}
19:22:27.095| WARNING: SQLite error (code 1): near "(": syntax error {at errorLogCallback:125}
19:22:27.096| WARNING: SQLite error (code 11): database corruption at line 108616 of [2ef4f3a5b1] {at errorLogCallback:125}
19:22:27.096| WARNING: SQLite error (code 11): malformed database schema (tasks) - near "(": syntax error {at errorLogCallback:125}
19:22:27.096| WARNING: CBL_SQLiteStorage: database is unreadable (err 11) {at -[CBL_SQLiteStorage decryptWithKey:error:]:308}`

I tried to open other cblite2 files also with CouchbaseLiteViewer and same error occurs. Previously these files are opening in viewer without any issues. Using another sqlite viewer for eg: "DB Browser for SQLITE" opens the database with no issues. Also running the query "PRAGMA Integrity" on these databases do not show any errors.

MAC OS X version: 10.13.2
XCode version: 9.3.1 (9E501)

**Comment by snej** [comment]
The database viewer app uses Couchbase Lite 1, which can't read Couchbase Lite 2 databases. We'd have to update the viewer to use CBL 2.

**Comment by parvezq** [comment]
Do we have any tentative deadline to update couchbase viewer? Though we are able to open cblite2 in other sqlite browser but it is very difficult to visualize the database content. Can you please share the sql query that we can use to list out  data in other database browser
________________________________

**Comment by borrrden** [comment]
You will not be able to view the data via SQLite viewer.  There is a command line tool which I believe is inside the zip file that you download to get Couchbase Lite (look in tools) called "cblite" which is similar to the sqlite command line tool.  It can perform operations on a database such as listing documents, querying, etc.

**Comment by parvezq** [comment]
Will it provide same kind of display as is done by viewer? I haven't tried it yet.
________________________________

**Comment by borrrden** [comment]
It's not a graphical application, so it won't be exactly the same.  You will be able to get the same information (and more) out of it though.

**Comment by shobhakartiwari** [comment]
Hi i am trying to find details about the mobile data in cblite 2 using cblite command tools , which comes through couchbase-lite-swift_enterprise_2.1.1 folder , but i am unable to run the tools , as it says comand not found or

shobhakar-mac$ ./cblite

cblite: Couchbase Lite / LiteCore database multi-tool

Missing subcommand or database path.

For a list of subcommands, run cblite help .

To start the interactive mode, run cblite DBPATH

shobhakar-mac$ cblite /downloads/cblite2db

-bash: cblite: command not found

Kindly help me how to use this tool to debug the cblite db , i read the help file , but still the same issue .

**Comment by rajagp** [comment]
As error indicates, you have to pass in the cblite database file as a parameter.
Example : 
`
./cblite /path/to/mydb.cblite2
`

You will be provided with an interactive shell from where you can introspect the database

**Comment by shobhakartiwari** [comment]
Thanks @rajagp  for quick response . 

**I tried this and it works** 👍 

shobhakar$ ./cblite  /Downloads/mobile-travel-sample-master/ios/TravelSample/TravelSample/prebuilt/travel-sample.cblite2 
Opened database /Downloads/mobile-travel-sample-master/ios/TravelSample/TravelSample/prebuilt/travel-sample.cblite2/

Thanks for help again.

**Comment by filip982** [comment]
How can we view the Couch database 2.0 these days? The CouchbaseLiteViewer is not updated which the most unfortunate. Is there any solution out there? I can't even find the cblite tools. Please advise

**Comment by borrrden** [comment]
Please direct questions to [the forums](https://forums.couchbase.com/c/mobile)
