### ISSUE TITLE
Include document type property value in database change object

### ISSUE THREAD

**Issue by lightandshadow68** [couchbase/couchbase-lite-ios#2177]
Is it possible to include the "type" property value of a document as part of a database change notification?  This would circumvent the need to load each changed document to see if it's of a type I might be interested in. (I had started implementing this as part of a new feature, but the functionality was moved to the server and synced to the device via a document)

**Comment by snej** [comment]
Have you tried using a LiveQuery?

**Comment by lightandshadow68** [comment]
What I was trying to do was trigger rebuilding a cache containing expensive computed metadata for a specific model which is derived from multiple documents across different types. These documents do not change often, but invalidation could come from a change in any document across multiple types.

In my specific use case, one property consisted of a string representation of a node in a hierarchy, which has the hierarchy relations in one document, details about the nodes in others and a number of other related documents. "Root / Child 1 / Child 2 / Child 3". A change to any of theses documents requires rebuilding the cache. 

Since the client does not make local changes to these documents, It seemed much simpler to monitor for changes to of those types and update the local cache document. To use a live query, I'd need to somehow create a view that emits all of the right keys and values, including nested structures from the hierarchy, so the resulting view would be updated, trigger KVO and kick of a rebuild.

Would it be possible to just emit the revision ID instead of every property from the doc?

**Comment by pasin** [comment]
You can emit `document ID` with a `nil` value to get the change notified by the LiveQuery.

```
if (some-condition) {
    emit(doc[@"_id"], nil);
}
```

**Comment by jayahariv** [comment]
Closing issue, since 1.x already reached the end of life.
