### ISSUE TITLE
HTTP redirects are not handled

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-ios#2179]
### Version
2.0.4-10 on iOS 11.4 iPhone

### Steps
- Set up 1 CBS and 2 SGs.
- Set up a squid proxy to redirect incoming requests from SG1 to SG2.
- Verify that the redirect works
- Install the iOS test server and start a replication with SG1.

### Actual results
Replication test fails with the below error
```
>                   raise Exception("Error while replicating", err)
E                   Exception: ('Error while replicating', 'Optional(Error Domain=CouchbaseLite Code=11008 "OK" UserInfo={NSLocalizedDescription=OK})')
```
### Test setup
CBS - 10.17.6.122
SG1 - 10.17.6.121
SG2 - 10.17.6.141

### Squid redirects
```
» http --proxy=http:http://10.17.6.118:8080 10.17.6.121:4985
HTTP/1.1 302 Found
Connection: keep-alive
Content-Length: 0
Date: Tue, 26 Jun 2018 22:31:05 GMT
Location: http://10.17.6.141:4985/
Server: squid/3.5.20
Via: 1.1 localhost.localdomain (squid/3.5.20)
X-Cache: MISS from localhost.localdomain
X-Cache-Lookup: MISS from localhost.localdomain:8080

~ » http --proxy=http:http://10.17.6.118:8080 10.17.6.121:4984
HTTP/1.1 302 Found
Connection: keep-alive
Content-Length: 0
Date: Tue, 26 Jun 2018 22:31:16 GMT
Location: http://10.17.6.141:4984/
Server: squid/3.5.20
Via: 1.1 localhost.localdomain (squid/3.5.20)
X-Cache: MISS from localhost.localdomain
X-Cache-Lookup: MISS from localhost.localdomain:8080
```
### CBL Logs
https://gist.github.com/raghusarangapani/e3f1faa8ddc8639cdeb4a1c5887b0396

### Squid config
https://gist.github.com/raghusarangapani/c7f14f612ebafe27b0635647b7d823fb

### php redirect program
```
#!/usr/bin/php
<?php

$temp = array();

// Extend stream timeout to 24 hours
stream_set_timeout(STDIN, 86400);

while ( $input = fgets(STDIN) ) {
  // Split the output (space delimited) from squid into an array.
  $temp = split(' ', $input);

  // Set the URL from squid to a temporary holder.
  $output = $temp[0] . "\n";

  // Check the URL and rewrite it if it matches foo.example.com
  if ( strpos($temp[0], "10.17.6.121:4984") !== false ) {
    $output = "302:http://10.17.6.141:4984/\n";
  } elseif( strpos($temp[0], "10.17.6.121:4985") !== false ) {
    $output = "302:http://10.17.6.141:4985/\n";
  }
  echo $output;
}
```

**Comment by snej** [comment]
I'm confused by the purpose of this test — proxying is not the same as redirecting, and I don't know if you can combine them this way. It looks like your setup, with the PHP script, is designed to return a 302 status from the CONNECT request? I don't know if this is something that a proxy is expected to do, and it looks as though iOS's NSURLSession is not handling it.

**Comment by pasin** [comment]
@raghusarangapani Could you please revise the test?

**Comment by pasin** [comment]
I have done some test by setting up a simple HTTP server at port 8000 that redirects to SG at port 4984. I haven't used proxy to redirect as I'm not sure if it's the same thing or not.

Here is the result:
1. Redirect without Proxy : **Pass**
2. Redirect with Proxy : **Failed** with 400 Bad Request for GET db/_blipsync

The scenario 2 passed with using NSURLSession. The difference that I have seen is that when using NSURLSession, there are two CONNECT request sent to port 8000 and then 4984 respectively. When using NSStream implementation, there is only one CONNECT request sent to port 8000. That is something that is missing in our NSStream implementation.
