### ISSUE TITLE
CBL 2.0: Query issue: Particular document is not appearing in query results.

### ISSUE THREAD

**Issue by parvezq** [couchbase/couchbase-lite-ios#2180]
Using the Database's document(withID: aDocID), I have ensured that a document with given ID exists.
When I try below query then that document's data is not being included in the query results:

```
self.recentChatMessagesQuery = QueryBuilder.select(
            SelectResult.expression(DBColumnNames.Meta_ID),
            SelectResult.property("MyContent"),
            SelectResult.property("MyType"),
            SelectResult.property("MyDate"),
            SelectResult.expression(Expression.property("MyId")),
            SelectResult.expression(Expression.property("OtherId"))
            )
            .from(DataSource.database(self.database!))
            .where(
                ArrayFunction.contains(Expression.property("deletedByUser"), value: Expression.string("My ID To Match")).is(Expression.boolean(false)
                    .or(Expression.property("deletedByUser").isNullOrMissing())
                    .and(Expression.property("type").equalTo(Expression.string("MyType")))
                    .and(Expression.property("MyId").equalTo(Expression.string("My ID To Match")).or(Expression.property("OtherId").equalTo(Expression.string("My ID To Match"))))
            )
            .orderBy(Ordering.property("MyDate").descending())
```

The above query is returning the results but do not include the document about which I mentioned above despite that document matches all the specified conditions in the query. The "deletedByUser" is an optional string array field in the document, meaning that it can or cannot exists. This query is trying to get those documents for which "deletedByUser" do not contains the "My ID To Match" value. Is there any issue with this query? I have ensured that this document do not contains the field "deletedByUser".

--------
* Version:   CBL 2.0.3
* Client OS: iOS 9.0

**Comment by snej** [comment]
There's something wrong with the grouping -- the `.is(...)` expression contains all of the three following lines, which doesn't make any sense. You probably need a few more right parens after `false)` at the end of that line.
