### ISSUE TITLE
CBL Swift 2.0: QueryBuilder's delete & update multiple documents

### ISSUE THREAD

**Issue by parvezq** [couchbase/couchbase-lite-ios#2181]
It will be helpful if we can have support for deleting or updating multiple documents through QueryBuilder by having Delete or Update command like Select. Using this option, one can write query to either update or delete multiple documents at once.

Thanks

**Comment by pasin** [comment]
The deleting and updating documents will be done via the Database API. We don't plan to have the Query command for deleting and updating the documents.

**Comment by snej** [comment]
It's pretty trivial to make a query that returns just the docID of each document, and then write a loop that deletes the docs with the returned IDs. This could be a shared utility function you use in multiple places in your app.
