### ISSUE TITLE
2.0: Feature Request: allow creating Query from JSON

### ISSUE THREAD

**Issue by tommyo** [couchbase/couchbase-lite-ios#2182]
I'm writing a capacitor/cordova wrapper that exposes native methods to javascript rather than rely on the Listener. The only thing complicated is the Query building process. Exposing a method that allows me to submit a JSON query directly would avoid the unnecessary JSON string -> JSON object -> Query objects -> JSON string complexity.

**Comment by djpongh** [comment]
Moved to: https://issues.couchbase.com/browse/CBL-24
