### ISSUE TITLE
replication fails after resetCheckpoint on ios build 2.1.0-216

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-ios#2184]
### Environment
* Version:   2.1.0-216
* Client OS: iOS

### Steps to reproduce:
       1. create docs in cbl db1
       2. replicate docs to sg/cbl2 db with continous true and push replication
       3. purge docs in cbl db1
       4. replicate again using pull replicator
       5.Verify  purged docs should not get replicated
       6. stop replicator
       7. call reset api
       8. restart the replication using pull replicator

### Expected: 
       9. Verify all purged docs got back in CBL

### Result:
Got 0 docs in CBL

**Comment by pasin** [comment]
@sridevi-15 could you please enable the replicator logging and provide the log?

```
Database.setLogLevel(.info, domain: .replicator)
```

**Comment by sridevi-15** [comment]
It works now after I use same replicator as reset checkpoint .
