### ISSUE TITLE
p2p: Throwing an error revision id mismatch with push pull replicator

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-ios#2185]
### Environment: 
* Version:   2.1.0-223
* Client OS: ios
* Server:    sg = 2.1.0-114

### Steps to reproduce:
1. Create 10 docs on client 
2. Start server
3. Start client by giving server ip, port, server db name, client database
4. Start replication with continuous and push pull 
5. Wait until replication is idle
6. Verify docs got replicated

### Expected
It should not throw an error and replication should happen successfully

### Result:
It is throwing an error 409 : revision id mismatch. 

### gist:
https://gist.github.com/sridevi-15/17d3d39d6d70a8d8c5622bd75779e9a4

###Note:
It works fine with just push replicator

**Comment by pasin** [comment]
Somehow I couldn't reproduce this issue with the scenario above. 

From the log, it seems like there are more than one replicator (e.g. Repl#1, Repl#5 and Repl#9) running. Is it possible that there are more than one replicator running (all point to the same MessageEndpoint with a single UID)?

**Comment by sridevi-15** [comment]
I am testing with URL End Point.  I double checked my test and I see only one replicator is used.

**Comment by borrrden** [comment]
Among the first lines of the log are:

> 2018-07-24 15:07:07.315381-0700 CBLTestServer-iOS[23495:1357872] CouchbaseLite Sync Verbose: {DBWorker#2} Notified of 10 db changes #121 ... #130
2018-07-24 15:07:07.315604-0700 CBLTestServer-iOS[23495:1357870] CouchbaseLite Sync Verbose: {DBWorker#6} Notified of 10 db changes #121 ... #130

The log clearly shows two push replicators running at the same time.  Then after the call to clientStart there are three running.

**Comment by sridevi-15** [comment]
Tested with latest version. Looks like when I rerun the test, replicator with first run still running and causing the issue. After I strop the replicator and reran, it works fine.
