### ISSUE TITLE
Replication doesn't sync doc for upgrade from 1.4 to 2.1.0 for iOS

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-ios#2191]
I installed the app for 1.4 CBL (iOS) and created few docs. Docs are getting synced to both SG(1.5) and CBS(5.0). Then I upgrade the cluster to 2.1 (SG 2.1 and CBS 5.5) and also update CouchbaseLite Framework to 2.1 using the feature/2.0 branch. App gets deployed but the changes or new docs are not getting synced from CBL app (iOS) to SG and CBS.

Scenario Workflow -
1. Install 1.4 todo app with 1.5 cluster.
2. Create few docs and check if they are syncing to CBS and SG
3. Update CBS and SG to 5.5 cluster
4. Checkout feature/2.0 branch and deploy the todo app with 2.1.0-233 build.
5. Check that if any new docs created are syncing to CBS and SG. Also check the any mutation to old docs are also getting reflected to CBS and SG

CBL Logs are available here - 
https://gist.github.com/hrajput89/d4d07e130ea4c5e25293f56fef3f6749

**Comment by pasin** [comment]
From the log, the issue is `CBLWebSocket CLOSED WITH ERROR: NSOSStatusError[-9802]` which is not related to the upgrade. The error -9802 is `errSSLFatalAlert`. I'm not sure why it has that issue.

**Comment by pasin** [comment]
Just for confirmation. Can you use 2.1.0 alone instead of upgrade to see if it works?

**Comment by hrajput89** [comment]
I tried with 2.1 stand alone app and it was not able to replicate data to SG and CBS

**Comment by pasin** [comment]
Can you try quickly with CBL 2.0?

**Comment by hrajput89** [comment]
I tried with 2.0 also and I'm getting same issue. I also tried with cluster on different set of IPs but same result.

[sgcollect_info.zip](https://github.com/couchbase/couchbase-lite-ios/files/2261291/sgcollect_info.zip)

**Comment by pasin** [comment]
I believe the issue is about the configuration or environment, not the upgrade issue. Also we have done test fest on iOS, Android, and .NET yesterday and we don't see the same issue. Please check my comment above.
