### ISSUE TITLE
Use of undeclared identifier SHA_DIGEST_LENGTH in CBL_BlobStore

### ISSUE THREAD

**Issue by brendand** [couchbase/couchbase-lite-ios#2195]
When compiling the latest commit `dca2367e660083b4c15cc298f9fbbd6e66da3d46`, I get the error `Use of undeclared identifier SHA_DIGEST_LENGTH` when compiling the `CI MacOS` scheme in `CBL_BlobStore`.

It's a bit odd because `Security.framework` is linked and these are in the file:

#define COMMON_DIGEST_FOR_OPENSSL
#import <CommonCrypto/CommonDigest.h>

I know you don't support beta OS versions or beta Xcode versions, but since I saw some commits related to Xcode 10, I thought you'd be interested to know it won't compile for Mac at the moment.
 
--------
* Version:   1.4.x commit dca2367e660083b4c15cc298f9fbbd6e66da3d46
* Client OS: macOS Mojave 10.14, Xcode 10.
* Server:    n/a

**Comment by djpongh** [comment]
Thanks for the info. We have a 1.4.4 in the works and will look to get this in, depending on when Xcode 10 GA's. I did a quick search but couldn't find any dates.

**Comment by brendand** [comment]
@djpongh Also try compiling with the New Build System in Xcode 10. I believe there are a bunch of deprecated symbols that popup when you do that. They get marked as errors now rather than warnings. I had to switch to the Legacy Build System to get it to compile.
