### ISSUE TITLE
Can not delete database.

### ISSUE THREAD

**Issue by nuxzero** [couchbase/couchbase-lite-ios#2198]
I tried to delete the database but doesn't work. I didn't use Sync Gatway I think should not have problem with `Replication `.

 Error log:

```
CouchbaseLiteException{domain='CouchbaseLite', code=16, msg=Can't delete db file while other connections are open}
at com.couchbase.lite.CBLStatus.convertException(CBLStatus.java:49)
at com.couchbase.lite.CBLStatus.convertException(CBLStatus.java:55)
at com.couchbase.lite.AbstractDatabase.deleteC4DB(AbstractDatabase.java:871)
at com.couchbase.lite.AbstractDatabase.delete(AbstractDatabase.java:489)
at com.couchbase.lite.Database.delete(Database.java:25)
```

My code:

``` 
try {
            database.delete()
            database.close()
            this.database = null
        } catch (e: CouchbaseLiteException) {

        }
```
--------
* Version:   2.0.0
* Client OS: Android
* Server:    -

**Comment by mohsinsurani1** [comment]
Same problem I got in iOS 12.0 too. Did you find any solution to this?

**Comment by jayahariv** [comment]
@mohsinsurani1 could you try enabling the logs, and share it, when the issue happens? [docs](https://docs.couchbase.com/couchbase-lite/2.5/swift.html#logging)

**Comment by mohsinsurani1** [comment]
When I try to delete db, It throws an error saying:
 "Error Domain=CouchbaseLite Code=16 "Can't delete db file while other connections are open" UserInfo={NSLocalizedDescription=Can't delete db file while other connections are open}
"

I have removed all change listeners and still its showing same error.

**Comment by jayahariv** [comment]
We need more logs, not just the error message. Could you please follow the link shared earlier and (a)enable logs(like below), (b)run the app and create the issue, (c)copy the full console logs, and (d)share it with us. 

#### Enable logging
```
// deprecated in 2.5 
Database.setLogLevel(.verbose, domain: .all)

// OR 

Database.log.file.domain = .all
Database.log.file.level = .verbose

```

**Comment by mohsinsurani1** [comment]
I got that files in temporary directory but Im not able to open it in cbl-log. cbl-log is saying "missing subcommands". How to get logs in it?

**Comment by ptitnorm** [comment]
Same here!

**Comment by jayahariv** [comment]
In general, make sure all listener which are added, is properly removed or if replicators are started, stop before closing the database. 

If you are cleanly removing all and is still getting errors, enable the logs and attach **full logs**, not part of it. We need to look at all the events happened before closing the database. Which connection is still open, and if any error happened before this etc. 

If you are an enterprise customer, you could ask for help from our Couchbase Support team. For community, you can post your logs here, or send email(if logs include sensitive data) directly to me(jayahari.vavachan@couchbase.com)
