### ISSUE TITLE
Access issue.

### ISSUE THREAD

**Issue by SergeyBulyno** [couchbase/couchbase-lite-ios#2200]
Hi today I try install CouchbaseLite via cocoa pod and receive error:
Error installing CouchbaseLite
[!] /usr/bin/curl -f -L -o /var/folders/bq/9tzw48js2297cql95ml6rjvr0000gn/T/d20180907-43778-t6vt5m/file.zip https://packages.couchbase.com/releases/couchbase-lite-ios/2.0.3/couchbase-lite-objc_community_2.0.3.zip --create-dirs --netrc-optional
curl: (22) The requested URL returned error: 403 

 The Amazon CloudFront distribution is configured to block access from your country. 

Could you help me with this issue ? 
--------
* Version:  2.0.3

**Comment by djpongh** [comment]
What country are you in?

**Comment by SergeyBulyno** [comment]
Belarus

**Comment by pasin** [comment]
@rajagp Can you help checking about this issue?

**Comment by djpongh** [comment]
Looks like Belarus is blocked due to U.S. export restrictions.
