### ISSUE TITLE
CBLReplication filter nor work

### ISSUE THREAD

**Issue by suzhaev** [couchbase/couchbase-lite-ios#2201]
I'm trying to use CBLReplication filter property like this:

```
CBLReplication *pull = [database createPullReplication:url];
pull.filter = @"client/staff";
pull.continuous = YES;
[pull start];
```
I have filter design document on server couch.
In this case replication don't work, and request always "Waiting for response" in Charles

<img width="1347" alt="2018-09-09 3 52 41" src="https://user-images.githubusercontent.com/19522238/45260031-5ed91300-b3e4-11e8-877b-b8a87c7296df.png">

If I set breakpoint on this request in Charles, and clear request body(screenshot), and then execute (leave the parameters only in the URL)

<img width="822" alt="2018-09-09 3 53 14" src="https://user-images.githubusercontent.com/19522238/45260034-6f898900-b3e4-11e8-9a27-c250710577a5.png">

replication works fine and filter applies too.

<img width="1196" alt="2018-09-09 3 53 47" src="https://user-images.githubusercontent.com/19522238/45260037-8cbe5780-b3e4-11e8-9c2d-a922953b8f7f.png">
<img width="1266" alt="2018-09-09 3 53 52" src="https://user-images.githubusercontent.com/19522238/45260038-8cbe5780-b3e4-11e8-9e9d-7e961bf39e1f.png">

--------
* Version:   1.4.1
* Client OS: iOS
* Server:    Apache CouchDB 2.2.0

**Comment by suzhaev** [comment]
You can check it via CURL

Not work:
`curl -H 'Content-Type: application/json' -H 'User-Agent: CouchbaseLite/1.3 (iOS 1.4.1/86c63659b56d87406eac3b1e4db631fe67098139)' --data-binary '{"accept_encoding":"gzip","feed":"normal","heartbeat":300000,"style":"all_docs","active_only":true,"filter":"client\/staff"}' --compressed 'http://XXXX:XXXX@127.0.0.1:5984/**db_name**/_changes?feed=normal&heartbeat=300000&style=all_docs&active_only=true&filter=**filter**'`


This works fine:
`curl --header "Content-Type: application/json"  --request POST http://XXXX:XXXX@127.0.0.1:5984/**db_name**/_changes?filter=**filter**`

**Comment by pasin** [comment]
@suzhaev This seems to be compatibility issue with CouchDB. Does CouchDB ignore the filter when filter is in the Body? Can you check with CouchDB?

**Comment by pasin** [comment]
We have also done some changes to support CouchDB POST changes in #1139. Are there any changes lately with CouchDB 2.2.0?

**Comment by pasin** [comment]
Please feel free to reopen the issue when there is updated info. Thanks.
