### ISSUE TITLE
Add Replicator backgrounding functional tests

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#2203]
Scenario 1: Replicator continues working util idle or stopped (single shot) or the suspended by OS when the app goes into background and/or locked screen.
1. Start a replicator and make sure that the replicator is actively working.
2. Bring the app into background and locked screen.
3. Wait for a good amount of time that the replication should be done.
4. Bring the app to foreground, make sure that the continuous replicator wakes up or the single shot replicator stopped.
5. Verify that the replication was done.

Scenario 2: Start a new replication while the app is in background / locked screen
1. Bring the app into background and locked screen. Wait for at least 10 seconds.
2. Send a silent push notification to start a new replicator.
3. Make sure that the replicator starts and finish replication

The scenarios are applicable for both CBL 1.4 and 2.1.

**Comment by pasin** [comment]
CC: @sridevi-15

**Comment by pasin** [comment]
@hrajput89 @sridevi-15 

I have created [BackgroundTest](https://www.dropbox.com/s/qzjzl7ho0khupgv/BackgroundTest.zip?dl=0) sample app that starts a single shot replication when receiving a silent push notification. Please see README.md for more info.

**Comment by rajagp** [comment]
I think it would be simpler to use background fetch instead of silent notification ..you can do it using simulator itself .

**Comment by pasin** [comment]
I understood that background fetch doesn’t run when the app is under locked screen but if that’s not the case and simulator can trigger bg fetch under locked screen, then pls use bg fetch instead.

**Comment by pasin** [comment]
Also, regardless of using push notification or background fetch, the test should be done on device as simulator doesn't have data protection enabled when the app is under the locked screen.

**Comment by pasin** [comment]
I have added sync with push notification feature to https://github.com/couchbaselabs/mobile-training-todo for both 1.x and 2.0. QE can use it for testing. I'm closing this issue now.

**Comment by pasin** [comment]
How to use push notification sync in mobile-training-todo:

1. Enable push notification sync by kSyncWithPushNotification in AppDelegate to YES.
2. When running the app, after logging in, the device token ID used for pushing notifications will be printed out to console.
3. Use Script/push to send the notification.

**Comment by srinadh-k** [comment]
@pasin  can we use silent push notification for wakeup or restart our replication when replication stopped?

**Comment by pasin** [comment]
Yes.

**Comment by srinadh-k** [comment]
> Yes.

Thank you, Can you please send a documentation link to implement in my application.
