### ISSUE TITLE
Carthage support for xcode 10 swift 4.2

### ISSUE THREAD

**Issue by callo90** [couchbase/couchbase-lite-ios#2204]
Please update carthage support for xcode 10 and swift 4.2.

```Incompatible Swift version - framework was built with 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2) and the local version is 4.2 (swiftlang-1000.11.37.1 clang-1000.11.45.1)```

--------
* Client OS: 2.0.3

**Comment by pasin** [comment]
CBL 2.1.1 Carthage has been released.
