### ISSUE TITLE
No available version for binary

### ISSUE THREAD

**Issue by johnngoi** [couchbase/couchbase-lite-ios#2207]
*** Downloading binary-only framework CouchbaseLite-Enterprise at "https://packages.couchbase.com/releases/couchbase-lite-ios/carthage/CouchbaseLite-Enterprise.json"
No available version for binary "https://packages.couchbase.com/releases/couchbase-lite-ios/carthage/CouchbaseLite-Enterprise.json" satisfies the requirement: ~> 2.1.1

--------
* Version:   2.1.1
* Client OS: iOS 12
* Server:    NAME_AND_VERSION

**Comment by johnngoi** [comment]
I can download these links from Safari.

https://packages.couchbase.com/releases/couchbase-lite-ios/carthage/CouchbaseLite-Enterprise.json
https://packages.couchbase.com/releases/couchbase-lite-ios/2.1.1/couchbase-lite-carthage-enterprise-2.1.1.zip

I also copy/paste ...
```
binary "https://packages.couchbase.com/releases/couchbase-lite-ios/carthage/CouchbaseLite-Enterprise.json" ~> 2.1.1
```
...  same problem with `carthage update`

```
binary "https://packages.couchbase.com/releases/couchbase-lite-ios/carthage/CouchbaseLite-Enterprise.json" ~> 2.1.0
```
works fine

More info

Xcode 9.4.1
macOS 10.13.6 (High Sierra)
carthage version 0.30.1

**Comment by pasin** [comment]
My carthage version is 0.25. Let me upgrade and test.

**Comment by pasin** [comment]
I upgraded Carthage to v.0.30.1 and it worked for me. I used XCode 10 but I don't think it's related to the version of XCode.

@rajagp Can you try it out and see if you are seeing the same issue?

**Comment by rajagp** [comment]
@johnngoi Can you elaborate on what errors you are seeing. Please use verbose version and output the exact errors
`carthage update --verbose`


I couldn't install because I don't have xcode 10 on my system but I don't see the issue you indicated (because the fact that its complaining about incompatible swift version means that it was able to locate the 2.1.1 binaries and attempted to download 2.1.1)

**Comment by pasin** [comment]
Based on [this](https://stackoverflow.com/questions/46346743/carthage-error-no-available-version-for-binary) and [this](https://github.com/Carthage/Carthage/issues/1871). Delete the carthage's cache might solve the issue.

```
rm -rf ~/Library/Caches/org.carthage.CarthageKit/
rm -rf ~/Library/Caches/carthage/
```

**Comment by johnngoi** [comment]
doing this

```
rm -rf ~/Library/Caches/org.carthage.CarthageKit/
rm -rf ~/Library/Caches/carthage/
```

changed the problem.

```
carthage update --verbose
*** Downloading binary-only framework CouchbaseLite-Enterprise at "https://packages.couchbase.com/releases/couchbase-lite-ios/carthage/CouchbaseLite-Enterprise.json"
*** Downloading binary-only framework CouchbaseLite-Enterprise at "https://packages.couchbase.com/releases/couchbase-lite-ios/carthage/CouchbaseLite-Enterprise.json"
Incompatible Swift version - framework was built with 4.2 (swiftlang-1000.11.37.1 clang-1000.11.45.1) and the local version is 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2).
```

not really an issue for us in this instance, because we tend to push forward pretty quickly (will be at Swift 4.2 by end of month), but may be an issue for other slower Enterprise dev shops

**Comment by johnngoi** [comment]
@pasin also open to testing `carthage update` if you do have a solution for Swift 4.1.2 and giving feedback

**Comment by rajagp** [comment]
Looks like this is downloading as expected so appears to no longer be an issue. If you need 4.1.2, you can build from source - [this link](https://github.com/couchbase/couchbase-lite-ios/wiki/Building-Couchbase-Lite) will help you- there are some caveats if you need EE version

We currently  only support distributing prebuilt binaries corresponding to latest GA version of swift. Unfortunately, swift's lack of ABI stability makes this quite cumbersome for users.  Hopefully. that gets resolved with swift soon!.

**Comment by pasin** [comment]
@johnngoi It's the Carthage that checks the version compatibility (See [this](https://github.com/Carthage/Carthage/issues/2411) for more info). Swift 4.2 is generally compatible with 4.1.2. I don't have a workaround this. Also EE is closed source so building from source is not possible either.

**Comment by johnngoi** [comment]
Thanks for all the help. Now that we are at a known acceptable state, no need to spend more cycles looking into it. 

I’ll open a new issue if this does not work with Swift 4.2 via carthage update.
