### ISSUE TITLE
 CBLite 2.0 and it getting crashed randomly

### ISSUE THREAD

**Issue by shobhakartiwari** [couchbase/couchbase-lite-ios#2209]
--------
* Version:   cblite 2.0
* Client OS: iOS 11

I am using CBLite 2.0 and it getting crashed randomly , kindly help in resolving this issue :

terminating with uncaught exception of type std::__1: (worry) ystem_error: mutex lock failed: Invalid argument

**Comment by pasin** [comment]
Could you please provide the full stacktrace of all threads? Also there are several changes from 2.0 to 2.1. You may try to upgrade CBL and see if the crash still persists.

**Comment by djpongh** [comment]
@shobhakartiwari , any update?

**Comment by djpongh** [comment]
If you can get us more info, please re-open.

**Comment by shobhakartiwari** [comment]
i applog. for late response , here is the screenshot for this random crash.
<img width="1002" alt="screen shot 2018-10-09 at 4 46 05 pm" src="https://user-images.githubusercontent.com/13196077/46951914-fcd89100-d0a6-11e8-8230-0861c07c8e6f.png">

**Comment by snej** [comment]
This looks very much like a bug that was fixed in 2.1. Please upgrade, and if you still see the problem, comment here and we'll reopen the issue.

**Comment by shobhakartiwari** [comment]
Thanks for the update Snej , let me update to 2.1, Thanks for your support.
