### ISSUE TITLE
Carthage JSON broken

### ISSUE THREAD

**Issue by btyler** [couchbase/couchbase-lite-ios#2212]
Unable to parse binary-only framework JSON at https://raw.githubusercontent.com/couchbase/couchbase-lite-ios/master/Release/Carthage/CouchbaseLite-Community.json due to error: invalid JSON: dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.})))

**Comment by pasin** [comment]
Please use this instead:

```
binary "https://packages.couchbase.com/releases/couchbase-lite-ios/carthage/CouchbaseLite-Community.json" ~> 21.1
```
