### ISSUE TITLE
Support Swift Package Manager

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#2214]
It's not clear yet what we need to do to support Swift Package Manager but it's something we should look into that.

--------
* Version:   2.x

**Comment by pasin** [comment]
The first goal is to see what we need to restructure the current couchbase-lite-ios repo to support Swift Package Manager including how to link with LiteCore target.

**Comment by djpongh** [comment]
Moved to: https://issues.couchbase.com/browse/CBL-274

**Comment by iamlogiq** [comment]
Any update on when support for SPM will be added?

**Comment by marcblanchet** [comment]
+3

**Comment by joehinkle11** [comment]
+1 any updates?

**Comment by callo90** [comment]
Guys, SPM is adding support for binary frameworks, you might consider adding support.

https://github.com/apple/swift-evolution/blob/master/proposals/0272-swiftpm-binary-dependencies.md
https://developer.apple.com/videos/play/wwdc2020/10147/

**Comment by marcblanchet** [comment]
any update? nowadays, most packages are managed by SPM and it is 100% easier.
