### ISSUE TITLE
Performance and indeces for queries in "tables"

### ISSUE THREAD

**Issue by skela** [couchbase/couchbase-lite-ios#2215]
Its not clear from the documentation so I'm just posting the question here. So not really an issue apart from a need to flesh this bit out a bit in the docu.

All my documents have document ids of the same form: `{table_name}|{record_id}`
so for example: `users|1`
All the documents with the same document id prefix before | belong to the same "table".
Most of my queries occur in these tables, which means in couchbase lite 2 I do this in almost all my queries:
        
        let tableName = "users"
        let selection = QueryBuilder.select(SelectResult.expression(Meta.id))        
        let whereq = Meta.id.greaterThanOrEqualTo(Expression.string(tableName + "|")).and(Meta.id.lessThan(Expression.string(tableName+"}")))
        let query = selection.from(DataSource.database(database)).where(whereq)

Is there any value in me creating an index for the document ids then, since I do this alot, or is this already present? so for instance an index like this: `IndexBuilder.valueIndex(items:ValueIndexItem.expression(Meta.id)`

If I do more complex queries, say in the users table for users with a particular name, and I need the speed, do I need to then create yet another index that includes both the Meta Id and the property for name? in the same index?
Or should I create 1 index with the id, and 1 separate index with just the name property?

Do you think it's faster to for example add a field called "table" to all the documents, and then do the indexed queries that way for all documents of a particular table?

If I go back to my previous example of finding all users of a particular name, in the users table, and I've got this "table" field , with table index, do I need to have 2 indexes, or a combined index to have any performance improvement?

--------
* Version:   2.1.1
* Client OS: iOS 12

**Comment by snej** [comment]
We prefer the forum for questions.

There is already an index on the document ID, which will be used for greater/less comparisons. (It might even be used for `LIKE tableName + "|"` expressions, depending on how smart SQLite's query optimizer is.) So you don't need to add one.

If you want to add a test for a name property, then you'd want to create an index on docID and name (in that order.) A separate index on just the name _might_ help somewhat (depending on the query optimizer , and on the number of docs in the database) but it might not, and would never be as good as the combined index.

The `Query.explanation` property is your friend here. If you learn what it's saying, it can tell you how efficiently the query will run. (See the SQLite docs for "EXPLAIN QUERY PLAN".)
