### ISSUE TITLE
Full-Text Search prefix queries are not working properly in some cases

### ISSUE THREAD

**Issue by stas9019** [couchbase/couchbase-lite-ios#2217]
For query "'\*alterna\*'" FTS search finding the only word "alterna-porn", however, it should also match  "alternate", "alternative", "alternating" etc. I have no matches for "'*alternat*'" as well.

However, for query "'\*altern\*'" I see expected results, including "alternate", "alternative", "alternating".  Also, for  "'\*alternate\*'" I see exprected "alternate", "alternately".

I am creating the index in the following way. Probably it caused by English language stemmer.

```
let headwordFTSIndex = IndexBuilder
                .fullTextIndex(items:
                    FullTextIndexItem.property(Headword.Keys.headword.stringValue),
                    FullTextIndexItem.property(Headword.Keys.associated.stringValue)
                )
                .language("en")
                .ignoreAccents(true)
 try database.createIndex(headwordFTSIndex, withName: Index.FTS.Headword)
```

--------
* Version:   2.1.1 Community Edition
* Client OS: iOS 11/12

**Comment by snej** [comment]
This issue was moved to couchbase/couchbase-lite-core#593
