### ISSUE TITLE
Logging redirect is missing for 2.X

### ISSUE THREAD

**Issue by timritzer** [couchbase/couchbase-lite-ios#2221]
The 1.X branch of code offered a method on CBLManager (CBLManager.redirectLogging) That allowed redirecting the logging to be used by the developer for problems in the field (without access to the device).
We built infrastructure that allowed that logging to be uploaded to troubleshoot issues.

[CBLog.m](https://github.com/couchbase/couchbase-lite-ios/blob/master/Objective-C/Internal/CBLLog.m) features a logging callback, and the underlying couchbase-lite-core supports it well, however the set callback method isn't exposed anymore. (c4log_writeToCallback specifically)

Overwriting the default log callback is an important use case for troubleshooting field devices, but I no longer see a way to call it without a custom build (Something I hesitate to do because it makes EE support less straightforward.

--------
* Version:   Couchbase Lite Swift 2.1
* Client OS: iOS 12
* Server:    N/A

**Comment by pasin** [comment]
Thanks for the feedback. CC: @rajagp

**Comment by rajagp** [comment]
@timritzer  This is under consideration for our next major release (2.5).

**Comment by snej** [comment]
We are also working on an API that lets CBL generate a log file itself, but exposes the path of the file so the app can upload it. The advantage of that is that the log file is written in a very efficient/compact binary format (which can be decoded by the `cblite` tool), and CBL will take care of rotating out old log files.

**Comment by pasin** [comment]
Let's track this in https://github.com/couchbase/couchbase-lite-ios/issues/1955.
