### ISSUE TITLE
Support N1QL syntax for queries

### ISSUE THREAD

**Issue by geraldapeoples** [couchbase/couchbase-lite-ios#2222]
--------
* Client OS: Android/IOS

Are there any plans to enable couchbase lite queries using the n1ql query language? The use of the querybuilder seems very, very complicated compared to "SELECT model from mydb t where t.type = 'vehicle'"

**Comment by snej** [comment]
We don't have plans to. The thinking is that the builder API enforces enough structure at compile time to keep people from making most types of ill-formed queries, which helps with support. I do understand your complaint about verbosity, though, and I hope we can address that somehow.

(A secondary reason is that this would require writing a new N1QL parser in C or C++ — the Server one is written in Go, which we can't use in mobile. Not rocket science, but a nontrivial amount of work.)

**Comment by geraldapeoples** [comment]
I am coming from the Ionic/Cordova mindset here ... if we could define all of our queries in javascript as n1ql strings and pass them into the plugin it would simplify things so much, as it is, it looks like the cordova plugin itself will have to be support some simplified query syntax ... can't be helped I guess. Thanks for the explanation though.

**Comment by snej** [comment]
Right, that's #2219 which is in review right now.

IIRC, Couchbase has a N1QL parser written in JavaScript, which is used in the Server admin app. One could adapt that to output the JSON query schema used by LiteCore, which is very similar to a parse tree.

**Comment by timritzer** [comment]
On iOS at least, heavy extensions can make this very much less verbose. For example:

`extension Array where Element: queryExpressionable {
    public func asExpression() -> [ExpressionProtocol] {
        return self.map { $0.asExpression() }
    }
}

public protocol queryExpressionable {
    func asExpression() -> ExpressionProtocol
}

//Or Whatever type
extension String: queryExpressionable {
    public func asExpression() -> ExpressionProtocol {
        return Expression.string(self)
    }
}

extension Database {
    public var dataSource: DataSourceAs {
        return DataSource.database(self)
    }
}
`

This lets your queries look more normal such as

`let query = QueryBuilder.select(SelectResult.all())
                        .from(db.dataSource)
                        .where(Expression.property("type").equalTo("vehicle".asExpression()))`

We even went as far as to make static fields for our properties we referenced often, so it ends up even cleaner than that. Overall I think if you work at it you can make it pretty clean without too much trouble.

**Comment by geraldapeoples** [comment]
@snej Hi ... how would I get a hold of the N1QL javascript parser?

**Comment by snej** [comment]
@geraldapeoples Sorry, I can't remember what repo it's in — somewhere in `couchbase/` or `couchbaselabs/`.

**Comment by davisford** [comment]
> On iOS at least, heavy extensions can make this very much less verbose. For example:
> 
> ```
> extension Array where Element: queryExpressionable {
>     public func asExpression() -> [ExpressionProtocol] {
>         return self.map { $0.asExpression() }
>     }
> }
> 
> public protocol queryExpressionable {
>     func asExpression() -> ExpressionProtocol
> }
> 
> extension String: queryExpressionable {
>     public func asExpression() -> ExpressionProtocol {
>         return Expression.string(self)
>     }
> }
> 
> extension Database {
>     public var dataSource: DataSourceAs {
>         return DataSource.database(self)
>     }
> }
> ```
> This lets your queries look more normal such as
> 
> ```
> let query = QueryBuilder.select(SelectResult.all())
>                         .from(db.dataSource)
>                         .where(Expression.property("type")
>                                          .equalTo("vehicle".asExpression()))
> ```
> We even went as far as to make static fields for our properties we referenced often, so it ends up even cleaner than that. Overall I think if you work at it you can make it pretty clean without too much trouble.

Hi @timritzer -- would you be willing to share your extensions?  I'd be super interested in that!

**Comment by chinhnguyen** [comment]
Is it possible to have an online compiler that transfer N1QL to native QueryBuilder? 
Something like `SELECT *` to `QueryBuilder.select(SelectResult.all())` for Swift.

**Comment by timritzer** [comment]
Sorry @davisford it was written at my last company, and it would be illegal for me to share them. But the gist is what I did post, just added on for arrays, and other operations

@chinhnguyen It would totally be possible to do so with Swift's new support for DSL's, You could write a DSL that was N1QL, that translated into Swift QueryBuilder syntax. That would be really cool! You should look into writing that! I would certainly love to contribute to a project like that.

**Comment by snej** [comment]
> You could write a DSL that was N1QL, that translated into Swift QueryBuilder syntax

Swift does _not_ let you embed a totally foreign language like N1QL. The feature you're talking about is some small changes that allow you to write Swift expressions one-per-line whose results get combined into collections. It's very useful for things like describing view layouts, but it's nothing like N1QL.

**Comment by timritzer** [comment]
@snej  I'm talking about this DSL language feature https://forums.swift.org/t/function-builders/25167
(https://github.com/apple/swift-evolution/blob/9992cf3c11c2d5e0ea20bee98657d93902d5b174/proposals/XXXX-function-builders.md)
 added to support SwiftUI. It allows pretty cool transformation of any Domain Specific Language (ignored by the compiler) into proper swift code.

Seeing as you can write full HTML inside swift (somebody flushed out that example as an open source project) I don't see why you couldn't make it work with about any language you wanted. I am certainly not saying it would be easy as even after defining the DSL you would need lots of parsing logic, but certainly not impossible. And technically N1QL is a DSL of sorts (Arguable on the domain I suppose, but still)

You would as you noted, likely have a better time of it if you made some restrictions about lines. But again doesn't seem impossible.

**Comment by snej** [comment]
@timritzer Yes, I've read that spec. It doesn't transform arbitrary languages, and the compiler is not ignoring anything. From the spec:

>This proposal does not aim to enable all kinds of embedded DSL in Swift. It is focused on one specific class of problem that can be significantly improved with the use of a DSL: creating lists and trees of (typically) heterogenous data from regular patterns.

This feature lets you write a series of Swift expressions and will then combine them together. One example from the spec is an HTML DOM. But this requires Swift functions with names like `p` and `em` that takes parameters in parenthesized Swift syntax ... so it's not HTML syntax.

**Comment by snej** [comment]
If you want to see what something like N1QL would look like in something like Swift syntax, take a look at .NET's [LINQ](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/). This is the direction I'd like to go in: instead of gluing an entirely different language inside Swift, create a library that lets you query a database using recognizable idiomatic Swift functions like `map` and `filter`.

**Comment by timritzer** [comment]
@snej I see what you are saying now, and I agree. And I use LINQ regularly, and the fluent API nature of it would work very well within the Functional side of swift. Especially with Combine and similar APIs that have been released further building on that.

I could see Combine + LiveQueries + N1QL allowing for front to back data binding with live updates and almost no "glue" code in between. Especially with a LINQ like query syntax. Would be incredibly slick.

**Comment by chinhnguyen** [comment]
Thanks @timritzer, @snej for the inputs. I would then take it that there is no existing tool to make writing N1QL simpler in Swift and C#. And we should try to map queries into whatever we have right now. That's really sucks giving that I have a query like this 

`
SELECT SUM(approvedAmount) AS total,
             SUM(tipAmount) AS tip,
             COUNT(1) AS count,
             date,
             shift_index shift,
             transType trans_type, 
             cardType card_type
      FROM db
      LET approvedAmount = CASE
                      WHEN status="voided" OR status="voided-settled" THEN 0  
                      WHEN trans_type="credit_refund" THEN -approved_amount
                      ELSE approved_amount                      
                      END, 
          tipAmount = CASE 
                      WHEN status="voided" OR status="voided-settled" THEN 0 
                      WHEN trans_type="credit_refund" THEN -tip_amount
                      ELSE tip_amount 
                      END,
          date = SUBSTR(shift, 0, 6),
          transType = trans_type || 
                      (CASE WHEN trans_type="custom" THEN "$" || custom_trans_type || "$" || custom_trans_type_name ELSE "" END) ||
                      (CASE WHEN sub_payment_type="" THEN "" ELSE "$" || sub_payment_type || "$" || sub_payment_type_name END),      
          cardType = CASE WHEN card_type IS MISSING THEN "" ELSE card_type END
      WHERE type="transaction"
      AND deleted IS MISSING
      AND storeid="abc"
      AND trans_num > 0
      AND trans_type!="batch_close"
      GROUP BY 
        date,
        shift_index,
        transType,
        cardType
      ORDER BY 
        date, 
        shift_index, 
        transType, 
        cardType
`

**Comment by snej** [comment]
We do have a N1QL parser in the latest couchbase-lite-core (master branch). But there's no public API for it in Couchbase Lite yet. We will have to make an API design decision whether to add it, and what the public API should look like.

(The parser was added for the upcoming Couchbase Lite For C, because it doesn't make sense to port the fluent query API to C; it would be a mess. The question is whether to support it on other platforms too. I'm strongly in favor, but we need an official decision.)

**Comment by chinhnguyen** [comment]
@snej  thanks for the valuable information. We are on our way to migrate from Map/Reduce to N1QL, this is done without much effort on Couchbase Server, however on Couchbase Lite side it's a bit hard for us. Any idea about a rough timeline for this support?

**Comment by snej** [comment]
No timeline yet; it needs an official API spec & review, which @pasin is in charge of...

**Comment by klische** [comment]
> We don't have plans to. The thinking is that the builder API enforces enough structure at compile time to keep people from making most types of ill-formed queries, which helps with support. I do understand your complaint about verbosity, though, and I hope we can address that somehow.
> 
> (A secondary reason is that this would require writing a new N1QL parser in C or C++ — the Server one is written in Go, which we can't use in mobile. Not rocket science, but a nontrivial amount of work.)



> We do have a N1QL parser in the latest couchbase-lite-core (master branch). But there's no public API for it in Couchbase Lite yet. We will have to make an API design decision whether to add it, and what the public API should look like.
> 
> (The parser was added for the upcoming Couchbase Lite For C, because it doesn't make sense to port the fluent query API to C; it would be a mess. The question is whether to support it on other platforms too. I'm strongly in favor, but we need an official decision.)

To see if I understand correctly, it seems like the builder API emits N1QL to couchbase-lite-core? If not, what does it emit in order to execute the queries?

Thanks

**Comment by chinhnguyen** [comment]
@klische I suppose the QueryBuilder is emitting [JSON Query Scheme](https://github.com/couchbase/couchbase-lite-core/wiki/JSON-Query-Schema)

**Comment by jayahariv** [comment]
tracking this here [CBL-432](https://issues.couchbase.com/browse/CBL-432)

**Comment by jayahariv** [comment]
closing this from GH, and will be tracked in Jira.
