### ISSUE TITLE
Predictive Query API

### ISSUE THREAD

**Issue by djpongh** [couchbase/couchbase-lite-ios#2223]
**PRD**
1. https://docs.google.com/document/d/1ydyIaXLYv9871qWDQYJontaee4xTZgOxMJuqXtzIv1Q/edit

**API Spec**
1. https://github.com/couchbaselabs/couchbase-lite-apiv2/pull/229

**LiteCore API**
1. https://github.com/couchbase/couchbase-lite-core/blob/master/C/include/c4PredictiveQuery.h
2. https://github.com/couchbase/couchbase-lite-core/blob/master/C/include/c4Query.h#L194
3. https://github.com/couchbase/couchbase-lite-core/blob/3927e66f5685ef1d7b320f0a55799a0236610ec8/LiteCore/tests/PredictiveQueryTest.cc

**Comment by pasin** [comment]
The Predictive Query API has been implemented in 691a275e8a1b4fe945c010e43969d3e9c1f1302d. 

The Predictive Index is still pending.
