### ISSUE TITLE
module compiled with Swift 4.1 cannot be imported by the Swift 4.2.1

### ISSUE THREAD

**Issue by gumbright** [couchbase/couchbase-lite-ios#2225]
`error: module compiled with Swift 4.1 cannot be imported by the Swift 4.2.1 compiler: /Users/xxx/Projects/iOS/crucible/couchbaseHack/couchbaseHack/CouchbaseLiteSwift.framework/Modules/CouchbaseLiteSwift.swiftmodule/x86_64.swiftmodule`

All current community lite frameworks from download and via carthage versions result in the above error when trying to build under Xcode 10.1. So assuming build is with version 4.1.  Is there going to be an update for Xcode 10 compatibility?

**Comment by gumbright** [comment]
This is same kind of issue as #2204, just for latest version

**Comment by pasin** [comment]
What version of CBL are you specifying? CBL 2.1.1 was compiled with XCode 10 so there shouldn't bet the issue.

**Comment by djpongh** [comment]
Perhaps an older version of CBL has been cached? If you get more info into what is happening, fell free to re-open.
