### ISSUE TITLE
Replication crash when the app comes back from the unlocked screen

### ISSUE THREAD

**Issue by srinadh-k** [couchbase/couchbase-lite-ios#2226]
I am using couchbase lite iOS SDK and while i am using app and replication is going on... When user tries to lock the phone and unlock it. App getting crash. 

Even user app running in background mode and lock the phone and unlock the phone. if user tap on the app, it is going to crash.

* Version:   Couchbase Lite iOS V2.1.1
* Client OS: iOS 12.0.1
* Server:    Couchbase Server 6.0

**Comment by pasin** [comment]
Could you provide the crash log?

**Comment by srinadh-k** [comment]
Please check the following attachment for crash log.
[App-2018-11-13-235608.crash.zip](https://github.com/couchbase/couchbase-lite-ios/files/2577521/App-2018-11-13-235608.crash.zip)

**Comment by pasin** [comment]
The crash log doesn't get symbolicated. If you download CBL framework from the website, there is also the symbol files that you can add to your project to get the crash log symbolicated. 

I think the easiest way is to run the app attached to XCode and get the crash log by using `bt all` on the console when the crash happens.

**Comment by srinadh-k** [comment]
I didn't download CBL Framework from the website and I have been using pod command.
PFA for the log from the console.
[crash log](https://github.com/couchbase/couchbase-lite-ios/files/2577552/crash.log)

**Comment by pasin** [comment]
Thank you very much for the new crash log.

**Comment by pasin** [comment]
From the crash log, it turns out this is the same issue as #2196 which is fixed by https://github.com/couchbase/couchbase-lite-ios/commit/b42cf2694db48006e790f28dcdebfec1e401b481.

@srinadh-k we have fixed the issue and the fix will be released in the next release which is 2.1.2.

**Comment by srinadh-k** [comment]
@pasin  sounds great, it was fixed. Do you know, when V2.1.2 release?

**Comment by pasin** [comment]
I don't have the release date. Currently v2.1.1 is in the QA process. I hope it will be released soon.

**Comment by srinadh-k** [comment]
ok, is V2.1.1 in QA process? but right now, Couchbase lite stable version is V2.1.1

When we download from the following a link, it is giving Couchbase Lite 2.1.x Enterprise
https://www.couchbase.com/downloads

**Comment by pasin** [comment]
You can select Community or Enterprise.

**Comment by srinadh-k** [comment]
You mentiond in the below link, it was fixed in V2.1.1, Did you miss this in V2.1.1 and will be available in V2.1.2?

https://github.com/couchbase/couchbase-lite-ios/issues/2196#issuecomment-416799755

**Comment by srinadh-k** [comment]
> You can select Community or Enterprise.

We are using Enterprise edition and downloaded frameworks through pod files.

**Comment by pasin** [comment]
It turned out we didn't make it in v2.1.1 cut off.

**Comment by pasin** [comment]
Sorry for confusion. I just updated my comment about version. It should be 2.1.2 not 2.1.1.

**Comment by srinadh-k** [comment]
> It turned out we didn't make it in v2.1.1 cut off.

Oh ok, But seems it is very important bug for every iOS developer, even most of applications are in AppStore. So if possible please release asap. or else give a chance to access development git branch and update our pod file.

Even synch not working when user goes to background mode and leave the application some time. is it cause because of this issue? If that is also cause with same issue, i wont raise a new bug ortherwise i will raise a new bug
