### ISSUE TITLE
Incompatible Swift version, Swift 4.2.1

### ISSUE THREAD

**Issue by johnngoi** [couchbase/couchbase-lite-ios#2230]
*** Downloading CouchbaseLite-Enterprise.framework binary at "2.1.2"
Incompatible Swift version - framework was built with 4.2 (swiftlang-1000.11.37.1 clang-1000.11.45.1) and the local version is 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1).

Can we get a framework built with Swift 4.2.1?

--------
* Version:   2.1.2
* Client OS: NA
* Server:    NA

**Comment by pasin** [comment]
Sorry, I think this is the same issue as last time that Carthage really restricts to the exact Swift version.

**Comment by johnngoi** [comment]
@pasin we are using Carthage, let me know when you have something for us to test.

**Comment by pasin** [comment]
We have released v2.1.3 that was build with Swift 4.2.1.
