### ISSUE TITLE
No way to track CBL1->CBL2 Database Upgrade

### ISSUE THREAD

**Issue by skela** [couchbase/couchbase-lite-ios#2235]
I'm planning to move from Couchbase Lite 1.4 to 2.0. Did some initial testing with different database sizes, and I've run into a potential issue that I've found no way to work around.

When I start the application with CBL2, for the first time, I get log messages like:
Upgrader upgrading db
Upgrading CBL 1.x database

Fair enough, it needs to update the database from v1 to v2. However, this is taking upwards of 2 minutes, and in some cases up to 5 minutes. It could potentially take more for massive databases. I'll need to show the user an upgrading database status page as the app is completely useless when its upgrading itself. So I'll need a way to track the database upgrade process. I've found no information in the forums or documentation about how to achieve this, nor can I find any way to do that that's obvious from the library code.

How do I detect the database upgrade procedure, and its progress so that I can inform the user what is going on? 
--------
* Version:   2.0
* Client OS: iOS 12.1

**Comment by pasin** [comment]
Currently we don't have API to track the progress. If database is large, it could take sometime to upgrade. Can you open 1.x database in the background, show some indicator, and hide the indicator when the database is successfully opened?

**Comment by skela** [comment]
Yeah sure I can, but I would certainly prefer some kind of indication as to how much time it will take. Having a spinning indicator for 2-5 minutes isn't really ideal UX. So no way then?

**Comment by pasin** [comment]
CC @rajagp

**Comment by skela** [comment]
Ok, if I can't have a way to track progress, I can live with that, but at the very least I do need to be able to detect that an upgrade is needed or imminent fore opening the database. This is so I can show a "Upgrading Database" type screen to the user (with an indeterminate progress bar, since i cant have progress). I've tried to infer it from what's on the filesystem without any luck, is there anything else I can do to detect whether the stuff on the filesystem is a CBL1 v1 database, that will need to update once I open the database?

**Comment by skela** [comment]
I think I've found a way, but please let me know if there's anything better you can think of.
Before opening the Couchbase lite database, I open it in a SQLite library (readonly). Using this library here: https://github.com/stephencelis/SQLite.swift
Once opened, I can check for the existence of a "views" table, which doesn't seem to be present in CBL2 databases. Am I getting warmer?

**Comment by lightandshadow68** [comment]
Do you have external, per-database settings, such as the URL of the database on disk? If so, one migration strategy is to add a flag that indicates if the database is currently in 2.x format. Older versions of your app will not have set this flag, which will indicate a migration will be required. New versions of your app should set this flag when creating a new database, which would be 2.x by default, or once a migration has completed.

**Comment by djpongh** [comment]
Moved to: https://issues.couchbase.com/browse/CBL-275
