### ISSUE TITLE
Encrypted 2.X DB in Shared Location causes app to immediately terminate on backgrounding

### ISSUE THREAD

**Issue by timritzer** [couchbase/couchbase-lite-ios#2241]
Scenario is an app within an IOS App group, accessing the group file location for a Database that is encrypted will cause the app to immediately terminate (SigKill) whenever it goes into the background. This means no apps on iOS can share encrypted databases with the updated CB 2.X codebase.

Does not occur on simulator, or when encryption is disabled. Also doesn't happen unless there is a DB in the shared file container.

Handled on the SQLCipher side with this issue:
https://github.com/sqlcipher/sqlcipher/issues/255

If we still used SQLCipher, we could just use that fix, but since the encryption is different in 2.X, I am not sure how to accomplish this.

Related Apple Documentation:
https://developer.apple.com/library/archive/technotes/tn2408/_index.html

**Recreation Steps**: Create an app with an app group, and place the CB Lite db in the shared location. Add a password to the DB, and deploy to device. Launch app, background it for any reason (Launch second app, web link, etc). SigKill with reason 9 will follow.

--------
* Version:   2.1
* Client OS: iOS 12
* Server:    Not Required to Recreate

**Comment by pasin** [comment]
We are using SQLite Encryption Extension for encryption. This might require SQLite to fix the issue.

**Comment by timritzer** [comment]
Adding a password to this should recreate the issue.
https://blog.couchbase.com/sharing-data-ios-app-extensions-sync-capability/

**Comment by timritzer** [comment]
I wondered what you guys switched to, good information @pasin . Let me know if you guys need anything else details wise. I think, based on the SQLCipher ticket, it revolved around the header fields added to store the Salt, etc. But I am not an expert in the headers on SQLite at all.

**Comment by pasin** [comment]
Let's track this in https://github.com/couchbase/couchbase-lite-core/issues/647.
