### ISSUE TITLE
Implement date/time function

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#2242]
PRD:

https://docs.google.com/document/d/1OFw2eE9EDpApMPD9H_AR86oVZ-DesCg0CHoz6BKQn5s

--------
* Version:   Iridium

**Comment by pasin** [comment]
Please file an issue on LiteCore.

**Comment by snej** [comment]
Did you find this in a unit test? Those kind of tests should be in LiteCore itself.

**Comment by snej** [comment]
Fixed in LiteCore.
