### ISSUE TITLE
View document in the ios app 

### ISSUE THREAD

**Issue by mandyyiuting** [couchbase/couchbase-lite-ios#2250]
If documents in couchbase lite is erased in a real ipad device, is there any way to view / prove documents in couchbase lite are all deleted ? 
or any suggestion we can view documents of couchbase lite in a real ipad device instead of using couchbase lite view in simulator?  

--------
* Version:   VERSION
* Client OS: NAME_AND_VERSION
* Server:    NAME_AND_VERSION

**Comment by rajagp** [comment]
Please post questions for clarifications to the [Dev Forums](https://forums.couchbase.com). Github is for bugs and feature requests .
