### ISSUE TITLE
CBLLiveQuery updateAfter: Crash

### ISSUE THREAD

**Issue by siva1513** [couchbase/couchbase-lite-ios#2251]
Crashed: com.apple.main-thread
0  libdispatch.dylib              0x1c2dbb7bc dispatch_after$VARIANT$armv81 + 260
1  CouchbaseLite                  0x10334d6cc -[CBLLiveQuery updateAfter:] (CBLLiveQuery.mm:181)
2  CouchbaseLite                  0x10334d5c0 -[CBLLiveQuery databaseChanged:] (CBLLiveQuery.mm:172)
3  CouchbaseLite                  0x10334dd90 __21-[CBLLiveQuery start]_block_invoke (CBLLiveQuery.mm:84)
4  libdispatch.dylib              0x1c2dd36c8 _dispatch_call_block_and_release + 24
5  libdispatch.dylib              0x1c2dd4484 _dispatch_client_callout + 16
6  libdispatch.dylib              0x1c2db3b44 _dispatch_main_queue_callback_4CF$VARIANT$armv81 + 1012
7  CoreFoundation                 0x1c332a1bc __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
8  CoreFoundation                 0x1c3325084 __CFRunLoopRun + 1964
9  CoreFoundation                 0x1c33245b8 CFRunLoopRunSpecific + 436
10 GraphicsServices               0x1c5598584 GSEventRunModal + 100
11 UIKitCore                      0x1f01ccbc8 UIApplicationMain + 212
12 NooorApp                       0x10058d478 main (main.m:14)
13 libdyld.dylib                  0x1c2de4b94 start + 4

**Comment by pasin** [comment]
Closed as duplicate with #2243.
