### ISSUE TITLE
CBLDatabase postDocumentChanged: Crash

### ISSUE THREAD

**Issue by siva1513** [couchbase/couchbase-lite-ios#2252]
Crashed: com.twitter.crashlytics.ios.exception
0  NooorApp                       0x105061198 CLSProcessRecordAllThreads + 4345319832
1  NooorApp                       0x105061658 CLSProcessRecordAllThreads + 4345321048
2  NooorApp                       0x105050ea8 CLSHandler + 4345253544
3  NooorApp                       0x10505f7a8 __CLSExceptionRecord_block_invoke + 4345313192
4  libdispatch.dylib              0x181868ae4 _dispatch_client_callout + 16
5  libdispatch.dylib              0x181871640 _dispatch_queue_barrier_sync_invoke_and_complete + 56
6  NooorApp                       0x10505f218 CLSExceptionRecord + 4345311768
7  NooorApp                       0x10505ed04 CLSTerminateHandler() + 4345310468
8  libc++abi.dylib                0x18112037c std::__terminate(void (*)()) + 16
9  libc++abi.dylib                0x181120400 std::terminate() + 84
10 CouchbaseLite                  0x107bf2f58 __35-[CBLDatabase postDocumentChanged:]_block_invoke (CBLDatabase.mm:778)
11 CouchbaseLite                  0x107c60954 c4socket_received (c4Socket.cc:258)
12 libdispatch.dylib              0x181868b24 _dispatch_call_block_and_release + 24
13 libdispatch.dylib              0x181868ae4 _dispatch_client_callout + 16
14 libdispatch.dylib              0x181872a38 _dispatch_queue_serial_drain$VARIANT$mp + 608
15 libdispatch.dylib              0x181873380 _dispatch_queue_invoke$VARIANT$mp + 336
16 libdispatch.dylib              0x181873d4c _dispatch_root_queue_drain_deferred_wlh$VARIANT$mp + 340
17 libdispatch.dylib              0x18187c11c _dispatch_workloop_worker_thread$VARIANT$mp + 668
18 libsystem_pthread.dylib        0x181b9be70 _pthread_wqthread + 860
19 libsystem_pthread.dylib        0x181b9bb08 start_wqthread + 4

**Comment by pasin** [comment]
Could you please provide more info about the crash?

1. What version of Couchbase Lite you are using?

2. Do you have scenarios that cause the crash?

**Comment by siva1513** [comment]
We are using Couchbase Lite  v 2.0.3
Crash occurs happen Build Configuration in release mode.  In debug mode we can't find any crashes.

**Comment by pasin** [comment]
We have fixed several crashes in v2.1.2 but this seems to be new. Just in case, Could you try with v2.1.3 and see if that helps?

**Comment by djpongh** [comment]
@siva1513, if you try with 2.1.3 and still have the issue, feel free to reopen this.
