### ISSUE TITLE
RefCounted.hh Crash

### ISSUE THREAD

**Issue by siva1513** [couchbase/couchbase-lite-ios#2253]
Crashed: Pull->ws:xxxx/db/_blipsync
0  CouchbaseLite                  0x106054b80 litecore::blip::Connection::~Connection() (RefCounted.hh:48)
1  CouchbaseLite                  0x106051ad8 litecore::actor::safelyCall(void () block_pointer) (GCDMailbox.cc:87)
2  CouchbaseLite                  0x106051a40 ___ZN8litecore5actor10GCDMailbox7enqueueEU13block_pointerFvvE_block_invoke (GCDMailbox.cc:123)
3  libdispatch.dylib              0x1c46a16c8 _dispatch_call_block_and_release + 24
4  libdispatch.dylib              0x1c46a2484 _dispatch_client_callout + 16
5  libdispatch.dylib              0x1c4649be0 _dispatch_lane_serial_drain$VARIANT$mp + 592
6  libdispatch.dylib              0x1c464a728 _dispatch_lane_invoke$VARIANT$mp + 432
7  libdispatch.dylib              0x1c4652ec8 _dispatch_workloop_worker_thread + 600
8  libsystem_pthread.dylib        0x1c48840dc _pthread_wqthread + 312
9  libsystem_pthread.dylib        0x1c4886cec start_wqthread + 4

**Comment by pasin** [comment]
Could you please provide more info about the crash?

What version of Couchbase Lite you are using?

Do you have scenarios that cause the crash?

**Comment by pasin** [comment]
Please try with v2.1.2 or v2.1.3 (latest). We have fixed several WebSocket crash issues in v2.1.2. I understand that this is one of them. If the issue still persists, we could reopen the issue. Thanks.
