### ISSUE TITLE
Logging.hh Crash

### ISSUE THREAD

**Issue by siva1513** [couchbase/couchbase-lite-ios#2254]
Crashed: BLIP[->ws:xxxx/db/_blipsync]
0  CouchbaseLite                  0x103734240 litecore::blip::MessageIn::receivedFrame(litecore::blip::Codec&, fleece::slice, litecore::blip::FrameFlags) (Logging.hh:221)
1  CouchbaseLite                  0x10372f9fc litecore::blip::BLIPIO::_onWebSocketMessage(fleece::alloc_slice, bool) (BLIPConnection.cc:429)
2  CouchbaseLite                  0x103730c20 ___ZN8litecore5actor5Actor7enqueueINS_4blip6BLIPIOEJN6fleece11alloc_sliceEbEEEvMT_FvDpT0_ES9__block_invoke (slice.hh:234)
3  CouchbaseLite                  0x103729ad8 litecore::actor::safelyCall(void () block_pointer) (GCDMailbox.cc:87)
4  CouchbaseLite                  0x103729a40 ___ZN8litecore5actor10GCDMailbox7enqueueEU13block_pointerFvvE_block_invoke (GCDMailbox.cc:123)
5  libdispatch.dylib              0x183040aa0 _dispatch_call_block_and_release + 24
6  libdispatch.dylib              0x183040a60 _dispatch_client_callout + 16
7  libdispatch.dylib              0x18304a9b4 _dispatch_queue_serial_drain$VARIANT$mp + 608
8  libdispatch.dylib              0x18304b2fc _dispatch_queue_invoke$VARIANT$mp + 336
9  libdispatch.dylib              0x18304bcc8 _dispatch_root_queue_drain_deferred_wlh$VARIANT$mp + 340
10 libdispatch.dylib              0x183054098 _dispatch_workloop_worker_thread$VARIANT$mp + 668
11 libsystem_pthread.dylib        0x183373e70 _pthread_wqthread + 860
12 libsystem_pthread.dylib        0x183373b08 start_wqthread + 4

**Comment by pasin** [comment]
Could you please provide more info about the crash?

1. What version of Couchbase Lite you are using?

2. Do you have scenarios that cause the crash?

3. Exception name/info if available.

**Comment by pasin** [comment]
Please try with v2.1.2 or v2.1.3 (latest). We have fixed several WebSocket crash issues in v2.1.2. I understand that this is one of them. If the issue still persists, we could reopen the issue. Thanks.
