### ISSUE TITLE
Fix Iridium Build issues

### ISSUE THREAD

**Issue by djpongh** [couchbase/couchbase-lite-ios#2262]

**Comment by jayahariv** [comment]
DocumentExpirationTest.testDocumentNotShownUpInQueryAfterExpiration() test is failing in jenkins, which is not failing in Xcode or command line in local machine(both Swift and ObjC tests). Wondering why this exact test is failing, as the same scenario is executed in other test cases which is not failing.

**Comment by jayahariv** [comment]
https://github.com/couchbase/couchbase-lite-ios/blob/master/Swift/Tests/DocumentExpirationTest.swift#L89

**Comment by jayahariv** [comment]
Seems like it passed 2.5.0-104

It failed with CE build once, due to other reason. 
```
10:38:30 Build step 'Execute shell' marked build as failure
10:38:30 Set build name.
10:38:30 Workspace is not accessible
10:38:30 ERROR: mobile-builder-ios-xcode10 is offline; cannot locate 
10:38:30 [description-setter] Description set: 
10:38:30 ERROR: Step ‘E-mail Notification’ failed: no workspace for couchbase-lite-ios-edition-build #1663
10:38:30 [BFA] Scanning build for known causes...
10:38:30 [BFA] No failure causes found
10:38:30 [BFA] Done. 0s
```

**Comment by jayahariv** [comment]
Seems like the unit tests are not failing for 2.5.0-105, but `mobile-builder-ios-xcode10` is offline error. 

```
15:12:40 Build step 'Execute shell' marked build as failure
15:12:40 Set build name.
15:12:40 Workspace is not accessible
15:12:40 ERROR: mobile-builder-ios-xcode10 is offline; cannot locate 
15:12:40 [description-setter] Description set: 
15:12:40 ERROR: Step ‘E-mail Notification’ failed: no workspace for couchbase-lite-ios-edition-build #1665
```

**Comment by pasin** [comment]
@jayahariv Can you check with @kimtrang about the error?

**Comment by jayahariv** [comment]
Successfully ran for 2.5.0-106.

**Comment by pasin** [comment]
@jayahariv I will remove the count check and see if the tests still pass.

**Comment by jayahariv** [comment]
Rebuild initiated after the count is removed.

**Comment by jayahariv** [comment]
After removing the count from the tests, it failed once.
```
20:33:47 Test Case '-[DocumentExpirationTest testDocumentNotShowUpInQueryAfterExpiration]' started.
20:33:53 
/Users/[*******]/[*******]/workspace/couchbase-lite-ios-edition-build/couchbase-lite-ios-ee/couchbase-lite-ios/Objective-C/Tests/DocumentExpirationTest.m:130: error: -[DocumentExpirationTest testDocumentNotShowUpInQueryAfterExpiration] : Asynchronous wait failed: Exceeded timeout of 5 seconds, with unfulfilled expectations: "Document expiry test".
20:33:53 Test Case '-[DocumentExpirationTest testDocumentNotShowUpInQueryAfterExpiration]' failed (5.261 seconds).
```

**Comment by jayahariv** [comment]
We are hoping this is related to the `dbObserverCallback` timing issue(#2266). We will wait till this is fixed and further investigate.

**Comment by jayahariv** [comment]
We merged one more fix which is to call the `-purgeExpiredDocs` from serialDispatchQueue, which will solve the race condition. `purgeExpiredDocs` and `postDBChange` are in the same queue, so unless it is purgeExpiry is finished with the transaction,  postDBChange will wait serially. 

This issue can cause the race condition and intermittent documentListenerCallback which still has the document. Meaning, the document purging transaction might not be committed, and the callback is fired before that. 

We will wait and investigate further more after this new commit. It ran once and is successful.

**Comment by pasin** [comment]
let's close this issue. We can reopen if the tests still fail.
