### ISSUE TITLE
Verify TTL Test Scenarios are covered

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-ios#2267]
As laid out in [this document](https://docs.google.com/spreadsheets/d/1RK87u2pmkhiF5IvuGW9LO8viibw2aR9NJ6slFTaTvLs/) the following cases must be in the developer test suite:

- [x] Getting / Setting expiration via API
- [x] Document purged after expiration date
- [x] Expired documents do not show up in query (even a deleted docs one)
- [x] Removing expiration causes a document to not expire
- [x] Expired documents are not replicated (testing lack of replication, which is why this one is here)
- [x] Expiring a document immediately via a call to `setDocumentExpiration(<now>)`

**Comment by jayahariv** [comment]
i guess this scenario will be handled in lite-core, but should we need to check?
- set expiry and then purge document, what happens when the timer is fired

**Comment by borrrden** [comment]
The timer should make a call to LiteCore to begin the purge.

**Comment by jayahariv** [comment]
Pass criteria should be, 'not to raising any warnings, or errors'. But seems like more of a lite core test case.

**Comment by borrrden** [comment]
It could also be folded into the first test case.  Make two documents, expire both, and purge 1.  Verify no documents are in the DB after the expiration date.
