### ISSUE TITLE
testPushAndPullBigBodyDocument_SG intermittently fails

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#2274]
Reported by @jayahariv in #2268. Here is the [logs.txt](https://github.com/couchbase/couchbase-lite-ios/files/2659314/logs.txt).

**Comment by pasin** [comment]
@jayahariv Can you enable Network log and try to reproduce?

**Comment by pasin** [comment]
Wait, I just saw that the log has already been enabled.

**Comment by pasin** [comment]
Sorry, that is the log from different test so I think we need the log.

**Comment by pasin** [comment]
It's strange that the input stream is still reading while the CBLWebSocket is disposed. The input/output stream should already be closed in disconnect() prior to the dispose.

**Comment by jayahariv** [comment]
I got the crash in Xcode, with logging enabled, and run multiple times. Command line is not crashing even with a for loop. But the Xcode test is crashing. 

<img width="1305" alt="screen shot 2018-12-10 at 4 50 46 pm" src="https://user-images.githubusercontent.com/10448770/49770966-c4ff5b80-fc9b-11e8-8ee2-d4650554048f.png">

<img width="1302" alt="screen shot 2018-12-10 at 4 49 46 pm" src="https://user-images.githubusercontent.com/10448770/49770944-a731f680-fc9b-11e8-99b3-3c73d9bd7018.png">

**Comment by jayahariv** [comment]
Attaching the logs: [log.txt](https://github.com/couchbase/couchbase-lite-ios/files/2668827/log.txt)

Sync Gateway:  2.1.1

**Comment by jayahariv** [comment]
Closing as this is not happening right now 

possible fix: #2289
parent task #2262

Will reopen if this happens again.
