### ISSUE TITLE
Couchbase 2.0 --> Create Index is Slow.

### ISSUE THREAD

**Issue by ThiyagarajanShivSankaran** [couchbase/couchbase-lite-ios#2299]
Hi --> I am creating 6 indexes for more than eighty thousand documents. Our app hangs for more than 4 seconds while calling create index every-time. Look at the below time profiler screen shot. 

<img width="1287" alt="time profiler" src="https://user-images.githubusercontent.com/17313049/50502647-d65faa80-0a86-11e9-9719-263ff7a17121.png">

--------
* Version:   2.1.3
* Client OS: IOS

**Comment by snej** [comment]
Well, that's indexing about 3000 docs per second, which seems reasonable for a mobile device. Your screenshot doesn't show much of the profile data, but from the backtrace on the right I can see that 1/3 of the time is spent simply by SQLite reading pages from storage.

This only has to be done once, of course, the first time you launch the app.

Another option is to create the indexes before populating the database -- then createIndex will be instantaneous, but adding each doc will be slightly slower. The overall time will be about the same, but responsiveness may be better.

**Comment by ThiyagarajanShivSankaran** [comment]
Actually, the above screenshot is from iPhoneX device. If, I try with iPad or any lower version of devices it's even worse. 

> This only has to be done once, of course, the first time you launch the app.

Yeah, But every-time I close and open the app. 

But, it's working better in v1.4.1. It will take time at first when we open the app in a day and then it is faster.  

> (Oh, also: it looks like you're creating the indexes on the main thread. Don't do that! Use a background thread to avoid locking up the app.) 

Okay, thanks for this.

So, what do we do?

**Comment by pasin** [comment]
> Yeah, But every-time I close and open the app.

If the index has already been created, the index will not get recreated again.

> So, what do we do?

If the application already has a lot of documents to index, it could take time when creating the index first time. So the application could call database.createIndex() in a background queue to avoid freezing the main thread.

**Comment by pasin** [comment]
I don't think there is an issue about creating the index. I'm closing the issue now.

**Comment by ThiyagarajanShivSankaran** [comment]
@pasin But it's working fine with v1.4.1. Anyway, We won't upgrade our SDK or we will find any other.

**Comment by pasin** [comment]
@ThiyagarajanShivSankaran The index method is different in 2.0. In 1.4.x, the map function is used for creating the index and the map function is run before the query is executed by default. In 2.0.0, we utilize the SQLite index directly so that the index will be run right after the index is created.

**Comment by snej** [comment]
@ThiyagarajanShivSankaran In 1.x, indexes are updated lazily when first queried. In 2.x, the index is populated when it's created. It takes about the same amount of time, but most developers prefer to pay the cost up-front, not while running a query.

>>Yeah, But every-time I close and open the app.
>If the index has already been created, the index will not get recreated again.

As Pasin says, createIndex is a no-op if the index already exists. If you're seeing different behavior, please describe in detail what you're doing.
