### ISSUE TITLE
Iridium Logging Test Cases

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-ios#2302]
See the CBL Logging test plan for details on each item

- [x] Log availability at default location
- [x] Logging format with default behavior
- [x] Enabling Text logging
- [x] Logs for each log level
- [x] Max size log rotation
- [x] Disable logging
- [x] Re-enable logging
- [x] log file name
- [x] System configuration Snippet at the start of log
- [x] Custom logging
- [x] Custom logging log level
- [x] Disable custom logging
- [x] re-enable custom logging

**Comment by jayahariv** [comment]
Since the file logging is going to change, closed the current implementation PRs.

**Comment by jayahariv** [comment]
Logs for each log level = testCustomLoggingLevels 
Custom logging log level = testPlainTextLoggingLevels

**Comment by jayahariv** [comment]
will continue after the new API changes for FileLogging are in place

**Comment by jayahariv** [comment]
Marking maxSize test case as completed, but not closing the issue as the test is disabled.
