### ISSUE TITLE
Replication Filter Test Cases

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-ios#2303]
See the replication filter test plan for details on each item

- [x] Create Filter with one-shot replication
- [x] Create Filter with continuous replication
- [x] Filter deleted document
- [x] Filter removed document
- [x] Stopping and restarting replication with same filter

**Comment by jayahariv** [comment]
Filter deleted document & Filter removed document unit tests are added, but now they are disabled(due to an error with replication 403). Once they got enabled, will mark them as completed.

**Comment by jayahariv** [comment]
Marking all as completed. but not closing the issue, since the tests are disabled.
