### ISSUE TITLE
Need to be able to specify Date Format other than ISO 8601

### ISSUE THREAD

**Issue by tomcondon** [couchbase/couchbase-lite-ios#2308]
--------
* Version:   1.485  Same code exists in the 2.0 master branch
* Client OS: iOS 12.1.x
* Server:    Couchbase Server Enterprise Edition 5.0.1 build 5003

The assumption that everyone uses the hard coded ISO 8601 format of "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" for date representations is not a good one. For instance GO uses RFC 3339 which is a profile of ISO 8601. Our team of engineers have had issues with date queries because of differences in format. It would be nice to specify your own NSDateFormatter for the conversion of NSDate to JSON and back.

**Comment by pasin** [comment]
@borrrden @rajagp Will the new date functions be able to support RFC 3339?

**Comment by djpongh** [comment]
Moved to: https://issues.couchbase.com/browse/CBL-283
