### ISSUE TITLE
The FMDatabase <FMDatabase > is currently in use.

### ISSUE THREAD

**Issue by Suneel-Gunupudi** [couchbase/couchbase-lite-ios#2346]
The app is crashing only a few times, i can't find any solution. I am using Swift and FMDB version 2.7.2.
I need solution.

The FMDatabase <FMDatabase: 0x2826a97a0> is currently in use.
[logging] BUG IN CLIENT OF sqlite3.dylib: illegal multi-threaded access to database connection

func getLastSyncTime(customer_id: String) -> String{
        var last_sync_time = "0"
        guard sharedInstance.database!.open() else{
            return last_sync_time
        }
        do{
            //            sharedInstance.database!.open()
//----------------The below line the app is crashing------
            let resultSet: FMResultSet! = try sharedInstance.database!.executeQuery("SELECT last_sync_time FROM Customers_Table WHERE customer_id=?", values: [customer_id])
            if resultSet != nil{
                while resultSet.next(){
                    last_sync_time = resultSet.string(forColumn: "last_sync_time")!
                }
            }
            //            sharedInstance.database!.close()
        }catch{
            print(#function, " Error: \(error)")
        }
        guard sharedInstance.database!.close() else{
            return last_sync_time
        }
        return last_sync_time
        
    }

and the issue is showing in below FMDB method
- (FMResultSet *)executeQuery:(NSString *)sql values:(NSArray *)values error:(NSError * __autoreleasing *)error {
    FMResultSet *rs = [self executeQuery:sql withArgumentsInArray:values orDictionary:nil orVAList:nil];
    if (!rs && error) {
        *error = [self lastError]; --------- Here the app Crashes
    }
    return rs;
}

**Comment by pasin** [comment]
Close as this does seem to be FMDatabase issue not Couchbase Lite iOS. Please open the issue to the right repository.
