### ISSUE TITLE
Attachments saved from Couchbase-lite-ios v2.1.3 crashes pouchdb changes feed #7621

### ISSUE THREAD

**Issue by ThiyagarajanShivSankaran** [couchbase/couchbase-lite-ios#2351]
Adding an attachments from Couchbase-lite-ios sdk v2.1.3 app crashes the pouchdb changes feed.  But, it's working fine with the older version of couchbase-lite-ios sdk 1.4.1.

I think it's because of blobs that we are saving from newer version.

Error log, 

> Access to fetch at 'https://development.xxxxx.xx/xxxxsync/-mhCt_3_ukvnnadeDM2aNiY/blob_/54bfe584-4828-47ca-80bc-ecdbc4c889ff.jpg?rev=3-02ff16f1091c456018f8ac9851ec19f5d5ba509a' from origin 'https://xxxx.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

--------
* Version:   v2.0 and above
* Client OS:  iOS 12.1.x
* Server:   Couchbase Server Enterprise Edition 6.0.0 build 1693

**Comment by pasin** [comment]
I'm not familiar with how PouchDB changes feed work. Can you explain more how pouchDB uses or calls into Couchbase Lite?

**Comment by ThiyagarajanShivSankaran** [comment]
@pasin  Once the attachments is saved from mobile pouchdb uses syncgateway rest api's to pull the attachments. Since the file name contains blob `blob_/54bfe584-4828-47ca-80bc-ecdbc4c889ff.jpg`  due to the rest api is not working and crashes pouchdb. If, I remove "blob_" from url then it's working fine.

**Comment by snej** [comment]
This sounds more like a PouchDB bug. I believe it needs to quote the `/` in the blob name as `%2F`.

**Comment by ThiyagarajanShivSankaran** [comment]
@snej I have already posted this in Pouchdb GitHub issues, but they said it's Couchbase Lite SDK issue. [https://github.com/pouchdb/pouchdb/issues/7621](url)

**Comment by rajagp** [comment]
@ThiyagarajanShivSankaran 

> pouchdb uses syncgateway rest api's to pull the attachments. Since the file name contains blob


 As Jens pointed out and as indicated in our[ SGW REST ](https://docs.couchbase.com/sync-gateway/2.1/admin-rest-api.html#/attachment/put__db___doc___attachment_)API docs

_Attachment name. This value must be URL encoded. For example, if the attachment name is blob_/avatar, the path component passed to the URL should be blob_%2Favatar (tested with URLEncoder)._

**Comment by snej** [comment]
>they said it's Couchbase Lite SDK issue.

No, they said "we don't support Couchbase".

**Comment by ThiyagarajanShivSankaran** [comment]
@snej Sorry, my bad. 

@rajagp Okay, We will try this from our end, Thanks.

**Comment by ThiyagarajanShivSankaran** [comment]
@snej Yeah, now it's working, Thanks.
