### ISSUE TITLE
Validate and add NonNull to all public APIs

### ISSUE THREAD

**Issue by jayahariv** [couchbase/couchbase-lite-ios#2353]
Validate and add NonNull to all public APIs. 

DATABASE
- [x] Database.swift
- [x] DatabaseChangeListener.swift
- [x] DatabaseConfiguration.swift
- [x] DocumentChangeListener.swift
- [x] EncryptionKey.swift
- [x] ListenerToken.swift
- [x] Logging.swift
- [x] Prediction.swift

DOCUMENT
- [x] ArrayObject.swift
- [x] Blob.swift
- [x] DictionaryObject.swift
- [x] Document.swift
- [x] DocumentFragment.swift
- [x] Fragment.swift
- [x] MutableArrayObject.swift
- [x] MutableDictionaryObject.swift
- [x] MutableDocument.swift
- [x] MutableFragment.swift

REPLICATOR
- [x] Authenticator.swift
- [x] DocumentFlags.swift
- [x] Endpoint.swift
- [x] Replicator.swift
- [x] ReplicatorConfiguration.swift
- [x] Message.swift	
- [x] MessageEndpoint.swift
- [x] MessageEndpointConnection.swift
- [x] MessageEndpointListener.swift

QUERY
- [x] Iterable.swift
- [x] Parameters.swift
- [x] Query.swift
- [x] QueryBuilder.swift
- [x] QueryChangeListener.swift
- [x] Result.swift
- [x] ResultSet.swift

CLAUSE
- [x] Collation.swift
- [x] DataSource.swift
- [x] From.swift
- [x] GroupBy.swift
- [x] Having.swift
- [x] Join.swift
- [x] Joins.swift
- [x] Limit.swift
- [x] OrderBy.swift
- [x] Ordering.swift
- [x] Select.swift
- [x] SelectResult.swift
- [x] Where.swift

EXPRESSION
- [x] ArrayExpression.swift
- [x] ArrayExpressionIn.swift
- [x] ArrayExpressionSatisfies.swift
- [x] Expression.swift
- [x] FullTextExpression.swift
- [x] Meta.swift
- [x] PropertyExpression.swift
- [x] VariableExpression.swift

FUNCTION
- [x] ArrayFunction.swift
- [x] FullTextFunction.swift
- [x] Function.swift

INDEX
- [x] Index.swift

ROUTER
- [x] FromRouter.swift
- [x] GroupByRouter.swift
- [x] HavingRouter.swift
- [x] JoinRouter.swift
- [x] LimitRouter.swift
- [x] OrderByRouter.swift
- [x] WhereRouter.swift

**Comment by snej** [comment]
Don't you mean `nullable`?

**Comment by jayahariv** [comment]
Similar to this in Android. https://github.com/couchbase/couchbase-lite-android/pull/1846

**Comment by snej** [comment]
This was already done in 2.0 — `nullable` in Obj-C, `?` in Swift — but you can compare it against the API spec to check for any omissions (here or in the spec!)
