### ISSUE TITLE
Fetch data returned mismatching format between SGW and CBL with iOS client

### ISSUE THREAD

**Issue by euniceatcouchbase** [couchbase/couchbase-lite-ios#2355]
### Versions
* Server version:    5.5.0-2473
* Sync_gateway version:   2.1.1
* CBL:    2.5.0-161
* Client OS:    iOS
* Other Config:    xattrs=true, mode=cc, allow conflicts, cbs <-> sg ssl disabled

### Operating System / Device Details
tested on iOS simulator

### Steps To Reproduce
Ensure travel-sample on both CBL and SGW
Fetches docs in with a matching substring

swift call
`let searchQuery = QueryBuilder
                 .select(
                        SelectResult.expression(Meta.id),
                        SelectResult.expression(Expression.property(select_property1)).as(select_property1),
                        SelectResult.expression(Function.upper(Expression.property(select_property2)))
                  ) 
                .from(DataSource.database(database))
                .where(Function.contains(Expression.property(select_property1),                                                                                    substring: Expression.string(substring)))
`

Verifies with n1ql - 
`select meta().id, email, UPPER(name) from `travel-sample` t where CONTAINS(t.email, "gmail.com")`

### Expected behavior
Data retrieved from SGW and CBL match properly with the same same value

### Actual behavior
CBL (by SelectResult.expression(Function.upper(Expression.property(select_prop))) returns value like: 
{**'UPPER()'**: u'IL VECCHIO', 'email': u'ilvecchio.restaurant@gmail.com', 'id': u'landmark_21522'}
SGW (n1ql) returns value like: 
{u'id': u'landmark_21522', u'email': u'ilvecchio.restaurant@gmail.com', u'**$1**': u'IL VECCHIO'}

### Log files
[Console Log](https://drive.google.com/file/d/1s_CarKjR9mT0o6qoolreP4YOT6Fcw11h/view?usp=sharing)
[Xcode Log](https://drive.google.com/file/d/1DlhJhq0ppmIxORGqlrwH5GkihhBWQJud/view?usp=sharing)
[Jenkins job failure:](http://uberjenkins.sc.couchbase.com:8080/job/iOS-Listener-TestServer-Query-tests/318/testReport/testsuites.CBLTester.CBL_Functional_tests.SuiteSetup_FunctionalTests/test_query/test_query_substring_email_name_gmail_com_/)

### Notes
I tried to twist swift call to 
`let searchQuery = QueryBuilder
                .select(SelectResult.expression(Meta.id),
                        SelectResult.expression(Expression.property(select_property1)).as(select_property1),
                        SelectResult.expression(Function.upper(Expression.property(select_property2))).as(select_property2))
                .from(DataSource.database(database))
                .where(Function.contains(Expression.property(select_property1),                                                                                    substring: Expression.string(substring)))`

and changed n1ql to  
`select meta().id, email, UPPER(name) **as name** from `travel-sample` t where CONTAINS(t.email, "gmail.com")`

which solves the problem, however, since the original test code worked before now it shows as regression failure, we need to understand what the spec says.

**Comment by snej** [comment]
There isn't any obvious column name for a computed result column like this; it's just a matter of making something up (and IMHO, something based on the expression is more useful than just a number.)

I don't think it's a good idea to rely on such a name. If a test wants to verify the results, it should be getting the query row as an array, to avoid these ambiguities.

**Comment by euniceatcouchbase** [comment]
I agree. In that case we need to ensure SelectResultAs available to all platforms, not just for iOS.

**Comment by snej** [comment]
FYI, [the JSON schema supports `AS` on a result column](
https://github.com/couchbase/couchbase-lite-core/wiki/JSON-Query-Schema#the-what-clause-result-columns), so the query can set a custom column name to avoid ambiguities like this.

**Comment by rajagp** [comment]
@pasin  Is there a reason why we changes the way the column name was generated ? 


> Will this be considered as breaking API changes?

Yes. I consider this as an API breaking change because the result format is changed. Existing apps could potentially break upon upgrade possibly requiring  an update of their usage of the API.  I cannot comment on how current users are querying the data and how much it would impact them but this change violates our API policy

> All platforms need to make change together so that we have the same behavior. Depending on schedule, we may not make this change in Iridium

 I would not want to delay the Iridium release  - I vote to revert this change and go back to the $index names . I agree that its not great but it is at least consistent with N1QL's naming policy .

**Comment by pasin** [comment]
@rajagp we have moved the logic to generate the column name to LiteCore. We haven't discussed about the format changes but on anther thought is that using the column name with the function name seems to be standard for SQL. We could discuss more on this when we can make the API change.

**Comment by rajagp** [comment]
@pasin  OK. In that case, let's track the new column name change as a future enhancement for consideration in 3.0 and revert back to ${index} for now.
  When we decide to make the change, I would think that whatever is done , it would be good to align with N1QL  (not that we are N1QL compliant but it avoids questions from users on why the two platforms differ)

**Comment by snej** [comment]
I asked about what Server does, on Slack:

>**Sitaram Vemulapalli [10:31 AM]**  
>N1QL will try to derive alias from the expression (if dotted expression last field name become alias, identifier it becomes alias, otherwise it will be Missing). Other places where it is must will return error. In Projection in the absence of AS clause it will try to use the alias if it is Missing we assign names $1, $2, increasing order.  This is way it works from day one. Not sure if really documented  but i have seen many examples that shows this.
>**Marco Greco [10:39 AM]**  
>bear in mind that it is a standard relational technique to give default sequential aliases to expressions that are unnamed, but what these aliases look like is not set in stone, so...

**Comment by snej** [comment]
@rajagp:
>I consider this as an API breaking change because the result format is changed

If we never documented what those column names would be, I don't think this can be considered an API change, just a change in (undocumented) behavior. It's definitely possible for behavioral changes not part of an API to cause problems for clients (e.g. the order in which callbacks are invoked, what runloop something runs on, etc.)

Our clients don't have to use names to access result columns, because we also provide them as an array with positional indexing. In the case of computed columns I think it's a bad idea to access them by name.

**Comment by snej** [comment]
So we should
- [ ] [Create a LiteCore bug](https://github.com/couchbase/couchbase-lite-core/issues/686) to change the synthetic column names to what they were in 2.0
- [ ] Add the `AS` operator to the API spec, to give developers control over column names.

**Comment by pasin** [comment]
Thanks @snej. I'm closing this issue then.
