### ISSUE TITLE
Couchbase-lite-2.0 IOS - Querying is not generic anymore.

### ISSUE THREAD

**Issue by ThiyagarajanShivSankaran** [couchbase/couchbase-lite-ios#2363]
Hi, 

Couchbase 1.4.x querying is very generic when compared to 2.x, 

1.4.x query builder,

```
let predicate = NSPredicate(format: "createdby == 'user1' AND (ANY detail.jobcode IN {'Jobcode1', 'Jobcode2’}")
let results = try? CBLQueryBuilder(database: self.database, select:[], wherePredicate: predicate, orderBy: nil).runQuery(withContext: nil)
```

But, In 2.x it's different, 

```
let DETAILS = ArrayExpression.variable("DETAILS") 
let DETAILS_JOBCODES = ArrayExpression.variable("DETAILS.jobcode") 
let a = [Expression.string("Jobcode1"), Expression.string("Jobcode2")]
let query = QueryBuilder 
.select(SelectResult.all()) 
.from(DataSource.database(database!)) 
.where(ArrayExpression.any(DETAILS).in(Expression.property("details")).satisfies(Expression.not(DETAILS_JOBCODES.in(a))))
```

Because, we are using a generic code base for more than 100 queries. So, we are facing a hard time converting the above string's to expression's to work with the latest couchbase-lite-2.0 app.

In 1.4.x, I can change this string `"createdby == 'user1' AND (ANY detail.jobcode IN {'Jobcode1', 'Jobcode2’}"` dymanically from the document and use it in queries. But, we can't do this in 2.x.

Sorry for creating the above question/feature-request in issues.  

--------
* Version:   v2.0 and above
* Client OS: 12.x
* Server:    Couchbase Server Enterprise Edition 6.0.0 build 1693

**Comment by snej** [comment]
Hi! Please ask your question on the [Couchbase web forum](https://forums.couchbase.com/c/mobile) or the [Couchbase Mobile mailing list](https://groups.google.com/forum/#!forum/mobile-couchbase). We use Github issues only for bug reports and feature suggestions. Thanks.

**Comment by ThiyagarajanShivSankaran** [comment]
@snej I have posted this in https://forums.couchbase.com/c/mobile and it's show 'Account temporarily on hold'.  And, I have tried in here https://groups.google.com/forum/#!forum/mobile-couchbase , But, it's showing 'You do not have permission to post to this group'.

So, where do I need to post.

**Comment by snej** [comment]
The web forum is best. I don't know why your account would be on hold ... what username did you use?

**Comment by rajagp** [comment]
The [post](
https://forums.couchbase.com/t/couchbase-lite-2-0-ios-querying-is-not-generic-anymore/19974) is available
