### ISSUE TITLE
Carthage build failed (1.4.2)

### ISSUE THREAD

**Issue by adamski** [couchbase/couchbase-lite-ios#2375]
Trying to install version 1.4.2 via Carthage fails during Carthage build:

```
*** Building scheme "CBL iOS framework - Carthage" in CouchbaseLite.xcodeproj
Build Failed
        Task failed with exit code 65:
```

log output:

```
** ARCHIVE FAILED **


The following build commands failed:
	CompileC<PATH-TO-PROJECT>/Carthage/Checkouts/couchbase-lite-ios/Build/Intermediates/ArchiveIntermediates/CBL\ iOS\ framework\ -\ Carthage/IntermediateBuildFilesPath/CouchbaseLite.build/Release-appletvos/CBL\ iOS\ library.build/Objects-normal/arm64/CollectionUtils.o <PATH-TO-PROJECT>/Carthage/Checkouts/couchbase-lite-ios/vendor/MYUtilities/CollectionUtils.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

Looks like its trying to build a tvOS version?

(If you're wondering why I'm still on 1.4, its because I need CouchDB compatibility)

--------
* Version:   1.4.2
* Client OS: iOS 12
* Server:    n/a

**Comment by adamski** [comment]
Luckily I have copies of the version 1.4.0 macOS and iOS frameworks I downloaded previously. I see they are no longer available from the website, nor from GitHub as compiled frameworks. 
(I'm trying to avoid using CocoaPods if possible)

**Comment by pasin** [comment]
I have tested with Carthage v0.32, and I was able to build CBL 1.4.4 (latest 1.4.x) framework for both iOS and tvOS. Here is my Cartfile and carthage command to build only iOS:

Cartfile:
````
github "couchbase/couchbase-lite-ios" == 1.4.4
````

Command:
```
carthage update --platform iOS
```

Please try with CBL 1.4.4 instead of 1.4.2.
