### ISSUE TITLE
Upgrade Swift Version to 5

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#2382]
We should do this when XCode release 10.2.

**Comment by matteosist** [comment]
Hi, when this CR will be released? From today with Xcode 10.2 we get this error "module compiled with swift 4.2.1 cannot be imported by the swift 5.0 compiler".

Thanks.

**Comment by snej** [comment]
Cobalt is our next feature release after Iridium (which has not yet shipped), so it's at least a few months out. We can't just upgrade the compiler and the Swift language version and put out a new build — that's a significant change, so it requires going through the full QA process as part of a release.

Right now your options are
* [Download](https://developer.apple.com/download/more/) and reinstall Xcode 10.1
* Check out and build CBL yourself with Xcode 10.2 — but if you're a Couchbase customer be aware that (a) our support team won't support a homemade build, and (b) you won't get the EE features.

**Comment by pasin** [comment]
As XCode 10.2 was released, we will upgrade Swift version to 5.0 for Cobalt and 4.2 for Iridium (XCode backward compatibility).

**Comment by pasin** [comment]
@jayahariv I have updated Swift version for iridium to 4.2. Could you please update the cobalt to 5.0 and fixed anything that we need to.

**Comment by johnngoi** [comment]
@pasin let me know when you have a release for Swift 5. We are upgrading this week.

**Comment by lacklock** [comment]
hope you can upgrade soon, after upgrade to Xcode 10.2, my project can't build pass.

**Comment by pmusolino** [comment]
I can’t migrate my project, Couchbase Lite is the only pod that present this problem.

**Comment by pasin** [comment]
We are working on releasing a new version that fix the issue. Thank you for your patience.

**Comment by callo90** [comment]
@pasin any updates?

**Comment by rajagp** [comment]
As  Pasin mentioned , we are working on it. We will update this ticket when it is released. This will happen once it passes our QA process.

**Comment by rajagp** [comment]
If you missed it, 2.1.6 was released yesterday with swift5 support. Available via carthage, cocoapods and via our downloads page.

**Comment by johnngoi** [comment]
@rajagp I don't see the tag/release for 2.1.6. Am I missing something?

**Comment by pasin** [comment]
@johnngoi The tag will be created soon.

**Comment by johnngoi** [comment]
@pasin thanks! once I see it, I will run `carthage update`

**Comment by pasin** [comment]
Release Tag 2.1.6 has been pushed.

**Comment by lightandshadow68** [comment]
Any chance we will see this for the 1.x versions as well, for those that have yet to upgrade to 2.0?

**Comment by pasin** [comment]
We don't have plan to release a new 1.x version but definitely we could fix the Swift version in the xcconfig file.

**Comment by lightandshadow68** [comment]
We're already building from source, so that would be great.
