### ISSUE TITLE
CouchbaseLite 500 error "Invalid data in database' or missing rows when querying a map reduce view

### ISSUE THREAD

**Issue by AlexanderKaraberov** [couchbase/couchbase-lite-ios#2394]
Hello @snej  I'm really sorry for pinging you directly and creating an issue for (I guess) an already unsupported version of CBL. But I believe you may be the single person who might provide me a fresh thought and opinion relying on your vast experience with CBL, because at this point I've got stuck in resolving a weird bug which happened in couchbase-lite-ios 1.0.0. 

The bad thing and main obstacle is that I can't reproduce this issue locally and only rely on reports from other people who witnessed it.

We are using CouchDB 2.3 on a sever-side and CBL 1.0.0 for iOS clients. A map-reduce view which was backing particular functionality failed for plenty of iOS clients. After mobile database replicated a set of documents which are supposed to be indexed by this view and then the view was queried it returned `500 "invalid data in database"` which according to CBL codebase corresponds to only one SQLite error code: 
```C
        case SQLITE_CORRUPT:
            return kCBLStatusCorruptError;
```
this seems odd as according to SQLite docs this error can happen in very [specific situations](https://www.sqlite.org/howtocorrupt.html). The only more or less veracious explanation might be running an sql query on the same db instance from multiple threads. What's interesting is that after view code was changed which caused full view index re-deployment:
```C
 if (lastSequence == 0) {
            // If the lastSequence has been reset to 0, make sure to remove all map results:
            ok = [fmdb executeUpdate: @"DELETE FROM maps WHERE view_id=?", @(_viewID)];
```
this issue was fixed and this view returned correct set of key-values pairs. When this issue was observed the first time instead of `500` error `Invalid data` the view just didn't return the row for the document which is supposed to be indexed. This document definitely was in the mobile database because another view from the same design document returned a row for it. What if corruption somehow happened in the `maps_keys` sql index?
```sql
 CREATE INDEX maps_keys on maps(view_id, key COLLATE JSON); 
```

Based on the description I've provided does this ring a bell? Perhaps you've encountered with similar situation and have a hunch what might happened? Let me know if additional information is needed. Thank you beforehand for any input or thought you may provide.

**Comment by AlexanderKaraberov** [comment]
So I've managed to reproduce this corruption issue and here is a quick update on this.
The actual error caught in the debugger:
```
2019-04-02 18:14:36.004923+0200 [44341:1775449] Unknown error calling sqlite3_step (11: database disk image is malformed)
2019-04-02 18:14:36.005090+0200 [44341:1775449] DB Query: DELETE FROM maps WHERE view_id=? AND sequence IN (SELECT parent FROM revs WHERE sequence>? AND parent>0 AND parent<=?)
(lldb) po db.lastDbError
kCBLStatusCorruptError
```
This error happened after `fmdb` tried to run this query:
```Objective-C
  // Delete all obsolete map results (ones from since-replaced revisions):
            ok = [fmdb executeUpdate: @"DELETE FROM maps WHERE view_id=? AND sequence IN ("
                  "SELECT parent FROM revs WHERE sequence>? "
                  "AND parent>0 AND parent<=?)",
                  @(_viewID), @(lastSequence), @(lastSequence)];
        }
```

After I had executed SQLite database consistency checker (`PRAGMA integrity_check`) I've found that database was not corrupted as severely as I thought before and main `maps_keys` index is fine. Corruption happened only in the internal index automatically created by SQLite and which is used to implement UNIQUE and PRIMARY KEY constraints on ordinary tables. In our case it was sqlite_autoindex_revs_1:



<img width="438" alt="Screenshot 2019-04-03 at 10 16 37" src="https://user-images.githubusercontent.com/3254818/55471132-5eff6100-5609-11e9-9302-6b06441d755f.png">


Naming scheme confirms this was an internal index created for sequence row:
```sql
CREATE TABLE revs ( 
                sequence INTEGER PRIMARY KEY AUTOINCREMENT,
```
This also explains why one particular query for clearing outdated index entries failed but all other ones succeeded. So this is a failing query:

```sql
DELETE FROM maps WHERE view_id=45 AND sequence IN (
                   SELECT parent FROM revs WHERE sequence>17634
                  AND parent>0 AND parent<=17634)
```

If we now try to decompose it to find a minimum failing query, we'll see that subquery to select parent sequences works just fine and this query works as well:

```sql
SELECT * FROM maps WHERE view_id=45
```
But as soon as I run this query:

```sql
SELECT * FROM maps WHERE view_id=45 AND sequence=17634
```

I observe `database disk image is malformed` error. I suppose this is because this query relies on the internal index for sequence row mentioned above while the previous one just have to use `maps_key` b-tree index which apparently is fine. Confirmed:
```sql
SEARCH TABLE maps USING INDEX maps_keys (view_id=?)
```

I've used a handy `REINDEX` to delete and recreate indices from scratch as soon as corrupted error is thrown and verified that the aforementioned query now succeeds. Catching an error, running `REINDEX` and then again retying `updateIndex` looks like sweeping under the rug therefore it would be great to understand the source of this thread safety violation which caused this corruption. Apparently this check didn't catch it:

```Objective-C
    if (!ok) {
        [[NSAssertionHandler currentHandler] handleFailureInMethod:_cmd
                                                            object:self
                                                              file:@(__FILE__)
                                                        lineNumber:__LINE__
                                                       description:
             @"***** THREAD-SAFETY VIOLATION: This database is being used on a thread it wasn't "
              " created on! Please see the concurrency guidelines in the Couchbase Lite "
              "documentation. *****"];
    }
```

**Comment by pasin** [comment]
Couchbase Lite 1.x is not thread safe so basically the objects (e.g. Database, Document, Query / View) cannot be shared across threads. The thread-safety violation can be detected only when using threads with runloop **BUT NOT** when using dispatch queues; that could be the reason that the "`THREAD-SAFETY VIOLATION`" check doesn't get called. If a dispatch queue is used, the dispatch queue should be set to CBLManager [here](https://github.com/couchbase/couchbase-lite-ios/blob/1.x/Source/API/CBLManager.h#L173).

In the past, there was a database corruption [issue](https://github.com/couchbase/couchbase-lite-ios/issues/1424) that was fixed for MacOS framework. If thread-safety is not the problem, you may try to apply the same fix and rebuild Couchbase Lite to see if it solves the problem or not.

**Comment by AlexanderKaraberov** [comment]
Hello @pasin and thanks for reply. Could you please pinpoint what exactly shall I change in sqlite compile options or in CBL? I wasn't able to find this in the mentioned thread.
Btw `sqlite3_threadsafe()` returns 1 in our case (`SQLITE_THREADSAFE=1`).

**Comment by pasin** [comment]
@AlexanderKaraberov look like I gave you the wrong link to the issue. Can you check [here](https://github.com/couchbase/couchbase-lite-ios/issues/1482) which has mmap fix for MacOS?

Regarding the fix for #1424, is it possible to upgrade to 1.4.x instead of using 1.0.0 so that you can get all the fixes?

**Comment by AlexanderKaraberov** [comment]
Hi @pasin . I checked mentioned issues and they both seem to be related to `mmap` issue on OS X. First I don't have this config set at all `SQLITE_CONFIG_MMAP_SIZE` and also issue is reproducible on iOS device without any power failures, the app wasn't even backgrounded. I managed to to reproduce it constantly. So I just replicate data and periodically at the same time I update view indexes and I after I repeat this 2-3 times I got this error:
```Objective-C
NSLog(@"Unknown error calling sqlite3_step (%d: %s) eu", rc, sqlite3_errmsg(db));
```
```
(lldb) po sqlite3_errmsg(db)
"database disk image is malformed"
```
when execute this query in the updateIndex:
```Objective-C
 // This is the revision that used to be the 'winner'.
                            // Remove its emitted rows:
                            first = NO;
                            SequenceNumber oldSequence = [r2 longLongIntForColumnIndex: 1];
                            [fmdb executeUpdate: @"DELETE FROM maps WHERE view_id=? AND sequence=?",
                                                 @(_viewID), @(oldSequence)];
```

I've checked that `CBLManager` is not shared accross threads and everything happens on the the same background thread which is reserved for main operations: replication, view index building. Proper read write locking is done in the `beginTransaction` therefore at this point I would exclude multithreaded issues.

Any other ideas what am I missing?

**Comment by AlexanderKaraberov** [comment]
Quick update. Issue is resolved and indeed it had nothing to do with multithreading. I'm closing it.

FYI root cause was a sorting bug in the `JSON` collation used by a `key` column in the `maps` table and `maps_key` index. This was causing a silent corruption in the index b+-tree effectively making it inconsistent with a table. By debugging `sqlite3VdbeExec` I've found that `OP_NotExists` byte code related to a `SeekRowid` one had failed with `SQLITE_CORRUPT_BKPT`. This also explains why `REINDEX` worked for me. Defining a proper Unicode ordering fixed this issue.

**Comment by pasin** [comment]
@AlexanderKaraberov I knew that it's been awhile. Would you mind sharing more detail about the problem in the JSON Collation that doesn't handle the Unicode ordering properly?
