### ISSUE TITLE
Swift 5.0.1

### ISSUE THREAD

**Issue by skela** [couchbase/couchbase-lite-ios#2424]
Incompatible Swift version - framework was built with 5.0 (swiftlang-1001.0.69.5 clang-1001.0.46.3) and the local version is 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5).
make: *** [bootstrap] Error 1

Unable to use the library with Xcode Version 10.2.1 (10E1001) and Swift 5.0.1 via Carthage binary only.
--------
* Version:   2.1.6
* Client OS: NAME_AND_VERSION
* Server:    NAME_AND_VERSION

**Comment by pasin** [comment]
Hope there is a way to get around Carthage strictly checks Swift version.

**Comment by rajagp** [comment]
@pasin  Can you file a new [ticket ](https://github.com/Carthage/Carthage/issues/2411)with Carthage for 5.0.1 . Because 5.0.1 is compatible with 5.0 so there is no reason for Carthage to enforce the strict version checking.

**Comment by pasin** [comment]
I have added a comment to https://github.com/Carthage/Carthage/issues/2411 to see if there is a workaround or not.

**Comment by skela** [comment]
Awesome, just FYI, i was able to have it complile via Carthage successfuly, (didn't used to work), so if I use carthage to build it, there's no issue with Swift compatibility or anything like that. 
In other words adding this to my Cartfile:

`github "couchbase/couchbase-lite-ios" == 2.1.6`

Works :)

**Comment by pasin** [comment]
@skela Thanks for the update. I have also fixed this issue in the coming 2.5.0 release.
