### ISSUE TITLE
Please make DictionaryProtocol accessible

### ISSUE THREAD

**Issue by davisford** [couchbase/couchbase-lite-ios#2433]
Currently [DictionaryProtocol](https://github.com/couchbase/couchbase-lite-ios/blob/master/Swift/DictionaryObject.swift#L24) is `internal`, but multiple types adhere to the protocol, e.g. `Document`, `DictionaryObject`...

It would be great if the protocol were public so I could use it's type.  As it stands I have to write several versions of the same copy-pasta, eg.

```swift
public static func fromDocument(doc: Document) -> SomeType {
  // use DictionaryProtocol API to get at fields
}

public static func fromResult(res: Result) -> SomeType {
   if let dict = result.dictionary(forKey: dbname) {
      // use DictionaryProtocol API to get at fields
   }
}
```
--------
* Version:   latest
* Client OS: Mac OS Mojave
* Server:    N/A

**Comment by pasin** [comment]
Thanks for suggestion. We have received several requests on this.

**Comment by jayahariv** [comment]
closing since PR is merged.
