### ISSUE TITLE
Cannot Open Database Encrypted in 2.1.x with 2.5

### ISSUE THREAD

**Issue by djpongh** [couchbase/couchbase-lite-ios#2438]
Trying to open a database encrypted in 2.1.x with 2.5 yields the following error:

“CouchbaseLite Database ERROR: file is not a database (26/26) Error: Error Domain=CouchbaseLite Code=20 "file is not a database" UserInfo={NSLocalizedDescription=file is not a database}.”

**Comment by pasin** [comment]
This is fixed by https://github.com/couchbase/couchbase-lite-core/commit/4ed72ceebbb92e6d248fbd938174e578d226ab05.
