### ISSUE TITLE
Potential to interfere the UI thread by Live Query if there are a lot of changes

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#2439]
Currently LiveQuery is observing the database changes on the main thread which could have some effect to the UI when they are a lot of changes coming in especially from the replicator. We should investigate this and change to observe the database changes on the live query dispatch queue.

**Comment by pasin** [comment]
From https://github.com/couchbase/couchbase-lite-java/pull/109, it seems like the issue is that the database change handler's synchronize block that shares the same lock object with other synchronize blocks (e.g. performing query).

**Comment by jayahariv** [comment]
Verified it using the sample project, and is not blocking the main thread. 

// If you want to use this below code. Copy the framework to `LiveQuery/../Framework/`
[LiveQuery.zip](https://github.com/couchbase/couchbase-lite-ios/files/3254550/LiveQuery.zip)
