### ISSUE TITLE
Compiled with newer version

### ISSUE THREAD

**Issue by shrikanttanwade** [couchbase/couchbase-lite-ios#2449]
CouchbaseLiteSwift.framework/CouchbaseLiteSwift compiled with newer version of Swift language (unknown ABI version 0x07) than previous files (unknown ABI version 0x06) file
--------
* Version:  Swift 4.2, Xcode 10.1

**Comment by pasin** [comment]
The binary downloaded from couchbase website was compiled with xcode 10.2 / swift 5 which will not be compatible with xcode 4.2. To get the binary for xcode 10.1, please build the framework by following the “How to build framework files” steps from the github readme.
