### ISSUE TITLE
Boolean value get saved as 0 or 1

### ISSUE THREAD

**Issue by bawelter** [couchbase/couchbase-lite-ios#2453]
The issue is when boolean values get saved as 0 or 1 because they aren't recognized as a boolean value.

This issue is specifically for a serialization issue which I encountered when making a flutter plugin to use Couchbase.

One possible solution is add an additional case statement in DataConverter.swift

```
case let bool as NSNumber:
            if (bool === kCFBooleanTrue || bool === kCFBooleanFalse) {
                return bool === kCFBooleanTrue
            } else {
                return value
            }
```

This would check on a deeper level for a boolean value and save it as boolean in the document instead of 0 or 1.

--------
* Version:   2.5
* Client OS: iOS / Swift using Cocoa Pod 'CouchbaseLite-Swift', '~> 2.5.1'
* Server:    N/A

**Comment by jayahariv** [comment]
Swift will not recognize or accept 0 or 1 as boolean, instead you should provide the boolean values. 

Unlike in other programming languages, in Swift, integers and strings cannot be used where a Boolean value is required. 

Instead you can try saving as `intVar != 0` when saving.

**Comment by bawelter** [comment]
The problem is Foundation's JSON serialization uses NSNumber to wrap both integers and booleans, I already put this through my own DataConverter to fix the issue I just thought if you wanted more compatibility in this library it would be useful but that is up to you.

Yes you are correct swift has its own boolean type which why I am trying to convert the NSNumber to boolean after it is deserialized with Foundation's JSON serializer, otherwise it is stored as an int in Couchbase.  I know I could just use objc instead but my experience is in Swift not objc.

Hopefully a supported plugin for Couchbase comes out for flutter soon but until then.

For reference:

https://flutter.dev/docs/development/platform-integration/platform-channels
https://flutter.dev/docs/development/packages-and-plugins/developing-packages

**Comment by bawelter** [comment]
After looking at this it's probably better to process the data on my end like I already am.

Do you know of how to contact anyone or request Couchbase mobile for flutter?  With platform support for mobile, desktop, web I can see this picking up a lot of momentum and is much needed with a lack of NoSQL solutions.

**Comment by jayahariv** [comment]
Closing since it is not a Couchbase issue. 

@rhedgpeth @rajagp any comments on the request for Couchbase mobile for flutter?

**Comment by rajagp** [comment]
@bawelter There is a community driven (not couchbase driven) project https://github.com/oltrenuovefrontiere/fluttercouch that may be of interest. There is a blog post in the works on the same - so stay tuned.

**Comment by bawelter** [comment]
Ah ok that’s the one I’m already working on, well thanks for your help!

Bryan Welter
Saltech Systems
Lead Software Developer
(515) 250-5061

________________________________
