### ISSUE TITLE
CBL 2.5.0 is not able to open CBL 2.1.5 encrypted db

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-ios#2481]
--------
* Version:   CBL-2.5.0-272
* Client OS: iOS
* Server:    CBS-6.0.0-1693

I'm trying to open encrypted iOS db of CBL 2.1.5 with the password configured db config in CBL2.5.0 (database copied from 2.1.2 app, but I'm getting "file is not a database" error.

# CBL Logs

[logs1559651469.6311321.zip](https://github.com/couchbase/couchbase-lite-ios/files/3252359/logs1559651469.6311321.zip)

# Python client logs
[python_client.log](https://github.com/couchbase/couchbase-lite-ios/files/3252363/python_client.log)

Test command - 
1. git clone https://github.com/couchbaselabs/mobile-testkit.git
2. git checkout feature/cbl-upgrade-testing
3. pytest -rsx -s  --skip-provisioning --timeout 3600 --base-liteserv-version=2.1.5 --upgraded-liteserv-version=2.5.0-272 --liteserv-host=localhost --liteserv-port=8080 --sync-gateway-version=2.5.0-269 --mode=cc --server-version=6.0.0-1693 --liteserv-platform=ios --enable-file-logging testsuites/CBLTester/upgrade_tests/test_cbl_upgrade.py

CBL-2.1.5 iOS db is available here - https://github.com/couchbaselabs/mobile-testkit/tree/feature/cbl-upgrade-testing/CBLClient/Apps/CBLTestServer-iOS/Databases/travel-sample-encrypted-2.1.5.cblite2

**Comment by jayahariv** [comment]
This is fixed as part of 2.5.1 release

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
