### ISSUE TITLE
Anyway to disable sqlite3 WAL journaling during sync

### ISSUE THREAD

**Issue by Shagans982** [couchbase/couchbase-lite-ios#2514]
Hello, 

We are running the Swift version which sync from Couchase Server 6.0. Our users seem to be running into storage limitations on their devices due to the bulging sqlite3.wal file. Is there a way to disable this, freeing up storage space while still allowing writes to occur? 

What are the potential downsides of this if it is possible.

**Comment by jayahariv** [comment]
Could you please let us know how long and how much data is synced from gateway to CBL, which is causing the bumping of WAL file? 

Is there a way to close the database when not in use, which will recycle WAL file and clean up the disk.

**Comment by Shagans982** [comment]
We are only pulling and the dataset is 172mb uncompressed - however, our WAL file fairy consistently  gets to 2.5GB and on occasion gets to 5GB. This is our initial sync since we prefer not to load up the app bundle directly. We could monitor the storage compacity and open/close the connection when needed keeping the WAL at a more manageable size, however, if we can keep the connection open, that would be preferred.

**Comment by jayahariv** [comment]
Unfortunately, keeping the replicator running and closing database(or disabling WAL), we don't support this. 

We can think of workaround as to stop the replicator periodically.

**Comment by Shagans982** [comment]
Does that sizing sound correct? 172mb -> 2.5 or 5gbs?

**Comment by Shagans982** [comment]
Also, if we were to manually stop the replicator to manage the WAL size manually.. is this an option?

**Comment by pasin** [comment]
According to this [doc](https://www.sqlite.org/wal.html), I would think that periodically stop and start the replicator for the large initial sync would work as it will allow SQLite to cleanup the WAL file as there will be no active SQLite Connection.

**Comment by pasin** [comment]
> We are only pulling and the dataset is 172mb uncompressed (taking a few hours or so to pull down)

This doesn't seem right. Can you enable `Replicator` log and share?

**Comment by jayahariv** [comment]
closing this, since we cannot do anything further with disabling WAL while syncing.
