### ISSUE TITLE
Store raw JSON

### ISSUE THREAD

**Issue by klische** [couchbase/couchbase-lite-ios#2537]
Is there API in Couchbase lite to store stringified JSON directly? I'm looking for something similar to https://docs.couchbase.com/sdk-api/couchbase-java-client-2.5.9/com/couchbase/client/java/document/RawJsonDocument.html and https://developer.couchbase.com/documentation/server/3.x/developer/java-2.1/documents-basics.html (RawJsonDocument). So something like this:

```
// write the raw data
String content = "{\"hello\": \"couchbase\", \"active\": true}";
bucket.upsert(RawJsonDocument.create("rawJsonDoc", content));
```

Except, in the place of bucket, it would be the database.saveJSONDocument(StringifiedJSON)

--------
* Version:   2.5.3
* Client OS: iOS 12.4
* Server:    Couchbase lite (no server)

**Comment by pasin** [comment]
CBL doesn't have the API to store JSON string directly. The JSON string needs to be parsed to (Swift) dictionary first. When having the JSON dictionary, you can either create a new MutableDocument with the dictionary or set the dictionary to a document.

```Swift
let json: [String: Any] = ["foo": "bar"]
let doc = MutableDocument(id: "doc1", data: json)
try db.save(doc)
...
let doc = document.toMutable()
doc.setData(json)
try db.save(doc)
```

**Comment by pasin** [comment]
Close as not the issue.

**Comment by klische** [comment]
@pasin Are there any plans to implement API to store JSON strings directly?
