### ISSUE TITLE
FTS and database alias

### ISSUE THREAD

**Issue by fedal-mas** [couchbase/couchbase-lite-ios#2540]
Hi, 

I'm trying to do the following query on CBL:

```swift
QueryBuilder
    .select(SelectResult.expression(Meta.id.from("db")))
    .from(DataSource.database(db).as("db"))
    .where(
        Expression.property("type").from("db").equalTo(Expression.string("A"))
        .and(FullTextExpression.index("FTSIndex").match("test"))
    )
    .orderBy(Ordering.expression(FullTextFunction.rank("FTSIndex")).descending())
    .limit(Expression.int(Int.max))
```

But I'm getting the following error: 

> CouchbaseLite Database WARNING: {DB#10} SQLite error compiling statement "SELECT "db".db.rowid, offsets(fts1."kv_default::FTSIndex"), fl_result("db".key) FROM kv_default AS "db" JOIN "kv_default::FTSIndex" AS fts1 ON fts1.docid = "db".rowid WHERE (fl_value("db".body, 'type') = ‘A’ AND fts1."kv_default::FTSIndex" MATCH 'test') AND ("db".flags & 1 = 0) ORDER BY rank(matchinfo(fts1."kv_default::FTSIndex")) DESC LIMIT MAX(0, 9223372036854775807) OFFSET MAX(0, 0)": no such column: db.db.rowid

Is it expected to happen? 

Also, am I able to make a FTS and a Join on the same query?

Thanks!

--------
* Version:   2.6.0
* Client OS: iOS 13.1

**Comment by jayahariv** [comment]
thanks @fedal-mas, we will investigate further and update. 

Jira ticket: [CBL-369](https://issues.couchbase.com/browse/CBL-369)

**Comment by jayahariv** [comment]
fixed here https://github.com/couchbase/couchbase-lite-core/commit/b7a94380bdd5ade8d6efa74fadfacb6e586cfd56
