### ISSUE TITLE
Xcode 11 build

### ISSUE THREAD

**Issue by ngAvaddon** [couchbase/couchbase-lite-ios#2546]
Is there an eta for Swift 5.1 release?

--------
* Version:   2.6.0
* Client OS: iOS 13, Swift

**Comment by jayahariv** [comment]
@rajagp

**Comment by djpongh** [comment]
Our build is currently going through testing. While we don't expect anything to show up we like to be sure. We should have something available by the end of the week.

**Comment by djpongh** [comment]
Apple just released a C2 so we are starting over in our testing. Don't think we'll make this week. Also worried if Apple is going to release a C3...

**Comment by kenosan** [comment]
Any updates? I have several projects that use the framework and being blocked because of this compile time error: 

> Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler: $PROJECT_PATH/Pods/CouchbaseLite-Swift/iOS/CouchbaseLiteSwift.framework/Modules/CouchbaseLiteSwift.swiftmodule/x86_64.swiftmodule

Any recommendations on workaround (apart from going back to XCode 10) until release is done?

**Comment by stockley-ca** [comment]
Guys as a related feature request, for future Xcode releases, would it be possible to make your release candidate/beta/test builds available as pre-release pods (https://guides.cocoapods.org/making/making-a-cocoapod.html#cocoapods-versioning-specifics) for those of us who adopt Xcode releases quickly?

I have been scouring your forums for information that might un-block my projects that rely on CBL and it looks like my options are basically build the code myself (which your documentation recommends against), downgrade Xcode or wait until you get this out.  I'd much rather have been in a position to keep moving and potentially help you out by reporting whatever bugs I discover than spend time on temporary workarounds.

**Comment by newlegendmedia** [comment]
**Critical** - Any progress or workaround for this? I cannot build with Xcode 11 and that's the only way I can fix an issue that was just introduced by iOS 13.1 on iPhone.

**Comment by jayahariv** [comment]
We are working on releasing it by this week.

If you are a Enterprise customer, you need to wait until the build is ready. 

If you are a Community user, you can wait or build yourself the framework [how to build wiki page](https://github.com/couchbase/couchbase-lite-ios/wiki/Building-Couchbase-Lite)

**Comment by dariopellegrini** [comment]
@jayahariv building worked (oxygen is mandatory).
Waiting for your release.

Thank you.

**Comment by jayahariv** [comment]
Closing since the latest release is available via dowloads page, cocoapod and carthage.
