### ISSUE TITLE
putExistingRevisionWithProperties in Couchbase Lite 2.x?

### ISSUE THREAD

**Issue by suzhaev** [couchbase/couchbase-lite-ios#2556]
We now migrating to Couchbase 2.5 from Couchbase 1.4 and I did't see the ability to insert initial documents on first app launch after login (documents are account specific and prebuild database do not suitable)

**Comment by suzhaev** [comment]
In Couchbase 1.4 we requested all user documents via REST API and inserting it to database. This method allowed us to instantly download all user documents, then we started pull replication, which synchronized the missing changes

**Comment by pasin** [comment]
Currently we do not support this functionality. In 2.0, we have decided to put the revision concept behind the scene. Also the putExistingRevisionWithProperties is not a common database operation and is mostly used for replication. Can you download and insert the document in the database using the normal save operation?

**Comment by djpongh** [comment]
Closing. Please reopen if you Pasin's suggestion doesn't work.
