### ISSUE TITLE
Conflict error when updating a document multiple times in transaction block

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/couchbase-lite-ios#256]
Test Definition: Create a document and update a value for n times. 
When updating the value using the "in-transaction" block an exception is received. 

The bug can be reproduced by the following code: 
https://github.com/couchbaselabs/iOS-WorkerBee/blob/Performance_Testing_2/Tests/Test8_DocRevisions.m

The exception does not occur when the document revision is done without a in-transaction block.

**Comment by zgramana** [comment]
@snej: @pasin needs to discuss some side effects of the PR with you.

**Comment by snej** [comment]
Fixed one week before its first anniversary :D

**Comment by jschmid** [comment]
The [documentation](http://developer.couchbase.com/mobile/develop/guides/couchbase-lite/native-api/document/index.html#updating) still links to this issue. Should it be updated?

**Comment by snej** [comment]
I'll file an issue against the docs — thanks for pointing it out.
