### ISSUE TITLE
App is crashing when locking device before hearing response from syncing socket

### ISSUE THREAD

**Issue by omegapatten** [couchbase/couchbase-lite-ios#2598]
When I lock the device before the socket has started receiving a response my app crashes. The device does have a passcode. So I'm assuming the database is being accessed after the "isProtectedDataAvailable" is false. Seems to be more common when network connectivity is slow.

Crashed: DB->wss://***************
0  CouchbaseLiteSwift             0x10551198c sqlite3_backup_init + 37836
1  CouchbaseLiteSwift             0x1055111a8 sqlite3_backup_init + 35816
2  CouchbaseLiteSwift             0x1055132bc sqlite3_backup_init + 44284
3  CouchbaseLiteSwift             0x10551ab44 sqlite3_backup_step + 26728
4  CouchbaseLiteSwift             0x105515120 sqlite3_backup_step + 3652
5  CouchbaseLiteSwift             0x105526a6c sqlite3_step + 12572
6  CouchbaseLiteSwift             0x105523b1c sqlite3_step + 460
7  CouchbaseLiteSwift             0x1054bd7c0 SQLite::Statement::executeStep() + 40
8  CouchbaseLiteSwift             0x10547cb40 litecore::SQLiteDataFile::intQuery(char const*) + 76
9  CouchbaseLiteSwift             0x10547c4b4 litecore::SQLiteDataFile::optimizeAndVacuum() + 40
10 CouchbaseLiteSwift             0x10547b36c litecore::SQLiteDataFile::close() + 108
11 CouchbaseLiteSwift             0x10547ce48 litecore::SQLiteDataFile::~SQLiteDataFile() + 40
12 CouchbaseLiteSwift             0x10547b2e8 litecore::SQLiteDataFile::~SQLiteDataFile() + 12
13 CouchbaseLiteSwift             0x1054b77f4 c4Internal::Database::~Database() + 424
14 CouchbaseLiteSwift             0x105471134 c4Database::~c4Database() + 56
15 CouchbaseLiteSwift             0x1054878dc litecore::repl::DBWorker::computeActivityLevel() const + 776
16 CouchbaseLiteSwift             0x105487530 c4socket_received + 124
17 libdispatch.dylib              0x182cb0aa0 _dispatch_call_block_and_release + 24
18 libdispatch.dylib              0x182cb0a60 _dispatch_client_callout + 16
19 libdispatch.dylib              0x182cba9b4 _dispatch_queue_serial_drain$VARIANT$mp + 608
20 libdispatch.dylib              0x182cbb2fc _dispatch_queue_invoke$VARIANT$mp + 336
21 libdispatch.dylib              0x182cbbcc8 _dispatch_root_queue_drain_deferred_wlh$VARIANT$mp + 340
22 libdispatch.dylib              0x182cc4098 _dispatch_workloop_worker_thread$VARIANT$mp + 668
23 libsystem_pthread.dylib        0x182fe3e70 _pthread_wqthread + 860
24 libsystem_pthread.dylib        0x182fe3b08 start_wqthread + 4

**Comment by jayahariv** [comment]
which version of CouchbaseLiteSwift is being used?

**Comment by jayahariv** [comment]
@omegapatten can you give more hints on how to reproduce this issue? the above steps are not crashing.

**Comment by jayahariv** [comment]
Reference to [CBL-622](https://issues.couchbase.com/browse/CBL-622)

**Comment by jayahariv** [comment]
@omegapatten Could you include [console logs](https://docs.couchbase.com/couchbase-lite/2.6/swift.html#logging) (level = verbose, domain = all) during the crash?

**Comment by snej** [comment]
The SQLite symbols in the backtrace are wrong, which makes this hard to figure out. SQLite certainly shouldn't be crashing — if it gets filesystem errors reading/writing the database, it should just fail cleanly.

**Comment by jayahariv** [comment]
@omegapatten do you have any updates on how to repro or logs during the crash?

**Comment by omegapatten** [comment]
Sorry for the slow reply. Trying to gather more tangible information on this.
This is occurring in our app for both CBLite v2.6.3. 
Still occurring after backgrounding the application. I'm tracking the socket create by Couchbase using Charles proxy. Even after I've locked the device the socket lingers open. When the socket finishes the "handshake" to start syncing is when I see the crash. 
I'm running this off of a debug build but we have a production build out there that appears to have the same crash.

I'll see if I can get console logs shortly.

**Comment by jayahariv** [comment]
@omegapatten  did you get a chance to gather the console logs?

**Comment by jayahariv** [comment]
Closing this issue, due to inactivity. Please feel free to open it when you get more information.
