### ISSUE TITLE
CocoaHTTPServer should be a dependency to CouchbaseListener, not built into CouchbaseListener framework

### ISSUE THREAD

**Issue by mz2** [couchbase/couchbase-lite-ios#260]
CocoaHTTPServer and classes derived from it are built into CouchbaseListener but not exported as symbols. Wouldn't it be better to include CocoaHTTPServer as a separate build target that CouchbaseListener depends on? This way you could use CouchbaseListener in a binary which needs to link against CouchbaseListener and other code which needs to link against CocoaHTTPServer (I happen to be using CouchbaseListener in a build target which also uses RoutingHTTPServer for some extra functions in DEBUG builds to ease development of web view / Cocoa interactions -- and RoutingHTTPServer itself depends on CocoaHTTPServer). 

If you think this is a good idea to do, I'd be happy to separate the CocoaHTTPServer code into a separate target for OSX and iOS.

**Comment by jayahariv** [comment]
Closing 1.x issue!
