### ISSUE TITLE
Carthage and Swift 5.1.3

### ISSUE THREAD

**Issue by skela** [couchbase/couchbase-lite-ios#2602]
Unable to include Couchbase Lite iOS via Carthage with Xcode 11.3

Incompatible Swift version - framework was built with 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7) and the local version is 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15).

--------
* Version:   2.6.3
* Client OS: macOS Catalina 10.15.2

**Comment by pasin** [comment]
In general, this becomes a Carthage issue that doesn't support binary compatible (See https://github.com/Carthage/Carthage/issues/2887).

@jayahariv could you please check this if we need to upgrade XCode on the build system?

**Comment by jayahariv** [comment]
our build machine is on 11.3, for mercury, it should be good.

**Comment by jayahariv** [comment]
Please use the latest release of CouchbaseLiteSwift, 2.7.0 which is built using 11.3 latest.
