### ISSUE TITLE
Intermittent crash when mutating data and app is in background

### ISSUE THREAD

**Issue by rob-keepsafe** [couchbase/couchbase-lite-ios#2609]
Hi there 👋 

We've seen a couple of crashes during development, and they appear to happen when mutating records while the app is in the background (we don't set `allowReplicatingInBackground` at all fyi)

I've symbolicated the two crashes and attached them since they both have similar call sites.

[symbolicated.txt](https://github.com/couchbase/couchbase-lite-ios/files/4228528/symbolicated.txt)

[symbolicated_2.txt](https://github.com/couchbase/couchbase-lite-ios/files/4228533/symbolicated_2.txt)

I only have a little bit of stack trace for one of the crashes and it looks like we were uploading some data and then mutating a document to set a boolean value on it (e.g. `isUploaded = true`)

--------
* Version:   2.7.0
* Client OS: iOS
* Server:  enterprise 6.5

**Comment by jayahariv** [comment]
Hi @rob-keepsafe, 

Thanks for reporting the issue, but it seems like the the stack frames are pointing to the wrong call stack. 

Can you provide some more details mentioned below, 
1. if you can reproduce this crash with a unit test or sample project, please share. 
2. enable the logs(level = .debug) in Xcode, and copy the full logs to see what events are happening. Once it crashes, in the LLDB console, type `bt` to get the back trace, include that as well. 

Could you please also share the information about the device you are using, including the password protection info.

If you are an enterprise customer, you could contact support for more faster communication.

**Comment by rob-keepsafe** [comment]
Thanks @jayahariv ; I'll see if we can get someone to repro it locally since it happened on a release build

I'll close this issue for now until we have more information
