### ISSUE TITLE
[Swift] Database.inBatch API is misleading (and potentially dangerous)

### ISSUE THREAD

**Issue by dtorres** [couchbase/couchbase-lite-ios#2613]
The `Database.inBatch` method accepts a throwing closure however the underlying Objective-C does not react to failures within this block

As currently implemented, this will stop execution of the closure but any changes executed up to that point will still be committed to the database.

This is even worse from the callsite perspective as the error from the closure is thrown back and developers may assume that an error indicates nothing was committed.

--------------------

This method should either be amended to:
- allow the Obj-C side receive the error and stop the transaction all together.

or

- not take a throwing closure

**Comment by emarc-m** [comment]
Hello, for reference this is the source from Android `couchbase-lite`. This looks like the correct behavior and should have parity with both platforms.

```
/**
 * Runs a group of database operations in a batch. Use this when performing bulk write operations
 * like multiple inserts/updates; it saves the overhead of multiple database commits, greatly
 * improving performance.
 *
 * @param runnable the action which is implementation of Runnable interface
 * @throws CouchbaseLiteException Throws an exception if any error occurs during the operation.
 */
public void inBatch(@NonNull Runnable runnable) throws CouchbaseLiteException {
    Preconditions.checkArgNotNull(runnable, "runnable");
    synchronized (lock) {
        mustBeOpen();
        try {
            final C4Database db = getC4Database();
            boolean commit = false;
            db.beginTransaction();
            try {
                runnable.run();
                commit = true;
            }
            finally {
                db.endTransaction(commit);
            }
        }
        catch (RuntimeException e) {
            throw new CouchbaseLiteException(e);
        }
        catch (LiteCoreException e) {
            throw CBLStatus.convertException(e);
        }
    }
    postDatabaseChanged();
}
```

**Comment by emarc-m** [comment]
Note: This is from the Couchbase enterprise on both platforms.

**Comment by pasin** [comment]
Yes, that is an implementation bug in Swift. Thanks for reporting this.

**Comment by jayahariv** [comment]
Jira ticket for tracking this issue: [CBL-717](https://issues.couchbase.com/browse/CBL-717)

**Comment by jayahariv** [comment]
fix is committed  to master > https://github.com/couchbase/couchbase-lite-ios/commit/d13fb026c06a5ef6bbf7e399ae215709376a9aec

**Comment by dtorres** [comment]
Hey @jayahariv, thanks for the quick fix! I left some comments on the PR for your consideration
