### ISSUE TITLE
Save fails when NSDate inserted with [CBLMutableDocument setData]

### ISSUE THREAD

**Issue by hyling** [couchbase/couchbase-lite-ios#2619]
**Describe the bug**
Fails to save CBLMutableDocument when NSDate is inserted with [CBLMutableDocument setData]

**To Reproduce**
```
    CBLMutableDocument *mDoc = [CBLMutableDocument document];
    [mDoc setDate:[NSDate date] forKey:@"date"];
    XCTAssertTrue([self.db saveDocument:mDoc error:nil]);  // pass
 
    NSDictionary *dataDict = @{@"date" : [NSDate date]};
    mDoc = [CBLMutableDocument document];
    [mDoc setData:dataDict];
    XCTAssertTrue([self.db saveDocument:mDoc error:nil]); // fail, Fleece error 4.
```

**Expected behavior**
expected both saves to succeed

**Platform (please complete the following information):**
 - Device: iPhone XR & iPhone 8 Simulator
 - OS: iOS 13
 - Couchbase Version: CouchbaseLiteObjective-C 2.7.0
 - Sync Gateway Version: NA

**Comment by jayahariv** [comment]
thanks @hyling  for reporting it, corresponding Jira ticket for tracking it [CBL-745](https://issues.couchbase.com/browse/CBL-745)

**Comment by pasin** [comment]
Closed as fixed.
