### ISSUE TITLE
Suport for Xcode 11.4/Swift 5.2

### ISSUE THREAD

**Issue by mihah** [couchbase/couchbase-lite-ios#2627]
After Xcode upgrade project build failed with error: Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2 compiler

Platform :
 - OS: macOS 10.15.3, Xcode 11.4
 - Couchbase Version: CouchbaseLiteSwift 2.7.0

**Comment by jayahariv** [comment]
Are you using Carthage or direct downloaded binary?

**Comment by mihah** [comment]
Cocoapods

**Comment by jayahariv** [comment]
Can you share a sample app which can reproduce the error?

**Comment by jayahariv** [comment]
Jira tracking ticket 
https://issues.couchbase.com/browse/CBL-863

**Comment by jayahariv** [comment]
Also could you please share more information, what all errors you are receiving(probably with a screenshot), steps to reproduce(if you can).

**Comment by mihah** [comment]
Update to 2.7.1 fixed the issue for me
