### ISSUE TITLE
Xcode 11.4.1 with 2.7.1 LLDB error

### ISSUE THREAD

**Issue by MetaImi** [couchbase/couchbase-lite-ios#2630]
Hi

We updated our project from 2.7.0 to 2.7.1 and LLDB stopped working with the following error:
error: Couldn't IRGen expression, no additional error

If we switch back to 2.7.0 it works. 

Project setup: 
Core: Standalone pod library with CouchbaseLite-Swift-Enterprise dependency 
App: Integrates core with pod. 

Also tried with a new project, which just integrates the CouchbaseLite-Swift-Enterprise without any framework. Same result.

**Comment by jayahariv** [comment]
Did you try this?
https://stackoverflow.com/questions/43977271/lldb-couldnt-irgen-expression

**Comment by MetaImi** [comment]
As a programmer you can be sure that I tried to google it :) thats why I wrote that I just created an empty project, add Couchbase as a pod and add a breakpoint into appdelegate and the result is the same. No unit test, container framework involved.

**Comment by jayahariv** [comment]
tracking ticket https://issues.couchbase.com/browse/CBL-896

**Comment by matteosist** [comment]
Hi, there is a delivery date for this issue? It's a little frustrating cannot use the debugger.

**Comment by MetaImi** [comment]
You can switch back to 2.7.0. That is working for ua

**Comment by matteosist** [comment]
Unfortunately we cannot switch back to previous version because 2.7.1 contains a fix we were waiting and is a choice mandatory for us. Anyway thanks for suggestion.

**Comment by jayahariv** [comment]
Workaround as of now, is to delete the dSYM file shipped or use carthage build. In both case, the compile units will be empty which will result in not able to debug the CBL library but able to debug parent project.

**Comment by jayahariv** [comment]
Closing this task, and fix will be available in next release. Updates can be found in Jira ticket.
