### ISSUE TITLE
Missing 2.7.1 tag

### ISSUE THREAD

**Issue by johnngoi** [couchbase/couchbase-lite-ios#2631]
**Describe the bug**
From the SDK download page, we can download 2.7.1. But from the GitHub releases, I do not see 2.7.1 release/tag

**To Reproduce**
Go to Github.com

**Expected behavior**
Expect to see a 2.7.1 release

**Comment by jayahariv** [comment]
Tagged! Please check again

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by johnngoi** [comment]
@jayahariv thanks, I see it!
