### ISSUE TITLE
Release Version Compatible with Xcode 11.5/Swift 5.2.4

### ISSUE THREAD

**Issue by SteveHallSDHO** [couchbase/couchbase-lite-ios#2671]
**Describe the bug**
Cannot upgrade to 2.7.1 SDK using carthage

**To Reproduce**
Followed these instructions: https://docs.couchbase.com/couchbase-lite/current/swift.html
1. Upgraded to Xcode to 11.5
2. Updated cartfile to point to 2.7.1
3. Ran carthage update --platform ios.

Received this unsuccessful result:
*** Downloading binary-only framework CouchbaseLite-Enterprise at "https://packages.couchbase.com/releases/couchbase-lite-ios/carthage/CouchbaseLite-Enterprise.json"
Incompatible Swift version - framework was built with 5.2.2 (swiftlang-1103.0.32.6 clang-1103.0.32.51) and the local version is 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53).

**Expected behavior**
Successful carthage

**Platform (please complete the following information):**
 - OS: iOS 13.5
 - Couchbase Version: CouchbaseLiteSwift 2.7.1

**Comment by johnngoi** [comment]
related to

https://github.com/couchbase/couchbase-lite-ios/issues/2644

**Comment by johnngoi** [comment]
@jayahariv  @pasin  this is blocking us from adopting CouchbaseLiteSwift 2.7.1

**Comment by jayahariv** [comment]
Could you either choose Xcode 11.4.1 as default Xcode(while carthage update) or build the latest Carthage from source.

**Comment by johnngoi** [comment]
@jayahariv  the entire engineering org is moving to Xcode 11.5 due to iOS security vulnerabilities. when can we get a buildable release that will work when we do `carthage update` for Xcode 11.5

do we expect CouchbaseLiteSwift to be this rigid and require explicit Swift versions in the future?

**Comment by jayahariv** [comment]
The error you described is happening with the Carthage(its version lock). Which they taken care in their master branch(https://github.com/Carthage/Carthage/pull/2902), since then no public release happened(last release happened on Oct 2019). 

CouchbaseLiteSwift has already enabled the module stability, and the binary will be compatible with future swift compilers.

**Comment by jayahariv** [comment]
Closing this, since this is not a Couchbase issue.
