### ISSUE TITLE
Cannot build on macOS Catalyst

### ISSUE THREAD

**Issue by NilsBerni** [couchbase/couchbase-lite-ios#2712]
**Describe the bug**

**To Reproduce**
Share a unit test or sample project or steps to reproduce the behavior
1. Unit test or 
2. Sample project or 
3. Steps to reproduce it. 

**Expected behavior**

**Logs** 
Sharing logs will make debugging and troubleshooting easier. 
 - Enable console/file logging: [reference](https://docs.couchbase.com/couchbase-lite/2.7/swift.html#logging)
 - Attach the logs(hide any sensitive data from it before submitting).

**Screenshots**

**Platform (please complete the following information):**
 - Couchbase Version [e.g. CouchbaseLiteSwift 2.7.0]
 - Synch Gateway Version [e.g. Sync Gateway 2.7.0]

**Additional context**

**Comment by jayahariv** [comment]
Closing this, as this is not an issue, but more like an enhancement and we haven't prioritized yet. If you are an enterprise customer please request it to support, which might impact the priority of the task. Else, please wait for an announcement.
