### ISSUE TITLE
CBL 2.7.1 Failed to compile with XCode 12

### ISSUE THREAD

**Issue by WarWithinMe** [couchbase/couchbase-lite-ios#2723]
**Describe the bug**
When compiling CBL 2.7.1 with XCode 12, Swift 5.3, there are many compile errors.

**To Reproduce**
Clone CBL 2.7.1, and use XCode 12 to build the project.

**Expected behavior**
XCode 12 should compile without error.

**Platform (please complete the following information):**
 - OS: MacOS 10.15.5
 - Couchbase Version: 2.7.1
 - XCode: 12 beta-5

**Comment by pasin** [comment]
The code in master branch should be able to compile with XCode 12 now. If not, please circle back. Thanks.
