### ISSUE TITLE
Records on device periodically not replicating with server (Critical Bug)

### ISSUE THREAD

**Issue by SteveHallSDHO** [couchbase/couchbase-lite-ios#2749]
**Describe the bug**
Periodically we see that Couchbase records on the device are not replicated to the server.  Users have to kill the app and restart it, or in some cases, reboot their devices in order for the records to be pushed to the server.  We have set our replicator configuration to be continuous.

**To Reproduce**
1. The user creates a new Couchbase record on their device.
2. Check the Couchbase server via a custom web app.  The record is not replicated.
3. Kill the app and restart it.
4. Check the Couchbase server via a custom web app.  The records are now replicated.

**Expected behavior**
Any record that is created on the device should appear on the Couchbase server within seconds.  Restarting the app should not be necessary.

**Logs** 
When testing in the Xcode simulator, I have seen these error messages in the log indicating issues with replication:

2020-09-14 11:51:34.468200-0700 MyAppQA[98022:13559334] CouchbaseLite Network WARNING: {C4SocketImpl#7}==> litecore::repl::C4SocketImpl wss://xxx.com/sync_gateway/cache/_blipsync @0x7fee316924a0
2020-09-14 11:51:34.468416-0700 MyAppQA[98022:13559334] CouchbaseLite Network WARNING: {C4SocketImpl#7} Unexpected or unclean socket disconnect! (reason=errno, code=54)
2020-09-14 11:51:34.469105-0700 MyAppQA[98022:13559336] CouchbaseLite Replicator ERROR: {Repl#8}==> litecore::repl::Replicator /Users/xxxx/Library/Developer/CoreSimulator/Devices/82A8ADBA-A20D-459B-8F40-BD3818D90BAD/data/Containers/Data/Application/E7C1438B-C6A3-47B7-A4C0-47B6DC58236E/Library/Application Support/CouchbaseLite/qa-cache.cblite2/ ->wss://xxx.com/sync_gateway/cache/_blipsync @0x7fee32196c28
2020-09-14 11:51:34.469467-0700 MyAppQA[98022:13559336] CouchbaseLite Replicator ERROR: {Repl#8} Got LiteCore error: POSIX error 54 "Connection reset by peer"

**Platform (please complete the following information):**
 - Device: Any iPhone, iPad, and Xcode simulator
 - OS: 13.x
 - CouchbaseLite 2.7.1

**Additional context**
- Do you have recommended way that we can debug these sync issues?
- Is there way we can check the replicator status, and if there's an issue, do something to resolve it?  Because restarting the app fixes the issue, there might be something programmatically we can do fix the syncing issue.

**Comment by pasin** [comment]
Did the replicator stopped or retired to connect after getting the error above? I expected that the replicator should try to reconnect. To understand the issue, can you provide the full log both CBL and Sync Gateway logs, when the replicator is supposed to replicate the change and it doesn't do that? On CBL, please enable verbose logging for Replicator and Network domain.

**Comment by SteveHallSDHO** [comment]
Hi Pasin...How do I know if the replicator is stopped?  We've set it to be continuous replication, I don't know of any monitoring I should be doing, please advise.

In the meantime, I'll work with my team to get the logs you've requested.

**Comment by jayahariv** [comment]
Even though its not actual sometimes, for debugging purpose you can try using `status.completed == status.total && status.activity == .idle`

> The replication change object also has properties to track the progress (change.status.completed and change.status.total). But since the replication occurs in batches and the total count can vary through the course of a replication, those progress indicators are not very useful from the standpoint of an app user. Hence, these should not be used for tracking the actual progress of the replication.

Replication Status: 
https://docs.couchbase.com/couchbase-lite/2.7/swift.html#replication-status

Logging: 
https://docs.couchbase.com/couchbase-lite/2.7/swift.html#logging

**Comment by SteveHallSDHO** [comment]
@jayahariv: Trying to do the verbose logging as was suggested.   I have implemented the logging as shown here:

```swift
            let tempFolder = NSTemporaryDirectory().appending("CouchbaseLiteLog")
            Database.log.file.config = LogFileConfiguration(directory: tempFolder)
            Database.log.file.level = .verbose
```
However, when I go into Xcode to view the device logs, I don't see the CouchbaseLiteLog that I thought I created.  I am running Xcode 11.7 and did "Window/Devices and Simulator" and clicked "View Device Logs" button to see the logs.

**Comment by jayahariv** [comment]
Xcode Devices Logs includes any crash logs, the logs which you saved will be available in the location you specified, which is TemporaryDiectory > CouchbaseLiteLog. 

Could you programmatically read/copy them and get it out? 

You could also, try using console log instead of file logging for easy copy pasting of logs(if you can debug the app). 
`Database.log.console.level = .verbose`, you will see the logs in Xcode console itself.

**Comment by SteveHallSDHO** [comment]
Okay, I've figured out how to properly find the file logs on an actual device.  I'm almost there!  However, the logs are in binary format.  The documentation says I should be able to configure the log to store in plain text.  How do I that?  I've fiddled around with cbl-log but I cannot figure out how to get that tool to work and would much rather go the plain text route as other team members will be examining the logs as well.

**Comment by jayahariv** [comment]
```
let config = LogFileConfiguration(directory: tempFolder)
config.usePlainText = true
Database.log.file.config = config
```

**Comment by SteveHallSDHO** [comment]
Okay, we are all set with being able to create the logs.  I will work with my QA team to get us the relevant logs.  Once I'm able to get the logs, Is there a secure place where I can upload them to for your analysis?

**Comment by SteveHallSDHO** [comment]
I have the logs from my QA team.  A team member has also opened up a ticket with Support for this issue, so I've uploaded the CBLite log files there.  

https://support.couchbase.com/hc/en-us/requests/36391?page=1

**Comment by jayahariv** [comment]
Since we already have a support ticket, closing this here.
