### ISSUE TITLE
CocoaPods installation fails for CouchbaseLite-Swift

### ISSUE THREAD

**Issue by Alexandru981** [couchbase/couchbase-lite-ios#2756]
**Describe the bug**
When trying to run `pod install` for the `CouchbaseLite-Swift` the operation fails do, most likely, to a private resource. This is happening for an iOS project which supports iOS 11 and up and is using Swift.

**To Reproduce**
1. Add `pod 'CouchbaseLite-Swift'` to the Podfile
2. Run `pod install`

**Expected behavior**
The `pod install` operation completes successfully.

**Logs** 
Here is the cocoa pods log:
```
[!] Error installing CouchbaseLite-Swift
[!] /usr/bin/curl -f -L -o /var/folders/wk/45np229x1wv_9vy7jgs8_sdsk8hppr/T/d20201002-50762-slrcch/file.zip https://packages.couchbase.com/releases/couchbase-lite-ios/2.8.0/couchbase-lite-swift_community_2.8.0.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 403
```

**Platform (please complete the following information):**
 - Device: iPhones and iPad
 - OS: iOS11 and up
 - Couchbase Version CouchbaseLiteSwift 2.7.0

**Comment by pasin** [comment]
It's weird that it tried to download 2.8 version which is not available yet.

**Comment by jayahariv** [comment]
Could you please specify the exact version for now?
```
target '<target>' do
  use_frameworks!

  pod 'CouchbaseLite-Swift-Enterprise', "~> 2.7.1"

end

**Comment by Alexandru981** [comment]
Thanks @jayahariv !

It seems to be fixed now.

I was indeed using 2.7.1:

`pod 'CouchbaseLite-Swift', "~> 2.7.1"`

**Comment by jayahariv** [comment]
yea, the issue got resolved by updating the Cocoapod specs.
