### ISSUE TITLE
please publish XCode 12 - compatible build to cocoapods

### ISSUE THREAD

**Issue by vonovak** [couchbase/couchbase-lite-ios#2758]
Hello, 
when building a release build for a simulator with XCode 12.0.1, I'm getting

```
Failed to build module 'CouchbaseLiteSwift' from its module interface; the compiler that produced it, 'Apple Swift version 5.2.2 (swiftlang-1103.0.32.6 clang-1103.0.32.51)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)'
```

podfile (just the relevant part)

```
platform :ios, '10.0'


target 'abcTests' do
  pod 'CouchbaseLite-Swift', '2.7.1'
end

target 'abc' do
    pod 'GoogleSignIn', '~> 5.0.2'
    pod 'CouchbaseLite-Swift', '2.7.1'
    pod 'OHAttributedStringAdditions'
    ...
  

end
```

can you please publish a release that is built using XCode 12? Thank you!

**Comment by jayahariv** [comment]
what version of `pod` you are using?

**Comment by vonovak** [comment]
@jayahariv I'm using `1.9.3`

**Comment by jayahariv** [comment]
We have enabled the module stability flag, `BUILD_LIBRARY_FOR_DISTRIBUTION`, so this shouldn't be an issue. Also I double checked with the same pod version and Xcode, from my machine, its working fine. 

Could you share a sample project, just a podfile and project, which I can try and see. If there is something I am missing.

**Comment by vonovak** [comment]
after upgrading to 2.8.0, the error changed to 

```
Module 'CouchbaseLiteSwift' was created for incompatible target arm64-apple-ios9.0: abc/ios/Pods/CouchbaseLite-Swift/iOS/CouchbaseLiteSwift.framework/Modules/CouchbaseLiteSwift.swiftmodule/arm64.swiftmodule
```
in my case, it was fine to work around it as in https://stackoverflow.com/a/63622570/2070942

Since the problem is gone for me, I'll not investigate further, feel free to close if you want @jayahariv 

thanks!
