### ISSUE TITLE
Exception rebuild bitcode

### ISSUE THREAD

**Issue by matteosist** [couchbase/couchbase-lite-ios#2760]
**Describe the bug**
Hi, after update Couchbase to the latest version 2.8.0 (from 2.7.1) i cannot release my app due to an exception during bitcode compiling.

**To Reproduce**
1) Update Couchbase version to 2.8.0
2) Archive
3) Release Ad Hoc with "Rebuild from Bitcode" enabled

**Logs** 
[IDEDistributionPipeline.log](https://github.com/couchbase/couchbase-lite-ios/files/5407480/IDEDistributionPipeline.log)

**Platform (please complete the following information):**
 - IDE: Xcode 12.0.1
 - Cocoapods 1.9.3
 - Couchbase Version [CouchbaseLiteSwift EE 2.8.0]

**Comment by jayahariv** [comment]
Have you tried disabling code coverage? Please let us know the result please. 

```
Apple Staff :

This is a known bug: The linker does not encode -sectalign correctly with bitcode. 

The work around (as you surmised) is to disable code coverage. Apparently, you have not actually disabled code coverage to this target.
``` 
https://developer.apple.com/forums/thread/662947

**Comment by matteosist** [comment]
Hi @jayahariv, i tried right now with code coverage disabled but i get the same result.

Here the new logs
[IDEDistributionPipeline.log](https://github.com/couchbase/couchbase-lite-ios/files/5410004/IDEDistributionPipeline.log)

Any other suggestions?

Many thanks

**Comment by jayahariv** [comment]
Could you check with Xcode 12.1 released, which includes a fix for bit code enabled build failure.

```
Resolved
Fixed a bitcode issue that could cause App Store processing to fail, resulting in an “ITMS-90562: Invalid Bundle” error in App Store Connect. (69121373) (FB8708120)
```
https://developer.apple.com/documentation/xcode-release-notes/xcode-12_1-release-notes

**Comment by jayahariv** [comment]
is it possible to use the XCFramework? that might be a quick remedy I can think of, meanwhile we will look into the issue. 

You can download `swift-xcframework` from the Downloads page. 
https://www.couchbase.com/downloads

**Comment by matteosist** [comment]
Hi @jayahariv unfortunately i get the same error also with xcode 12.1

About your suggestion of embedding Couchbase through xcframework is not possible because is wrapped inside another pod and not added plain on our main project.

Do you have any update about this issue? Downgrade to 2.7.1 also is a problem because 2.8 resolve some issue that we are waiting for a while.

Many thanks.

**Comment by tony-osibov** [comment]
Hi @jayahariv thanks for the quick response and advice. I too tried disabling code coverage and no dice. Just like @matteosist commented, xcframework is not an option for us as well. I downgraded to 2.7.1 and problem was resolved. Would love to take advantage of the bug fixes in 2.8.0 if possible before our next release. Thanks for all the help!

**Comment by jayahariv** [comment]
Jira tracking ticket: https://issues.couchbase.com/browse/CBL-1403

**Comment by jayahariv** [comment]
Since you are an enterprise customer, could you please file a support ticket.

**Comment by rajagp** [comment]
@matteosist , @tony-osibov The issue should be fixed in 2.8.1 which is available today

**Comment by jayahariv** [comment]
@tony-osibov, to gather more information on failed to use XCFramework cases, could you share why its not an option for you?  Is it because of the XCFramework itself is causing trouble or is it same as Matteo mentioned wrapped inside another Pod?

**Comment by tony-osibov** [comment]
@rajagp thanks it is indeed fixed!

**Comment by tony-osibov** [comment]
@jayahariv we initially had the couchbase dependency through a sub pod, however, we have since moved away from that dependency. I think the XCFramework solution could work in a pinch, but wouldn't want to do it long term since updates would have to be handled manually instead of through a pod.

**Comment by jayahariv** [comment]
@tony-osibov thanks!

**Comment by jayahariv** [comment]
@matteosist @tony-osibov we are thinking about sharing the `.xcframework` via Cocoapods(currently its `.framework`), just to double confirm, are you going to face any issues integrating that?

**Comment by jayahariv** [comment]
@matteosist  @tony-osibov If you get sometime, could you let us know, if we share the `CouchbaseLiteSwift.xcframework` via Cocoapods, is there any challenge you will face integrating it?

**Comment by tony-osibov** [comment]
@jayahariv apologies for the slow response. We are using both the SPM and Cocoapod implementations with the xcframework (different implementations of our codebase in different projects). We have not had any issues with Cocoapods, however, with SPM we have noticed some Xcode idiosyncrasies with nested xcframeworks. That being said there were pretty easy to work around and minor all things considered.
