### ISSUE TITLE
Why has upgrading to Couchbase Lite 2.8.0 increased our app size by 6MB?

### ISSUE THREAD

**Issue by SteveHallSDHO** [couchbase/couchbase-lite-ios#2767]
**Describe the bug**
We have upgraded our app from CBLite 2.7.1 to 2.8.0 and noticed our app size increased by 6MB.

**To Reproduce**
N/A 

**Expected behavior**
N/A

**Logs** 
N/A

**Screenshots**
N/A

**Platform (please complete the following information):**
 - CouchbaseLiteSwift 2.8.0

**Additional context**
Can you explain the additional "bloat" we are seeing?

**Comment by Danyaga** [comment]
Hello Guys.

We have the same problem here, in particular we are not able to use your lib in App Clip as we used to for the size.

In case, this size is really needed you could think a way to deliver the library in slices and so we can decide what we really use.

**Comment by jayahariv** [comment]
Could you please check the 2.8.1 and see, if the size went down? We might have accidentally enabled the test coverages which might have caused the increase in size. Feel free to reopen if issue still exists.

**Comment by Danyaga** [comment]
I ll have a look. Thanks @jayahariv!

**Comment by SteveHallSDHO** [comment]
@jayahariv, I have tested CBLite 2.8.1 and can confirm that our app size shrank as a result of upgrading.
