### ISSUE TITLE
CBL 1.4.1 and macOS 11 Big Sur

### ISSUE THREAD

**Issue by adamski** [couchbase/couchbase-lite-ios#2770]
Will CBL 1.4.1 be supported in the next versions of macOS? Is it likely that support will be dropped in future updates of iOS/macOS?

**Comment by djpongh** [comment]
Couchbase Lite 1.4.x end of life was April 2019. See: https://www.couchbase.com/support-policy/enterprise-software for details on supported versions. Unfortunately we will not be supporting 1.4.1 on Big Sur.
