### ISSUE TITLE
Does not run on swift packagemanager, can import CouchbaseLiteSwift but module appears empty

### ISSUE THREAD

**Issue by NilsBerni** [couchbase/couchbase-lite-ios#2779]
**Describe the bug**
Couchbase 2.8.1 does not work when included via the swift package manager.

**To Reproduce**
Share a unit test or sample project or steps to reproduce the behavior
1. Install community edition package via package manager
2. Import  CouchbaseLiteSwift in ViewController.swift
3. Try to use Couchbase class e. g. Database

**Platform:**
 - OS: [iOS]
 - Couchbase Version [CouchbaseLiteSwift 2.8.1]

**Comment by jayahariv** [comment]
Whats the error you are seeing?

**Comment by NilsBerni** [comment]
It does not know the Couchbase classes at all and the module is empty.


<img width="624" alt="Screenshot 2020-11-25 at 00 58 02" src="https://user-images.githubusercontent.com/30769791/100164966-5aac4980-2eb9-11eb-9ea6-b8b4b7d82adc.png">
<img width="620" alt="Screenshot 2020-11-25 at 00 58 20" src="https://user-images.githubusercontent.com/30769791/100164967-5c760d00-2eb9-11eb-8b99-3fda2d09c819.png">

**Comment by jayahariv** [comment]
can you tell me how are you including the dependency or package.swift file ?

**Comment by NilsBerni** [comment]
Here is how I did it, but I tried multiple things, and nothing seemed to work. Even on one target. I am working on an apple silicon mac if that helps, but other frameworks seemed to work fine as well. 

<img width="573" alt="Screenshot 2020-11-25 at 08 33 05" src="https://user-images.githubusercontent.com/30769791/100197135-315fdd80-2efa-11eb-8a15-5e177ed17082.png">
<img width="728" alt="Screenshot 2020-11-25 at 08 33 42" src="https://user-images.githubusercontent.com/30769791/100197140-3329a100-2efa-11eb-9528-7ba6f25be2bc.png">
<img width="713" alt="Screenshot 2020-11-25 at 08 35 26" src="https://user-images.githubusercontent.com/30769791/100197149-34f36480-2efa-11eb-8fc6-1ba9a35100eb.png">
<img width="729" alt="Screenshot 2020-11-25 at 08 35 52" src="https://user-images.githubusercontent.com/30769791/100197153-36bd2800-2efa-11eb-9cc3-54a800f7ecde.png">
<img width="394" alt="Screenshot 2020-11-25 at 08 36 03" src="https://user-images.githubusercontent.com/30769791/100197161-3ae94580-2efa-11eb-87f5-96578665ed06.png">

**Comment by NilsBerni** [comment]
On the Couchbase website is a description for exactly what I do as Use Case 2: https://docs.couchbase.com/couchbase-lite/current/swift/start/swift-gs-install.html#case-2

It is also the suggested approach to include dependencies since Xcode 11. CocoaPods are not natively supported on Apple Silicon.

**Comment by NilsBerni** [comment]
Maybe to prevent confusion: I am building for iOS

**Comment by jayahariv** [comment]
Latest 2.8.x is not supporting Apple Silicon, if you are an enterprise customer could you please open up a support ticket? Or you can wait for next major release, _hopefully_ we will have it supported by then

**Comment by NilsBerni** [comment]
You are right, I tested it on a Intel based mac and that works. But the CouchBase lib via Pods or building the framework yourself does also not work on Apple Silicon. I beliefe it makes sense to prioritise that because people wont be able to develop their applications anymore, when they replace their old mac with a new mac.

**Comment by jayahariv** [comment]
thanks @NilsBerni, will prioritize it in coming releases. Closing this issue, since this is expected. For tracking purpose, you can follow [CBL-1474](https://issues.couchbase.com/browse/CBL-1474)
