### ISSUE TITLE
Set-Cookie from sync gateway causes Unauthorized on Second Replication

### ISSUE THREAD

**Issue by lroling8350** [couchbase/couchbase-lite-ios#2828]
**Describe the bug**

Our use case is to call a one shot replication, check some information from replicated data, and then perform a continuous replication afterwards. Upon upgrading the Object-C client to 2.8 we begin receiving 401 Unauthorized from the second replication. It was discovered the initial replication request was sending back two Set-Cookie headers because of our AWS load balancers. The second replicator was then having the cookie become corrupted causing the session authentication to fail. Instead of second Cookie being `SyncGatewaySession=e0f8da7dbda874bb558c2613bd36cd92bfa36d25` it was `SyncGatewaySession=e0f8da7dbda874bb558c2613bd36cd92bfa36d25,mycookie=Breaks` where the `,` needs to be a `;` before `mycookie`. I believe this may have been introduced with [CBL-384](https://issues.couchbase.com/browse/CBL-384). 

I've attached some request/responses to highlight the issue. Note any set-cookie returned causes the problem.

Initial Request
```
GET /todo/_blipsync HTTP/1.1
Host	192.168.86.33:4984
Sec-WebSocket-Protocol	BLIP_3+CBMobile_2
Sec-WebSocket-Version	13
Sec-WebSocket-Key	21Ibl+t3kdn+8hiVn1k89g==
Upgrade	websocket
Cookie	SyncGatewaySession=e0f8da7dbda874bb558c2613bd36cd92bfa36d25
User-Agent	CouchbaseLite/2.8.4 (ObjC; iOS 14.4.1; iPhone) Build/18 Commit/5ea5cd71+CHANGES LiteCore/2.8.4 (18)
Connection	Upgrade
```

Initial Response
```
HTTP/1.1 101 Switching Protocols
Upgrade	websocket
Connection	Upgrade
Sec-WebSocket-Accept	Z8+xeEpLRvncheeXJ0I0TEOyaWw=
Sec-WebSocket-Protocol	BLIP_3+CBMobile_2
Set-Cookie	MyCookie=Breaks
```

Second Request
```
GET /todo/_blipsync HTTP/1.1
Host	192.168.86.33:4984
Sec-WebSocket-Protocol	BLIP_3+CBMobile_2
Sec-WebSocket-Version	13
Sec-WebSocket-Key	KhDRAWUyLg/8ztXj4kG1bg==
Upgrade	websocket
Cookie	SyncGatewaySession=e0f8da7dbda874bb558c2613bd36cd92bfa36d25,mycookie=Breaks
User-Agent	CouchbaseLite/2.8.4 (ObjC; iOS 14.4.1; iPhone) Build/18 Commit/5ea5cd71+CHANGES LiteCore/2.8.4 (18)
Connection	Upgrade
```

Second Response
```
HTTP/1.1 401 Unauthorized
Content-Type	application/json
Server	Couchbase Sync Gateway/2.8.2 EE
Date	Tue, 20 Apr 2021 14:23:12 GMT
Content-Length	51
Set-Cookie	MyCookie=breaks
Connection	keep-alive
```

**To Reproduce**
1. Setup replication as a one shot and then follow on with a continuous
2. Ensure your SyncGateway is returning a Set-Cookie header.

I've created the repo https://github.com/lroling8350/mobile-training-todo/tree/bug-report which converts the Todo App to do two replications exhibiting the error. The setup requires

1. Clone repo https://github.com/lroling8350/mobile-training-todo
1. Checkout bug-report branch
1. Download and install Objective-C framework for building on device (not simulator)
1. Updating signing and bundle identifier to build on device
1. Setup Sync Gateway
    1. at root of repo run the following commands
    1. ./sync-gateway/run.sh
    1. ./sync-gateway/create-user.sh
    1. ./sync-gateway/create-user-session.sh
    1. copy the session id from the output of the last command
 1. Replace kSessionId with the session id copied from before (found in AppDelegate.m)
 1. Replace the ip address in kSyncEndpoint (found in AppDelegate.m)
 1. Setup a proxy to add any Set-Cookie header. I suggest [Charles Proxy](https://help.testlio.com/en/articles/1144391-charles-proxy-guide-for-ios) to rewrite the response to include a set-cookie header
 1. Run the application and note in the logs the last replicator was unauthorized. If you have charles proxy setup you will see the cookie for SyncGateWaySession is not correct.

**Expected behavior**
The second replication should not fail authorization.

**Platform (please complete the following information):**
 - Device: iPhone8 (any physical iphone should exhibit the issue)
 - OS: iOS 14.1
 - Couchbase Version CouchbaseLite 2.8.x
 - Synch Gateway Version Sync Gateway 2.8.2

**Additional context**
This issue only seems to occur when using the Object-C library with SessionAuthenticator and on a physical device. It is not a problem on simulators. What's interesting is that it is also not an issue with the Swift library.

**Comment by lroling8350** [comment]
I believe i've traced this to [here](https://github.com/couchbase/couchbase-lite-ios/blob/7d9724464d99e5b5cbb3203a58287f29c4f8ef0b/Objective-C/Internal/Replicator/CBLWebSocket.mm#L384) where 

```
[_logic addValue: cookie  forHTTPHeaderField: @"Cookie"];
```

the addValue uses a comma delimiter which causes the cookie header to break. I'm unclear how to properly join cookies other than string concatenation with a `;` between items.

**Comment by jayahariv** [comment]
Will track this in Jira  [CBL-1908](https://issues.couchbase.com/browse/CBL-1908).

**Comment by lroling8350** [comment]
I see this issue has been merged to master. Thank you for taking care of this so quickly! I am curious if there is a timeline for the next release of this package so I can consume the updates.

**Comment by jayahariv** [comment]
Closing this, will be available in the upcoming release.

**Comment by rajagp** [comment]
@lroling8350 Is there an email address I can reach out to you with more details on the availability of the release
