### ISSUE TITLE
`valueWouldChange` does not check whether `newValue` is a `CBLDictionary` 

### ISSUE THREAD

**Issue by blaugold** [couchbase/couchbase-lite-ios#2865]
Instead of checking whether `newValue` is either a `CBLArray` or a `CBLDictionary` the code checks whether it is a `CBLArray` twice. It does not cause wrong behavior, but partially circumvents the optimization of not comparing collections.

https://github.com/couchbase/couchbase-lite-ios/blob/7d9724464d99e5b5cbb3203a58287f29c4f8ef0b/Objective-C/Internal/CBLFleece.mm#L134-L135

**Comment by pasin** [comment]
Good catch!!. Thanks for reporting this.
