### ISSUE TITLE
CouchbaseLite-Swift-Enterprise pod produces warning when compiling with Xcode 13

### ISSUE THREAD

**Issue by s-hocking** [couchbase/couchbase-lite-ios#2895]
**Describe the bug**
When using the `CouchbaseLite-Swift-Enterprise` pod v2.8.4 with Xcode 13, the project produces a warning when building:

```
'~/CouchbaseBug/Pods/CouchbaseLite-Swift-Enterprise/iOS/CouchbaseLiteSwift.framework/Modules/CouchbaseLiteSwift.swiftmodule/Project/x86_64-apple-ios-simulator.swiftsourceinfo' is either malformed or generated by a different Swift version. Note that it uses an unstable format and may leak internal project details, it should not be distributed alongside modules
```

Using the .xcframework that is available from the Couchbase downloads works fine however, without a warning. Is there an ETA for making the xcframework available as a pod?

**To Reproduce**
1. Create a new Swift iOS project using Xcode 13
2. Run `pod init` in the project and add `pod 'CouchbaseLite-Swift-Enterprise'` to the Podfile
3. `pod install`
4. `import CouchbaseLiteSwift` in the project and try to compile

**Expected behavior**
Project should compile without warnings

**Platform (please complete the following information):**
 - Device: iOS Simulator or Any iOS Device (arm64)
 - OS: N/A
 - Couchbase pod v2.8.4

**Comment by jayahariv** [comment]
thanks @s-hocking, we have a tracking it CBL-2387

**Comment by s-hocking** [comment]
Glad to see it's on your radar already @jayahariv ! Can you please confirm if there is a plan to make the .xcframework available via CocoaPods?

**Comment by jayahariv** [comment]
Yes, from next release.

**Comment by jayahariv** [comment]
@s-hocking Could you please email to priya.rajagopalcouchbase.com for additional details on the release.

**Comment by uluckas** [comment]
> thanks @s-hocking, we have a tracking it [CBL-2387](https://issues.couchbase.com/browse/CBL-2387)

CBL-2387 say "[This warning is only for the Carthage binary](https://issues.couchbase.com/browse/CBL-2387?focusedCommentId=554739&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-554739)" and it seems like the fix will be to report the issue to Carthage-upstream.

It is also mentioned: "Now there is nothing more to be done from my side, will close this issue and wait for the next steps on this."

This does not sound very promising as a fix to Carthage-upstream will not solve this issue which is reported against a CocoaPod.

**Comment by jayahariv** [comment]
It should be fixed when we start consuming the XCFramework through the cocoapod, you can try 3.0.0-beta. 
```
pod 'CouchbaseLite-Swift-Enterprise', '~> 3.0.0-beta02'
pod 'CouchbaseLite-Swift', '~> 3.0.0-beta02'
```
