### ISSUE TITLE
Sync crashing CB lite 2.8.0 Ios 15.1

### ISSUE THREAD

**Issue by krishanrohitashsharma** [couchbase/couchbase-lite-ios#2910]
Ios 15.1  Iphone12 CB Lite 2.8.0 Community

Crashed: Repl->wss://abc.com/channels/_blipsync
0 CouchbaseLiteSwift 0x1b7484 litecore::repl::Replicator::_onClose(litecore::websocket::CloseStatus, litecore::blip::Connection::State) + 1148
1 CouchbaseLiteSwift 0x14e66c litecore::actor::GCDMailbox::safelyCall(void () block_pointer) const + 28
2 CouchbaseLiteSwift 0x14e628 litecore::actor::GCDMailbox::enqueue(void () block_pointer) + 128
3 libdispatch.dylib 0x2914 _dispatch_call_block_and_release + 32
4 libdispatch.dylib 0x4660 _dispatch_client_callout + 20
5 libdispatch.dylib 0xbde4 _dispatch_lane_serial_drain + 672
6 libdispatch.dylib 0xc958 _dispatch_lane_invoke + 392
7 libdispatch.dylib 0x171a8 _dispatch_workloop_worker_thread + 656
8 libsystem_pthread.dylib 0x10f4 _pthread_wqthread + 288
9 libsystem_pthread.dylib 0xe94 start_wqthread + 8

**Comment by jayahariv** [comment]
Could you please include the steps to reproduce(or a sample project would be more helpful), logs and full stack trace? 

[console-logs](https://docs.couchbase.com/couchbase-lite/current/swift/troubleshooting-logs.html#lbl-console-logs)

**Comment by jayahariv** [comment]
@krishanrohitashsharma any updates?

**Comment by jayahariv** [comment]
Closing this now, feel free to reopen when more details are available.
