### ISSUE TITLE
setMapBlock is executing for all CBLView s instead of specific mentioned CBLView

### ISSUE THREAD

**Issue by SravanPeddi** [couchbase/couchbase-lite-ios#2962]
I am having 4 CBLViews (AData, BData, CData,DData)
when i am trying to access below method using AData CBLView it is executing for all the CBLViews created.
- (BOOL) setMapBlock: (CBLMapBlock)mapBlock
         reduceBlock: (nullable CBLReduceBlock)reduceBlock
             version: (NSString*)version;

    CBLView *aView = [database existingViewNamed: @"AData"];
[aView setMapBlock: MAPBLOCK({
       NSLog(@"doc[type] %@",doc[@"type"]);
            if ([[doc[@"title"] lowercaseString] containsString:[@"abc" lowercaseString]]) {
                emit(CBLTextKey(@"content"),doc[@"masterId"]);
                break;
            }
 
    }) reduceBlock: NULL version: @"1"];

in log it is printing all CBLView names. 
As mentioned setMapBlock is executed by aData CBLView, expecting that it executes only for AData CBLView instead of all CBLVIews

**Comment by SravanPeddi** [comment]
is there any patch release available as we need to test all scenarios with upgradation.

**Comment by jayahariv** [comment]
plz use the latest binary, if there is any issue with that let us know. Closing this
