### ISSUE TITLE
Add Linux Support

### ISSUE THREAD

**Issue by guthriec** [couchbase/couchbase-lite-ios#3000]
It would be great to be able to write a CBL-based data layer in Swift and have it work on embedded or cloud Linux machines.

**Comment by jayahariv** [comment]
is this something you might be interested? 
https://github.com/couchbase/couchbase-lite-C

**Comment by guthriec** [comment]
Yep, that's what I'm using in absence of Swift support. I just think Swift is a nicer language than C, and bridging between them is non-negligible effort. Also your C API requires constructing the query string before making a query, whereas the Swift API has a nice builder for queries.

**Comment by jayahariv** [comment]
@rajagp

**Comment by jayahariv** [comment]
Supporting the Swift API is not in our radar especially since there is a choice of couchbase-lite-C.

**Comment by rajagp** [comment]
@guthriec  Your feedback is noted. As Jay indicated, the option is to use CBL-C which is designed for embedded, desktop and server applications for cross platform development.  As far as query API, the string based API offers advantages in that it follows the familiar SQL++ syntax, succinct compared to query builder API especially when it comes to very complex queries.
