### ISSUE TITLE
Document deletion and gateway channels

### ISSUE THREAD

**Issue by nl** [couchbase/couchbase-lite-ios#311]
When fetching a list of documents from a remote database (or all documents in a Sync Gateway channel), and allowing the user to delete those documents on the client side (which is done using purgeDocument: + a compaction), we're running into trouble when the user expresses interest in those documents/that channel again.

As suggested by Jens, we're creating a pull replication whose documentIDs are the documents we want to refetch. This has its own set of problems because in our case the client has no way of knowing which documentIDs to fetch. All we know is we need to fetch the gateway channel xxx.

The user can subscribe to a channel, then unsubscribe, then subscribe again.  Each change in subscription should reflect a change on whether the documents are physically present on the device of not.

This seems like a very simple use case but doesn't seem supported at the moment. Is this accurate?

**Comment by jayahariv** [comment]
Closing 1.x issue!
