### ISSUE TITLE
P2P replication

### ISSUE THREAD

**Issue by akalvapalli** [couchbase/couchbase-lite-ios#315]
We are working on peer to peer replication in CouchbaseLite using CouchbaseListener.
For replicating 5K documents form Device-A to Device-B it took 10 min. Any advice to reduce the time period? We configured P2P replication with Bonjour services. (Data transfer via Bluetooth)

**Comment by joshblour** [comment]
@akalvapalli i was able to get p2p replication working over wifi but i just realized that it doesnt work out of the box over blutooth. Would you mind sharing how you managed to get it working?

**Comment by snej** [comment]
If you're using NSNetService to discover peers, you should get Bluetooth support "for free". When the Bonjour daemon discovers a peer on BT, and you then ask to resolve the address, it constructs a network interface that tunnels IP through BT and gives you an address on that. In other words, opening a TCP connection to that IP address will tunnel the traffic through Bluetooth.

(The same goes for "infrastructure" WiFi, i.e. direct device-to-device WiFi connections when no base station is available.)

**Comment by joshblour** [comment]
@snej Thanks for the quick reply! I'm using NSNetServiceBrowser to find and resolve services, but the delegate never gets called with 'foundservices' when only bluetooth is on. I had a look through bonjour part of CBListener and noticed that it doesn't set "includesPeerToPeer = YES". could that be a factor?

**Comment by snej** [comment]
Oh! Yes, that sounds like the cause. If you'd like to add that line and see if it fixes your situation, we'd love a pull request. Otherwise please file an issue pointing out the problem.

**Comment by joshblour** [comment]
So that was it! I added the following snipped to the 'publishBonjour' method of HTTPServer.m and it worked like a charm.

````objc
		netService = [[NSNetService alloc] initWithDomain:domain type:type name:name port:[asyncSocket localPort]];

        if ([netService respondsToSelector:@selector(includesPeerToPeer)]) {
            netService.includesPeerToPeer = YES;
        }

        [netService setDelegate:self];
````

I'd love to submit a pull request but I could use some guidance on how to do it properly.

The publishBonjour method is a private method belonging to CocoaHTTPServer. I suppose the 'right' way to do it would be a pull request to them which makes this 'includesPeerToPeer' method optional and then a pull request to CouchbaseListener which sets that option to YES (or passes it on the to the developer.

Is there another (read: lazier) way to do it?

**Comment by snej** [comment]
Let me take a look…

**Comment by snej** [comment]
Added it. (We actually have our own fork of CocoaHTTPServer since there are other custom changes we've needed to make.) Thanks!

**Comment by snej** [comment]
I'm going to close this issue since we haven't heard from the originator in 8 months and there's not any information in the report to diagnose the performance problem.

@akalvapalli, if you still have this problem and want to diagnose it, just post the details here and I'll re-open it.
