### ISSUE TITLE
【iOS Swift】CouchbaseLite Replicator ERROR: {Repl#935} Got LiteCore error: WebSocket error 1006, "connection closed abnormally"

### ISSUE THREAD

**Issue by coderliu007** [couchbase/couchbase-lite-ios#3175]
**Describe the bug**
The xcode console reports a large number of 1006 warnings during synchronization
```
CouchbaseLite Replicator ERROR: {Repl#935} Got LiteCore error: WebSocket error 1006, "connection closed abnormally"
```

**Log
![Snip20230717_9](https://github.com/couchbase/couchbase-lite-ios/assets/83936591/7522f18b-8764-49c7-8164-d5748db7643b)

**Platform (please complete the following information):**
 - Device: [iPhone12 pro]
 - OS: [iOS14.6]
 - Couchbase Version [ CouchbaseLiteSwift 3.1.0]

**Comment by velicuvlad** [comment]
Can you provide more information about what you are trying to do and the scenario you see this happening?

**Comment by velicuvlad** [comment]
from the screenshot, it seems that the replicator is losing connection and is retrying as is a transient error and will retry until maxAttempts is hit. You potentially can set loglevel to error only.

@coderliu007 is this still an "issue"?  Can you please clarify what is the desired outcome you are looking for?

**Comment by velicuvlad** [comment]
will close this for inactivity
