### ISSUE TITLE
Undefined symbols for CBLReplicatedDocument using CBL ObjC

### ISSUE THREAD

**Issue by hyling** [couchbase/couchbase-lite-ios#3176]
**Describe the bug**
I'm getting undefined symbols for architecture arm64: "_OBJC_CLASS_$_CBLReplicatedDocument"

**To Reproduce**
`NSLog(@"%@", NSStringFromClass([CBLReplicatedDocument class]));
`

or from Swift calling an Objective C method

```
// where aDoc is a CBLReplicatedDocument
for aDoc in repl.documents {

}
```

Full sample project here: https://github.com/hyling/TestCouchbase3

**Expected behavior**
Link with no errors

**Platform (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 16.5.1(c)
 - Couchbase Version: CouchbaseLite 3.1.1 (ObjC)
 - Xcode 14.3.1
 - Cocoapods: 1.12.1
 - Compiling for physical device, not simulator

**Comment by pasin** [comment]
Sorry that we are getting into this so late. This was fixed in 3.1.7.
