### ISSUE TITLE
After downloading the demo, it cannot be run.

### ISSUE THREAD

**Issue by chen834921478** [couchbase/couchbase-lite-ios#3187]
Did you forget to declare these files as outputs of any script phases or custom build rules which produce them?

/Users/chkf/Library/Developer/Xcode/DerivedData/CouchbaseLite-bqcydxjsieafgjbmmzffcgjaaxmy/Build/Intermediates.noindex/PrecompiledHeaders/SharedPrecompiledHeaders/16215133027227322841/CBLPrefix.h.gch Command ProcessPCH++ failed with a nonzero exit code
<img width="265" alt="image" src="https://github.com/couchbase/couchbase-lite-ios/assets/18497781/f3981457-a113-4fc4-a4fc-bc62e55a1a7e">

**Comment by velicuvlad** [comment]
What demo are we talking about here? Also can you please refer what target are you trying to build and what is the XCode version?
