### ISSUE TITLE
`PrivacyInfo.xcprivacy` file is missing `NSPrivacyCollectedDataTypes` key

### ISSUE THREAD

**Issue by Vyazovoy** [couchbase/couchbase-lite-ios#3257]
**Describe the bug**
When I try to generate a privacy report in Xcode the report mentions next:
<img width="744" alt="Screenshot 2024-03-15 at 15 58 50" src="https://github.com/couchbase/couchbase-lite-ios/assets/2086081/9a164646-d5b9-4cf4-adb1-fea21f6361ba">

**To Reproduce**
Try to generate a privacy report

**Expected behavior**
No errors in the report

**Additional Info**

Looks like it would be better to have all required keys even if corresponding array is empty. Like this
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>NSPrivacyTracking</key>
  <false/>
  <key>NSPrivacyCollectedDataTypes</key>
  <array/>
  <key>NSPrivacyTrackingDomains</key>
  <array/>
  <key>NSPrivacyAccessedAPITypes</key>
  <array>
    <dict>
      <key>NSPrivacyAccessedAPIType</key>
      <string>NSPrivacyAccessedAPICategoryFileTimestamp</string>
      <key>NSPrivacyAccessedAPITypeReasons</key>
      <array>
        <string>C617.1</string>
      </array>
    </dict>
  </array>
</dict>
</plist>
```

**Comment by pasin** [comment]
Seem like the only two keys are required : `NSPrivacyCollectedDataTypes` and `NSPrivacyAccessedAPITypes`. But I doesn't hurt to add all of the keys. Also I noticed that the generated report is empty unless there are something in NSPrivacyTracking and NSPrivacyTrackingDomains.

**Comment by velicuvlad** [comment]
This has now been ported to the 3.1 line and will be available on the next version. Unfortunately, we don't have a clear timeline for that yet.

**Comment by manuel-ceschi** [comment]
Hi @velicuvlad . Do you have any news regarding a release date?

**Comment by velicuvlad** [comment]
3.1.7 has been now released and it includes the fix for this. @manuel-ceschi @Vyazovoy
