### ISSUE TITLE
Couchbase Lite for iOS: Database Integrity Check Failures

### ISSUE THREAD

**Issue by shamim-ict** [couchbase/couchbase-lite-ios#3263]
I am encountering several database integrity issues with Couchbase Lite for iOS in our application. The integrity check reveals problems ranging from incorrect freelist sizes to missing rows from indexes. These issues have surfaced during routine checks and are impacting our application's data reliability.

**Environment**
Couchbase Lite Version: 2.8.0
Operating System & Version: iOS version: iOS 17.3]
Device: iPhone XR

**Expected Behavior**
The database should maintain its integrity under normal operation conditions without any errors during integrity checks.

**Observed Behavior**

During a routine database integrity check, the following warnings were observed:

Main freelist: size is 53 but should be 55
On tree page 150303 cell 2: Rowid 109749 out of order
Page 150538 is never used
Page 150561 is never used
Wrong # of entries in index sqlite_autoindex_kv_default::db.index.conversationNameFTSIndexOnConversation_segdir_1
Row 3223 missing from index db.index.conversationRefId
Row 17234 missing from index messageStore.index.docType-refId

**Logs**
I used `cblite` tool for checking db integrity.

```
(cblite) check
Checking database integrity ... 12:31:46.919893| [DB] WARNING: {DB#1} Integrity check: *** in database main ***
Main freelist: size is 53 but should be 55
On tree page 150303 cell 2: Rowid 109749 out of order
Page 150538 is never used
Page 150561 is never used
12:31:46.948678| [DB] WARNING: {DB#1} Integrity check: wrong # of entries in index sqlite_autoindex_kv_default::db.index.conversationNameFTSIndexOnConversation_segdir_1
12:31:47.068089| [DB] WARNING: {DB#1} Integrity check: row 3223 missing from index db.index.conversationRefId
12:31:47.622944| [DB] WARNING: {DB#1} Integrity check: row 17234 missing from index messageStore.index.docType-refId
12:31:47.646875| [DB] WARNING: {DB#1} Integrity check: row 17689 missing from index messageStore.index.docType-refId
12:31:48.278762| [DB] WARNING: {DB#1} Integrity check: row 24580 missing from index messageStore.index.docType-refId
12:31:58.498903| [DB] WARNING: {DB#1} Integrity check: row 343741 missing from index messageStore.index.docType-refId
12:31:59.688153| [DB] WARNING: {DB#1} Integrity check: wrong # of entries in index messageStore.index.docType-refId
12:31:59.753357| [DB] WARNING: {DB#1} Integrity check: wrong # of entries in index messageStore.index.doctype-contentType-conversationRefId

Error: Integrity check failed: Database integrity check failed (details below)
*** in database main ***
Main freelist: size is 53 but should be 55
On tree page 150303 cell 2: Rowid 109749 out of order
Page 150538 is never used
Page 150561 is never used
wrong # of entries in index sqlite_autoindex_kv_default::db.index.conversationNameFTSIndexOnConversation_segdir_1
row 3223 missing from index db.index.conversationRefId
row 17234 missing from index messageStore.index.docType-refId
row 17689 missing from index messageStore.index.docType-refId
row 24580 missing from index messageStore.index.docType-refId
row 343741 missing from index messageStore.index.docType-refId
wrong # of entries in index messageStore.index.docType-refId
wrong # of entries in index messageStore.index.doctype-contentType-conversationRefId (1/15)

````

**Questions**

Are there known issues that could lead to these integrity check warnings in the specified version of Couchbase Lite for iOS?
What steps can we take to diagnose further and resolve these integrity issues?
Is there a recommended approach for preventing these types of integrity issues in future?

Thank you for your assistance in resolving these critical database integrity issues.

**Comment by bmeike** [comment]
I've opened [CBL-5564](https://issues.couchbase.com/browse/CBL-5564) to track this issue.

Questions:
  What version of CBLite are you using to perform this "integrity check"
  Is the integrity failure visible from whatever application created this DB?  Can we see the logs?
  Can we have a copy of the database?  You are welcome to sanitize it, of course, as long as the sanitized version still has the issue.

**Comment by pasin** [comment]
It's not clear what is leading into the index missing row issues. From what I knew, we once have an issue (already been fixed) upgrading from 2.8.x to 3.x.x which could result in the invalid database format due to some mismatched data type in the index. You may upgrade to 3.1.6, delete, and recreate the index.

**Comment by shamim-ict** [comment]
@bmeike

We utilized Couchbase Lite version `cblite tool 2.8 EE`:

```
❯ cblite --version
Couchbase Lite Core 0.0.0-EE (df1951bf+e2588435+)
```

Additionally, we conducted an integrity check within the iOS app using the following method, encountering the same error observed with the CBLite tool:

```swift
try messageStore.performMaintenance(type: .integrityCheck)
```

**Comment by velicuvlad** [comment]
Hi @shamim-ict ,
As Blake mentioned, it would be a great help to have verbose logs alongside with a sample db with the issue you are mentioning.

We have tests in place for `performMaintenance` that are passing for current release and without more context of what is leading into index missing row issues, it will be very hard to understand what is going on.

I must say that 2.8 is End-of-Life -  https://www.couchbase.com/support-policy/enterprise-software/ -  so this won't be prioritised unless it can reproduced on 3.0 onwards.

Can you please upgrade to, at least, 3.0 and check if the issue is still persisting?
