### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by eakarsu** [couchbase/couchbase-lite-ios#3313]
I am building project with scripts/build_framework.sh for CBL_Swift for ios, I am getting error

**Logs** 
Sharing logs will make debugging and troubleshooting easier. 
 - Enable console/file logging: [reference](https://docs.couchbase.com/couchbase-lite/2.7/swift.html#logging)
 - Attach the logs(hide any sensitive data from it before submitting).

**Screenshots**
If applicable, add screenshots to

**Comment by pasin** [comment]
What is the error you are having? I recommend to use the script to build xcframework instead.

```
/Scripts/build_xcframework.sh -s "CBL_Swift" -o <your output directory>
```

**Comment by eakarsu** [comment]
Thanks for helping. But that script you adviced to use is also getting same error

**Comment by eakarsu** [comment]
./Scripts/build_xcframework.sh -s CBL_Swift -o output

/Users/erakarsu/research/couchbase-lite-ios/Objective-C/Internal/CBLPrefix.h:24:9: fatal error:
      'fleece/Fleece.h' file not found
#import "fleece/Fleece.h"
        ^~~~~~~~~~~~~~~~~
1 error generated.
note: Run script build phase 'Remove Private Module' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'CBL_Swift' from project 'CouchbaseLite')
** ARCHIVE FAILED **


The following build commands failed:
	ProcessPCH++ /Users/erakarsu/Library/Developer/Xcode/DerivedData/CouchbaseLite-bgcjfcjogfzctcdlgxqdcepjlahm/Build/Intermediates.noindex/ArchiveIntermediates/CBL_Swift/PrecompiledHeaders/SharedPrecompiledHeaders/1348955647072114454/CBLPrefix.h.gch /Users/erakarsu/research/couchbase-lite-ios/Objective-C/Internal/CBLPrefix.h normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.analyzer (in target 'CBL_Swift' from project 'CouchbaseLite')
	ProcessPCH++ /Users/erakarsu/Library/Developer/Xcode/DerivedData/CouchbaseLite-bgcjfcjogfzctcdlgxqdcepjlahm/Build/Intermediates.noindex/ArchiveIntermediates/CBL_Swift/PrecompiledHeaders/SharedPrecompiledHeaders/1288389167757695930/CBLPrefix.h.gch /Users/erakarsu/research/couchbase-lite-ios/Objective-C/Internal/CBLPrefix.h normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'CBL_Swift' from project 'CouchbaseLite')
	ProcessPCH++ /Users/erakarsu/Library/Developer/Xcode/DerivedData/CouchbaseLite-bgcjfcjogfzctcdlgxqdcepjlahm/Build/Intermediates.noindex/ArchiveIntermediates/CBL_Swift/PrecompiledHeaders/SharedPrecompiledHeaders/16621548804183882929/CBLPrefix.h.gch /Users/erakarsu/research/couchbase-lite-ios/Objective-C/Internal/CBLPrefix.h normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'CBL_Swift' from project 'CouchbaseLite')
(3 failures)

**Comment by eakarsu** [comment]
This is resolved. I missed check out command

**Comment by eakarsu** [comment]
Can you please another ticket I have created?

Thanks


Erol Akarsu
