### ISSUE TITLE
Background Fetch did not work because the replicator's suspend mode cannot be changed

### ISSUE THREAD

**Issue by dreamwords** [couchbase/couchbase-lite-ios#339]
Hi, Guys

We are trying to add the backgound fetch functionality to our app but encountered some problem.

When the user get the push notification sent by Apple, the app can get some cycle to run (at when we want to sync the data). However the replication did not work, since the it's in suspend mode.

Detail in CBL_Replicator+Backgrounding.m

-appBackgrounding

and

-appForegrounding

When the app goes into background mode, the interal api of CBLReplicator::setSuspended set the suspend flag to YES which actually go offline the replicator. Only if the app goes back to Foreground mode, the sync can be started.

Just wondered is that possible to add a new notification or public interface at CBLReplication level to set the suspend flag?

So we can send notification or call the api to go online the replicator to try to finish the sync (in 30 seconds)

(void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler
{
    // set suspend flag to NO
}

Please let me know your thoughts. Thanks!

**Comment by npomfret** [comment]
Hi - how do I resume replication inside didReceiveRemoteNotification in my AppDelegate.m?

**Comment by snej** [comment]
Turn off the replication's `suspended` property.
