### ISSUE TITLE
Etag values for change feed should contain more identifying information than last sequence number

### ISSUE THREAD

**Issue by mz2** [couchbase/couchbase-lite-ios#353]
The Etag HTTP header values included by the Couchbase Listener in its responses for change feeds and _all_docs only include the last sequence number. This gets one in trouble if a different database is served at the same URL at different time points: client can respond with data from a stale cache.

This bit me in the backside way with a series of integration tests between the listener and a client which tests getting, updating and removing data, and listening to changes using the listener. I observed confusing cases where after initial success my change feed dependent tests would begin to fail because the client (JavaScript runtime of either Safari or Chrome, or one embedded in my app) would return JSON from its stale cache. Problem is resolved by clearing the browser's cache.

I am not sure what the best solution would be to fix this -- couchdb seems to include a hash of some kind in its _all_docs and changefeed responses as the Etag, not simply the sequence number.

**Comment by jayahariv** [comment]
Closing 1.x issue!
