### ISSUE TITLE
_all_docs doesn't handle keys request for non-existent document correctly

### ISSUE THREAD

**Issue by yaronyg** [couchbase/couchbase-lite-ios#356]
Please see https://github.com/couchbase/couchbase-lite-java-core/issues/201#issuecomment-45373806 for the details.

@andreibaranouski confirmed this bug exists in IOS.
@tleyden asked me to file the bug here.

**Comment by pasin** [comment]
Close as the issue doesn't exists in the current master branch. The unit test is also added.
