### ISSUE TITLE
CBLQuery doesn't call observer on dispatch queue

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#364]
Per [this email thread](https://groups.google.com/d/msgid/mobile-couchbase/b7e9627b-3aa1-41bd-80c4-242d5ee67e65%40googlegroups.com?utm_medium=email&utm_source=footer), if a CBLManager instance is associated with a dispatch queue (instead of an NSThread) then a CBLLiveQuery won't notify its observers when the results change. See the thread for details and code examples.

**Comment by hermanccw** [comment]
@snej I just try to do something as describe in this [google group thread](https://groups.google.com/forum/#!searchin/mobile-couchbase/livequery$20thread/mobile-couchbase/hApRE-18R54/0hbfYe5tzdkJ) and I am getting exactly the same problem.

i am running the branch release/1.1.0 and I try to look for the test added in [a8611d2](https://github.com/couchbase/couchbase-lite-ios/commit/a8611d2d73740a72c0b6eb78c4f0fcee75292b29) and couldn't find it, was it somehow moved and missed? or is there a better way to run a LiveQuery under a dispatch queue?

**Comment by sapieneptus** [comment]
Actually, we've been having the same issue lately with the 1.0.4 release where the `LiveQuery`s are very intermittent in receiving updates. I'll try doing some logging (is `"Query"` good enough?) to see if I can find anything.  

I'll also see if I can downgrade to 1.0.3 and verify if this is a regression or not.

**Comment by hermanccw** [comment]
@sapieneptus I think what you are talking about is fix after 1.0.4 with this [issue](https://github.com/couchbase/couchbase-lite-ios/issues/542)

Does livequery kvo work for you in 1.0.4?

**Comment by sapieneptus** [comment]
@hermanccw Thanks for the info, I guess we'll have to try that out. 

Our live queries report results only the first time they're run, and on average do not report any subsequent changes via KVO (either through internal updates or changes coming from the pull replication).

**Comment by hermanccw** [comment]
Actually, force alarm, I didn't set the dispatch_queue in CBLManager.
