### ISSUE TITLE
Assertion failure in -[CBLBulkDownloader startedPart:]

### ISSUE THREAD

**Issue by sellingsolutions** [couchbase/couchbase-lite-ios#373]
CBL_Puller[http://username:****_@domain/dbName] bulk-fetching 50 remote revisions...
23:10:03.951‖ SyncVerbose: CBL_Puller[http://username:**_**@domain/dbName] bulk-fetching remote revisions: (....lots of revs....

SyncVerbose: CBL_Puller[http://username:**_**@domain/dbName]: POST _bulk_get
*_\* ASSERTION FAILED: !_docReader
**\* Assertion failure in -[CBLBulkDownloader startedPart:](), /Users/zno/Documents/Xcode Projects/couchbase-lite-ios/Source/CBLBulkDownloader.m:138

Full backtrace can be found here:
http://pastebin.com/dymTeH46

**Comment by BrandonNott** [comment]
I was able to reproduce this issue.  It was probably triggered by switching networks mid replication.  The application continued replication until completion and then threw an assertion failure

[crash log.txt](https://github.com/couchbase/couchbase-lite-ios/files/1252608/crash.log.txt)

**Comment by pasin** [comment]
@BrandonNott What CBL version are you using? The stack trace in the log doesn't provide the info where the crash is so I couldn't confirm that you are experiencing a new issue or the issue that has recently been fixed.

FYI: There was a [fix](https://github.com/couchbase/couchbase-lite-ios/pull/1784) for the same issue committed in the master branch. There is also a pending [PR](https://github.com/couchbase/couchbase-lite-ios/pull/1869) that could address a similar issue as well.
