### ISSUE TITLE
CBLModel should type-check property values on load

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#419]
When reading a model property of type NSString, NSArray or NSDictionary from the CBLDocument, CBLModel should check whether the value has the correct class. Otherwise a document with an unexpected value type can lead to exceptions.

A common case of this is if a document has JSON null values that indicate empty properties. Currently the native property will get an NSNull object, which will subsequently cause crashes if the app reads the property and messages it as though it were an NSString or NSArray.

(Inspired by [this mailing-list thread](https://groups.google.com/d/msgid/mobile-couchbase/CAN8S9iJ6jRGheHycb_8kUfdW0bqpoGaosVs1wdzQjd9kUSv3nw%40mail.gmail.com))

**Comment by apiology** [comment]
I'm still forced to use NullSafe with version 1.0.4 of CBL to deal with nil values with @NSManaged properties on a Swift-based CBLModel.  Is this expected?
