### ISSUE TITLE
Add API to tell which documents haven't been pushed to the server

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-ios#442]
Extracted from this [discussion](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/mobile-couchbase/k4AV07PW49s/3ZJbxe4t34wJ), it would be great to have a public API call:

```
-[CBLReplication hasPushedDocument: (CBLDocument*)doc].
```

which would indicate whether the document has been successfully pushed or not.

**Comment by snej** [comment]
The commit was merged on Dec 19, but this issue didn't get closed then. Closing it.

**Comment by tleyden** [comment]
I added a ticket to java-core to port this: https://github.com/couchbase/couchbase-lite-java-core/issues/417
