### ISSUE TITLE
pull replication from couchbase sync_gateway 1.0.2 with self-signed cert does not work

### ISSUE THREAD

**Issue by mglasgow** [couchbase/couchbase-lite-ios#444]
## In summary

cannot pull replicate from couchbase sync_gateway (compiled binary release 1.0.2) when sync_gateway is using self-signed cert. Neither one-shot nor continuous pull replication works.
## Detailed info

Couchbase sync_gateway supports hosting via ssl: https://github.com/couchbase/sync_gateway/wiki/SSL-support

I have setup a sync_gateway using a self-signed cert and, after calling CBLReplicator setAnchorCerts, I can successfully perform a push replication (both one-shot and continuous).
### Workaround for one-shot pull replication

However, pull replication isn't working (neither one-shot nor continuous). For one-shot, CBLSocketChangeTracker was reporting an OSStatus error of -9807. I enabled a workaround by commenting out line 100 of CBLSocketChangeTracker.m:

```
NSDictionary *settings = $dict(
    // {(id)kCFStreamSSLLevel, @"kCFStreamSocketSecurityLevelTLSv1_0SSLv3"},
    {(id)kCFStreamSSLValidatesCertificateChain, @NO});
CFReadStreamSetProperty(cfInputStream, kCFStreamPropertySSLSettings, (CFTypeRef)settings);
```

This line forces the SSL level to TLS1.0. The comment above this setting dictionary indicates it was added to support older SSL servers.  My guess is that the sync_gateway does not support TLS1.0. When commented out, the one-shot pull replication now works fine.

It seems some way of specifying the TLS version for the replicator is required, instead of hard-coding?
### Investigating continuous pull replication

I spent several hours digging into the continuous pull replication, but didn't get a satisfactory workaround. It simply times out against the remote server, but keeps trying. I enabled all the logging I could see in the code path, but nothing informative was actually given.

From what I can tell, CBLWebSocketChangeTracker doesn't include any option to validate self-signed certs, but does not hard-code the TLS version. The self-signed cert validation might be the cause. 

CBLWebSocketChangeTracker uses WebSocketClient (from https://github.com/couchbaselabs/WebSockets-Cocoa). WebSocketClient supports a useTLS method (from the super class, WebSocket), but never actually applies it. The superclass uses it when setAsyncSocket is assigned, but WebSocketClient directly assigns the private field _asyncSocket. ie, setAsyncSocket is never called and tls settings are never applied.

I tried setting up a dictionary of TLS settings like so:

```
NSDictionary* settings = $dict(
  {(id)kCFStreamSSLAllowsAnyRoot, @YES},
  {(id)kCFStreamSSLValidatesCertificateChain, @NO}
);
```

and modified WebSocketClient to actually apply them when building _httpSocket, but this didn't help.

The included source for GCDAsyncSocket has logging hard-coded to off. When I enabled it, I get a linker error missing a reference to DDExtractFileNameWithoutExtension. I hit a wall, and stopped investigating, as I was using one-shot replication only anyway.

**Comment by sapieneptus** [comment]
It seems that with CBL 1.1.0 iOS, we are having the opposite issue to the OP: Pull seems to work, but push does not. Any chance the fix somehow switched them?

We are also using a self signed cert, SG 1.1.0.

**Comment by snej** [comment]
I can't think of anything that would make pull work but not push — they use basically the same network calls except for one extra one that pull uses. Please file a new issue with lots of juicy details including logs.
