### ISSUE TITLE
CBLReplication goes offline sometimes and doesn't continue

### ISSUE THREAD

**Issue by ristkof** [couchbase/couchbase-lite-ios#465]
(using version 1.0.2)

Sometimes, in hard to reproduce circumstances, but often enough to notice, the CBLReplication objects I'm instantiating in my iOS app go to offline state and don't recover.

It is my guess that sometimes reachability notifications get missed. I have not been able to find a scenario that reproduces the problem 100%, but if I disconnect the network often enough, sooner or later I'll run into the problem.

I programmed, as a workaround, a timer that restarts the replications if they are offline, but I would love to have a better solution (or a bug fix). Maybe I'm doing something wrong?

Any other ideas?

**Comment by kamal-mann** [comment]
Able to replicate same behavior on **1.0.3.1** version running on *iPad simulator (iOS 8.4)*. Steps to reproduce are:
1. Replication is in progress
2. Turn off WiFi (n/w interface)
3. Turn on WiFi again and `CBLReplication` instance is unable to recover.
Tried calling `restart` on `CBLReplication` instance but nothing helps.
Note: Never happens on device though.

**Comment by pasin** [comment]
I have noticed similar behaviors in the past when testing on simulators but not on devices. Anyway FYI, we have released v1.1.0 about a month ago. V1.1.0 comes with several enhancement and bug fixes that you might consider upgrading the library.
