### ISSUE TITLE
Replication filters not working in conjunction with changing users

### ISSUE THREAD

**Issue by muellermichel** [couchbase/couchbase-lite-ios#474]
According to the replication algorithm wiki entry, couchbase lite tracks replication sequence numbers with the following index: 

`Generate a unique identifier for this replication based on the database IDs, and the filter name and parameters (if any). For instance, you can concatenate these with an unambiguous delimiter and then run that string through a cryptographic digest algorithm like SHA-1. The exact mechanism doesn’t matter, because this identifier is used only by a particular implementation.`

One thing that *isn't* being analyzed here, is the couchdb user. This leads to the following scenario:

1. Documents are replicated for user 1. Some documents aren't included because of the filter function. 

2. Sequence number is set to X for for these parameters. 

3. With the same request parameters, but a different user (user 2), the client issues a new replication. Couchbase now (IMO incorrectly) continues at sequence number X, which leads to documents from 0 to X not being sent, even though the filter function would return true for user 2.

Suggestion: Including everything from the user context object seen by the server side filter function, that can possibly be known to couchbase lite, into the hash that indexes the private replication documents. It would be even better, if the replication function took a full user document as a parameter in order to include it into the hash, such that currently active roles are being included as well.

Workaround: Include username and roles as parameters to the replication function.

**Comment by pasin** [comment]
Closing the issue as there is no issues.
