### ISSUE TITLE
Map blocks can't access attachment contents

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#498]
I just realized that, within a map block, there's no reliable way to retrieve the contents of an attachment. You get the document as an NSDictionary, and can see the `_attachments` property, but the body of the attachment isn't in there.

This came up in the context of storing text in docs in compressed form but being able to full-text index it. This would require putting the text in an attachment but retrieving it in the map function to emit. There are probably other contexts this could come up in too.

We wouldn't want to load every attachment into the doc dictionary, since that would be slow and potentially use a lot of memory, and in most cases the map function won't need it. So there needs to be a way to load it on demand. Except the map function doesn't have direct access to any CBL objects to call, since it may be running on a background thread...

**Comment by jayahariv** [comment]
Closing 1.x issue!
