### ISSUE TITLE
Recurrent timeout during a large replication 

### ISSUE THREAD

**Issue by mz2** [couchbase/couchbase-lite-ios#518]
I'm getting a recurrent timeout when attempting to pull a certain large database of documents into another one, with a certain document always causing a timeout towards the end of the process (there's approx 7100 documents in the database, one causing the issue is 7011th always). The error message is always as such:

10:31:53.342‖ CBLMultipartUploader[PUT http://lite.couchbase./shared/[...the document id ...]?new_edits=false]: Got error Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo=0x608000cebe00 {NSUnderlyingError=0x600002e5fa70 "The request timed out.", NSErrorFailingURLStringKey=http://lite.couchbase./shared/[...the document id ...]?new_edits=false, NSErrorFailingURLKey=http://lite.couchbase./shared/[...the document id ...]?new_edits=false, NSLocalizedDescription=The request timed out.}

I'm happy to share the database or source code privately to help reproduce this. I'm suspecting it's some unhandled error with the contents of that database which translates into a timeout.

**Comment by mz2** [comment]
@pasin sorry for the delay -- sounds like based on your experience, issue is unlikely related to simply data size. I've sent the example data separately in email. 

Based on watching the logs when this issue hits, the timeout always begins predictably at the same document.

**Comment by snej** [comment]
I think you CC:d me on the email — our mail server's security checker blocked it saying "too many files in zip archive"(!) You might want to share it via Dropbox or something like that instead.=

**Comment by pasin** [comment]
I got the same notification. @mz2, could you share it via other methods?

**Comment by mz2** [comment]
@snej  & @pasin links now sent separately.

**Comment by snej** [comment]
@mz2: You said earlier (12/5) that the issue might be "based on a workaround I've put in place in my fork". If you're using a forked version of Couchbase Lite where you've modified the behavior of the replicator, I don't know if it's worth it for us to try to diagnose this. Can you reproduce the problem with a stock build of CBL, ideally from the current master branch?

**Comment by mz2** [comment]
I'm not so certain about it really is related to anything in my fork to be honest, I shouldn't really have said that, it was mostly self-deprecation rather than trying to be perceptive at the time :) I just noticed that there was odd behaviour coming from the replicator's NSNotificationQueue based notification posting, it seemed as though notifications noting the completion of a replication were not coming through reliably at least in this large replication case. I've not actually in this instance forked the relevant behaviour in CBL, but I have put in a workaround in the client end where I spin in the client end of the replication (= code where I set up a one-off replication) a runloop around until the replication is in a finished state (this replication is part of app startup procedure -- I load some bundled and/or online data in and then present it to the user once it's all finished pulling in), and I also tried adding a callback to note the completion of the replication, as the notifications that inform of its state change to finishing didn't seem to fire reliably. But neither really is on code paths that would lead to these timeouts and the issue with that timeout was there already before, which is something I forgot when adding these workarounds. It's a long story, one that I am happy to explain privately with source code in some more detail. I'm actually 90% this reproduces with a stock CBL in suitable conditions and that the issue is real, but due to some other things I've exposed from the CBL framework for myself (things like some introspection helper functions in MYDynamicObject) it's not a trivial effort to compile my app with a stock CBL at the moment (it's something I've planned after a product launch). If I'm right, simply attempting to pull the example CBL data with its attachments into an arbitrary (empty?) CBL database should reproduce the problem.

**Comment by pasin** [comment]
I still couldn't reproduce the issue with your sample. I push my test mac app here:
https://github.com/pasin/Issue-518. I included the framework built from the current master. Your sample database is also included.

@mz2, could you check if I miss anything to reproduce the issue?

**Comment by pasin** [comment]
@mz2 can you look into my test app and see what I missed to make the issue reproducible? or If you have any more info, please provide.
