### ISSUE TITLE
Implement isStoredInExternalRecord support in CBLIncrementalStore

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#526]
This feature is initiated from the PR https://github.com/couchbase/couchbase-lite-ios/pull/409. We need to design what 'isStoredInExternalRecord' means to CBLite for storing binary data (or other type data). For iOS, apple uses this property to determine whether the binary data should be stored outside the SQLite DB based on the size of the binary data. Mac uses this property for spotlight search.

**Comment by pasin** [comment]
Based on my research and observation on Apple iOS Core Data:

1. Setting `allowsExternalBinaryDataStorage` property (A.K.A Allows External Storage option in XCode's Model Design Tool) of the `Binary Data` attribute type (The other attribute types don't have this option) does enable CoreData to heuristically store the data in an external storage. 

Based on my simple experiment in an iOS app, when the data size is more than 128k, Core Data stores the data externally when the `Allows External Storage` option is set. It's possible that Core Data  have more sophisticated algorithm than just checking the data size to determine when to keep the data externally. 

2. Settings `isStoredInExternalRecord` (A.K.A `Store in External Record File` option in Xcode's Data Model Design tool) have no effect in iOS which is inline with what the [API doc] (https://developer.apple.com/library/ios/documentation/Cocoa/Reference/CoreDataFramework/Classes/NSPropertyDescription_Class/index.html#//apple_ref/occ/instp/NSPropertyDescription/storedInExternalRecord) said.

Based on [Core Data Spotlight Integration Programming Guide] (https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/SpotlightCoreData/Articles/recordLevel.html#//apple_ref/doc/uid/TP40008065-CH101-SW10), setting 'External Record File` option allows the data to be stored externally for Spotlight search indexing. This is for Mac apps only not for iOS app.

**Comment by jchris** [comment]
@ManuTroquet it would help to hear what you are wanting to do with external storage / records. Is it about plug in compatibility with existing code? Eg will your app crash without this, or just run slow?

I took a look at your pull request and the questions that I come up with are around details like base64 encoding etc where one of our engineers who knows our internals might be able to come up with more optimizations as we review your contribution / implement this feature.

Thanks for helping us get this right!

**Comment by pasin** [comment]
@ManuTroquet , I have reviewed your PR with @snej and @zgramana and we are sorry that we will not accept the PR. The main reason is that :
1. The PR overrides the actual meaning of the `isStoredInExternalRecord` property, which is supposed to use for Mac Spotlight indexing and have no effect on the iOS platform. Using the property for something else would confuse other developers either Mac or iOS developers.

2. We already have a way to store data as an attachment by specifying the data type to binary. Of course when storing and retrieving would require data conversion. The same data conversion process happens in your PR as well.

Please feel free to let us know your specific use cases or requirements associated with your PR so that we could help optimizing or finding any other alternative solutions. Again, thanks a lot for the PR and  help improving CBLIncrementalStore.
