### ISSUE TITLE
Mac Application Reachability issue

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#536]
Per reported in #522, when using CBL in mac app, reachability stops working correctly sometime and always reported that the connected server is not reachable.

**Comment by nl** [comment]
This is still very much a showstopper for using continuous replications in Mac apps.

**Comment by snej** [comment]
[Logs here](https://gist.githubusercontent.com/nl/22abd61c0e880171ae7f/raw/ceecc22a1aa6552692a4ff05218c86c91ec7746f/gistfile1.txt).

There are some well-known networking bugs in 10.10, especially having to do with DNS and Bonjour, and I wonder if they're what's causing this. (But @nl said in #522 that this happens on 10.9 as well...)

**Comment by snej** [comment]
@pasin, didn't you change the replicator so it tries to connect whether or not Reachability says the server is reachable? I remember that being discussed a few months ago...

**Comment by nl** [comment]
I believe this change affected one-shot replications, not continuous. I can confirm one-shot replications don't exhibit this odd reachabilty behavior, and that whenever I run into this bug with continuous replications (in 1.0.4), switching them to noncontinuous fixes it and the revisions atart pushing/pulling right away.

**Comment by pasin** [comment]
We rolled back all the changes as we don't have a complete solution. 

We tried to change the replicators to connect anyway and use the reachability only for triggering the retry logic in replicators and change trackers. The replicator also has an option to set network type (WiFi or Cell). 

As we can't use the reachability to detect and limit network access, we tried to limit network type access by setting the NSMutableURLRequest's allowsCellularAccess property and CFStream's kCFStreamPropertyConnectionIsCellular property directly. The thing was we also support WebSocket and we are using CocoaHTTPServer which we couldn't find a way to limit the network access. As a result we decided to rollback all changes.

**Comment by pasin** [comment]
@nl , we haven't put the fix for both one-shot or continuous replicator. Does this mean that the reachability is correct first time but the reachability is not reliable when switching the network on / off?

**Comment by nl** [comment]
I'm only experiencing the bug for continuous replications. Here's what that means, whenever the bug happens (which isn't always, but when it does, it does until I reboot my Mac or switching the network on/off):
I build my app with continuous replications. The replications aren't firing, and they should.
I change the continuous = YES to NO in Xcode and build & run. The replications fire.
I change the continuous = NO to YES in Xcode and build & run. The replications don't fire.
And so on. The behavior is 100% predictable, again, whenever the reachability bug pops up, which seems to be random.

**Comment by pasin** [comment]
You are right. We made the fix only for a single replication.

https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CBL_Replicator.m#L354-L355

**Comment by pasin** [comment]
@nl, we put a workaround for this issue as an option not to trust reachability offline result.

Could you try to set the option as follows and see if that works for you?
```
puller.customProperties = @{ @"trust_reachability" : @(NO) };
```
Note: Please make sure you do not set 'network' option as it will override the 'trust_reachability option.

I'm closing the issue for now. If you still see the issue, feel free to reopen it.
