### ISSUE TITLE
Replicators should have independent cookie storage

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#543]
By default every NSURLConnection in a process shares the same cookies. Since we do Facebook and Persona login using sessions/cookies, that means that all replicators effectively share a single login. This causes two problems:

* An app can't switch the FB/Persona user it's authenticating as, because the old cookie is still present.
* You can't have two replications to the same host that authenticate as different FB/Persona users.

The fix, I think, is to create a separate NSHTTPCookieStore for each CBL_Replicator and have its NSURLConnections use that instead of the shared one.

**Comment by SebastianBO** [comment]
NSHTTPCookieStorage *cookieJar = NSHTTPCookieStorage.sharedHTTPCookieStorage;
    for (NSHTTPCookie *aCookie in cookieJar.cookies) {
        if ([aCookie.name  isEqual: @"SyncGatewaySession"]) {
            [cookieJar deleteCookie:aCookie];
        }
Works for now i guess? Best Regards
