### ISSUE TITLE
iOS cordova client cblite sync calls to SG fail to authenticate after app restart

### ISSUE THREAD

**Issue by vinaynb** [couchbase/couchbase-lite-ios#552]
Hello

I posted about this bug initially at [Google cb mobile group](https://groups.google.com/forum/#!topic/mobile-couchbase/nEvhKKuednw) but was advised to carry this discussion over here to get more fruitful result so here i am describing the issue i am facing.

I am using cblite in a cordova application on android as well as iOS. I am currently using two different versions of cblite plugin on android (1.0.0) and iOS(1.0.2) (i am currently facing issues with other versions on each platform)

I am using custom authentication with my nodejs server making the requests to SG to obtain cookies with session id's and return them to the mobile client. On android initially i was not being able to set the cookie which i received from nodejs to my cblite and hence it used to give me 401 auth fail errors in SG. So what i did was that i set the "Cookie" property in headers manually while setting up my replicator and this solved the issue for me.

Now on iOS i learned that the cookies are not handled port specific and i just need to set the cookie in response headers from nodejs to my client and then cblite will automatically make use of these cookies while making calls to SG. This flow works perfectly when a user opens app for the first time, logs in and starts syncing. User calls are authenticated by SG and i can see the logs.

But after i restart the app (not resume it) then the subsequent calls to SG by cblite fail with 401 auth error. I do not have a clue as to why doesn't cblite use the cookie which was received when user logged in for the first time.

I will be happy to provide you any stats,code,reports,logs and stuff that you need.

Thanks !

**Comment by hideki** [comment]
Hi @vinaynb 

I have tried to figure out the difference between iOS and Android regarding about setting a cookie from PhoneGap/Cordova app. From your second comment, I understand how you could set cookie for android platform. But I am not sure how you set cookie for iOS from your initial comment. 

> Now on iOS i learned that the cookies are not handled port specific and i just need to set the cookie in response headers from nodejs to my client and then cblite will automatically make use of these cookies while making calls to SG.

Could you please provide how you set cookie for iOS from PhoneGap/Cordova app?

Thanks!

**Comment by vinaynb** [comment]
For ios you don't need to setCookie explicitly in your phonegap app. The only thing you need to do is that whatever api you are calling for authentication you just need to set the cookie with session id obtained from sync gateway, in the header of the response from that api. That is all. Henceforth your all your rest calls will use that cookie automatically.

**Comment by hideki** [comment]
Hi @vinaynb Thank you very much for your comment. 

>  The only thing you need to do is that whatever api you are calling for authentication you just need to set the cookie with session id obtained from sync gateway, in the header of the response from that api.

I am still not clear how you set cookie on iOS. Did you set cookie in document DOM object like “document.cookie=“xxxx=yyyy”;?
Could you please provide us code snippet? 
Thanks!

**Comment by vinaynb** [comment]
i did nothing on the client side (i.e your cordova/phonegap app) to set cookie. No setting anything in the DOM Object.

Just as to clear things what kind of authentication do you have for authentication with sync_gateway in your implementation ?

**Comment by hideki** [comment]
@vinaynb Thank you for your comment. 

> i did nothing on the client side (i.e your cordova/phonegap app) to set cookie. No setting anything in the DOM Object.

Let me confirm. Remote authentication server set cookie. Without any code at client side, the cookie is set in request to sync_gateway server for iOS. For Android, this does not work. so you set cookie explicitly in push/pull replication config.

> Just as to clear things what kind of authentication do you have for authentication with sync_gateway in your implementation ?

I am not developing app/service. I am working for tickets which are Android/PhoneGap cookie related. Your experience written here is really helpful to understand difference between iOS and Android behaviors. 
https://github.com/couchbase/couchbase-lite-java-core/issues/360 https://github.com/couchbase/couchbase-lite-java-core/issues/353

Thanks,

**Comment by vinaynb** [comment]
> Let me confirm. Remote authentication server set cookie in the response. Without any code at client side, the cookie is set in request to sync_gateway server for iOS. For Android, this does not work. so you set cookie explicitly in push/pull replication config.

You hit the bull's eye. Yes that's correct.

**Comment by dhavaln** [comment]
@vinaynb How exactly you set the cookies in the response. I tried to set it from the node/express app but the connection fails. I am using the pouchdb to connect with sync gateway, till date we were using the pouchdb-authenticate with username/password but now I am changing that to support the Auth0 based login
