### ISSUE TITLE
ForestDB slower on indexing number of document over 1000

### ISSUE THREAD

**Issue by lichenyang2** [couchbase/couchbase-lite-ios#564]
ForestDB is much faster in indexing when number of documents is under 1000, but about 80% slower when number of document is above 1000.

With ForestDB build from forestdb  branch on 1/13/2015
```
-------------------- Test21_Index - 1/14/15, 3:50 PM
 # docs; 10 B, 1000 B, 100000 B, 500000 B, 1000000 B, 2000000 B, 
10 docs; 4.57; 3.52; 13.72; 52.71; 98.75; -1.00; ;
100 docs; 11.37; 13.40; 104.38; -1.00; -1.00; -1.00; ;
1000 docs; 93.02; 93.00; -1.00; -1.00; -1.00; -1.00; ;
10000 docs; 1882.56; -1.00; -1.00; -1.00; -1.00; -1.00; ;
100000 docs; 21599.64; -1.00; -1.00; -1.00; -1.00; -1.00; ;
--- Percentage of deviation from baselines
 # docs; 10 B, 1000 B, 100000 B, 500000 B, 1000000 B, 2000000 B, 
10 docs; -72.83%; -82.21%; -67.15%; -56.86%; -59.33%; 0.00%; ;
100 docs; -47.84%; -47.57%; -63.55%; 0.00%; 0.00%; 0.00%; ;
1000 docs; -11.40%; -63.81%; 0.00%; 0.00%; 0.00%; 0.00%; ;
10000 docs; 70.31%; 0.00%; 0.00%; 0.00%; 0.00%; 0.00%; ;
100000 docs; 75.02%; 0.00%; 0.00%; 0.00%; 0.00%; 0.00%; ;
```

With  version 1.0.4-2
```
-------------------- Test21_Index - 1/14/15, 3:48 PM 
 # docs; 10 B, 1000 B, 100000 B, 500000 B, 1000000 B, 2000000 B, 
10 docs; 11.85; 11.56; 25.19; 94.87; 182.87; -1.00; ;
100 docs; 17.76; 18.88; 178.81; -1.00; -1.00; -1.00; ;
1000 docs; 88.10; 131.60; -1.00; -1.00; -1.00; -1.00; ;
10000 docs; 915.28; -1.00; -1.00; -1.00; -1.00; -1.00; ;
100000 docs; 10817.52; -1.00; -1.00; -1.00; -1.00; -1.00; ;
--- Percentage of deviation from baselines
 # docs; 10 B, 1000 B, 100000 B, 500000 B, 1000000 B, 2000000 B, 
10 docs; -29.55%; -41.59%; -39.68%; -22.35%; -24.68%; 0.00%; ;
100 docs; -18.53%; -26.13%; -37.55%; 0.00%; 0.00%; 0.00%; ;
1000 docs; -16.09%; -48.79%; 0.00%; 0.00%; 0.00%; 0.00%; ;
10000 docs; -17.20%; 0.00%; 0.00%; 0.00%; 0.00%; 0.00%; ;
100000 docs; -12.34%; 0.00%; 0.00%; 0.00%; 0.00%; 0.00%; ;
```
The test case is at:  https://github.com/couchbaselabs/iOS-WorkerBee/blob/master/Tests/Test21_Index.m

**Comment by snej** [comment]
How do I get WorkerBee to output tables like what you show above? Mine just dumps a bunch of logs. It also doesn't run 100,000 docs at all, it just logs "SKIP".

From what I can see, ForestDB is much faster at 10,000 docs:

    10000 docs; 865.14; -1.00; -1.00; -1.00; -1.00; -1.00; ;

vs SQLite:

    10000 docs; 3721.35; -1.00; -1.00; -1.00; -1.00; -1.00; ;

That's 4.3x the speed of SQLite. (This is on my iPhone 6+.)

**Comment by snej** [comment]
BTW, are you sure you built a Release version of the forestdb branch? Xcode by default will build the Debug version, which is much slower.

**Comment by lichenyang2** [comment]
The performance does improve with release build:
# docs; 10 B, 1000 B, 100000 B, 500000 B, 1000000 B, 2000000 B, 
10 docs; 3.42; 2.71; 10.72; 44.67; 80.66; -1.00; ;
100 docs; 7.37; 8.35; 84.38; -1.00; -1.00; -1.00; ;
1000 docs; 57.52; 53.01; -1.00; -1.00; -1.00; -1.00; ;
10000 docs; 808.65; -1.00; -1.00; -1.00; -1.00; -1.00; ;
100000 docs; -1.00; -1.00; -1.00; -1.00; -1.00; -1.00; ;

To get the output, I used iExplore to look at the iPhone, under apps/HeadlessBee/Documents there is a file named bee_csv.txt
