### ISSUE TITLE
save and lockForWriting issues

### ISSUE THREAD

**Issue by nl** [couchbase/couchbase-lite-ios#566]
For a couple of weeks, using the master branch, I've been having issues with CBL regularly failing to write to the database, and locking up indefinitely.

This manifests in two ways.

1) When starting up my app, I'll sometimes see messages about the SQL database being busy.
*** SQLITE database busy: <CBL_FMDatabase: 0x7ff06ad2b6a0>
*** SQLITE database busy: <CBL_FMDatabase: 0x7ff06ad2b6a0>
*** SQLITE database busy: <CBL_FMDatabase: 0x7ff06ad2b6a0>

2) When calling save: on a model, the following lockup happens.
https://gist.github.com/nl/7e264ef595b4301ffe91

The only way to completely work around this so far has been to delete the entire database in Application Support.

**Comment by snej** [comment]
Yikes. To diagnose that save lockup I'll need to see _all_ threads. Next time it happens, enter `bt all` in the debugger console and post that, please.

**Comment by nl** [comment]
The other threads don't seem to be doing much. Here you go.
https://gist.github.com/nl/6af502153ee532c7f851

**Comment by nl** [comment]
Oops, it seems lldb when used from the terminal doesn't print everything out. Here's a more thorough backtrace. https://gist.github.com/nl/da19ea994912d4ea16bb
I can confirm the same issue also happens if i revert CBL to the latest release instead of tip of master.

**Comment by pasin** [comment]
Can you provide steps that we can use to reproduce in house?

**Comment by nl** [comment]
This seems to happen exclusively when one (or more) documents in the database have several thousand revisions.

**Comment by pasin** [comment]
@nl, I understand that you are building the library yourself from the master branch. 

Could you change the constant LOG_LOCKS to 1 at FMDatabase.m (https://github.com/couchbaselabs/fmdb/blob/master/src/FMDatabase.m#L21), rebuild the library and reproduce the issue? Setting LOG_LOCKS to 1 will log database acquiring and releasing locking message sequences.

**Comment by snej** [comment]
The backtrace from 20 Jan shows the main thread blocked waiting for the database lock, while thread 11 (the background/replicator thread) is busy inserting documents. To that extent it looks normal — I don't see any sign of trouble involving the lock itself. 

If the app is hung, that must mean that the background thread is stuck inside the transaction and never exits. Are you sure it isn't just taking a long time? Sampling the app in this state would give a better idea of what the background thread is doing, but I don't know how to sample an already-running iOS app. (Turning on SyncVerbose logging would be an alternate way to get some insight into it.)

**Comment by pasin** [comment]
@nk Per Jens's comment, does the lock stay forever or is it just very slow (due to high # of docs)?

If you think there is a real dead lock issue here, could you provide me more information that I can use to reproduce?
1. # of document, document & attachment size.
2. # of revision of each document on Avg. High # of revisions that you think it causes the issue.
3. What are the scenarios/steps to cause the lock (e.g. start a query / live query over a large set of documents and update a document at the same time).
4. (If possible) Share you database or source code that I can use to reproduce the issue.

**Comment by nl** [comment]
I think the issue is it gets very slow and/or never finishes because of the high number of revisions. i don't think it's a deadlock, cause I can see CPU consumption at 100% with no app usage other than CBL housekeeping: threads aren't sitting there idling. I'm not seeing this with 1.0.4, only master, so I've reverted to 1.0.4 but will give master a try again soon.

**Comment by snej** [comment]
Could you please get a CPU sample of the app while it's in this state?

**Comment by nl** [comment]
I pulled master and am not seeing this issue anymore at the moment.

**Comment by snej** [comment]
That's what we like to hear :)
