### ISSUE TITLE
SetDescending not working in android

### ISSUE THREAD

**Issue by marpal** [couchbase/couchbase-lite-ios#568]
Hi, 

We are having a problem in the Android version of our product with the SetDescending(true) on a complex query. 

Below is a gist with the code. 
https://gist.github.com/marpal/c657756acde567067c83

When SetDescending is set to true on the query, then the query returns no row. Without the SetDescending set to true the query returns the correct result. 

Thanks,
Martin

**Comment by pasin** [comment]
Please create this issue in https://github.com/couchbase/couchbase-lite-android repo.

**Comment by snej** [comment]
Your startKey and endKey are backwards. For a descending query the startKey should be the higher one and the endKey should be the lower.
