### ISSUE TITLE
Use CBLQueryBuilder in CBLIncrementalStore

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#571]
Use CBLQueryBuilder in CBLIncrementalStore so that:
1. View can be auto-generated based on fetch request's predicate.
2. Support more types of predicates such as compound predicates.
3. Simplify query coding logic.

Limitation:
No relationship queries (Join) supported by CBLQueryBuilder. We could detect this and fall back to full-table scan as the current CBLIncrementalStore does when there are no views specified.

**Comment by snej** [comment]
Can this be closed now that the PR has been merged? Or is there more work?

**Comment by pasin** [comment]
This can be closed now.
