### ISSUE TITLE
CouchbaseConnect2014 demo app fails when updating Xamarin Forms Package

### ISSUE THREAD

**Issue by ltaljaard** [couchbase/couchbase-lite-ios#573]
Hello

When updating the Xamarin.Forms NuGet package in your demo CouchbaseConnect2014 solution (and specifically in the CouchbaseConnect2014.iOS project), I get the following error: "Could not install package 'Couchbase.Lite 1.0.4.1'. You are trying to install this package into a project that targets 'MonoTouch,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

I need to update to the latest Xamarin.Forms package as I need access to recently released Xamarin.Forms features.

PS: I have also tried adding the Couchbase Lite NuGet package to a new PCL based project, but apparently PCL is not supported as of yet ( https://github.com/couchbase/couchbase-lite-net/issues/371 ). Hence, as an alternative, I'm trying to copy the CBConnect2014 demo app and just adapting it to my needs from there - but if I can't update to the latest Xamarin.Forms, this approach would be futile as well...

Please advise.

**Comment by snej** [comment]
Hi, this should be filed against [the .NET repo](https://github.com/couchbase/couchbase-lite-net/issues). I'd move it there for you, but Github doesn't let you move issues across projects…
