### ISSUE TITLE
New object notification not generated when using CBLIncrementalStore

### ISSUE THREAD

**Issue by CapoChino** [couchbase/couchbase-lite-ios#576]
On 2 devices, I'm running the [Recipe example] (https://github.com/couchbaselabs/cblite-coredata-sample-ios) that uses CBLIncrementalStore.  When I edit an item on one device, the change is propagated to the other device.  That's great.  However, when I create a new Recipe on one device, the behavior isn't perfect.  The addition does indeed sync to the other device, but the NSManagedObjectContext is never notified of the addition, so the new item does not appear in the table on the 2nd device.  Even performing the fetch again and reloading the table data is not enough to cause the new item to show up.  If I restart the app, it will then appear.

**Comment by snej** [comment]
@pasin is currently working on NSIncrementalStore so I'll assign this to him.

**Comment by CapoChino** [comment]
Fix worked for me, thank you @pasin!
