### ISSUE TITLE
Fatal runtime error on launch of ToDoLite: "no CBL_SQLiteStorage class found"

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#586]
I built the framework from the master branch, tested with ToDoLite app and got the following error:

```
2015-02-08 18:41:52.014 ToDoLite[43341:830213] *** ASSERTION FAILED: CBLManager.storageType is 'SQLite' but no CBL_SQLiteStorage class found
2015-02-08 18:41:52.015 ToDoLite[43341:830213] *** Assertion failure in -[CBLDatabase(Internal) open:](), /Users/pasin/Git/couchbase/couchbase-lite-ios/Source/CBLDatabase+Internal.m:160
2015-02-08 18:41:52.021 ToDoLite[43341:830213] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Assertion failed: CBLManager.storageType is 'SQLite' but no CBL_SQLiteStorage class found'
```

I checked the codes under the Storage folder and found that CBL_SQLiteStorage's target is set to `CBL Mac` only. Most of the files in the Storage folder was configured the same way. 

@snej, could you revise this?

**Comment by snej** [comment]
No, CBL_SQLiteStorage is also in the "CBL SQLite Storage" target, and that library gets copied into CouchbaseLlite.framework in iOS.

**Comment by snej** [comment]
My built framework has that class:

```
$ nm CouchbaseLite.framework/CouchbaseLite | grep '.*CLASS.*CBL_SQLiteStorage'
0000000000021040 S _OBJC_CLASS_$_CBL_SQLiteStorage
0000000000021018 S _OBJC_METACLASS_$_CBL_SQLiteStorage
00000000000206c8 s l_OBJC_CLASS_PROTOCOLS_$_CBL_SQLiteStorage
0000000000020f20 s l_OBJC_CLASS_RO_$_CBL_SQLiteStorage
00000000000206e0 s l_OBJC_METACLASS_RO_$_CBL_SQLiteStorage
```

**Comment by pasin** [comment]
I will rebuilt and retested this and let you know.

**Comment by pasin** [comment]
I still have the same issue. My nm result was the same as yours:

```
$ nm CouchbaseLite.framework/CouchbaseLite | grep '.*CLASS.*CBL_SQLiteStorage'
0000000000020ab0 S _OBJC_CLASS_$_CBL_SQLiteStorage
0000000000020a88 S _OBJC_METACLASS_$_CBL_SQLiteStorage
0000000000020138 s l_OBJC_CLASS_PROTOCOLS_$_CBL_SQLiteStorage
0000000000020990 s l_OBJC_CLASS_RO_$_CBL_SQLiteStorage
0000000000020150 s l_OBJC_METACLASS_RO_$_CBL_SQLiteStorage
```

**Comment by pasin** [comment]
Do we still build the framework for iOS with `Continuous iOS` scheme?

**Comment by snej** [comment]
I think so. But the scheme doesn't really matter for this, the target does. The Build Phases for the "CBL iOS Library" target link the library libCBLSQLiteStorage.a, which contains that class.

**Comment by snej** [comment]
Turns out the ToDoLite target was missing the `-ObjC` linker flag. The result was that the linker decided to dead-strip the CBLSQLiteStorage class, because there are no direct references to it elsewhere in the code (it's kind of a plug-in, so it's only looked up dynamically via `NSClassFromString`.) Adding `-ObjC` to "Other Linker Flags" fixed the problem.

I'm pretty sure we already tell developers they need this flag. It was necessary at one point, but apparently not recently because ToDoLite was working without it. We should check the docs to make sure (and our other demo apps!)
