### ISSUE TITLE
sqlite3-unicodesn submodule was not included in vendor folder

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#587]
The `sqlite3-unicodesn` submodule is missing from https://github.com/couchbase/couchbase-lite-ios/tree/master/vendor. Somehow when I updated the submodule, sqlite3-unicodesn was downloaded but the folder is untracked.

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	vendor/sqlite3-unicodesn/
```

**Comment by snej** [comment]
It used to be a submodule of couchbxse-lite-ios, but now it's a submodule of CBForest. You can delete the obsolete folder.
