### ISSUE TITLE
Optimize indexing by letting view specify a "type" value

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#590]
It's very common for a view to index only a particular type of document, as indicated by its `type` property. So the map block will often start with `if (![doc[@"type] isEqual: @"sometype"]) return;`.

If we allowed a view to state that it only applies to docs with a specific `type` value, then the indexer could use that information to avoid a lot of wasted time fetching and parsing irrelevant docs:

* In SQLite we can add a `type` column to `rev` and index it, then restrict the indexer query to only the matching type(s).
* In ForestDB we can put the type into the document metadata and check it before reading the document body.

**Comment by snej** [comment]
Note 1: CBLQueryBuilder can make use of this by checking whether the map predicate tests doc.type.

Note 2: If we want developers not using CBLQueryBuilder to use this, we'll need an API addition — something like a `CBLView.documentType` property.

**Comment by snej** [comment]
There's a [tech note](https://github.com/couchbase/couchbase-lite-ios/wiki/CBLView.documentType) in the wiki now, describing what this is and how to use it.

**Comment by jeanregisser** [comment]
Great addition!

Would it be possible to make the "type" key configurable?

When my team migrated to couchbase we had a set of existing documents to migrate and couldn't use the "type" key because it was already used in them for a different purpose.
We ended up using a key name "doctype" instead.

**Comment by snej** [comment]
I knew someone was going to ask that… :grimacing: I'll have to think about it. It's probably not too hard, but I'm not sure where to store the magic property name and how to set it.

**Comment by skela** [comment]
I have a somewhat related question in that we don't have "type", but use a document id prefix as a type descriptor. Would it be possible to make use of this ?

**Comment by snej** [comment]
Same answer, I'm afraid! If we make it configurable we can do something like letting you specify a pattern in the docID.

There wasn't any issue covering making this flexible, so I've just filed one.
