### ISSUE TITLE
LiveQuery should re-run query from scratch after options are changed

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#596]
Changing the query options of an already-running CBLLiveQuery should be supported, and should re-run the query from scratch (regardless of the view's current sequence number.)

**Comment by atkit** [comment]
thanks

**Comment by atkit** [comment]
Am I correct, every time we change LiveQuery parameters we should call:
```
queryOptionsChanged
```
as well

**Comment by pasin** [comment]
Yes, you are correct.

**Comment by snej** [comment]
Rationale was that there are a _lot_ of properties that can be set, and we thought it wasn't worth creating custom setters for every single one of them to detect changes (or adding dozens of KV observers.) Especially since it's likely you'll change more than one of them at a time, so there'd be extra complexity to wait for you to stop making changes before triggering the query...
