### ISSUE TITLE
iOS Dynamic Framework / Module support

### ISSUE THREAD

**Issue by lordkev** [couchbase/couchbase-lite-ios#597]
Opening this per the list discussion here:

https://groups.google.com/forum/#!topic/mobile-couchbase/q2kLQv01LKQ

This would allow the library to be built as an iOS 8+ dynamic framework under a new additional target. Should have a PR incoming in the next few days.

**Comment by snej** [comment]
The "CBL iOS Framework" target builds a true dynamic-library framework for use in iOS 8.

Note: This library isn't fat. I'm actually unsure whether we _should_ build a fat dynamic library; I don't know if the simulator code will get stripped out when the developer's app is built.

**Comment by lordkev** [comment]
Great, thanks for this. Apologies for not getting around to finishing it up - got busy with other stuff.

**Comment by snej** [comment]
No prob. I felt better about doing it myself anyway … no slight intended, it's just that the build settings in the project are pretty complex and prone to breaking if not treated exactly right :)

**Comment by lordkev** [comment]
None take, I understand. :)
