### ISSUE TITLE
Sync pull replication not working

### ISSUE THREAD

**Issue by marbetschar** [couchbase/couchbase-lite-ios#599]
I'm trying to implement sync in my iOS app. I can see the push/pull are running and the documents are sent to the Couchbase Server (seeing them in the Admin Console).

But for some reason, pulling the data to other devices does not store them in the Couchbase-Lite catalog (when I'm opening the Couchbase-Lite database of iOS Simulator I can't see newly added documents of another device).

That's the code used for syncing:

    let syncURL		= NSURL(string: "http://myserverurl:4984/mybucket/")
    let syncAuth	= CBLAuthenticator.basicAuthenticatorWithName("myusername", password: "mypassword")
    self.pushSync	= CBLConnector.sharedInstance.database.createPushReplication(syncURL)
    self.pullSync	= CBLConnector.sharedInstance.database.createPullReplication(syncURL)
			
    self.pushSync.continuous = true
    self.pullSync.continuous = true
			
    self.pushSync.authenticator = syncAuth
    self.pullSync.authenticator = syncAuth
			
    NSNotificationCenter.defaultCenter().addObserver(self, selector: "syncChanged:", name: kCBLReplicationChangeNotification, object: self.pushSync)
    NSNotificationCenter.defaultCenter().addObserver(self, selector: "syncChanged:", name: kCBLReplicationChangeNotification, object: self.pullSync)
			
    self.pushSync.start()
    self.pullSync.start()

What's wrong?

**Comment by pasin** [comment]
Can you enable 'Sync' and 'SyncVerbose' log and post the log messages?

```
CBLManager.enableLogging("Sync")
CBLManager.enableLogging("SyncVerbose")
```

**Comment by marbetschar** [comment]
Hi Pasin! Thanks for helping out!!
Sure, I got the following by enable the login.

03:41:17.971‖ SyncVerbose: CBL_Pusher[http://biz.mandelkind.ch:4984/mandelkind/]: Queuing #154 {11802F2A-3343-43BA-8D7C-6C8CB8FEFCAB #1-db79d018a4acd5db013db099335fc64f}
    03:41:17.971‖ Sync: CBL_Pusher[http://biz.mandelkind.ch:4984/mandelkind/] Progress: set active = 1
    03:41:17.971‖ SyncVerbose: CBL_Pusher[http://biz.mandelkind.ch:4984/mandelkind/]: postProgressChanged (0/0, active=1 (batch=1, net=0), online=1)
    03:41:17.971‖ SyncVerbose: *** CBL_Pusher[http://biz.mandelkind.ch:4984/mandelkind/]: BEGIN processInbox (1 sequences)
    03:41:17.971‖ SyncVerbose: CBL_Pusher[http://biz.mandelkind.ch:4984/mandelkind/]: POST _revs_diff
    03:41:17.972‖ SyncVerbose: *** CBL_Pusher[http://biz.mandelkind.ch:4984/mandelkind/]: END processInbox (lastSequence=153)
    03:41:17.986‖ Sync: CBL_Pusher[http://biz.mandelkind.ch:4984/mandelkind/]: Sending 1 revisions
    03:41:17.986‖ SyncVerbose: CBL_Pusher[http://biz.mandelkind.ch:4984/mandelkind/]: Sending (
        "{11802F2A-3343-43BA-8D7C-6C8CB8FEFCAB #1-db79d018a4acd5db013db099335fc64f}"
    )
    03:41:17.988‖ SyncVerbose: CBL_Pusher[http://biz.mandelkind.ch:4984/mandelkind/]: postProgressChanged (0/1, active=1 (batch=0, net=1), online=1)
    03:41:17.988‖ SyncVerbose: CBL_Pusher[http://biz.mandelkind.ch:4984/mandelkind/]: POST _bulk_docs
    03:41:18.003| Sync: CBLReplication[to http://biz.mandelkind.ch:4984/mandelkind/]: active, progress = 0 / 0, err: (null)
    03:41:18.004| Sync: CBLReplication[to http://biz.mandelkind.ch:4984/mandelkind/]: active, progress = 0 / 1, err: (null)
    03:41:18.006‖ SyncVerbose: CBL_Pusher[http://biz.mandelkind.ch:4984/mandelkind/]: Setting lastSequence to 154 (from 153)
    03:41:18.006‖ SyncVerbose: CBL_Pusher[http://biz.mandelkind.ch:4984/mandelkind/]: Sent (
        "{11802F2A-3343-43BA-8D7C-6C8CB8FEFCAB #1-db79d018a4acd5db013db099335fc64f}"
    )
    03:41:18.007‖ Sync: CBL_Pusher[http://biz.mandelkind.ch:4984/mandelkind/] Progress: 1 / 1
    03:41:18.007‖ SyncVerbose: CBL_Pusher[http://biz.mandelkind.ch:4984/mandelkind/]: postProgressChanged (1/1, active=1 (batch=0, net=1), online=1)
    03:41:18.007‖ Sync: CBL_Pusher[http://biz.mandelkind.ch:4984/mandelkind/] Progress: set active = 0
    03:41:18.007‖ SyncVerbose: CBL_Pusher[http://biz.mandelkind.ch:4984/mandelkind/]: postProgressChanged (1/1, active=0 (batch=0, net=0), online=1)
    03:41:18.008| Sync: CBLReplication[to http://biz.mandelkind.ch:4984/mandelkind/]: idle, progress = 1 / 1, err: (null)
    03:41:23.006‖ Sync: CBL_Pusher[http://biz.mandelkind.ch:4984/mandelkind/] checkpointing sequence=154
    03:41:23.007‖ SyncVerbose: CBL_Pusher[http://biz.mandelkind.ch:4984/mandelkind/]: PUT _local/1886d397b44885836c2c1555b7d9e64bf2054593
    03:41:23.027‖ Sync: CBL_Pusher[http://biz.mandelkind.ch:4984/mandelkind/] saved remote checkpoint '154' (_rev=0-10)
    2015-02-14 03:41:53.846 biz[37860:2934308] the behavior of the UICollectionViewFlowLayout is not defined because:
    2015-02-14 03:41:53.846 biz[37860:2934308] the item width must be less than the width of the UICollectionView minus the section insets left and right values.
    2015-02-14 03:41:53.846 biz[37860:2934308] the behavior of the UICollectionViewFlowLayout is not defined because:
    2015-02-14 03:41:53.847 biz[37860:2934308] the item width must be less than the width of the UICollectionView minus the section insets left and right values.
    03:41:59.342| APP BACKGROUNDING
    03:41:59.342‖ Sync: CBL_Pusher[http://biz.mandelkind.ch:4984/mandelkind/]: Reachability state = <biz.mandelkind.ch>:reachable (02), suspended=1
    03:41:59.343‖ Sync: CBL_Pusher[http://biz.mandelkind.ch:4984/mandelkind/]: Going offline
    03:41:59.343‖ Sync: Stopping 0 remote requests
    03:41:59.343‖ SyncVerbose: CBL_Pusher[http://biz.mandelkind.ch:4984/mandelkind/]: postProgressChanged (1/1, active=0 (batch=0, net=0), online=0)
    03:41:59.343| APP BACKGROUNDING
    03:41:59.344‖ Sync: CBL_Puller[http://biz.mandelkind.ch:4984/mandelkind/]: Reachability state = <biz.mandelkind.ch>:reachable (02), suspended=1
    03:41:59.344‖ Sync: CBL_Puller[http://biz.mandelkind.ch:4984/mandelkind/]: Going offline
    03:41:59.344‖ Sync: Stopping 0 remote requests
    03:41:59.344‖ SyncVerbose: CBL_Puller[http://biz.mandelkind.ch:4984/mandelkind/]: postProgressChanged (0/0, active=0 (batch=0, net=0), online=0)
    03:41:59.344‖ Sync: CBL_Puller[http://biz.mandelkind.ch:4984/mandelkind/]: ChangeTracker stopped; error=(null)
    03:42:00.365| Sync: CBLReplication[to http://biz.mandelkind.ch:4984/mandelkind/]: offline, progress = 1 / 1, err: (null)
    03:42:00.365| Sync: CBLReplication[from http://biz.mandelkind.ch:4984/mandelkind/]: offline, progress = 0 / 0, err: (null)
    03:42:00.917| APP FOREGROUNDING
    03:42:00.917| APP FOREGROUNDING
    03:42:00.917‖ Sync: CBL_Pusher[http://biz.mandelkind.ch:4984/mandelkind/]: Reachability state = <biz.mandelkind.ch>:reachable (02), suspended=0
    03:42:00.917‖ Sync: CBL_Pusher[http://biz.mandelkind.ch:4984/mandelkind/]: Going online
    03:42:00.918‖ Sync: CBL_Pusher[http://biz.mandelkind.ch:4984/mandelkind/] Progress: set active = 1
    03:42:00.918‖ SyncVerbose: CBL_Pusher[http://biz.mandelkind.ch:4984/mandelkind/]: postProgressChanged (1/1, active=1 (batch=0, net=1), online=1)
    03:42:00.918‖ SyncVerbose: CBL_Pusher[http://biz.mandelkind.ch:4984/mandelkind/]: GET _local/1886d397b44885836c2c1555b7d9e64bf2054593
    03:42:00.918‖ SyncVerbose: CBL_Pusher[http://biz.mandelkind.ch:4984/mandelkind/]: postProgressChanged (1/1, active=1 (batch=0, net=1), online=1)
    03:42:00.918‖ Sync: CBL_Puller[http://biz.mandelkind.ch:4984/mandelkind/]: Reachability state = <biz.mandelkind.ch>:reachable (02), suspended=0
    03:42:00.919‖ Sync: CBL_Puller[http://biz.mandelkind.ch:4984/mandelkind/]: Going online
    03:42:00.919‖ Sync: CBL_Puller[http://biz.mandelkind.ch:4984/mandelkind/] Progress: set active = 1
    03:42:00.920‖ SyncVerbose: CBL_Puller[http://biz.mandelkind.ch:4984/mandelkind/]: postProgressChanged (0/0, active=1 (batch=0, net=1), online=1)
    03:42:00.920‖ SyncVerbose: CBL_Puller[http://biz.mandelkind.ch:4984/mandelkind/]: GET _local/a7588ea8dea1f4890c2567a025be573f04b3f4b2
    03:42:00.920‖ SyncVerbose: CBL_Puller[http://biz.mandelkind.ch:4984/mandelkind/]: postProgressChanged (0/0, active=1 (batch=0, net=1), online=1)
    03:42:00.930| Sync: CBLReplication[to http://biz.mandelkind.ch:4984/mandelkind/]: active, progress = 1 / 1, err: (null)
    03:42:00.930| Sync: CBLReplication[from http://biz.mandelkind.ch:4984/mandelkind/]: active, progress = 0 / 0, err: (null)
    03:42:00.954‖ Sync: CBL_Pusher[http://biz.mandelkind.ch:4984/mandelkind/]: Replicating from lastSequence=154
    03:42:00.955‖ SyncVerbose: CBL_Pusher[http://biz.mandelkind.ch:4984/mandelkind/]: Received 0 revs
    03:42:00.955‖ Sync: CBL_Pusher[http://biz.mandelkind.ch:4984/mandelkind/] Progress: set active = 0
    03:42:00.955‖ SyncVerbose: CBL_Pusher[http://biz.mandelkind.ch:4984/mandelkind/]: postProgressChanged (1/1, active=0 (batch=0, net=0), online=1)
    03:42:00.955| Sync: CBLReplication[to http://biz.mandelkind.ch:4984/mandelkind/]: idle, progress = 1 / 1, err: (null)
    03:42:00.982‖ Sync: CBL_Puller[http://biz.mandelkind.ch:4984/mandelkind/]: Replicating from lastSequence=(null)
    03:42:00.982‖ SyncVerbose: CBL_Puller[http://biz.mandelkind.ch:4984/mandelkind/] starting ChangeTracker: mode=3, since=(null)
    03:42:00.983‖ SyncVerbose: CBLWebSocketChangeTracker[0x7fa650dec000 mandelkind]: GET //biz.mandelkind.ch:4984/mandelkind/_changes?feed=websocket
    03:42:01.059‖ Sync: CBL_Puller[http://biz.mandelkind.ch:4984/mandelkind/]: Caught up with changes!
    03:42:01.059‖ Sync: CBL_Puller[http://biz.mandelkind.ch:4984/mandelkind/] Progress: set active = 0
    03:42:01.059‖ SyncVerbose: CBL_Puller[http://biz.mandelkind.ch:4984/mandelkind/]: postProgressChanged (0/0, active=0 (batch=0, net=0), online=1)
    03:42:01.059| Sync: CBLReplication[from http://biz.mandelkind.ch:4984/mandelkind/]: idle, progress = 0 / 0, err: (null)

First I've added a new record in the iOS Simulator to force pushing the new record to the server.
Afterwards I've added a new record on the iPhone - which kicked off the second sync process.

But still no luck seeing the record in the database :(

**Comment by pasin** [comment]
I don't see anything wrong from the log. The puller just didn't get any docs. I suspected that the issue might be at the sync function. Can you check the sync function if you granted the user (your simulator user) to the channel that you put the document into?

**Comment by marbetschar** [comment]
I did not specify any channel yet - how may I do this? The code posted in my first comment is truly everything I've took in place till now :(

**Comment by marbetschar** [comment]
Wow!

The reason was, I didn't specify the channels for the user on the sync server. The user had a configuration like the following:

    {"name":"mandelkind","all_channels":[]}

After mutating the user using the Sync REST API:

    curl -X PUT localhost:4985/mandelkind/_user/mandelkind --data '{"admin_channels":["*"]}'
    {"name":"mandelkind","admin_channels":["*"],"all_channels":["*"]}

Things just magically started working!

Thank you very much! YOU'VE MADE MY DAY!!!

**Comment by pasin** [comment]
Glad to hear that you make it working.

If you wanna see some samples of sync-gateway config, you may look at these repos:
https://github.com/couchbaselabs/TodoLite-iOS
https://github.com/couchbaselabs/Grocery-Sync-iOS

The Sync Gateway documentation is [here] (http://developer.couchbase.com/mobile/develop/guides/sync-gateway/index.html).

We also have a user [forum] (https://forums.couchbase.com/c/mobile) that you can ask questions.
