### ISSUE TITLE
Error saving CBLModel in iOS

### ISSUE THREAD

**Issue by marbetschar** [couchbase/couchbase-lite-ios#612]
Hi!
I'm trying to save a CBLModel with the following property definition:

    @NSManaged var calendardates: NSArray

Containing the following value

    (
        {
            label = "B781C88C-D0DA-4E78-A600-6E788D774C45";
            value = "2015-02-27 22:21:39 +0000";
        }
    )

Unfortunately this does not work since I receive the following error:

    2015-02-27 23:21:42.672 biz[48763:7492646] Error saving Bean: Optional(Error Domain=CBLHTTP Code=400 "400 Invalid JSON" UserInfo=0x7ff119f31580 {NSLocalizedFailureReason=Invalid JSON, NSLocalizedDescription=400 Invalid JSON})

Is this a bug or am I missing something?

**Comment by pasin** [comment]
Is the value's data type NSDate or String? 

FYI, NSDate is not  a valid JSON date type. To store NSDate values in a JSON document, you will need to convert them into ISO-8601 format. You can sue CBLJSON utility class to do that:

```
CBLJSON.JSONObjectWithDate(NSDate())
```

**Comment by marbetschar** [comment]
Hi Pasin! The value's dat type is NSDate - so this seems to be the issue?
How may I best intercept storing and loading the values in the array? So the NSDate is converted to ISO and vice versa?

**Comment by pasin** [comment]
If you want to store date value in a dictionary (JSON Doc), you will need to convert it to ISO-8601 format. 

Per your intercepting question, there is a function called `willSave(changedPropertyNames: NSSet!)` that you call override and modify data before save, but I do not recommend this as you are going to change the data type (you will end up having to deal with 2 data types (NSDate and NSString). See Customizing saving section in http://developer.couchbase.com/mobile/develop/guides/couchbase-lite/native-api/model/index.html.

If you store only an array of NSDate (but not dictionary), you can declare the data type as a sample objective-c (Not sure what is Class equivalent in swift) below:

```
// Objective-c
+ (Class) calendardatesClass {
    return [NSDate class];
}
```

Another option would be creating a new custom class implementing CBLJSONEncoding protocol and store instance of that class in the array instead of the dictionary.

**Comment by pasin** [comment]
I'm closing the issue now. Feel free to post any more comments or reopen the ticket if you found a bug.

**Comment by snej** [comment]
You may want to create a custom class for the array values; the class would store the label and date. Then you need to make the class implement the `CBLJSONEncoding` protocol, so it can load/save to JSON. Your model class would declare that the array items are instances of that class.

**Comment by marbetschar** [comment]
Ok thanks! Seems like I'd have to go down the CBLJSONEncoding route.
There is just one last question left.

I've implemented the object according to the docs and your advice as follows:

    @objc(NSLabeledDate)
    class NSLabeledDate: NSObject,CBLJSONEncoding{
	var value: NSDate?
	var label: NSString?
	
	
	required init(JSON jsonObject: AnyObject!){
		println("JSON")
		let json = jsonObject as [String:NSObject]
		
		if let label = json["label"] as? NSString{
			self.label = label
		}
		
		if let val = json["value"]{
			self.value = CBLJSON.dateWithJSONObject(val)
		}
	}
	
	
	convenience init(item: FormItemDescriptor){
		var json = [String:NSObject]()
		
		if let val = item.value as? NSDate{
			json["value"] = CBLJSON.JSONObjectWithDate(val)
		}
		
		if let label = item.labelValue{
			json["label"] = (label as Label).document.documentID
			
		} else if let label = item.defaultLabelValue{
			json["label"] = (label as Label).document.documentID
		}
		
		self.init(JSON: json)
	}
	
	
	func encodeAsJSON() -> AnyObject! {
		var json = [String:NSObject]()
		
		if let val = self.value{
			json["value"] = CBLJSON.JSONObjectWithDate(val)
		}
		
		if let label = self.label{
			json["label"] = self.label
		}
		
		return json
	}
    }

Which let's me save the object to the database.
Unfortunately for some reason it does not get initialized when items are loaded from the database.

I've tried also adding the itemClass to the property

    class func calendardatesItemClass() -> AnyClass{
		return NSLabeledDate.self
    }

But this does not seem to have any effect.
What's wrong?

**Comment by snej** [comment]
I'm not sure what's wrong. Try setting a breakpoint in the `calendardatesItemClass` method, and see if it gets called when a model is loaded.

(Also, btw, you should never begin a class name with `NS`. That prefix is reserved by Apple.)

**Comment by marbetschar** [comment]
Ok, Thx!
