### ISSUE TITLE
-[CBL_Puller pullBulkRevisions:] crash

### ISSUE THREAD

**Issue by nl** [couchbase/couchbase-lite-ios#613]
This crash happened during a pull replication from the gateway in CBL 1.0.4.
https://gist.github.com/nl/6ebd699c515d0078b2b6

**Comment by snej** [comment]
```
__32-[CBL_Puller pullBulkRevisions:]_block_invoke274 + 425
-[CBLRemoteRequest respondWithResult:error:] + 214
-[CBLRemoteRequest connection:didFailWithError:] + 490
-[CBLRemoteRequest cancelWithStatus:] + 203
-[CBLRemoteRequest connection:didReceiveResponse:] + 731
-[CBLBulkDownloader connection:didReceiveResponse:] + 495
__65-[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:]_block_invoke + 69
```

**Comment by pasin** [comment]
As the crash happens inside the block, the crash log doesn't reveal exactly where the crash happened. I tried to reproduce the crash myself by simulating an error based on your log in several ways that I can think of but I still have no luck.  

Can you help trying to make the app crash again with zombie enabled? or at least, can you capture where the XCode highlights when the app crashes?

**Comment by pasin** [comment]
Wait! I think I was able to reproduce it. To reproduce it, the error code needs to be one of the permanent errors which will causes the stop method to get called when setting the error. I hope this is the same scenario that you encountered. It would be great if you can let me the error code that you got when the app crashed.

**Comment by snej** [comment]
Well, we know it's 425 bytes into the block. If you check out the 1.0.4 tag and disassemble the optimized x86-64 version of CBLPuller, you can look at what's at that offset past `_block_invoke274`.

**Comment by pasin** [comment]
Thanks Jens for pointing this out. Reading the assemble code now, just disassemble the binary and it the offset (+425) is at same line that I got the crash.

```
00000000000167b3         mov        rsi, qword [ds:0x266a20]                    ; @selector(setChangesProcessed:), argument "selector" for method imp___stubs__objc_msgSend
00000000000167ba         mov        rcx, qword [ss:rbp+var_68]
00000000000167be         mov        rdi, rcx                                    ; argument "instance" for method imp___stubs__objc_msgSend
00000000000167c1         mov        rdx, rax
00000000000167c4         call       imp___stubs__objc_msgSend
00000000000167c9         mov        rax, qword [ss:rbp+var_28]
00000000000167cd         mov        rcx, qword [ss:rbp+var_40]
00000000000167d1         mov        rdx, qword [ds:rcx+0x30]
00000000000167d5         mov        rdx, qword [ds:rdx+0x8]
00000000000167d9         mov        rdx, qword [ds:rdx+0x28]
```
