### ISSUE TITLE
Indexing scales poorly, due to suboptimal SQL DELETE query

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#615]
A customer has noticed that view index updating gets very slow in large databases; they even plotted a graph showing that the time increases linearly with number of documents. The slow part is in between the `Checking indexes` and `Updating indexes` log messages. That points to the SQL DELETE query that removes obsolete index rows.
```sql
DELETE FROM maps WHERE sequence IN (
SELECT parent FROM revs WHERE sequence>?
AND parent>0 AND parent<=?)
```
The problem is that the query is using a suboptimal index:
```
$$$ Caching SQL query: DELETE FROM maps WHERE sequence IN (SELECT parent FROM revs WHERE sequence>? AND parent>0 AND parent<=?)
0 0 0 SEARCH TABLE maps USING COVERING INDEX maps_sequence (sequence=?)
0 0 0 EXECUTE LIST SUBQUERY 0
0 0 0 SEARCH TABLE revs USING COVERING INDEX revs_parent (parent>? AND parent<?)
```
`revs_parent` is the wrong index to use. Instead it should be using the implicit `sequence` index of `rows` (implicit because `sequence` is the primary key.)

The SQLite docs show how to stop `revs_parent` from being used: add a unary `+` before the terms that involve `parent`:
```sql
... AND +parent>0 AND +parent<=?)
```

**Comment by snej** [comment]
@hideki @borrrden — this same query probably exists in the Java and C# versions, and should be fixed there too.

**Comment by tleyden** [comment]
Added downstream tickets for java-core and .net

**Comment by snej** [comment]
FYI, while these are valid optimizations, the customer reports they aren't having an effect on their slow performance. I'm guessing in their case the time is dominated by the actual deletion of the rows from the table, not by the lookup of which rows to delete.

**Comment by snej** [comment]
Customer reports that updating the index of a large view (~100,000 rows) went from 20 sec down to 2 sec after this fix. Niiiice. :grinning:
