### ISSUE TITLE
API to know if a given channel has new updates on the server

### ISSUE THREAD

**Issue by jchris** [couchbase/couchbase-lite-ios#619]
In a scenario where a user has synced a few channels, but nothing is syncing now, there might be new updates available on those channels. If the application wants to prompt the user to sync (perhaps by highlighting the channels with updates available, and letting the user select which ones to pull), currently they have to engage in heavy workarounds involving the Sync Gateway REST API.

**Comment by jchris** [comment]
Maybe the underlying API is a REST API on the Sync Gateway (a query option on like `/db/_changes?since=MYCURRENTLASTSEQ&feed=channels` which would give you the list of channels that have changes since your current last seq. I think this is better than trying to parse the sequence id on the client.

**Comment by zgramana** [comment]
Why not just use etags for this? You could make a HEAD request and get back the current highest sequence number. If it matches, no need to sync. If it doesn't, you do.

**Comment by zgramana** [comment]
Requested for the Forest Service's use case.

**Comment by zgramana** [comment]
Refs couchbase/sync_gateway#712

**Comment by snej** [comment]
This is mostly a SG feature. Once they've implemented it as a REST API we can easily add a method that calls it.
