### ISSUE TITLE
Wrong emmitted data using ForestDB + FullTextSearch

### ISSUE THREAD

**Issue by razorblade446** [couchbase/couchbase-lite-ios#620]
Hi.

I'm currently testing for performance, the master branch using ForestDB as Storage Engine.

So far I can notice speedups, but i'm having trouble with FullTextSearch.

Here is my view declaration:

    CBLView *vistaRutasContactosMedicosFTS = [_db viewNamed:@"RutasContactosMedicosFTS"];
    
    [vistaRutasContactosMedicosFTS setMapBlock:^(NSDictionary *doc, CBLMapEmitBlock emit) {
        if([doc[@"type"] isEqualToString:@"RuteroMedicos"] && [doc[@"estado_contacto"] integerValue] != 4 && [doc[@"estado_contacto"] integerValue] != 2){
            
            NSString *datoTexto = [NSString stringWithFormat:@"%@ %@ %@ %@ %@ %@ %@", doc[@"codigo_contacto"], doc[@"nombres"], doc[@"apellidos"], doc[@"nombre_especialidad"], doc[@"direccion_visita"], doc[@"categoria_color"], doc[@"categoria_nombre"]];
            
            // Tokenizar y generar keys
            
			emit(CBLTextKey(datoTexto), @([doc[@"ruta_visita"] integerValue]));
        }
    } version:@"1.3"];

Using SQLite the view renders correctly (or that I presume) and let me use the CBLQueryRow.value for getting the data desired.

But when using ForestDB, the CBLQueryRow.value gets values in two groups, first the "keys" used by CBLTextKey, then NSArray, but neither the values i need.

I can use the specific property from the document emmited, but i cant use custom values, so i think is a different behavior than expected

Version: Couchbase-Lite-iOS Beta 1.1

**Comment by snej** [comment]
How are you querying the view? With a full-text view you need to set the `fullTextQuery` property to the string you want to search for.

Full-text query rows never have a key, but the `value` property should work — I just checked and it's broken in the master branch. I'll fix it.
