### ISSUE TITLE
CBLSocketChangeTracker not using OS proxy

### ISSUE THREAD

**Issue by notjosh** [couchbase/couchbase-lite-ios#622]
I'm using Charles to watch my requests fly by. It's great! But I'm not seeing `_changes` requests.

There are a couple of ways to address the issue. The [code responsible for proxy support](https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/ChangeTracker/CBLSocketChangeTracker.m#L98-L105) exists, and it's correct if `-my_proxySettings` returns the right value. It doesn't. It only returns the proxy information for the relevant URL ([see](https://github.com/snej/MYUtilities/blob/master/MYURLUtils.m#L118-L131) where it discards `proxySettings`, and only returns a `proxy`), not the full system proxy information that `CFReadStreamSetProperty()` expects. (For reference, [this gist](https://gist.github.com/notjosh/5922fb9063c2b2326321) shows the output of each of the values. You can see how drastic the difference is!)

I propose we just forward the system proxy settings on, if any exist. We don't need to do any checks via `-my_proxySettings`.

So, something simple like the following reduces dependency and complexity:

```objc
CFDictionaryRef proxySettings = CFNetworkCopySystemProxySettings();
if (proxySettings) {
    CFReadStreamSetProperty(cfInputStream, kCFStreamPropertyHTTPProxy, proxySettings);
}
CFRelease(proxySettings);
```

Thoughts? Can send a PR if you're into it.

**Comment by tleyden** [comment]
By default, the change tracker on ios uses websockets, which may be why it doesn't show up in Charles.  There is an option to disable websockets:

```
pullReplication.customProperties = @{@"websocket": @NO};
```

**Comment by notjosh** [comment]
Nah, I had breakpoints set to verify. If you take a look at the gist, you'll see it's passing the wrong params in as proxy settings, which explains why it's not adopting them.

**Comment by snej** [comment]
@tleyden - The WebSocket-based change tracker isn't used if there's a proxy present (because I don't know how to make GCDAsyncSocket use proxies). CBL_Puller has a proxy check that disables it.

@notjosh - Sure, please send a PR, please.

**Comment by tleyden** [comment]
> The WebSocket-based change tracker isn't used if there's a proxy present

Aha, good to know.

**Comment by snej** [comment]
Yeah, I'd forgotten about that check until I looked up the callers of `my_proxySettings` just now :)
