### ISSUE TITLE
Replication loop with conflicts (status 594).

### ISSUE THREAD

**Issue by ndouglas** [couchbase/couchbase-lite-ios#629]
My project, ReactiveCouchbaseLite, tries to give a FRP interface (to the extent that it's possible) to Couchbase-Lite-iOS.  So, working on it, I'm doing a lot of unit tests with a standard setup (a database, a "peer" database (on the same device, but just a database with a different name), and push and pull replications set up from the test database to the "peer" database).

Generally this works well, but I'm seeing an issue with conflicts in replications.  I'm fairly sure it's a result of my ignorance, but since I can't confirm it (and it seems a bit odd), I thought I'd mention it.

Currently, I'm using the forestdb branch, commit dd20d33b4bc759bd76e3c84d0ed6e5dfbe313819.

You can view the source of the test I'm running here: ndouglas/ReactiveCouchbaseLite@05d999bdfd3d8f2ce57a5938d5286e57604795c5 

The RCLTestCase class does a number of things, but I think they're straightforward, and none of them use the code that I'm writing in my project.

Briefly, the test:
- gets the shared instance of CBLManager.
- generates a UUID (the test ID), uses that to create a database name (a valid one), and creates a "test" database.
- generates a different database name, and creates the "peer" database.
- sets up and starts an instance of CBLListener on some local port.
- creates a push replication for the test database, pushing to the peer database.
- creates a pull replication for the test database, pulling from the peer database.
- turns on logging (TDRouter, Sync, SyncVerbose, RemoteRequest, ChangeTracker, Query, CBLDatabase, CBLListener).
- loops from 1 to *n*:
 - creates a document on the test database and updates it with a UUID key and UUID value
 - creates a document on the peer database and updates it with a UUID key and UUID value
 - creates a new UUID, and
   - creates a document on the test database with that UUID as its ID and updates it with a UUID key and UUID value
    - creates a document on the peer database with that UUID as its ID and updates it with a UUID key and UUID value

So for *n* = 400, there should be 400 documents created on the test database, 400 documents created on the peer database, and 400 documents created on both the test and peer databases but with different values -- conflicts, in other words.

Instead, at some point, replication seems to get caught in a loop, and the number of documents to replicate will inch up steadily as replication proceeds.  Here's a log of this happening: https://gist.github.com/ndouglas/6f6d8a1b53652a7f4dcf

Normally, I'd think that I screwed something up -- maybe conflict resolution is an absolute must to keep replication working, etc.  Except this doesn't seem to happen at *n* = 50, or at least not reliably.  Increasing *n* to 100, though, it starts happening, or is more likely to happen.

It's worth noting that at some point, I encounter the following message in the log:

    11:15:21.129‖ WARNING: CBL_Puller[http://Leilah.local:2028/peer_4584659048870601316] failed to look up local revs; status=594

The backtrace of the relevant threads look like this:

        0	0x00007fff86305743 in objc_exception_throw ()
        1	0x00007fff90a4ddf4 in -[__NSArrayM objectAtIndex:] ()
        2	0x0000000105228af9 in -[CBL_RevisionList objectAtIndexedSubscript:] ()
        3	0x00000001052581e7 in __56-[CBLDatabase(Replication) findMissingRevisions:status:]_block_invoke ()
        4	0x000000010520d1a1 in -[CBLDatabase(Internal) _try:] ()
        5	0x0000000105258018 in -[CBLDatabase(Replication) findMissingRevisions:status:] ()
        6	0x0000000105220e0a in -[CBL_Puller processInbox:] ()
        7	0x0000000105232c10 in __23-[CBL_Replicator start]_block_invoke ()
        8	0x000000010524302a in -[CBLBatcher processNow] ()
        9	0x00007fff9511d84b in __NSFireDelayedPerform ()
        10	0x00007fff90ad6b64 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ ()
        11	0x00007fff90ad67f3 in __CFRunLoopDoTimer ()
        12	0x00007fff90b49dbd in __CFRunLoopDoTimers ()
        13	0x00007fff90a93288 in __CFRunLoopRun ()
        14	0x00007fff90a92858 in CFRunLoopRunSpecific ()
        15	0x00007fff95121849 in -[NSRunLoop(NSRunLoop) runMode:beforeDate:] ()
        16	0x000000010521dbaf in -[CBL_Server runServerThread] ()
        17	0x00007fff9511f90a in __NSThread__main__ ()
        18	0x00007fff94ec7268 in _pthread_body ()
        19	0x00007fff94ec71e5 in _pthread_start ()
        20	0x00007fff94ec541d in thread_start ()

or this: 

        0	0x00007fff86305743 in objc_exception_throw ()
        1	0x00000001059a5af9 in -[CBL_RevisionList objectAtIndexedSubscript:] ()
        2	0x00000001059d51e7 in __56-[CBLDatabase(Replication) findMissingRevisions:status:]_block_invoke ()
        3	0x000000010598a1a1 in -[CBLDatabase(Internal) _try:] ()
        4	0x00000001059d5018 in -[CBLDatabase(Replication) findMissingRevisions:status:] ()
        5	0x000000010599de0a in -[CBL_Puller processInbox:] ()
        6	0x00000001059afc10 in __23-[CBL_Replicator start]_block_invoke ()
        7	0x00000001059c002a in -[CBLBatcher processNow] ()
        8	0x00000001059c021b in -[CBLBatcher queueObjects:] ()
        9	0x00000001059c02e6 in -[CBLBatcher queueObject:] ()
        10	0x00000001059b0d89 in -[CBL_Replicator addToInbox:] ()
        11	0x000000010599d70b in -[CBL_Puller changeTrackerReceivedSequence:docID:revIDs:deleted:] ()
        12	0x00000001059b87b2 in __38-[CBLChangeTracker parseBytes:length:]_block_invoke ()
        13	0x000000010599964f in -[CBLChangeMatcher end] ()
        14	0x00000001059e376b in -[CBLJSONReader endArrayOrMap:] ()
        15	0x00000001059e4117 in parsed_end_map ()
        16	0x0000000105a78226 in yajl_do_parse ()
        17	0x0000000105a70089 in yajl_parse ()
        18	0x00000001059e30b4 in -[CBLJSONReader parseBytes:length:] ()
        19	0x00000001059b85a0 in -[CBLChangeTracker parseBytes:length:] ()
        20	0x0000000105a2e8b0 in -[CBLSocketChangeTracker readFromInput] ()
        21	0x0000000105a2f045 in -[CBLSocketChangeTracker stream:handleEvent:] ()
        22	0x00007fff90ae0bd4 in _signalEventSync ()
        23	0x00007fff90ae0b04 in _cfstream_solo_signalEventSync ()
        24	0x00007fff90ae09bf in _CFStreamSignalEvent ()
        25	0x00007fff94a6af99 in HTTPReadStream::streamEvent(unsigned long) ()
        26	0x00007fff90ae0bd4 in _signalEventSync ()
        27	0x00007fff90b1e2bd in _cfstream_shared_signalEventSync ()
        28	0x00007fff90aa1681 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ ()
        29	0x00007fff90a9380d in __CFRunLoopDoSources0 ()
        30	0x00007fff90a92e3f in __CFRunLoopRun ()
        31	0x00007fff90a92858 in CFRunLoopRunSpecific ()
        32	0x00007fff95121849 in -[NSRunLoop(NSRunLoop) runMode:beforeDate:] ()
        33	0x000000010599abaf in -[CBL_Server runServerThread] ()
        34	0x00007fff9511f90a in __NSThread__main__ ()
        35	0x00007fff94ec7268 in _pthread_body ()
        36	0x00007fff94ec71e5 in _pthread_start ()
        37	0x00007fff94ec541d in thread_start ()

These exceptions do seem to be caught, but they make me suspicious :-)

I'm of course available to provide more information as needed -- and fully prepared to accept the likely answer that I'm Doing It Wrong™ or in some other way being an idiot :-)

Thanks for your time!

**Comment by pasin** [comment]
Thanks for reporting this and providing test steps and code. I will look into this probably this afternoon.

**Comment by snej** [comment]
What version of CBL are you using?

The backtrace is confusing, especially `__56-[CBLDatabase(Replication) findMissingRevisions:status:]_block_invoke ()`. That method doesn't have a block in it, and in 1.0.x it doesn't have a `status:` parameter. (On the master branch it does, but it's been moved out of the CBLDatabase class entirely.)

The only thing that seems plausible to me is that you've built from the master branch but haven't updated your sources in a few months? If so please update [or go back to 1.0.4] and try again and see if this problem persists.

**Comment by snej** [comment]
Oh, I just noticed you said "Currently, I'm using the forestdb branch, commit dd20d33." That's from Feb 6. A lot of code has changed since then, and in particular that branch got merged into master. Could you please update to the current master branch?

**Comment by ndouglas** [comment]
Ah, I see -- I wasn't aware forestdb was merged into branch.  :blush:  I missed that and was waiting patiently for updates.

This issue (if it was a bug) isn't showing up for me in HEAD, so I guess once again I've managed to waste your time -- sorry about that.

**Comment by snej** [comment]
I [posted about the merge](https://groups.google.com/d/msgid/mobile-couchbase/4D602383-7822-41C3-AD76-ADD346F0ECDD%40couchbase.com?utm_medium=email&utm_source=footer) when it happened, but I know it's easy to miss emails, I do it too. :/

That method does still exist in basically the same form, it's just in the class CBL_ForestDBStorage now. But I've looked over it and can't figure out how it could be throwing that exception.
