### ISSUE TITLE
Cocoapod specs should support OS X

### ISSUE THREAD

**Issue by hiaw** [couchbase/couchbase-lite-ios#632]
Hi,

Couchbase Lite support OS X and there's a demo app from couchbaselabs showing it.

https://github.com/couchbaselabs/tunes-demo-mac

But the Cocoapods spec does not support OS X as a platform. I think "jessliu" should change that as she authors the pod spec. 

https://github.com/CocoaPods/Specs/blob/master/Specs/couchbase-lite-ios/1.0.3.1/couchbase-lite-ios.podspec.json

Thanks.

**Comment by snej** [comment]
Jessica Liu used to be our product manager and was named as the owner of the podspec, but she didn't write or maintain it. I can't remember the name of the guy who wrote it — if you search closed issues for "podspec" you should be able to find issues that he filed or was named in.

**Comment by davidquon** [comment]
> I found your email in the Couchbase lite github page and understand you're a contributor to the cocoa pods specs for CBL.
>
> Can you please add OS X support onto the cocoa pods specs? It's literally just one line of
> "osx": "10.8"

@hiaw - To follow up on the email you sent me I'm currently running CBL for iOS not OSX.  I'm not an expert on making a podspec work for both iOS and OSX.  Would you like to be added as a contributor for the `couchbase-lite-ios` podspec?  You should test that any changes made won't break the iOS side of the podspec.  Alternatively given the name of the current podspec you might want to consider making a `couchbase-lite-osx` podspec that just has the configuration for the OSX side.  You'll probably want to add @snej as the owner as well as anyone else at CBL that should have access as a contributor to the podspec.

Let me know if I can be of any further assistance.

**Comment by pasin** [comment]
@hiaw could you add me to the contributor list? I will be happy to help adding osx support and test.

**Comment by davidquon** [comment]
@pasin Did you want to add the OSX support to `couchbase-lite-ios`?  If so please email me the email address you want to use.  If not I think you can just follow CocoaPod's rules for creating a new spec.

**Comment by pasin** [comment]
@davidquon after checking, look like we don't have a zip package for the osx platform available yet (users currently need to built it themselves). I will check with @zgramana regarding this.

Anyway could you add me (pasin@couchbase.com) to the contributor list so I could help on any podspec issues in the future?

**Comment by davidquon** [comment]
> after checking, look like we don't have a zip package for the osx platform available yet (users currently need to built it themselves)

I was wondering about that.  Thanks for the update.

@pasin can you please register yourself with trunk and I can add you to the contributor list?  http://guides.cocoapods.org/terminal/commands.html#pod_trunk_register

**Comment by davidquon** [comment]
@pasin - TLDR;
```
$ pod trunk register eloy@example.com `Eloy Durán` --description=`Personal Laptop`
```
Let me know when you're registered and I'll add you to the contributor list.

**Comment by pasin** [comment]
Sorry for the delay. Registered.

**Comment by davidquon** [comment]
@pasin - Okay you should be added as an owner of the `couchbase-lite-ios`.  Let me know if there is anything else I can do to help.

**Comment by pasin** [comment]
@davidquon, thanks a lot!

**Comment by zgramana** [comment]
Will close once the OS X podspec is published.

**Comment by pasin** [comment]
The CBL OSX 1.1.0 podspec has been published. Please add the following line to your Podfile to use it.

```
pod 'couchbase-lite-osx', '~> 1.1'
```
