### ISSUE TITLE
Revision ID generation is missing the attachment digests.

### ISSUE THREAD

**Issue by deanelhard** [couchbase/couchbase-lite-ios#636]
The code in CBLDatabase+Insertion.m for generating the revision id claims to be basing it on the previous revision id, document JSON, and attachment digests, but never actually looks at the attachments.  The android version does include the attachments in the rev id generation (although it has a bug that it is missing the previous rev id).

**Comment by snej** [comment]
The attachments are already in the JSON as an `_attachments` object.

**Comment by deanelhard** [comment]
The different ways of doing this (iOS including them in the JSON and android hashing them separately) still means that the two clients will come up with different names for the same revision content.  Is this a concern, and if so, where should it be addressed?

**Comment by snej** [comment]
No, it's not a problem. It would be ideal if they were the same — it would eliminate some "false conflicts" where two clients make exactly the same change — but the source bases have diverged. (If we were going to fix one, we'd fix Android. It's still using an older scheme for storing attachments outside the JSON.)
