### ISSUE TITLE
CBLMultipartUploader assertion failed: "HTTP multipart upload body has indeterminate length"

### ISSUE THREAD

**Issue by nl** [couchbase/couchbase-lite-ios#640]
In master, complied from source. https://gist.github.com/nl/f7bbaee1916909220326

I think I may have ended up with a null-length or a nil attachment somewhere, but it probably shouldn't take down the entire app.

**Comment by snej** [comment]
```
'Assertion failed: HTTP multipart upload body has indeterminate length'
 
_AssertFailed + 393
-[CBLMultipartUploader start] + 0
-[CBL_Pusher uploadMultipartRevision:] + 1952
__27-[CBL_Pusher processInbox:]_block_invoke + 1331
__58-[CBL_Replicator sendAsyncRequest:path:body:onCompletion:]_block_invoke + 228
-[CBLRemoteRequest respondWithResult:error:] + 72
-[CBLRemoteJSONRequest connectionDidFinishLoading:] + 422
```

**Comment by snej** [comment]
@nl, what exact commit is this? There's been a very recent change to CBL_Pusher's multipart handling.

**Comment by nl** [comment]
0b19a4c355d0858a35c6ce82b90915ff78f2d988

**Comment by snej** [comment]
OK, that's later than 2fdf3e086e723ca28e15fbd0f05c39918920eb07 so it may be a regression caused by that. I'll investigate.

**Comment by nl** [comment]
I remember seeing a few "400 invalid attachment" and "400 bad_request" console logs a couple of days ago, too. Maybe those are related to this problem.
