### ISSUE TITLE
add CBLJSViewCompiler to the framework

### ISSUE THREAD

**Issue by jchris** [couchbase/couchbase-lite-ios#652]
We should just go ahead and make it trivial to add JS views by making [this code](https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CBLJSViewCompiler.h) part of the default package and easier to call.

**Comment by snej** [comment]
+1. It's not much code. There are three source files to add — 
* CBLJSViewCompiler.m
* CBLJSFunction.m
* CBLRegisterJSViewCompiler.m

**Comment by pasin** [comment]
@zgramana do we target this fixed in 1.1.0?
