### ISSUE TITLE
Can't have a comma inside map block: "Too many arguments provided to function-like macro invocation"

### ISSUE THREAD

**Issue by tar500** [couchbase/couchbase-lite-ios#656]
Let me show you some example:
```objective-c
[self.view setMapBlock:MAPBLOCK({
    ...
    NSArray *key = @[calendarId, date];
    ...
}) reduceBlock:nil version:@"1"];
```
This will result in "Too many arguments provided to function-like macro invocation" error.

Here is the link to the similar issue: http://stackoverflow.com/questions/9187614/how-do-i-have-a-comma-inside-braces-inside-a-macro-argument-when-parentheses-cau

**Comment by snej** [comment]
Not all commas pose a problem. Every map block has a comma inside it, as part of the `emit(key, value)` call. Generally it works fine. The only case where it's a problem is if you have a comma that _isn't inside parentheses_. This is a limitation of the C preprocessor; there isn't anything we can do about it.

The workaround is to put parens around the expression containing the comma. In your example, change the line in the `MAPBLOCK` macro to:
```objc
    NSArray *key = (@[calendarId, date]);
```
and it'll compile fine (I just tried it.)

**Comment by tar500** [comment]
Nice workaround, thanks @snej !
