### ISSUE TITLE
ForestDB: fullTextSearch emmits wrong values

### ISSUE THREAD

**Issue by razorblade446** [couchbase/couchbase-lite-ios#662]
Hi, i'm testing ForestDB engine, but having issues with fullTextSearch.

('master' branch, commit 4cf8324)

I'm emmitting with:

    emit(CBLTextKey(doc[@"title"]), doc[@"id_contact"]); // doc[@"title"] and doc[@"id_contact"] are Strings

But getting unexpected result:

    for(CBLFullTextQueryRow *filaRuta in rutasFichas.rows){
        // filaRuta.value gives me 
        //      [
        //          doc[@"title"],
        //          doc[@"id_contact"]
        //      ]
        // Instead of expected value:
        //      doc[@"id_contact"]
    }

Also query does not run if i dont define CBLLiveQuery.fullTextSearch (but don't know it this behavior is expected)

**Comment by snej** [comment]
Hm, with #620 fixed, the value should be correct. The unit test `-[ViewInternal_Tests test23_FullTextQuery]` does almost exactly what you're doing and gets the correct value. I've just looked through the code and don't see any problems.

Could you please download the [latest archived build](http://latestbuilds.hq.couchbase.com/couchbase-lite-ios/ios/0.0.0/0.0.0-380/couchbase-lite-ios-community_0.0.0-380.zip) and test with it?
