### ISSUE TITLE
Tag + Cocoapods?

### ISSUE THREAD

**Issue by lordkev** [couchbase/couchbase-lite-ios#668]
Any chance of getting a new tag and bump in the Cocoapods spec that includes the Xcode 6.3 build fixes already in master? 

Unfortunately I can't point Cocoapods at master as I'm using CBL as a dependency in a podspec for an internal pod.

**Comment by pasin** [comment]
Hello @lordkev, 

We plan to port an XCODE 6.3 build issue from master to 1.0.4 release branch and tag. Will that be helpful for you or Do you need to have a tag from of master branch? For the later case, I will need to check the team here if we would like to tag the current master as a beta release.

**Comment by pasin** [comment]
CBL 1.1.0 has been published to the cocoapods.org.
