### ISSUE TITLE
track library size and launch time across builds

### ISSUE THREAD

**Issue by jchris** [couchbase/couchbase-lite-ios#67]
Write a minimal test app we can keep up to date that has two versions, with and without Couchbase Lite, then we compare the build size. 

This app will be used to track the contribution of Couchbase Lite to the overall size of the app in a release build. It should test with and without CouchbaseLiteListener.

It will also test the launch time of the app with and without Couchbase Lite. So if it is possible to soft-bind Couchbase Lite somehow so that the UI's first load is the same with and without it, so that after the first UI paint (And Couchbase Lite is launched) we can time how long it took.

We can't just time before and after times on a Couchbase Lite launch because that leaves out the factor of loading the code into memory which wouldn't have happend on a build that doesn't have CBL linked.

**Comment by pasin** [comment]
CC: @sethrosetter
