### ISSUE TITLE
"_removed" properties received from SG cause errors pushing to another server

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#671]
If CBL used to have access to a document but loses access, SG will send it one more revision whose only property is `"_removed":true`, to let it know. The problem is that, if CBL pushes the same database to a _different_ server (SG or CouchDB or whatever) it will try to push that document, and the server will (correctly) reject the `_removed` property as illegal because it has a leading underscore.

Since this isn't a "real" revision at all, CBL shouldn't be pushing it. We need to filter it out.

**Comment by snej** [comment]
Marked the severity as "Major" because, if this happens, it stops the entire replication.

**Comment by pasin** [comment]
Currently _remove property is stored in the JSON doc. It's not efficient to do the filtering on the _removed property as we will need to always include the JSON body when querying for the rev changes. Should we introduce removed field in the revs table?

**Comment by snej** [comment]
Probably best to check for `_removed` after the doc's body has been loaded and it's about to be pushed; then just skip it.

**Comment by zgramana** [comment]
@pasin will schedule a meeting to discuss this with the other teams.

**Comment by pasin** [comment]
For some reasons, I couldn't make Sync Gateway to send _removed revisions. I think I don't understand how this actually works. Here is my test.

1. I prepared sync gateway config file with one user names user1 (GUEST is also disabled). I setup sync function to grant access or remove access based on a document property named 'grant'.  The config file is here: https://gist.github.com/pasin/ddc0cad171630874126d#file-config-json.

2. On client side, I have setup continuous push and pull replication. I setup the basic auth to both replicators. Then I created a document with grant = true. Waited for 5 seconds, I updated the document with grant = false. My test code is here:  https://gist.github.com/pasin/ddc0cad171630874126d#file-viewcontroller-m

The test result was no _removed property sent to client. 
- I checked isGone property of the document, and it returned false.
- I checked the actual json in the sqlite file, and there is no _removed revision. 
- I checked the client log and sync gateway log, and there is no indiction of sending or receiving _removed revision after removing the channel access.

Client log :
https://gist.github.com/pasin/ddc0cad171630874126d#file-client-log

Sync Gateway log:
https://gist.github.com/pasin/ddc0cad171630874126d#file-sync_gateway-log

@snej or @adamcfraser could you review my test and let me know what is wrong in my test?

**Comment by snej** [comment]
You're removing the user from the channel. There's a bug/limitation in SG that this doesn't trigger removal of documents (I don't remember the bug #.)

Instead, remove the _document_ from the channel. That does trigger an update.

**Comment by adamcfraser** [comment]
For the curious, that's SG bug https://github.com/couchbase/sync_gateway/issues/264.

**Comment by pasin** [comment]
I made change to the sync function by removing the document from the channel but I still didn't get the _removed revision. I'm using sync gateway from the master branch (https://github.com/couchbase/sync_gateway/commit/bfb402f6d4609929cf86593cb172e6994ac6f5b7). @adamcfraser is this perhaps sync gateway bug?

Sync Gateway Config:
https://gist.github.com/pasin/ddc0cad171630874126d#file-remove_doc_channel_config-json

Sync Gateway Log:
https://gist.github.com/pasin/ddc0cad171630874126d#file-remove_doc_channel_sync_gateway-log

Client Log:
https://gist.github.com/pasin/ddc0cad171630874126d#file-remove_doc_channel_config_client-log

**Comment by adamcfraser** [comment]
@pasin Based on your Sync Gateway log, it doesn't look to me like your user (user1) ever gets granted access to the 'note' channel - they only ever have the public `!` channel:

```
2015-06-17T11:20:52.673+07:00 Changes+: MultiChangesFeed: channels expand to channels.TimedSet{"!":0x1} ...   (to user1)
```

Try giving them access to the 'note' channel in the user definition in the config  - e.g. `"admin_channels":["note"]`.

**Comment by pasin** [comment]
I just reorganized and updated all gist links.

**Comment by pasin** [comment]
@adamcfraser I modified sync function and forgot to give the access to user1. Let me put it back to the sync function. Hope it solves the issue.

**Comment by adamcfraser** [comment]
If you're just trying to generate _removed entries, I really would just stick it in the config file.

As previously discussed, _removed entries are only generated when docs move out of channels, and not when users move in and out of channels.  So for a cleaner repro case, I'd just do an admin-level grant of the channel in the config.

**Comment by pasin** [comment]
After updating as @adamcfraser's suggested, sync gateway now sends the _removed revision to the changes feed.

```
{"results":[
{"seq":1,"id":"_user/user1","changes":[]}
,{"seq":3,"id":"-ie-Nu_mjnG1qzm5ZLYW_co","removed":["note"],"doc":{"_id":"-ie-Nu_mjnG1qzm5ZLYW_co","_removed":true,"_rev":"2-6de4ae0c4c6b97f5f81cf56440c52080"},"changes":[{"rev":"2-6de4ae0c4c6b97f5f81cf56440c52080"}]}
],
"last_seq":"3"}
```

However there is another issue on the client side that the revision id of the _removed revision is still the same as the client updates the document to trigger the revoke channel access event. Therefore, client doesn't download the new _removed revision.

As discussed with @adamcfraser, there is a proposed change to the sync gateway to generated a transient revision (new revision id) for the _removed revision (See comment in https://github.com/couchbase/sync_gateway/issues/264) so the issue above should be resolved by that.

**Comment by adamcfraser** [comment]
After reviewing with @pasin, it looks like this is a use case not covered by the solution discussed here:
https://github.com/couchbase/sync_gateway/issues/927#issuecomment-112604997

That solution assumes that the client doesn't already have the revision that's triggering the channel removal.  In the case that the client was the originator of the revision that's triggering the removal, it will just end up with a conflict on the client, where the non-removed revision is (incorrectly) the winning revision.  Plan to have a followup discussion, and will update https://github.com/couchbase/sync_gateway/issues/927 with the results.

**Comment by pasin** [comment]
Here are the updated sync gateway config and client code that could test _removed rev sent from sync gateway to client:
https://gist.github.com/pasin/ddc0cad171630874126d#file-3_1_viewcontroller-m
https://gist.github.com/pasin/ddc0cad171630874126d#file-3_2_config-json

**Comment by pasin** [comment]
I have tested pushing a _removed rev document to a new remote sync gateway. The result was that sync_gateway accepted the document without errors on both client and sync gateway side, BUT the stored document is empty as an example below:

```
{
  "_rev": "2-645e8e2936c1a1a12402079f0657906f",
  "_id": "doc1"
}
```

**Comment by snej** [comment]
Reopening this because the new replicator also needs a fix for this. If command line args `-TestNewReplicator YES` are added while testing, the unit test `test17_RemovedRevision` will fail.
