### ISSUE TITLE
Test performance improvement replicating docs with large revision trees

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-ios#677]
Test to detect perf regression https://github.com/couchbase/couchbase-lite-ios/commit/5b98b28308bc9b3f3d1f07adda34accb1de0dbc0

**Comment by pasin** [comment]
The test will be added to the performance test (worker bee) project.

**Comment by snej** [comment]
FYI, this wasn't a regression. The slow code path was in there from the beginning.

**Comment by snej** [comment]
Also, the "interesting" case is where the doc already has a lot of local revisions, and then a rev is added that also has a long revision history (that is, the history array passed to the insertion method is lengthy.) That causes the really slow O(n^2) behavior.
