### ISSUE TITLE
Make sure replaceDatabase handles both 1.0 and 1.1 databases correctly

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-ios#678]
As far as I can tell, there is no logic in the replaceDatabase method that distinguishes whether the source db is a 1.0.x style database or a 1.1+ style database.  There needs to be some discussion about this because all platforms should handle this in the same way so that databases generated on one platform can be preloaded into another.

**Comment by snej** [comment]
Pasin just checked in support for the old db layout. Please take a look at the current code and see you think the problem still exists.

**Comment by pasin** [comment]
I think we need to calling upgrading db if replacing 1.0 db after replacing operation is done.

**Comment by pasin** [comment]
Actually we need to upgrade the database before it's opened (after it's opened, the schema version could get updated).

**Comment by pasin** [comment]
I have a patch for release/1.1.0 branch. I will review and submit a PR.

**Comment by borrrden** [comment]
Looking good to me!  I'll start porting this to .NET.
