### ISSUE TITLE
Thread-safety issue in CBLReplication cookie methods

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#691]
The CBLReplication methods -setCookieNamed:... and deleteCookieNamed:... both reference the instance variable `_bg_replicator` directly, i.e. on the main thread. That violates the policy that ivars prefixed `_bg_` are only to be accessed on the background replicator thread.

There's a potential race condition where `_bg_replicator` is either set or nil'ed out while one of these cookie methods is running, specifically right after the test `if (_bg_replicator)`.

(I'm running into a sporadic failure of the `test10_ReplicationCookie` unit test. I don't think it's caused by this particular error, but I noticed it as soon as I started looking at the replicator cookie code.)

**Comment by snej** [comment]
Also, the `_pendingCookies` instance variable is modified on both the main and replicator threads without synchronization. Setting the variable's value isn't guaranteed to be an atomic operation, and worse, if the array is mutated on the main thread while being iterated on the background thread it could cause a crash.

**Comment by snej** [comment]
Ah, the unit test also has a race condition, which is why it sometimes fails. In this code:

```objc
    CBLReplication* repl = [db createPullReplication: remoteDbURL];
    [repl deleteCookieNamed: cookie2.name];
    ...
    [repl start];
    [self runReplication: repl expectedChangesCount: 0 expectedChangedCookies: @[cookie1, cookie3]];
```
since the CBLReplication configures the cookies in a background method triggered by -start, it's possible for it to do so _before_ the -runReplication: method gets a chance to register its observer method, so the observer won't see the changes.

**Comment by pasin** [comment]
The fixed has been merged.
