### ISSUE TITLE
Revise replaceDatabase signature and backward db support

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#695]
There are some changes in the CBLManager's -replaceDatabaseNamed method due to the new database layout (cblite2) in v1.2. However the new signature is not applicable for replacing the old database structure which the attachments folder is detached from the database file.

This ticket is opened to discuss about the right signature (or more than one signatures) for the -replaceDatabaseNamed method.

v1.1 and below
```
- (BOOL) replaceDatabaseNamed: (NSString*)databaseName
             withDatabaseFile: (NSString*)databasePath
              withAttachments: (NSString*)attachmentsPath
                        error: (NSError**)outError                  __attribute__((nonnull(1,2)));
```

v1.2
```Objective-C
- (BOOL) replaceDatabaseNamed: (NSString*)databaseName
              withDatabaseDir: (NSString*)databaseDir
                        error: (NSError**)outError;
```

**Comment by pasin** [comment]
@snej what is your comment on this? Should we have 2 replaceDatabaseNamed: methods?

**Comment by snej** [comment]
Add the new one, deprecate the old one I think. The implementation of the old method would update the database to 1.1 format, presumably...

**Comment by pasin** [comment]
I think even the old method, it will need to update the database to use 1.2 database schema and the new file layout (cblite2). Otherwise the CBLSQLiteStorage will need to support 2 file layouts which is too complicated.
