### ISSUE TITLE
ForestDB fails in 32-bit OS due to bug in get_memory_size fn

### ISSUE THREAD

**Issue by ryuzmukhametov** [couchbase/couchbase-lite-ios#700]
I tried launch Couchabse Lite with ForestDB data storage in iPad Retina Simulator and got FDB_RESULT_TOO_BIG_BUFFER_CACHE error. When I dive into the code I detect bug related to 32-bit architecture. In function "get_memory_size" from "get_memory_size.cc" file we can see the following code:
```c++
    int64_t size = 0; /* 64-bit */
    size_t len = sizeof( size );
    if ( sysctl( mib, 2, &size, &len, NULL, 0 ) == 0 ) {
        return (size_t)size;
    }
    return 0L; /* Failed? */
```
Because sizeof(size_t) == 4 in 32-bit iOS simulator with 4GB RAM this code returns 0 - when 2^32 casts to 32-bit integer it truncates to zero value.

**Comment by snej** [comment]
Thanks for finding this. That function is a pretty new addition to forestdb and it doesn't look like they tested it in a 32-bit environment. I'll file a bug and make sure we get the fix into 1.1 final.

**Comment by snej** [comment]
[Filed in Jira](https://issues.couchbase.com/browse/MB-15021).

**Comment by snej** [comment]
Rustam — does the same problem occur on a real 32-bit _device_? I'm thinking that the result of 2^32 is due to the host Mac having 4GB of RAM, whereas a real device wouldn't (yet) have that much.

**Comment by ryuzmukhametov** [comment]
I think so. When I test it using a real 32-bit device - as expected I don't get this exception. It appears that this problem is actual for host Mac having 4GB or greater (because 8GB (2^33) also casts to zero from int64 to int32)

**Comment by snej** [comment]
Thanks for testing. I'm downgrading from Showstopper, but I still want to get this fixed because I bet many developers will run into it and get stuck and come to us for help. And the fix is trivial.
