### ISSUE TITLE
CBLModel not working with namespaced Swift classes

### ISSUE THREAD

**Issue by marbetschar** [couchbase/couchbase-lite-ios#703]
Hi!

I'm trying to establish a many-to-one relationship between a Location and a Person Model. Both of them are subclasses of a generic "Model" class as follows:

    @objc class Model: CBLModel{
	func save() -> Bool{
		var error: NSError?
		super.save(&error)
		
		if error != nil{
			NSLog("Error saving bean: \(error)")
		}
		
		return error == nil
	}
	
	
	func delete() -> Bool{
		var error: NSError?
		super.deleteDocument(&error)
		
		if error != nil{
			println("Error deleting bean: \(error)")
		}
		
		return error == nil
	}
    }

The person looks like

    @objc class Person: Model{
	@NSManaged var firstName: NSString
	@NSManaged var lastName: NSString
	
	
	convenience init(){
		self.init(document: Connection.sharedInstance().database[NSUUID().UUIDString] as CBLDocument)
		self.type = _stdlib_getDemangledTypeName(self).componentsSeparatedByString(".").last!
	}
    }

And the Location

    @objc class Location: Model{
	@NSManaged var longitude: NSNumber
	@NSManaged var latitude: NSNumber
	@NSManaged var moment: NSDate
	@NSManaged var countrycode: NSString?
	@NSManaged var zip: NSString?
	@NSManaged var state: NSString?
	@NSManaged var city: NSString?
	@NSManaged var sublocality: NSString?
	@NSManaged var street: NSString?
	@NSManaged var person: Person?
	
	
	convenience init(){
		self.init(document: Connection.sharedInstance().database[NSUUID().UUIDString] as CBLDocument)
		self.type = _stdlib_getDemangledTypeName(self).componentsSeparatedByString(".").last!
	}
    }

Now I'm trying to display the data as follows in a UITableViewController's cellForRowAtIndexPath:

    let location = Location(forDocument: self.query.rows.rowAtIndex(UInt(indexPath.row)).document)
    cell.textLabel?.text = location.person.firstName			

Unfortunately `location.person`just points to the ID of the person document. The person document itself seems not to be loaded. That why trying the firstName crashes the app.

Any idea what's wrong here?? :(

**Comment by marbetschar** [comment]
It seems i got the error - but I can't see the reason why this is happening.
There seems to be a difference between the following two class definitions:

Does *NOT* work:

    @objc class Person: Model

Does work (if I change Location and Person to the following way of declaring):

    @objc(Person)
    class Person: Model

Any Idea what's different between the two...?! I thought the first one is just a short way of writing?

**Comment by snej** [comment]
I don't know what the difference is between those declarations, but I'm not a Swift expert.

It sounds like, when the first form is used, the result is that the Obj-C runtime metadata for the `Location.person` property doesn't indicate that its object class is `Person`. Then CBLModel doesn't realize it needs to resolve the JSON string value to a Person object, causing the error.

What version of CBL is this with? The 1.1 candidate build includes some recent fixes for Swift-based model classes that might or might not fix this issue.

**Comment by snej** [comment]
According to Apple's _Using Swift With Cocoa_ book:

>“When you use the `@objc(<#name#>)` attribute on a Swift class, the class is made available in Objective-C without any namespacing.”

Is your Person class declared within a module, i.e. in a framework/library target not an app target? If so, its real name is `ModuleName.Person`. I think that either the Obj-C runtime won't put such a class name into property metadata, or my code isn't reading it from the metadata properly.

Do you get any warning messages in the console when your app launches or when it first uses the `Location.person` property?

**Comment by pasin** [comment]
FYI, the CBLModel [sample code](http://developer.couchbase.com/mobile/develop/guides/couchbase-lite/native-api/model/index.html) also uses @object(Class Name).

Anyway I did try this, and without @objc(Person), there will be some warning messages printed by the MYDynamicObject when trying to assign a person object to a location object.

```
18:19:46.235| WARNING: MYDynamicObject: TestSwiftModel.Location.person has type @"Person" which is not a known class or protocol
18:19:46.236| WARNING: Dynamic property TestSwiftModel.Location.person has type '@"Person"' unsupported by TestSwiftModel.Location
```

From reading the code, I understand that MYDynamicObject couldn't dynamically resolve the set method of the person property as it couldn't get the property info. MYDynamicObject uses objective-c runtime class_getProperty() method to dynamically get the property info as below.

```Objective-C
// From MYDynamicObject.MYGetPropertyInfo():
objc_property_t property = class_getProperty(cls, name);
```

All swift classes are namespaced at least by their target name while all objective-c classes are in a global namespace. I believe this is the main reason why objective-c runtime couldn't find the property info of the person property. So I think using @objc(Person) is correct workaround.
