### ISSUE TITLE
Restructure iOS Performance tests

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/couchbase-lite-ios#704]
The current app for Performance testing (HeadlessBee/WorkerBee) needs an overhaul. The current KPI metrics are difficult to understand.  The current app also needs external software (iExplorer) to grab all the results. 
Need to restructure the current app or port them as Performance tests under XCtest framework.

**Comment by pasin** [comment]
Recently I simplified the iOS-WorkerBee. I think we can close this.
