### ISSUE TITLE
Code coverage for CBLite ios

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/couchbase-lite-ios#706]

**Comment by snej** [comment]
Xcode 7 has a kick-ass new code-coverage reporting feature. Unfortunately I can't get it to work at all in the released beta versions (the compiler hangs when building our source code with coverage enabled.) Have filed a bug report with Apple.

**Comment by snej** [comment]
Coverage works in Xcode 7 beta 3. But the unit tests need to be run for Mac OS, not iOS, because there's an Xcode bug that causes coverage not to be collected for code in static libraries, and the iOS target links CBL as a static library.

**Comment by snej** [comment]
Should we move this to mobile-test-kit?
If we decide to do this, it's pretty easy to generate the report from Xcode.

**Comment by sethrosetter** [comment]
Since automated unit testing is on build's plate, would this make more sense assigned to @michaelkwok?

**Comment by djpongh** [comment]
@pasin, this is working now, correct?

**Comment by pasin** [comment]
I have done some work on this and can close this now.
