### ISSUE TITLE
Please verify if iOS v1.1 view/query works with .NET v1.0.4 database

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-ios#708]
Android v1.1.0 is not compatible with .NET v1.0.4 views or maps table. So following unit test's commented out codes does not work. I am curious if iOS v1.1 view/query is compatible with .NET 1.0.4
https://github.com/couchbase/couchbase-lite-android/blob/master/src/androidTest/java/com/couchbase/lite/ManagerTest.java#L348-L390

**Comment by pasin** [comment]
I doubled check my unit test and the unit test already covers that view/query test for .NET 104. The unit test passes without any issues.

https://github.com/couchbase/couchbase-lite-android/blob/master/src/androidTest/java/com/couchbase/lite/ManagerTest.java#L348-L390

https://github.com/couchbase/couchbase-lite-android/blob/master/src/androidTest/java/com/couchbase/lite/ManagerTest.java#L348-L390

**Comment by pasin** [comment]
One thing that the iOS v1.1.0 CBLDatabaseUpgrade does is re-creating the database and moving document data over. Views and Map (no maps table anymore) data are not moved.
