### ISSUE TITLE
Potential database upgrade error

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#711]
In [this forum post](https://forums.couchbase.com/t/ios-couchbase-lite-via-cblincrementalstore/3824) a developer says they upgraded the CBL framework to the 1.1 candidate and their app can no longer open its database due to an invalid-ID error.

This error doesn't make sense for opening the database itself (the database name is valid, and it's an already-existing database) so I'm worried that it comes from within the upgrade process -- that somehow a document ID that was considered valid before is being rejected when it's copied into the new db.

We should try to get a copy of the database file from the developer so we can reproduce this.

```
CoreData: error: -addPersistentStoreWithType:CBLIncrementalStore configuration:(null) URL:file:///Users/florion/Library/Developer/CoreSimulator/Devices/BB6F7BB0-B1EF-4C7A-898A-61E1310B90B6/data/Containers/Data/Application/B005D3AE-DB85-4261-989F-96C6390500C8/Library/Application%20Support/myApp/database694.sqlite options:{
    NSInferMappingModelAutomaticallyOption = 1;
    NSMigratePersistentStoresAutomaticallyOption = 1;
} ... returned error Error Domain=CBLISErrorDomain Code=6 "Could not create database" UserInfo=0x786aa5a0 {NSUnderlyingError=0x786ab970 "400 Invalid database/document/revision ID", NSLocalizedDescription=Could not create database} with userInfo dictionary {
    NSLocalizedDescription = "Could not create database";
    NSUnderlyingError = "Error Domain=CBLHTTP Code=400 \"400 Invalid database/document/revision ID\" UserInfo=0x786ab120 {NSLocalizedFailureReason=Invalid database/document/revision ID, NSLocalizedDescription=400 Invalid database/document/revision ID}";
}
```

**Comment by snej** [comment]
(The developer's actual question is about Core Data support, but I don't think that's relevant to this particular issue since the error happens during opening the database and I don't think any IncrementalStore stuff has happened by that point. Right, @pasin ?)

**Comment by pasin** [comment]
That's correct. The error happened during the very first step of getting the CBLDatabase object.

```
self.database = [manager databaseNamed: databaseName error: &error];
    if (!self.database) {
        if (outError)
            *outError = CBLISError(CBLIncrementalStoreErrorCreatingDatabaseFailed,
                                   @"Could not create database", error);
        return NO;
    }
```

As the error status is kCBLStatusBadID (Invalid database/document/revision ID), I believe that it happened during the database upgrade process. I have tested migrating (but very simple test with a few docs with attachments) from v1.0.4 to 1.1.0. 

The user said that he is using CBL 1.0 before so it's also possible that the database is from any version from 1.0.0 to 1.0.4. I could look more into this tonight, and it's better if we could get the user's database.

**Comment by pasin** [comment]
As reported on the forum by the user that there is no real issues, I'm closing the issue.
