### ISSUE TITLE
ForestDB - error

### ISSUE THREAD

**Issue by SebastianBO** [couchbase/couchbase-lite-ios#713]
-[CBL_ForestDBStorage openAtPath:readOnly:manager:error:]: unrecognized selector sent to instance 0x7fe4dbd9dff0

Added -CBLStorageType ForestDB in the schema, obviously imported the lib. When opening a new fresh (and resetted device) database i get the above error.

**Comment by snej** [comment]
That method exists but it had a slightly different name before Apr 27 (commit 087c0e8a948c). I think you're linking against an obsolete ForestDB-storage library.

**Comment by SebastianBO** [comment]
But the library was built from the current source code? https://issues.couchbase.com/browse/CBL-32 is the wrong one then i guess..any tutorial to how we will get the right version? :)

**Comment by snej** [comment]
Ah, that explains it. Don't build it from the `master` branch. Use the `release/1.1` branch so you get a binary that's compatible with the release. (There are some internal API differences between the two branches.)

**Comment by SebastianBO** [comment]
Nice, got it working :+1:

**Comment by snej** [comment]
Great! And the final 1.1 release, with the ForestDB lib included, should be out Wednesday.
