### ISSUE TITLE
Error re-adding a document after it's been purged

### ISSUE THREAD

**Issue by evankyle** [couchbase/couchbase-lite-ios#714]
couchbase-lite-ios
Branch: release/1.1.0  commit 25f3967

Sync gateway
Branch: master commit 5b15afb

Setup sync gateway with:
A document test-95 which is assigned channel X by sync-func.
A different document needs to grant X channel access to user.

iOS App
New database.
Start replication both directions.
Allow to pull changes and log all docs in db including deleted.
test-95 shows in log.
purge all docs in channel X.
log and see test-95 is gone from db.

Sync-Gateway
Update so user no-longer has access to channel X.

IOS App
pull and log all docs shows no test-95 in db correctly.

Sync-Gateway
Update so user is granted access to channel X again.

iOS App
Pull results in app trying to pull test-95 document correctly and gets a 200 from SG, but it fails to write see log.  The expected result would be to write the missing document into the database.

21:21:55.445‖ SyncVerbose: CBL_Puller[http://10.254.0.158:4984/dev/] inserting test-95 ["1-1ad5b9f09f4b75a46c7b1507f5102ebc"]
2015-05-18 21:21:55.445 App[12935:13535541] <CBL_FMDatabase: 0x7a7ab370> executeUpdate: SAVEPOINT cbl_2
21:21:55.446‖ CBLDatabase: Begin transaction (level 2)...
2015-05-18 21:21:55.445 App[12935:13535541] <CBL_FMDatabase: 0x7a7ab370> executeUpdate: INSERT OR IGNORE INTO docs (docid) VALUES (?)
2015-05-18 21:21:55.445 App[12935:13535541] obj: test-95
21:21:55.446‖ CBLDatabase: Abort transaction (level 2)
2015-05-18 21:21:55.446 App[12935:13535541] <CBL_FMDatabase: 0x7a7ab370> executeUpdate: ROLLBACK TO cbl_2
2015-05-18 21:21:55.446 App[12935:13535541] <CBL_FMDatabase: 0x7a7ab370> executeUpdate: RELEASE cbl_2
21:21:55.446‖ WARNING: CBL_Puller[http://10.254.0.158:4984/dev/] failed to write {test-95 #1-1ad5b9f09f4b75a46c7b1507f5102ebc}: status=590
21:21:55.447‖ Sync: CBL_Puller[http://10.254.0.158:4984/dev/] Progress: set error = 500 Database error!

**Comment by evankyle** [comment]
This is an intermittent issue, and I incorrectly closed this ticket. After the database is in a state of error other then a new database file, the only way I have found to get the document to sync is by removing the record in the docs table using sqlite3 cli tool, running "delete from docs where docid = "test-95"; After this the write does not fail.  I was under the impression the purge made it as if the document was completely forgotten but it is leaving the document around in the docs table.

**Comment by snej** [comment]
Purging removes revisions, but not the row in the `docs` table (which is simply a docID-to-row-id mapping.)  Removing the `docs` row would be harder because CBLDatabase keeps an in-memory cache  of those mappings, and there can be multiple CBLDatabase instances for a db file. ("There are only two hard problems in computer science: naming things and cache invalidation.")

Looks like the bug is that if the `INSERT OR IGNORE INTO docs` statement (CBL_SQLiteStorage.m:662) doesn't cause any rows to be added, it's treated as an error, whereas it should be considered a success; although it'll need to then call `_getDocNumericID:` to find the existing row ID.

**Comment by snej** [comment]
Should be easy to reproduce this in a unit test by simply creating a document, purging it, then creating it again.

**Comment by evankyle** [comment]
I was just trying to update the purgeDocument test.. First I had to get tests to run and the wiki is a little out of date for that ;)  My first try at a test was to do what you suggest, but it passed with flying colors. I was wondering if maybe if my test was not really testing what I think it is do to caching. I will post the test in a moment.

**Comment by evankyle** [comment]
The test below is passing :(

```objective-c
- (void) test10_PurgeDocument {
  
    NSString* docId = @"purge-test-doc";
    NSDictionary* properties = @{@"testName": @"testPurgeDocument", @"_id":docId};
  
    CBLDocument* doc = [self createDocumentWithProperties: properties];
    Assert(doc);
    AssertEqual(doc.documentID, docId);
  
    CBLDocument* redoc = [db existingDocumentWithID:docId];
    Assert(redoc);
    AssertEqual(redoc.documentID, docId);
    
    NSError* error;
    Assert([redoc purgeDocument: &error]);
    
    CBLDocument* docAfterPurge = [db existingDocumentWithID:docId];
    Assert(!docAfterPurge);
  
    docAfterPurge = [self createDocumentWithProperties: properties];
    Assert(docAfterPurge);
    AssertEqual(docAfterPurge.documentID, docId);
 
    CBLDocument* redocAfterPurge = [db existingDocumentWithID:docId];
    Assert(redocAfterPurge);
    AssertEqual(redocAfterPurge.documentID, docId);
  
}
```

**Comment by snej** [comment]
Thanks for checking! The bug may be specific to adding an already-existing revision, which is what the puller does, but there's no public API to do it directly.

(BTW, thanks for pointing out that the unit-test documentation is wrong. I've [updated it now](https://github.com/couchbase/couchbase-lite-ios/wiki/Running-Tests).)

**Comment by evankyle** [comment]
#721 pull request to fix.
