### ISSUE TITLE
[ForestDB] Old emitted k/v pair unexpectedly missing

### ISSUE THREAD

**Issue by joshblour** [couchbase/couchbase-lite-ios#716]
I keep seeing the following message in my log:
WARNING: Old emitted k/v pair unexpectedly missing

I'm using 1.1 (built from master at commit 9d0609600764) with ForestDB as the storageType

**Comment by snej** [comment]
That's in the indexing code we wrap around ForestDB (Index.cc:139.) Are you seeing any incorrect query results?

**Comment by joshblour** [comment]
I haven't seen this issue in a while. Going to close for now and reopen if it crops up again.
