### ISSUE TITLE
CBLListener.readOnly=YES prevents clients from storing checkpoints

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#726]
If an app with a CBLListener sets its `readOnly` property to YES (to prevent clients from modifying its databases), it has the unwanted side effect that clients' pull replicators can't store checkpoints, because the request to PUT the `_local` doc gets rejected with a 403. This means that every replication has to start over from the beginning, which hurts performance.

(The same thing happens when replicating with a CouchDB/Cloudant server without write access.)

Options:

* Make the listener allow PUTs to `_local` docs even in readOnly mode
* Make CBLReplicator more graceful about an inability to store a remote checkpoint, i.e. remember the fact and don't require the remote checkpoint to exist the next time.

**Comment by snej** [comment]
Another option:

* Give the app finer grained control over remote access to docs, allowing the peer to update `_local` docs but not any regular docs.

**Comment by pasin** [comment]
@snej does the CBLSyncListener support readOnly mode yet? I tried to follow the code but I couldn't find where that got implemented.

**Comment by snej** [comment]
Oops, it doesn't. Just filed #838 to remind myself.
