### ISSUE TITLE
Checkpoint ID shared by distinct pull replications

### ISSUE THREAD

**Issue by nl** [couchbase/couchbase-lite-ios#728]
I create a pull replication (`CBLReplication`) on a single database (`CBLDatabase`), and ask it to fetch a channel from a remote Sync Gateway (`replication.channels = @[ @"A" ]`). It fetches the documents from sequence 0 to sequence N, and stores the last sequence ID (N) under a hash that matches this replication's DNA. The replication stops.

A minute later, I create a pull replication on that same database (and same remote URL), and ask it to fetch another set of channels (`replication.channels = @[ @"A", @"B" ]`).

Expected behavior: the checkpoint ID for this new replication is different from the first replication.
Observed behavior: the checkpoint IDs are identical
Bug: the replication reuses the 'since' parameter from the previous channel-A pull, and fails to get all documents in channel B whose sequence ID are less than N.

Some logs right before calling `-start` on replications:
``
remoteCheckpointDocID = 4f1d55a06f4707736e263b2df7d55e533bd91ff5 | filterParameters = { channels = "a"; }
``

And later:
``
remoteCheckpointDocID = 4f1d55a06f4707736e263b2df7d55e533bd91ff5 | filterParameters = { channels = "a,b"; }
``

If I use the `reset` option in all my replications, which forces the replication to use `since=0`, the channel-B-only seqID-less-than-N documents finally appear.

Am I overlooking something? Or is this a major issue?

**Comment by snej** [comment]
Hm, that shouldn't be happening. -[CBLReplication setChannels:] sets the underlying filter and filterParams properties, and -[CBLReplicator remoteCheckpointDocIDForLocalUUID:] takes those into account when generating the checkpoint ID.

**Comment by snej** [comment]
…or maybe you've found a SHA-1 hash collision, in which case you'll be famous :)

**Comment by nl** [comment]
As far as I can tell, by the time `-[CBLReplicator remoteCheckpointDocIDForLocalUUID:]` gets called, _filterName and _filterParameters are both null.

**Comment by nl** [comment]
Here's the code creating the replication:
``
		CBLReplication *repl = [self.database createPullReplication:remoteURL];
		repl.channels = self.channels;
``

**Comment by nl** [comment]
NB: `setChannels:` is writing self.filter and self.filterParams whereas `remoteCheckpointDocIDForLocalUUID:` is reading _filterName and _filterParameters

**Comment by snej** [comment]
filterName and filterParameters are set immediately after the CBLReplication is instantiated, at CBLManager.m:781. That's well before CBLReplication gets around to looking at checkpoints.

**Comment by nl** [comment]
The replicator is asking for the remoteCheckpointDocID way before the filter can be set, at CBL_Replicator:123.

``
        _cookieStorage = [[CBLCookieStorage alloc] initWithDB: db
                                                   storageKey: self.remoteCheckpointDocID];
``

**Comment by snej** [comment]
Ouch! Good call. I didn't notice this was causing the checkpoint ID to get determined during the initializer. That's a fairly recent regression, from the cookie overhaul in February. I think we still have a chance to fix it for 1.1.

**Comment by nl** [comment]
Yay, great news!

**Comment by zgramana** [comment]
Re-opened to ensure that we add appropriate test coverage to catch future regressions.

**Comment by snej** [comment]
The patch includes a unit test that fails without the fix.

**Comment by pasin** [comment]
Closed as patch already includes a unit test.

**Comment by zgramana** [comment]
I saw the unit test, but this needs a functional test added to cblite-tests.

**Comment by zgramana** [comment]
@ashvindersingh, can you take a look at this?

**Comment by ashvindersingh** [comment]
Looked into this and also discussed with @pasin. The remoteCheckpointDocID method of CBL_replicator object is not exposed as a REST api and hence we can't add the equivalent test in cblite-tests repo.

**Comment by zgramana** [comment]
Cool. I think the unit tests are enough.
