### ISSUE TITLE
Listener doesn't return 416 for unsatisfiable Range: header

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#74]
The 3rd-party CocoaHTTPServer framework doesn't quite handle HTTP range requests properly. If a range isn't satisfiable, it just ignores the Range: header (and sends back the whole body with a 200 status) instead of returning a 416 status.

This causes a failure in a CouchDB unit test -- attachment_ranges.js:146

```
$ ./bin/couchdb-harness -p 59840 attachment_ranges
1..1
not ok 1 attachment_ranges
Reason: expected '416', got '200'
Trace back (most recent call first):
    
  46: /Couchbase/couchdb-harness/util/cli_runner.js
      T(false,"expected '416', got '200'","fetch 5-3")
 321: /Couchbase/couchdb-harness/script/couch_test_runner.js
      TEquals(416,200,"fetch 5-3")
 146: /Couchbase/couchdb-harness/script/test/attachment_ranges.js
      ()
  53: /Couchbase/couchdb-harness/util/cli_runner.js
      runTestConsole(1,"attachment_ranges",(function (debug) {var db = new C
  72: /Couchbase/couchdb-harness/util/cli_runner.js
      runAllTestsConsole()
  85: /Couchbase/couchdb-harness/util/cli_runner.js
      
Test failures: 1
```

**Comment by pasin** [comment]
Confirm that CocoaHttpServer ignores Range requests if the input range is invalid. Per chatting with @snej, this is very low priority and has very less severity at this point. No fix as least now.

**Comment by pasin** [comment]
In CBLRouter, there is a property called processRanges. The property is set to NO when the CBLRouter is created to allow CocoaHttpServer to process ranges request. @snej Is there a reason not to use CBLRouter's processRanges?

**Comment by snej** [comment]
I think because CocoaHTTPServer automatically handles the range parsing, so if we did it too we'd return the wrong results (i.e. a subrange of a subrange). But it's been a long time since I looked at that code so I might be wrong.

**Comment by pasin** [comment]
I have submitted a ticket https://github.com/robbiehanson/CocoaHTTPServer/issues/142.

**Comment by snej** [comment]
We have our own fork of CocoaHTTPServer and I've just been making changes/fixes in that.

**Comment by pasin** [comment]
Thanks Jens. I will make changes in that repo.
