### ISSUE TITLE
CBLIncrementalStore saves NSDate using GMT time zone 

### ISSUE THREAD

**Issue by paolonl** [couchbase/couchbase-lite-ios#743]
When creating JSON representation of NSDate objects, CBLincrementalStore invokes the method `+JSONObjectWithDate:` of `CBLJSON` class. This in turn, invokes `+JSONObjectWithDate:timeZone:` passing `[NSTimeZone timeZoneForSecondsFromGMT:0]` as `NSTimeZone` parameter causing wrong values being stored in the database.

I am in central Europe time zone and when trying for example to store an NSDate like this  `5/29/2015, 12:00:00 AM GMT+2:00 DST` (i.e. `28 May 2015 22:00:00 GMT`), the date is saved as string `2015-05-28T22:00:00.000Z`. When reading this value in my time zone, I get a wrong day. 

Instead of using GMT as default, CBLIncrementalStore should use `[NSTimeZone localTimeZone]` to match the time zone of the app

**Comment by snej** [comment]
NSDate itself has no notion of time-zone; it simply represents a moment in time. Thus it doesn't matter what time zone is used when writing it to a string, as long as the time-zone is provided in the string. The convention is to use GMT when the time zone is unknown or doesn't matter.

I'm not sure what you mean by "When reading this value in my time zone, I get a wrong day". Can you give more detail? The example string you gave above is correct. When parsing that string you'll get an NSDate equivalent to the one you originally stored. To determine what calendar day that date corresponds to, you'll need to use NSDateFormatter, which will interpret that date according to its timeZone property, which I believe defaults to your local time zone.

**Comment by paolonl** [comment]
The problem was on my side. The fetch request used to read the data was comparing dates using their ISO8601 representations. And in my `NSDateFormatter` I forgot to set the time zone to GMT. Which is the default zone couchbase uses.
