### ISSUE TITLE
Best practice for NSManagedObjectContext merge policy ?

### ISSUE THREAD

**Issue by cflorion** [couchbase/couchbase-lite-ios#747]
In your opinion, what should we use as a merge policy when setting up NSManagedObjectContext ?

- NSErrorMergePolicy
- NSMergeByPropertyStoreTrumpMergePolicy
- NSMergeByPropertyObjectTrumpMergePolicy

For example, Ensembles (https://github.com/drewmccormack/ensembles) uses the last one. I'm not sure I have all the informations about how Couchbase-lite works to make that decision.

What do you think ? :)
Thanks!

**Comment by snej** [comment]
Hi, this issue tracker is for reporting bugs and feature requests. Please ask questions on the Google group or the web forum.

**Comment by cflorion** [comment]
Sorry. Thanks
