### ISSUE TITLE
CBL 1.1 Mac: CBLQueryRow.document is null

### ISSUE THREAD

**Issue by mdfw** [couchbase/couchbase-lite-ios#755]
Just updated from (I think) beta 3 of 1.0.0 on to 1.1 Mac (built it myself from commit: 7949e8d59b9b30f7711be47a121dfbda9c82f2a8 downloaded today).

I have code that was working fine before that's no longer working.

`CBLQueryRow.document` is always empty, even if `documentID` and `documentProperties` (via `CBLQuery.prefetch = YES`) are valid. Expected behavior: document has the `CBLDocument` associated with `documentID`.

I have worked around this by adding a line that loads the document with the documentID from the database.

Steps to reproduce:
Create a `CBLQuery` (I'm using allDocs)
Enumerate and try to get `row.document`. It's always nil for me.

I haven't tried to dig deeply into the why, but I did notice that `CBLDocument loadCurrentRevisionFrom:` has changed significantly from 1.0.0.

**Comment by snej** [comment]
Yikes! Could you come up with something like a test case? Ideally you could add an actual XCTest test method to Database_Tests.m, but a standalone snippet that reproduces the problem is fine too.

The existing -[Database_Tests test12_AllDocuments] does basically what you're saying — runs an all-docs query and asserts that each row's .document property is non-nil. Is there something different about your query?

**Comment by mdfw** [comment]
I'll see what I can come up with. This is a pretty basic CBL implementation - it's the editor for some config information for another app (similar to what Jim was talking about at CouchConnect yesterday).  The only difference I see between what I'm doing and -[Database_Tests test12_AllDocuments] is I'm doing it as part of a livequery. Let me see if I can get a reproducible test case outside my app.

**Comment by mdfw** [comment]
Definitely seems like something with CBLLiveQuery. I'm not confident enough to write an XCTest, but here's a snippet that fails in my app (doc is always empty), where the test in test12_AllDocuments passes against the same database:

    CBLQuery *allDocsQuery = [db createAllDocumentsQuery];
    CBLLiveQuery  *allDocsQueryLive = [allDocsQuery asLiveQuery];
    [allDocsQueryLive start];
    BOOL __unused finished = [allDocsQueryLive waitForRows];
    CBLQueryEnumerator* rows = allDocsQueryLive.rows;
    NSLog(@"rows: %@, count: %lu", rows, rows.count);
    for (CBLQueryRow* row in rows) {
        CBLDocument* doc = row.document;
        NSLog(@"doc: %@", doc);
    }

I have not yet tried to spin up an entire test app, let me know if you want that.

**Comment by snej** [comment]
Thanks for the snippet — I pasted it into a unit test and it fails, demonstrating the bug.

The bug is with all-docs queries that are run asynchronously (including LiveQueries.) The QueryRow doesn't get hooked up to a CBLDatabase instance so it can't load a document. I've got a fix.

**Comment by snej** [comment]
At this point it may be too late to put this fix into 1.1. We may have to release-note it. For future reference, the workaround is to use the .documentID property instead, so instead of `row.document` use `[db documentWithID: row.documentID]`.

**Comment by mdfw** [comment]
Thanks Jens. I'll update again soon and see how things go.

**Comment by snej** [comment]
OK! At this point the master branch (which I committed the fix to) is really close to 1.1. It looks like there are just a few recent 1.1 fixes that haven't been merged into master yet. If you want to play it safe, you could check out the `release/1.1` branch and cherry-pick my fix onto it.
