### ISSUE TITLE
CBLIS query with boolean value returns 0 result

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#756]
Reported by https://github.com/couchbase/couchbase-lite-ios/pull/751.

**Comment by pasin** [comment]
CBLIS stores boolean value as 0 or 1 (CoreData boolean value) instead of true or false. The fix would be converting the value from 0 or 1 to NSNumber with the correct boolean value. Users will then need to update their documents to have correct boolean values otherwise they would need to query by using the predicate like 'checked == YES or checked == 1'.

**Comment by snej** [comment]
Storing booleans as the NSNumbers 0 and 1, instead of NO and YES, seems wrong. Is it a bug in the CBLIS code, or is this something CoreData does?

(Is this being caused by the problem of distinguishing NSNumbers 0/1 from NO/YES? I.e. CoreData tells us to store a YES value, but it's an NSNumber and we think it's a 1? If so, I know the workaround; see CBJSONEncoder.m, lines 178-185.)

**Comment by mastohhh** [comment]
Each of these tests fails :

    fetchRequest.predicate = [NSPredicate predicateWithFormat:@"check == YES"];
    fetchRequest.predicate = [NSPredicate predicateWithFormat:@"check == NO"];
    fetchRequest.predicate = [NSPredicate predicateWithFormat:@"check == 1"];
    fetchRequest.predicate = [NSPredicate predicateWithFormat:@"check == 0"];
    fetchRequest.predicate = [NSPredicate predicateWithFormat:@"check == %@", @YES];
    fetchRequest.predicate = [NSPredicate predicateWithFormat:@"check == %@", @NO];
    fetchRequest.predicate = [NSPredicate predicateWithFormat:@"check == %@", @(1)];
    fetchRequest.predicate = [NSPredicate predicateWithFormat:@"check == %@", @(0)];
    fetchRequest.predicate = [NSPredicate predicateWithFormat:@"check == %@", @"1"];
    fetchRequest.predicate = [NSPredicate predicateWithFormat:@"check == %@", @"0"];
    fetchRequest.predicate = [NSPredicate predicateWithFormat:@"check == %c", "1"];
    fetchRequest.predicate = [NSPredicate predicateWithFormat:@"check == %c", "0"];

To avoid this problem, I fetch all objects and then I filter the array of NSManagedObjects.

Problems : 

- performance
- unusable with NSFetchedResultsController, indexPaths are false.

**Comment by pasin** [comment]
The boolean value from the CoreData is NSNumber with char type ('1' or '0') and CBLIncrementalStore doesn't convert that to the correct JSON boolean value.

```ObjectiveC
case NSBooleanAttributeType:
        result = CBLISIsNull(value) ? @(NO) : value;
        break;
```

@mastohhh When I change your unit test PR with below, the unit test pass but that's not what it should be anyway.
```
 fetchRequest.predicate = [NSPredicate predicateWithFormat:@"check == 1"];
 fetchRequest.predicate = [NSPredicate predicateWithFormat:@"check == 0"];
```

I plan to correct the value saved in CBL database but currently I don't have an efficient way to correct the existing data.

**Comment by pasin** [comment]
@mastohhh I have fixed the issue. The boolean value is now stored as the JSON boolean value instead of number value from now on. 

I would be ideal if you could reset your data, otherwise please set customProperty kCBLISCustomPropertyQueryBooleanWithNumber with value = YES to the CBLIS store as below:

```Objective-C
[store setCustomProperties:@{kCBLISCustomPropertyQueryBooleanWithNumber: @(YES)}];
```

Let me know if you have any questions.
