### ISSUE TITLE
Problems with conflictHandler in CBLIncementalStore

### ISSUE THREAD

**Issue by mastohhh** [couchbase/couchbase-lite-ios#757]
I tried to reproduce this error in a UnitTest but I didn’t succeed. So I’ll try to explain it here.

First of all, when a conflict occurs, the `conflictingRevisions` array is empty. So there’s an exception when we try to find the `winning` revision with `conflictingRevisions[0]`

```objective-c
- (CBLISConflictHandler) defaultConflictHandler {
    CBLISConflictHandler handler = ^(NSArray* conflictingRevisions) {
        // merges changes by
        // - taking the winning revision
        // - adding missing values from other revisions (starting with biggest version)
        CBLRevision* winning = conflictingRevisions[0];
            …
        }
    };
    return handler;
}
```

The `defaultConflictHandler` is called by this method :

```objective-c
- (void) resolveConflicts: (CBLQueryEnumerator*)enumerator {
    // Resolve conflicts
    for (CBLQueryRow* row in enumerator) {
        if ([kCBLISMetadataDocumentID isEqual: row.documentID]) // For v1.0.4 and below.
            continue;
        if (self.conflictHandler) {
            self.conflictHandler(row.conflictingRevisions);
        }
    }
}
```

But `row.conflictingRevisions` **always returns an empty array**

So I tried this	:

```objective-c
- (void) resolveConflicts: (CBLQueryEnumerator*)enumerator {
    // Resolve conflicts
    for (CBLQueryRow* row in enumerator) {
        if ([kCBLISMetadataDocumentID isEqual: row.documentID]) // For v1.0.4 and below.
            continue;
        if (self.conflictHandler) {
            CBLDocument* doc = [_database documentWithID: row.sourceDocumentID];

            self.conflictHandler([doc getConflictingRevisions:NULL]);
        }
    }
}
```

Now I have `CBLRevision`s in my array.

At this point I don’t know if I did well, but `defaultConflictHandler` handles something. But the problem is : it handles everything ! 

When `defaultConflictHandler` always create the new revision :

```objective-c
CBLUnsavedRevision* newRevision = [winning.document newRevision];
[newRevision setProperties: properties];

NSError* error;
[newRevision save: &error];
```

This produce a loop that never ends.

That’s why I add a test in this method with `BOOL changed = NO` to create a revision only if needed.

```objective-c
- (CBLISConflictHandler) defaultConflictHandler {
    CBLISConflictHandler handler = ^(NSArray* conflictingRevisions) {
        // merges changes by
        // - taking the winning revision
        // - adding missing values from other revisions (starting with biggest version)
        CBLRevision* winning = conflictingRevisions[0];
        NSMutableDictionary* properties = [winning.properties mutableCopy];
        
        NSRange otherRevisionsRange = NSMakeRange(1, conflictingRevisions.count - 1);
        NSArray* otherRevisions = [conflictingRevisions subarrayWithRange: otherRevisionsRange];
        
        NSArray* desc = @[[NSSortDescriptor sortDescriptorWithKey: @« revisionID »
                                                        ascending: NO]];
        NSArray* sortedRevisions = [otherRevisions sortedArrayUsingDescriptors: desc];
         
        // this solution merges missing keys from other conflicting revisions to not loose any values
        BOOL changed = NO;

        for (CBLRevision* rev in sortedRevisions) {
            for (NSString* key in rev.properties) {
                if ([key hasPrefix: @« _ »]) continue;
                
                if (![properties objectForKey:key]) {
                    [properties setObject:[rev propertyForKey: key] forKey: key];
                    changed = YES;
                }
            }
        }
        
        // TODO: Attachments

        if (changed) {
            CBLUnsavedRevision* newRevision = [winning.document newRevision];
            [newRevision setProperties: properties];

            NSError* error;
            [newRevision save: &error];
        }
    };
    return handler;
}
```

As I can’t reproduce this in a UnitTest, and this bug occurs in my project with your compiled framework, I didn’t know why `conflictingRevisions` array was empty.

Last thing, it’s a question :

Why do you run the query again `CBLQueryEnumerator* enumerator = [query run: &error]` before calling ` [self resolveConflicts: enumerator]` :

```objective-c
- (void) observeValueForKeyPath: (NSString*)keyPath ofObject: (id)object
                         change: (NSDictionary*)change context: (void*)context {
    if ([@« rows » isEqualToString: keyPath]) {
        CBLLiveQuery* query = object;
        
    			NSError* error;
        CBLQueryEnumerator* enumerator = [query run: &error];
        
        if (enumerator.count == 0) return;
        
        [self resolveConflicts: enumerator];
    }
}
```

while the `query` object has already new rows ?

```objective-c
- (void) observeValueForKeyPath: (NSString*)keyPath ofObject: (id)object
                         change: (NSDictionary*)change context: (void*)context {
    if ([@« rows » isEqualToString: keyPath]) {
        CBLLiveQuery* query = object;
        
        CBLQueryEnumerator* enumerator = query.rows;
        
        if (enumerator.count == 0) return;
        
        [self resolveConflicts: enumerator];
    }
}
```

**Comment by pasin** [comment]
> But row.conflictingRevisions always returns an empty array

I don't know the reason yet. I will need to debug this.

> Why do you run the query again CBLQueryEnumerator* enumerator = [query run: &error] before calling [self resolveConflicts: enumerator]

I don't think we need to run the query again. I will fix that.

**Comment by pasin** [comment]
@mastohhh, I added a unit test to check if I could get the conflict revisions, and I could get all conflict revs as expected. Could you explain more about your scenario that the conflict revisions array is empty? 

Also just want to confirm with you that you are using CBLIS from the master branch?

> That’s why I add a test in this method with BOOL changed = NO to create a revision only if needed.

I think this is a good idea. I plan to add this to the CBLIS as well.

**Comment by mastohhh** [comment]
As I said, I really wanted to reproduce it in a unitTest.

I used the master branch, but it was around May 15th.

I'll try again, but I remember the `conflictingRevisions`never worked.

Instead of calling this method, I copy paste his implementation and it worked.

I'll try again with actual master and I'll tell you.

**Comment by pasin** [comment]
I'm thinking that the issue that you are seeing might be related to https://github.com/couchbase/couchbase-lite-ios/issues/755 that @snej fixed last week.

**Comment by mastohhh** [comment]
You're right, it's fixed now ! Thanks

**Comment by pasin** [comment]
I'm glad to hear that.
