### ISSUE TITLE
Assertion Failed: Can't run base configuration

### ISSUE THREAD

**Issue by SteffeyDev** [couchbase/couchbase-lite-ios#760]
I have only modified one line of code in the CBLUITableSource.h file, and when I try to run my project with this framework in an app that was working fine with the publicly distributed framework, I get the following errors:

<code>
2015-06-07 14:09:15.357 X[1130:280041] WARNING: Upgrade skipped: Database upgrading class is not present.
2015-06-07 14:09:15.363 X[1130:280041] *** ASSERTION FAILED: CBLManager.storageType is 'SQLite' but no CBL_SQLiteStorage class found
2015-06-07 14:09:15.363 X[1130:280041] *** Assertion failure in -[CBLDatabase(Internal) open:](), /Users/petersteffey/Documents/couchbase-lite-ios/Source/CBLDatabase+Internal.m:160
2015-06-07 14:09:15.364 X[1130:280041] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Assertion failed: CBLManager.storageType is 'SQLite' but no CBL_SQLiteStorage class found'
*** First throw call stack:
(0x184fa82d8 0x1967740e4 0x184fa8198 0x185e5cf40 0x1001cdba8 0x1001d638c 0x1001bb760 0x1000ed7e4 0x1000f0abc 0x1000f0c9c 0x189a5b190 0x189c72854 0x189c75208 0x189c73778 0x18d7b93c8 0x184f6027c 0x184f5f384 0x184f5d9a8 0x184e892d4 0x189a5443c 0x189a4efac 0x1000f313c 0x196df2a08)
libc++abi.dylib: terminating with uncaught exception of type NSException
</code>

Any ideas what would be causing this?  I am not doing anything with ForestDB as far as I am concerned, but this seems to be the only part that is known to cause this error.

In the meantime I will be going back to the publicly distributed version to continue development, and implement custom features later.

Thank you for your time

**Comment by snej** [comment]
The error means the library you built doesn't have the SQLite storage code in it. (`no CBL_SQLiteStorage class found`.) Which target did you build, and what build directory did you get the framework from?

Actually the simplest thing to do would be to keep using the regular distributed library. Just copy the CBLUITableSource source files into your project, rename the class so it doesn't conflict, and make the changes you need.

**Comment by zgramana** [comment]
@SteffeyDev can you confirm is you're sorted out, or do you still have the problem?

**Comment by SteffeyDev** [comment]
Adapting my own CBLUITableSource without using the new framework has worked brilliantly, I will wait until this version is more documented before making the switch.  Thank you very much.

**Comment by pasin** [comment]
@SteffeyDev have you add -ObjC to the Other Linker Flags in the target Build Settings? I believe adding -ObjC flag will solve your issue.

**Comment by pasin** [comment]
Per my comment above, I'm closing the issue now. @SteffeyDev , please let us know if adding -ObjC doesn't solve the issue.

**Comment by JoeyCarson** [comment]
@pasin Thanks for the tip on the -ObjC linker flag.  Ran into this issue and forgot to add that flag per the instructions in programming guide.
