### ISSUE TITLE
dateWithJSONObject: method cannot parse ISO 8601 dates with a time zone designator "+hhmm" or "-hhmm"

### ISSUE THREAD

**Issue by tmpduarte** [couchbase/couchbase-lite-ios#765]
I tried the following in the Xcode command line

```
po [CBLJSON dateWithJSONObject:@"2015-03-25T07:59:42+00:00"];
2015-03-25 07:59:42 +0000

po [CBLJSON dateWithJSONObject:@"2015-03-25T07:59:42+0000"];
nil
```
The only difference here is the Time Zone Designator which changes from **+00:00** to **+0000**. According to the ISO 8601 both designators are allowed. 
It was expected that both **po** attempts should return the same date which does not happen.

I am using couchbase lite v1.0 from cocoapods ``` pod 'couchbase-lite-ios', '~> 1.0'  ```.

**Comment by tmpduarte** [comment]
I investigated a bit more and I found that couchbase seems more compliant with this [W3C note](http://www.w3.org/TR/NOTE-datetime) that limits the scope of the ISO 8601 to a more restricted subset.

**Comment by snej** [comment]
Fixed in commit e2aeb39

**Comment by snej** [comment]
Reopened because the fix didn't work (and I reverted the commit.)

**Comment by snej** [comment]
Fixed for real by https://github.com/couchbase/couchbase-lite-ios/pull/767 (and I verified that the tests pass.)
