### ISSUE TITLE
SSL error -9806 from P2P replication

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#772]
In #724 @joshblour [says](https://github.com/couchbase/couchbase-lite-ios/issues/724#issuecomment-111698367) he's getting an SSL error trying to run a P2P replication:

Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo=0x1741ad740 {_kCFStreamErrorCodeKey=-9806, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, NSUnderlyingError=0x170240060 "An SSL error has occurred and a secure connection to the server cannot be made.", NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://yonahs-macbook-pro.local.:52021/proximator/_local/bf62d56660ceca7b09b41bbc73f751b092eac23c, NSErrorFailingURLStringKey=https://yonahs-macbook-pro.local.:52021/proximator/_local/bf62d56660ceca7b09b41bbc73f751b092eac23c, _kCFStreamErrorDomainKey=3}

This is with the master branch after the change that skip hostname validation for .local hosts.

**Comment by snej** [comment]
Error code -9806 is `errSSLClosedAbort`, "The connection closed due to an error."  
And -1200 is `kCFURLErrorSecureConnectionFailed`, "The secure connection failed for an unknown reason."  
Not very helpful...

**Comment by snej** [comment]
I was able to replicate from CBL in the iOS 8.3 simulator to LiteServ on my Mac (OS X 10.10) without problems; the replication URL was `https://jens.local:59840/grocery-sync/`. Appending a "." after the hostname worked too.

@joshblour, could you please turn on SyncVerbose logging and see if anything else relevant gets logged?

**Comment by joshblour** [comment]
Sure. My phone (8.1.2) and simulator(8.1.3) are trying to pull from each other.
simulator logs: https://gist.github.com/joshblour/34d2d5e3bfd7a6b75949
phone logs: https://gist.github.com/joshblour/3fe10eab0cdfb36f5701

**Comment by snej** [comment]
On either side the first sign of trouble is `CFNetwork SSLHandshake failed (-9805)`, which means "closed gracefully". Weird.

**Comment by joshblour** [comment]
ok! I'm able to reproduce the issue using GrocerySync. checkout my fork here: https://github.com/joshblour/Grocery-Sync-iOS/tree/bonjour-sync

I've committed my copy of the cbl framework as well.

**Comment by snej** [comment]
OK, I'll uncomment that stuff in PeerSync and build with the latest CBL from master.

**Comment by snej** [comment]
I can reproduce the problem running the same setup you describe.
Also, I can't connect to the listener in the simulator from a 'curl' command on my Mac; I get the exact same SSL error -9805.
However, I _can_ connect to a CBL listener in LiteServ … so this seems to be some issue that only appears on iOS. That narrows things down...

**Comment by snej** [comment]
I can't figure out what's going on here. The SSL connection handshake is failing.

* The client receives the server cert from the NSURLConnection delegate API and the CBL code OKs it.
* The listener suddenly receives an error -9846 from SSLRead (down in GCDAsyncSocket.m) and closes the connection.
* This causes the client to get that -9805 error; it's just responding to the connection being closed from the other side.

I don't know why SSLRead is returning an error, and I don't know why this only happens on iOS.

**Comment by snej** [comment]
I tracked the problem down further yesterday: when the SecIdentityRef is read from the Keychain, it incorrectly has the public key, not the private key. I asked about this on the apple-cdsa list, and Ken McLeod confirmed it's a bug in iOS:

>It sounds like you've diagnosed this correctly, and have run into Radar 18205627. On iOS, there is an issue where the query that fetches the private key for a certificate is only for kSecClassKey with a particular kSecAttrPublicKeyHash, omitting the key type. If both the private and public keys are present, they'll both match, and so which one is returned depends entirely on the order in which they happen to exist in the keychain. Normally the private key is found first, but the public key could get inserted ahead of the private key in some cases.

>If you don't need the public key to exist in the keychain, then deleting it from the keychain would be a workaround.

The workaround solved the problem and I can now make SSL connections to Grocery Sync.

**Comment by joshblour** [comment]
I've built from master but I'm still getting the same error code, and also some new ones (`kCFStreamErrorDomainSSL error -9846.` and `kCFStreamErrorDomainSSL error -9801.`)

gist here: https://gist.github.com/joshblour/ff7792ba66770db571d4

**Comment by snej** [comment]
Did you make sure to update submodules? The actual fix is in vendor/MYUtilities/MYAnonymousIdentity.m.

**Comment by snej** [comment]
Another thing to try is using `curl` to call the listener. You have to use the `-k` flag to disable cert validation.

**Comment by joshblour** [comment]
Ok, i've just updated the submodules, but still getting it...
here's the results from curl:
````
Yonahs-MacBook-Pro:couchbase-lite-ios Yonah$ curl https://iPhone-de-Yonah.local.:52021/proximator
curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
Yonahs-MacBook-Pro:couchbase-lite-ios Yonah$ curl https://iPhone-de-Yonah.local.:52021/proximator -k
curl: (35) Unknown SSL protocol error in connection to iPhone-de-Yonah.local:-9805
````

**Comment by snej** [comment]
That's exactly what `curl` did before the fix. Are you sure you rebuilt both CouchbaseLite.framework and CouchbaseLiteListener.framework? Also, as a sanity check, open MYAnonymousIdentity.m and verify that it has a static function called `removePublicKey`. (That's the one I added as part of the fix.)

(I had a lot of these problems myself while debugging. I'd add logging and find it wasn't taking effect, if I didn't make sure to rebuild both frameworks.)

**Comment by snej** [comment]
Oh! I know what the problem is. Your app still has the original key-pair in its keychain. The fix (workaround for Apple's bug) was to remove the public key from the keychain after generating the key-pair. But this only happens when generating the key-pair, i.e. when there isn't already a key-pair in the keychain.

Unfortunately it seems as though even deleting an app doesn't delete its keychain. I found that to get the change to take effect in the simulator I had to reset the entire simulator. Obviously not practical for a real device!

What you can do, though is change the `label` string you pass to `setAnonymousSSLIdentityWithLabel:`. That will result in a new key-pair being created.

**Comment by joshblour** [comment]
Awesome! I'll try that

**Comment by joshblour** [comment]
That did the trick! thank you

**Comment by snej** [comment]
Whew! Thanks for finding this problem. I was being lazy before and only tested SSL with LiteServ on my Mac (because 99% of the time things work the same on both platforms … I forgot that crypto/Keychain is always an exception!)
