### ISSUE TITLE
Live Query KVO while using "backgroundTellDatabaseNamed:" doesn't work

### ISSUE THREAD

**Issue by thiver** [couchbase/couchbase-lite-ios#779]
Using iOS SDK 8.3
Using Couchbase Lite 1.0.4

When you have a Live Query started on the main thread, showing the data in a UITableView for example, the Live Query doesn't send out a "rows" KVO notitication, when the data is changed in a backgroundTellDatabaseNamed: function call. If you replace the background database with the database on the main thread, the notifications work well.

The data itself always updates, it are just the notifications that are not sent. If you scroll the UITableView or do a UITableView reloadData manually, the content gets replaced.

My temporary solution was to attach an observer to each document, but this results in an giant collection of observers firing to much notifications.

I will make an Xcode Project with the problem.

**Comment by pasin** [comment]
@thiver I have added a unit test to check the issue but I was not able to reproduce the issue. 

Last week we officially released v1.1.0 which also contains some fixes to the LiveQuery. Could you also tried v.1.1.0 with your application to see if the issue still exists? Please let us know. Thanks.

**Comment by thiver** [comment]
Hi, I just tested v1.1.0 and had no problem receiving notifications from the live query when the database was accessed in the background.

Thanks!

From: Pasin Suriyentrakorn
Reply-To: couchbase/couchbase-lite-ios
Date: Thursday 25 June 2015 11:36
To: couchbase/couchbase-lite-ios
Cc: Thijs Vergauwe
Subject: Re: [couchbase-lite-ios] Live Query KVO while using "backgroundTellDatabaseNamed:" doesn't work (#779)


@thiver<https://github.com/thiver> I have added a unit test to check the issue but I was not able to reproduce the issue.

Last week we officially released v1.1.0 which also contains some fixes to the LiveQuery. Could you also tried v.1.1.0 with your application to see if the issue still exists? Please let us know. Thanks.
