### ISSUE TITLE
Release 1.1.0 pod spec fails to install looking for LICENSE.txt

### ISSUE THREAD

**Issue by evankyle** [couchbase/couchbase-lite-ios#780]
[!] Unable to read the license file `.../Pods/couchbase-lite-ios/LICENSE.txt` for the spec `couchbase-lite-ios (1.1.0)`

**Comment by pasin** [comment]
@evankyle I have just published the podspec to cocoapods.org. Please use the published one instead.

**Comment by pasin** [comment]
I don't know why when trying to use the podspec locally, the license file doesn't get copied to the right location. Anyway the published podspec works file.

**Comment by evankyle** [comment]
Thanks! Works now just tested too.

btw, I was using;

pod 'couchbase-lite-ios', :git => 'https://github.com/couchbase/couchbase-lite-ios.git', :branch => 'release/1.1.0'

**Comment by pasin** [comment]
Currently we only have a podspec that links to our pre-built zip file. We do not have a podspec that can build the framework from the source code yet. So pointing the pod to the repo directly will not be working now. We will try to make it work in the next release.
