### ISSUE TITLE
Warning replicating attachments from CouchDB

### ISSUE THREAD

**Issue by desarrollospyro** [couchbase/couchbase-lite-ios#786]
While replicating a database with attachments a warning is appearing <i>"Oops, server is trying to send a compressed attachment, I can't do that yet"</i>. I find a condition in CBLMultipartDocumentReader.m class that don't let to replicate documents with attachments. Is there any problem with attachments? Where can we replicate documents with attachments?

**Comment by snej** [comment]
Replication with attachments works. What server are you replicating with?

**Comment by desarrollospyro** [comment]
We are replicating a couchDB and rCouch database servers with couchbaselite ios.

**Comment by snej** [comment]
I think at some point in the last year or two CouchDB started sending (some?) attachments with gzip compression, which it didn't use to, and CBL doesn't handle it.

**Comment by snej** [comment]
That warning is in -[CBLMultipartDocumentReader startedPart:]; it happens when the attachment's headers include `Content-Encoding:`. This warning is fairly new (3/2015) but I think the old behavior would have been to silently do the wrong thing.

If this is being triggered by CouchDB, it means that CouchDB is (finally) emitting headers for nested MIME parts. It didn't use to include any headers at all.

If someone wants to help debug this, please set a breakpoint on the warning (currently CBLMultipartDocumentReader:246) and find out what the value of `headers` is.

**Comment by dyowee** [comment]
Not sure if this will help. I wrote a small C# app to get the headers. Requesting a document that has an attachment returned these headers: 
        Connection: keep-alive
	Content-Length: 443
	Cache-Control: must-revalidate
	Content-Type: text/plain; charset=utf-8
	Date: Mon, 29 Jun 2015 07:23:17 GMT
	ETag: "4-0c292b2522faf59db8864ed736d5fa7e"

Requesting the attachment itself returned these:
        Connection: keep-alive
	Accept-Ranges: none
	Content-Length: 146789
	Cache-Control: must-revalidate
	Content-Type: text/html; charset=utf8
	Date: Mon, 29 Jun 2015 07:27:54 GMT
	ETag: "UmAzp8Fd2FJFpV2dI0Uw1w=="

**Comment by desarrollospyro** [comment]
We catch the headers value with a NSLog print:
`{
    "Content-Disposition" = "attachment; filename=\"h-thumb\"";
    "Content-Encoding" = gzip;
    "Content-Length" = 12492;
    "Content-Type" = "image/jpeg";
}`

Also we make some tests with uncompressed files (images) and the replication finishes fine but when we want to view the images, it doesn't work. We make this test with rCouch server.

Thanks for your quick replies.

**Comment by snej** [comment]
I'm working on a fix. I can reproduce the problem with the latest CouchDB (1.6.1).

**Comment by snej** [comment]
I wouldn't recommend updating to this revision — earlier today I checked in a bunch of major replicator changes that haven't had enough testing yet — but it's a small patch and should be easy to cherry-pick onto the 1.1 release.

This would also be a good candidate to include in a hypothetical 1.1.1 update.

**Comment by dyowee** [comment]
Thanks. :) Will wait for 1.1.1

**Comment by huytd** [comment]
As mentioned in #837, I have get the source and build it by myself. 
It worked but only for HTTP protocol, when I try with HTTPS, the message is not displayed anymore but there is nothing saved to local database.

**Comment by snej** [comment]
That sounds like a different problem. Please file a new issue.
