### ISSUE TITLE
OSX: CouchbaseLite.h tries to  #import "CBLUITableSource.h" but that header is missing 

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-ios#790]

**Comment by pasin** [comment]
I'm not sure why the following statement in CouchbaseLite.h doesn't work.
```
#if TARGET_OS_IPHONE
#import "CBLUITableSource.h"
#endif
```

**Comment by pasin** [comment]
Is this error from v1.1.0 binary?

**Comment by snej** [comment]
I build OS X apps and I've never seen this happen. More details please.

**Comment by zgramana** [comment]
Yes, this error happened with the 1.1 release binary. User initially downloaded the iOS package, so confirming the issue still exists. Also asked them to make sure that the MacOS target isn't also accidentally defining TARGET_OS_IPHONE.

**Comment by zgramana** [comment]
Confirmed that user inadvertently added the OSX framework to an iOS target.
