### ISSUE TITLE
MQTT broker support for Listener

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-ios#799]
Listener module to allow CBLite to act as a [broker for MQTT data](https://github.com/mqtt/mqtt.github.io/wiki/public_brokers). This allows CBLite to ingest data from MQTT networks, run map reduce on them, and additionally push into Sync Gateway.

Preliminary requirements:
* Bridge MQTT topics to SG channels.
* Optimize for ForestDB storage engine.
* Support incremental reductions.
* Support reduce 'into'.

**Comment by snej** [comment]
[Mosquitto](http://mosquitto.org/) is an open source broker implementation in C. It builds as a daemon process; I don't know how hard it would be to break out into a library we could call.

Protocol docs: [The official spec for v3.1.1](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html) is huge and very difficult to read. [This earlier spec for v3.1](http://public.dhe.ibm.com/software/dw/webservices/ws-mqtt/mqtt-v3r1.html) looks a lot clearer.
