### ISSUE TITLE
"Unexpected CBForest exception iterating query"

### ISSUE THREAD

**Issue by SebastianBO** [couchbase/couchbase-lite-ios#800]
We've had problems with the Facebook Login, these are one of the errors.

"WARNING: Unexpected CBForest exception iterating query". For some reason it works sometimes with Facebook Login SDK 4.0 + with ForestDB / CBL 1.1 with SG 1.1.
Is there anyone who has been able to get it stable? The Facebook login code looks very similar to the  ToDoLite when you updated the SDK, has there been any update on that where you adapt to ForestDB etc that i've missed? Best Regards

**Comment by snej** [comment]
Could you describe the exact steps to reproduce this? Even better would be if you could show us sample code.

ForestDB shouldn't be affecting a higher-level operation like Facebook auth, but it's possible your code is using some particular type of query that exposes a bug in our ForestDB storage. But I'd need to see exactly what the parameters of the query are.

**Comment by SebastianBO** [comment]
Right, well we have upgraded all of our queries to ForestDB with "documentType",


from: if ([doc[fDocType] isEqualToString: sTUser]) 
to :viewAllUsers.documentType = sTUser;

but we also use the new query builder in our framework that initially shows in debug mode what type of documents are stored locally, like the Couchbase Lite Viewer but inside the apps. But that query only gets executed when inside the View Controller so that should not be the issue i think.

**Comment by snej** [comment]
Turn on `Query` logging and you should get log messages before (and maybe after) the warning telling you what query it's running. If that's not enough info, try changing to `QueryVerbose`.

**Comment by SebastianBO** [comment]
DocumentType has nothing to do with ForestDB whatsoever of course,  sorry about that :) And yes il try to debug

**Comment by snej** [comment]
@SebastianBO: We'd like to track this down and fix it; do you have any new information like log output? Thanks!

**Comment by SebastianBO** [comment]
Hopefully i can look into it tomorrow, 01:12 am here

**Comment by zgramana** [comment]
@sebastianbo any updates?

**Comment by zgramana** [comment]
@sebastianbo we'll close this next Friday if we don't receive any updates.

**Comment by zgramana** [comment]
@sebastianbo if you can post additional info, we can re-open.
