### ISSUE TITLE
Nested CBLJSONEncoding example -

### ISSUE THREAD

**Issue by iamabhish** [couchbase/couchbase-lite-ios#801]
Hello,

I am designing an application where there are three classes. 

class A  derived by CBLJSONEncoding and implementing protocol
class B also derived by CBLJSONEncoding and also keeping NSArray of class A.
class C derived by CBLModel class and keeping the NSArray of class B.

class A: CBLJSONEncoding
{

}

class B: CBLJSONEncoding
{

NSArray *arrayOfA; -- here only addresses of A comes
};

class C: CBLModel
{

NSArray * arrayofB; - this gets encoded properly
}

When I am saving the object. the encoded Json seems to work fine till the level of class C and class B.
But the class A is not being encoded and instead only address of Class A are coming within Class B.

Could you please guide how to hold the CBLJSONEncoding class within CBLJSONEncoding dervied class?

I am also not able to find proper example of NestedModeling. On how to use

+ (Class)nsarrayitem{
    return [NSArrayItemClassl class];
} 

Kindly guide.

Thanks
Abhishek

**Comment by snej** [comment]
We use our issue tracker for bug reports and feature requests, not for questions — you can ask your question on our mailing list or web forum.

https://groups.google.com/forum/?fromgroups#!forum/mobile-couchbase
https://forums.couchbase.com/c/mobile
