### ISSUE TITLE
[CBLReplication setAnchorCerts:] with self-signed cert disables push replication

### ISSUE THREAD

**Issue by sapieneptus** [couchbase/couchbase-lite-ios#804]
CBL 1.1, SG 1.1

We have a self-signed ssl cert on a staging server (because we connect to the SG via IP address since we've found the connection closes with DNS / reverse proxy). We connect using basic auth and reference a local `.der` file to allow the cert to be recognized as valid, like so:

```
        NSMutableArray *certs = [NSMutableArray array];
        NSString *resourcePath = [[NSBundle mainBundle] pathForResource:ENVIRONMENT ofType:@"der"];
        if (resourcePath) {
                NSData *certData = [NSData dataWithContentsOfFile:resourcePath];
                SecCertificateRef cert = SecCertificateCreateWithData(NULL, (__bridge CFDataRef)certData);
                if (cert) {
                        [certs addObject:CFBridgingRelease(cert)];
                        [CBLReplication setAnchorCerts:certs onlyThese:NO];
                }
        }
```
 We have enabled logging with `ChangeTracker`. 

When we launch the app, it seems to pull correctly, but the push replication does not seem to work as it should. 

[Here is the log from a fresh onboard (lots of pull) followed by several document updates (which ought to sync).] (https://gist.github.com/sapieneptus/7f06778e68b9a81d0dea)

Please let me know what other info I can provide.

**Comment by snej** [comment]
Did you look through the logs yourself? It's always a good idea to look for warnings. There's one from the push replicator:

```
18:27:47.731â€– WARNING: CBL_Pusher[https://54.85.252.215:4982/db_3_19_14_2]: _bulk_docs got an error: {
    error = "bad_request";
    id = "report::557f2cf071df8afe5c06b77a";
    reason = "user defined top level properties beginning with '_' are not allowed in document body";
    status = 400;
}
```

So, your database has a document with ID `report::557f2cf071df8afe5c06b77a` that was rejected by the server for having an unrecognized property name starting with `_`.

My guess is that you're running into issue #671. The fix was checked in recently (PR #776); the reason the issue is still open is because we have some new replication code that's not enabled yet that needs a similar fix added to it. It's a five-line fix (without the unit test) so it would be easy to cherry-pick onto 1.1.

**Comment by sapieneptus** [comment]
Hi Jens,

I did see those, but assumed they were not causing the issue since we have seen that error before using self signed certs and did not encounter the problem. 

Nevertheless we'll give cherry picking that fix and see what happens.

**Comment by sapieneptus** [comment]
Having a spot of trouble building the latest. Since we're often building from source, I'm trying to link the project directly, as per [these instructions] (https://github.com/couchbase/couchbase-lite-ios/wiki/Building-Couchbase-Lite#linking-couchbase-lite-into-your-own-app). 

Getting a block of undefined symbol warnings:

```
Undefined symbols for architecture x86_64:
  "_CBLGeoPointKey", referenced from:
      ___21+[CBSync setupViews:]_block_invoke_7 in CBSync.o
  "_OBJC_CLASS_$_CBLJSON", referenced from:
      objc-class-ref in TeamHistoryView.o
      objc-class-ref in Utility.o
      objc-class-ref in Filter.o
      objc-class-ref in OpenIssueCell.o
      objc-class-ref in Report.o
      objc-class-ref in PieChartVisualizationView.o
      objc-class-ref in UserHistoryView.o
      ...
  "_OBJC_CLASS_$_CBLManager", referenced from:
      objc-class-ref in CBSync.o
  "_OBJC_CLASS_$_CBLReplication", referenced from:
      objc-class-ref in CBSync.o
  "_OBJC_CLASS_$_CBLView", referenced from:
      objc-class-ref in CBSync.o
  "_kCBLReplicationChangeNotification", referenced from:
      ___24-[CBSync initializeSync]_block_invoke in CBSync.o
ld: symbol(s) not found for architecture x86_64
```

The odd thing is we aren't building for x86_64 (that I'm aware of). Our settings are pretty vanilla:

<img width="689" alt="screen shot 2015-07-03 at 11 07 10 pm" src="https://cloud.githubusercontent.com/assets/3009852/8506729/4ea69616-21d8-11e5-8aed-d9dc8f70b2ad.png">

Attempting to just build the CBLContinuous target and manually drop in the framework (which we have successfully done many times in the past) gives us this error:

```
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_JSContext", referenced from:
      objc-class-ref in CouchbaseLite(CBLJSFunction.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'd prefer to be able to link in the project, but for the sake of testing this fix it'd suffice to get either way working.

**Comment by sapieneptus** [comment]
Linked our project with JSCore (never had to do this before?) and was able to get the archived framework to build, though it would still be preferable to link the project directly. 

On the plus side, the fix seems to have worked. Will update if we discover to the contrary.

**Comment by snej** [comment]
>I did see those, but assumed they were not causing the issue

FYI, if you're having problems with SSL certs, you won't get as far as sending or receiving any HTTP traffic — the client or server will just abort the socket during the initial handshake. So any logging that involves an HTTP response from the server indicates that the SSL handshake worked.

**Comment by snej** [comment]
>The odd thing is we aren't building for x86_64

You are if you're targeting the simulator, i.e. if the target device in the Xcode toolbar is a simulator and not a real device.

No idea why you'd get those link errors though. Are you sure you symlinked the framework from the `Debug-ios-universal` directory? That's the one that has both device and simulator binaries.

**Comment by snej** [comment]
>Linked our project with JSCore (never had to do this before?)

We've added the JavaScript map/reduce support into the framework itself since a number of developers use it. It won't have any runtime impact if you're not using it, but it does require linking against JavaScriptCore.

**Comment by sapieneptus** [comment]
Looks like we had an issue on our side which masked the fact that documents were actually syncing. Appears to be resolved now, thanks for you help.

**Comment by snej** [comment]
Whew!
