### ISSUE TITLE
Add "_conflicts" property to doc in map function when doc is in conflict

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#806]
It's poorly documented, but CouchDB adds a `_conflicts` property to the `doc` object passed to a map function, when the document is in conflict. [From the CouchDB wiki](http://wiki.apache.org/couchdb/Replication_and_conflicts):

>Views only get the winning revision of a document. However they do also get a _conflicts member if there are any conflicting revisions. This means you can write a view whose job is specifically to locate documents with conflicts. Here is a simple map function which achieves this:
```
function(doc) {
  if (doc._conflicts) {
    emit(null, [doc._rev].concat(doc._conflicts));
  }
}
```

For compatibility it would be good to support this. I don't think it will affect performance: the SQLite engine already has to iterate over all the conflicting revisions, and the ForestDB engine has all the revisions readily available in the `VersionedDoc` object.

**Note:** We already support finding conflicts using `_all_docs` queries. In the REST API, add the query param `?include_conflicts=true` or `?only_conflicts=true`. In the native API use `kCBLShowConflicts` or `kCBLOnlyConflicts`. This is actually more convenient than having to create a special view just to find conflicts.

**Comment by borrrden** [comment]
I see you made some commits to the ForestDB storage engine in regards to this ticket, but not SQLite.  Was SQLite already working?  Or will it not be supported?

**Comment by pasin** [comment]
Yes, I just fixed the reference to the commit and PR. Please look at the PR link above.
