### ISSUE TITLE
CBLReplication.pendingDocIDs doesn't update while replicator not running

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#807]
It relies on calling the background CBLReplicator to compute the actual value, so it won't do anything if there isn't one or it hasn't been started.

It should be able to do the work itself by just reading the latest checkpointed sequence from the database.

**Comment by pasin** [comment]
I looked at the current implementation and noticed that the method returns the cached result of the first time call. Why don't we compute the result every time?

**Comment by snej** [comment]
I think I was assuming that it might get called a lot. Like, a table view might call it on every visible row to highlight the ones that still need to be synced.
