### ISSUE TITLE
Notify app when push replicator gets a 403 (server rejected doc)

### ISSUE THREAD

**Issue by jschmid** [couchbase/couchbase-lite-ios#813]
This issue is related to [this thread](https://groups.google.com/d/msg/mobile-couchbase/ijaSWNKWdww/hHIGLY1JKKMJ).

It could be nice if the replicator posts a notification when it gets a rejection from the sync gateway.
As Jens also said, the replicator could also post "finer-grained progress information".

**Comment by atom992** [comment]
If the replicator can post the reason of why sync gateway reject the doc at the same time, It will be better for CBL to handle the conflict depend on the error message.

**Comment by zgramana** [comment]
Good proposal. We will work on a spec.

**Comment by pasin** [comment]
Currently the only notification from the replicator is kCBLReplicationChangeNotification. The notification is sent with empty info (UserInfo). One option is that we add a list of failed or rejected document ids to the user info.

**Comment by zgramana** [comment]
Having an internal discussion next week.

**Comment by pasin** [comment]
We have implemented this in 2.5.0.
