### ISSUE TITLE
Is CBLQueryBuilder working at all in Swift

### ISSUE THREAD

**Issue by jmcazaux** [couchbase/couchbase-lite-ios#814]
Hi there,
I have been trying to use QueryBuilder in a swift project, but I did not succeed even initializing the thing?

Has it beed tested and proven in Swift ?

My initilisation code looks like this : 
>           var error: NSError
>
>           let select: [AnyObject]? = [NSExpression(format: "count(*)")]
>
>           let queryBuilder = CBLQueryBuilder(database: database,
>               select: select,
>               where: "type == 'alert'",
>               orderBy: nil,
>               error: &error)

On the `select = select` , it wants me to add a semi-colon (`Expected ',' separator`) and on the `where` line, its says something along the lines `Expected expression in list of expressions`

And the documentation is sparse and does not cover Swift (or I messed it all together).

Many thanks in advance for your help.

**Comment by snej** [comment]
The problem is that `where` is a reserved word in Swift, so using it as a parameter keyword confuses the parser. Fortunately there's an alternate initializer that uses the keyword `wherePredicate:` instead. Here's initialization code that compiles for me:

```swift
        var error: NSError?
        let select = [NSExpression(format: "count(*)")]
        let pred = NSPredicate(format: "type == 'alert'")
        let queryBuilder = CBLQueryBuilder(database: database, select: select, wherePredicate: pred, orderBy: nil, error: &error)
```

Also note that `select` doesn't have to be an optional, but `error` does.

**Comment by snej** [comment]
Just found another way around this — put `where` in back-quotes. That tells the Swift parser not to treat it as a reserved word.

**Comment by jmcazaux** [comment]
Thank you snej, that was a quick answer ;)

If I may suggest, the documentation should be amended, or change the method signature.
