### ISSUE TITLE
ChangeTracker SSL settings incompatible with iOS 9 Transport Security

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#815]
iOS 9's new [App Transport Security](https://developer.apple.com/library/prerelease/mac/technotes/App-Transport-Security-Technote/) feature requires that apps make only SSL connections, using at a minimum the TLS 1.2 protocol. This conflicts with code in CBLChangeTracker that forces the connection to use TLS 1 (`kCFStreamSocketSecurityLevelTLSv1`). I added this restriction a long time ago because some SSL servers/proxies were incompatible with TLS 1.2 so Apple recommended falling back to an earlier version.

The result is that by default, a pull replication will immediately fail with an SSL error :(

The fix is to remove the line in CBLChangeTracker.m that sets this key in the SSL options dictionary. We should try to get this into a release before Apple's deadline for submitting apps before the iOS 9 release.

The workaround is for the app to opt out of Transport Security using the Info.plist keys described in the technote. It'll need to set `NSAllowsArbitraryLoads=YES`, or maybe just `NSExceptionMinimumTLSVersion=TLSv1.0`, either globally or for the domain of the server CBL is syncing with.

Even with this fix, apps may have problems if their servers' SSL configurations aren't modern enough for Transport Security. Some of this is a matter of how the cert is generated (it needs to be at least RSA-2048 with a SHA-256 fingerprint) but some of it is the SSL implementation itself — it needs to handle ciphers that support forward secrecy (see the list in the technote.) ~~I haven't yet tested Sync Gateway to see if Go's SSL implementation is compatible.~~

Peer-to-peer apps will have other problems; I'm trying to fix those right now on the master branch but the changes are too big to put into a 1.1.1 release. For now any app that wants to make P2P connections should just turn off Transport Security entirely.

**Comment by snej** [comment]
I just tested Sync Gateway 1.1 with its built-in Go SSL server; it works fine with Transport Security.

**Comment by zgramana** [comment]
Resolved on master in https://github.com/couchbase/couchbase-lite-ios/commit/f0eb1cb54d59095f2adc3f3c8b9a7c37991d7272.

**Comment by snej** [comment]
This turns out not to be a problem.

1. Apparently `kCFStreamSocketSecurityLevelTLSv1` means to use a _minimum_ of TLS 1.0, which means TLS 1.2 will be used when available, so connections to SG use 1.2.
2. I'm now seeing that ATS doesn't care what SSL protocol version CFStream connections use — I've seen it accept a TLS 1.0 connection. That's confusing because it contradicts the docs. Maybe the TLS 1.2 requirement only applies to NSURLConnection/NSURLSession?
