### ISSUE TITLE
Add SSL client cert support to replicator

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#82]
The replicator should be able to use a client-side SSL cert for authentication to the server. I think this mostly means checking for the associated auth type in the NSURLConnection delegate auth callback, looking up the cert, and passing it back as a credential.

There will need to be public API to specify what cert to use for a replication.

(See #81 for server-side SSL support in the listener. Both sides are needed for secure P2P replication.)

**Comment by snej** [comment]
Should clarify: It's _useful_ for P2P. There are other ways the 'server' (listener) can verify the 'client' (initiator), but they require setting up authentication and creating an account with a password. SSL client certs are a lot cleaner.

**Comment by sapieneptus** [comment]
@snej  What about the `[CBLReplication setAnchorCerts: onlyThese:];` API? I just tried using this with a self-signed, but it only appears to work for pull replications (push don't seem to trigger any activity whatsoever - logging `SyncVerbose` doesn't even make any output).

**Comment by snej** [comment]
@sapieneptus That method is for _server_ certs. If you're having trouble with that method, please file a new issue. Thanks.

**Comment by snej** [comment]
Checked in the implementation; last commit was bd1be92.
