### ISSUE TITLE
CouchbaseLite 1.1: Missing CouchbaseLiteListener.framework when install/update via CocoaPods

### ISSUE THREAD

**Issue by mnguyen85** [couchbase/couchbase-lite-ios#821]
I updated my podfile today as following to update to 1.1 (was working before with 1.0.4)

pod 'couchbase-lite-ios', '~> 1.1.0'

However, after pod install, pod update, its missing CouchbaseLiteListener.framework.

**Comment by pasin** [comment]
We have moved the Listener framework into a subspec as not every application uses the listener.

Please add `pod 'couchbase-lite-ios/Listener', '~>1.1.0'` to your Podfile.

**Comment by mnguyen85** [comment]
Ahhh I see, thank you
