### ISSUE TITLE
CBLQueryBuilder initializer naming is incompatible with Swift

### ISSUE THREAD

**Issue by 24601** [couchbase/couchbase-lite-ios#823]
It appears the - (nullable instancetype) initWithDatabase: (nullable CBLDatabase*)database   select: (nullable NSArray*)valueTemplate  where: (NSString*)predicateStr orderBy: (nullable NSArray*)sortDescriptors error: (NSError**)outError; method translates into an invalid Swift constructor (specifically, the "where" for the predicateStr is something the Swift compiles does not like when you try to declare a CBLQueryBuilder in swift with something like  var query = CBLQueryBuilder(database,select: valueTemplate, where: predicateStr, orderBy: sortDescriptors, error: outError) because the where keyword appears to be reserved in Swift.

Renaming this will create a breaking API change, so perhaps adding a new method with a signature that is not illegal when translated to Swift/called from Swift would be helpful. This is what I do in my workaround, which is to create an Objective-C wrapper/helper that I call from my Swift code that does precisely that. The function I am using in this helper for a complete workaround looks like this:

+(CBLQueryBuilder*) buildWithDatabase: ( CBLDatabase*)database
                               select: ( NSArray*)valueTemplate
                                wherePredicateStr: (NSString*)predicateStr
                              orderBy: ( NSArray*)sortDescriptors
                                error: (NSError**)outError
{
    
    return [[CBLQueryBuilder alloc]
            initWithDatabase: database
            select:valueTemplate
            where: predicateStr
            orderBy: sortDescriptors
            error: outError];
}

then I just call:

var cblQuery = MyObjcWrapperHelperClassThatIAmBridging.buildWithDatabase(......)

And it works just fine.

**Comment by snej** [comment]
Same as #814. There's already a variant with a `wherePredicate:` keyword, which you can use instead. Or you can put the `where:` keyword in back-quotes, which tells the Swift parser not to treat it as a reserved word.
