### ISSUE TITLE
Phonegap Todo-lite channel creation issue

### ISSUE THREAD

**Issue by JPDas** [couchbase/couchbase-lite-ios#825]
We are not able to mimic the native API functionality of “sync/replicate with channel filter” using CBL REST API….Is there anything specific we have to do ???
We are using the coax module from phonegap “Todo-lite” app….
 
The problem as far as I can tell, is the “replicate” CBL REST endpoint is not taking the “channels” parameter……

**Comment by snej** [comment]
In the REST API you also need to add a parameter `"filter":"sync_gateway/bychannel"`.

**Comment by JPDas** [comment]
Can you please let us know which REST API do we need to add this ??

(a) When we added to the "replicate" ....it was ignored (could not see in the outgoing http request)

(b) When we added to the "changes" feed API ..it took it (we could see it in the outgoing http request as shown below) ...but it did not work....i.e we can see changes from other channels make it to ios CBLite......and also the changes stopped reaching the webview (javascript side)

[Log] XMLHttpRequest (modules.js, line 1372)
_id: "3: GET http://lite.couchbase./pratap_test/_changes?include_docs=true&since=50&filter=sync_gateway%2Fbychannel&channels=11111&feed=longpoll"
body: Object
id: "3: GET http://lite.couchbase./pratap_test/_changes?include_docs=true&since=50&filter=sync_gateway%2Fbychannel&channels=11111&feed=longpoll"
onabort: null
onerror: null
onload: null
onloadend: null
onloadstart: null
onprogress: null
onreadystatechange: function on_state_change(event) {
ontimeout: null
readyState: 4
response: "{"status":404,"error":"not_found"}"
responseText: "{"status":404,"error":"not_found"}"
responseType: ""
responseXML: null
seq_id: 3
status: 404
statusCode: 404
statusText: "Not Found"
timeout: 0
timeoutTimer: 13
upload: XMLHttpRequestUpload
withCredentials: false
__proto__: XMLHttpRequestPrototype

**Comment by JPDas** [comment]
Thanks Snej, 
Issue got resolved after adding the below params.

pull = {
	        	target : self.dbName,
	        	source : remote,
	        	continuous : true,
	        	filter: "sync_gateway/bychannel",
    			query_params: {"channels": "11111"}
	    	};
