### ISSUE TITLE
Removed long-deprecated facebook/persona auth API in CBLReplication

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#833]
This is a pair issue linked to commit https://github.com/couchbase/couchbase-lite-ios/commit/92b7cacc97418dfd201071aaa3b9e326ff0b48bb

Removed long-deprecated facebook/persona auth API in CBLReplication

This is deprecated APIs prior 1.0.0.

**Comment by snej** [comment]
This was cherry-picked to release/1.1.1 as 23c0dc2 on 7/29. We've decided to back it out, as it introduces an API change (even though the API was always deprecated.)
