### ISSUE TITLE
Allow adding/removing db encryption, or changing the key

### ISSUE THREAD

**Issue by brendand** [couchbase/couchbase-lite-ios#836]
Now that ForestDB has support for encryption (yay!!!), there is one issue that would be great to be addressed to make it perfect.

According to the CBL Wiki:

`It's not yet possible to add encryption to an existing database, or to change or remove the key afterwards.`

In my current app, I allow the user to encrypt a non-encrypted database, change the key, and decrypt an encrypted database so it no longer requires the key to open.

IMHO, adding these features would make the CBL encryption story complete.

**Comment by snej** [comment]
With SQLCipher, we'd use the [`sqlcipher_export`](https://www.zetetic.net/sqlcipher/sqlcipher-api/index.html#sqlcipher_export) function to write a copy of the database with the updated key, then replace the old db with the new one.

There is also a [`pragma rekey`](https://www.zetetic.net/sqlcipher/sqlcipher-api/#rekey) command, but the docs say it can only be used to change the key of an already-encrypted database, not to add or remove encryption.

With ForestDB, the equivalent is to manually compact the database to a new database, first registering the new key (or no key) for the new db, then replacing the db with the new one.

I have a feeling that in both cases the hardest part will be to coordinate between multiple threads that have the database open. The rekey operation will need to tell every other thread to close the database, do the update/replace, then let the other threads reopen using the new key. There's some overlap here with what `deleteDatabase` does.

**Comment by snej** [comment]
Oh, and either way all of the attachments have to be copied over with the new (or no) encryption too.

**Comment by snej** [comment]
I later had the idea that this could be done using the CBLDatabaseUpgrade class, by having it create a new database with the desired key (or no key.) It wouldn't be as fast, but it'd be a lot easier to implement!

**Comment by snej** [comment]
Tasks:

- [x] Re-key the attachment store (done as part of 722dfc5)
- [ ] Re-key a SQLCipher database
- [ ] Re-key a ForestDB database
- [ ] Central CBLDatabase method to tie the above together and act as the public API.

**Comment by brendand** [comment]
Have the other tasks been completed in the list above? They all look checked to me so I thought maybe they have, but I haven't found in the source from master the code to do this. I searched for sqlcipher_export to see if you were using that and I didn't see that you were for encrypting a non-encrypted database. I do see the code for the first task though. Or is this still a work-in-progress?

**Comment by snej** [comment]
Sorry, it's not quite ready to commit yet. Hopefully tomorrow!

**Comment by brendand** [comment]
That's great news!

**Comment by brendand** [comment]
I've just started testing encryption and I don't know if there's something I'm doing wrong, but I'm receiving a NO in response to calling changeEncryptionKey, but without an error returning.

Here's my code:

    NSString *encryptionKeyNew = @"test";
    BOOL didEncrypt = [couchDatabase changeEncryptionKey:encryptionKeyNew error:&error];
    if (!didEncrypt) {
       NSLog(@"Error: %@", error)
    }

I do have SQLCipher linked to my project and I also have SQLITE_HAS_CODEC enabled. So I'm not sure what I need to do now. I am running the above code on a separate dispatch queue (DISPATCH_QUEUE_PRIORITY_DEFAULT), so maybe that's it? Although I just took that out to test and it still didn't work.

**Comment by brendand** [comment]
Update: It's working for my ForestDB database. Just not for the SQLCipher database yet. Working on it...

**Comment by snej** [comment]
Hm, you must be hitting some configuration that isn’t covered in the unit tests for this feature. Is there any way you can create a simple test case that fails?

(The code paths are kind of complex because of the need to back out all the prior changes if any one operation fails, to avoid leaving the database damaged. It sounds like there’s a bug in there, at least in the SQLite-based part, but it may be hard to track down if I can’t watch it happening…)

**Comment by brendand** [comment]
I'll work on a test case app to see what I can come up with.

**Comment by brendand** [comment]
I've emailed you a sample app.
