### ISSUE TITLE
Client-side pull replication filters

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#847]
It could be useful to support a pull replication filter function that runs on the client side. It wouldn't have access to the document contents, just the docID and revID, but it could be used to implement pattern-based pull, like "skip all docs whose docID starts with 'xyz:'".

This could also serve as a workaround for [Sync Gateway not supporting pulling a set of documents](https://github.com/couchbase/sync_gateway/issues/545) (i.e. its `_changes` feed not supporting a list of docIDs.)

**Comment by snej** [comment]
A specific use case for this just came up: skip all design documents (i.e. doc IDs that start with `_design/`) when pulling from CouchDB.

**Comment by zgramana** [comment]
Needs a spec.
