### ISSUE TITLE
CBLManager setLogging:nil gives a compiler warning

### ISSUE THREAD

**Issue by pegli** [couchbase/couchbase-lite-ios#854]
Very minor gripe: can you move `+ (void) enableLogging: (NSString*)type` outside the `NS_ASSUME_NONNULL_BEGIN`/`NS_ASSUME_NONNULL_END` block since it accepts nil as a valid value?

**Comment by snej** [comment]
Sure, except the actual fix is to add the `nullable` keyword to the parameter.
