### ISSUE TITLE
Add API to defer downloading some attachments but not others

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#862]
Currently if you want to defer downloading some attachments, you have to set the replication's `downloadAttachments` property to `NO`, which stops it from downloading _any_ attachments automatically. But it's pretty likely that an application will only want some attachments to be deferred. It would be good to have a filter of some sort to let them customize this.

**Workaround:** Observe `CBLDatabaseChangeNotification`, examine the attachments of every new revision that's pulled, and immediately issue a download request for each attachment that you want.

(Re. #79)

**Comment by djpongh** [comment]
Moved to: https://issues.couchbase.com/browse/CBL-116
