### ISSUE TITLE
Migrating SQLite db to ForestDB

### ISSUE THREAD

**Issue by sapieneptus** [couchbase/couchbase-lite-ios#870]
I understand there's no inherent _need_ to migrate from SQLite to Forest. However, our project contains some fairly complex threading code to deal with the limitations of SQLite. It is my understanding that ForestDB's allowance of multithreaded access will allow us to greatly simplify our threading architecture. 

So I think it'd be great if we could migrate all of our users to ForestDB so we can simplify our project (rather than branch our code depending on their storage type). 

How might we go about doing that efficiently?

<hr>
_EDIT_
In the same vein, is the process for loading a pre-built db the same with ForestDB as it was for SQLite?

**Comment by snej** [comment]
In 1.1 there isn’t a direct way of doing this, although the infrastructure exists (there’s an internal class called CBLDatabaseUpgrader that copies a SQLite-based database into a new database.) I agree it would be good to have an explicit upgrade path, especially as ForestDB comes closer to becoming the default storage engine.

For now I believe you can do this by using a local-to-local replication, one where the remote URL is simply the name of the other database, like `[NSURL URLWithString: @“otherdb”]`. Configure the Manager to prefer ForestDB, create a new db, then replicate from the old db to the new one.
