### ISSUE TITLE
Support lowercase attachment blob filenames

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#875]
Android 1.0.4 and .NET 1.1.0 have lowercase blob file names and iOS expected uppercase filename. Somehow when testing this with simulator, everything works file even with lowercase file name but this is not the case on the real devices.

**Comment by snej** [comment]
iOS has a case-sensitive filesystem; OS X doesn't (so the simulator doesn't either.)

**Comment by pasin** [comment]
As android 1.1.0 has already fixed to use uppercased file name, and .NET will have the fix in 1.2 (as checking with @zgramana, the issue will be less and less critical going forward. Instead of fixing this in BlobStore to support lowercase, I will rename the files in UpgradeDatabase instead.

**Comment by snej** [comment]
I agree, renaming the files sounds like the best approach.
