### ISSUE TITLE
Listener throws warnings even though there is no error

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/couchbase-lite-ios#877]
Release: 1.1.1-8
Using the sync-gateway-tests repo when run the replication tests, Listener throws warnings:
 
"2015-08-19 17:57:52.113 LiteServ[50071:3815313] WARNING: CBLHTTPConnection: Client disconnected: (null)"

The tests run successfully with no data loss, all the documents get replicated to sync gateway with the expected revisions. 

This error was not present in 1.1.0 release. 

To run the tests from sync-gateway-tests repo. Please do the following 
- Clone repo https://github.com/couchbaselabs/sync-gateway-tests.git
- Download the sync gateway release 1.1.1
http://latestbuilds.hq.couchbase.com/couchbase-sync-gateway/release/1.1.1/1.1.1-8/
- Download the latest cbl-ios release http://latestbuilds.hq.couchbase.com/couchbase-lite-ios/release/1.1.1/ios/1.1.1-8/
- setup two environment variables in your bash_profile with respective path of SG and liteserv: 
example:
-- export LITESERV_PATH=/Users/ashvinder/Downloads/couchbase-lite-ios-enterprise_1.1.0-31/LiteServ.app/Contents/Tools/LiteServ
export SYNCGATE_PATH=/Users/ashvinder/mygit/sync_gateway/bin/sync_gateway
- source ~/.bash_profile
- cd sync-gateway-tests
- npm install
- node tests/cbl-replication.js

**Comment by pasin** [comment]
This is sort of a false alarm. Before warning, it needs to check if the error is nil or not. The bug happens only in 1.1.1 branch. 

https://github.com/couchbase/couchbase-lite-ios/blob/release/1.1.1/Listener/CBLHTTPConnection.m#L68-L71

@zgramana could you please review and let us know if you would like this to get fixed in 1.1.1?

**Comment by zgramana** [comment]
I think we can list this as a known issue in the release notes.

**Comment by pasin** [comment]
I'm closing this issue as the master branch already has the fix.
