### ISSUE TITLE
Need a purge method from CoreData with CBLIncrementalStore

### ISSUE THREAD

**Issue by mastohhh** [couchbase/couchbase-lite-ios#879]
I'm using CouchbaseLite iOS through CBLIncrementalStore.

This is great because I don't know about `CBLDocument`, `CBLDatabase` etc... But something's missing. I can't purge a `NSManagedObject`. The only thing I found is to fetch the associated `CBLDocument`, purge it, and then refresh `NSManagedObjectContext`contexts.

I can't do that *outside* `CBLIncrementalStore`because it calls private methods such as `couchbaseLiteIDRepresentation`or `informObservingManagedObjectContextsAboutUpdatedIDs:deletedIDs:`.

Do you think it could be a good idea to add a new category method on `NSManagedObjectContext` that allows to purge `NSManagedObject`s ?

Here's what I propose:

```objc
@interface NSManagedObjectContext (CBLIncrementalStore)

- (void)purgeObject:(NSManagedObject *)object;

@end
```

```objc
@implementation NSManagedObjectContext (CBLIncrementalStore)

- (void)purgeObject:(NSManagedObject *)object {
    CBLIncrementalStore *incrementalStore = (CBLIncrementalStore *)self.persistentStoreCoordinator.persistentStores.firstObject;

    NSString* uuid = [object.objectID couchbaseLiteIDRepresentation];

    CBLDocument *doc = [incrementalStore.database documentWithID:uuid];

    NSError *error;
    [doc purgeDocument:&error];

    if (error) {
        NSLog(@"%@", error);
    }
    else {
        [incrementalStore informObservingManagedObjectContextsAboutUpdatedIDs:@[] deletedIDs:@[object.objectID]];
    }
}

@end
```

I know this post sounds like a Pull Request, but I don't know if you want that feature. And I don't know if `self.persistentStoreCoordinator.persistentStores.firstObject`is the best way to get the `CBLincrementalStore`from the `NSManagedObjectContext`.

We can also add a method that takes an array of `NSManagedObject`s that loops on them and then just call once `informObservingManagedObjectContextsAboutUpdatedIDs:deletedIDs:`method.

Tell me if you want a PR.

Thank you

**Comment by pasin** [comment]
Thanks a lot for suggestion. I think it's a good idea. I will check with our PM @zgramana and get back to you.

**Comment by mastohhh** [comment]
Just for info, this code works fine :

```objc
@implementation NSManagedObjectContext (CBLIncrementalStore)

- (void)purgeObject:(NSManagedObject *)object {
    return [self purgeObjects:@[object]];
}

- (void)purgeObjects:(NSArray *)objects {
    CBLIncrementalStore *incrementalStore = (CBLIncrementalStore *)self.persistentStoreCoordinator.persistentStores.firstObject;

    [incrementalStore.database doAsync:^{
        NSMutableArray *objectIDs = [NSMutableArray array];

        for (NSManagedObject *object in objects) {
            NSString* uuid = [object.objectID couchbaseLiteIDRepresentation];

            CBLDocument *doc = [incrementalStore.database documentWithID:uuid];

            NSError *error;

            [doc purgeDocument:&error];

            if (error) {
                NSLog(@"%@", error);
            }
            else {
                [objectIDs addObject:object.objectID];
            }
        }
        
        [incrementalStore informObservingManagedObjectContextsAboutUpdatedIDs:@[] deletedIDs:objectIDs];
    }];
}

@end

````

**Comment by mastohhh** [comment]
If you want to add this feature in 1.2, I just want to tell you that the `purgeDocument:` method is slow.

In my case, I try to purge thousands of documents.

As we can see in the implementation, the `purgeDocument:` method calls `purgeRevisions:` that can take lots of documents :

```obj-c
- (BOOL) purgeDocument: (NSError**)outError {
    CBLStatus status = [_database.storage purgeRevisions: @{self.documentID : @[@"*"]} result: nil];
    if (CBLStatusIsError(status)) {
        CBLStatusToOutNSError(status, outError);
        return NO;
    }
    [_database removeDocumentFromCache: self];
    return YES;
}
```

Maybe it can be a good idea to add a `purgeDocuments:` method on `CBLDatabase` with an array of documents (or documentIDs).

An other idea : I just want documents in channels I subscribed to. I don't want to keep others, that's why `purge`is the good way to do this. But maybe it can be an option on `CBLReplication`object ? When we change channels, it purges all old documents in deleted channels ?

**Comment by snej** [comment]
File a new issue if you have a new problem to report. Thanks!

**Comment by pasin** [comment]
One thing that can help the slowness of the purge is calling compact regularly to reduce # of unused revisions.

**Comment by mastohhh** [comment]
As you are on this issue, let me tell you that the code I posted above doesn't work because of this line : 

```objc
[incrementalStore informObservingManagedObjectContextsAboutUpdatedIDs:@[] deletedIDs:objectIDs];
```

This line deletes objects. But I think not this method doesn't exists anymore

**Comment by pasin** [comment]
Yes, I'm working on this now. I have been shuffled the code around a little bit. It should be done very soon.
