### ISSUE TITLE
Duplicate symbols linking to CocoaHTTPServer and CouchbaseLiteListener on iOS.

### ISSUE THREAD

**Issue by ndouglas** [couchbase/couchbase-lite-ios#880]
I switched back to an architecture I haven't worked on for about a year or so and (after updating all of the relevant things I can think of) get these errors:

    duplicate symbol _DDUnionRange in:
     <snip>-CocoaHTTPServer.a(DDRange.o)
     <snip>/CouchbaseLiteListener.framework/CouchbaseLiteListener(DDRange.o)

    duplicate symbol _DDIntersectionRange in:
     <snip>-CocoaHTTPServer.a(DDRange.o)
     <snip>/CouchbaseLiteListener.framework/CouchbaseLiteListener(DDRange.o)

    duplicate symbol _DDStringFromRange in:
    <snip>-CocoaHTTPServer.a(DDRange.o)
    <snip>/CouchbaseLiteListener.framework/CouchbaseLiteListener(DDRange.o)

    duplicate symbol _DDRangeFromString in:
    <snip>-CocoaHTTPServer.a(DDRange.o)
    <snip>/CouchbaseLiteListener.framework/CouchbaseLiteListener(DDRange.o)

    duplicate symbol _DDRangeCompare in:
    <snip>-CocoaHTTPServer.a(DDRange.o)
    <snip>/CouchbaseLiteListener.framework/CouchbaseLiteListener(DDRange.o)

I've noticed that you've done some other work in this area (see #758, 712a81f6450d1ec44b00650de00ed0f61a38e912, etc), so hopefully this won't be too bothersome.  @pasin's commits helped (I had more of these errors before incorporating those changes), so I suspect I'm having a genuine issue and not just suffering from the ongoing effects of my own stupidity.

FWIW, I had C Flags to rename these symbols (See #325, #260), but they no longer worked.  I'm not sure why.  Perhaps because of the acrobatics I'm doing with the other library I'm using (RoutingHTTPServer) that incorporates CocoaHTTPServer.  Maybe shifting from a traditional Xcode workflow to using Cocoapods made those flags useless.

Sorry for the aggravation, and thanks for your time.

**Comment by pasin** [comment]
@ndouglas , could you try to rename those duplicate symbols in https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CouchbaseLitePrefix.h and rebuild both couchbase-lite-ios and couchbase-lite-listener binary? 

If it works, could you also submit a PR?

**Comment by ndouglas** [comment]
Absolutely.
