### ISSUE TITLE
Option to config and send log output to SG

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-ios#881]
Enable remotely configurable logging by sending a special _logging config doc, which can define logging policy including the option to periodically replicate log data back up to SG (e.g. as an attachment, or blocked into n docs as KV data).

**Comment by snej** [comment]
I'm writing up a [spec for the replication part](https://github.com/couchbaselabs/couchbase-lite-api/wiki/Log-and-Time-Series-Syncing).

**Comment by snej** [comment]
WIP on `feature/logging` branch.

**Comment by snej** [comment]
Added "chore" tag to prevent this from showing up in release notes, since there's no public API yet.
