### ISSUE TITLE
Get total number of rows in a paginated query

### ISSUE THREAD

**Issue by ajithrnayak** [couchbase/couchbase-lite-ios#884]
While implementing pagination, I was looking for a way to show a footer as **10 of 100 results shown**. 
i,e "**limit*page** of **total** results".

But when `-limit` is applied to query, the number of rows returned in the enumerator is ≤ limit. So, it would be useful to have an option to know total results; without needing to run query without `-limit` option by ourselves. 

Or, is this already made possible?

**Comment by snej** [comment]
There is a `CBLView.totalRows` property, which used to be internal but has recently been made public (#808). You can access it in CBL 1.1 by declaring it yourself:

```objc
@interface CBLView (NotPublicYet)
@property (readonly) NSUInteger totalRows;
@end
```

In CBL 1.1 the getter doesn't update the view index, so to be sure you get up-to-date results, call it after doing a query. In 1.2 it will update the index if necessary.

**Comment by snej** [comment]
`totalRows` won't help you if you want to query a key range, though. There's currently no workaround; you'd just have to do the entire non-paginated query. If that's your situation, let me know and I'll reopen.

**Comment by ajithrnayak** [comment]
That's awesome! It should help us to avoid few of reduce function based views; thank you :+1: 

But, I also have couple of filters. So, yes, I'm working with key ranges.

**Comment by ajithrnayak** [comment]
@snej  You said that you will re-open. Missed it? 

I'm also querying a key range and showing it as a paginated view. For now, I'm doing a non-paginated query to get just the total rows count.

**Comment by snej** [comment]
OK, reopened this to cover the need for something like a `CBLQuery.totalRows` property that computes the number of rows that would be returned. This will have to do some querying in the internal database, but it'll be cheaper than running the CBL query because it doesn't have to read the index values or allocate row objects.

**Comment by zgramana** [comment]
Given the existence of a workaround, we're putting this on the backlog for the moment.

**Comment by JesusTheHun** [comment]
Disintering this.
Having a query result envelop at the protocol level could bring unlimited amount of information.

A statement in the query could set the query metadata to retrieve : 

```
ENVELOP totalRows, queryTime, nodesQueriedCount
SELECT foo FROM bar
```

Then, using pseudo sdk code : 

```
resultEnvelop = query.execute();
result = resultEnvelop.getContent();
metadata = resultEnvelop.getMetadata();
```

Another solution, not as good but easier to implement, would be to allow to select those metadata through the `SELECT`statement itself.

```
SELECT QUERY().totalRows, queryTime, nodesQueriedCount, foo FROM bar
```

This would add unnecessary data to the returned result but it would be cheaper than another query.

**Comment by jayahariv** [comment]
Closing 1.x issue!
