### ISSUE TITLE
Cannot build with error: no member named 'hasPrefix' in 'forestdb::slice'

### ISSUE THREAD

**Issue by ufosky** [couchbase/couchbase-lite-ios#885]
When I run the unit test,the error generate,but just run the framework target has no error.
/Users/ufo/Documents/resp/couchbase-lite-ios/Source/CBL_ForestDBViewStorage.mm:94:33: error: no member named 'hasPrefix' in 'forestdb::slice'
        } else if (cppDoc.key().hasPrefix(slice("_design/"))) {
                   ~~~~~~~~~~~~ ^
1 error generated.

**Comment by pasin** [comment]
The CBForest submodule needs to be updated. Could you please update the submodule?

```
git submodule update --recursive
```
