### ISSUE TITLE
query.sortDescriptors doesn't gives expected result when '-limit' is applied.

### ISSUE THREAD

**Issue by ajithrnayak** [couchbase/couchbase-lite-ios#892]
Applying sortDescriptor and limit to query doesn't gives me expected result. 

From community group's [post][1]: @snej says, the offset/limit are being applied before the in-memory sorting, which gives the wrong results.

[1]:https://groups.google.com/d/msg/mobile-couchbase/kRMipQg8WRc/LxvIV4deLAAJ

**Comment by ajithrnayak** [comment]
Possible duplicate of  https://github.com/couchbase/couchbase-lite-ios/issues/889 but I'm not using `CBLQueryBuilder`.

**Comment by snej** [comment]
Yes, but there are at least two issues involved in #889 so I will leave this one open to cover this issue.
