### ISSUE TITLE
Couchbase Lite 1.1.0-31 LiveQuery Has All Rows And Document IDs But All Documents NULL

### ISSUE THREAD

**Issue by ColossalChris** [couchbase/couchbase-lite-ios#897]
I have loved using Couchbase in my iOS and Android projects to create Couch documents and replicate them to remote servers. Unfortunately I've run in to a bit of a snag recently since updating to the newest version of Couchbase Lite.

Before my most recent update, I would set up my manager and database and then call ``initializeQuery`` the following would have pulled all the docs from the db with their data intact where I could see the documentID and data in each doc (double checking the database I see all the docs are still there and they all have the key ``type`` set with a string): 

     - (void) initializeQuery {
         CBLQuery* query = [_database createAllDocumentsQuery];
         liveQuery = query.asLiveQuery;
         [liveQuery addObserver: self forKeyPath: @"rows" options: 0 context: NULL];
         [liveQuery start];
     }

     - (void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary *)change context:(void *)context{
         if (object == liveQuery) {
        
             CBLQueryEnumerator *result = liveQuery.rows;
        
             NSLog(@"No. 1 - number of rows is %lu", (unsigned long)result.count);
        
             for (CBLQueryRow *row in result) {
                  NSLog(@"No. 2 - what is each row's doc ID: %@", row.documentID);
                  NSLog(@"No. 3 - what is each row's document %@", row.document);
             }
         }
     }

Now (since updating to the newest Couchbase Lite) I still get the correct number of rows (on NSLog No. 1), and get all the right docIds (on NSLog No. 2) but each row's document is now ``(null)`` (on NSLog No. 3) and all keys/values do not exist. Can anyone explain to me if I need to change something to get my data to remain intact all the way to the end. If so a poor Idaho programmer will owe you a life debt! (Not worth much it is true, but it is all I have to give)

**Comment by snej** [comment]
Hm, that's very weird — I don't see anything wrong with your code, and from the implementation of `CBLQueryRow.document` it shouldn't be able to return nil if the `documentID` is non-nil.

By "newest Couchbase Lite" do you mean version 1.1, or are you building your own from the source code on the master branch?

**Comment by snej** [comment]
Ah, found it — you've run into issue #755, which was fixed just after we froze 1.1. :(

We're finishing up the 1.1.1 release, which includes the fix, and it should be out pretty soon. We have a continuous-build server you can download it from (I'll look up the URL) or you can build it yourself by checking out the release/1.1.1 branch.

**Comment by snej** [comment]
1.1.1 builds are [here](http://latestbuilds.hq.couchbase.com/couchbase-lite-ios/release/1.1.1/). That should fix your problem!
