### ISSUE TITLE
Create a JSON doc with empty key value can cause replication hang up

### ISSUE THREAD

**Issue by atom992** [couchbase/couchbase-lite-ios#906]
CBL version:1.1.0
Create a JSON by REST API like this:

curl -X PUT -H "Content-Type: application/json"  -d '{"key":"value","":"value2"}' 'http://127.0.0.1:59840/db/doc2'

return OK.

 It will cause replication hang up with sync gateway, see also sync gateway isssue 976:
https://github.com/couchbase/sync_gateway/issues/976

**Comment by snej** [comment]
The replication stops because Sync Gateway returns a fatal error (probably a 50x). That's correct behavior.

Fixing the bug in Sync Gateway will resolve the problem.

**Comment by atom992** [comment]
I think the CBL should be reject the PUT request with empty key value in body.

**Comment by snej** [comment]
Why? It's valid JSON. The only keys we reject are ones starting with an underscore, because those are reserved (like `_id`.)

**Comment by atom992** [comment]
It is valid, but meaningless.
