### ISSUE TITLE
Support for bitcode

### ISSUE THREAD

**Issue by jschmid** [couchbase/couchbase-lite-ios#911]
I am surprised that I'm the first one to notice this. Currently CBL does not support [bitcode](https://developer.apple.com/library/prerelease/watchos/documentation/IDEs/Conceptual/AppDistributionGuide/AppThinning/AppThinning.html).

I don't know what it means for CBL to support it. Has this been discussed already?

**Comment by snej** [comment]
I don't know either; I would guess that it's treated as a new CPU architecture in the build settings.

One reason our current builds don't support it is that only Xcode 7 has bitcode support, naturally, but we don't use beta versions of Xcode on our build machines.

**Comment by snej** [comment]
The only build setting I found is "Enable Bitcode" under "Build Options". It defaults to Yes. So I assume that bitcode will be generated if CBL/iOS is built on Xcode 7.

**Comment by jschmid** [comment]
For the record, I enabled Bitcode support in the CBL Xcode project and the compilation succeeded. 
I then used the compiled Framework in my app, which worked fine. 

Since every Framework must support Bitcode if you want to compile using this setting, I keep it off in my project. Waiting on this issue to be solved. (Not a pressing issue on my side)

**Comment by snej** [comment]
What setting(s) did you have to change?

**Comment by jschmid** [comment]
Only the "Enable Bitcode" boolean that you mentioned above.

**Comment by snej** [comment]
In which target(s)? It looked like it was already set to Yes by default.

**Comment by jschmid** [comment]
The "iOS framework" target.

**Comment by jschmid** [comment]
Sorry for the misleading information @snej. The setting is indeed set to Yes by default. I've got mixed up during my testing.

I guess that v1.2.0 will support Bitcode then :rocket:

**Comment by snej** [comment]
Easy fix, yay :)

**Comment by jschmid** [comment]
(Here is the related issue from the Couchbase folks #916 )
