### ISSUE TITLE
ASSERTION FAILED: CBLManager.storageType is 'ForestDB' but no CBL_ForestDBStorage class found

### ISSUE THREAD

**Issue by joshblour** [couchbase/couchbase-lite-ios#913]
Building from master (commit ad82b1b), i get the following error:
````
2015-09-15 11:50:31.112 proximator[66531:3747135] *** ASSERTION FAILED: CBLManager.storageType is 'ForestDB' but no CBL_ForestDBStorage class found, maybe add the -ObjC flag to Other Linker Flags in Build Settings
2015-09-15 11:50:31.112 proximator[66531:3747135] *** Assertion failure in -[CBLDatabase(Internal) open:](), /Users/Yonah/development/couchbase/couchbase-lite-ios/Source/CBLDatabase+Internal.m:159
````

I have -ObjC in 'Other Linker Flags'
<img width="1258" alt="screen shot 2015-09-15 at 11 45 24" src="https://cloud.githubusercontent.com/assets/1440796/9873446/26461848-5ba0-11e5-8f80-753c189c72a7.png">

Note: I didn't have this issue in my previous build (commit c857847)

**Comment by snej** [comment]
I don't think anything related to this has changed. Try using the `nm` tool on your Couchbase Lite framework binary to see if the Couchbase Lite_ForestDBStorage class is included in it.

**Comment by joshblour** [comment]
@snej I've run `nm -Au CouchbaseLite | grep Forest` from the CoucbaseLite.framework folder and got zero results. Was that the right command? I'm not familiar with the nm tool. I also deleted my copy of cbl, cloned again from master, and rebuild; same error

**Comment by joshblour** [comment]
I got a copy of the latest build from here: http://latestbuilds.hq.couchbase.com/couchbase-lite-ios/0.0.0/ios/0.0.0-525/ and it has the fix I needed (f38ef1e). Closing this issue. Unless you guys want to troubleshoot it, in which case I'm happy to help if there's anything you'd like me to try.

**Comment by snej** [comment]
The `-u` flag shows only _undefined_ symbols (imports), which is the opposite of what you want. Just `nm CouchbaseLite` without flags should be fine.

Which framework did you build? It should be "CBL iOS Framework".

**Comment by joshblour** [comment]
Ran `nm -A CouchbaseLite | grep Forest`; same result.

I built "Continuous iOS" (following https://github.com/couchbase/couchbase-lite-ios/wiki/Building-Couchbase-Lite)

I just tried archiving "CBL iOS Framework" but the xcarchive file was empty.

**Comment by snej** [comment]
Oops, I forgot that on iOS the ForestDB related code isn't in the static framework, but in libCBLForestDBStorage.a. You're building and linking that too, right?

**Comment by joshblour** [comment]
yep !

**Comment by snej** [comment]
Try `nm libCBLForestDBStorage.a | grep CBL_ForestDBStorage`

**Comment by joshblour** [comment]
Ok, `nm libCBLForestDBStorage.a | grep CBL_ForestDBStorage` gives me loads of results (https://gist.github.com/joshblour/5a6c9aac712215f77c24).

I tried running `nm proximator | grep CBL_ForestDBStorage` on my application binary. no results. Then I tried `nm proximator | grep CBL` and `nm proximator | grep Forest`. Also no results.

**Comment by snej** [comment]
Possibilities:

* libCBLForestDBStorage.a doesn't include a binary for the architecture you're running the app on. I believe nm can be told to look at a specific architecture only. If not, otool can.
* Somehow your app isn't linking that library anymore.
* Somehow your -ObjC build flag got removed.

Are you running `nm` on a debug or release build of your binary? A release build will have most or all symbols stripped out of it, depending on your build settings. You can tell the linker to create a link-map file that will list where all the symbols are.
