### ISSUE TITLE
Version 1.1.1 date

### ISSUE THREAD

**Issue by desarrollospyro** [couchbase/couchbase-lite-ios#914]
Hi,
When is going to be 1.1.1 version released?
Thanks.

**Comment by snej** [comment]
Please don't use the issue tracker to ask questions (it says that in our contributor guidelines.) You can ask this question on the developer forums or the Google group.

**Comment by snej** [comment]
(Also, I don't know the answer to the question. Our project manager does, and he can answer it on the forum.)
