### ISSUE TITLE
Re-release 1.1.1 built with Xcode 7, for bitcode support

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#916]
Developers releasing iOS 9 compatible versions of iOS apps will need to submit their apps with bitcode enabled. That means they need a version of Couchbase Lite that includes a bitcode binary. This happens by default if we build with Xcode 7, but of course not with Xcode 6.4.

We will need to upgrade our build machines to Xcode 7 as soon as the official GM build is out, and then re-build and release 1.1.1 (maybe call it 1.1.2 to avoid confusion?)

**Comment by zgramana** [comment]
Let's call it 1.1.1.1.

**Comment by snej** [comment]
Xcode 7 has been released now, so we can update the builders at any time. (And re-QA of course.)

**Comment by snej** [comment]
Developers who need this: Anyone submitting apps for iOS or watchOS.

How they know they need this: Build errors, probably at the time they're running the Archive command or preparing the archive for submission, complaining that not all of the application code contains bitcode.

**Comment by davidquon** [comment]
The build error happens when building for the device (not simulator) unless bitcode is disabled for the project.  Thanks for the prompt attention @snej.  :+1:

**Comment by pellekrogholt** [comment]
@snej in the maintime what is your suggestion about a solution when using `couchbase-lite-ios` and cocoa pods:

I naively tried to set the bitcode in `couchbase-lite-ios/CouchbaseLite.xcodeproj/project.pbxproj` in a forked branch and then include it in my Podfile:

    pod 'couchbase-lite-ios', :git => 'https://github.com/pellekrogholt/couchbase-lite-ios.git', :branch => 'hotfix-release-1.1.1/enable-bitcode'

but after a pod install my project couldn't 

    #import <CouchbaseLite/CouchbaseLite.h>

any suggestions?

**Comment by snej** [comment]
Sorry, I don’t really know anything about CocoaPods. You’re better off asking questions on the mailing list or the web forum.

**Comment by pellekrogholt** [comment]
@snej fair enough thx

**Comment by pasin** [comment]
The way our CocoaPods works now is pointing to the release zip file. We haven't had a chance to try to make the CocoaPods to build from the source yet.

**Comment by snej** [comment]
Filed in Jira as https://issues.couchbase.com/browse/CBLT-384 (assigned to Michael Kwok)

**Comment by snej** [comment]
This turns out to be harder than I thought – "all we need to do is build with Xcode 7, and the binary will automatically include bitcode" turns out to be untrue. :(

What I've found is that the binaries directly built by Xcode have bitcode, but when our build script calls `lipo` to pack the device and simulator binaries into a single file, for some reason the bitcode is removed. I have no idea why lipo does this, and the tool has very few command-line options so I don't think there's a way to prevent it. I'll need to find some alternate way to generate the fat library.

**Comment by snej** [comment]
@borrrden pointed me at a [StackOverflow thread](http://stackoverflow.com/questions/31233395/ios-library-to-bitcode) describing the command-line Clang flags for bitcode generation. Apparently in a regular build Xcode just outputs a placeholder/blank bitcode section; the real bitcode is only generated for an archive build. That may explain why the bitcode got lost during the lipo operation: maybe it was empty anyway?

**Comment by snej** [comment]
For future reference, here's how to check whether a binary contains bitcode:
```
otool -arch armv7 -l CouchbaseLite.framework/CouchbaseLite | grep __LLVM
otool -arch arm64 -l CouchbaseLite.framework/CouchbaseLite | grep __LLVM
```
I just verified that using the Archive command in Xcode 7.1b3 produces a framework that contains bitcode. Whew.

**Comment by snej** [comment]
A regular Release build (via Product > Build For > Profiling) also produces a binary with bitcode, i.e. `Release-ios-universal/CouchbaseLite.framework/CouchbaseLite`. That I believe is what our build bot does, so our releases should be good.

I guess my comment from last week was a false alarm — I think the `otool` check that I found today (on SO) is better than the one I was using before.

Since there's nothing further to do, other than upgrade the build bots to Xcode 7, I'm going to close this.

**Comment by iyepes** [comment]
I'm still having this issue with cocoa pods 1.1.1 Are the build bots upgraded yet?

**Comment by snej** [comment]
You'll have to [build it yourself](https://github.com/couchbase/couchbase-lite-ios/wiki/Building-Couchbase-Lite), sorry! Check out branch `release/1.1.1`.
