### ISSUE TITLE
CBL returns NO with no error when attempting to encrypt an SQLite database

### ISSUE THREAD

**Issue by brendand** [couchbase/couchbase-lite-ios#917]
Built from master using commit ad82b1b94887df639034baf3dfaa1812508fd60a on Mac OS X 10.11. Using SQLCipher 3.3.0 from cocoa pods.

I am unable to encrypt an SQLite store. ForestDB stores encrypt correctly.

A sample app to demonstrate was emailed to Jens.

Providing a screenshot to show the results of calling changeEncryptionKey. It returns NO, but provides no error. I have a valid CBLDatabase instance.

<img width="886" alt="screen shot 2015-09-18 at 7 09 37 pm" src="https://cloud.githubusercontent.com/assets/586075/9973880/dda28428-5e38-11e5-96b2-7dae329f6caf.png">

**Comment by brendand** [comment]
I'm not sure why, but now I am unable to encrypt ForestDB databases either. I'm currently using the latest  commit ebef00859f51431b38ee7177a257476ce5e4a1fe now.

On my app I'm receiving the following error:

```
13:28:32.362‖ WARNING: ForestDB error: FORESTDB ERROR -3
2015-09-27 13:28:40.308 Tap Forms[32167:1745617] Error encrypting: Error Domain=CBLHTTP Code=404 "404 not_found" UserInfo={NSLocalizedFailureReason=not_found, NSLocalizedDescription=404 not_found}
```

I'm not sure why it's not able to find the database during encryption since I can open the database and read from it fine.

However, with my sample test app which I sent to Jens a while back, I still just get no error, even trying to encrypt a ForestDB database, despite the fact that the result is NO when returning from changeEncryptionKey.

**Comment by snej** [comment]
Sorry, it turned out that enabling auto-compact in ForestDB (ebef008) broke my encryption hooks. I'll back it out until my fix is ready.

**Comment by brendand** [comment]
Ok, no worries. At least I know I'm not going insane now :-)

**Comment by snej** [comment]
I also just fixed #930, which might well have been causing errors re-keying, although as far as I can tell you'd have gotten a non-nil NSError.

**Comment by brendand** [comment]
I just updated to the latest code, but I get the following error when I want to re-open a ForestDB database:

    /**
     * Open a file with invalid compaction mode.
     */
    FDB_RESULT_INVALID_COMPACTION_MODE = -22,

    15:04:01.439| WARNING: ForestDB error: FORESTDB ERROR -22
    2015-09-30 15:04:01.439 Tap Forms[45491:1231992] Error opening Tap Forms database: Error Domain=CBLHTTP Code=500 "500 Database error!" UserInfo={NSLocalizedFailureReason=Database error!, NSLocalizedDescription=500 Database error!}

If I revert to the previous build, I can open the file again.

However, I can open an SQLite file and when I encrypt, I am now getting this error:

    Error encrypting: Error Domain=CBLHTTP Code=501 "501 unimplemented" UserInfo={NSLocalizedFailureReason=unimplemented, NSLocalizedDescription=501 unimplemented}

Which leads me to believe that even though I have SQLCipher in my Podspec, Couchbase is not using it for some reason.

And from my log file, it says it's using this version:

    Couchbase Lite using SQLite version 3.8.10.2 (2015-05-20 18:17:19 2ef4f3a5b1d1d0c4338f8243d40a2452cc1f7fe4)

I'm going to dig into this some more. I know that my app is definitely using SQLCipher because I can migrate an old encrypted database file to Couchbase just fine. I just checked again to verify and yes, it is reading my old SQCipher encrypted database just fine.

**Comment by snej** [comment]
The `FDB_RESULT_INVALID_COMPACTION_MODE` error might be because you ran with the previous commit that was enabling auto-commit, and now you're back to not using it? But I didn't think it caused a persistent change in the file. I'll take a look.

Re. SQLite — Since you're on Mac OS, Couchbase Lite is a dynamic library, which itself links against the system SQLite library. Even if you change your app to link SQLCipher, that doesn't affect what CBL uses. You'll have to modify the `CBL Mac` target to link with SQLCipher, then rebuild. (On the plus side, this explains why you were getting the NO result with a nil error — that's the bug I fixed in ddf987b. It happened when the storage system found it had no encryption support.)

**Comment by brendand** [comment]
So I was using SQLCipher 3.3.0 which had a slightly older version of SQLite (version 3.8.8.3). I've just updated to SQLCipher 3.3.1 which has 3.8.10.2. I guess Apple was a head with the system version of SQLite than SQLCipher was. I'm using OS X 10.11.1 beta 2 now.

Excellent. I'm glad you were able to get an error message displayed now. It helps you and me.

I'll link to SQLCipher inside CBL Mac then.

I'm guessing I can't just add it to a Podfile, eh? (yes, I'm Canadian) :-)

**Comment by brendand** [comment]
Hmm... so does that actually mean that I'll be embedding SQLite twice in my app? Once with SQLCipher and once with Couchbase Lite? Can CBL be told to use the one I'm already linking with? Or maybe if I get it embedded within Couchbase Lite I can remove it from my Podspec and my app will still use SQLCipher, but the one embedded in CBL. Not sure.

**Comment by snej** [comment]
If you build SQLCipher as a dylib, you can have both CBL and your app link against it. I have no idea how that interacts with CocoaPods, because I've never used it...

**Comment by snej** [comment]
Also, there is some command-line tool in the OS that can edit the imports of dylibs. You might be able to use that to tell the regular CBL framework to link against your SQLCipher dylib. I can't remember the name of the tool, though...

**Comment by snej** [comment]
`install_name_tool` ... check the man page.

**Comment by brendand** [comment]
As for `FDB_RESULT_INVALID_COMPACTION_MODE` I didn't explicitly set that. It was I guess just the default from the previous build. It's no big deal. I can just delete that database file and create a new one with the current build.

**Comment by brendand** [comment]
Thanks for the tips. I'll get on that.

**Comment by snej** [comment]
Gonna close this issue since we now know what the NO-and-nil problem was caused by. Thanks for noticing (I found the fix while inspecting the code trying to find some way that it could return NO without setting *error.)

**Comment by brendand** [comment]
Excellent. Also ForestDB encryption works fine now too again.

**Comment by snej** [comment]
FYI, I recommend updating from the master branch again — I fixed a regression that was making it impossible to _re_-open a ForestDB-backed database.

**Comment by brendand** [comment]
Will do. Thanks.

**Comment by brendand** [comment]
I have not been able to compile SQLCipher into CBL at all. I've got a static library built for Mac which I linked to CBL, but I get 3 duplicate symbol errors for arch x86_64. I tried using your pre-built OS X build too, but I got the same errors as when I compiled SQLCipher from the latest source myself. 

Not sure if I should open new issue for this or post it on the forum, or continue here. Sorry if I'm not supposed to post here for this bit.

```
duplicate symbol _sqlite3_free in:
    /Users/brendan/Projects/xcode-build/CouchbaseLite-dkzxjlgugdkowifscppurssdgkjh/Build/Products/Debug/libCBForest.a(libCBForest.a-x86_64-master.o)
    /Users/brendan/Projects/iPhone/couchbase-lite-ios/vendor/libsqlcipher-macos-2.a(sqlite3.o)
duplicate symbol _sqlite3_malloc in:
    /Users/brendan/Projects/xcode-build/CouchbaseLite-dkzxjlgugdkowifscppurssdgkjh/Build/Products/Debug/libCBForest.a(libCBForest.a-x86_64-master.o)
    /Users/brendan/Projects/iPhone/couchbase-lite-ios/vendor/libsqlcipher-macos-2.a(sqlite3.o)
duplicate symbol _sqlite3_realloc in:
    /Users/brendan/Projects/xcode-build/CouchbaseLite-dkzxjlgugdkowifscppurssdgkjh/Build/Products/Debug/libCBForest.a(libCBForest.a-x86_64-master.o)
    /Users/brendan/Projects/iPhone/couchbase-lite-ios/vendor/libsqlcipher-macos-2.a(sqlite3.o)
ld: 3 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm not sure how to compile SQLCipher as a dylib, so I've been trying with the static library rather than that `install_name_tool` command.

How do you have SQLCipher linked into CBL?

**Comment by snej** [comment]
This is a different thing and really should be filed as a new issue.

ForestDB includes a component that's normally a sqlite plugin, so it defines a couple of sqlite symbols so that plugin can link. You're going to have to build sqlcipher as a dylib to avoid these link errors, sorry.
