### ISSUE TITLE
Build for tvOS (AppleTV)

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#918]
We should have a build of Couchbase Lite for tvOS (AppleTV).

- [x] Fix build errors — there are some deprecation warnings.
- [x] Set up targets to build a framework that can be used with simulator and device, as with iOS

**Comment by brendand** [comment]
I'm curious about this. If there's no storage space available on Apple TV, how is running Couchbase Lite going to work? It was my understanding that you could only use CloudKit or iCloud for storage.

**Comment by snej** [comment]
It appears that you _can_ write to local storage, although only to your app sandbox's `Caches` directory. The data you write there may be deleted at any time after the app quits; from the info I've found, it will currently happen if the device is rebooted, or if storage starts to get full.

**Comment by snej** [comment]
The unit we got has about 26GB of free space on it, so they've got to be planning on developers putting _something_ on it...

**Comment by brendand** [comment]
I just figured the storage was for movies/music/app binaries. It would be cool though. I would love to build an Apple TV version of my Tap Forms Organizer app, possibly just as a dashboard service of some sort. Obviously not good for data entry, but great for displaying aggregate data.

**Comment by snej** [comment]
This is basically done; I just haven't been able to get the unit tests to build yet. It's in the branch `release/1.1.1_appleTV`.

**Comment by cflorion** [comment]
Cooool ! :)

One question, you managed to build, but did you manage to run a sample on the device ?
Thanks! Can't wait to try that out :)

**Comment by snej** [comment]
I love you guys' enthusiasm, but post it on the mailing list instead! :smiley_cat:  It's kind of getting in the way of the progress info in this issue report.

**Comment by snej** [comment]
For the sake of completeness I'll add status info that I posted to the mailing list last week:

* For development purposes, you can use the iOS Couchbase Lite framework in tvOS apps, since tvOS is mostly the same as iOS. But you’ll get a linker warning complaining that it’s not a “real” tvOS binary. In the near future we’ll release a build that’s been officially compiled for tvOS.
* AppleTV apps cannot write to the Application Support directory, only the Caches directory. You’ll need to instantiate the CBLManager with a custom path pointing to that directory, otherwise it’ll fail when trying to create a database. (In the upcoming official build, I’m putting in an #ifdef to have CBLManager default to the Caches directory.)
* Good news: the Caches directory seems more persistent than Apple’s docs imply. I’ve run a simple app that creates a database there, and the database persists across app launches and across device restarts. I suspect it will get dumped when storage fills up, but I haven’t tested this yet.

**Comment by snej** [comment]
Filed an internal Jira ticket to get the build set up: https://issues.couchbase.com/browse/CBLT-385

**Comment by cflorion** [comment]
Hmm strange, I tried to compile it in order to get the Framework (I used the target CBL tvOS Empty App) but the compile fails since I'm missing CBForect submodule. When I update the submodules I get this message:

```
fatal: reference is not a tree: 1a1fbf9aa8d80031db2e7f773689b58d77ac984e
Unable to checkout '1a1fbf9aa8d80031db2e7f773689b58d77ac984e' in submodule path 'vendor/CBForest'
```

Is it working for you ?
Thanks ;)

**Comment by snej** [comment]
Sorry about that — I made a change to CBForest but hadn’t pushed it to Github. Please try again and it should work now.

**Comment by snej** [comment]
Working on this again. I got the "CBL tvOS Empty App" target to run, and got the unit tests to build too. The tests pass on the simulator but fail on the device, and I'm looking at the failures, which are very very strange.

**Comment by cflorion** [comment]
Just so you know, I haven't tried the unit tests, but I tried it with my tvOS app and it's working like a charm :)
I did that in 2 minutes to I haven't look and logs or warnings, I'll do that and will tell you.
Thanks!

**Comment by SebastianBO** [comment]
Got our Apple TV some days ago, thanks @snej and @cflorion @brendand ..success here too :+1:

**Comment by snej** [comment]
The test failures turned out to be a known issue in 1.1.1 (we had them on iOS too, but for various reasons they weren't fixed.)

I've updated the `release/1.1.1-appletv` branch with the fixes to make the unit tests work. I also made some trivial changes to the [Building Couchbase Lite](https://github.com/couchbase/couchbase-lite-ios/wiki/Building-Couchbase-Lite) wiki page, mostly just to note that tvOS is supported and name the target to build.

**Comment by snej** [comment]
Next step is for @michaelkwok to add a builder for this. One obstacle is that you need Xcode 7.1 to build for tvOS, and that's still in beta, so they may want to hold off until it's GA.

**Comment by michaelkwok** [comment]
I will keep an eye on this.  I am in the process of bringing up a new build server for Xcode 7.

**Comment by snej** [comment]
Ship date for the Apple TV is "late October", and the GA of Xcode 7.1 should be about a week before that to give developers time to rebuild with it and submit their apps. So I'd start expecting it anytime starting about a week from now...

**Comment by snej** [comment]
The GA of Xcode 7.1 was released yesterday. It can be downloaded/updated via the Mac App Store.

**Comment by amg1976** [comment]
Hi guys.

Tried to compile the framework based on these instructions (https://github.com/couchbase/couchbase-lite-ios/wiki/Building-Couchbase-Lite) and it worked. 

But when trying to use it inside the app, I'm getting a lot of errors:
[couchbase-errors.txt](https://github.com/couchbase/couchbase-lite-ios/files/52230/couchbase-errors.txt)

Can you help me?

Thanks.

**Comment by amg1976** [comment]
Fixed by adding -lstdc++ in Other Linker Flags.

**Comment by snej** [comment]
Or you can add libstdc++ to the Link With Libraries section of the Build Phases.
