### ISSUE TITLE
CBLQueryBuilder: Sorted property disappears from _valueTemplate (select)

### ISSUE THREAD

**Issue by 24601** [couchbase/couchbase-lite-ios#921]
Assuming a CBLQueryBuilder like so:

self.vtEdgeQueryBuilder = try CBLQueryBuilder.init(database: self.cblDatabase, select: ["_id","label","tags","leftId","rightId","matchData","data","metaData","displayPriority"], `where`: "_id LIKE $PERSONID AND type LIKE 'VTEdge'", orderBy: ["-label"]);

The select (_valueTemplate) at runtime does NOT include the "label" property, it is simply omitted, resulting in array that is of length 7, not length 8. 

Removing it from the orderBy restores expected functionality (e.g. it is selected and in the _valueTemplate):

self.vtEdgeQueryBuilder = try CBLQueryBuilder.init(database: self.cblDatabase, select: ["_id","label","tags","leftId","rightId","matchData","data","metaData","displayPriority"], `where`: "_id LIKE $PERSONID AND type LIKE 'VTEdge'", orderBy: []);

This previously worked, as recently as July, I've looked at changes since then and can't seem to find anything that would seem to break this except possibly the code changes where keyPredicates are removed from _valueTemplate.

This behavior still does not appear to make sense to me in that just because I am sorting on a value does not mean I don't necessarily want it in my _valueTemplate, in fact, it's probably all the more probable I would.

**Comment by snej** [comment]
The reason that values found in the key are removed from the value is to reduce the size of the index: putting the same data in both the key and value is redundant.

On the other hand, you're right that it's unexpected. It means that, to find the moved value, you have to have knowledge of how the query was transformed.

I'll take out the code that removes the redundant values.

**Comment by 24601** [comment]
Thank you, @snej , professional, succinct, and well explained and executed as usual!
