### ISSUE TITLE
Puller shouldn't get attachments interleaved with docs

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#923]
As discussed in couchbase/sync_gateway#1163, the `_bulk_get` response can be compressed more efficiently if it contains only JSON doc bodies, not attachments. This would require CBL to send the request without `?attachments=true`, then look at the attachment metadata and send separate requests for the attachments.

This actually ties in well with lazy attachment downloading, which is like the above except that it doesn't request the attachments until the app asks. So we already have most of the machinery we need to do this, including queueing up the attachment requests.

**Comment by jayahariv** [comment]
Closing 1.x issue!
