### ISSUE TITLE
Slow creation/update of some records in DB

### ISSUE THREAD

**Issue by Danyaga** [couchbase/couchbase-lite-ios#924]
I wrote a method to exec a creation of records from a given NSArray, that contains some NSDictionaries (they come from a JSON obtained via REST APIs).

This method is able to handle the case where this record is already in the DB, and in this case exec an "update" with new versions of properties.

Basically my the issue is this operation is a bit slow and uses a lot of CPU time to be completed for the common size of said array (about 30 dictionary objects with more or less 10 properties).

Here my code:
```ObjectiveC
- (BOOL)saveExeciseTemplateDictionaries:(NSArray *) exerciseTemplateDictionaries{
    
    NSDate *startDate = [NSDate date];
    
    // create an object that contains data for the new document
    
    NSArray *exerciseTemplates = [exerciseTemplateDictionaries copy];
    
    BOOL success = [[self getDatabase] inTransaction:^BOOL{
        NSError *error;
        
        BOOL success = true;
        
        DDLogInfo(@"creating or updating %lu exerciseTemplates", (unsigned long)[exerciseTemplates count]);
        
        for (NSDictionary *orig_dic in exerciseTemplates) {
            NSMutableDictionary *dic = [orig_dic mutableCopy];
            
            // Save the ID of the new document
            NSString *docID = [[dic objectForKey:@"id"] copy];
           
            // Create an empty document
            CBLDocument *doc = [[self getDatabase] documentWithID:docID];
            
            // Write the document to the database
            if(dic && doc){
                //DDLogInfo(@"Saving ID = %@...", docID);
                
                CBLRevision *newRevision = [doc putProperties: dic error:&error];
                
                if (error) {
                    DDLogInfo(@"Document NOT created, error = %@", error.localizedDescription);
                    
                    //if this exerciseTemplate is already in DB, then update it
                    if (error.code == 409) {
                        success = success && [self updateExerciseTemplate:dic];
                    } else {
                        success = success && false;
                    }
                } else if (newRevision) {
                    DDLogInfo(@"Document created and written to database, ID = %@", docID);
                    
                    success = success && true;
                }
            }
        }
        
        return success;
    }];
    
    
    NSDate *endDate = [NSDate date];
    NSTimeInterval jobTime = [endDate timeIntervalSinceDate:startDate];
    
    DDLogInfo(@"updated done in %.0f s", jobTime);
    
    return success;
}

- (BOOL) updateExerciseTemplate:(NSDictionary *) exerciseTemplateDic{
    
    NSDate *startDate = [NSDate date];
    
    NSError *error;
    
    NSString *docID = [[exerciseTemplateDic objectForKey:@"id"] copy];
    
    // retrieve the document from the database
    CBLDocument *getDocument = [[self getDatabase] documentWithID:docID];    
    
    CBLSavedRevision* newRev = [getDocument update:^BOOL(CBLUnsavedRevision *rev) {
        // Toggle the "check" property of the new revision to be saved:

        for (NSString *key in [rev.properties allKeys]) {
            if ([exerciseTemplateDic objectForKey:key]) {
                if (![rev[key] isEqual:key]) {
                    rev[key] = [exerciseTemplateDic objectForKey:key];
                }
            } else {
                //just skip all nill properties (they are the DB's ones, like _id and _rev)
            }
        }
        
        return YES;
    } error: &error];
    
    
    if (!newRev) {
        DDLogInfo(@"current exerciseTemplate NOT UPDATED");
        
        return NO;
    }
    
    NSDate *endDate = [NSDate date];
    NSTimeInterval jobTime = [endDate timeIntervalSinceDate:startDate];
    
    // display the new revision of the document
    DDLogInfo(@"current exerciseTemplate UPDATED in %f s", jobTime);
    return YES;
    
}
`````````

With Instruments i noticed that the hard work for CPU is due to the subsequent operation done by DB and not direct the methods i coded. In particular the method that generates a lot work is [CBLDatabse(Internal) postChangeNotification].

My question: Is there a better way to do this operation? Is provided another strategy to handle a bulk creation?

**Comment by snej** [comment]
Your code looks reasonable from a performance standpoint. (You're overwriting the document with the incoming dictionary, which is going to blow away any changes that were made locally and make conflict handling impossible, but I assume you know about that and it works for your app.)

>In particular the method that generates a lot work is [CBLDatabse(Internal) postChangeNotification].

I haven't seen this as a hot spot in the benchmarking I've done. Is it possible the time is being taken up by your application's methods that observe this notification? Can you show some samples or Instruments profile output that show where the time is going?

(Also, what version are you using?)

**Comment by Danyaga** [comment]
I'm currently using 1.1.0. I know that there is at least one newer version available, but in this stage of development of our major update I'm not able to update it. We are planning a minor version after this big release to fix minor aspects like this one.

Just for give you a more complete idea of our architecture of this method usage: I have a NSOperationQueue (a main thread queue) that does the following operations:
* show a loading window;
* call method to exec the API call to get the said JSON
* in the completation block allocs (and insert in same queue) new operation that: call the method above with JSON as parameter, remove the loading window and go to new view controller.

All this operation has as dependency the previous operation.

As a temporally solution, I lowered a lot the impact (about 20%) the CPU usage by using a background queue to headle the operations that not involve UI (like the DB call). 

I'll provide you a Instruments file as requested in next few days.

**Comment by snej** [comment]
Are you handling the threading correctly? Couchbase Lite isn't thread-safe, so any CBLManager instance and the objects it creates can only be called from a single thread or dispatch queue.

**Comment by Danyaga** [comment]
I have red about it in your knowledge base, so I decided firstly to exec all operations above in main thread (as all other calls to DB we do in our app). But for this performance issue in this bulk insertions I tried to move some operations, the ones that do not touch UI, in a background queue (I refer to alloc a NSOperationQueue in this way [[NSOperationQueue alloc] init] instead take it from main thread, in this way [NSOperationQueue mainQueue). All work fine at the moment, in particular with no differences at all compared to execute all in main thread, DB side (no exceptions raised, no issues in the collected data,…).

At the moment we are a little satisfied about the performance I get with this workaround (and some others I omitted because they are more higher level, like calling backend also in other moments to test if something have changed, or the system to calculate an hash of JSON to avoid the update of local DB in case no needed). 

Do you revise any problems by using this strategy? My first intent was know if I used your DB in the right way for this operation.

**Comment by snej** [comment]
It's fine as long as you create a separate CBLManager instance for the background queue, and on that queue use only that manager and objects derived from it (CBLDatabase, etc.) You also need to set the CBLManager's `dispatchQueue` property to the operation queue's `underlyingQueue`.

**Comment by zgramana** [comment]
@Danyaga were you able to resolve your issue?

**Comment by snej** [comment]
Any update? Are you still seeing slow performance?

**Comment by zgramana** [comment]
@danyaga closing this out. If it's not resolved, please reopen.
