### ISSUE TITLE
crash in processing CBLIS changes when document has no type

### ISSUE THREAD

**Issue by mastohhh** [couchbase/couchbase-lite-ios#925]
There's a crash in this method : 

```objc
- (void) processCouchbaseLiteChanges: (NSArray*)changes {
    NSMutableSet* changedEntitites = [NSMutableSet setWithCapacity: changes.count];
    NSMutableArray* deletedObjectIDs = [NSMutableArray array];
    NSMutableArray* updatedObjectIDs = [NSMutableArray array];

    for (CBLDatabaseChange* change in changes) {
        if (!change.isCurrentRevision) continue;
        if ([change.documentID hasPrefix: @"CBLIS"]) continue;

        CBLDocument* doc = [self.database documentWithID: change.documentID];
        CBLRevision* rev = [doc revisionWithID: change.revisionID];

        BOOL deleted = rev.isDeletion;

        NSDictionary* properties = [rev properties];

        NSString* type = [properties objectForKey: [self documentTypeKey]];
        NSString* reference = change.documentID;

        NSDictionary *entitiesByName = self.persistentStoreCoordinator.managedObjectModel.entitiesByName;
        NSEntityDescription* entity = entitiesByName[type];

        // CRASH : type is nil
        NSManagedObjectID* objectID = [self newObjectIDForEntity: entity referenceObject: reference];

        if (deleted) {
            [deletedObjectIDs addObject: objectID];
        } else {
            [updatedObjectIDs addObject: objectID];
        }

        [changedEntitites addObject: type];
    }

    [self informObservingManagedObjectContextsAboutUpdatedIDs: updatedObjectIDs
                                                   deletedIDs: deletedObjectIDs];
}
```

Here's the properties of the `CBLDocument` : 

```objc
{
    "_deleted" = 1;
    "_id" = "E2DDD307-58A1-4542-A36B-A5A15638C5CE-72886-000031E956FD1D7F";
    "_rev" = "2-f667ec1782f9606f43421cb41a2002f8";
}
```

Here's the response of the `sync_gateway` : 

```unix
curl http://x.x.x.x:4985/database/E2DDD307-58A1-4542-A36B-A5A15638C5CE-72886-000031E956FD1D7F
{"error":"not_found","reason":"deleted"}
```

My questions are : 
- Why do I receive an object without any `type` ?
- Is it a good solution to avoid the crash by checking `nil`value of this `type` ? Or the problem could be deeper ? (By this way, it doesn't answer why this document has no `type`.)
- Finally, what's the purpose of `changedEntitites` array ?

**Comment by pasin** [comment]
> Why do I receive an object without any type ?
I believe the when deleting the entity object, the type get removed. I will need evaluate if it needs to preserve the type property or not.

Is it a good solution to avoid the crash by checking nilvalue of this type ? Or the problem could be deeper ? (By this way, it doesn't answer why this document has no type.)
> I think maybe we don't need to get type at all. I will evaluate this.

Finally, what's the purpose of changedEntitites array ?
> I don't think it is getting used. Probably it's left off after refactoring the code. I will evaluate this and remove.

**Comment by pasin** [comment]
@mastohhh I believe you could delete the following 2 lines from -processCouchbaseLiteChanges:.

```Objective-C
NSMutableSet* changedEntitites = [NSMutableSet setWithCapacity: changes.count];
...
[changedEntitites addObject: type];
```

However I'm still wondering about missing 'type' property from the deleted revision. I would need more time to evaluate to make sure that CBLIS doesn't require 'type' of the deleted revision in the other parts of the code.

**Comment by mastohhh** [comment]
What are the ways to delete a document ? Except by deleting the `NSManagedObject` ...

For example, does the `conflictHandler` can delete a document ? Or Sync Gateway ? Or Couchbase Server ?

I don't know if it could be related but I have some test customers that complains about deleted objects that shouldn't be.

**Comment by pasin** [comment]
I have looked at this closely and the type property is for getting the entity object. When out the type property, the deleted object will not be notified. I don't see the default conflict deletes the type property. If the database is shared with other non CBLIS app, it is possible that the non CBLIS app deletes the document without preserving the type property.

I'm going the fix the crash issue first.
