### ISSUE TITLE
compression for _changes feed requests (continuous)

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#927]
CBLWebSocketChangeTracker doesn't support data compression because there's no built-in compression for the WebSocket protocol.

To enable compression we'd just need to
- [x] Define how to do the compression. Best would be to use the standard per-message-compression extension (see below).
- [x] Make the client request such compression.
- [x] Decode the compressed data in the WebSocket messages.
- [x] Plus of course implement compression on the Sync Gateway side.

Note: This only affects continuous pull replications. For non-continuous ones, see #926.

**Comment by snej** [comment]
There is a standard "[per-message compression](https://www.igvita.com/2013/11/27/configuring-and-optimizing-websocket-compression/)" WebSocket extension. IIRC, the PocketSocket library we use in CBL/iOS already supports it. However, I don't know if there is a Go implementation for SG to use.

**Comment by snej** [comment]
I couldn't find a Go WebSocket implementation with per-message compression. However, we can get basically the same effect by manually compressing every message, using the same gzip context (flushing the context at the end of each message.)

The client can distinguish compressed messages because they'll be binary, not strings.

To signal compatibility, the client will include `"Accept-Encoding":"json"` in the initial JSON message it sends with the feed parameters.

I've got this working on a branch. It of course required some small Sync Gateway changes to do the compression.

**Comment by robertjpayne** [comment]
@snej FWIW I'd advise merging in some of the changes I've done on PocketSocket's main repo. There was a critical flaw with the permessage-deflate implementation, particularly the stuff involved in this commit: https://github.com/zwopple/PocketSocket/commit/98445cd1c0adb20edde5e038018a166810d31ac9

It doesn't corrupt anything but without the fixes the websocket connection can drop unexpectingly

**Comment by snej** [comment]
Thanks for the advice. It might be tough to merge, though, since I made such extensive changes in my fork. (I was hoping you'd just pull my fork into yours, since I started from your last commit.)

**Comment by robertjpayne** [comment]
@snej I can do it for you :) I didn't pull the commits verbatim because there was a bit of things I wanted to tidy up and/or enhance the API of.
