### ISSUE TITLE
Replication with SSL and self signed certificate does not work

### ISSUE THREAD

**Issue by AlexDobrushin** [couchbase/couchbase-lite-ios#929]
Replicating with SSL URL with self signed certificate on the server gives me an error:

CBL_Pusher[https://here is my address]: SSL cert is not trustworthy (result=5)

Result=5 is kSecTrustResultRecoverableTrustFailure.

Yes, I added my certificate file from server in binary DER format to app and to AnchorCerts array, see code I am using below. 

    - (void) addSelfSignedCertificate{
          NSMutableArray *certs = [NSMutableArray array];
          NSString *resourcePath = [[[NSBundle mainBundle] resourcePath] stringByAppendingPathComponent:@"cert/server.cer"];
          if (resourcePath) {
                 NSData *certData = [NSData dataWithContentsOfFile:resourcePath];
                 SecCertificateRef cert = SecCertificateCreateWithData(NULL, (__bridge CFDataRef)certData);
                 if (cert) {
                          [certs addObject:CFBridgingRelease(cert)];
                         [CBLReplication setAnchorCerts:certs onlyThese:NO];
                 }
         }
    }

I asked the question in forum https://forums.couchbase.com/t/how-to-make-my-couchbasemobile-ios-app-use-ssl/3228, and it looks like an issue in code.

**Comment by snej** [comment]
@AlexDobrushin sent me a copy of the self-signed cert used in the test. I opened it with Keychain Access and saw that it expired in Feb 2014. I'm pretty sure SecTrust will not trust an expired cert even if it's given as a root, so this is probably the reason for the failed connection.

Alex, please retry with a cert that hasn't expired yet. If you still have the same problem, please post details here and I'll re-open the issue.
