### ISSUE TITLE
Manage NSPOSIXErrorDomain while replicate

### ISSUE THREAD

**Issue by desarrollospyro** [couchbase/couchbase-lite-ios#933]
We are using CouchbaseLite 1.1.1 feature and CouchDB 1.6.1. We have the next error log several times, not always, when we replicate a database. 
```
[1714:1631035] WARNING: CBLSocketChangeTracker[0x146640850 db_name]: Can't connect, giving up: Error Domain=NSPOSIXErrorDomain Code=54 "Connection reset by peer"
[1714:1631035] Replication: CBL_Puller[http://db_url/db_name] took 225.045 sec; error=Error Domain=NSPOSIXErrorDomain Code=54 "Connection reset by peer"
```
The app continue running but not CouchbaseLite and we can not do nothing. We want to manage this error or let to CouchbaseLite manage it and let the replication run.
Thanks in advance.

**Comment by snej** [comment]
Are you using a continuous or one-shot replication? If it's one-shot, then it's expected that the replication stops if it hits an error.

If it's a continuous replication, it shouldn't stop, but if it does you can just tell it to restart.

**Comment by zgramana** [comment]
@desarrollospyro any update?

**Comment by desarrollospyro** [comment]
We are using one-shot replication. Some errors stop the replication but another ones don't. When we have more traces we post here.
Thanks.

**Comment by snej** [comment]
Couchbase Lite is behaving correctly. A failure to open a socket to the server is a fatal error to a one-shot replication.
