### ISSUE TITLE
Database releaseReadLock exception

### ISSUE THREAD

**Issue by vfernandezg** [couchbase/couchbase-lite-ios#934]
Hi
Sometimes I'm getting the exception CBL_FMDatabase releaseReadLock in the method createDatabase of the CBLDatabase object (iOS Framework). This is the log that I was able to see in crashalytics:

Fatal Exception: NSInternalInconsistencyException
Too many calls to releaseReadLock

0 CoreFoundation 	__exceptionPreprocess
3 Foundation 	-[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]
4 KomandApp 	 -[CBL_FMDatabase releaseReadLock]
5 KomandApp 	 -[CBL_FMDatabase executeQuery:withArgumentsInArray:orVAList:]
6 KomandApp 	 -[CBL_FMDatabase(FMDatabaseAdditions) intForQuery:]
7 KomandApp 	 -[CBLDatabase(Internal) schemaVersion]
8 KomandApp 	 -[CBLDatabase(Internal) open:]
9 KomandApp 	 -[CBLManager databaseNamed:error:]
10 KomandApp HCAppDelegate.m line 1193 -[HCAppDelegate createTheDatabase]
11 KomandApp HCAppDelegate.m line 136 -[HCAppDelegate application:didFinishLaunchingWithOptions:]

**Comment by vfernandezg** [comment]
Sorry I forgot to said that I'm using Couchbase Lite 1.0.4

**Comment by snej** [comment]
Can you try upgrading to 1.1? At this point 1.0.4 is pretty old (code freeze was last December.)

**Comment by snej** [comment]
Actually this looks like a bug in FMDatabase that was fixed by cdd2d90 just two months ago (which means it might be in 1.1.1, or might not be in any release yet.) Although that bug only happened when the query failed, and I wouldn't expect `-schemaVersion` to fail.

You could try cherry-picking commit cdd2d90 into the 1.0.4 branch — it's a very small change that isn't dependent on other stuff.

**Comment by vfernandezg** [comment]
I'm trying to generate the framework from the branch release/1.0.4-hotfix1 but I'm getting the error that said CollectionUtils.h file not found.

**Comment by snej** [comment]
`git submodule update --init --recursive`

**Comment by snej** [comment]
Let use know if the patch fixes it, and I can close this bug. Thanks.

**Comment by vfernandezg** [comment]
Yes, I've only seen the issue in the field so maybe I'm going to take a while in confirm if this solve the problem. Thanks!

**Comment by zgramana** [comment]
@vfernandezg let us know if 1.1.1 does not address this issue.
