### ISSUE TITLE
Syntax error attempting to encrypt using SQLCipher

### ISSUE THREAD

**Issue by brendand** [couchbase/couchbase-lite-ios#935]
Hi,

I've built SQLCipher as a dynamic library and removed the standard SQLite library reference from the CBL Mac target and put libsqlcipher.dylib in its place. I also added the requisite SQLCipher flags to the Other Objective C Flags build setting:

```
-DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4_UNICODE61 -DSQLITE_HAS_CODEC
```

I'm not convinced the SQLCipher library is being used though because when my app starts up, CBL outputs the following debug statement:

```
Couchbase Lite using SQLite version 3.8.10.2 (2015-05-20 18:17:19 2ef4f3a5b1d1d0c4338f8243d40a2452cc1f7fe4)
```

I built SQLCipher just now so the date should be today's date I would think. Unless I'm mistaken what the above log output is telling me. The version number is correct though.

When I attempt to encrypt, I get the following log output:

```
<CBL_FMDatabase: 0x6000000a7f80> executeUpdate: ATTACH DATABASE ? AS rekeyed_db KEY "x'00d156d86b3961ad722527c995cf190acedabba9f0096ad5d72aa772cf615f26'"
obj: /var/folders/gy/pdjjqyr88xg9gn001s6sl56h0000gn/T/com.tapzapp.tapforms-mac/-7NKwK3ulBth9bjIpA_broN
<CBL_FMDatabase: 0x6000000a7f80> executeUpdate: SELECT sqlcipher_export('rekeyed_db')
<CBL_FMDatabase: 0x6000000a7f80> executeQuery: PRAGMA user_version
<CBL_FMDatabase: 0x6000000a7f80> executeUpdate: PRAGMA rekeyed_db.user_version = ?
DB Error: 1 "near "?": syntax error"
DB Query: PRAGMA rekeyed_db.user_version = ?
*** Assertion failure in -[CBL_FMDatabase executeUpdate:error:withArgumentsInArray:orVAList:], /Users/brendan/Projects/iPhone/couchbase-lite-ios/vendor/fmdb/src/FMDatabase.m:776
DB Error: 1 "near "?": syntax error"
```

So I'm wondering if maybe I built SQLCipher wrong or if somehow CBL is using the built-in SQLite instead of the one from SQLCipher.

Any ideas on what to try next would be greatly appreciated. I tried following the instructions in the Wiki for including SQLCipher, but it talks about a static library and that doesn't work on OS X with CBL due to some naming conflicts.

Thanks,

Brendan

**Comment by snej** [comment]
Set the environment variable `DYLD_PRINT_LIBRARIES` and you'll get log output showing exactly which dynamic libraries are loaded and when.

**Comment by snej** [comment]
Maybe the SQL `PRAGMA` doesn't allow a `?` placeholder. Try replacing Couchbase Lite_SQLiteStorage.m lines 333-337 with:

```objc
            NSString* vers = $sprintf(@"PRAGMA rekeyed_db.user_version = %d", self.schemaVersion);
            return [self checkUpdate: [_fmdb executeUpdate:@"SELECT sqlcipher_export('rekeyed_db')"]
                               error: outError]
                && [self checkUpdate: [_fmdb executeUpdate: vers]
                               error: outError];
```
(I'd try this myself but we don't have a setup for unit testing with SQLCipher yet, so it involves a bunch of work to switch back and forth. If you can patch those lines in and let me know if they work, I'll commit them and owe you a beer or something :)

**Comment by brendand** [comment]
Bingo! That did it! Thanks Jen!

I've now successfully encrypted my Couchbase database with both ForestDB and SQLCipher. During development I prefer to use SQCipher since I have tools that make it easier to view the contents of the database. There's not much other than CouchbaseLite Viewer for ForestDB as far as I know. I suspect though that when I go to production I may decide to use ForestDB. Or at least give the user a choice perhaps.

No beers necessary Jens. Just really grateful for all the hard work you put into such an awesome product!

Brendan
