### ISSUE TITLE
Failure to decrypt SQLite database

### ISSUE THREAD

**Issue by brendand** [couchbase/couchbase-lite-ios#937]
When I decrypt my database, all the blobs are properly decrypted, but then the database is left encrypted with the following error displayed in the logs:

```
2015-10-05 15:04:43.702 Tap Forms[62882:6960460] DB Error: 26 "file is encrypted or is not a database"
2015-10-05 15:04:43.702 Tap Forms[62882:6960460] DB Query: SELECT count(*) FROM sqlite_master
2015-10-05 15:04:43.702 Tap Forms[62882:6960460] *** Assertion failure in -[CBL_FMDatabase executeQuery:withArgumentsInArray:orVAList:], /Users/brendan/Projects/iPhone/couchbase-lite-ios/vendor/fmdb/src/FMDatabase.m:635
DB Error: 26 "file is encrypted or is not a database"
15:07:00.700‖ WARNING: MYAction: Exception raised by step #3: DB Error: 26 "file is encrypted or is not a database"
15:07:00.700‖ WARNING: MYAction: Error cleaning up step #3: Error Domain=MYAction Code=1 "(null)" UserInfo={NSException=DB Error: 26 "file is encrypted or is not a database"}
```

Yet the result from calling:

`BOOL didDecrypt = [weakSelf.databaseDocument.couchDatabase changeEncryptionKey:nil error:&error];`

is that `didDecrypt` is YES.

The blob files are properly decrypted and the encryption file is gone from the attachments folder. But the db.sqlite file is still actually encrypted.

It stops on the following code before it returns from `changeEncryptionKey:error:` 

```
if (SQLITE_OK != rc) {
     if (logsErrors) {
         NSLog(@"DB Error: %d \"%@\"", [self lastErrorCode], [self lastErrorMessage]);
         NSLog(@"DB Query: %@", sql);
#ifndef NS_BLOCK_ASSERTIONS
         if (crashOnErrors) {
             NSAssert2(false, @"DB Error: %d \"%@\"", [self lastErrorCode], [self lastErrorMessage]);
         }
#endif
}
```
Specifically it stops on the NSAssert2() statement. That's line `635` in `FMDatabase.m`.
which is called from the following code in `CBL_SQLiteStorage.m`:
```
    // Verify that encryption key is correct (or db is unencrypted, if no key given):
    if ([_fmdb intForQuery:@"SELECT count(*) FROM sqlite_master"] == 0) {
        int err = _fmdb.lastErrorCode;
        if (err) {
            Warn(@"CBL_SQLiteStorage: database is unreadable (err %d)", err);
```
I'm guessing that lastErrorCode is not set or something because it's returning YES in that it successfully decrypted, but it didn't.

Just to verify it wasn't anything I was doing wrong in my code, I switched to ForestDB and it encrypted and decrypted correctly.

Thanks,

Brendan

**Comment by snej** [comment]
I've rebuilt with SQLCipher and can reproduce this. The existing DatabaseEncryption_Test tests pass, but the rekeying test only tries to change from one key to a different key. I added tests for adding encryption and removing encryption, and the remove-encryption test fails. As you said, the database file appears to still be encrypted.

**Comment by brendand** [comment]
Works like a charm! Case closed :-)

Thanks Jens! As far as I can tell the encryption story is now complete. Awesome!

**Comment by snej** [comment]
Whew! Thanks for your help. This is going to be one of the banner features of v1.2, so it's great to have the extra real-world testing.
