### ISSUE TITLE
Documentation/Infrastructure: Building Couchbase Lite behind a firewall 

### ISSUE THREAD

**Issue by ncoelle** [couchbase/couchbase-lite-ios#939]
The firewall of my office is blocking the _git:..._-URL. I had to change the protocol from _git:_ to _https:_. I did the following modifications as step 3 after checking out the code **before** performing `git submodule update --init --recursive`:

```bash
cd couchbase-lite-ios
grep -r 'git:' .
vim .gitmodules
git submodule update --init
grep -r 'git:' .
vim ./vendor/BLIP/.gitmodules
vim ./vendor/CBForest/.gitmodules
git submodule update --init --recursive
```

Solution proposal:
    a) Change the submodule definition from git: to https:
or
    b) Add a note to the documentation

**Comment by snej** [comment]
Unfortunately using Github with HTTPS is a pain. First you have to [configure a credential helper](https://help.github.com/articles/caching-your-github-password-in-git/) so you don't have to enter your username/password every time you push; then if you're using two-factor authentication you have to [create a special access token](https://help.github.com/articles/creating-an-access-token-for-command-line-use/) to use as the credentials. (I just spent ten minutes looking up these docs, after changing the `.gitmodules` files and then being unable to push.)

As you're the only person ever to report trouble with `git:` URLs (in the four years this repository and its predecessor have been around), I don't think it's worth making this change. Sorry!
