### ISSUE TITLE
CBLReplication: No local checkpoint; not getting remote one

### ISSUE THREAD

**Issue by brendand** [couchbase/couchbase-lite-ios#945]
Since the latest commit of CBL ( 74b90aa8d70a362aba53a35be9d2d6232a811a62 ), I seem to be getting a full replication between my Macs every time I trigger a pull request after having just opened up the database. After the initial large pull, subsequent pulls appear to behave normally until I close and re-open the database.

Here's some of the log output I'm seeing:

```
2015-10-09 03:03:12.229 Tap Forms[28341:626245] last seq: 17059
2015-10-09 03:03:12.229 Tap Forms[28341:626245] incoming seq: 17060

2015-10-09 03:03:12.229 Tap Forms[28341:626245] Pulling from peer:db-8cbd8e5030564754bdad8a304bb548cd@DefiantX9...
2015-10-09 03:03:12.229 Tap Forms[28341:626245] Peer went offline
03:03:12.229| Sync: CBLReplication[from http://DefiantX9.local.:51971/db-8cbd8e5030564754bdad8a304bb548cd]: offline, progress = 0 / 0, err: (null)
03:03:12.230‖ Sync: CBLRestPuller[http://DefiantX9.local.:51971/db-8cbd8e5030564754bdad8a304bb548cd] STARTING ...
03:03:12.247‖ Sync: CBLRestPuller[http://DefiantX9.local.:51971/db-8cbd8e5030564754bdad8a304bb548cd]: Going online
03:03:12.247‖ Sync: CBLRestPuller[http://DefiantX9.local.:51971/db-8cbd8e5030564754bdad8a304bb548cd]: No local checkpoint; not getting remote one
03:03:12.247‖ Sync: CBLRestPuller[http://DefiantX9.local.:51971/db-8cbd8e5030564754bdad8a304bb548cd] Progress: set active = 1
03:03:12.248‖ Sync: CBLReplication[from http://DefiantX9.local.:51971/db-8cbd8e5030564754bdad8a304bb548cd]: active, progress = 0 / 0, err: (null)
03:03:12.675‖ Sync: CBLRestPuller[http://DefiantX9.local.:51971/db-8cbd8e5030564754bdad8a304bb548cd] Progress: 0 / 100
03:03:12.688‖ Sync: CBLRestPuller[http://DefiantX9.local.:51971/db-8cbd8e5030564754bdad8a304bb548cd] Progress: 100 / 100
03:03:12.690‖ Sync: CBLRestPuller[http://DefiantX9.local.:51971/db-8cbd8e5030564754bdad8a304bb548cd] Progress: 100 / 200
03:03:12.703‖ Sync: CBLRestPuller[http://DefiantX9.local.:51971/db-8cbd8e5030564754bdad8a304bb548cd] Progress: 200 / 200
03:03:12.705‖ Sync: CBLRestPuller[http://DefiantX9.local.:51971/db-8cbd8e5030564754bdad8a304bb548cd] Progress: 200 / 300
03:03:12.718‖ Sync: CBLRestPuller[http://DefiantX9.local.:51971/db-8cbd8e5030564754bdad8a304bb548cd] Progress: 300 / 300

...

03:03:14.985‖ Sync: CBLRestPuller[http://DefiantX9.local.:51971/db-8cbd8e5030564754bdad8a304bb548cd] Progress: 16600 / 16700
03:03:14.999‖ Sync: CBLRestPuller[http://DefiantX9.local.:51971/db-8cbd8e5030564754bdad8a304bb548cd] Progress: 16700 / 16700
03:03:14.999‖ Sync: CBLReplication[from http://DefiantX9.local.:51971/db-8cbd8e5030564754bdad8a304bb548cd]: active, progress = 16700 / 16704, err: (null)
03:03:15.011‖ Sync: CBLRestPuller[http://DefiantX9.local.:51971/db-8cbd8e5030564754bdad8a304bb548cd]: Caught up with changes!
03:03:15.012‖ Sync: CBLRestPuller[http://DefiantX9.local.:51971/db-8cbd8e5030564754bdad8a304bb548cd]: ChangeTracker stopped; error=(null)
03:03:15.012‖ Sync: CBLRestPuller[http://DefiantX9.local.:51971/db-8cbd8e5030564754bdad8a304bb548cd] queued 1 remote revisions from seq=17060 (0 in bulk, 1 individually)
03:03:15.013‖ Sync: CBLReplication[from http://DefiantX9.local.:51971/db-8cbd8e5030564754bdad8a304bb548cd]: active, progress = 16703 / 16704, err: (null)
03:03:15.030‖ Sync: CBLRestPuller[http://DefiantX9.local.:51971/db-8cbd8e5030564754bdad8a304bb548cd] inserted 1 revs in 0.002 sec (409.8/sec)
03:03:15.030‖ Sync: CBLRestPuller[http://DefiantX9.local.:51971/db-8cbd8e5030564754bdad8a304bb548cd] Progress: set active = 0
03:03:15.030‖ Sync: CBLRestPuller[http://DefiantX9.local.:51971/db-8cbd8e5030564754bdad8a304bb548cd] STOPPED
03:03:15.030‖ Replication: CBLRestPuller[http://DefiantX9.local.:51971/db-8cbd8e5030564754bdad8a304bb548cd] took 2.783 sec; error=(null)
03:03:15.030‖ Sync: CBLRestPuller[http://DefiantX9.local.:51971/db-8cbd8e5030564754bdad8a304bb548cd] checkpointing sequence=17060
2015-10-09 03:03:15.030 Tap Forms[28341:627180] database updated: {
    changes =     (
        "CBLDatabaseChange[{rec-lib_inventory_1:2E93CD1C9D3F4C2F9726C1BBECA2423B #4-4d846d3ba80592f611c726df06a7d2f9}]"
    );
    external = 1;
}
03:03:15.031‖ Sync: CBLRestPuller[http://DefiantX9.local.:51971/db-8cbd8e5030564754bdad8a304bb548cd] Progress: 16704 / 16704
2015-10-09 03:03:15.031 Tap Forms[28341:627183] <PeerManager: 0x608000c94a00> Replication finished
03:03:15.033‖ Sync: CBLReplication[from http://DefiantX9.local.:51971/db-8cbd8e5030564754bdad8a304bb548cd]: stopped, progress = 16704 / 16704, err: (null)
03:03:36.384‖ WARNING: CBLHTTPConnection: Client disconnected: Error Domain=GCDAsyncSocketErrorDomain Code=4 "Read operation timed out" UserInfo={NSLocalizedDescription=Read operation timed out}
```

You can see at the top that last seq was 1759 and incoming seq was 1760. Only a single change was made on my other Mac. You can also see the one change in the "database updated" log message. But it pulled in the entire set of documents I believe. This seems to be a different behaviour than I was seeing with a previous build.

Is there something I need to make sure I'm doing now to make replication work only from the last checkpoint?

One thing that I am doing which I understood that commit 988ee30a3d15a96b4ebc84b95975434db8cd0df4 dealt with was to handle the case of pre-packaged databases. I don't have exactly this situation, but it's similar because the database on one Mac was copied to the other Mac and then I started replication. So the databases would have started out with the same checkpoint value.

This issue occurs every time I make a change to either of the copies of the database.

After I copy the database file over to my other machine, should I be calling replaceUUIDs on it to give it its own unique internal UUIDs? Perhaps that's what I'm missing?

Thanks,

Brendan

**Comment by brendand** [comment]
I should also mention that I'm doing peer to peer replication.

**Comment by snej** [comment]
This is a regression caused by 988ee30, "Don't fetch remote checkpoint if there's no local checkpoint" — see the log message `No local checkpoint; not getting remote one`. But I'm not sure why; that change should only trigger if the database has never replicated with that remote db before. After the first sync it'll save a checkpoint, then it'll work normally. (See the log message `checkpointing sequence=17060`.)

> the database on one Mac was copied to the other Mac and then I started replication.

This is _definitely_ problematic, because you've now got two databases with the same UUID. I don't think it's going to cause problems when two copies sync with each other, but it will if they sync with a 3rd database, because each of them will save the remote checkpoint with the same docID. That means they'll keep clobbering each others' checkpoints, and whenever that happens they'll start over and replicate from the beginning.

Yes, you should definitely call replaceUUIDs on a database after it's been copied. That should prevent the above problem.

> it pulled in the entire set of documents I believe

It's not actually pulling the documents, but it's pulling their docIDs and revIDs and looking them up locally, then realizing it already has them so it doesn't need to pull them. Which is still more overhead than you want, but much less than downloading the entire db!

**Comment by snej** [comment]
Oh, one thing I just remembered — are you using the `remoteUUID` replication option? One of the difficulties in P2P replication is that the URL of the remote db can change simply because its host changed its IP address or Bonjour hostname, and the URL is part of what determines the checkpoint's ID. So if the hostname/address changes, the replicator will think it hasn't replicated with this database before. Using `remoteUUID` allows you to override the remote URL with a UUID you provide — the PeerSync example code in that GrocerySync branch shows how.

**Comment by brendand** [comment]
Hi Jens,

Thanks for the info. Ok, I'll implement the change to call replaceUUIDs.

I don't see the remoteUUID option used in the GrocerySync app. I'm using the bonjour-sync-swift2 branch as my example.

I'll set that though to see how it goes.

**Comment by brendand** [comment]
One other question about remoteUUID. Will that affect things when I want to sync with Sync Gateway or Cloudant or some other cloud service?

**Comment by snej** [comment]
remoteUUID isn't necessary for server-based databases because their URLs stay fixed. It's a per-replication setting, so only use it for replications with peers over Bonjour.

**Comment by brendand** [comment]
How do I properly set the remoteUUID option?

I'm currently making my CBLReplicator like this:
```
self.currentPull = [self.databaseDocument.couchDatabase createPullReplication:peerURL];
```
Do I do it like this?
```
NSDictionary *pullProperties = @{@"remoteUUID" : self.currentPullPeer.service.name};
self.currentPull.customProperties = pullProperties;
```

My currentPullPeer has an NSNetService on it and I'm using its name as the remoteUUID value. It looks something like this: `db-8cbd8e5030564754bdad8a304bb548cd@DefiantX9`. DefiantX9 is the name of the computer I'm connecting to and the `db-8cbd8e5030564754bdad8a304bb548cd` part is the name of the database document I'm connecting to. Each database document opened up gets the same UUID, but the network device name can be different.

I couldn't find an example in the GrocerySync app, so I gleamed a bit of this from the source. If there's a better place to find more information about the remoteUUID option, please point me to it.

Thanks,

Brendan

**Comment by snej** [comment]
Yup, that's right. The customProperties need better documentation; for now you can look at the bottom of CBL_Replicator.h in the CBL source code.

**Comment by snej** [comment]
Filed an issue to make remoteUUID an official property: https://github.com/couchbaselabs/couchbase-lite-api/issues/126
