### ISSUE TITLE
Add group/reduce support to CBLQueryBuilder

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#947]
CBLQueryBuilder can't yet generate queries that use reduce functions or grouping. CBLIncrementalStore needs this to support some Core Data features (see #907).

**Comment by snej** [comment]
Looks like grouping/reducing would be needed when an expression in the `select:` list is an aggregate function like `max()` or `avg()`.

@pasin: What kind of predicates/expressions does Core Data use that require grouping?

**Comment by pasin** [comment]
NSFetchRequest has 2 properties for grouping and filtering the result.

1. propertiesToGroupBy : 

 > An array of `NSPropertyDescription` or `NSExpressionDescription` objects, or `key-path` strings that indicate how data should be grouped before a select statement is run in an SQL database. 

 > If you use this setting, then you must set the resultType to `NSDictionaryResultType`, and the SELECT values must be `literals`, `aggregates`, or `columns specified in the GROUP BY`. Aggregates will operate on the groups specified in the GROUP BY rather than the whole table. If you set properties to group by, you can also set a having predicate

 The document doesn't explicitly say the type of the expression. From the doc above, I understand that the expression could be `NSAggregateExpressionType` (for aggregation) or `NSConstantValueExpressionType` (for literal).

2. havingPredicate: 
 > If a having predicate is supplied, it will be run after the GROUP BY. Specifying a HAVING predicate requires that a GROUP BY also be specified.

**Comment by jayahariv** [comment]
Closing 1.x issue!
