### ISSUE TITLE
Parse new compound Server header format

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-ios#949]
Will include a stable/functional revision as well as the binary version, e.g. something like  `Sync Gateway 1.3 (0.0.234 #29AE23F)`.

Exact format will be specified in https://github.com/couchbase/sync_gateway/issues/1209.

**Comment by snej** [comment]
For backward compatibility and to comply (sort of) with the HTTP/1.1 spec, it's going to have to start with `Couchbase Sync Gateway/n.n `, which the existing code will parse. So there's nothing that needs to be done on the client side right now.

As we introduce new replication API features in the future, we can expose their presence by adding new tokens to the Server: header, and add code to CBL to recognize those.
