### ISSUE TITLE
Update CouchbaseLiteViewer

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-ios#950]

**Comment by snej** [comment]
That's https://github.com/couchbaselabs/CouchbaseLiteViewer

**Comment by snej** [comment]
Updated the viewer, tagged & released as [v0.5](https://github.com/couchbaselabs/CouchbaseLiteViewer/releases/tag/v0.5):

* Updated to Couchbase Lite 1.1.1
* Now updates the database display after another app (i.e. your app) makes changes to the database
* App browser:
  * Finds apps in the new iOS Simulator file layout
  * Added context menu with "Reveal In Finder" command
* Document editor:
  * Now uses an outline view to support viewing and editing nested JSON
  * Error alert if you try to save invalid JSON
  * You can add custom columns for nested JSON properties (even array elements)

### Known Issues

* You can lose changes in the editor by switching to another document without pressing Save.
* Changes made in the viewer app may not be detected by your app if it's running at the same time. (The changes will be there, but the app won't post database-changed or doc-changed notifications, LiveQueries won't update, etc. This is something we'd need to fix in a future version of Couchbase Lite.)
