### ISSUE TITLE
Couchbase lite eventually sends invalid heartbeat value for longpoll feed

### ISSUE THREAD

**Issue by alex7egli** [couchbase/couchbase-lite-ios#963]
We are using non-websocket push and pull replicators (set customProperties.webSocket to 0), couchbase lite 1.1.1 and sync gateway 1.1.1. After a few minutes our Pull replication will get a 400 response for one of the POST _changes requests and this kills the replication. It doesn't try to reconnect or anything so after that we don't retrieve any changes from the server. I can see in the sync gateway logs that the problem is invalid json:
21:43:41.016608 2015-10-27T21:43:41.016Z HTTP: #2524:     --> 400 Invalid JSON: "json: cannot unmarshal number 45190.0027692318 into Go value of type uint64"  (27.1 ms)

I can see from the packets being sent from the client to the server that the value is from the heartbeat parameter:
{"heartbeat":45921.76951467991,"feed":"longpoll","style":"all_docs","filter":"sync_gateway\/bychannel","since":251208,"channels":"long list of channels"}

At some point during the replication this pops up in the app logs:
2015-10-27 17:39:29.986 PUSH[422:44022] WARNING: CBLSocketChangeTracker[0x1baafe80 dbws]: Longpoll connection closed (by proxy?) after 61.2 sec 

In the couchbase lite code that warning comes before code that sets heartbeat to elapsed * 0.75 (in this case elapsed rounded to 1 decimal place is 61.2) Source > Replicator > ChangeTracker > CBLSocketChangeTracker.m line 250 in release/1.1.1. Basically if elapsed is precise to a sufficient number of decimal places it breaks the replication. Please round elapsed up before multiplying, or round the multiplication result to a value that sync gateway can unmarshal.

**Comment by snej** [comment]
You're right, the `heartbeat` value should be rounded to an integer when sent to the server in CBLChangeTracker. (There are two places that happens, one as a URL query param, the other as a JSON property.)

**Comment by snej** [comment]
Fixed on the release/1.2 branch. (Trivial 1-line patch if you want to cherry-pick it, Alex)
