### ISSUE TITLE
WebSockets cannot be used with channel filtering for large amounts of channels

### ISSUE THREAD

**Issue by alex7egli** [couchbase/couchbase-lite-ios#964]
WebSockets requires a GET request to make the initial connection, but couchbase uses the pull replicator _changes call to make this request. The _changes call has a variable length url though that is based on the number of channels filtered. If you are filtering by too many the url gets too long and the request fails. Please send any variable length parameters for the _changes request in a POST request so that we can filter by as many channels as needed and still use web sockets. This is for connecting to sync gateway.

**Comment by snej** [comment]
CBLChangeTracker sends the request parameters in the request body, either as a POST request in the normal mode, or as an initial message in the WebSocket mode. This was done largely so that the URL wouldn’t grow too big. But then it encodes the filter params in the URL anyway! Guess we forgot to take out that bit. It should be safe to remove it.

**Comment by snej** [comment]
Actually it _doesn't_ encode the params in the URL — CBLWebSocketChangeTracker overrides -changesFeedURL to return just the remote db URL with `_changes?feed=websocket` appended.

I've verified that on the master branch this issue doesn't occur. I can't switch to 1.1.1 right now, but looking at older revisions of CBLWebSocketChangeTracker.m it seems to behave the same way. I'll verify it soon.

**Comment by alex7egli** [comment]
Here is a log snippet from our sync gateway access.log file. This is the _changes request we saw when we used channel filtering and web sockets:
141.117.116.138 - - [26/Oct/2015:17:33:16 +0000] "GET /db/_changes?feed=normal&heartbeat=300000&style=all_docs&filter=sync_gateway%2Fbychannel&channels=all%2C236df1a7-3055-491a-ad4e-d292e3425c0f_sync%2C236df1a7-3055-491a-ad4e-d292e3425c0f_4215%2C236df1a7-3055-491a-ad4e-d292e3425c0f_4315%2C236df1a7-3055-491a-ad4e-d292e3425c0f_4415%2C-4sF5eDKLmP03idt8BViLgx_sync%2C-4sF5eDKLmP03idt8BViLgx_4215%2C-4sF5eDKLmP03idt8BViLgx_4315%2C-4sF5eDKLmP03idt8BViLgx_4415%2C-7WSw0gSqBwTJE2caD3GG8O_sync%2C-7WSw0gSqBwTJE2caD3GG8O_4215%2C-7WSw0gSqBwTJE2caD3GG8O_4315%2C-7WSw0gSqBwTJE2caD3GG8O_4415%2C-EC64zyqIRa7srRg92u3Nnk_sync%2C-EC64zyqIRa7srRg92u3Nnk_4215%2C-EC64zyqIRa7srRg92u3Nnk_4315%2C-EC64zyqIRa7srRg92u3Nnk_4415%2C-L6uZteyzAt93KwuLH2Yw7P_sync%2C-L6uZteyzAt93KwuLH2Yw7P_4215%2C-L6uZteyzAt93KwuLH2Yw7P_4315%2C-L6uZteyzAt93KwuLH2Yw7P_4415%2C-Zl3tLMpCzLfnAlxacjXhZj_sync%2C-Zl3tLMpCzLfnAlxacjXhZj_4215%2C-Zl3tLMpCzLfnAlxacjXhZj_4315%2C-Zl3tLMpCzLfnAlxacjXhZj_4415%2C-eFoS-dbjAFySJB66YlHGpj_sync%2C-eFoS-dbjAFySJB66YlHGpj_4215%2C-eFoS-dbjAFySJB66YlHGpj_4315%2C-eFoS-dbjAFySJB66YlHGpj_4415%2C-fCJcVIovZ8YoqJSDJEyeBz_sync%2C-fCJcVIovZ8YoqJSDJEyeBz_4215%2C-fCJcVIovZ8YoqJSDJEyeBz_4315%2C-fCJcVIovZ8YoqJSDJEyeBz_4415%2C-hPyO5btaywFJDDDmrW-Xe8_sync%2C-hPyO5btaywFJDDDmrW-Xe8_4215%2C-hPyO5btaywFJDDDmrW-Xe8_4315%2C-hPyO5btaywFJDDDmrW-Xe8_4415%2C-7KqXdOXm28Uv6cUEHn_yqd_sync%2C-7KqXdOXm28Uv6cUEHn_yqd_4215%2C-7KqXdOXm28Uv6cUEHn_yqd_4315%2C-7KqXdOXm28Uv6cUEHn_yqd_4415%2C-Xl1N9lJDeZgXsl4zgNu03C_sync%2C-Xl1N9lJDeZgXsl4zgNu03C_4215%2C-Xl1N9lJDeZgXsl4zgNu03C_4315%2C-Xl1N9lJDeZgXsl4zgNu03C_4415%2C-bScPOAXhnJ7J0HuK7dXyW9_sync%2C-bScPOAXhnJ7J0HuK7dXyW9_4215%2C-bScPOAXhnJ7J0HuK7dXyW9_4315%2C-bScPOAXhnJ7J0HuK7dXyW9_4415%2C-kNcM5-sm3870iqEzSPl0UE_sync%2C-kNcM5-sm3870iqEzSPl0UE_4215%2C-kNcM5-sm3870iqEzSPl0UE_4315%2C-kNcM5-sm3870iqEzSPl0UE_4415%2C-kXw2sA07xOQcotHRPds4AA_sync%2C-kXw2sA07xOQcotHRPds4AA_4215%2C-kXw2sA07xOQcotHRPds4AA_4315%2C-kXw2sA07xOQcotHRPds4AA_4415%2C-lRuKylSboraJduS5veypuH_sync%2C-lRuKylSboraJduS5veypuH_4215%2C-lRuKylSboraJduS5veypuH_4315%2C-lRuKylSboraJduS5veypuH_4415%2C-rFIklG1lazgfb8hg0Fm3UM_sync%2C-rFIklG1lazgfb8hg0Fm3UM_4215%2C-rFIklG1lazgfb8hg0Fm3UM_4315%2C-rFIklG1lazgfb8hg0Fm3UM_4415%2C-2GhHtQT3FRJAtddiqYi9xn_sync%2C-2GhHtQT3FRJAtddiqYi9xn_4215%2C-2GhHtQT3FRJAtddiqYi9xn_4315%2C-2GhHtQT3FRJAtddiqYi9xn_4415%2C-D6TQI59F6Q2liyozlBXAzM_sync%2C-D6TQI59F6Q2liyozlBXAzM_4215%2C-D6TQI59F6Q2liyozlBXAzM_4315%2C-D6TQI59F6Q2liyozlBXAzM_4415%2C-IxHM7iMIuAl5O6uysf6uwe_sync%2C-IxHM7iMIuAl5O6uysf6uwe_4215%2C-IxHM7iMIuAl5O6uysf6uwe_4315%2C-IxHM7iMIuAl5O6uysf6uwe_4415%2C-WUdEnzgDkNOykKpNi9TXAU_sync%2C-WUdEnzgDkNOykKpNi9TXAU_4215%2C-WUdEnzgDkNOykKpNi9TXAU_4315%2C-WUdEnzgDkNOykKpNi9TXAU_4415%2C-c6ljPHTfEEHfDWcxwhgH4K_sync%2C-c6ljPHTfEEHfDWcxwhgH4K_4215%2C-c6ljPHTfEEHfDWcxwhgH4K_4315%2C-c6ljPHTfEEHfDWcxwhgH4K_4415%2C-uBR4SWKbQSo-LRujxKrDia_sync%2C-uBR4SWKbQSo-LRujxKrDia_4215%2C-uBR4SWKbQSo-LRujxKrDia_4315%2C-uBR4SWKbQSo-LRujxKrDia_4415%2C-xuX2wc_lS6qoN2wlask596_sync%2C-xuX2wc_lS6qoN2wlask596_4215%2C-xuX2wc_lS6qoN2wlask596_4315%2C-xuX2wc_lS6qoN2wlask596_4415%2C305a95ca-4812-4003-b03f-32e8122cfcea_sync%2C305a95ca-4812-4003-b03f-32e8122cfcea_4215%2C305a95ca-4812-4003-b03f-32e8122cfcea_4315%2C305a95ca-4812-4003-b03f-32e8122cfcea_4415%2C3db31419-e588-47ca-bb4e-444a358933d2_sync%2C3db31419-e588-47ca-bb4e-444a358933d2_4215%2C3db31419-e588-47ca-bb4e-444a358933d2_4315%2C3db31419-e588-47ca-bb4e-444a358933d2_4415%2C40297110-28b4-4d00-882b-33988e356f40_sync%2C40297110-28b4-4d00-882b-33988e356f40_4215%2C40297110-28b4-4d00-882b-33988e356f40_4315%2C40297110-28b4-4d00-882b-33988e356f40_4415%2C463ad257-ea84-4455-89e4-99682108068b_sync%2C463ad257-ea84-4455-89e4-99682108068b_4215%2C463ad257-ea84-4455-89e4-99682108068b_4315%2C463ad257-ea84-4455-89e4-99682108068b_4415%2C5e665beb-1c76-4596-964f-cfd0b2d9db79_sync%2C5e665beb-1c76-4596-964f-cfd0b2d9db79_4215%2C5e665beb-1c76-4596-964f-cfd0b2d9db79_4315%2C5e665beb-1c76-4596-964f-cfd0b2d9db79_4415%2C8fe43daf-b911-40f6-a2e8-29489048b348_sync%2C8fe43daf-b911-40f6-a2e8-29489048b348_4215%2C8fe43daf-b911-40f6-a2e8-29489048b348_4315%2C8fe43daf-b911-40f6-a2e8-29489048b348_4415%2C92373afb-5151-4a13-a78a-d7f921ce23ae_sync%2C92373afb-5151-4a13-a78a-d7f921ce23ae_4215%2C92373afb-5151-4a13-a78a-d7f921ce23ae_4315%2C92373afb-5151-4a13-a78a-d7f921ce23ae_4415%2Cfdfdbad0-538d-4cf5-bdee-e68be234ded1_sync%2Cfdfdbad0-538d-4cf5-bdee-e68be234ded1_4215%2Cfdfdbad0-538d-4cf5-bdee-e68be234ded1_4315%2Cfdfdbad0-538d-4cf5-bdee-e68be234ded1_4415%2C-DcIgQzg7kX5oTzisVOszAI_sync%2C-DcIgQzg7kX5oTzisVOszAI_4215%2C-DcIgQzg7kX5oTzisVOszAI_4315%2C-DcIgQzg7kX5oTzisVOszAI_4415%2C-IY82CA0wUQCFfUFCzyoNd__sync%2C-IY82CA0wUQCFfUFCzyoNd__4215%2C-IY82CA0wUQCFfUFCzyoNd__4315%2C-IY82CA0wUQCFfUFCzyoNd__4415%2C-OzU1j7CXsfXSCT8UWKiW10_sync%2C-OzU1j7CXsfXSCT8UWKiW10_4215%2C-OzU1j7CXsfXSCT8UWKiW10_4315%2C-OzU1j7CXsfXSCT8UWKiW10_4415%2C-Sty2k-cLazCdfNVOCuqBbp_sync%2C-Sty2k-cLazCdfNVOCuqBbp_4215%2C-Sty2k-cLazCdfNVOCuqBbp_4315%2C-Sty2k-cLazCdfNVOCuqBbp_4415%2C-a1vJ-Y2CbIZe1Z5gM3Z3y3_sync%2C-a1vJ-Y2CbIZe1Z5gM3Z3y3_4215%2C-a1vJ-Y2CbIZe1Z5gM3Z3y3_4315%2C-a1vJ-Y2CbIZe1Z5gM3Z3y3_4415%2C-rIybMNQxJvqsvCoRn21hba_sync%2C-rIybMNQxJvqsvCoRn21hba_4215%2C-rIybMNQxJvqsvCoRn21hba_4315%2C-rIybMNQxJvqsvCoRn21hba_4415%2C-3dO_NFNhofeBBhPXLXss-4_sync%2C-3dO_NFNhofeBBhPXLXss-4_4215%2C-3dO_NFNhofeBBhPXLXss-4_4315%2C-3dO_NFNhofeBBhPXLXss-4_4415%2C-N_K8NMBuE1AE_k-D8I0hvB_sync%2C-N_K8NMBuE1AE_k-D8I0hvB_4215%2C-N_K8NMBuE1AE_k-D8I0hvB_4315%2C-N_K8NMBuE1AE_k-D8I0hvB_4415%2C-ZevtVLCuYxvUbaqp60czi-_sync%2C-ZevtVLCuYxvUbaqp60czi-_4215%2C-ZevtVLCuYxvUbaqp60czi-_4315%2C-ZevtVLCuYxvUbaqp60czi-_4415%2C-fHXgFy-Zq5uhn7NqgBnQOe_sync%2C-fHXgFy-Zq5uhn7NqgBnQOe_4215%2C-fHXgFy-Zq5uhn7NqgBnQOe_4315%2C-fHXgFy-Zq5uhn7NqgBnQOe_4415%2C-lwmHfZKUJ6fpIAxPBDIuwD_sync%2C-lwmHfZKUJ6fpIAxPBDIuwD_4215%2C-lwmHfZKUJ6fpIAxPBDIuwD_4315%2C-lwmHfZKUJ6fpIAxPBDIuwD_4415%2C-mcw6F00L551Qx6IbuISQhv_sync%2C-mcw6F00L551Qx6IbuISQhv_4215%2C-mcw6F00L551Qx6IbuISQhv_4315%2C-mcw6F00L551Qx6IbuISQhv_4415%2C-9uweW5vWgDD01rIzTJh69n_sync%2C-9uweW5vWgDD01rIzTJh69n_4215%2C-9uweW5vWgDD01rIzTJh69n_4315%2C-9uweW5vWgDD01rIzTJh69n_4415%2C-XXzrfkZaYPaCf0rNzuR8g6_sync%2C-XXzrfkZaYPaCf0rNzuR8g6_4215%2C-XXzrfkZaYPaCf0rNzuR8g6_4315%2C-XXzrfkZaYPaCf0rNzuR8g6_4415%2C-YoROuXNtHtsZ55_aUICcCg_sync%2C-YoROuXNtHtsZ55_aUICcCg_4215%2C-YoROuXNtHtsZ55_aUICcCg_4315%2C-YoROuXNtHtsZ55_aUICcCg_4415%2C-wYZ7bidPoCc4399GL3yP1Y_sync%2C-wYZ7bidPoCc4399GL3yP1Y_4215%2C-wYZ7bidPoCc4399GL3yP1Y_4315%2C-wYZ7bidPoCc4399GL3yP1Y_4415%2C-1jxDrecRmwSqYNOgnhcAlQ_sync%2C-1jxDrecRmwSqYNOgnhcAlQ_4215%2C-1jxDrecRmwSqYNOgnhcAlQ_4315%2C-1jxDrecRmwSqYNOgnhcAlQ_4415%2C-38FwFFGjDkIv9-twxSEIPr_sync%2C-38FwFFGjDkIv9-twxSEIPr_4215%2C-38FwFFGjDkIv9-twxSEIPr_4315%2C-38FwFFGjDkIv9-twxSEIPr_4415%2C-8b5K8OZW2rzUcrw8olXXYI_sync%2C-8b5K8OZW2rzUcrw8olXXYI_4215%2C-8b5K8OZW2rzUcrw8olXXYI_4315%2C-8b5K8OZW2rzUcrw8olXXYI_4415%2C-KQWkRBc0pC0-vA27VzAiwU_sync%2C-KQWkRBc0pC0-vA27VzAiwU_4215%2C-KQWkRBc0pC0-vA27VzAiwU_4315%2C-KQWkRBc0pC0-vA27VzAiwU_4415%2C-M2E-uh7GWDw1dHVfkQUONL_sync%2C-M2E-uh7GWDw1dHVfkQUONL_4215%2C-M2E-uh7GWDw1dHVfkQUONL_4315%2C-M2E-uh7GWDw1dHVfkQUONL_4415%2C-knk8XNpuo8797rTNcSwOof_sync%2C-knk8XNpuo8797rTNcSwOof_4215%2C-knk8XNpuo8797rTNcSwOof_4315%2C-knk8XNpuo8797rTNcSwOof_4415%2C-mpu4mRw96cuqm-cAs16t9D_sync%2C-mpu4mRw96cuqm-cAs16t9D_4215%2C-mpu4mRw96cuqm-cAs16t9D_4315%2C-mpu4mRw96cuqm-cAs16t9D_4415%2C699F9E10-4E91-4CA7-9E77-21F43812B931_sync%2C699F9E10-4E91-4CA7-9E77-21F43812B931_4215%2C699F9E10-4E91-4CA7-9E77-21F43812B931_4315%2C699F9E10-4E91-4CA7-9E77-21F43812B931_4415%2C8B3C238C-6050-4F73-9C13-F2540AB3FC67_sync%2C8B3C238C-6050-4F73-9C13-F2540AB3FC67_4215%2C8B3C238C-6050-4F73-9C13-F2540AB3FC67_4315%2C8B3C238C-6050-4F73-9C13-F2540AB3FC67_4415%2CB5A89CEA-245B-4B4E-8B4D-219CD95CDC62_sync%2CB5A89CEA-245B-4B4E-8B4D-219CD95CDC62_4215%2CB5A89CEA-245B-4B4E-8B4D-219CD95CDC62_4315%2CB5A89CEA-245B-4B4E-8B4D-219CD95CDC62_4415%2CE612A099-EB95-4EB6-8C50-486F8D2F1885_sync%2CE612A099-EB95-4EB6-8C50-486F8D2F1885_4215%2CE612A099-EB95-4EB6-8C50-486F8D2F1885_4315%2CE612A099-EB95-4EB6-8C50-486F8D2F1885_4415%2C-nfkPkFIAAl_uYdCZtM6w9Y_sync%2C-nfkPkFIAAl_uYdCZtM6w9Y_4215%2C-nfkPkFIAAl_uYdCZtM6w9Y_4315%2C-nfkPkFIAAl_uYdCZtM6w9Y_4415%2C0F1CBE2B-3A33-4B4B-AF3A-C255D838AE1E_sync%2C0F1CBE2B-3A33-4B4B-AF3A-C255D838AE1E_4215%2C0F1C" 414 192 "-" "-"

**Comment by snej** [comment]
The URL contains `?feed=normal`, not `?feed=websocket` — that's not a WebSocket request.

**Comment by snej** [comment]
Just looked through the non-WebSocket control flow for the changes feed: it uses a POST (instead of a GET, with the long URL) if the server is Sync Gateway. If it's not doing so, that implies it didn't receive a Server: header in a response, or that this is the first request being sent.

IIRC, weren't you having trouble earlier with the Server response header being dropped? Also, what version of CBL are you using?

**Comment by alex7egli** [comment]
We're using Couchbase Lite iOS v1.1.1 and Sync Gateway v1.1.1. To create the replicator we used:
CBLReplication pull = [_database createPullReplication:_remoteURL];
   pull.continuous = YES;
   
   CBLReplication push = [_database createPushReplication:_remoteURL];
   push.continuous = YES;
   
   [self listenForPullReplicationEvents:pull];
   [self listenForPushReplicationEvents:push];
   [_authenticator registerCredentialsWithReplications: @[pull, push]]; 
[pull start];
[push start];

That produced the nginx access log I posted above, and as far as I know this is the default recommended way to create a replicator. I was told in a couchbase forum post that web sockets were the default communication method, but are you saying that we need to explicitly tell the replicator to use web sockets? Do we need to set the customProperties.websocket flag to 1?

**Comment by snej** [comment]
Sorry, that was someone else having that problem … I'm getting support tickets mixed up :/

But it does sound like something (nginx?) is stripping the `Server:` response header from SG. If CBL doesn't see that, it doesn't think it's talking to SG, so it won't use protocol extensions like WebSockets. (Or a POST to the changes feed to shorten the URL, which was my mistake as that's not actually a custom extension.)

Try using curl to send a request to SG and look at the response headers — something like `curl -i http://blahblah.com/db`.

**Comment by alex7egli** [comment]
nginx is configured to pass the Server and Accept headers through the proxy. I did curl -i against our web sockets endpoint and got (I changed the host and db name for privacy reasons since this is our dev server):

 curl -i http://host/dbws/
HTTP/1.1 200 OK
Date: Tue, 03 Nov 2015 18:29:09 GMT
Content-Type: application/json
Content-Length: 170
Connection: keep-alive
Server: Couchbase Sync Gateway/1.1.1{"committed_update_seq":253069,"compact_running":false,"db_name":"dbName","disk_format_version":0,"instance_start_time":1446478748413082,"purge_seq":0,"update_seq":253069}

**Comment by snej** [comment]
Is the missing CRLF after the Server header in the original output, or something that happened when you pasted it in?

**Comment by alex7egli** [comment]
I think that's from pasting it in, in the terminal Server: Couchbase Sync Gateway/1.1.1 is all on one line, then there is an empty line, then the body of the response.

**Comment by snej** [comment]
Just noticed you said:
>This is the first request being sent in by the client though

That's weird; the first request should be a GET of the checkpoint, which has a path like `/db/_local/abunchofrandomhex`. After that, CBL has a response from SG to look at, so it can determine that it's talking to SG. But if the changes feed is the first request, it doesn't know yet that it's talking to SG.

You're using the released binary of 1.1.1? Or did you build it from source?

Anywho, I'm checking in a one-line fix that makes CBL always use the POST form of `_changes`, which will fix the URL issue. It's going into the 1.2 branch, but you can easily cherry-pick it onto 1.1.1 if you check out and build yourself.

**Comment by alex7egli** [comment]
My bad, the _local calls are the first ones to get the checkpoints, the _changes is just the first request for actual data that seems to be used to establish the websocket connection, and then usually after that it does a bunch of _bulk_get calls to get all the actual data.

We're using the released binary of 1.1.1. We're having a lot of trouble with replication and the non-websockets (longpoll) form though, so we may end up using your fix and trying to get web sockets working with it.

**Comment by snej** [comment]
Hm. Feel free to file bug reports about the problems with longpoll … I don't think they're known issues, since it generally works.

**Comment by alex7egli** [comment]
Looking in the master branch at CBLWebSocketChangeTracker.m, lines 57 to 60 (in the start method) are:
 // A WebSocket has to be opened with a GET request, not a POST (as defined in the RFC.)
    // Instead of putting the options in the POST body as with HTTP, we will send them in an
    // initial WebSocket message, in -webSocketDidOpen:, below.
    self.usePOST = NO;

So won't that always override your hardcoding of usePOST? Since [_changeTracker start] is called after the line you changed?

**Comment by alex7egli** [comment]
That's why I was calling that _changes request the initial request, because the comment above implied that the _changes request had to be a GET request to open the connection.

**Comment by snej** [comment]
CBLWebSocketChangeTracker uses a GET, as required by the WebSocket protocol, but it doesn't send the list of channels in the URL, rather in the first WebSocket message.
