### ISSUE TITLE
Allow database file to be moved while it's opened

### ISSUE THREAD

**Issue by brendand** [couchbase/couchbase-lite-ios#968]
I'm using NSDocument and NSFileWrapper to store my Couchbase database file in a bundle (folder). A typical NSDocument based Mac app allows you to move and rename the bundle while it's still opened. There are even Rename and Move To command built-in to the File menu. You can also rename or move a document from the titlebar area or you can drag the file proxy icon in the titlebar to a new location.

Unfortunately Couchbase Lite doesn't support these kinds of operations. I had a discussion with Jens a while ago about this on the Google group. I realize it might be impossible to have this, but I thought I would submit this as a feature request in the hopes that it may be something worthwhile for others too. For now I'm doing what I can to prevent someone from renaming or moving the bundle from within my app, but I can't prevent them from renaming or moving the bundle right in the Finder while the document is opened.

For reference, I'm including Jens' response to the discussion we had:

> Both ForestDB and SQLite keep the database file open and just issue read/write calls on the file descriptor, for the most part. That works fine even if the file gets moved.
> 
> The things that I believe will fail, for a ForestDB-based database, are
> - Compacting a database (this creates a new db file in the directory and eventually replaces the old file with the new one)
> - Querying or indexing a view whose backing db file wasn’t already open at the time
> - Reading or creating attachments
> 
> I’d like to not have these problems, but they might be hard to fix. In particular, ForestDB has file paths baked into its implementation at a pretty deep level.
> 
> —Jens

Here's the original link to the discussion thread:

https://groups.google.com/d/msg/mobile-couchbase/gRAgpPj6BPM/HN1jFAENBgAJ

**Comment by snej** [comment]
The best way to do this would be to use an alternative filesystem path to the database that would continue to work even if the parent directory is moved. I'm not sure if such a thing exists, though. It could be done by creating a hard-link to the directory, but that would introduce other problems. I've asked about this on Apple's darwin-userlevel mailing list.

**Comment by jayahariv** [comment]
Closing 1.x issue!
