### ISSUE TITLE
CBL_SQLiteStorage references hard-coded "type" key in properties

### ISSUE THREAD

**Issue by subpop** [couchbase/couchbase-lite-ios#975]
From what I've gathered from reading the documentation on CBLDocument, there's a convention around using the "type" key in documents to define different entity or record types. As in `list`, below:

```
let properties = [
    "type": "list",
    "title": title,
    "owner": owner,
    "members": []
]
```

The dataset I'm working with already uses "type" to define something else. Since `CBL_SQLiteStorage` hardcodes a reference to this key on [line 1680](https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CBL_SQLiteStorage.m#L1680), I have to change my dataset to be used with this storage engine.

```
        SequenceNumber sequence = [self insertRevision: newRev
                                          docNumericID: docNumericID
                                        parentSequence: parentSequence
                                               current: YES
                                        hasAttachments: (properties.cbl_attachments != nil)
                                                  JSON: json
                                               docType: properties[@"type"]];
```

It sounds like type should be changed to a reserved "_type" key, since it's used for internal data organization.

**Comment by snej** [comment]
What problem does the hardcoded use of `type` cause for your app? It's only an optimization, allowing a view to filter the docs that it maps. It shouldn't affect you unless you use that feature (setting CBLView.documentType`).

**Comment by subpop** [comment]
That is a feature I would consider using, since I have multiple document types (both of which happen to have an existing "type" key). The problem I have is that in order to use this documentType feature, I need to modify my data (which is sourced from an external JSON source). NBD if the intention of the feature is to attempt at scraping the "type" value from data without the programmer intervening. But since `type` feels like a reserved key, I figured it might make sense to name it more explicitly as such.

**Comment by snej** [comment]
If we used a different key for this, then a lot of developers, who already use `"type"`, would have to modify all of their data.

Also, adding a key that starts with an underscore is bad for compatibility because CouchDB will reject it, as will current versions of Sync Gateway.
