### ISSUE TITLE
Package a SQLCipher binary with our storage engine

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-ios#976]
In the spirit of providing Couchbase Lite with "batteries included," we need to offer a SQLCipher native image so that they aren't required to provide their own. If they have a commercial build from Zetetic, they should be able to use that instead.

**Comment by snej** [comment]
We should have a Jenkins job that builds SQLCipher for iOS and Mac OS. Then we can ship the resulting `libsqlcipher.a` in our release. Then the developer can link their app either with that file or with the system SQLite.dylib.

**Comment by snej** [comment]
Actually on Mac it's a little more complicated because the CBL framework contains a dynamic library that's already configured to link with libsqlite.dylib; it's not something the developer can configure after it's built. Instead we'd need to ship two copies of the framework, one using the system library and one with SQLCipher linked in. Or maybe we only offer the latter — it's only ~1mb larger I think, and Mac developers probably don't care that much about binary size.

**Comment by zgramana** [comment]
@mchaelkwok, can you please update the build script to include libsqlcipher.a in the release package?

**Comment by michaelkwok** [comment]
Is somebody going to  integrated in our iOS project?  Perhaps as a submodule?

**Comment by snej** [comment]
I can do that, but we'll need SQLCipher for the other versions of CBL too (including the iOS build of CBL/.NET.) Would it make more sense to have a separate SQLCipher Jenkins build that spits out binaries for all supported platforms?

**Comment by pasin** [comment]
Can we use https://github.com/couchbaselabs/couchbase-lite-libsqlcipher? Currently I manually built for each platforms and put the library in `lib`. Each platform has build-xx.sh script to build.

**Comment by pasin** [comment]
Currently https://github.com/couchbaselabs/couchbase-lite-libsqlcipher builds the library with these options for iOS and OSX. 

```
"-DSQLITE_HAS_CODEC",
"-DSQLITE_TEMP_STORE=2",
"-DSQLITE_THREADSAFE=2",
"-DSQLCIPHER_CRYPTO_CC",
"-DSQLITE_ENABLE_FTS3_PARENTHESIS",
"-DSQLITE_ENABLE_FTS4",
"-DSQLITE_ENABLE_COLUMN_METADATA"
```

@snej would these be enough for all features (e.g. geo and full text search) supported by CBL iOS?

**Comment by pasin** [comment]
Look like we need to add -DSQLITE_ENABLE_RTREE.

**Comment by snej** [comment]
I think that will do it. Running the unit tests will catch anything we might have missed.

**Comment by michaelkwok** [comment]
That's good to have it in couchbaselabs.  

@Pasin, I thought it's already integrated as part of the Java/Android build.  Maybe I am looking at the wrong thing.  It actually makes packaging easier and cleaner to manage if it's integrated.   Would you guys be able to integrate it fairly quickly?

**Comment by michaelkwok** [comment]
It seems Pasin builds all the binaries by hand and most likely we only need to build one time for now.  The binaries are kept under the same repo so Android/Java submodules the repo and use the binary to build a jni library.  I do see libsqlcipher.a in the same repo.  If we don't need to rebuild on every iOS build, we can just use the libsqlcipher.a.  I think I understand better.  Let's wrap it up after the holiday break.

**Comment by brendand** [comment]
When I build SQLCipher along with the above options, I also add: -DSQLITE_ENABLE_FTS4_UNICODE61 which allows me to provide support for proper sorting and searching of some other languages such as Russian.

**Comment by snej** [comment]
For iOS we don't need to build our code differently. We just need to provide a separate libSQLCipher.a static library, and developers can add that to their app's linked-libraries in place of the system libSQLite.dylib.

For Mac OS the framework is linked, so we do need to build it differently. We'll need a new target that links with  a Mac libSQLCipher.a instead of libSQLite.dylib. (That library will need to be provided externally, i.e. you'll need to copy it into the project folder somewhere before building. This will be done as part of our automated build process.)

**Comment by snej** [comment]
Fixed on release/1.2 branch. Notes from the commit log:

>Added CBL Mac+SQLCipher target
>This target builds a Mac OS framework that uses SQLCipher (built-in) instead of the system SQLite.
To build this, you must have copied a 64-bit Mac OS static library of SQLCipher into `vendor/SQLCipher/libs/osx/libSQLCipher.a`.
>To avoid name collisions, the build output appears in directories named `Debug-SQLCipher` and `Release-SQLCipher`. The framework of course has the same name.

I haven't been able to run the unit tests on this version — the Mac unit tests target seems hardwired to use the framework built by the regular target, and I couldn't figure out how to change that. But I used `nm` to look at the exported and imported symbols, and it looks good — all the public API symbols are exported, and the sqlite3 symbols are not imported.

**Comment by snej** [comment]
@brendand:
>When I build SQLCipher along with the above options, I also add: -DSQLITE_ENABLE_FTS4_UNICODE61 

Our current SQLCipher build doesn't have that flag enabled, but @pasin says he'll add it today, so the version we ship in 1.2 will include it. Thanks for pointing it out.

**Comment by michaelkwok** [comment]
SQLCipher is in all the builds now
