### ISSUE TITLE
Perform backup and restore from within iOS app

### ISSUE THREAD

**Issue by marbetschar** [couchbase/couchbase-lite-ios#980]
I open a database connection during the application start of my iOS app. This connection is kept open during the whole runtime of the app.

Now, I'd like to perform complete database backups during with a given schedule (for example once every day) and allow the user to perform a restore to a given snapshot from within the app.

How would be the best approach for achieving this?
Is there already any API available for this?

FWIW: The data is replicated in one channel per user and sent to a sync gateway, running in front of one bucket, which stores all data from all users on the server.

**Comment by snej** [comment]
Close the database, then copy its files somewhere. 

* SQLite-based databases in version 1.1.1 and earlier consist of a file `xxx.cblite` and optionally a directory `xxx attachments`.
* ForestDB-based databases, and all dbs in 1.2+, consist of a directory `xxx.cblite2`.

Note that if all docs in your db are replicated to a server, that is effectively a remote backup, and you could restore the db by creating an empty db and pulling from the server. So a local backup may not be necessary.

**Comment by marbetschar** [comment]
I'm aware of the remote backup; and exactly this one is the reason for my headaches:

If I close the local database, then delete it move an older one (which was copied earlier) to it's place and then open the older one; now the sync process kicks in: Wouldn't the sync keep up with the latest revisions stored on the server instead of the explicitly restored local one?

And what about attachments? As far as I know, they are stored in a separate folder and not within the database file?

**Comment by snej** [comment]
> Wouldn't the sync keep up with the latest revisions stored on the server instead of the explicitly restored local one?

Yes. This is usually considered a good thing :)

If you do explicitly want to revert a document back to a previous state, you have to do it by adding a new revision with the same contents as the old one. (Rather like doing a revert in git.)

> And what about attachments? As far as I know, they are stored in a separate folder and not within the database file?

That's what's in that `attachments` folder I mentioned above. In the `cblite2` format the attachments are in a sub-directory.

**Comment by marbetschar** [comment]
> Yes. This is usually considered a good thing :)

Indeed :)

> If you do explicitly want to revert a document back to a previous state, you have to do it by adding a new revision with the same contents as the old one. (Rather like doing a revert in git.)

Ok you really helped me a lot! Just one last question: How would I best add a new revision of a document containing the exact same values?

**Comment by snej** [comment]
No problem. But if you want to ask questions, we prefer to use our Couchbase web forums or Google group for that.

**Comment by marbetschar** [comment]
Sure, thank you!!!!
