### ISSUE TITLE
migrate replicator to JSON encoded list of channel names

### ISSUE THREAD

**Issue by jchris** [couchbase/couchbase-lite-ios#981]
The current filter API uses a comma delimited list of channel names, but we want to allow user data in channel names, so API clients need to start using the JSON option before they can access channels that have comma in the name...

This will require fixing https://github.com/couchbase/sync_gateway/issues/1292 first.

**Comment by snej** [comment]
IIRC it's only the GET form of `_changes` that does this, and CBL doesn't use that.

**Comment by jayahariv** [comment]
Closing 1.x issue!
