### ISSUE TITLE
Comparing CBLQuery objects

### ISSUE THREAD

**Issue by jordanpwood** [couchbase/couchbase-lite-ios#984]
I would like to take two CBLQuery objects and find out if they represent the same query on a view. I can compare the parameters that are important to me (startKey, endKey, groupLevel, mapOnly), but I can't check that the two queries actually reference the same view, since I see no way to find out what view created a query from the query object.

Is there a better way for me to compare two queries that have been created with separate calls to [myView createQuery]? Can I get the name of the view that created a CBLQuery? I am using this to update a set of CBLLiveQuery objects that my app keeps.

**Comment by jordanpwood** [comment]
I still would like a way to get the name of the view that a query is on when I only have the query object.

**Comment by snej** [comment]
The view is an internal instance variable, so it would be trivial to expose it as a property.

**Comment by snej** [comment]
Merged to dev branch; closing.
