### ISSUE TITLE
CBManager enableLogging doc

### ISSUE THREAD

**Issue by Sagaris** [couchbase/couchbase-lite-ios#985]
The CBLManager enableLogging documentation refers to a none existing page http://docs.couchbase.com/couchbase-lite/cbl-ios/#useful-logging-channels for a list of types. 
Please provide the correct url to the list of logging types.

**Comment by snej** [comment]
Thanks. I've filed an issue in our (non-public) docs issue tracker. You can find a list of logging channels [here](https://github.com/couchbase/couchbase-lite-ios/wiki/Logging).
