### ISSUE TITLE
ForestDB crashes with a fullTextQuery

### ISSUE THREAD

**Issue by jschmid** [couchbase/couchbase-lite-ios#987]
I am using Couchbase Lite 1.1 and ForestDB. I have a very simple test search view that I am querying. 

```swift
let viewName = "contacts-textsearch"
let searchView = self.database.viewNamed(viewName)
searchView.documentType = "Contact"
searchView.setMapBlock("2") { doc, emit in
    let displayName = // using doc...
    emit(CBLTextKey(displayName), displayName)
}
```

I am trying to query it with `runAsync` but the callback does not always get called. 

```swift
let query = searchView.createQuery()
query.fullTextQuery = terms
query.runAsync { enumer, error in
  DDLogVerbose("\(enumer.count) rows")
}
```

See the log when I type *anna*.

```
2015-12-03 13:15:20:555 myproject[38201:2738091] <>
13:15:20.596| Query: CBLQuery[contacts-textsearch-one]: Async query reach/contacts-textsearch-one...
13:15:20.599‖ QueryVerbose: Full-text search for "":
13:15:20.599‖ QueryVerbose: Iterating index...

2015-12-03 13:15:24:387 myproject[38201:2738091] <a>
13:15:24.388| Query: CBLQuery[contacts-textsearch-one]: Async query reach/contacts-textsearch-one...
13:15:24.388‖ QueryVerbose: Full-text search for "a":
13:15:24.388‖ QueryVerbose: Iterating index...

2015-12-03 13:15:27:729 myproject[38201:2738091] <an>
13:15:27.730| Query: CBLQuery[contacts-textsearch-one]: Async query reach/contacts-textsearch-one...
13:15:27.730‖ QueryVerbose: Full-text search for "an":
13:15:27.730‖ QueryVerbose: Iterating index...

2015-12-03 13:15:30:257 myproject[38201:2738091] <ann>
13:15:30.258| Query: CBLQuery[contacts-textsearch-one]: Async query reach/contacts-textsearch-one...
13:15:30.258‖ QueryVerbose: Full-text search for "ann":
13:15:30.258‖ QueryVerbose:     token: "ann"
13:15:30.258‖ QueryVerbose: Iterating index...
13:15:30.259‖ Query: Query contacts-textsearch-one: Returning iterator
13:15:30.259| Query: CBLQuery[contacts-textsearch-one]: ...async query finished (0 rows, status 200)
2015-12-03 13:15:30:260 myproject[38201:2738091] rows next: []

2015-12-03 13:15:33:161 myproject[38201:2738091] <anna>
13:15:33.162| Query: CBLQuery[contacts-textsearch-one]: Async query reach/contacts-textsearch-one...
13:15:33.162‖ QueryVerbose: Full-text search for "anna":
13:15:33.162‖ QueryVerbose:     token: "anna"
13:15:33.162‖ QueryVerbose: Iterating index...
13:15:33.162‖ Query: Query contacts-textsearch-one: Returning iterator
13:15:33.164| Query: CBLQuery[contacts-textsearch-one]: ...async query finished (1 rows, status 200)
2015-12-03 13:15:33:165 myproject[38201:2738091] rows next: [CBLFullTextQueryRow[key=null; value="Anna Haru"; id=-0wufpBDjt-JDo_3b1rRGp8]]
```

For some reason, the first 3 searches never call my callback. Is it specific to the full text search? Is there a limit to the number of characters needed for a search to work? In any case, the callback should always be called, right?

**Comment by jschmid** [comment]
I just tested with the SQLite storage and it works fine. It seems to be a ForestDB bug/limitation.

**Comment by jschmid** [comment]
Alright! After some more tests I've found that it does not depend on `runAsync`.

Running a full text query with less than 3 characters simply crashes the app.

I see two bugs:

* When running with `run`, the app crashes (even with the Swift try/catch)
* When running with `runAsync`, the app does not crash, but the callback is never called.

**Comment by snej** [comment]
Nice job isolating the bug! I'll take a look at it.

**Comment by snej** [comment]
I can't reproduce this. Please include a crash log.

(FYI, Swift `catch` doesn't catch any sort of exceptions/crashes. It only works with APIs that return errors via the usual Cocoa pattern of an `NSError**` parameter.)

**Comment by jschmid** [comment]
Here is a crash log: https://gist.github.com/jschmid/337cb34c5830985edcef
I don't know if it'll help you.

I tried with CBL 1.1.0 and 1.1.1 (downloaded from the website) and I get the same crash.

(Thanks about the reminder for the Swift catch :+1: )

**Comment by snej** [comment]
Thanks — that's definitely a smoking gun :)

```
0x0000000196ecef44 std::__terminate(void (*)()) + 16
0x0000000196ece85c __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*) + 0
0x0000000100298adc forestdb::CollatableReader::endArray() (Collatable.cc:200)
0x00000001002a0a50 forestdb::IndexEnumerator::read() (Index.cc:290)
0x000000010028c16c -[CBL_ForestDBViewStorage fullTextQueryWithOptions:status:] (CBL_ForestDBViewStorage.mm:808)
```

The first problem is an internal exception reading from the view index, and the second problem is that `CBL_ForestDBViewStorage` doesn't have a `catch` block in place to handle it, so the process aborts.

**Comment by snej** [comment]
The `catch` block was added in September in commit e831224cd36977349e07c30979c196180870e666. So that's fixed in master (and in the upcoming 1.2 release.)

**Comment by jschmid** [comment]
Thanks @snej.

Should I consider this issue solved? I guess it will not crash anymore, but will it return values if it has some?

**Comment by snej** [comment]
The query will still fail in this situation. And your database has some bogus data in the index, which is bad. There have been a bunch of changes to indexing in 1.2; is it feasible for you to update to the latest build ([from here](http://latestbuilds.hq.couchbase.com/couchbase-lite-ios/0.0.0/)) and try to reproduce this?

**Comment by jschmid** [comment]
Thanks for the reply.

I currently have problems with concurrency that I do not handle well. 1.1.0 works fine with it, but 1.1.1 starts to break. This bug might be because of that. 
It am in the process of cleaning my database accesses, and once it's done I will update to 1.2 and try again the search. Thanks Jens

**Comment by jschmid** [comment]
I tried with the nightly build you referenced. It does not crash anymore, and works with keywords that are less than 3 characters.

Thanks!
