### ISSUE TITLE
CBLDatabaseOptions.readOnly is being ignored

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-ios#998]
@borrrden pointed out that the `readOnly` database option doesn't currently do anything — instead the `_readOnly` flag is set at init time based on the CBLManager's readOnly attribute. It should instead be set in the -openWithOptions:error: method.

**Comment by borrrden** [comment]
In the new system, when does the manager's readOnly value come into play?  Will the manager force the CBLDatabaseOptions.readOnly property to true?

**Comment by snej** [comment]
That sounds right — if the manager is read-only, my intuition is that it shouldn't be possible to make changes to any database. So a r/o CBLManager would need to reset that flag in the options before passing it to CBLDatabase.

**Comment by borrrden** [comment]
Cool.  For reference, this is what I ended up doing -> https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Database.cs#L1945

**Comment by snej** [comment]
Fixed on release/1.2 branch.

I also fixed a number of problems where a r/o database could do things it wasn't supposed to — see the commit message for details.
